- CONTRIBUTING.md
- README.md
- community/README.md
* Add contribution guidelines
* Updates readme with slack and SIG list
* Migrates available SIG missions
* Adds community meeting as basic example
Ping @sarahnovotny @spiffxp
> Added base structure with example

- sig-openstack/SIG-members.md
As GitHub doesn't allow to view the list of team members within an organization for the users, who are not the members of the organization, this list has been created to be viewable by everyone.
> Created list of the OpenStack SIG team members.

- community/fixit201606.md
I think the last link is supposed to be to the zoom community meeting directly.
Also formatted the paragraph so it's not a giant blob.
> replace calendar link with zoom link

- incubator.md
Kubernetes charts is closely tied to kubernetes/helm which not moving out of the kubernetes org.  Therefore, leave kubernetes/charts in place too.
> kubernetes/charts to incubate but not move.

- sig-service-catalog/README.md
Update the sig-service-catalog agenda link to a publicly viewable one.
> Update sig-service-catalog meeting agenda link

- incubator.md
Fixing a couple headings.  This always happens when a gdoc exits the chrysalis and becomes a markdown doc.
> Fix headings in incubator doc

- incubator.md
The code inside of `kubernetes/contrib/mesos` should get promoted to its own repository.  It is built on top of Kubernetes, but it adapts those concepts for use as a mesos framework.  It is distinct from the core Kubernetes code base.
We've discussed the idea in https://github.com/kubernetes/kubernetes/issues/33283 and since it's already part of the Kubernetes source tree, we have an existing OWNERS file to use to prime the new repo.
@k82cn @smarterclayton @thockin
> move kube-mesos-framework to incubator project

- sig-cli/README.md
SIG CLI basic info with links to the needed resources. @pwittrock @AdoHe let me know if you want to tweak anything.
> Adding SIG CLI info

- sig-aws/README.md
No starting Friday was given in the docs.
There is a potential error case here for situations with 5 Fridays in a month, but that's probably irrelevant right now.
> Clarify on *which* Fridays sig-aws meets

- project-managers/README.md
With regards to the agreement, this PR updates the team naming from "Project Managers" to "PM".
> Update README with updated naming of PM group

- contributors/design-proposals/hpa-v2.md
This proposal introduces a redesigned Horizontal Pod Autoscaler,
designed to better allow scaling based on multiple metrics, and scaling
based on arbitrary metrics.
(moved from kubernetes/kubernetes#34754)
> Proposal: Horizontal Pod Autoscaler Version 2

- contributors/devel/development.md
`devel/development.md` change pulled out of https://github.com/kubernetes/kubernetes/pull/36964. It should probably merge after that one.
> No need to go get go-bindata

- contributors/devel/scheduler.md
Delete the content about priorities.go.
I have a same  PR [#37542](https://github.com/kubernetes/kubernetes/pull/37542)  in kubernetes/kubernetes  , but the k8s-merge-robot put a do-not-merge label .
So , I put the PR here.
Thanks.
> Delete the content about priorities.go

- contributors/devel/client-libraries.md
Client is in development and soon to be released out of alpha, but it is supported. I would like to add it to this list so it gets more attraction.
I also want this to be updated at main kubernetes repo, how does that work from this repo to main repo? ref: kubernetes/kubernetes#37719
> Add client-python to supported clients

- contributors/devel/container-runtime-interface.md
Fix the link of cri protobuf API.
cc @yujuhong
> Fix links of cri protobuf API

- CLA.md
I added a reference link to https://github.com/cncf/cla for those looking to review the CLA text in advance of going through the signing process.
> Add link to CNCF CLA text for reviewers

- sig-openstack/README.md
Introduce basic premise of sig-openstack, add links to open issues and
pull requests. Remove IRC channel as it is not a primary mechanism of
communication for the group at this point, the main avenue for IM is
slack.kubernetes.com.
> Expand sig-openstack README.md

- contributors/design-proposals/propagation.md
Move from https://github.com/kubernetes/kubernetes/pull/37276
What this PR does / why we need it:
Add a design doc about HostPath volume propagation
Special notes for your reviewer:
As discussed in https://github.com/kubernetes/kubernetes/pull/31504, I created a document about our use cases and our alternative implementations.
> add document about HostPath volume propagation mode

- contributors/devel/running-locally.md
From kubernetes/kubernetes#38726.
Deletes the unused var `KUBE_DNS_REPLICAS` from `running-locally.md`.
@thockin
> Removes unused KUBE_DNS_REPLICAS var

- governance.md
I've observed lots of questions regarding roles and their meanings, this PR formalizes currently assumed roles in Kubernetes
cc @bgrant0607
> governance: include contributor roles inside the organization

- contributors/devel/scheduler.md
This is to update scheduler.md to make it easier for new dev to understand:
- extend "exploring the code" section and put it before "scheduling algorithm"
- update the scheduling algorithm diagram. The previous one is really confusing.
> devel/scheduler: update intro and scheduling algo

- contributors/devel/scheduler.md
Minor update on "predicates and priorities policies" section.
Also move it from "extensibility" to "algorithm" section because we only needs to talk about how to modify it in "ext" section.
> scheduler.md: update policy section

- contributors/design-proposals/bootstrap-discovery.md
This is https://github.com/kubernetes/kubernetes/pull/30707 ported over to the community repo.
This has been discussed at length and has been LGTM'd.
/cc (from other issue) @dgoodwin @timothysc @errordeveloper @liggitt @smarterclayton @pires
> A proposal for bootstrap discovery.

- contributors/devel/kubectl-conventions.md
Adds information about how the kubectl factory is structured.
@kubernetes/sig-cli @fabianofranz
> add kubectl factory conventions

- contributors/design-proposals/daemon.md
Corrects DaemonSet design doc including an example which would not validate.
`spec.template.spec.containers` was type `map` instead of type an `array`.
> Corrected DaemonSet example

- contributors/design-proposals/optional-configmap.md
> Initial optional configmap proposal

- contributors/design-proposals/service-external-name.md
`type` and `externalName` are child elements of `spec`.
> Fix YAML indentation

- contributors/devel/instrumentation.md
This extends a simple quick start guide by links to reference documentation and reiterations of the most important points to hopefully unify the instrumentation approach across components over time.
The contents were discussed in the last @kubernetes/sig-instrumentation-misc meeting and decided to be added in here.
> Update metric instrumentation guide

- README.md
- sig-creation-procedure.md
Following up the discussion, initiated at https://groups.google.com/forum/#!topic/kubernetes-dev/LEtIxeG0i84 and https://github.com/kubernetes/community/pull/90, this procedure describes the process of creating the new SIG (as well as optimizing the existing ones) within the Kubernetes community.
These steps were performed and reproduced for the newly created SIG-OnPrem, existing SIG’s should be updated via this procedure as well.
> The new SIG creation procedure

- contributors/devel/README.md
these links are broken caused migration which was described in issue: #134 #235
some were fixed already, but some are not in the README.md
fixed the remains broken links
> fix broken links

- sig-storage/contributing.md
Fixes link now that labels have been updated. Could someone from @kubernetes/sig-storage-misc please take a look. Thanks!
> Update issue query for SIG Storage

- contributors/design-proposals/node-allocatable.md
The link to `KubeReserved` should be `#kube-reserved`.
Replace https://github.com/kubernetes/kubernetes/pull/38425 and will close that one.
cc @michelleN . Thanks!
> Fix incorrect link

- contributors/devel/README.md
- resolves resolves #235
- Update README doc links to new doc location that's migrated from
community github repo
> Fix broken developer doc links in README

- contributors/devel/kubemark-guide.md
Ref [issue#38967](https://github.com/kubernetes/kubernetes/issues/38967) on @wojtek-t 's comment to update kubemark documentation.
In the light of recent design changes in Kubemark ([moving master components to pods](https://github.com/kubernetes/kubernetes/commit/0a0294c), [migration of the master from Debian to GCI](https://github.com/kubernetes/kubernetes/commit/8e888a767), [addition of hollow-node-problem-detector to hollow-nodes](https://github.com/kubernetes/kubernetes/commit/f9707a7), [refactoring kubemark code to be provider-independent](https://github.com/kubernetes/kubernetes/pull/39033) and the future roadmap we discussed for kubemark w.r.t becoming more reliable in mirroring real clusters to help with our scalability goals), some changes have been made to the Kubemark design …
> Improved kubemark-guide to reflect recent changes

- contributors/design-proposals/kubelet-rootfs-distribution.md
After discussion with @philips and @vishh we settled on running the Kubelet in a chroot as being a fairly sane way to solve the problem of mount utility availability (among a couple others).
This proposal outlines a few more details of that idea and provides some alternatives.
Related issues: https://issues.k8s.io/19765, https://issues.k8s.io/16508, https://issues.k8s.io/35224, https://issues.k8s.io/35249 and others I'm sure.
cc @vishh @philips
-------
Moved from https://github.com/kubernetes/kubernetes/pull/35328 due to repo reorgianization, some context remains there.
> proposals: add proposal for a chrooted kubelet

- sig-openstack/README.md
As we closed out 2016 we ran a poll to select new meeting times for the
coming year. As discussed in the last meeting there was no clear winner
in the results but there were a handful of slots in particular that came
up as "least bad".
In the hope of encouraging participation from those who have not been able
to attend in the past we are going to trial running a 1500 UTC meeting time,
alternating with our traditional 2100 UTC meeting time. Meetings remain
only every second week for now.
> Update SIG OpenStack Meeting times for 2017

- contributors/devel/e2e-tests.md
Added a new [Volume] label as part of [PR 39171](https://github.com/kubernetes/kubernetes/pull/39171).
cc @kubernetes/sig-testing-misc
> Update e2e doc to add [Volume] label.

- contributors/devel/adding-an-APIGroup.md
This is some small updates that are complete as it is. I can turn it into a long running WIP, but I'd rather we focus on small incremental additions for now.
@pmorie @deads2k @lavalamp Is `apis/authentication` still a good base to template off of for newcomers?
> Api doc update

- contributors/devel/development.md
Follow up on https://github.com/kubernetes/kubernetes/issues/28960
Also for example in https://github.com/kubernetes/kubernetes/pull/36020 http.ErrUseLastResponse is used which was introduced in go 1.7.
> go 1.7 is now required - updating the docs

- contributors/design-proposals/core-metrics-pipeline.md
Addresses @piosz's comments on #252.
The only comment I did not address is: "Cumulative cpu usage needs to be accompanied with time window from which it was collected."
It may make sense to add the start time to the endpoint.  This would give the full time window as the "end time" is the timestamp.
I plan to omit the start time for now, as it isnt really a "metric", since it is constant.
Other than computing the long-term average cpu usage, I also dont see a use for the start time.  Comparing two sequential sets of metrics would produce a short term usage rate over the time period between the two metrics.  @vishh had expressed a desire to include this short-term rate in addition to the long term total in the endpoint as well.
Regardless, I think this is something that should be addressed …
> Core Metrics changes

- contributors/design-proposals/self-hosted-kubernetes.md
Recently, the optional self-hosted deployment was merged into kubeadm. Although it still requires more work and verification, it is currently merged.
See https://github.com/kubernetes/kubernetes/pull/40075
> Corrected state of kubeadm self-host deployment

- contributors/design-proposals/kubelet-rootfs-distribution.md
- contributors/design-proposals/propagation.md
CoreOS Linux was renamed to CoreOS Container Linux. Make it consistent
in a couple of design proposals.
https://coreos.com/os/docs/latest/
cc @euank
> contributors: rename CoreOS -> CoreOS Container Linux

- contributors/design-proposals/custom-metrics-api.md
This proposal details the custom metrics API as proposed in the new
monitoring vision. It is designed for use with the HPA, but should be
generally useful for controllers that wish to consumer custom metrics.
(transferred from kubernetes/kubernetes#34586)
> Proposal: Introduce Custom Metrics API

- sig-openstack/README.md
Add shared link for sig-openstack meeting minutes, the old link does not
include share information which means it's not viewable for folks who
haven't already been granted access.
> Add shared link for sig-openstack meeting minutes

- contributors/devel/e2e-tests.md
- contributors/devel/node-performance-testing.md
ref https://github.com/kubernetes/test-infra/issues/1475 https://github.com/kubernetes/kubernetes/pull/4123 
Switch `go run hack/e2e.go` to `go run hack/e2e.go --`
Add section describing updater flags (`--get` and `--old`)
> Add -- flag in hack/e2e.go documentation

- contributors/devel/api-conventions.md
Pretty much what it sounds like - these links have been allowed to rot.
> Fix numerous broken links in API conventions doc

- contributors/devel/community-expectations.md
A simple fix to change the broken link to a link to the part of the governance file that refers to the code of conduct.
> Fix links to code of conduct

- sig-pm/README.md
Typo wasn't fixed in 3 reviews.
Now fixed in additional commit.
> Fix typo in sig-pm README

- contributors/devel/testing.md
`make test WHAT` as documented in these docs don't work anymore and must be invoked with full path. it throws error:
```
kipped k8s.io/kubernetes/cmd/libs/go2idl/generator
skipped k8s.io/kubernetes/vendor/k8s.io/client-go/1.4/rest
can't load package: package pkg/kubectl: cannot find package "pkg/kubectl" in any of:
/data/go/src/pkg/kubectl (from $GOROOT)
/home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/pkg/kubectl (from $GOPATH)
can't load package: package pkg/kubectl: cannot find package "pkg/kubectl" in any of:
/data/go/src/pkg/kubectl (from $GOROOT)
/home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/pkg/kubectl (from $GOPATH)
```
This PR fixes it.
> make test with WHAT arguments changed

- contributors/devel/cherry-picks.md
- contributors/devel/pull-requests.md
Couple of links in docs still referencing relative path to kubernetes github. 
This makes "PR Template" links not working in these links -  https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#release-notes  and https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md#propose-a-cherry-pick
fixes #362
> Fix the relative path to kubernetes in doc

- contributors/devel/api_changes.md
reading this doc, it says `two files` and lists four files. As far as I understand it, we should prefer to use examples from `pkg/apis/`.
I adjusted the example to have the matching name in the repo.
I also adjusted the formatting so the text is all at the same level.
> only list two files

- contributors/devel/scheduler.md
404 Error because file was moved from plugin/pkg/scheduler/generic_scheduler.go to plugin/pkg/scheduler/core/generic_scheduler.go
change was made correspond to that change
> Fixed broken link to generic_scheduler.go

- contributors/devel/e2e-node-tests.md
`--disable-kubenet` has been removed and replaced with `--kubelet-flags` in node e2e tests.
cc @Random-Liu @yujuhong
> Correct kubenet config on node e2e tests

- contributors/design-proposals/README.md
1.`multi-cluster.md` link navigate a incorrect link. It seems to be at another doc repo [kubernetes.github.io](https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/multi-cluster.md) 
but i think we should use the [link](https://kubernetes.io/docs/admin/multi-cluster/) , i am not sure :)
2.Obviously, the path `../proposals/federation.md` is incorrect. Should be use `federation.md` directly.
> fix the obvious link error

- contributors/devel/e2e-node-tests.md
- contributors/devel/e2e-tests.md
- contributors/devel/node-performance-testing.md
- contributors/devel/writing-good-e2e-tests.md
Fix error links in test docs:
* [e2e-tests.md](https://github.com/kubernetes/community/tree/master/contributors/devel/e2e-tests.md)
* [e2e-node-tests.md](https://github.com/kubernetes/community/tree/master/contributors/devel/e2e-node-tests.md)
* [writing-good-e2e-tests.md](https://github.com/kubernetes/community/tree/master/contributors/devel/writing-good-e2e-tests.md)
* [node-performance-testing.md](https://github.com/kubernetes/community/tree/master/contributors/devel/node-performance-testing.md)
> fix error links in test docs

- sig-openstack/README.md
After discussion in the kubernetes-sig-openstack group, this
patch clarifies the mission of sig-openstack to cover all
interactions between the Kubernetes and OpenStack communities. 
Issue #376 
https://groups.google.com/forum/#!topic/kubernetes-sig-openstack/yTjt2_kJb4o
> Clarify the sig-openstack mission statement

- contributors/design-proposals/mount-options.md
Adding initial proposal for mount options. 
CC @saad-ali @matchstick @rootfs
> Add proposal for mount options

- contributors/design-proposals/bootstrap-discovery.md
Signed-off-by: Joe Beda <joe.github@bedafamily.com>
> Update bootstrap design doc with kubeadm UX

- contributors/devel/development.md
* Added etcd installation instructions ptr
(cannot run integ tests w/o it).
* Moved pre-commit hook installation instructions from development
loop to git clone section (one time setup shouldn't be in dev loop).
* Ditto for "setting upstream remote to no_push".
* Gathered Go install/upgrade discussion to one section.
(instead of having it split up by the 'build' section)
* Put build/test instructions between checkout and commit.
This puts them in the development loop.
Formerly, build was up before fork (odd), and test was
tacked at end of doc.
* Removed unnecessary mercurial instructions
(install works w/o mercurial).
* Brought text into sync with the Workflow fig:
* Assured 1:1 correspondence between numbered figure steps
and numbered section headers - had no numbers before.
* Used …
> Fix development instructions.

- contributors/design-proposals/pod-preset.md
from https://github.com/kubernetes/community/pull/254#issuecomment-282050817
we also need to decide on the api group
ping @pmorie @erictune @bgrant0607
> rename pod injection 

- contributors/design-proposals/cloud-provider-refactoring.md
@thockin @luxas @roberthbailey @chrislovecnm @liggitt @saad-ali @erictune 
This PR is a copy of the rectified contents of this PR - https://github.com/kubernetes/kubernetes/pull/37037
PTAL
> Proposal for refactoring cloud provider API

- contributors/devel/community-expectations.md
I think, based on logic in contributors criteria sentence should "five" word in it
> corrected # of pull requests

- contributors/design-proposals/pod-resource-management.md
Update the documentation for pod resource management based on current plan.
Document a rollout plan and tentative timeline for enabling the feature.
> Update pod resource management design and rollout plan

- contributors/design-proposals/add-new-patchStrategy-to-clear-fields-not-present-in-patch.md
Move from issue #229.
@kubernetes/sig-api-machinery-misc @kubernetes/sig-cli-misc
> Proposal: Add Tag Indicating To Replace Union Fields in Patch

- contributors/devel/security-release-process.md
After the v1.4.3 release I know we are all thinking about the security
disclosure and response plan for Kubernetes. I think we need to document some
internal processes, external communication templates/process, and improve the
disclosure systems.
This document is based on discussion and a Google doc on SIG Auth:
https://groups.google.com/forum/#!topic/kubernetes-sig-auth/Xq2f8bWCNDM
**Known issues**
- We haven't specified a way to cycle the Product Security Team; but we need
this process deployed quickly as our current process isn't working. I will put
a deadline of March 1st 2017 to sort that.
Tracking issue: https://github.com/kubernetes/kubernetes/issues/35462
> docs: devel: add security release process

- contributors/design-proposals/federation-clusterselector.md
This a proposal for enabling selector based control over placement of federated resources using a similar structure as the [NodeSelector object](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L1798) and nodeAffinity matching rules.
ref: kubernetes/kubernetes#29887
/cc @nikhiljindal
> Federation: cluster selector based placement proposal

- communication.md
Links were to past conferences. Updated link will stay up-to-date.
> Update KubeCon links

- contributors/devel/e2e-tests.md
Fix some bash parameter mismatches.
Also pulled test re-compilation detail out of `Federation e2e tests` section to it's own section.
> Update e2e docs

- sig-api-machinery/api-extensions-position-statement.md
Previously this existed in a google doc here: https://docs.google.com/document/d/1lU1SnVtEec2iIfYx5U3L5N0za2YhfEOik0uPen276Ks/edit# .  This pull just moves to a public repo to ease sharing and referencing.
No edits other markdown formatting.
@kubernetes/sig-api-machinery-misc @lavalamp @smarterclayton
> move sig-api-machinery api extensions position to community

- contributors/design-proposals/aggregated-api-servers.md
The aggregator will be embedded into the `kube-apiserver` during 1.7.  This updates our aggregated-apiserver doc to match our intent from https://docs.google.com/document/d/1lU1SnVtEec2iIfYx5U3L5N0za2YhfEOik0uPen276Ks/edit#
@kubernetes/sig-api-machinery-misc
> embed aggregator inside of the kube-apiserver

- sig-contribx/README.md
I am in the 2017 KubeCon Berlin. We are talking about contribution
and that lead me to this page. I noticed the page does not render
in markdown correctly when looking at it in a browser:
https://github.com/mbruzek/community/tree/master/sig-contribx
> Fixing the sig-contribx/README.md markdown.

- contributors/devel/cherry-picks.md
The newline was causing Github to not render this as a link.
> Fix cherry-picks link.

- contributors/devel/pull-request-commands.md
This is a knock on to kubernetes/test-infra#2126, with the goal of consolidating the list of bot commands into one file. Also updates the language around approvers slightly.
> Update reference to bot commands

- contributors/devel/development.md
We have a lot of upstream PRs that have optimization goals which can turn into bikeshedding, because they are submitted without data , graphs, etc.  
So I think we should do our contributors a favor and make it easy for them to self review the quality of their performance or architecture improvements before they submit them.
Examples where new contributors need a little more guidance in terms of how to submit a performance optimization:
- https://github.com/kubernetes/kubernetes/issues/43843
- https://github.com/kubernetes/kubernetes/issues/43912
I think we can just point folks to this doc, or something similar, for performance or architecture improvements to make sure they've dont the basic calisthenics necessary for submitting those sorts of patches.
> architecture vs performance improvements guidelines

- contributors/devel/e2e-tests.md
KUBE_MASTER_IP must not contain prefix "http://".
> Fixes KUBE_MASTER_IP in contributors/devel/e2e-tests.md.

- contributors/design-proposals/kubectl-extension.md
From: kubernetes/kubernetes#30086
> Proposal: kubectl extension

- contributors/devel/e2e-tests.md
Document the flag to switch off color in the output logs.
> Add a tip about --ginkgo.noColor

- contributors/design-proposals/federated-placement-policy.md
This a proposal for enabling policy-based control over placement of federated resources (e.g., ReplicaSets).
ref: https://github.com/kubernetes/kubernetes/issues/39982
/cc @quinton-hoole @nikhiljindal
> Proposal: policy-based federated resource placement

- contributors/devel/e2e-tests.md
Add information on how to reproduce failures in flaky e2e tests.
> Add flaky test debugging info to e2e-tests.md

- contributors/design-proposals/aws_under_the_hood.md
I don't think it's the POD that's getting a /24 CIDR but rather the virtual machine itself, a POD has a single address, not a range.
Please close PR if my understanding is incorrect, thanks!
> Update aws_under_the_hood.md to clarify pod vs node instance

- contributors/devel/development.md
Markup was broken because of newline
> Fix markup for link to docker build

- community/2017-events/05-leadership-summit/announcement.md
Publicly announcing leadership summit on the same day as sending invitations to the smaller list of prospective attendees.
> Create announcement.md for public awareness

- sig-scalability/README.md
- sig-scalability/extending_slo.md
Google-doc-made-md - a copy of the doc shared with the community a month ago, thus ready to be made "official". This is the best place we were able to find to put this, but if it there is a better place please let me know. cc @thockin for better idea on where to put this.
@kubernetes/sig-scalability-pr-reviews
> Add Extending SLO docs to sig-scalability

- sig-openstack/README.md
Consolidating on a single meeting time, 1500 UTC Wednesdays.
> Update Kubernetes-SIG-OpenStack Meeting Time

- contributors/design-proposals/aggregated-api-servers.md
This is a trivial patch fixing the typo found in a design-proposal. The typo may cause confusion for readers.
> Trivial: fix typo in aggregated-api-servers proposal

- contributors/devel/flexvolume.md
Updated the links to point to k8s master branch - is this ok or should I use e.g. release-1.6 branch instead?
> Fix yaml links in flexvolume document

- contributors/design-proposals/thirdpartyresources.md
There are a number of important issues with the alpha version of ThirdPartyResources that we wish to address to move TPR to beta. The list is tracked [here](https://github.com/kubernetes/features/issues/95), and also includes feedback from existing Kubernetes ThirdPartyResource users. This proposal covers the steps that are necessary to move TPR to beta and to prevent future challenges in upgrading.
@kubernetes/sig-api-machinery-misc @erictune @lavalamp @brendandburns @philips
> Proposal: TPR to beta proposal

- sig-api-machinery/README.md
Changed "Agenda/Mission doc" name to "Mission Doc". Added meeting agenda & notes link per governance. Removed Hangouts Link and added Zoom link, as the group has transitioned to Zoom.
> Updated README per governance

- contributors/design-proposals/deployment.md
Alternative proposal to https://github.com/kubernetes/community/pull/384
@kubernetes/sig-apps-api-reviews @kubernetes/api-reviewers
> Refine the Deployment proposal and switch hashing algorithm

- contributors/design-proposals/auditing.md
Re-submitting https://github.com/kubernetes/kubernetes/pull/29443.
First pass at defining more extensible and detailed auditing system for the Kubernetes API.
@sttts @deads2k @roberthbailey @cjcullen @kubernetes/rh-cluster-infra @nikhiljindal fyi, since you all commented/was present on the original PR
> Advanced audit proposal

- sig-pm/SIG PM representatives.md
As discussed in the April 27th SIG Node meeting:
Add Dan Williams as primary sig-net representative and Christopher M
Luciano as the secondary
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
> Add SIG net representatives to PM list

- contributors/devel/generating-clientset.md
The current doc page for generating-clientset shows a broken Analytics link.
Remove duplicated and unformatted text and fix it.
> Fix broken Analytics in generating-clientset

- contributors/devel/api-conventions.md
The highlighting "accessing the cluster docs" just confused me (for a second). imo 'docs' is redundant her. Please ignore and close the PR is this to nit picky.
> Minor tweak

- contributors/devel/godep.md
Work I had to do to get https://github.com/kubernetes/kubernetes/pull/45056 working.
cc @sttts @thockin @caesarxuchao
> contributors/devel: update godeps instructions with required hack scripts

- contributors/devel/e2e-tests.md
The munger config directory has moved to https://github.com/kubernetes/test-infra/tree/master/mungegithub
> Fix munger config broken link:e2e-tests.md

- contributors/design-proposals/hpa-status-conditions.md
This proposal details an extension to the HPA status field that would
add conditions, similar to other Kubernetes objects.
> Proposal: HPA Status Conditions

- contributors/design-proposals/gce-l4-loadbalancer-healthcheck.md
From kubernetes/kubernetes#14661.
I guess it may be better to have this L4 healthcheck feature in-place before promoting ESIPP to GA, just to make sure we won't need to change semantics for OnlyLocal service in future.
@nicksardo @thockin @bowei
> Proposal for GCE L4 load-balancer health check

- contributors/design-proposals/local-storage-overview.md
A note to reviewers: A detailed design proposal will be posted once the overall design in this proposal has been accepted by the community. So kindly hold on to specific design questions or suggestions that are not relevant to the overall high level design for local storage. 
cc @kubernetes/sig-storage-proposals  @kubernetes/sig-node-proposals @kubernetes/sig-apps-proposals @kubernetes/sig-scheduling-proposals 
cc @msau42  
For https://github.com/kubernetes/features/issues/121
TODO:
> [Proposal] Improve Local Storage Management

- contributors/devel/release/README.md
Update links and docs contact for upcoming 1.7 release.
> Update Writing Feature Documentation for 1.7

- contributors/design-proposals/multi-fields-merge-key.md
As @pwittrock suggested, break https://github.com/kubernetes/community/pull/476 to 2 proposals:
- how to support multi-fields merge key (this proposal).
- how change the merge key (this part remains in https://github.com/kubernetes/community/pull/476).
> Proposal: support multi-fields merge key

- contributors/design-proposals/server-get.md
This proposal discusses how the `kubectl get` operation can be moved to the server to allow multiple clients to more easily show simple lists of objects.
Part of https://github.com/kubernetes/kubernetes/issues/12143 and general work under api-machinery.
Depends on:
* https://github.com/kubernetes/community/pull/123
Related to:
* https://github.com/kubernetes/kubernetes/issues/24855
Prototype:
* https://github.com/kubernetes/kubernetes/pull/40848
Some WIP items left, including a sketch of describe to contrast the two approaches.
> Proposal: Server-side `kubectl get`

- contributors/design-proposals/preserve-order-in-strategic-merge-patch.md
Move from https://github.com/kubernetes/community/pull/467, since we want to move strategic merge patch doc out of the api-convention doc. [WIP PR](https://github.com/kubernetes/community/pull/535)
Addressed comments in https://github.com/kubernetes/community/pull/467.
cc: @pwittrock @lavalamp @liggitt @apelisse
> Proposal: preserving order in strategic merge patch

- contributors/design-proposals/admission_control_extension.md
This is a very rough first draft of the proposal for how to make admission control extensible. It covers the reasoning and background at a high level but I'm still pulling together the proposed design (one exists, just not in paper).
Basically, add a new "initialization" phase for resources that is opaque to old clients but controllers can opt in to seeing uninitialized objects - the last initializer makes the object visible to everyone else.  Also, add non-mutating generic webhooks for doing remotable checks against a server (like SubjectAccessReview). Make both of those dynamically configurable via some core API object.
@kubernetes/sig-api-machinery @bgrant0607
> Proposal: Extensible Admission Control

- contributors/design-proposals/kubelet-authorizer.md
Proposal to subdivide kubelet API access to read secrets/configmaps, and to mutate node and pod resources
> Scoped Kubelet API Access

- contributors/devel/api-conventions.md
Document to avoid `IsBla`-type names for boolean properties.
This is extremely consistent throughout our APIs, but not written down.
> Document naming convention for boolean API fields

- contributors/devel/on-call-user-support.md
This will show unanswered questions listed most recently asked order. The
existing links are not helpful as they're sorted by relevance and shows
questions from long time ago.
Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>
> Modify StackOverflow unanswered links to newest questions

- sigs.yaml
Fixing what looks like a copy/paste error (`sig-service-catalog` to `sig-storage`).
Did not run `make all` since the generated files are not yet live.
CC @jamiehannaford
> Correct information about sig-storage leads in sigs.yaml

- contributors/devel/api_changes.md
references to `Semantic.DeepEqual` are outdated. this updates them.
> updates documentation references to Semantic.DeepEqual routine

- contributors/design-proposals/monitoring_architecture.md
federated-api-servers.md has been redirect to aggregated-api-servers.md, correct and update the link.
> correct the link for aggregated api servers

- contributors/devel/scheduler.md
Added missing "core" directory name into the path of
generic_scheduler.go file.
> Correct wrong path for generic_scheduler.go file

- contributors/design-proposals/dynamic-admission-control-configuration.md
A sub-proposal of #132, proposal on Extensible Admission Control.
@smarterclayton @lavalamp @whitlockjc as initial reviewers.
> Design: Dynamic registration of admission controllers and initializers

- sig-governance.md
- sigs.yaml
Changed all deprecated links to sig-pm (now sig-product-management), sig-onprem (now sig-on-premise), and sig-contribx (now sig-contributor-experience), also updated the sigs.yml file to match sig-list
CC: @sarahnovotny
> Fixed broken references to sig-pm, sig-contribx, sig-onprem

- contributors/design-proposals/no-new-privs.md
Carried from #180 by @xingzhou closes #180 
Addresses kubernetes/kubernetes#38417
Addresses comments left on #180 with regard to interactions of `no_new_privs` and other existing linux primitives, including suid binaries.
Changes the proposal to default to `no_new_privs` being enabled, with exceptions documented so suid binaries and existing privileged/cap_sys_admin containers do not break.
It renames the initial proposal to `allowPrivilegeEscalation`
Also if anyone is worried about the whole "defaulting to true" thing, when we turned on seccomp by default in docker, I tested all the public Dockerfiles on github, we can do the same for this.... just to see what breaks ;)
> Add support for `no_new_privs` via allowPrivilegeEscalation

- contributors/devel/development.md
Rewrite the `development.md` document to improve clarity and delete redundant information. Along the way, resolve grammar and spelling issues. Wrap to a semi-uniform line width.
> development.md: rewrite for clarity, grammar, and spelling

- community-membership.md
- Reduce bar for org membership
- Summarize and provide additional descriptions for roles
- Refactor membership doc to explicitly define requirements vs responsibilities and make wording consistent
- Delete a bit of the New contributor role that overlaps with org membership
> Flesh out community membership roles.

- sig-node/README.md
The sig-node document invites users to participate in kubernetes.slack.com Slack group. But as a new user I got stuck trying to login there. This PR therefore provides a link where one should go get the invitation prior trying to use Kubernetes Slack channels.
> Add missing link for new users of kubernetes Slack

- contributors/design-proposals/sig-cli/get-describe-apiserver-extensions.md
…ns for non-compiled in types.
@fabianofranz The sig-service-catalog was going to fork kubectl and compile in custom types for get and describe to work.  I really don't like this solution, and think we could support their needs in a simple way.
Would you be open to discussing this on Wednesday?
sig-service-catalog has agreed to donate the development resources to implement.  @simonleung8
> `kubectl get` and `kubectl describe` extensions

- contributors/devel/development.md
Emphasized that the local repo location is not optional.
Added a pointer to the page about building with Bazel.
Resolves #597
> Updates to development.md wrt Bazel

- contributors/devel/development.md
Since we have `make help`, it would be good to add it in development.md
Ref: https://github.com/kubernetes/kubernetes/issues/46911
/cc @cblecker 
/assign @krzyzacy
> Add "make help"

- sig-service-catalog/README.md
- sigs.yaml
Looks like I missed some previously.
> Remove old references to SIG service catalog leads

- contributors/design-proposals/kubelet-authorizer.md
Updated the node authorization proposal based on implementation feedback:
* Recognition of nodes from userinfo is always strict... unless an incoming request has the `system:nodes` group AND a username in the format `system:node:<nodeName>`, the node authorizer and admission will ignore it
* Authorizer is opt-in as an authorization mode rather than a feature gate
* Admission is opt-in as an admission plugin
* Included PV and PVC objects as subdivided objects
* Added plan for deprecating the `system:nodes` group -> `system:node` role RBAC auto-binding
> Update node authorization proposal

- contributors/design-proposals/sysctl.md
Follow-up of https://github.com/kubernetes/kubernetes/pull/26057. The proposal is implemented (with the limited set of safe sysctls). So this PR is only to preserve the proposal text, as the basis for further work in this direction.
> Add sysctl proposal

- incubator.md
Marking kops as a Kubernetes Community Project, graduating in June of 2017.
> Mark kops as a Kubernetes Community Project

- community-membership.md
- Also have users confirm they have joined kubernetes-dev@googelgroups.com
> Add email template for community-membership requests.

- contributors/design-proposals/pod-preset.md
The new format simply adds a prefix of "podpreset-" to the current
annotation that records what presets have acted on a pod. The new naming
makes it such that there is no chance of collision with the newly
introduced opt-out annotation (or future ones yet to be added).
Opt-out annotation PR:
kubernetes/kubernetes#44965
> Update PodPreset modification annotation format

- contributors/design-proposals/add-new-patchStrategy-to-clear-fields-not-present-in-patch.md
When implementing https://github.com/kubernetes/community/pull/278 (PR is https://github.com/kubernetes/kubernetes/pull/44597),
@pwittrock and I found we can do it more efficiently when patching a list with `replace` patch strategy and still keep backward compatibility.
This is very similar to what we have in https://github.com/kubernetes/community/pull/278.
cc: @liggitt
> improve replaceKeys proposal

- contributors/design-proposals/resource-qos.md
Github appears to render YAML snippets with tabs used for indentation with big red blobs over the whitespace inserted by the tabs (showing that there is a syntax error, apparently). 
Change the indentation to two spaces so that the document displays cleaner when viewing on github.com.
> replace tabs in yaml snippets with spaces

- contributors/devel/instrumentation.md
In case of using two spaces github doesn't treat nested list as a separate numerated list.
> Fix indentation for nested numerated list

- contributors/devel/cri-validation.md
Reference features: https://github.com/kubernetes/features/issues/292.
> Add docs for CRI validation test suites

- generator/app.go
- sig-api-machinery/README.md
- sig-apps/README.md
- sig-auth/README.md
- sig-autoscaling/README.md
- sig-aws/README.md
- sig-azure/README.md
- sig-big-data/README.md
- sig-cli/README.md
- sig-cluster-lifecycle/README.md
- sig-cluster-ops/README.md
- sig-contributor-experience/README.md
- sig-docs/README.md
- sig-federation/README.md
- sig-instrumentation/README.md
- sig-list.md
- sig-network/README.md
- sig-node/README.md
- sig-on-premise/README.md
- sig-openstack/README.md
- sig-product-management/README.md
- sig-scalability/README.md
- sig-scheduling/README.md
- sig-service-catalog/README.md
- sig-storage/README.md
- sig-testing/README.md
- sig-ui/README.md
- sig-windows/README.md
- wg-resource-management/README.md
Timestamps in the sig docs generation create more potential for merge conflicts, as well as touch/modify files that would otherwise not need to be modified when running `make all`.
cc: @jamiehannaford
> Remove timestamp from sig file generation

- contributors/devel/coding-conventions.md
This link is deleted by this:
https://github.com/kubernetes/community/commit/6b42e8126a7e36af4e880c922478f4ab1c066d00#diff-c61d1306839d4aa3fa96ff4bae197585L226
This is a dead link now.
> clean up description about "pre-commit" hook

- contributors/devel/api-conventions.md
Earlier the link redirected to docs in Chinese because of the redirects present here: https://github.com/kubernetes/kubernetes.github.io/blob/master/cn/docs/tutorials/object-management-kubectl/object-management.md.
> Fix link to point to English docs instead of Chinese

- contributors/devel/on-call-build-cop.md
There was some confusion about this in slack, so I've changed the wording to make it clear that the build cop only needs to make sure that they're running, not that they're flake-free.
> Reword build cop duties for batch merges.

- contributors/design-proposals/customresources-validation.md
ThirdPartyResource (TPR) is deprecated and CustomResourceDefinition (CRD) is the successor which solves the fundamental issues of TPRs to form a stable base for further features.
Currently we do not provide validation for CustomResources (CR). This proposal proposes the design and describes a way to add JSON-Schema based validation for CustomResources.
cc @sttts @deads2k @enisoc @xiao-zhou @erictune @lavalamp @brendanburns @philips @fabxc @frankgreco @sdminonne
> Proposal: Validation for CustomResources.

- sigs.yaml
- wg-resource-management/README.md
old URL pointed to youtube recordings rather than Agenda.  Agenda has a link to youtube recordings.  Other SIGs point to their agenda doc in meeting_archive_url
> Correct the resource management working group meeting_archive_url

- contributors/design-proposals/dynamic-kubelet-configuration.md
This moves the proposal PR for dynamic config from the core repo to the community repo. See the original PR for prior discussion: https://github.com/kubernetes/kubernetes/pull/29459.
> Move dynamic config proposal to community repo

- contributors/design-proposals/pod-priority-api.md
@kubernetes/sig-scheduling-api-reviews 
@kubernetes/api-reviewers
> Design proposal for adding priority to Kubernetes API

- contributors/devel/automation.md
Felt as though this should be a markdown link, and there is no history to suggest otherwise.
> fix 'submit-queue' markdown link in automation.md

- contributors/devel/kubectl-conventions.md
After [a discussion](https://github.com/kubernetes/kubernetes/pull/48572#discussion_r126269251) on my PR in kubernetes/kubernetes.
ref: https://github.com/kubernetes/kubernetes/pull/48572#discussion_r126269251
> kubectl-conventions: rename MineConfig -> MineOptions

- contributors/devel/client-libraries.md
This content is now served at https://kubernetes.io/docs/reference/client-libraries/
and removing this page will encourage people to keep the website up to date.
> Move client-libraries.md to kubernetes.io

- contributors/devel/scheduler.md
Removed unused space which break link format.
> Fix wrong link format for predicates.go file

- contributors/devel/godep.md
I'm not sure whether it should be before or after `update-staging-client-go.sh` is invoked.
For the record: found while working on https://github.com/kubernetes/kubernetes/pull/48384
> Add missing update staging godeps command

- sig-auth/README.md
Replace url to report specific vulnerabilities by new url : https://kubernetes.io/security/
Dead link: http://kubernetes.io/v1.1/docs/reporting-security-issues.html
> Replace url to report specific vulnerabilities

- contributors/design-proposals/daemonset-update.md
In summary:
1. Use PodTemplate to store DaemonSet history 
1. Use "pod-template-generation" to label both pods and PodTemplates, so that DaemonSet controller can map a pod to a PodTemplate (history), and than compare PodTemplate with DaemonSet template 
1. Each PodTemplate is a snapshot of DaemonSet template + annotation + templateGeneration at the moment. A DaemonSet can have multiple PodTemplates with the same template (each with a unique pod-template-generation label)
1. Default clean up policy for DaemonSet history is 2. Only PodTemplates with no existing pods map to it can be cleaned up (so that a pod can always be mapped to a PodTemplate). 
1. Rollback will be done server side using RollbackConfig, similar to Deployment 
An alternative is to create a DaemonSetHistory resource, …
> Proposal for DaemonSet history and rollback

- contributors/devel/README.md
- contributors/devel/issues.md
This guideline was initially created and proposed by Sahdev Zala and
Jorge Castro. It has been discussed multiple times in the ContribX
SIG meetings and via emails, and it incorporates all the suggestions. This
PR is created per the latest SIG meeting discussion.
The original open document with little bit more content is available here,
https://docs.google.com/document/d/1dfZGGIsx4QrY8aaC1o2SNmMU6eQKS4xYg55xNLtHDmc/edit
Co-Authored-By: Jorge Castro <jorge@heptio.com>
> Create Issue Triage Guideline

- sigs.yaml
This just removed an extra whitespace that snuck in there.
/cc @xiangpengzhao
> Remove extra whitespace from sig-arch

- contributors/design-proposals/volume-metrics.md
This document adds a proposal for gathering metrics
at operation level for volume operations. This ensures
metrics can be captured regardless of individual volume
plugin implementation.
xref https://github.com/kubernetes/features/issues/349
> Add a proposal for high level volume metrics

- contributors/devel/godep.md
The update-staging-client-go.sh has been removed, and there is no
need to run it.
> Remove a not exist update-staging-client-go.sh

- contributors/design-proposals/hpa-v2.md
when  a link about master metrics API has added,I think the link of custom metrics api is necessary to given.
> add custom metrics API link

- contributors/devel/bazel.md
As per https://github.com/kubernetes/kubernetes/pull/47090, update the doc.
/cc @mikedanese
> Update bazel.md: adding "bazel-test-integration"

- contributors/design-proposals/cpu-manager.md
**Notes for reviewers**
First proposal submitted to the community repo, please advise if something's not right with the format or procedure, etc.
cc @flyingcougar @sjenning @derekwaynecarr
> Add CPU manager proposal.

- contributors/devel/on-call-federation-build-cop.md
fix an obsolete link to federation ci test results
/assign @madhusudancs
> Fix an obsolete link in on-call-federation-build-cop.md

- contributors/design-proposals/bootstrap-discovery.md
@jbeda @mikedanese @justinsb @timothysc @roberthbailey @lukemarsden @liggitt 
A first draft of the v1.7 updates for hopefully bringing Bootstrap Tokens to beta.
Minor changes but important
> Update the token discovery proposal

- contributors/devel/development.md
- make test WHAT=pkg/util/cache GOFLAGS=-v, seems like a typo because with this command it ends up looking for the desired test in $GOROOT/pkg/util/cache and $GOPATH/pkg/util/cache instead of $GOPATH/k8s.io/kubernetes/util/cache. 
- The example package test, /pkg/util/cache doesn't exist anymore. I replaced this package test with another test so that anyone new to running tests for Kubernetes will be able to have a working test instead of feeling confused after following the documentation.
> Update Development Guide - fixed typo for running tests

- contributors/design-proposals/taint-node-by-condition.md
Removed `InodePressure` condition according to https://github.com/kubernetes/kubernetes/pull/50124 .
> Removed InodePressure condition.

- contributors/devel/kubectl-conventions.md
Currently code in `kubectl` for Example strings is not uniform and often does not follow the conventions. This PR updates the conventions to be more descriptive. If this PR is merged I will audit all Example strings in `kubernetes/pkg/kubectl/cmd/*.go` and bring them into line with the conventions. Trivial I know ;)
> Update Example conventions

- contributors/devel/owners.md
`kubernetes/test-infra` pull requests #3766 and #3898 changed the
behavior of the OWNERS process slightly. This patch updates the
documenation to be more up-to-date.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
/cc @spiffxp 
Layers on top of https://github.com/kubernetes/community/pull/873
> Update OWNERS documents to reflect recent changes

- governance.md
Define community groups, as they currently exist, taking some text from the draft Recommended Project Structure document.
> Define community groups

- README.md
It's a better UX to link to help wanted issues and explain what those issues are.  TODO, link to the criteria for help wanted issues.
> Link to Help Wanted Issues Only

- README.md
link Collaboration Guide now points to - collab.md instead of developer.md.
> Updated Readme link Collaboration Guide now points to - collab.md.

- contributors/devel/README.md
- contributors/devel/welcome-to-kubernetes-new-developer-guide.md
Add a new 1-page document targeted to brand new developers. Some of this information is duplicated elsewhere but there is no "onboarding" doc for Kubernetes developers (as far as I could discern).
Review welcome!
@grodrigues3 and @pwittrock have already done a couple rounds of review on this in Google docs.
Thanks!
> contributors/devel: add welcome-to-kubernetes-new-developer-guide.md

- contributors/design-proposals/hugepages.md
A pod may request a number of huge pages.  The `scheduler` is able to place the pod on a node that can satisfy that request.  The `kubelet` advertises an allocatable number of huge pages to support scheduling decisions. A pod may consume hugepages via `hugetlbfs` or `shmget`.  
Planned as Alpha for Kubernetes 1.8 release.
See feature: https://github.com/kubernetes/features/issues/275
@kubernetes/sig-scheduling-feature-requests
@kubernetes/sig-scheduling-misc
@kubernetes/sig-node-proposals
@kubernetes/api-approvers
@kubernetes/api-reviewers
> HugePages proposal

- contributors/devel/godep.md
If we don't recreate the `vendor/BUILD` file after deleting it, then the `all-srcs` rule in the root `BUILD.bazel` file will get updated for all changes to `vendor/`, which we definitely do not want.
/assign @nicksardo
> Update godep instructions to recreate vendor/BUILD file

- contributors/design-proposals/mount-options.md
Also add support for specifying mount options
in storage classes.
cc @kubernetes/sig-storage-api-reviews @liggitt
> Proposal for taking mount option to GA

- contributors/devel/e2e-tests.md
Since 07c6da22fe9f97ab44a02e67a7c574b49998605d, KUBERNETES_PROVIDER
has been deprecated. So this PR replaces KUBERNETES_PROVIDER with
the option --provider to specify a provider on e2e test.
> Replace KUBERNETES_PROVIDER with --provider

- contributors/devel/e2e-tests.md
e2e test finds a suitable util.sh from "--provider" option.
However the e2e test way of community repo didn't show the setting of
the option and the gce's util.sh was selected as the default.
This patch fixes it.
> Specify --provider option on local e2e test

- contributors/devel/e2e-tests.md
Elaborate on how to use `e2e.test` to run ginkgo tests locally.
> Add more information for e2e testing framework

- contributors/devel/flexvolume.md
The following PR introduces a FlexVolume API change, so the documentation needs to be updated.
https://github.com/kubernetes/kubernetes/pull/47503
> Updating FlexVolume doc with capabilities addition.

- community/2017-events/05-leadership-summit/announcement.md
Updated the Kubernetes Developer's Summit for 2016 to point correctly
> Fixed the broken link

- contributors/design-proposals/flexvolume-deployment.md
This lays out the design for the improved deployment story of Flexvolume, making it easier to work with out-of-tree volume plugins before CSI comes to fruition.
> Dynamic Flexvolume plugin discovery proposal.

- contributors/design-proposals/propagation.md
The proposal won't work as it was merged, it makes too many directories as shared (see #648).
A different approach is needed, I've chosen 'Add an option in VolumeMount API', but I would be fine also with 'Add an option in HostPathVolumeSource', there is only very small difference to me.
The proposal also describes how it will be implemented, especially during alpha phase.
Fixes #648
@kubernetes/sig-node-proposals @kubernetes/sig-storage-proposals
> Redesign mount propagation

- contributors/design-proposals/OWNERS
Can I get a few sig leads to propose reasonable reviewers for blunderbuss to use when assigning PRs in this dir?
I started with the top level [OWNERS](https://github.com/kubernetes/kubernetes/blob/master/OWNERS) from k/k.
If you make comment's with github handle's that should be included, I'll add them to the list of reviewers.
**NOTE** - Approvers isn't turned on yet in this repo so adding LGTM (anyone in the org can do this) will put the PR in the queue to be merged.  Being a reviewer just means you can be auto-assigned to design-proposals reviews.
> add design proposals owners

- contributors/devel/development.md
Well, against merge commits, to be more accurate.
> add guidelines for merge commits

- contributors/design-proposals/kubectl-create-from-env-file.md
> fix bad url in kubectl-create-from-env-file.md

- contributors/devel/api_changes.md
Summarizing outcome of discussions with @kubernetes/sig-api-machinery-misc 
ref:
* https://docs.google.com/document/d/1wuoSqHkeT51mQQ7dIFhUKrdi3-1wbKrNWeIL4cKb9zU/edit#
* https://github.com/kubernetes/kubernetes/issues/34508#issuecomment-319412303
* https://www.youtube.com/watch?v=bzSK00TxEx0&list=PL69nYSiGNLP21oW3hbLyjjj4XhrwKxH2R&index=4&t=2580 (43:00-59:00)
* https://github.com/kubernetes/kubernetes/issues/30819
> Update alpha field guidance

- contributors/design-proposals/flex-volumes-drivers-psp.md
This PR proposes to add the `AllowedFlexVolumes` to a PSP to control pod's access to the different Flexvolume drivers.
PTAL @smarterclayton @pweil- @mfojtik
> [Proposal] Allow a Pod Security Policy to managing access to the Flexvolumes

- contributors/devel/flexvolume.md
Based on discussion on kubernetes-sig-storage:
Some drivers implemented getvolume, some didn't[4]. Is it expected to be a name of an existing volume on the storage? Can nodename+volumename be considered unique?
[Chakri] GetVolumeName is not supported and is ignored. You don’t have to implement it.
[4] https://github.com/kubernetes/kubernetes/commit/7885aaf6896d66a69658a9f55cd6063488ad3e06
> Remove getvolume, as it is not supported and ignored

- contributors/design-proposals/kubelet-eviction.md
Previously, I introduced a number of possible methods for introducing priority: https://github.com/kubernetes/community/pull/846.
We came to agreement on using the strategy:
This solution provides users with a clear path to avoiding evictions. It prevents abuse by high-priority pods by not allowing them to disrupt other pods that are below, or near their requests.  Using a function provides a more nuanced approach to allowing pods to consume "unused" (not requested) memory on the node.  Power users, or cluster administrators can determine how unused memory is allocated to pods by choosing priority levels for pods that are closer for more equal sharing of extra memory, or further apart to give better availability to higher priority pods.  For pods that have equal priority, the function is …
> Modify Eviction Strategy to take Priority into account

- contributors/design-proposals/job.md
This update addresses problems raised in https://github.com/kubernetes/kubernetes/issues/30243 and https://github.com/kubernetes/kubernetes/issues/43964.
@erictune I've mentioned this to you during last sig-apps, ptal
@kubernetes/sig-apps-feature-requests ptal
@lukasheinrich @nickschuch @Yancey1989 @sstarcher @maximz fyi since you all were interested in this
> Backoff policy and failed pod limit

- contributors/design-proposals/grow-volume-size.md
cc @kubernetes/sig-storage-pr-reviews @liggitt @eparis
> Proposal for growing persistent volumes

- contributors/design-proposals/api-chunking.md
In order to reduce the memory allocation impact of very large LIST operations against the Kubernetes apiserver, it should be possible to receive a single large resource list as many individual page requests to the server.
Part of kubernetes/features#365. Taken from kubernetes/kubernetes#49338. Original discussion in kubernetes/kubernetes#2349
> Design for consistent API chunking in Kubernetes

- contributors/design-proposals/volume_stats_pvc_ref.md
Flushes out details for part 1 of the changes described in
[#855](https://github.com/kubernetes/community/pull/855)
Feature: [#363](https://github.com/kubernetes/features/issues/363)
> Proposal for adding PVC info to VolumeStats

- contributors/devel/cherry-picks.md
- contributors/devel/pull-requests.md
New labels are being used to signify that a PR should not be merged if
it's got a missing release note and/or requires a release note.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
/cc @spxtr @fejta @xiangpengzhao
> Update doc for release note and cherry pick labels

- contributors/design-proposals/apiserver-count-fix.md
This is a proposal to fix the apiserver-count issue at https://github.com/kubernetes/kubernetes/issues/22609. I would appreciate a review on the proposal.
> add apiserver-count fix proposal

- contributors/design-proposals/admission_control_event_rate_limit.md
This is a proposal for adding an admission control that allows the user to limit the rate of events accepted by an API Server. The limits can be set per-server, per-namespace, per-user, and per-source+object.
> Admission control to limit events accepted by an API Server

- contributors/devel/generating-clientset.md
This depends on: https://github.com/kubernetes/kubernetes/pull/51638 for the `// +genclient:method`.
Fixes the syntax of the generator after https://github.com/kubernetes/kubernetes/pull/49192
> list supported genclient tags and fix the format of the genclient tag

- community/elections/2017/README.md
Rather than saying that the committee does not endorse any
of the candidates, which means something rather different!
Also remove the term "current bootstrap committee" - the future
committee is the steering committee.
> Include the non-electioneering commitment

- contributors/devel/e2e-tests.md
The flag does not work anymore as per https://github.com/kubernetes/kubernetes/issues/45947
> Removing prom-push-gateway flag

- community/elections/2017/README.md
* Don't impose a naming policy on people
* Candidates were not asked at the same time to provide bios, so avoid
statements that could give the wrong impression.
> Election: Amend bio links statement

- governance.md
- sig-architecture/charter.md
Looks like principles.md and architecture.md, moved into the subdirectory architecture a few weeks ago. The links no longer work.
This PR fixes the links to these documents.
> Fixed links to architecture.md and principles.md

- contributors/design-proposals/runas-groupid.md
Allows specifying the Primary Group ID of the container, in addition to Primary User Id when running in Docker similar to how docker supports this.
> Allow specifying the primary group id of the container

- sig-cli/README.md
- sigs.yaml
Previously some random video was playing on clicking the hyperlink for meeting recordings.
> Fix sig-cli meeting recordings url

- contributors/devel/automation.md
- contributors/devel/pull-requests.md
fixes: #834 
/cc @bgrant0607 @spiffxp
> Update Development Automation and Pull Request Process

- contributors/design-proposals/auth/apparmor.md
- contributors/design-proposals/auth/pod-security-policy.md
- contributors/design-proposals/auth/runas-groupid.md
- contributors/design-proposals/dir_struct.txt
- contributors/design-proposals/node/sysctl.md
It's counter intuitive that proposal about PSP has name `security-context-constraints.md`.
@pweil- Do you have objections against renaming a file?
CC @simo5
> Rename security-context-constraints.md to pod-security-policy.md

- contributors/devel/automation.md
fixes: https://github.com/kubernetes/community/pull/1016#issuecomment-330992673
/cc @spiffxp
> Update merge requirements in doc

- contributors/design-proposals/architecture/kubernetes-enhancement-proposal-process.md
I'm opening this up to have a discussion on what the relationship between a KEP and the release note process is.  I see KEPs being most useful for things that will often span releases.  I *want* us to think bigger and across multiple releases.  Often times a KEP will be discussed and accepted before and outside of the release cycle.
I've also moved some stuff around so that this doc stands more on its own vs. being a "delta" on our current process.  In a years time this will be our current process and this won't read as clearly.
> Clarify relationship of KEP to release note process

- Makefile
- generator/README.md
- generator/app.go
Having to set two different variables is confusing. Changed this to look at the `WHAT` envvar and match on a suffix.
Fixes #1126.
cc: @jamiehannaford
> Update generator to use WHAT variable

- incubator.md
kube-state-metrics is active once again (it became active soon after the first commit to this file when it was proposed to be retired). It seems to be the only popular tool that does what it does.
Decision to retire md-check was taken in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/0FcCGNtnxE0/JmQfETD0AwAJ
> Don't retire kube-state-metrics. Retire md-check.

- contributors/design-proposals/sig-storage/volume-topology-scheduling.md
- contributors/design-proposals/storage/volume-topology-scheduling.md
Proposal for a smarter scheduler that influences PV binding.
Part of kubernetes/features#121
/sig storage
/sig scheduling
/cc @kubernetes/sig-storage-proposals @kubernetes/sig-scheduling-proposals
> Volume topology aware scheduling design

- community/elections/README.md
This adds the process we used to run the steering committee election to the community directory so we can refer to it for the election next year.
> Initial commit of the election process

- contributors/design-proposals/node/kubelet-eviction.md
After discussion with @dchen1107 and @bsalamat I think it would be simpler to start with a tiered eviction sorting rather than by using a function.  See https://github.com/kubernetes/community/pull/846#pullrequestreview-66920328 for some of the rationale.
This PR makes two changes:
1. Changes the release at which changes take effect to 1.9 (since implementation missed 1.8)
2. Changes the strategy from (usage > requests, func(priority, usage - requests)) to (usage > requests, priority, usage - requests)
cc @dchen1107 @derekwaynecarr @vishh
> Update priority eviction docs

- contributors/design-proposals/api-machinery/apiserver-build-in-admission-plugins.md
- contributors/design-proposals/api-machinery/dynamic-admission-control-configuration.md
- contributors/design-proposals/auth/pod-security-policy.md
- contributors/design-proposals/cloud-provider/cloudprovider-storage-metrics.md
- contributors/design-proposals/instrumentation/core-metrics-pipeline.md
- contributors/design-proposals/instrumentation/metrics-server.md
- contributors/design-proposals/storage/volume-metrics.md
- contributors/devel/README.md
- contributors/devel/cri-container-stats.md
Some links broke when design proposals were organized in https://github.com/kubernetes/community/pull/1010. They were mostly fixed in https://github.com/kubernetes/community/pull/1116 but a few seem to still be pointing to the old ones.
Takes another stab at https://github.com/kubernetes/community/issues/1109.
/cc @grodrigues3
> Fix links after design proposals move

- wg-container-identity/README.md
Add a link to the agenda to the working group README.
cc @destijl @smarterclayton @liggitt
> update links for container identity working group

- sigs.yaml
- wg-container-identity/README.md
#1167 updated `wg-container-identity/README.md` instead of updating sigs.yaml. This fixes that and regenerates the doc.
> Fix wg-container-identity/README.md

- sig-federation/CONTRIBUTING.md
Inspired from https://github.com/kubernetes/community/blob/master/sig-cli/CONTRIBUTING.md.
Most of the links might be broken at the moment  as sig-federation is renamed to sig-multicluster everywhere.
Will send another PR to rename the parent folder.
cc @csbell @quinton-hoole
> Adding CONTRIBUTING.md for sig-multicluster

- contributors/design-proposals/api-machinery/alternate-api-representations.md
Supports server side handling of transformation of resources.
From kubernetes/kubernetes#33900
> Proposal: Alternate API representations for resources

- contributors/design-proposals/auth/runas-groupid.md
See here https://github.com/kubernetes/community/pull/756
> add author to my proposal for reachability

- contributors/devel/api-conventions.md
Updating description of `deletionTimestamp` as adviced [here](https://github.com/kubernetes/community/pull/1174#discussion_r144286471).
> Update deletionTimestamp with information about finalizer effect.

- .github/PULL_REQUEST_TEMPLATE
- README.md
There still seems to be a few PRs that are unaware of how to generate SIG docs, so this PR hopes to plug that knowledge gap by:
- adding a reference to the README
- adding a PR template that contributors see every time they send a changeset
We might not need the checkbox in the PR template, so I can remove if we feel it should go.
Fixes #1121.
/cc @xiangpengzhao @cblecker
> Clearer generator docs

- generator/README.md
The path of markdown files is incorrect in generator and we maybe use relative path.
> Modify the path of markdown files in generator

- contributors/devel/issues.md
This is my best guess. I'm assuming @spzala did not mean "on its own in
the comment" because then the "at the front" would be superfluous.
> Clarify what "on its own" means.

- contributors/devel/security-release-process.md
cc @philips @cjcullen @tallclair @liggitt
Just some small wording around how things might change if another upstream is involved.
> Security Release: add copy about other upstream timelines

- contributors/devel/on-call-user-support.md
https://github.com/k8s-oncall works
https://github.com/search?q=k8s-support-oncall&type=Users&utf8=%E2%9C%93
shows no matches, and https://github.com/k8s-support-oncall is a 404.
I guess this is another call for #359.
> Fix name and link to k8s oncall.

- contributors/devel/README.md
The target was merged with a different doc which is already linked from
this one.
> Remove a useless link to an empty document.

- contributors/devel/api_changes.md
As per https://github.com/kubernetes/kubernetes/issues/43214 we shouldn't use `extensions` API group. This PR removed suggestions about using it as a starting point for a new API.
PTAL @soltysh 
CC @simo5
> api_changes.md: don't suggest to create API in extensions group

- contributors/devel/testing.md
It is incorrect (rotten) and superfluous: git already keeps track of
when each file is updated.
> Remove "updated" note.

- contributors/devel/automation.md
When a new k8s contributor reads through the developer guide, this
document is the first one which mentions e2e. Expanding the acronym
here helps to keep the learning curve gentle.
> Expand the e2e acronym.

- contributors/devel/api-conventions.md
Documents that taint names should follow the naming conventions for annotations.
ref https://github.com/kubernetes/kubernetes/issues/51246
cc @smarterclayton
> Clarify taint key name convention

- contributors/devel/automation.md
Rather than help, this cryptic reference only brings more confusion to a
newcomer reading this doc as part of the "Developer Guide".
It does not help that the only other occurence of word "mungedocs" in
this repo is in a dead link.
> Remove unhelpful reference to mungedocs.

- contributors/design-proposals/api-machinery/dynamic-admission-control-configuration.md
issue kubernetes/kubernetes#51290, kubernetes/kubernetes#53859
xref PR kubernetes/kubernetes#53879
/cc @ahmetb @gyliu513 @liggitt @smarterclayton @caesarxuchao
> add NamespaceSelector to select namespaces for Initializers

- contributors/devel/development.md
It is incorrect to upgrade Go version for e2e image and test image in development.md
> Correct the upgrading Go version for e2e image and test image

- contributors/design-proposals/network/coredns.md
Add coredns proposal for https://github.com/kubernetes/features/issues/427
> Add coredns proposal

- contributors/design-proposals/predicates-ordering.md
> adding predicate ordering design proposal

- sig-scalability/thresholds.md
Now, the number of max pods per machine is 110: https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/kubelet.md
The goal of max pods per machine is 500: https://github.com/kubernetes/community/blob/master/sig-scalability/goals.md
> Adjust the value of the current and long-term goal.

- sig-cli/CONTRIBUTING.md
Signed-off-by: yuexiao-wang wang.yuexiao@zte.com.cn
Fix some typos  and incorrect links in CONTRIBUTING.md.
The links are dead or incorrect as follows:
[kubectl concept docs]: https://github.com/kubernetes/kubernetes.github.io/tree/master/docs/concepts/tools/kubectl
[design repo]: https://github.com/kubernetes/community/tree/master/contributors/design-proposals/sig-cli
[communication]:  https://github.com/kubernetes/community/tree/master/sig-cli#communication
> Fix  some dead links and some typos

- contributors/design-proposals/storage/postpone-pvc-deletion-if-used-in-a-pod.md
Proposal for postponing deletion of Persistent Volume Claim in case it's used by a pod.
Implementation will fix issue https://github.com/kubernetes/kubernetes/issues/45143
/sig storage
/cc @kubernetes/sig-storage-proposals
> Postpone Deletion of a Persistent Volume Claim in case It Is Used by a Pod

- contributors/devel/api_changes.md
There is no script called `hack/update-codecgen.sh` anymore and the proto files are generated using `hack/update-generated-protobuf.sh`.
> api-changes: update proto script

- contributors/design-proposals/cli/get-describe-apiserver-extensions.md
- contributors/design-proposals/node/container-init.md
`compability` to `compatibility`
`compatibilty` to `compatibility`
> fixed get-describe-apiserver-extensions.md and container-init.md

- contributors/design-proposals/api-machinery/customresources-subresources.md
[CustomResourceDefinitions](https://github.com/kubernetes/community/pull/524) (CRDs) were introduced in 1.7. The objects defined by CRDs are called CustomResources (CRs). Currently, we do not provide subresources for CRs.
However, it is one of the [most requested features](https://github.com/kubernetes/kubernetes/issues/38113) and this proposal seeks to add  `/status` and `/scale` subresources for CustomResources.
cc @sttts @deads2k @enisoc @bgrant0607 @erictune @lavalamp @brendandburns @philips @liggitt @mbohlool @fabxc @adohe @munnerz
> Proposal: SubResources for CustomResources

- contributors/devel/api_changes.md
After renaming `k8s.io/kube-gen` package, the instruction got dated. As far I understand, now we need to modify `hack/update-generated-protobuf-dockerized.sh` script. This PR updates the instruction.
PTAL @sttts 
CC @simo5
> api_changes.md: update place with list of packages for protobuf

- contributors/design-proposals/api-machinery/admission-webhook-bootstrapping.md
Originally distributed as a [google doc](https://docs.google.com/document/d/1pw6FyobY3pVxfWYwmAFuF5WJpvjfq-M3Ciz996kblVc/edit?ts=59f1d824#).
The idea is from an Oct. 23 meeting with lavalamp, cheftako, deads2k, smarterclayton, liggitt. It also draws inspiration from #1191.
cc @kubernetes/sig-api-machinery-api-reviews  @lavalamp @deads2k
> Add a design doc for admission webhook bootstrapping

- contributors/devel/e2e-node-tests.md
Signed-off-by: yanxuean <yan.xuean@zte.com.cn>
The --experimental-cgroups-per-qos  is outdated.
The arg is renamed since 1.6.0.
See 1.6.0 changelog.
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.6.md
Rename --experiemental-cgroups-per-qos to --cgroups-per-qos (#39972,)
> correct the arg of kubelet in test-e2e-node

- contributors/design-proposals/rules-review-api.md
xref https://github.com/kubernetes/features/issues/380
cc @kubernetes/sig-auth-proposals @kubernetes/api-reviewers @xilabao
> rules review API: what can I do?

- contributors/devel/contributor-cheatsheet.md
This started as a list of resources I would check on every day, sort of like a portal page from the 90s meets the kubectl cheat sheet. Then I started to ask around what URLs people use day-to-day and then people asked for a copy, so I figured it wouldn't be a bad thing to share: 
Contrib-ex discussion and proposal: https://groups.google.com/forum/#!topic/kubernetes-wg-contribex/-azSwMpLsZE
I think this still needs a few things to be useful to more people, perhaps someone with front end experience can make it shiny, in the meantime setting it as your new tab page in the browser has been working for me.
> Add a contributor cheatsheet

- contributors/design-proposals/cli/preserve-order-in-strategic-merge-patch.md
I think `convered ` should be `covered `.
> change preserve-order-in-strategic-merge-patch.md

- contributors/design-proposals/resource-management/admission_control_resource_quota.md
**What this PR does:**
1. Update the admission_control_resource_quota.md according to @derekwaynecarr  's PR [Ability to do object count quota for all namespaced resources #54320](https://github.com/kubernetes/kubernetes/pull/54320)
2. fix two nil links
> Update ResourceQuota design doc

- contributors/design-proposals/node/kubelet-eviction.md
After https://github.com/kubernetes/kubernetes/issues/52336, which uncovered a bug in disk accounting, I have struggled to see why ephemeral-storage allocatable evictions are necessary.
For CPU and Memory allocatable, enforcing allocatable through cgroups provides protection from being starved of compute resources by user pods.
However, for ephemeral-storage it seems that the node-level enforcement mechanisms are able to prevent the node from running out of disk, and thus prevent impact to system daemons.
Additionally, memory usage metrics read from cgroups or statfs are far more reliable than an aggregation of `du` calls which may be collected at different times (as https://github.com/kubernetes/kubernetes/issues/52336 demonstrated).
(As a side note, we should read from the /kubepods …
> Remove Disk Allocatable Evictions

- sig-auth/cluster-role-aggregation.md
In order to support easy RBAC integration for CustomResources and Extension
APIServers, we need to have a way for API extenders to add permissions to the
"normal" roles for admin, edit, and view.
A doc form of https://github.com/kubernetes/kubernetes/pull/54005
@kubernetes/sig-auth-feature-requests
> add clusterrole aggregation doc

- contributors/design-proposals/storage/containerized-mounter-pod.md
@kubernetes/sig-storage-proposals  @kubernetes/sig-node-proposals
> Proposal: containerized mount utilities in pods

- contributors/design-proposals/storage/raw-block-pv.md
This PR is an addendum to the #1265 to dictate the behavior of the container runtime for read-only devices as specified in the PVCVolumeSource. The precedence already exists for filesystems thus having a consistent behavior for the user. UC9 was added to illustrate the usage.
> add readOnly use case to raw block device proposal

- contributors/devel/api_changes.md
> Fix api changes doc

- contributors/design-proposals/multicluster/cluster-registry/api-design.md
/assign @quinton-hoole @csbell 
/cc @pmorie @font @ericchiang 
This is a mechanical conversion of the [Cluster Registry API doc](https://docs.google.com/document/d/1Oi9EO3Jwtp69obakl-9YpLkP764GZzsz95XJlX1a960/edit), with a few tweaks to better suit the format and to note the provenance of this document.
Quinton and Christian, I'd like both of you to sign-off on this before I commit. Anyone else is free to chime in if they have concerns, but I believe that we achieved consensus on this doc, and I'd like to formalize that.
> Add the cluster registry API design to the community repo

- contributors/design-proposals/multicluster/cluster-registry/project-design-and-plan.md
/cc @csbell @quinton-hoole 
This is a mechanical conversion of the [Cluster registry project plan doc](https://docs.google.com/document/d/1bVvq9lDIbE-Glyr6GkSGWYkLb2cCNk9bR8LL7Wm-L6g/edit), with a few tweaks to better suit the format and to note the provenance of this document.
Quinton and Christian, I'd like both of you to sign-off on this before I commit. Anyone else is free to chime in if they have concerns, but I believe that we achieved consensus on this doc, and I'd like to formalize that.
@font @pmorie @ericchiang
>  Migrate the cluster registry design and plan to the community repo

- contributors/design-proposals/network/pod-resolv-conf.md
> Add proposal for configurable pod resolv.conf

- contributors/guide/README.md
This is the starting point for creating a single source of truth for how to contribute to Kubernetes.
A follow-up umbrella issue will be filed that contains a list of tasks that need to be completed to fully  migrate all the information to a central source of truth.
The README itself contains references to tasks that are still outstanding, but it would be helpful to have it merged into master, so we have somewhere to point people, to make them aware this is being worked on, and perhaps to garner more help.
> Contributor guide folder and central starting point README outline

- contributors/design-proposals/node/accelerator-monitoring.md
For https://github.com/kubernetes/features/issues/369, https://github.com/google/cadvisor/pull/1762 and  https://github.com/kubernetes/kubernetes/pull/55188
Conversion to markdown from Google doc: https://docs.google.com/document/d/13O4HNrB7QFpKQcLcJm28R-QBH3Xo0VmJ7w_Pkvmsf68/edit
(accessible to anyone who is a member of kubernetes-dev@ or kubernetes-users@ Google Groups). Lots of discussion on the doc which is hard to recreate here now.
> Add design proposal for accelerator monitoring.

- contributors/design-proposals/scheduling/taint-node-by-condition.md
- contributors/design-proposals/storage/local-storage-overview.md
Part of: https://github.com/kubernetes/kubernetes/issues/51246
~~**DO NOT MERGE** until kubernetes/kubernetes#51266 is in!~~
> Use new taint key in design doc

- contributors/design-proposals/cluster-lifecycle/draft-20171020-bootstrap-checkpointing.md
This is a distillation, and jump, point from the other proposals.  It's meant to be a simplification to eliminate the potential for misinterpretation.  
/cc @kubernetes/sig-cli-feature-requests @yujuhong @dchen1107 @roberthbailey @luxas
> Design proposal for bootstrap checkpointing for self hosting

- contributors/devel/issues.md
The link with google-kubernetes tag doesn't give any search result. Updating
the tag to kubernetes from google-kubernetes to get an expected output. The changes are required in just one file in the repo as modified herewith.
> Update serverfault link tag per updated site tag

- contributors/devel/e2e-tests.md
Fix broken 'kinds of tests' link in the e2e tests documentation
> Fix broken link. Clean up some trailing whitespace.

- community-membership.md
This was a discussion topic with @calebamiles @smarterclayton and myself.
The previous guidance was that sponsors across organizations results in gold star, but this guidance firms up that requirement.  I am in favor of this change as a way of demonstrating integration into the broader community.
Opening for others input.
> members must have sponsors that span organizations

- contributors/guide/README.md
Issue triaging is an important contribution to the project and should be
highlighted with other areas of contribution. Creating this PR per discussion
in the ContribX SIG meeting on November 29, 2017.
> Add issue triage section

- contributors/design-proposals/service-catalog/pod-preset.md
> Fix anchor in pod-preset.md

- contributors/devel/e2e-tests.md
Fix #1263
1. According to https://github.com/kubernetes/kubernetes/pull/42140,  "build/push-federation-images.sh" shoud be "federation/develop/push-federation-images.sh"
2. " cluster/log-dump.sh" should be "federation/cluster/log-dump.sh"
> Fix #1263: bad reference for push-federation-images in e2e-test

- OWNERS
This alpha sorts the OWNERS file and adds @castrojo and myself as approvers (Jorge helping community manage, and myself having been shepherding stuff in this repo). This would be for fall-through stuff, as there are more-specific owners files in all the sig-owned directories.
I think with the document sorting being mostly done, the bots and CI working well, and the OWNERS_ALIASES file set up with all the sig leads, we might be able to turn on the new prow approval plugin in kubernetes/community.
> Add cblecker and castrojo to community approvers

- CONTRIBUTING.md
Note: There is a larger effort to write a full contributor guide, so this is mostly a revision. Biggest change is an addition of a section for how we should deal with trivial edits, which mostly is a crib from StackOverflow's policies on dealing with trivial edits. 
Fixes #1226
> First pass at revising the contributing guidelines

- contributors/guide/README.md
This commit replaces the "Improvements needed" marker for the testing
topic with an initial section of overview information and jumping off links
to sig-testing, test documentation, and test code.
Part of: https://github.com/kubernetes/community/issues/1413
> contributing guide: add initial section on testing

- contributors/guide/README.md
This PR has a series changes to the new contributing guide spanning:
* add a more cohesive PR section
* add a more cohesive code review section
* misc cleanups
I'm not sure that some of these are correct, so I split them into separate patches to allow more specific review and ack/nack.
> Contrib guide: more PR and review info and some cleanups

- sig-windows/README.md
We had a lot of interest in the SIG-Windows meetup at Kubecon last week, and a few people pointed out that the SIG-Windows page doesn't have what they need to get started or look for ways to contribute. I added some clarifications into a `CUSTOM CONTENT` section to help out.
> Updating doc & contributing links for SIG-Windows

- contributors/guide/README.md
We're to a point were a table of contents at the top of the contrib guide
is informative on overall flow of the doc.  Will need to regenerate this
if/when new sections are added since it's not a render-time artifact.
Relates to issues #1413.
> contrib guide: add table of contents

- README.md
Looks like the label was renamed from help-wanted to "help wanted", so the links didn't show any issues.
> Change help-wanted label to "help wanted" in README

- contributors/guide/README.md
The doc's referring to "help-wanted" labeled issues, but that shows zero
open and closed, where there's a bunch with "help wanted" through the
project history.  This patch updates the url to search issues with the
"help wanted label.
> contrib guide: update "help wanted" issue url

- contributors/devel/flexvolume.md
This PR marks FlexVolume GA.
Fixes the issue: https://github.com/kubernetes/website/issues/6641
> Mark Flexvolume GA

- sig-aws/CONTRIBUTING.md
- sig-aws/README.md
Add small section named Contributing which invites Users to attend meetings and link
them for more Informations to community-membership.md.
Greetings, Thomas
CC as discussed: @chrislovecnm
> Add explicit invite to sig-aws-meetings

- contributors/devel/help-wanted.md
> Added contributors/devel/help-wanted.md

- sig-windows/README.md
I added some docs and other info for sig-windows before 1.9 was final. Now that it's final - I'd like to remove some old links :)
> Replace draft links with 1.9 live docs

- contributors/design-proposals/scheduling/scheduler-equivalence-class.md
Original issue: https://github.com/kubernetes/kubernetes/issues/17390 
Please note this feature has been implemented but we need to amend a design doc (we do not have design PR process during working on the original issue)
This makes equivalence class feature easier to track and improve.
Part of: https://github.com/kubernetes/kubernetes/issues/51779
> Amend a design doc for equivalence class based scheduling

- contributors/guide/README.md
Fix incorrect anchor for Github markdown header in contributors guide.
> Fix incorrect anchor for Github markdown header in contributors guide

- contributors/design-proposals/storage/grow-volume-size.md
- contributors/design-proposals/storage/local-storage-overview.md
- contributors/design-proposals/storage/local-storage-pv.md
- contributors/design-proposals/storage/pod-safety.md
During reading docs under storage, found and fixed some minor typos.
- perfomed -> performed
- succeded -> succeeded
- direclty -> directly
- curent -> current
- parition -> partition
- toplogy -> topology
- bolume -> volume
- multi-tenent -> multi-tenant
- adminstrator -> administrator
- undestand -> understand
- spreadhseet -> spreadsheet
- evalutes -> evalutes
- existant -> existent
- wil -> will
- arbitary -> arbitrary
> fix typos in storage docs

- events/2017/05-leadership-summit/announcement.md
- events/2017/12-contributor-summit/ContribSummitInformation.md
The k/community repo's events directories underwent a shuffle recently.
This led to a few broken links, fixed in this commit.
> unbreak a few event links

- contributors/devel/strategic-merge-patch.md
Updates the doc for SMP. OpenAPI annotations are now allowed for strategic merge patch.
/cc @mengqiy
> StrategicMergePatch: OpenAPI annotations are now allowed

- keps/OWNERS
Adds additional people who are active on iterating on the KEP process
as OWNERS to the extracted `kep` directory.
> adds additional approvers and reviewers to KEPs OWNERS

- contributors/design-proposals/node/troubleshoot-running-pods.md
Fix the doc reference to Resource Quality-of-Service
> Fix the doc reference to Resource Quality-of-Service

- generator/README.md
- generator/app.go
- generator/sig_readme.tmpl
- sig-api-machinery/README.md
- sig-apps/README.md
- sig-architecture/README.md
- sig-auth/README.md
- sig-autoscaling/README.md
- sig-aws/README.md
- sig-azure/README.md
- sig-big-data/README.md
- sig-cli/README.md
- sig-cluster-lifecycle/README.md
- sig-contributor-experience/README.md
- sig-docs/README.md
- sig-gcp/README.md
- sig-instrumentation/README.md
- sig-multicluster/README.md
- sig-network/README.md
- sig-node/README.md
- sig-on-premise/README.md
- sig-openstack/README.md
- sig-release/README.md
- sig-scalability/README.md
- sig-scheduling/README.md
- sig-service-catalog/README.md
- sig-storage/README.md
- sig-testing/README.md
- sig-windows/README.md
- sigs.yaml
Each github team is associated with a google group. Example: https://github.com/orgs/kubernetes/teams/sig-api-machinery-pr-reviews is associated with https://groups.google.com/forum/#!forum/kubernetes-sig-api-machinery-pr-reviews.
I think it's helpful to document this because it allows someone to follow along even if they are not part of the team.
This PR contains the following changes:
- adds google groups for github teams in the generator.
- improves the generator `README`.
- `sig-storage`: removes info about google groups from custom content
- `sig-apimachinery`:
- removes duplicate content
- renames TPR to CRD
/assign cblecker spiffxp vishh
> generator: add google groups for github teams

- org-owners-guide.md
cc @kubernetes/steering-committee @idvoretskyi 
I think I have this right but I'm not sure. After some conversations in December I wanted to capture what I'd learned in writing.
> Adding initial directions for kubernetes organization owners

- CONTRIBUTING.md
Also moving trivial edits section to the PR doc makes sense, see #1628
> Point contributors towards our new resources

- contributors/devel/owners.md
fixes kubernetes/community#1286
- reference prow instead of mungegithub
- drop deprecated `assignees` field
- add new `options` field
- misc wording changes
> Refresh OWNERS docs

- contributors/design-proposals/architecture/identifiers.md
According to [namespaces.md](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/namespaces.md) a namespace is a DNS label.
> Namespace is a DNS_LABEL

- CLA.md
- setting-up-cla-check.md
This is pretty much rote copy-paste from a google doc I got from @foxish.
I followed these instructions as part of https://github.com/kubernetes-sig-testing/frameworks/issues/3
/cc @mattfarina @foxish @idvoretskyi
since I mentioned this to you
FYI @kubernetes/sig-testing-pr-reviews 
This could stand to be streamlined, any suggestions?
> Add instructions on how to setup the CNCF CLA check

- contributors/guide/README.md
- contributors/guide/community-expectations.md
This is part of #1413 
This moves the community expectations from the old place to the new contributor guide. I've given it a once over, removed the duplicated content that is stated elsewhere (we don't need every single page to mention the CoC for example), and I've grabbed things that were in `collab.md` and integrated it into this document.
We will not need to bring collab.md over to the contributor guide.
> Moving and revising community expectations

- sig-windows/README.md
- sig-windows/api-tracking.md
I'm adding a link to the Trello board used in SIG meetings, and a draft of the upcoming API work item list. This was requested to help clarify to SIG-Node what APIs need to be implemented or changed on Windows. The api-tracking.md doc is not 100% complete yet, but I'd like to keep it here for SIG members to start collaborating on.
> Adding trello board and API list draft

- contributors/design-proposals/node/container-runtime-interface-v1.md
- contributors/design-proposals/node/pod-pid-namespace.md
We will need to support configuring shared PID namespace in docker per-pod.
> Update Docker Shared PID proposal for per-pod configuration

- contributors/devel/testing.md
- contributors/guide/github-workflow.md
`go-workspace` link taken from `contributors/devel/development.md:181`
> fixed typo and missing link

- contributors/guide/README.md
The difference between the two links for communications around questions
and troubleshooting was not clear to me, and the wording made them
seem somewhat redundant.  They're really two separate topic links,
so I've changed the wording to hopefully make it more clear that one has
general communications information and once is actually a
troubleshooting guide.
> contrib guide: tighten some language

- communication.md
- events/community-meeting.md
The community meeting google doc is starting to have too much info at the top, so I'd like to put it in the github repo for more permanence. 
It makes some changes which I have proposed at a prior meeting, so I'd like the reviewers to note the codification of things, notably the purpose of the meeting, and the addition of stricter requirements for the community demo.
/cc @jdumars @jberkus @tpepper
> Break out the community meeting documentation into its own page

- sig-aws/CONTRIBUTING.md
- sig-multicluster/CONTRIBUTING.md
- sig-storage/contributing.md
This adds a link to the main contributor guide from 3 SIG contributing.md guides.
This fixes #1612 #1614 and #1615
> Update SIG contributing link to mention the Kubernetes contributor's

- README.md
- community-membership.md
- contributors/guide/README.md
- mentoring/group-mentee-guide.md
Some 404 errors fixed because community-expectations.md was moved to contributors/guide
> fixed links to community expectations

- OWNERS
Somehow Brian was missed in the top-level OWNERS file of k/community
cc: @bgrant0607 @spiffxp
> Add bgrant0607 to top-level OWNERS

- contributors/design-proposals/auth/kubectl-exec-plugins.md
Updates https://github.com/kubernetes/kubernetes/issues/55968
Updates https://github.com/kubernetes/kubernetes/issues/14362
cc @kubernetes/sig-auth-proposals 
cc @mattmoyer 
cc @ericavonb
> proposal: external client-go auth providers

- contributors/guide/OWNERS
Right now changes to the contributor's guide flow up to the top level approvers. This creates an OWNERS file for the guide so that the people who are working on it can review it. Please let me know if anyone should be added/removed.
/hold
for comment
/cc @castrojo @guineveresaenger @tpepper @parispittman @spiffxp
> Add OWNERS file for contributors/guide/

- sig-storage/out-of-tree-plugin-faq.md
With CSI in development, there are now two different ways to implement out-of-tree volume plugins in Kubernetes. This doc aims to demystify the differences and provide answers to common questions from storage vendors that come up while deciding between CSI and FlexVolume.
Once this is merged, I'll add a link to this doc here: https://kubernetes.io/docs/concepts/storage/volumes/#out-of-tree-volume-plugins
@chakri-nelluri @saad-ali @childsb
> Out-of-tree volume plugin FAQ for storage vendors.

- contributors/design-proposals/storage/raw-block-pv.md
- contributors/design-proposals/storage/volume-provisioning.md
This PR updates current specification of Block volume to support dynamic provisioning functionality.
Initial design doc proposal for block volume: https://github.com/kubernetes/community/pull/1265
Feature issue: https://github.com/kubernetes/features/issues/351
> Spec update of Block volume to support for dynamic provisioning

- contributors/guide/README.md
Communication resources are in their own directory, this points people
to it.
> Add pointer to communication/

- README.md
This file was renamed in 774750b5d22b16203a0ea18d352821cb0aa7d43a.
Then, the link was fixed in ec8afcb36282ae771a02c7b5568e896d61faeba2. But broken again by 069e6e50f91563e4efdb68e0a9c786a2a9f75d52
> Fix link to community expectations

- contributors/design-proposals/node/cri-windows.md
> Design proposal for Windows Container Configuration in CRI

- contributors/devel/README.md
- contributors/guide/README.md
- mentoring/README.md
This adds the necessary metadata to generate a table of contents when
when generating these pages for the documentation.
> Add TOC headers to contributor, developer, and mentorship guides

- contributors/guide/README.md
The table of contents has slipped out of date.
FYI I'm generating a ToC with a command like:
pandoc -t markdown_github --toc -s README.md
and then picking up the modifications and dropping them in the document.
Not the best workflow, but..markdown.
> contrib guide: update ToC

- contributors/design-proposals/api-machinery/alternate-api-representations.md
fix a typo in alternate api representations
> fix a typo in alternate api representations

- contributors/design-proposals/scheduling/schedule-DS-pod-by-scheduler.md
xref https://github.com/kubernetes/features/issues/548
/cc @bgrant0607 , @bsalamat , @kubernetes/sig-apps-feature-requests
> Design doc of 'Schedule DS Pod by default scheduler'.

- contributors/design-proposals/storage/postpone-pv-deletion.md
add finalizer to postpone pv deletion if it is bound to a pvc
xref: https://github.com/kubernetes/features/issues/499
/sig storage
/assign @pospispa
> postpone pv deletion if it is bound to a pvc

- contributors/devel/issues.md
Fix a broken link. This is the only broken link that I found after checking all the files that are moved to guide.
> Fix a broken link for a file moved to guide from devel

- contributors/guide/README.md
Thanks were expressed twice in the Contributor Guide. To remove clutter, this pull request removes this section from the main README but leaves it in community-expectations.md. In the future, code review documentation will be added as well.
> This commit removes the duplication of thanks from the Contributor Guide

- kubernetes-repositories.md
This is a general proposal from the Kubernetes steering committee. I authored the pull, but the document is jointly authored.
@bgrant0607 @thockin @timothysc @michelleN @smarterclayton @derekwaynecarr @quinton-hoole @sarahnovotny @jbeda @spiffxp @pwittrock @philips 
We plan on discussing this at Kubernetes community meeting on 2/8/2018
> Add new repository structure doc.

- kubernetes-repositories.md
Escape underscore so github doesn't show the remaining text in italics when changes are to this file. You can see the incorrect results when looking at this PR: https://github.com/kubernetes/community/pull/1752/files  - everything after line 35 is in italics.
> Escape underscore

- sig-scalability/tools/performance-comparison-tool.md
As I'm getting numerous requests for access to the [original document](https://docs.google.com/document/d/1olGQ7nHqoZVO714XtgBzrPvifR7nWu0pQWwelN3VQtM) on my google drive. I believe this should be made openly available here.
/cc @wojtek-t @countspongebob
> Add performance comparison tool doc to sig-scalability/tools

- sig-storage/README.md
- sigs.yaml
The actual path in the Kubernetes repo is pkg/volume, not pkg/volumes.
> sig-volume: fix owner link for pkg/volume owners

- generator/wg_readme.tmpl
- sigs.yaml
- wg-cloud-provider/README.md
This is a statement of intent to create new Git repositories for the
cloud providers to extract from `kubernetes/kubernetes`. Handling
repositories for newly donated cloud providers will be handled
separately
> List desired cloud provider git repositories as subprojects

- events/community-meeting.md
This clarifies how best to subscribe to the community meeting. Unfortunately ical usage depends on the client, so we don't want to cover every case here, so we link to wikipedia. 
Perhaps a page or videos for each specific client might be a good idea if we want some follow up work.
> Make ical instructions clearer

- sig-scalability/processes/formal-scalability-processes.md
We've been having various scattered discussions on how scalability/performance regressions are affecting k8s and its eng productivity. To try to solve those issues, I've assimilated some of my thoughts for formal scalability processes into [this google doc](https://docs.google.com/document/d/1Jv_QbehMTf0t2YVS4pYM_iSqWpg777JDRRbIUKXErYI/edit?usp=sharing), which changed into the current form after some great inputs from sig-scale folks (@wojtek-t, @wasylkowski-a, @gmarek, @porridge - thanks!).
This PR is a markdown version of that doc. PTAL
/cc @thockin @smarterclayton (as steering committee members)
/cc @spiffxp (as sig-testing lead)
/cc @wojtek-t (as sig-scalability lead)
> Formal scalability processes design proposal

- keps/0000-kep-template.md
- keps/0001-kubernetes-enhancement-proposal-process.md
- keps/0002-controller-manager.md
- keps/README.md
- keps/sig-cluster-lifecycle/0003-cluster-api.md
- keps/sig-cluster-lifecycle/0004-bootstrap-checkpointing.md
Based on discussions on SIG-Architecture we are changing the `accepted` state to `provisional`.
Also made the process in the template much more clear.  Expanded KEP README.md to add some FAQs.  Most critical is that SIGs are not required to use the KEP process.
Fixes #1793.
Supersedes #1775.
Signed-off-by: Joe Beda <joe.github@bedafamily.com>
> Update/clarify KEP process

- contributors/design-proposals/storage/container-storage-interface.md
CSI now allows credentials to be specified on `CreateVolume`/`DeleteVolume`, `ControllerPublishVolume`/`ControllerUnpublishVolume`, and `NodePublishVolume`/`NodeUnpublishVolume` operations. This PR describes how credentials stored in Kubernetes secrets maybe passed to CSI.
> Introduce CSI secret/credential handling

- contributors/design-proposals/autoscaling/hpa-external-metrics.md
This proposal describes an extension to the HPA v2 API that would allow autoscaling based on metrics coming from outside kubernetes cluster. This is not possible using existing API.
Common use-cases are autoscaling pods using a hosted service (ex. hosted message queue) or autoscaling in systems that have (so far) only partly moved to Kubernetes.
https://github.com/kubernetes/community/pull/1802 describes External Metrics API used internally by HPA to retrieve metrics. 
/sig-autoscaling
> Proposal: HPA using external metrics

- sig-contributor-experience/README.md
- sigs.yaml
The current link for [**contributors-guide** Owners](https://github.com/kubernetes/community/blob/master/sig-contributor-experience/README.md#subprojects) is not valid.
> Fix invalid link for contributors-guide owners

- contributors/design-proposals/network/nodeport-ip-range.md
/sig network
@kubernetes/huawei
> Proposal: Support specifying NodePort IP range

- sig-network/README.md
- sigs.yaml
There is no cmd/kube-proxy/OWNERS file anymore and pkg/api module
moved to the separate repository.
> sig-network: Fix OWNERS links

- contributors/guide/README.md
- contributors/guide/issue-triage.md
- mentoring/README.md
Hi, these are a few quick fixes to the documentation.
`contributors/guide/README.md`
→ Took me ages to find out what cni stood for, so I thought I'd add it to the guide for clarity.
`contributors/guide/issue-triage.md`
→ Typo.
`mentoring/README.md`
→ The previous information was inaccurate. Outreachy isn't targeted at students, it's targeted at groups traditionally underrepresented in tech. (Meaning cis/trans women, trans men, and genderqueer people.. but I'm not sure we wanna go into that much detaill.)
> Quick fixes

- contributors/devel/api_changes.md
Add the requirement that GA/stable APIs must have conformance tests, if/as appropriate.
The intent is to stop the bleeding on features progressing to GA without conformance tests. There are some details to work out, but I don't think they belong in this doc. I'm just trying to capture the intent here.
cc @kubernetes/sig-architecture-api-reviews @jagosan @WilliamDenniss
> Add the requirement that GA/stable APIs must have conformance tests

- sig-product-management/SIG PM representatives.md
SIG OpenStack leadership turned over in December of 2017. This
patch updates the SIG PM representatives file to reflect that.
> Update SIG PM representative with new SIG OpenStack leadership

- contributors/guide/contributor-cheatsheet.md
What this PR does / why we need it:
Previously the URL in [contributor cheatsheet](https://github.com/kubernetes/community/pull/1883/files#diff-44d578a3dd781a55fe797ae8cea800ea) to the bot commands page was outdated and still referred to the [old page](https://git.k8s.io/test-infra/commands.md). This PR makes a small change so that the URL points directly to the [new page](https://prow.k8s.io/command-help), thus less clicks and frustration for future readers.
Which issue(s) this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
None
Special notes for your reviewer:
None
Release note:
Fixed outdated URL to bot commands in contributor cheatsheet.
> Correcting an outdated URL in contributor cheatsheet

- community-membership.md
Merge *maintainer* responsibilities into *project owner*
Why are we doing this:
- The scope of the Kubernetes project is such that having a role for holistic maintenance of the entire project in all capacities is not practical.  Scoping responsibilities to specific *subprojects* within the Kubernetes project is feasible.
- Through automation improvements direct write access to the kubernetes/kubernetes will no longer be necessary for maintenance of the project going forward.
PR details:
- **Remove *maintainer* role and merge responsibilities into *owner* role**
- Rename *owner* to *subproject owner* and frame responsibilities in the context of a subproject
- Rename references to area / component to subproject
- Remove references to kubernetes-reviewers GitHub team
- Remove references to …
> Simplify membership ladder

- committee-steering/governance/README.md
- committee-steering/governance/sig-governance-template-short.md
Short template for sig governance
Also see:
- Long template #1650 
- ~Requirements PR: #1800~ Merged
> Sig Governance Short Template

- contributors/devel/e2e-tests.md
xref https://github.com/kubernetes/kubernetes/pull/60872
xref https://github.com/kubernetes/test-infra/pull/7164
xref https://github.com/kubernetes/test-infra/pull/7073
xref https://github.com/kubernetes/kubernetes/issues/60870
-v in kubetest/e2e.go has been changed to `--verbose-commands` and is default to true now. -v is used for glog and user need to supply a level.
/sig testing
/assign @Q-Lee @BenTheElder
> purge all the -v in e2e.go

- communication/slack-guidelines.md
Renamed 'ihor' -> 'idvoretskyi' to follow the nickname consistency across the community (GitHub, Slack, Twitter, etc.)
> Renamed myself to follow the consistency

- keps/sig-contributor-experience/0005-community-site.md
Add Paris as approver and Jorge as reviewer. Also list SIG-Docs as participating as they are certainly interested in how this pans out.
Signed-off-by: Joe Beda <joe.github@bedafamily.com>
> KEP-5: Update metadata

- sig-aws/README.md
- sig-azure/README.md
- sig-gcp/README.md
- sig-openstack/README.md
- sigs.yaml
- wg-cloud-provider/README.md
Make the existing SIGs
- SIG AWS
- SIG Azure
- SIG GCP
- SIG OpenStack
the "owners" for the repositories which will be created to host provider
specific code. Other SIGs will be charted as needed/desired for other
providers at a later time.
> Makes SIGs responsible for implementations of `CloudProvider`

- sig-cli/CONTRIBUTING.md
Hi! 
This PR has the purpose of fixing issue #1613. In summary:
- Added pointer to main kubernetes contributor guides
- Removed CLA reference 
- Restructured introduction for readability and general consistency checks 
I'm looking forward to read your feedback soon.
> #1613 nidorano sig cli contribution ptr

- contributors/design-proposals/federated-hpa.md
- contributors/design-proposals/multicluster/federated-hpa.md
For reference, there already has been quite a lot of discussion over this design [here](https://docs.google.com/document/d/1Uacp99LskNHkJ6ZFFOVGorDivYKi4ySkI8E3tTFAZJ8).
A very readable version of this doc can be viewed on my fork [here](https://github.com/irfanurrehman/community/blob/federated-hpa-design/contributors/design-proposals/federated-hpa.md)
@kubernetes/sig-federation-feature-requests
@kubernetes/sig-federation-misc
@kubernetes/sig-autoscaling-feature-requests
> [Federation] Federated hpa design

- hack/verify-generated-docs.sh
This copies all files to the verify directory, not just specifics. This should ensure that the verify script doesn't break when new files are added to the generator.
> Fix up verify-generated-docs script

- wg-cloud-provider/cloud-provider-requirements.md
This document defines a common code location and layout for provider
Cloud Controller Manager implementations.
https://github.com/kubernetes/community/pull/1862
> Proposal for common Cloud Controller Manager repository structure

- events/2018/05-contributor-summit/README.md
Fix link to CLA (unfortunately didn't find a way to use absolute links), explicitly state that May 1st is Tuesday to avoid confusion.
> Fix link to CLA, explicitly state weekday

- kubernetes-repositories.md
Remove the sig name prefix from the repo name.
> Update naming style for subprojects in the kubernetes-sigs org

- keps/sig-cluster-lifecycle/draft-20180130-kubeadm-join-master.md
Adapted from the kubeadm HA design document:
https://goo.gl/QpD5h8
It still needs some work, but it makes sense to get the first iteration checked in to start moving it through the approval process (and to deprecate the google doc).
This KEP matches what is implemented in this PR:
https://github.com/kubernetes/kubernetes/pull/58261
/CC @timothysc @roberthbailey @luxas @errordeveloper @jamiehannaford
> KEP kubeadm join --master workflow

- sig-multicluster/README.md
- sigs.yaml
Updates the sigs.yaml file with information about SIG multicluster's subprojects.
Note: the README file for this SIG already contains manually entered information about the subprojects which we would like to maintain - for now I've left it alone but am happy to shift around as folks want.
Note: I've opened https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/159 to add an OWNERS file to that repo so that it can be tracked correctly in sigs.yaml.
> Update sig.yaml with subprojects of SIG multicluster

- contributors/design-proposals/storage/pv-to-rbd-mapping.md
@rootfs here is a proposal to make rbd image non random that we talked about some time back
> add proposal to store additional metadata about rbd owner in rbd image

- contributors/design-proposals/node/seccomp.md
Updates kubernetes/kubernetes#39845
Feature issue kubernetes/features#135
This PR updates the seccomp design doc to indicate that we are enabling a default seccomp profile: docker/default. It pulls a few pieces from #660, but does not include the seccomp spec. The reasoning here is that we can simply enable docker/default as the first step and see how it works. If strong needs of a different default k8s seccomp profile come up, we can add that later.
> Update seccomp design doc to enable default seccomp profile

- contributors/design-proposals/cluster-lifecycle/local-cluster-ux.md
- contributors/devel/development.md
- contributors/devel/testing.md
- contributors/guide/coding-conventions.md
Mac OS X was renamed to OS X in 2012, and then renamed again to [macOS](https://en.wikipedia.org/wiki/MacOS) in 2016.
I suggest that the current name (macOS) should be used whenever referencing the Apple OS.
> Change 'Mac OS X' and 'OS X' to 'macOS'

- governance.md
> Include more instructions on WG creation.

- contributors/guide/README.md
Removed duplicate title on contributors guide readme page
> Fix for duplicate title on Contributors guide README

- contributors/guide/README.md
The issue triage doc has moved from:
contributors/devel/issues.md
to:
contributors/guide/issue-triage.md
> update issue triage doc url

- keps/sig-network/0007-pod-ready++.md
> add KEP for pod ready++

- contributors/design-proposals/node/pod-resource-management.md
Fix mistake about the example about calculating the cpu.shares of a burstable pod (Pod3) with two containers. Since the container "bar" in Pod3 is only specified with resource.limit, so the resource.request of container "bar" is equal to its limits, so request.cpu is 100m, request.memory is 1Gi. 
Therefore, when you calculate the pod level cgroup's cpu.shares should be the sum of resource.request.cpu of container "foo" and "bar",  which is 120m. The cpu share of burstable cgroup should also be modified to 130m.
> Fix mistakes about the example of resource account for burstable pods and typo mistake

- kubernetes-repositories.md
Adds information about rules for donating repositories to the kubernetes-sigs organization, per an email thread with steering committee members.
> Add rules for donating repositories to kubernetes-sigs

- mentoring/the1-on-1hour.md
adding the documentation for The 1:1 Hour - a mentoring program. The last link will be dead until I upload the mentoring guidelines. 
/hold
> add docs for The 1:1 Hour

- contributors/guide/issue-triage.md
Recently we have added new labels to identify issues that are candidates for close.
These issues are typically the one which are not goint to close via a fix. Add
description in triage guidelines about when to use these labels.
Related PR is,
https://github.com/kubernetes/test-infra/pull/7200
> Describe new labels in triage guidelines

- contributors/design-proposals/auth/bound-service-account-tokens.md
Proposal to improve the utility of service account tokens by supporting audience, time and key binding.
@kubernetes/sig-auth-api-reviews
> proposal: bound service account tokens

- contributors/devel/cherry-picks.md
The cherry-pick instruction guide had some readability issues in
its formatting, with numbered bullet lists not rendering correctly.
It also referenced an issue which was resolved, so I've added links
to the resulting tools and information.  Finally, based on watching
a new user attempt a cherry pick (a common occurance around release
time with the revolving staffing of the release team) a few
clarification and setup issues are described around the
hack/cherry_pick_pull.sh script.
> clarify some parts of the cherry pick process

- contributors/design-proposals/api-machinery/customresources-versioning.md
CRD versioning proposal is discussed in detail here:
https://docs.google.com/document/d/1Ucf7JwyHpy7QlgHIN2Rst_q6yT0eeN9euzUV6kte6aY/edit
This is the main no conversion part of the design agreed on by the community/API machinery SIG.
@sttts @deads2k @lavalamp
> CRD versioning design proposal [No Conversion]

- committee-steering/governance/sig-governance-requirements.md
Fixes a minor typo in the governance requirements doc
/sig steering
> Fix typo in governance requirements doc

- contributors/devel/coding-conventions.md
- contributors/devel/faster_reviews.md
- contributors/devel/go-code.md
- contributors/devel/owners.md
- contributors/devel/pull-requests.md
- contributors/devel/release/OWNERS
- contributors/devel/release/README.md
- contributors/devel/release/issues.md
- contributors/devel/release/patch-release-manager.md
- contributors/devel/release/patch_release.md
- contributors/devel/release/scalability-validation.md
- contributors/devel/release/testing.md
- contributors/devel/scalability-good-practices.md
- contributors/devel/security-release-process.md
Now that the release team contact info page has moved here: https://git.k8s.io/sig-release/ephemera/README.md and Kubernetes 1.10 has been released, I am submitting this PR to remove the page. (Since it said to delete once K8s 1.10 is out.) 😄
> Remove contributor page

- contributors/new-contributor-playground/OWNERS
- contributors/new-contributor-playground/README.md
This folder is meant as a location for participants of the new contributor track at KubeCon Copenhagen 2018 to safely try out submitting pull requests and familiarizing themselves with the workflow.
This PR also attempts to create the label `new-contributor-track` in a new OWNERS file (which has some shady membership level promotions as well to enable the teachers of the track to be Approvers). Please advise on details of new label creation, overstepping of boundaries or stepping on toes!
/assign @spiffxp 
/assign @parispittman 
> Adds new contributor playground [WIP]

- communication/README.md
As evidenced by a post to kubernetes-dev asking to be added to the list,
the current info on mailing lists may not be completely clear to
readers.  This commit makes the wording more explicit and includes a
link to Google Groups' info on how to find and join a group.
A broken link to the sig-list.md is also corrected.
> add info on joining Google Groups

- contributors/new-contributor-playground/README.md
When navigating the readme you can now click to be redirected to the repository k/community
> Added link to kubernetes/community

- contributors/design-proposals/apps/controller_history.md
> Typo fix in commands: kubeclt->kubectl

- events/community-meeting.md
The previous version of the Youtube link auto-played the most recent video, and tucked the historical recordings off to the side.
This version of the Youtube link focuses on the historical list of recordings and avoids potentially intrusive auto-play.
> Link to Playlist view of Youtube videos

- contributors/devel/api_changes.md
The line deleted explicitly tells that list of versions will be removed after 1.8 which is not case. So, removing it.
> Remove confusing aggregator list comment

- contributors/guide/README.md
KubeCon + CloudNativeCon is now held thrice a year.
China is added to the list of events.
Signed-off-by: Marius Gerling <marius@gerl1ng.de>
> Add China to the list of events

- contributors/new-contributor-playground/README.md
- events/2018/05-contributor-summit/new-contributor-workshop.md
This disseminates the video of the May 2018 New Contributor Workshop at KubeConEU by adding it to the event outline, and linking from the activity folder.
Suggestions on additional/alternate placement welcome.
> Workshop video

- committee-steering/governance/README.md
I don't think this is a `sigs.yaml` thing. 
I've never seen this anchor footnote thing before. It's super awesome.
> remove extra parenthesis

- contributors/new-contributor-playground/new-contributor-notes.md
Fix some typos.
excuted->executed
> Typo fix: excuted->executed

- contributors/devel/development.md
ref: https://github.com/kubernetes/kubernetes/pull/60597
> Add the minimum go version for release 1.11+

- contributors/design-proposals/auth/proc-mount-type.md
/cc sig-node-proposals
see also:
https://github.com/moby/moby/issues/36597
https://github.com/opencontainers/runc/issues/1658#issuecomment-373122073
> add ProcMount option

- contributors/devel/api_changes.md
Corrects location of core defaults.go based on current kubernetes/kubernetes repo.
> Fix incorrect path in api_changes doc

- keps/0008-node-heartbeat.md
/assign @dchen1107 @derekwaynecarr 
/reviewers @lavalamp @deads2k 
/cc @bgrant0607 @yujuhong @liggitt @smarterclayton 
@kubernetes/sig-node-api-reviews @kubernetes/sig-api-machinery-api-reviews
> KEP: efficient node heartbeats

- contributors/design-proposals/storage/volume-topology-scheduling.md
Continuation of #1857, which is unicorning too much.
This design is for 1.11 work to support dynamic provisioning.
Update volume topology design doc with:
Defining terms used to describe topology
Dynamic provisioning new APIs
In-tree and external provisioning interface changes
Scheduler implementation details
Examples for local, zonal, and multi-zonal volumes
@kubernetes/sig-storage-pr-reviews
/hold
> Topology aware dynamic provisioning design (take 3)

- committee-steering/governance/sig-governance-template-short.md
This adds a list of contacts for the repo that the Product Security Team can
reach out to for triaging and handling of incoming issues, please try to keep
this list small as the contact can then further decide who "needs to know" to
complete the fix.
> add SECURITY_CONTACTS to repo template

- org-owners-guide.md
- setting-up-cla-check.md
linuxfoundation appears to be the org, thelinuxfoundation is the bot.
> Fix name of linux foundation bot: thelinuxfoundation

- sig-vmware/README.md
- sigs.yaml
SIG VMware wants to create a subproject for the extraction of the in-tree vSphere cloud provider, this PR depends on the creation of the repo itself.
/cc: @calebamiles
> Add SIG VMware ML and cloud-provider-vsphere subproject

- generator/README.md
This is only a nit, but DST is generally Daylight Saving Time, not Daylight Saving**s** Time.
Wikipedia does [call out](https://en.wikipedia.org/wiki/Daylight_saving_time) that _savings_ is common in the U.S., so maybe this is a non-issue. I'd still rather see it be correct.
> Use singular form of DST

- community-membership.md
In the maintainers section of community-membership, it previously had a link that didn't point to anything (it was just a matter of upper/lower case). I just corrected it so it actually points to the OWNERS page.  Since none of the other links to owners corrected its case i.e OWNERS vs owners, I removed the `(#owners)` part.
> Fixed link to owners in the maintainer section

- keps/sig-network/0010-20180314-coredns-GA-proposal.md
This KEP is defined to graduate CoreDNS to GA.
> KEP for CoreDNS to GA.

- contributors/guide/contributor-cheatsheet.md
- Add few links related to testing.
- Update dead link related to code search.
- Use `*.k8s.io` for links.
Follow up of https://github.com/castrojo/contributor-cheatsheet/pull/1
/assign castrojo
> Update links in contributor cheatsheet

- wg-machine-learning/README.md
Per our last [MLWG meeting](https://www.youtube.com/watch?v=saj2KENcDT8&index=5&t=0s&list=PL69nYSiGNLP3NCO8CFgc8UCza86ZaJAyv), we presented a suggested charter for the working group. 
This PR includes some of the suggested topics, though more detail will most likely come over the coming weeks.
> Adding a bit more detail to the mlwg charter

- contributors/design-proposals/network/support_traffic_shaping_for_kubelet_cni.md
Currently the kubenet code supports applying basic traffic shaping during pod setup. This will happen if bandwidth-related annotations have been added to the pod's metadata, for example:
{
"kind": "Pod",
"metadata": {
"name": "iperf-slow",
"annotations": {
"kubernetes.io/ingress-bandwidth": "10M",
"kubernetes.io/egress-bandwidth": "10M"
}
}
}
Our current implementation uses the linux tc to add an download(ingress) and upload(egress) rate limiter using 1 root qdisc, 2 class(one for ingress and one for egress) and 2 filter(one for ingress and one for egress attached to the ingress and egress classes respectively).
Kubelet CNI code doesn't support it yet. However, there is enough functionality for us to add a simple CNI plugin to replicate the behavior we have today in kubenet if we feel …
> Support traffic shaping for Kubelet CNI network plugin

- contributors/guide/issue-triage.md
https://github.com/kubernetes/test-infra/blob/master/commands.md
redirects now to https://prow.k8s.io/command-help . Update the
documentation so that we link directly to the new location.
> Fix link to Prow commands

- keps/sig-cluster-lifecycle/draft-20180130-kubeadm-join-master.md
`system:node-bootstrapper` is a ClusterRole not a group.
> system:node-bootstrapper is not a group name

- contributors/devel/help-wanted.md
When I switched to hard-wrapping at 80 characters in my [last PR](2226), I introduced some odd formatting that I didn't catch at the time:
* The warning about not leaving contributors to find their own approver was intended to be bolded.
* The suggestion to use emoji should be its own list item.
> Fix markdown formatting in help wanted

- contributors/devel/e2e-tests.md
Resolves: #2180 
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>
> Update e2e testing against local clusters

- contributors/devel/cri-validation.md
Documentation for https://github.com/kubernetes/features/issues/292.
> Update docs for cri-tools

- contributors/guide/README.md
Related to https://github.com/kubernetes/community/pull/2226 and https://github.com/kubernetes/community/issues/1959
I'm adding a notice that the `good first issue` label is still a WIP and not every repository is going to have them yet. New contributors might be discouraged when they see the fancy new `good first issue` label only to find that the repository they want to contribute to doesn't have any issues with that label.
> add a notice that the good first issue label is new and a WIP

- contributors/devel/godep.md
On the release team I've seen a number of issues go by this year
where vendor code was updated and later implicated in issue triage
and bisection, but the original commits didn't sufficiently document
the change.  Reverting the update then reintroduced a previously
fixed issue, which was insufficiently documented in the changelog.  The
subsequent churn led to a lot of work by multiple people to resolve.
Terse godep vendor code update commit messages seem to be the norm and
we should aim higher.
> contributors/devel: request better godep vendoring commit messages

- sig-pm/README.md
Stephen is doing a huge amount of PdM job (specifically around the features process), this PR nominates him to hold this role officially within the SIG.
cc @justaugustus @jdumars @calebamiles 
> [SIG-PM] PdM subproject lead updated

- sig-aws/README.md
- sigs.yaml
> Updated sigs.yaml with aws-alb-ingress-controller subproject details

- keps/sig-cloud-provider/OWNERS
- keps/sig-cloud-provider/providers/0004-cloud-provider-template.md
This is a KEP template that new cloud providers can use to introduce new cloud providers as subprojects under SIG Cloud Provider. Requirements are mostly based on https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0002-cloud-controller-manager.md#repository-requirements and will be updated as those requirements change. 
In the future, we may expect existing cloud providers (aws, azure, gcp, vmware, etc) to create a KEP for consistency & visibility. 
cc @kubernetes/sig-cloud-provider @calebamiles
> New Cloud Provider KEP Template

- sig-governance.md
This removes the need to create SIG service accounts during the creation of a new SIG. It does not address what we'll do with the existing groups, but it will at least prevent us from creating more moving forward. 
dev list discussion: https://groups.google.com/forum/#!topic/kubernetes-dev/dH4tLdBUavU
> Remove creation of SIG service accounts

- contributors/devel/client-libraries.md
fix broken link to Kubernetes client libraries overview page
> update link to Kubernetes client libraries overview page

- .github/PULL_REQUEST_TEMPLATE
Replaces old 'Getting Started' guide link with one pointing to the
guide's new location.
> Update PR Template

- contributors/design-proposals/storage/grow-flexvolume-size.md
Proposal for growing FlexVolume size, the feature ticket is at:
https://github.com/kubernetes/features/issues/304
The original google doc for this proposal is at:
https://docs.google.com/document/d/1dwom9xQ3Fg5F_jJrybr0slp-QsO3_CKiisxzNRoMhec/edit?usp=sharing
> Proposal for growing FlexVolume size.

- community-membership.md
Sometimes it's much easier to copy the GH handle from the request body than from a subject. Adding an update the requires the GitHub handle at the community membership request body.
cc @cblecker @calebamiles 
> GitHub handle is required at the request body

- hack/verify-generated-docs.sh
- sig-contributor-experience/README.md
- sigs.yaml
The main readme for the SIG Contributor Experience covers at a high
level some of the information that is detailed in the new charter
document and is a bit out of date relative to it.  This freshens things a little.
> contribx: link charter doc in readme

- contributors/guide/README.md
The contributor guide currently has an empty section for security. I wanted to at least add a pointer to where people can find more information.
From what I can gather the Security Release Process page appears to be the entry point where we want to send people, so adding a link to that, and then one to the page for where to report security issues because I figure that never hurts.
Security folks, is there any other information you think we should add to this section? The target user is new contributors.  
/cc @philips @jessfraz @cjcullen @tallclair @liggitt
> Add an initial security section

- contributors/guide/coding-conventions.md
- contributors/guide/issue-triage.md
Just a couple small changes -- The current links point to redirects, this just points them to their actual target.
> Update kubernetes.io urls in contributor guide

- committee-steering/governance/sig-governance-template-short.md
As outlined by [Brian Grant](https://github.com/kubernetes/community/pull/2040#discussion_r189472207)
there isn't a process for a SIG Chair to be removed. I think the best
course is to suggest an unresponsive chair be encouraged to step down
and if that fails a consensus is reached amongst existing chairs and
subproject owners.
> steering: governance: define chair removal process

- keps/sig-cloud-provider/0003-testgrid-conformance-e2e.md
- keps/sig-cloud-provider/OWNERS
KEP for reporting conformance test results from all cloud providers.
@AishSundar @BenTheElder (sig-testing)
@calebamiles @jdumars (sig-release)
> SIG Cloud Provider KEP: Reporting Conformance Test Results to Testgrid

- contributors/devel/api_changes.md
Fixes #1159 
See https://github.com/kubernetes/community/issues/1159#issuecomment-397008148
Some examples have proto tags and some don't. Since proto tags are generated and not manually written, this PR removes the proto tags from the examples to remain consistent.
> api_changes: remove proto tags from examples

- contributors/guide/contributor-cheatsheet.md
I figured this would be a handy list of aliases to have in the cheat sheet. 
> Add a list of handy email aliases

- contributors/guide/OWNERS
- contributors/guide/non-code-contributions.md
This adds a skeleton section to the contributor guide for a non-developer section. I've put it in it's own document with a link from the guide so that the team can iterate quickly on one file. 
@kbarnard10 is already an org member so I've added her as a reviewer to the guide since she is working on this.
> Add non-developers contribution section and an owner for it

- keps/sig-auth/OWNERS
Owners file copied from sig-node, s/node/auth/
/sig auth
> Grant sig-auth leads approval of sig-auth KEPs

- README.md
Came across this while adding a `CONTRIBUTING.md` to [publishing bot](https://github.com/kubernetes/publishing-bot/issues/72).
/shrug
/cc guineveresaenger cblecker 
/assign cblecker
> README: fix typo in Contributing section

- community-membership.md
Kubernetes membership does not currently transfer from github/kubernetes to github/kubernetes-sigs due to the fact that on GitHub, they are different organizations. This pull request clarifies that any Kubernetes org member is automatically eligible for membership in related github orgs.
> Clarify membership requirements for related k8s github orgs

- committee-steering/governance/README.md
With the template updates in https://github.com/kubernetes/community/commit/32d184cee2ecb7c72f9de75e687f4a88f7c36413#diff-a068083f7bbb2cb58e8c350f4752056d we don't need as much explanation of these docs. Remove extra sentences and focus the goal.
> governance: shorten README based on template changes

- contributors/devel/cherry-picks.md
Searches for how to backport PRs to release branches are difficult if
you don't know what you're looking for. Add a sentence with that word to
make searching easier.
> Add a phrase to allow the word "backport" to be found

- contributors/design-proposals/scheduling/schedule-DS-pod-by-scheduler.md
This PR is to fix an issue that `NodeAffinity` section is mis-placed, and also add 4 spaces to make it indented properly.
> fix a mis-placed section in schedule-DS-pod-by-scheduler.md

- contributors/devel/godep.md
The documentation at [godep.md](https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md) explains the use of the `hack/run-in-gopath.sh hack/godep-restore.sh` command for restoring dependencies.
This is fine, but the `hack/run-in-gopath.sh hack/godep-restore.sh` command shows no progress information and often takes a lot of time.
So it's good to mention that if you want to see what is happening, you can use the `-v` flag to turn on the verbose mode of `godep restore`.
This pull request is about adding a sentence at the end of section [Restoring deps](https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md) explaining the possible use of the `-v` flag.
> Mention possibility to use -v flag when running godep-restore.sh

- contributors/guide/issue-triage.md
The kind/support is replaced with triage/support label, so replace references
accordingly.
> Use the triage support label

- contributors/guide/issue-triage.md
Since the fejta bot now actively triaging and closing issues, we should
mention it in the triage guidelines and if it has any impact on the usage of
the guidelines for closing issues. It should be helpful to anyone referencing
the guidelines specially to the new triagers.
> Mention fejta bot in the triage guidelines

- github-management/OWNERS
- github-management/README.md
- github-management/subproject-responsibilites.md
- sig-contributor-experience/README.md
- sig-contributor-experience/projects.md
- sigs.yaml
This creates the subproject proposed in #2367.
Fixes #2367.
> Establish GitHub Management Subproject

- contributors/devel/README.md
- contributors/devel/conformance-tests.md
- contributors/devel/e2e-tests.md
- contributors/guide/README.md
This PR create a  Conformance Document that provides a general guidelines when documenting a test as part of conformance test suite.
> Adding Conformance Guidelines document.

- contributors/design-proposals/storage/volume-topology-scheduling.md
- AllowedTopology -> AllowedTopologies (ref: https://github.com/kubernetes/kubernetes/pull/63233/files#diff-7dc0dea2b32ece49304df77954ffb69aR76) 
- AssumeVolumes -> AssumePodVolumes
- BindVolumes -> BindPodVolumes
> Keep naming consistent in volume-topology-scheduling.md

- contributors/guide/issue-triage.md
/hold
This updates docs as part of kubernetes/community#1579. The hold 
can be canceled once I've gotten permission from the community to 
proceed
> Remove mentions of priority/failing-test

- sig-cluster-lifecycle/README.md
- sigs.yaml
Fixes: https://github.com/kubernetes/community/issues/2419
> Update sigs.yaml to indicate that cluster-api-provider-gcp is owned by sig cluster lifecycle

- committee-steering/governance/sig-charter-template.md
This was a relative link before but as people copy the charter that
won't work. Make it a full URL instead.
> commitee-steering: link SIG Charter to SIG Governance

- sig-auth/README.md
- sig-auth/charter.md
- sigs.yaml
Add a sig-auth charter, based on the [sig-charter-template](https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-charter-template.md).
The first attempt at our charter is in https://github.com/kubernetes/community/pull/2000.
Co-authored by: @liggitt @mikedanese @tallclair
/sig auth
> sig-auth charter (v2)

- sig-service-catalog/README.md
- sig-service-catalog/charter.md
- sigs.yaml
Draft of the SIG Service Catalog charter. Announcement on SIG mailing list to follow.
The first commit contains the current working rules that the chairs have been following so far. Proposed changes are included in separate commits.
/cc @arschles @pmorie @vaikas-google @duglin
> SIG Service Catalog's charter

- contributors/guide/pull-requests.md
Hey all! 
This addresses the conversation from https://kubernetes.slack.com/archives/C1TU9EB9S/p1532528388000032
PRs can often get held due to the release cycle. SIGs should better communicate this when it happens, but we should also have something in the docs explaining that. 
Let me know if there's anything to add or change. :)
> add section on prs being held up by release cycle

- keps/sig-cloud-provider/providers/0005-cloud-provider-alibaba-cloud.md
Alibaba Cloud provides the Cloud Provider interface implementation as an out-of-tree cloud-controller-manager. It allows Kubernetes clusters to leverage the infrastructure services of Alibaba Cloud .
It is original open sourced project is [https://github.com/AliyunContainerService/alicloud-controller-manager](https://github.com/AliyunContainerService/alicloud-controller-manager)
Here we propose a repository under kubernetes orgnization to host Alibaba Cloud Provider code . It would be great benefit for people who want to run kubernetes on Alibaba Cloud.
> KEP proposals for adding Alibaba Cloud Provider into kubernetes ecosystem

- keps/sig-node/0014-runtime-class.md
As [previously discussed](https://docs.google.com/document/d/1mpjPTZkoeFV3tG59149KaIuI8LhIE-cekjFq8rRmNoQ/preview) in SIG-Node, here is the initial KEP for `RuntimeClass`.
This initial proposal excludes 2 important pieces: the supported features API, and the RuntimeController admission controller. My intent is to followup with another PR to add those, but let me know if those should be included here first.
/kind design
/sig node
> RuntimeClass KEP

- keps/sig-cloud-provider/0004-cloud-provider-documentation.md
> Add KEP for cloud provider doc maintenance

- keps/sig-auth/0014-dynamic-audit-configuration.md
Adds ability to configure policy dynamically in the `AuditConfiguration` resource.
> adds policy to dynamic audit kep

- sig-ibmcloud/OWNERS
Add owners file. Owners aliases and labels are already created.
> Add OWNERS file for sig-ibmcloud

- contributors/guide/README.md
This removes the disclaimer from the top of the contributor guide and just leaves a link for people to see the open issues and file their own. 
I also did a round of editing to the general document:
- Removed "check it out _here_" style links in favor of descriptive links.
- Reformatted it to use [semantic linefeeds](http://rhodesmill.org/brandon/2012/one-sentence-per-line/) so that future edit/diffs are easier to read. 
> Remove disclaimer and do one more round of copyediting

- sig-gcp/README.md
- sigs.yaml
> Add gcepd and filestore csi drivers to sig-gcp projects

- contributors/devel/conformance-tests.md
We have been talking about and progressing towards multi-arch support for a long while now: https://github.com/kubernetes/kubernetes/issues/38067
We have active work being done to ensure that container images used in e2e test suite can run across multiple architectures. So we should make sure we don't add to this debt.
- https://github.com/kubernetes/kubernetes/issues/66626
- https://github.com/kubernetes/kubernetes/issues/66618
> Advocate for running conformance tests in multiple architectures

- sig-contributor-experience/README.md
- sigs.yaml
ref: https://github.com/kubernetes/community/issues/2464
I'm guessing this is where this repo belongs if it's how the subproject
plans to automate away some of its toil
/cc @cblecker @fejta
> Add kubernetes/org to github-management subproject

- sig-contributor-experience/README.md
- sigs.yaml
Rename "contributor-guide" subproject to "contributor-documentation" per @parispittman 's recommendation to generalize the title.
Add contributor-site repo under "contributor-documentation". 
Fixes #2472
> Add contributor site to sigs.yaml

- contributors/design-proposals/api-machinery/customresource-conversion-webhook.md
CRD supports multiple version but no conversion between them (something called nopConverter which only change the apiVersion of the CR). With this proposal we introduced a conversion mechanism for CRDs based on an external webhook. Detail API changes, use cases and upgrade/downgrade scenarios are discussed.
/assign @deads2k @lavalamp @erictune @liggitt 
/cc @sttts @enisoc
You can find the original design doc and discussions [here](http://bit.ly/k8s-crd-conversion)
> KEP for CRD conversion webhook

- github-management/kubernetes-repositories.md
Added a new case I just ran into, and removed SIG Architecture from having
to be involved in the decision to archive (I view consulting SIG Arch as
part of the process for finding new active maintainers of the project, we
could bake this into the language if it needs to be explicit)
Formatting changes:
- Trimmed whitespace in the FAQ
- Unindented headers
- FAQ questions are now bold rather than italic
> github management: tweak repo removal language

- sig-docs/README.md
- sigs.yaml
Fixes #2470 
This PR:
- Updates the name and path of the Chinese i18n subproject to `kubernetes-docs-zh`.
- Adds subprojects for Japanese and Korean i18n.
> Add/correct i18n subprojects for SIG Docs

- sig-cluster-lifecycle/README.md
- sigs.yaml
Fixes #2471
Note that I also re-ordered a couple of subprojects to keep the overall list alphabetical. 
/cc @timothysc @luxas
> Add kubeadm-dind-cluster as a subproject of sig-cluster-lifecycle.

- keps/sig-cloud-provider/providers/0004-cloud-provider-template.md
- keps/sig-cloud-provider/providers/0020-cloud-provider-alibaba-cloud.md
- keps/sig-cloud-provider/providers/0021-cloud-provider-digitalocean.md
- keps/sig-cloud-provider/providers/0022-cloud-provider-baiducloud.md
This ensures that new (out-of-tree) providers are up to the same technical standards & meets the same requirements as existing in-tree providers. 
cc @calebamiles
> Expand requirements for new cloud providers

- generator/sig_readme.tmpl
- sig-api-machinery/README.md
- sig-apps/README.md
- sig-architecture/README.md
- sig-auth/README.md
- sig-autoscaling/README.md
- sig-aws/README.md
- sig-azure/README.md
- sig-big-data/README.md
- sig-cli/README.md
- sig-cloud-provider/README.md
- sig-cluster-lifecycle/README.md
- sig-contributor-experience/README.md
- sig-docs/README.md
- sig-gcp/README.md
- sig-ibmcloud/README.md
- sig-instrumentation/README.md
- sig-multicluster/README.md
- sig-network/README.md
- sig-node/README.md
- sig-openstack/README.md
- sig-release/README.md
- sig-scalability/README.md
- sig-scheduling/README.md
- sig-service-catalog/README.md
- sig-storage/README.md
- sig-testing/README.md
- sig-vmware/README.md
- sig-windows/README.md
This is a followup to https://github.com/kubernetes/community/issues/2324
Remove links to all of the google groups that correspond to the
k8s-mirror-* users thast were removed
> Remove github team google groups from SIG READMEs

- committee-steering/governance/sig-charter-template.md
A sigs.yml link isn't very helpful because the line numbers will keep
changing. Instead suggest people link to their subprojects in the SIG
README which is generated from the sigs.yml.
> committee-steering: remove sigs.yml link

- keps/0000-kep-template.md
I got a KEP accepted and ended up asking for a repo/org access later on. This adds an optional section to the KEP to ask for these upfront so people can think ahead of time if they need to ask for resources from their SIG so that these expectations are discussed up front.
> Add a resources needed section to the KEP template

- sig-cloud-provider/README.md
- sig-gcp/README.md
- sig-openstack/README.md
- sigs.yaml
Subprojects are about ensuring that code ownership ultimately
lands with a single SIG. There were a few cloud-provider-foo
subprojects that listed dual ownership due to ongoing
discussion of the future of some SIGs. I asked the SIG chairs
involved to make a decision about which SIG these subprojects
should fall to until that discussion is resolved.
cloud-provider-azure -> sig-azure
cloud-provider-gcp -> sig-cloud-provider
cloud-provider-openstack -> sig-cloud-provider
Fixes kubernetes/community#2516
> Ensure cloud-provider-foo subprojects have only one parent

- sig-docs/README.md
- sigs.yaml
Added a team, Korean l10n repository owners for sig-docs.
> Add Korean l10n repo owners for sig-docs

- sig-autoscaling/README.md
- sig-instrumentation/README.md
- sigs.yaml
This updates the mission statement for SIG Autoscaling to correspond to
the scope of SIG Autoscaling in the charter.
It also ensures that SIG Autoscaling has the right subprojects listed (cluster
autoscaler, vertical pod autoscaler, horizontal-pod-autoscaler, and
scale-client, cluster proportional autoscalers, addon-resizer), moving the
metrics project to SIG instrumentation where it belongs.
> Update SIG Autoscaling in sigs.yaml

- contributors/devel/conformance-tests.md
missing a critical part in run conformance test section:
user need to build e2e test binaries, kubectl, ginkgo before
launch test.
@BenTheElder
> improve conformance test document

- community-membership.md
This updates the community membership procedure, per the discussion kubernetes/community#2510.
As this is a wider reaching change, it will need a lazy consensus window. I will probably open that up on Monday, and run it until Thursday.
/cc @kubernetes/owners @mistyhacks @spiffxp 
fixes kubernetes/community#2510
> Update community membership procedure

- sig-testing/README.md
- sigs.yaml
I anticipate it will be some time before a team structure for all sigs is driven to conclusion https://github.com/kubernetes/community/issues/2323
In the meantime, I'd like to go ahead and prune sig-testing's teams manually:
- Rename sig-testing-misc to sig-testing
- Leave sig-testing-pr-reviews since I recall seeing that used when devstats was tracking this stuff
Everyone who's a member of the other teams is already a member of sig-testing-misc, so there will be no team membership changes.
NOTE: merging this does not actually remove the teams, it's something I will manually do as a request to kubernetes/org
> Prune sig-testing github teams

- contributors/guide/owners.md
In the description of how to assign reviewers to a pr it is not
explicitly mentioned, that the aliases used in OWNERS files should
be resolved before assigning.
Signed-off-by: Gergely Csatari <gergely.csatari@nokia.com>
> Refering to OWNERS_ALIASES from the assigning bulletpoint

- CLA.md
The word 'use' was used twice. Removed the extra word.
> Removing extra words (use)

- keps/sig-cluster-lifecycle/0015-kubeadm-join-control-plane.md
This PR updates `KEP0015 kubeadm join --master` with a `s/master/control-plane`, some additional details about the `kubeadm upgrade` workflow in case of many control plane instances + other small improvements.
/CC @timothysc @neolit123 @rosti
> Update KEP0015 kubeadm join --master

- events/elections/2018/README.md
- events/elections/README.md
This points to kubernetes/steering as the source of truth
for eligibility requirements for voting and candidacy
I also word wrapped the 2018 voting guide to 80 chars, which
makes for an awful diff, so I'll explain what I changed as
notes in the PR
I swear I didn't sneak in a "all votes secretly go to Aaron"
policy. Promise.  Really.
I would like for this to supersede https://github.com/kubernetes/community/pull/2542
> Rewrite 2018 voting guideline

- contributors/devel/testing.md
Small syntax fix for the timeout flag, should have quotes around `-timeout 300s`.
> syntax fix for testing doc

- sig-api-machinery/README.md
- sig-architecture/README.md
- sigs.yaml
Per discussion in https://github.com/kubernetes/utils/issues/44 I'm
suggesting a move of the kubernetes/utils subproject to sig-arch
I also think sig-arch should own deciding where to move code that
currently lives in k/contrib. This is the last repo not yet included in
sigs.yaml (ref: https://github.com/kubernetes/community/issues/2464)
I have added each of these as their own subprojects. Another approach
could be to make a "code-organization" subproject, and place both of
these repos under that
WDYT?
/cc @thockin @lavalamp
/hold
for comment
> Move k/utils to sig-arch, add k/contrib to sig-arch

- contributors/design-proposals/node/plugin-watcher.md
This PR is for adding design of an already merged feature. [Original design was on gdoc](https://docs.google.com/document/d/1dtHpGY-gPe9sY7zzMGnm8Ywo09zJfNH-E1KEALFV39s/edit#heading=h.7fe6spexljh6). With some updates adding the same here for better tracking.
/cc @tengqm @derekwaynecarr @vishh @jiayingz @ConnorDoyle @dchen1107 @RenaudWasTaken  @sjenning
> Add plugin watcher design

- keps/sig-cluster-lifecycle/0014-20180707-componentconfig-api-types-to-staging.md
Some minor changes to the initial KEP after further discussions in the sig-api-machinery Slack channel.
Builds on top of https://github.com/kubernetes/community/pull/2354 and marks it as `implementable`.
We have now submitted and merged the ~5 first PRs of this effort, with more PRs planned and in the reviewing stage. We hope to get all of this implemented by v1.12 code freeze.
The additions to this version is that we've decided on a defaulting story, and know a bit more about the actual implementation plan, and know what tests to write up for the MVP.
Again, mentioning the SIGs that are affected by this proposal:
@kubernetes/sig-cluster-lifecycle-pr-reviews @kubernetes/sig-api-machinery-pr-reviews @kubernetes/sig-architecture-api-reviews @kubernetes/sig-node-pr-reviews …
> Move the ComponentConfig types to staging KEP to implementable

- mentoring/group-mentoring.md
Picks the commit from https://github.com/kubernetes/community/pull/2006 since it has been open from April and has not had responses from the author. I fixed the nit and rebased.
Authorship is still maintained. It was @erinboyd's idea after all. :)
/assign parispittman cblecker
> Add a benefit for group mentoring

- sig-api-machinery/README.md
- sigs.yaml
It will be a subproject of sig-apimachinery.
@deads2k @lavalamp I checked how kubebuilder opened its own repo. They updated these sig files and then sent an email to kubernetes-sig-architecture@ to create the repo.
> Adding kube-storage-version-migrator repo

- sig-docs/README.md
- sigs.yaml
> Add Japanese l10n repo owners for sig-docs

- sig-storage/README.md
- sig-storage/charter.md
- sigs.yaml
Charter for @kubernetes/sig-storage-misc 
/assign @childsb for initial pass. Will assign to TOC for approval once we have internal SIG storage consensus.
Also closes https://github.com/kubernetes/community/issues/2467
> SIG-storage charter

- contributors/design-proposals/node/troubleshoot-running-pods.md
This proposes an API for Debug Containers that's idiomatic for Kubernetes and uses the existing `Container` definition. This makes it easier for admission controllers to gate these updates.
The previous Debug Containers proposal avoided changing the core API as much as possible.
> Use v1.Container in Debug Containers API

- sig-node/README.md
- sig-node/charter.md
Co-authored by: @derekwaynecarr @dchen1107 
/sig node
Topics for discussion with @kubernetes/steering-committee review:
1.  working group lifecycle - this proposal empowers a technical lead of a sig to sponsor a working group.  if working groups span sigs, this would mean agreement from a technical lead from each sponsoring sig may be required, and therefore should be common across the project.
1. process to decommission a sub-project - could be a variety of reasons (not healthy, not maintained, no longer endorsed or accepted by the sig).  this proposal makes no statement on the mechanism other than stating technical leads should have the power.
> [RFC] SIG-Node initial charter

- contributors/devel/e2e-tests.md
As detect-master method[1] of the provider "local", the variables
of KUBE_MASTER and KUBE_MASTER_IP are hardcoded. Then it is not
necessary to specify them on user side. In addition, the original
description shows KUBE_MASTER=local, but that is completely wrong
that should be localhost as the code[1].
This patch removes this unnecessary discription.
[1]: https://github.com/kubernetes/kubernetes/blob/2bdae8f3d047f1042822f4ab1aff1bf5a6c8b6bf/cluster/local/util.sh#L21
> Remove unnecessary discription of provider "local"

- contributors/design-proposals/storage/data-source.md
propose to add data source for volume operations including provisioning
volume from snapshot, and cloning volumes. This is part of the CSI snapshot proposal too https://github.com/kubernetes/community/pull/2335
> Add data source for volume provisioning

- contributors/design-proposals/storage/container-storage-interface-skip-attach.md
In this proposal, we describe a way how to skip creation of `VolumeAttachments` for non-attachable CSI drivers.
Benefits:
* Admins don't need to deploy external attacher for non-attachable CSI drivers. It was very confusing to them, they could not understand why they should run an attacher for non-attachable drivers. Now they won't need to do it.
* Somewhat faster pod startup
This PR depends on ~~`CSIPlugin`~~ `CSIDriver` introduced in https://github.com/kubernetes/community/pull/2514
> CSI: Skip attach/detach for non-attachable volumes

- sig-instrumentation/charter.md
This PR is currently work in progress and meant for sig-instrumentation to iterate on its charter document.
@kubernetes/sig-instrumentation-misc
> sig-instrumentation: Add charter document

- keps/sig-cloud-provider/0019-cloud-provider-documentation.md
Add manifest examples for out-of-tree providers as part of cloud provider docs. 
Follow up to https://github.com/kubernetes/community/pull/2442
> Include out-of-tree provider examples to cloud provider docs KEP

- contributors/guide/non-code-contributions.md
Creating a more thorough list of possible roles for the non-code contributor guide, for issue #2325.
This list was discussed during the SIG-ContribX meeting on August 29.
Signed-off-by: <jrosland@vmware.com>
> Adding more details into the non-code contributor guide roles

- generator/sig_readme.tmpl
- sig-api-machinery/README.md
- sig-apps/README.md
- sig-architecture/README.md
- sig-auth/README.md
- sig-autoscaling/README.md
- sig-aws/README.md
- sig-azure/README.md
- sig-big-data/README.md
- sig-cli/README.md
- sig-cloud-provider/README.md
- sig-cluster-lifecycle/README.md
- sig-contributor-experience/README.md
- sig-docs/README.md
- sig-gcp/README.md
- sig-ibmcloud/README.md
- sig-instrumentation/README.md
- sig-multicluster/README.md
- sig-network/README.md
- sig-node/README.md
- sig-openstack/README.md
- sig-release/README.md
- sig-scalability/README.md
- sig-scheduling/README.md
- sig-service-catalog/README.md
- sig-storage/README.md
- sig-testing/README.md
- sig-vmware/README.md
- sig-windows/README.md
Follow up of https://github.com/kubernetes/community/pull/2500
For https://github.com/kubernetes/community/issues/2324
/cc cblecker spiffxp 
/assign cblecker 
> generator: remove github team google groups note from all SIG READMEs

- sig-scalability/block_merges.md
- sig-scalability/charter.md
@kubernetes/sig-scalability-api-reviews 
@countspongebob @shyamjvs @wasylkowski-a @gmarek 
cc-ing everyone who was on the initial version:
/cc @thockin @smarterclayton @spiffxp @jdumars @bgrant0607 @timothysc
> SIG Scalability Charter

- contributors/devel/conformance-tests.md
I think this may have been relying on this feature which was moved/removed:  https://github.com/kubernetes/kubernetes/commit/4bf2ef646f5937c2d6eb49093fad15cfe65e7aae#diff-b67911656ef5d18c4ae36cb6741b7965L103
> Fix conformance test instructions for building Ginkgo

- sig-scalability/charter.md
ref: https://github.com/kubernetes/community/pull/2149#pullrequestreview-151505249
> Fix scalability charter typos

- keps/sig-apps/0026-ttl-after-finish.md
This resolved the issue with the frontmatter for kep-26 failing to render for both github and hugo (contributor site).  This is due to the `@` symbol being a reserved [yaml indicator](http://yaml.org/refcard.html) and must be quoted when it is used as the leading character in a string. 
/cc @castrojo
> fix yaml formatting in kep 26 frontmatter

- sig-api-machinery/README.md
- sigs.yaml
I need a place to put the following things.
* test vectors for apply (framework started in https://github.com/kubernetes/kubernetes/pull/67098)
* home for current apply code (move begun in https://github.com/kubernetes/kubernetes/pull/67101)
* home for subsequent apply code (building on this https://github.com/kubernetes/kubernetes/pull/67458)
I could put this in staging (as in the above PRs) but it's not necessary, and I prefer the versioning story if I don't.
This is part of what the Apply working group needs to do; since WGs don't own code, API Machinery will own this code, under the "idl-schema-client-pipeline" subproject.
> Add repo for serverside apply test cases & code

- sig-instrumentation/README.md
- sig-storage/README.md
- sigs.yaml
As I was reviewing other staging repos, I noticed two of them
weren't listed here in sigs.yaml. I don't really know whether
listing both the staging OWNERS and published OWNERS is any
better or worse than just listing one, so I leaned in the
direction of consistency
> Match other staging repos, both OWNERS files listed

- sig-storage/contributing.md
**What and Why**  
I was reading the contribution documentation for the storage sig and noticed a small typo where "Kubernetes" was accidentally misspelled.  
I've made this mistake countless times so I figured I'd fix it while I was in the area.
**Related issues**  
https://github.com/kubernetes/community/issues/2644
> Fixed typo in sig storage contributing docs

- contributors/devel/cri-testing-policy.md
- contributors/devel/cri-validation.md
- keps/sig-node/0014-runtime-class.md
cri-tools has been moved to https://github.com/kubernetes-sigs/cri-tools.
> Update links of cri-tools

- committee-steering/governance/sig-governance.md
/priority important-soon
I've heard this referred to as sunsetting elsewhere, but using the term
"retirement" to line up with us retiring projects to the
kubernetes-retired GitHub org.
SIG Cluster Ops is effectively retired due to lack of consistent quorum
(ref: #2031). Here's a swag at describing why, to use as policy to 
retire inactive SIGs in the future.
This is a very tiny start to the "why" of https://github.com/kubernetes/community/issues/2029 not necessarily the "how"
> Add sig retirement criteria (inactivity only)

- sig-testing/README.md
- sigs.yaml
ref: https://github.com/kubernetes/org/issues/86
A few misc cleanup nits while I was there:
- word-wrap the description for testing-commons
- alphabetize the subprojects
> Add kind to sig-testing subprojects

- sig-service-catalog/README.md
- sigs.yaml
- wg-app-def/README.md
- wg-multitenancy/README.md
The links are taken from the meeting notes document: https://docs.google.com/document/d/1fj3yzmeU2eU8ZNBCUJG97dk_wC7228-e_MmdcmTNrZY/edit?usp=sharing.
/assign @jessfraz @davidopp
> Add meeting recordings for wg-multitenancy and fix charters

- sig-storage/README.md
- sigs.yaml
Add this to sig-storage's external-storage project since that's
the repo this originated from
ref: https://github.com/kubernetes/org/issues/88
/cc @saad-ali @childsb
> Add kubernetes-sigs/sig-storage-lib-external-provisioner

- contributors/devel/flaky-tests.md
We have a good document on investigating flaky tests, but it can
be hard to correlate personal experience (my PR wont pass presubmits!?!)
with broader CI health (did AWS go down?).  For that portion of
triage it's useful to look at some aggregated statistics and we have
two nice pages for that.
I'm always forgetting these two links though and while some kind
folks have reminded me repeatedly, I take that as a sign it's time
to put them somewhere more visible.
> devel guide: note where to track flaky tests

- sig-scheduling/charter.md
> Add a charter for SIG Scheduling

- sig-ibmcloud/charter.md
Add charter for IBMCloud SIG. This PR is reviewed and discussed in the SIG meeting.
> Add sig-ibmcloud Charter

- contributors/guide/README.md
Use the git.k8s.io shortener for the issues labelled with `good-first-issue` in Contributor Guide.
> Add the redirection for the issues labeled with `good-first-issue`

- contributors/guide/bug-bounty.md
First attempt at the scope for Kubernetes bug bounty program.
I wasn't sure here to put the file. LMK if you have a better idea.
/assign @cjcullen @liggitt @philips @jessfraz
/cc @destijl @mayakacz
> Initial bug-bounty scope

- keps/0001a-meta-kep-implementation.md
This is a provisional meta-KEP, which discusses iterative improvements to the KEP process.
rel:
- https://github.com/kubernetes/community/issues/2565
- SIG Architecture meeting mentioning the need for a clearer KEP process - https://youtu.be/MMJ-zAR_GbI
- SIG Architecture meeting agreeing to move forward with a KEP process improvement effort to be co-led with SIG PM (@justaugustus / @jdumars) - https://youtu.be/fmlXkN4DJy0
/sig pm architecture
/assign @jdumars @calebamiles @idvoretskyi @timothysc 
> KEP-1a: Meta KEP Implementation

- keps/sig-azure/0025-20180809-cross-resource-group-nodes.md
> Make Azure cross resource group nodes KEP to implementable

- keps/0001a-meta-kep-implementation.md
- Update `status`
- Update `reviewers`
- Update `last-reviewed`
- Update implementation history
Adds links for KEP Implementation:
- tracking board: https://github.com/orgs/kubernetes/projects/5
- tracking issue: https://github.com/kubernetes/features/issues/617
Closes: https://github.com/kubernetes/community/issues/2728
/sig pm architecture
/assign @calebamiles @jdumars @idvoretskyi
> KEP-1a: Mark as implementable

- contributors/design-proposals/storage/container-storage-interface.md
This proposal depends on the following design changes:
Topology-aware dynamic provisioning design: https://github.com/kubernetes/community/pull/1857
CSI spec modifications related to topology: https://github.com/container-storage-interface/spec/pull/188/
/sig storage
/assign @saad-ali
/cc @vladimirvivien
> Topology updates to Kubernetes CSI implementation

- contributors/devel/automation.md
- contributors/devel/e2e-tests.md
- contributors/devel/flaky-tests.md
- contributors/devel/writing-good-e2e-tests.md
- contributors/guide/contributor-cheatsheet.md
- contributors/guide/owners.md
- contributors/guide/pull-requests.md
Ref: https://groups.google.com/d/topic/kubernetes-dev/sp0dOVt4WsA/discussion
The submit queue is also mentioned in many places in `sig-scalability/` but I don't want to correct them in this PR since it touches their charters, etc.
/cc @spiffxp @cblecker @BenTheElder @guineveresaenger
> Replace submit queue with Tide in docs

- README.md
- committee-steering/governance/README.md
- governance.md
- sig-governance.md
We talked about some of this during the Steering committee meetings.  I don't think any of this should be controversial.
> Various governance clarifications

- contributors/devel/release.md
I incorrectly had indicated a milestone was required in each of the four
major phases of the release cycle, where it is not in the "normal dev"
phase.  Not sure how we got that through review.  Part of it may have
been the html table format.  To help with that, in addition to removing
the errant indication of milestone as required in that early period,
I've also added html comments in the table so the reader of the raw code
can more clearly see which section is which.
> release docs: clarify tldr table html

- wg-security-audit/OWNERS
Looks like it got missed in https://github.com/kubernetes/community/pull/2767 :)
Related: https://github.com/kubernetes/test-infra/pull/9744 will add the label.
/cc @jessfraz
> wg-security-audit: add OWNERS file

- committee-steering/governance/sig-governance-requirements.md
- committee-steering/governance/sig-governance.md
- sig-azure/charter.md
- sig-cloud-provider/CHARTER.md
As it’s been used elsewhere in this repo already
> Use better reference links for lazy consensus

- contributors/devel/development.md
While trying to fix https://github.com/kubernetes/kubernetes/issues/62577
I noticed my system was lacking `rsync` installed, which was required to
have `make` and `make test` working.
> Add rsync as development dependency

- CLA.md
If you have to create your Linux Foundation account when clicking the links in Step 1, then the HelloSign email is not automatically sent and you have to go back and click it again. It definitely confused me.
I was thinking about changing Step 1 to only have one link to https://identity.linuxfoundation.org/projects/cncf, since on that page there are links for individual contributor or corporation.
I also opted to not use "Log in with GitHub", but created the account first, and then later I linked my GitHub account. I do not know if the ordering matters, and this might be why I didn't receive my HelloSign email after signing up.
> CLA clarification

- committee-steering/governance/wg-governance.md
- governance.md
> Clarify process for Working Group formation

- contributors/design-proposals/cli/preserve-order-in-strategic-merge-patch.md
Fix some typos like : a->an an-a 
does not keeping->does not keep
2 requirement->2 requirements
will be come before->will come before
to be merge->to be merged
> Fix some typos in preserve-order-in-strategic-merge-patch.md

- committee-code-of-conduct/README.md
- communication/moderation.md
- contributors/guide/contributor-cheatsheet.md
Now that we have a Code of Conduct Committee for Kubernetes, people should contact our private email list going forward with any problems.
> Update Code of Conduct page with new email

- contributors/devel/cherry-picks.md
Partial attempt to improve contributor experience on cherrypicks; this updates/clarifies some information in cherrypick instructions.
/sig release
/cc @tpepper @justaugustus @cblecker @spiffxp 
reference for tracking work on automation: https://github.com/kubernetes/test-infra/issues/1795
> Cherrypicks

- sig-testing/charter.md
/cc @fejta @stevekuznetsov @timothysc
sig chairs
FYI @kubernetes/sig-testing
> Add SIG Testing charter

- keps/sig-network/0030-nodelocal-dns-cache.md
This KEP aims to improve kube-dns performance by running a nodelocal dns cache. 
@thockin @bowei @johnbelamaric @sdodson
> KEP: NodeLocal DNS Cache

- sig-multicluster/README.md
- sig-multicluster/charter.md
- sigs.yaml
Replaces #1989 as a WIP for SIG multicluster charter.
> SIG Multicluster charter

- contributors/design-proposals/api-machinery/customresource-conversion-webhook.md
The defaulting section of customresource webhook conversion KEP was backward incompatible. This PR suggest a new approach. Different approaches as well as the problem description is detailed in [this document](http://bit.ly/k8s-crd-per-version-defaulting).
@liggitt @lavalamp @deads2k @sttts @erictune @roycaihw
> Add per version field section to custom resource webhook conversion KEP

- sig-contributor-experience/README.md
- sig-contributor-experience/devstats/OWNERS
- sig-contributor-experience/devstats/README.md
- sigs.yaml
Subprojects are supposed to be based on OWNERS files, even if they
are purely non-technical with no code they should still have docs
that explain what they are and how they operate.
I added a skeleton readme for devstats, and an OWNERS file. I added
jberkus and myself as approvers in addition to Phillels as I feel
we have done substantial work with devstats, if nothing else through
graph of the week presentations at community.
> Redo devstats as a subproject

- sig-cluster-lifecycle/README.md
- sigs.yaml
This PR adds DigitalOcean Cluster-API provider to `sigs.yaml` after the initial migration is done.
Relevant issue https://github.com/kubernetes/org/issues/196
> sigs.yaml: add DO Cluster-API provider as SIG Cluster Lifecycle subproject

- keps/sig-node/0008-20180430-promote-sysctl-annotations-to-fields.md
Fix for #2696
FILE: ./keps/sig-node/0008-20180430-promote-sysctl-annotations-to-fields.md
[✖] https://kubernetes.io/docs/reference/feature-gates/ → Status: 404
> Fix feature-gates link 

- sigs.yaml
- wg-security-audit/README.md
I don't think [PR 2872](https://github.com/kubernetes/community/pull/2872) used the generator to update wg leads. Including that in this PR.
We are ready to publish the RFP for the third party security audit. Added link to RFP in wg-security-audit README.md.
CC: @cblecker @joelsmith @cji
> Update wg-security-audit leads; include RFP link in readme.md

- sig-cluster-lifecycle/README.md
- sigs.yaml
Ref:
- https://github.com/kubernetes/org/issues/137
- https://github.com/kubernetes/kubernetes/blob/master/staging/README.md#creating-the-published-repository
/cc @yliaog @timothysc @roberthbailey @luxas
> sig-cluster-lifecycle: add cluster-bootstrap under the kubeadm subproject

- contributors/devel/logging.md
This patch add Trace level logging to Logging Conventions.
Maybe, our logging guidelines need a TRACE level.
I think having the right density of Trace messages makes k8s much more maintainable.
ref:
https://github.com/kubernetes/kubernetes/issues/69743
> Add Trace level logging

- contributors/devel/api_changes.md
Based on
https://docs.google.com/document/d/1Z8Vbo7RmV_Wvs4k8mluHQC2_Zs8cEwMJmHwWBf9BcaA/edit
and email discussions.
Resist the urge to clean up the whole doc - that will have to come
later.
> Document pluralization of API fields

- contributors/devel/OWNERS
Add @thockin and @lavalamp to approvers list for `contributors/devel/`. There's a bunch of legacy docs in there, including the api conventions. Also, alpha sort list.
> Add thockin and lavalamp to devel OWNERS

- CLA.md
Some folks may be unaware that their company has signed or needs to sign a CLA if they are contributing to Kuberentes as part of their job. This sentence prompts them to check their company legal representation first so they don't sign an individual contributor license.
Addresses https://github.com/kubernetes/community/issues/1794.
> Clarify employee CLA

- contributors/design-proposals/apps/deployment.md
- contributors/devel/automation.md
- keps/sig-cli/0024-kubectl-plugins.md
Signed-off-by: mooncake <xcoder@tenxcloud.com>
Fix typos: creats -> creates
> Fix typos: creats -> creates

- contributors/guide/owners.md
> Fix plugin links in owners documentation

- sig-architecture/README.md
- sigs.yaml
Followup to #2895
- removed teams link from owners as requested
- specifically called out steering as a placeholder
- add k/k test/conformance/OWNERS to conformance-definition, that's code involved in enforcing the conformance test list
/hold
EDIT: for reasons that I have now added to the bullet list
> Link to custom subproject descriptions, remove team from owners

- generator/app.go
- generator/sig_readme.tmpl
- sig-auth/README.md
- sig-testing/README.md
- sigs.yaml
Transplanted from:
https://docs.google.com/document/d/1RJvnSPOJ3JC61gerCpCpaCtzQjRcsZ2tXkcyokr6sLY/edit
I talked about this with @spiffxp in slack. Our current subprojects are generally cross cutting. The TLs for these subprojects don't roll up to specific OWNERS files generally. However, the convetions for the SIG README seems to be that subproject owners should be URLs to OWNERS files. Is this an issue?
cc @liggitt @tallclair 
Fixes #2505
> add subprojects for sig-auth

- sig-apps/README.md
- sig-apps/charter.md
- sigs.yaml
@bgrant0607 @philips @kow3ns @prydonius 
Here is another take on the SIG Apps charter following the new template. @kow3ns @prydonius look ok?
> Adding SIG Apps Charter

- contributors/devel/godep.md
Updating a vendored dependency can be a helpful thing to do, but every update carries risks of new bugs, security concerns, license issues, subtle behavioral changes, and time.  To avoid unnecessary risk, we only want to update vendored dependencies when the change can be justified for the health of the project or the ecosystem.  This pull enumerates those justifications.
/assign @thockin
> add acceptable justifications for updating a godep

- keps/sig-network/0030-nodelocal-dns-cache.md
@thockin @bowei @johnbelamaric
> Follow up edits on the nodelocaldns KEP

- keps/sig-node/compute-device-assignment.md
/cc @kubernetes/sig-node-api-reviews @kubernetes/sig-node-proposals @dashpole  @derekwaynecarr @dchen1107 @jiayingz @thockin @vishh @sjenning @jeremyeder 
/sig node
> KEP: Support Device Monitoring

- sig-release/README.md
- sigs.yaml
SIG Release GitHub teams have been updated in https://github.com/kubernetes/sig-release/issues/353, so reflecting that in our contact info as well.
/assign @calebamiles @tpepper @jdumars
> Update SIG Release contact information

- contributors/devel/vagrant.md
Adding a note that support for vagrant has been removed from kubernetes versions >= 1.10
> Adding deprecation note for vagrant support

- contributors/guide/issue-triage.md
Fixes https://github.com/kubernetes/community/issues/1757
We have [guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/help-wanted.md) for `help wanted` and `good first issue` labels but these guidelines should also be pointed out in the issue triage doc.
/assign @guineveresaenger
> issue triage: add help-wanted and good-first-issue details

- keps/sig-cluster-lifecycle/0031-20181022-etcdadm.md
This resolved an issue with the frontmatter header for kep-31 failing to render as metadata  for both github and hugo (contributor site).  This is due to the `@` symbol being a reserved [yaml indicator](http://yaml.org/refcard.html) and must be quoted when it is used as the leading character in a string. 
/cc @castrojo
> Fix yaml formatting in kep 31 metadata

- keps/sig-cloud-provider/providers/0004-cloud-provider-template.md
- keps/sig-cloud-provider/providers/0020-cloud-provider-alibaba-cloud.md
- sig-cluster-lifecycle/charter.md
- sig-docs/migrated-from-wiki/roadmap-docs.md
FILE: ./keps/sig-cloud-provider/providers/0020-cloud-provider-alibaba-cloud.md
[✖] https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0003-testgrid-conformance-e2e.md
→ Status: 404
FILE: ./keps/sig-cloud-provider/providers/0004-cloud-provider-template.md
[✖] https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0003-testgrid-conformance-e2e.md
→ Status: 404
[✖] https://github.com/kubernetes/community/blob/master/keps/sig-cloud-provider/0004-cloud-provider-documentation.md
→ Status: 404
FILE: ./sig-docs/migrated-from-wiki/roadmap-docs.md
[✖] https://git.k8s.io/kubernetes/examples/guidelines.md → Status: 404
FILE: ./sig-cluster-lifecycle/charter.md
[✖] ../sig-apimachinery → Status: 400 Error: ENOENT: no such file or
directory, access …
> Broken Links Fix for #2696

- contributors/design-proposals/autoscaling/hpa-v2.md
Really minor thing, but this make the example copy-pastable.
> add metadata name to HPA v2 example

- keps/sig-auth/0014-dynamic-audit-configuration.md
- keps/sig-cluster-lifecycle/0003-cluster-api.md
- sig-apps/agenda.md
- sig-cli/migrated-from-wiki/roadmap-kubectl.md
FILE: ./keps/sig-cluster-lifecycle/0003-cluster-api.md
[✖] https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1alpha1/types.go
→ Status: 404
FILE: ./keps/sig-auth/0014-dynamic-audit-configuration.md
[✖] http://github.com/kubernetes/community/blob/master/Users/patrick/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go
→ Status: 404
FILE: ./sig-apps/agenda.md
[✖] www.github.com/kubernetes/helm → Status: 400 Error: ENOENT: no such
file or directory, access
'/home/jorge/src/kubernetes/community/sig-apps/www.github.com/kubernetes/helm'
[✖] https://deis.com/ → Status: 0 Error: ETIMEDOUT
FILE: ./sig-cli/migrated-from-wiki/roadmap-kubectl.md
[✖] http://kubernetes.sh/kploy/ → Status: 404
> Fix for #2696

- contributors/devel/release.md
I don't think we've ever enforced the documented post-freeze merge requirements. AFAIK we have always returned to normal merge requirements when freeze ends.
/cc @AishSundar @tpepper @amwat
> Change post-freeze merge requirements to reference dev phase requirements.

- events/2018/12-contributor-summit/README.md
Once we have the final PDF for the schedule we'll inline the image and
remove the markdown table.
> Add link to calendar and update the schedule table

- keps/sig-apps/sidecarcontainers.md
This is my initial thoughts on the concept of the sidecar container to address https://github.com/kubernetes/kubernetes/issues/25908
Hopefully this can prompt some discussion around the issue as I think it's something that a fair amount of people would like to be addressed.
> kep-sidecar-containers

- keps/sig-cluster-lifecycle/0032-create-a-k8s-io-component-repo.md
Markdown proposal based on this google doc: https://docs.google.com/document/d/1nZnzJD9dC0xrtEla2Xa-J6zobbC9oltdHIJ3KKSSIhk/edit
Will be presented to @kubernetes/sig-architecture-api-reviews in a meeting soon.
cc @kubernetes/sig-cluster-lifecycle-pr-reviews @kubernetes/sig-api-machinery-pr-reviews (owning SIGs)
cc @kubernetes/sig-cloud-provider-pr-reviews @kubernetes/sig-node-pr-reviews @kubernetes/sig-scheduling-pr-reviews @kubernetes/sig-network-pr-reviews (component owners affected by this change)
xref: https://github.com/kubernetes/community/pull/2354 https://github.com/kubernetes/community/pull/2515
/assign @thockin 
/assign @bgrant0607 
/assign @smarterclayton 
/assign @jbeda
> KEP: Create a `k8s.io/component` repo

- contributors/devel/testing.md
The test_flag url to go doc has been changed, so the testing guide should be fixed correspondingly.
> fix a changed url in contributors/devel/testing.md

- code-of-conduct.md
Make it easier to find out who to contact quickly, without following a bunch of links.
> Link to CoCC from our CoC page

- sig-api-machinery/charter.md
As per the request, drafted SIG API Machinery charter file.
> Create api-machinery charter.md

- contributors/devel/logging.md
Following the move from `glog` to `klog` in https://github.com/kubernetes/kubernetes/pull/70889 this updates the devel logging docs to reference `klog` over `glog`.
Signed-off-by: Christopher Hein <me@christopherhein.com>
/cc @dims
> Change devel guide glog references to klog

- contributors/devel/api-conventions.md
We have non-compliant conditions in use and we use one as an example.
Be clearer in the doc.
> Add a bit more on conditions

- contributors/devel/instrumentation.md
> Fix typo in instrumentation.md: "into" -> "in"

- contributors/design-proposals/autoscaling/vertical-pod-autoscaler.md
In document `vertical-pod-autoscaler.md`, the link to file `resource-qos.md` was broken. I changed with this one:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md
> Fix link 404 to resource-qos.md in vertical-pod-autoscaler.md

- github-management/kubernetes-repositories.md
- github-management/permissions.md
Fixes a bunch of markdown formatting issues in github-management.
Before:
- [`kubernetes-repositories.md`](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md)
- [`permissions.md`](https://github.com/kubernetes/community/blob/master/github-management/permissions.md)
After:
- [`kubernetes-repositories.md`](https://github.com/nikhita/community/blob/5ac0d22c14cc94902d03e0b01b720ef6a41f61af/github-management/kubernetes-repositories.md)
- [`permissions.md`](https://github.com/nikhita/community/blob/5ac0d22c14cc94902d03e0b01b720ef6a41f61af/github-management/permissions.md)
> github-management: fix markdown formatting

- sig-scalability/README.md
- sig-scalability/processes/scalability-validation.md
- sigs.yaml
Moving it from https://github.com/kubernetes/sig-release/tree/master/ephemera to here as this is where the doc should rightfully reside IMO. Also that directory is intended to be short-lived.
/cc @wojtek-t
> Add release scalability validation doc

- governance.md
Related issue: https://github.com/kubernetes/community/issues/3059
> Fix the broken link to the repository guidelines in the governance.md

- sig-release/README.md
- sig-testing/README.md
- sigs.yaml
Specifically
- add boksos, gopherage, gubernator and prow to
sig-testing
- move sig-testing's "repo-publishing" to sig-release
as "publishing-bot"
- rename sig-release's "release" to "release-team" and
add the release-team/OWNERS to owners
- add descriptions to sig-release subprojects
I did the SIG Release stuff while I was there, I can punt that if it's
too scope creepy. Main thing was I looked back and publishing-bot was
added in by someone from API Machinery. Neither of the people listed as
approvers for that codebase have ever attended SIG Testing. It seems
more like up SIG Release's alley than having anything to do with
Testing.
I chose the SIG Testing subprojects based on those= which seemed like they
could conceivably be extracted into their own repos if we someday wanted to.
There …
> Adjust subprojects for sig-testing, sig-release

- mentoring/google-summer-of-code.md
- mentoring/outreachy.md
Adds the #gsoc-apps slack channel and slack usernames of coordinators. 
/cc @parispittman @idvoretskyi
> mentoring: add slack details for GSoC

- sig-storage/README.md
- sigs.yaml
Add staging repo: staging/src/k8s.io/csi-translation-lib
Remove repo kubernetes-csi/kubernetes-csi-migration-library which will be superseded by new staging repo: staging/src/k8s.io/csi-translation-lib
Related to https://github.com/kubernetes/org/issues/321#issuecomment-452837675
Depends on https://github.com/kubernetes/kubernetes/pull/72770 where above repo is populated.
/cc @msau42 @davidz627 @leakingtapan
> Update SIG Storage with info around csi-translation-lib

- sig-auth/archive/meeting-notes-2016.md
- sig-auth/archive/meeting-notes-2017.md
- sig-auth/archive/meeting-notes-2018.md
Convert the [sig-auth meeting notes](https://docs.google.com/document/d/16vJcIjvgYhu06ucXx_QXk_yzclyPxWED693jkrHg6PA/edit#) to markdown with a docs addon, and push to the community repo for a record. Yearly versions restored from version history & cleaned up. This will let us delete the old notes from the agenda doc, which is getting a bit slow to load due to its size.
/sig auth
/assign @liggitt @mikedanese @enj
> Add sig-auth meeting note archive to github

- contributors/devel/release.md
We decided a clear warning to brace for code freeze was sufficient,
and a whole extra delineated phase wasn't worth the effort. We'll
still remind folks not to do mean things like land massive changes
or refactors N days before code freeze.
ref: kubernetes/sig-release#269
/sig release
/cc @tpepper
> Remove code slush

- sig-contributor-experience/charter.md
Trying this charter thing out again since the mistake during the recent outage merged to master. Ref #2810.  
Incorporated most of @spiffxp's review from #2810 except the GitHub management bullets which I'd rather have @cblecker weigh in directly about. Expecting another edit.
> Contributor Experience Charter

- sig-node/archive/meeting-notes-2015.md
- sig-node/archive/meeting-notes-2016.md
- sig-node/archive/meeting-notes-2017.md
- sig-node/archive/meeting-notes-2018.md
Auto generated from https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit# using an apps script. The formatting isn't perfect, but I thought it was close enough for archival purposes.
Note that I omitted today's (Jan 08) meeting. I recommend we delete everything prior to Jan 08 in the existing agenda doc, and push yearly updates here.
/sig node
/assign @dchen1107 @derekwaynecarr
> Add historical sig-node agenda archive

- contributors/devel/adding-an-APIGroup.md
The file adding-an-APIGroup.md is a stub file with more than 90 days.
/kind feature
/assign @cblecker @lavalamp 
/cc @parispittman @nikhita
> Deleting stub file that is more than one year old

- contributors/guide/release-notes.md
Incorporates the review from #3021 
(Doing this because that PR stalled out.)
/assign @guineveresaenger @castrojo @parispittman
> Fix cherry-pick link

- contributors/devel/how-to-doc.md
Ref. #3064 
how-to-doc.md is a file in /devel that is outdated. Links in other files fixed.
/cc @parispittman @nikhita 
/assign @cblecker @idvoretskyi 
/area developer-guide
/kind cleanup
> Deleting outdated stub file

- contributors/devel/OWNERS
This PR adds the `area/developer-guide` label to the OWNERS file in `devel`, so that the label is automatically applied for PRs targeting it. This will help in triaging @eduartua's work in that area as well.
/hold
https://github.com/kubernetes/test-infra/pull/10876 will actually create that label. Hold until it is merged.
> devel: add area/developer-guide label

- github-management/OWNERS
- github-management/README.md
[kubernetes-sig-contributor-experience@ thread](https://groups.google.com/d/msg/kubernetes-sig-contribex/Oin3mGNRwNg/2gDnVdqFFAAJ) for the nomination
grodrigues3 has graciously agreed to step down for nikhita on the github admin team
I also adjusted OWNERS such that:
- I am subproject owner in lieu of grodrigues 
- the membership team are also listed as reviewers here
/hold
need steering signoff for the membership change
/assign @nikhita 
can you confirm you're interested in this, and accept the security embargo policy?
the OWNERS shuffle was a guess, am I doing it right?
> Add nikhita to github admins team, adjust OWNERS

- OWNERS_ALIASES
- sig-auth/README.md
- sigs.yaml
Seeding sig-auth tech leads following methodology discussed in https://groups.google.com/d/msg/kubernetes-sig-auth/v0-Awf0rBOg/Dk3SipCTAQAJ
Subproject approvers for more than one sig-auth subproject:
- @liggitt (6 subprojects)
- @deads2k (5 subprojects)
- @mikedanese (5 subprojects)
- @tallclair (3 subprojects)
- @smarterclayton (2 subprojects)
Will announce the proposal in the sig-auth meeting today, and in the [mailing list thread](https://groups.google.com/d/msg/kubernetes-sig-auth/v0-Awf0rBOg/Dk3SipCTAQAJ), and leave open for comment.
/assign @mikedanese @tallclair @enj
> Add tech_leads for sig-auth

- contributors/devel/OWNERS
- contributors/guide/OWNERS
Adds guineveresaenger as Reviewer to OWNERS file in `contributors/devel` and Approver in `contributors/guide`, due to assisting with the rebuilding of the developer guide and long-term experience with the contributor guide.
/assign @spiffxp @parispittman
> Add guineveresaenger to OWNERS files in contributors

- contributors/devel/e2e-tests.md
If a test is known to be using Linux-specific features
(e.g.: seLinuxOptions) or is unable to run on Windows nodes, it is labeled
`[LinuxOnly]`. When using Windows nodes, this tag should be added to the
`skip` argument.
This tag was proposed during [1][2].
Depends-On: https://github.com/kubernetes/kubernetes/pull/73204
Related Issue: https://github.com/kubernetes/kubernetes/issues/69871
[1] https://groups.google.com/forum/#!topic/kubernetes-sig-testing/ii5584-Tkqk
[2] https://docs.google.com/document/d/1z8MQpr_jTwhmjLMUaqQyBk1EYG_Y_3D4y4YdMJ7V1Kk/edit#heading=h.ukbaidczvy3r
> Adds the [LinuxOnly] tag

- communication/discuss-guidelines.md
- communication/moderation.md
- communication/moderators.md
Adds discuss.k8s.io specific communication guidelines.
reference: #2884 
/cc @parispittman @castrojo
> Add discuss communication guidelines

- contributors/design-proposals/storage/container-storage-interface-pod-information.md
This proposal adds possibility to send pod information in CSI `NodePublishVolumeRequest` call.
Fixes https://github.com/kubernetes/kubernetes/issues/64984
It depends on https://github.com/kubernetes/community/pull/2514
/sig storage
> CSI: send pod information in NodePublishVolumeRequest

- governance.md
@bgrant0607 @spiffxp @smarterclayton 
As discussed in steering committee...
> Add a description of user groups.

- communication/mailing-list-guidelines.md
- communication/moderation.md
This separates and adds mailing list specific communication guidelines.
Reference #2956
/cc @parispittman @castrojo
> Add mailing-list guidelines

- sig-ui/charter.md
Adds the [dashboard-metrics-scraper](https://github.com/kubernetes-sigs/dashboard-metrics-scraper) to our charter.
/sig ui
> Add dashboard-metrics-scraper to SIG-UI charter
