kubernetes/community

contributors/design-proposals/apps/deployment.md, contributors/design-proposals/node/node-usernamespace-remapping.md
=> fixs typo: dont -> don't

communication/slack-guidelines.md
Added:
careers channel requirements
archive info
updated slack numbers
other small formatting updates
=> slack guideline updates

CLA.md
Signed-off-by: Hart Hoover <hart@heptio.com>
Closes #1636
=> Add instructions to change affiliation to CLA documentation

sig-network/README.md, sigs.yaml
=> Fixed broken links for sig-network readme.md

sig-instrumentation/README.md, sigs.yaml
The CoreOS -> Red Hat google docs migration broke the link, so updating here :slightly_smiling_face: .
=> sig-instrumentation: Update meeting notes link.

sig-storage/README.md, sigs.yaml
Follow up to https://github.com/kubernetes/org/issues/254
=> Add new driver-registrar repos to sig storage

events/2018/12-contributor-summit/README.md
I was asked to facilitate WG LTS intro and discussion, so changing
"Release Management" to explicitly say "WG LTS".  And fixing my @
mention.
=> contrib summit: WG LTS

github-management/setting-up-cla-check.md, sig-cloud-provider/CHARTER.md, sig-scalability/blogs/k8s-services-scalability-issues.md, sig-scalability/goals.md
FILE: ./sig-cloud-provider/CHARTER.md
[✖] https://github.com/kubernetes/community/blob/master/keps/0002-controller-manager.md
→ Status: 404
[✖] https://github.com/kubernetes/community/blob/master/keps/0002-controller-manager.md#repository-requirements
→ Status: 404
FILE: ./github-management/setting-up-cla-check.md
[✖] https://identity.linuxfoundation.org/lfcla/github/postreceive?group=284&amp;comment=no&amp;target=https://identity.linuxfoundation.org/projects/cncf
→ Status: 404
FILE: ./sig-scalability/blogs/k8s-services-scalability-issues.md
[✖] https://cilium.io/blog/2018/04/17/why-is-the-kernel-community-replacing-iptables)
→ Status: 404
FILE: ./sig-scalability/goals.md
[✖] provider-configs.md → Status: 400 Error: ENOENT: no such file or
directory, access …
=> Broken Links fix for 2696

keps/sig-cloud-provider/0018-testgrid-conformance-e2e.md, keps/sig-cloud-provider/0019-cloud-provider-documentation.md
These two KEPs have been in progress for quite a bit but we forgot to update them.
=> update cloud provider KEPs to implementable status

sig-storage/README.md, sigs.yaml
Follow up on https://github.com/kubernetes/org/issues/268
/sig storage
=> Add new csi-lib-utils repo to sigs.yaml

keps/sig-aws/aws-lb-prefix-annotation.md
New KEP for sig-aws group.
@justinsb, @kris-nova or @d-nishi, can you assign someone to review the KEP?
@justaugustus, please review that the content of KEP answers the current template.
=> add new KEP aws-lb-prefix-annotation

keps/sig-aws/draft-20181127-aws-alb-ingress-controller.md
=> create kep for aws alb ingress controller

events/2018/12-contributor-summit/README.md
Removes the waitlist registration link.
/cc @parispittman @castrojo
=> Update contributor summit registration information

events/2018/12-contributor-summit/README.md
I fear this might be too long, so nitpicking appreciated.
=> Add unconference instructions

events/2018/12-contributor-summit/README.md
Finalizes the NCW schedule for KubeCon Seattle.
/assign @parispittman 
/assign @castrojo 
/cc @jberkus 
/cc @tpepper
=> New Contributor Workshop schedule, finalized

keps/sig-testing/0028-20180625-new-label-for-trusted-pr-identification.md
=> Update implementation history, add @tpepper comments

events/2018/12-contributor-summit/README.md
=> Last minute title changes

events/2018/12-contributor-summit/README.md
=> Rename KEP BOF, bring back better Networking session title

sig-network/charter.md
=> Add SIG Network charter

events/2018/12-contributor-summit/README.md
=> Update contrib summit hotel reg locations.

sig-scalability/configs-and-limits/provider-configs.md
=> Typo fix: plan->plane

contributors/design-proposals/instrumentation/external-metrics-api.md
=> HPA v2 API extension proposal | Dead link replaced

contributors/design-proposals/resource-management/device-plugin.md
typo fixes in device-plugin.md
(mainly "it's" vs "its")
=> Typo fixes in device-plugin.md

contributors/devel/api_changes.md
Updates guidance on alpha fields, feature gates, and validation based on experiences with field promotion, rollback, rolling upgrade, and safe feature disablement with existing data.
cc @kubernetes/api-approvers 
/assign @thockin @smarterclayton
=> Update feature gate and alpha field guidance

sig-scalability/README.md
=> Update upcoming meeting dates

sig-scalability/README.md, sigs.yaml
/assign @shyamjvs 
@thockin @kubernetes/sig-scalability-misc
=> Update sig scalability readme

sig-api-machinery/README.md, sig-architecture/README.md, sig-cloud-provider/README.md, sig-cluster-lifecycle/README.md, sig-instrumentation/README.md, sig-node/README.md, sig-storage/README.md, sig-windows/README.md, sigs.yaml
fixes kubernetes/org#38.
fixes kubernetes/org#208.
fixes kubernetes/org#195.
fixes kubernetes/org#213.
fixes kubernetes/org#244.
fixes kubernetes/org#284.
fixes kubernetes/org#285.
=> Add a number of repos to k/community

sig-scalability/slos/dns_latency.md, sig-scalability/slos/slos.md
/assing @bowei @caseydavenport @thockin @dcbw @countspongebob
=>   DNS latency SLI

sig-scalability/README.md, sigs.yaml
=> Update SIG scalability subprojects

sig-azure/README.md, sigs.yaml
=> Add Cluster API Azure subproject

contributors/devel/client-libraries.md, contributors/devel/issues.md, contributors/devel/update-release-docs.md, sig-architecture/api-review-process.md
#3086 
/kind feature
cc @parispittman @nikhita
=> Deleting stub files in /devel and updating links - Umbrella issue 3064

OWNERS_ALIASES, sig-contributor-experience/README.md, sig-testing/README.md, sigs.yaml
ref: https://groups.google.com/forum/#!topic/kubernetes-sig-contribex/prZ9erf6urE
=> Add nikhita as contribex tech lead 🎉🎈⭐️

sig-cluster-lifecycle/README.md, sigs.yaml
Previous link was to archived 2018 minutes
=> Update sig-cluster-lifecycle meeting agenda to 2019

contributors/devel/welcome-to-kubernetes-new-developer-guide.md
Just removing a stub file. There are no files in k/community pointing it.
issue #3064 
/kind feature
/assign @spiffxp 
/assign @guineveresaenger
=> Deleting stub file - Issue 3064

committee-steering/governance/wg-governance.md
=> wg-governance: link to repo doc

contributors/devel/api-conventions.md
Make it clearer wrt annotations and prefixes.
=> Fix up some of the API conventions docs

sig-testing/README.md, sigs.yaml
=> Use the correct link to the gopherage OWNERS file

sig-storage/README.md, sigs.yaml
Part of the sig-storage/kubernetes-csi subproject
ref: https://github.com/kubernetes/org/issues/342
=> Add kubernetes-csi/csi-release-tools repo

sig-architecture/README.md, sig-pm/README.md, sigs.yaml
=> Follow k/features rename, follow k/community/keps migration

sig-scalability/processes/scalability-validation.md
This is to match changes from https://github.com/kubernetes/test-infra/pull/10824.
=> Update the scalability test schedule.

sig-contributor-experience/devstats/OWNERS, sig-contributor-experience/devstats/README.md
Fixes https://github.com/kubernetes/community/issues/3094
Let's add links to the devstats website and cncf/devstats repo.
/cc @Phillels @lukaszgryglicki @jberkus @spiffxp
=> devstats: document how to suggest improvements

communication/moderators.md
Changed from CET
Signed-off-by: Ihor Dvoretskyi <ihor.dvoretskyi@gmail.com>
=> Ihor's default timezone is EET

communication/zoom-guidelines.md
Part of the comms docs overhaul.
Ref: #2536
Ref: #3159
/cc @castrojo @parispittman
=> Update zoom guidelines.

contributors/design-proposals/apps/controller_history.md
=> fix a wrong word

contributors/devel/sig-testing/e2e-tests.md
fix broken links in e2e-tests.md.
=> fix broken links in e2e-tests.md

contributors/design-proposals/apps/deployment.md
=> fix wrong words

contributors/design-proposals/apps/indexed-job.md
=> make the doc easy understand

communication/zoom-guidelines.md
=> Small text change

sig-cluster-lifecycle/grooming.md
/assign @detiber @neolit123 @roberthbailey 
/cc @BenTheElder @spiffxp @kubernetes/sig-cluster-lifecycle-pr-reviews
=> Document SCL's standard grooming practice

sig-cloud-provider/README.md, sigs.yaml
ref https://github.com/kubernetes/org/issues/314
=> add k8s.io/cloud-provider-sample to SIG Cloud Provider subproject

events/2019/05-contributor-summit/README.md, events/2019/06-contributor-summit/README.md, events/2019/11-contributor-summit/README.md
=> 2019 Contributor Summits placeholders added

events/2019/05-contributor-summit/README.md, events/2019/06-contributor-summit/README.md, events/2019/11-contributor-summit/README.md
Updates https://github.com/kubernetes/community/pull/3243
=> ContribSummit files 2018 -> 2019

contributors/devel/sig-architecture/godep.md
Adding some notes from @thockin that didn't appear to be in the existing steps. 
/assign @thockin 
cc @apelisse
=> add some more details to reviewing godeps

sig-windows/README.md, sigs.yaml
ref: [kubernetes/org#451](https://github.com/kubernetes/org/issues/451)
this is an updated PR to #3246 that went stale
=> updating the sigs.yaml for the gmsa project

community-membership.md
Addresses https://github.com/kubernetes/community/pull/3256#discussion_r256979112
@mrbobbytables Added some more explicit details. PTAL. :)
/assign @mrbobbytables @cblecker @justaugustus 
=> Add examples for member sponsorship requirements

committee-steering/governance/sig-governance.md, sig-architecture/README.md, sig-azure/charter.md, sig-cloud-provider/CHARTER.md, sig-release/charter.md
Following up on https://github.com/kubernetes/enhancements/pull/836 to update links to KEP template. 
/assign @justaugustus
=> update references to KEP template

sig-api-machinery/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/418
=> Add kubernetes-declarative-pattern to server-sdk subproject

sig-architecture/api-review-process.md
`api-review` label commands added in https://github.com/kubernetes/test-infra/pull/11350
bot help commenting added in https://github.com/kubernetes/test-infra/pull/11351
=> Update api-review label commands

sig-storage/volume-plugin-faq.md
=> Update FAQ to reflect CSI GA

sig-apps/README.md, sigs.yaml
Caught this while writing the script for https://github.com/kubernetes/community/issues/3305#issuecomment-467289626. :X 
/shrug
/cc @mattfarina
=> sig apps: use raw github links for owners

contributors/design-proposals/storage/csi-migration.md
Add section about API changes required. Describe changes required in CSI attach as well as how we will find the `VolumeAttachment` object for `Detach` and `WaitForAttach.`
/assign @msau42 @saad-ali @liggitt
=> Update design for migration for Inline Volumes

communication/moderation.md
fix #3315
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
=> fix /communication/moderation.md link

communication/moderators.md
=> Added existing moderators of discuss

.github/ISSUE_TEMPLATE/moderator_application.md, communication/moderation.md
=> Improved the issue template and docs of moderation

communication/moderators.md
ref: #3332
Signed-off-by: Jorge Alarcon Ochoa <alarcj137@gmail.com>
=> Added alejandrox1 to slack comm moderators

communication/moderators.md
=> Added DylanGraham to Slack Moderators Pro Tempore

communication/moderators.md
/cc @mrbobbytables 
ref: https://github.com/kubernetes/community/issues/3329
=> Added idealhack to Slack moderators

sig-architecture/README.md
=> Updating the links to the sig arch boards to be current

contributors/devel/sig-architecture/api-conventions.md
=> Fix the link to the Strategic Merge Patch doc

communication/moderators.md
=> add puja108 to slack moderators pro tempore

communication/moderation.md
Based on feedback from other slack admins.
=> Add more moderator duties

communication/moderators.md
Related to https://github.com/kubernetes/community/issues/3373
/cc @jdumars 
/assign @castrojo
=> Added rlenferink as slack moderator

communication/moderators.md
Fixes: https://github.com/kubernetes/community/issues/3385
=> add mkumatag to slack moderators Pro Tempore

communication/moderators.md
Fixes #3394 
adding myself to slack moderators pro tempore
=> add pontiyaraja to slack moderators pro tempore

contributors/devel/sig-architecture/godep.md
=> Fix typo in godep.md

contributors/guide/README.md
=> Fix typo in contributors guide

communication/moderators.md
=> Add @anguslees as slack moderator pro tempore

communication/moderators.md
ref #3407 
/cc @castrojo @nikhita
=> Add myself to moderators.md

communication/moderators.md
Resolves #3387
Signed-off-by: Jorge Alarcon Ochoa <alarcj137@gmail.com>
=> Added alejandrox1 to YouTube and Zoom

contributors/guide/README.md
=> Mention contributor playground in the contributor guide

communication/moderators.md
Whoops, forgot to add myself in here before.
=> Add Noah as a Slack moderator.

communication/moderators.md
=> Add @JoelSpeed as Slack moderator

generator/list.tmpl, sig-list.md
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> fix link to weekly meeting

contributors/guide/README.md
=> Adding #pr-reviews to the contributor guide

communication/moderators.md
=> Add mrbobbytables to ML, Youtube, Zoom moderators.

generator/aliases.tmpl
Got missed in https://github.com/kubernetes/community/pull/3298 :(
/cc @spiffxp @idealhack @erikerlandson
=> Automatically update OWNERS_ALIASES for UGs

events/community-meeting.md, events/office-hours.md
=> Use a timezone for the community meeting and office hours to avoid daylight savings adjustments

communication/moderators.md
Issue: https://github.com/kubernetes/community/issues/3411
/cc @castrojo @nikhita
=> Add @aditya-konarde as pro-tempore Slack moderator

sig-contributor-experience/README.md, sigs.yaml
fix #3365
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
=> remove duplicate events.

communication/OWNERS
Both @mrbobbytables and @jeefy have been involved in moderation and authoring/reviewing guidelines for our communication mediums.
/cc @mrbobbytables @jeefy 
can you leave lgtms here just to confirm that you are ok with this? :)
=> communication: add mrbobbytables and jeefy as reviewers

events/events-team/README.md, events/events-team/best-practices.md
starting to document our team and processes
=> starting events team role book

contributors/devel/sig-node/container-runtime-interface.md
=> Add Singularity CRI in runtimes list

communication/README.md
Update docs to point to new Slack requests process.
=> update instructions to use new slack request process

contributors/devel/sig-testing/testing.md
=> fix typo for testing documentation

events/2019/05-contributor-summit/README.md
Added the details from the content proposal in the Google doc to this page where we have details about the summit in one place. This is the final task required to resolve issue #3273 
/cc @guineveresaenger @jonasrosland
=> Added content proposal details for Contributor Summit EU

communication/moderators.md
=> Timezones added to moderators.md

generator/OWNERS
I reviewed PRs over the last year:
- @nikhita has done consistent review on almost every change
that touches this code, added a number of substantive
changes herself, and is a contribex tech lead
- pruning @grodrigues3 due to lack of activity in the past year
=> Update generator OWNERS

communication/moderators.md
Merges information from #3450 (region - Americas/APAC/EMEA) into better table format.
/cc @idvoretskyi
=> Add regions to moderator list.

sig-cluster-lifecycle/README.md, sigs.yaml
Sub-project of sig-cluster-lifecycle (https://github.com/kubernetes/org/issues/630)
=> Document cluster-addons repository

sig-windows/CONTRIBUTING.md, sig-windows/README.md
adding the k8s discussion server links for windows
/sig windows
=> adding the k8s discussion server links for windows

communication/moderators.md
=> Minor typo fix in moderators.md

contributors/design-proposals/storage/csi-migration.md
Small update based on API reviews and discussion.
/assign @msau42  
/cc @ddebroy @saad-ali @jsafrane @leakingtapan
=> Update inline volume design

contributors/design-proposals/storage/csi-migration.md
/cc @davidz627 @ddebroy @msau42
=> Update CSI migration doc for block volume migration

contributors/design-proposals/storage/csi-migration.md
some design for how to support volume reconstruction with migration.
/assign @msau42 @jingxu97 @saad-ali 
/cc @leakingtapan @ddebroy
=> Volume Reconstruction migration design

communication/calendar-guidelines.md, sig-creation-procedure.md, sig-wg-lifecycle.md
calendar documentation updates for chairs and house keeping
=> calendar doc updates

contributors/design-proposals/scheduling/nodeaffinity.md
=> Add the example: Run a pod on a node with an Intel or AMD CPU and in availability zone Z

sig-docs/README.md, sigs.yaml
=> Updated GitHub teams for localization teams

communication/calendar-guidelines.md
Cleans up and organizes the calendar guidelines.
=> Update calendar guidelines

sig-cli/README.md, sigs.yaml
reference: https://github.com/kubernetes/org/issues/599
=> Add SIG CLI subprojects krew and krew-index

sig-aws/README.md, sigs.yaml
Add two new subprojects to SIG AWS
Auto generate docs
=> Add two new subprojects to SIG AWS

governance.md
@nikhita are these generated files?
=> Add missing link to SIG lifecycle

sig-storage/README.md
fix broken link of sig storage contributor guide
Fixes #3554 
/kind cleanup
/sig storage
=> fix broken link of sig storage contributor guide

sig-cli/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/662
/assign @pwittrock
=> Add cli-experimental subproject to sig-cli

sig-wg-lifecycle.md
Links to #creation and #retirement were leading to 404.
=> Update internal links to creation and retirement

events/2019/05-contributor-summit/README.md
=> Update BCN Contributor Summit registration link.

sig-api-machinery/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/626
=> Introduce openapi perl client to api-machinery

sig-api-machinery/README.md, sigs.yaml
link to the playlist, not to a 2017 video
=> Update sig-apimachinery meetings playlist

contributors/devel/sig-architecture/conformance-tests.md
Bugs are ok, but features are not ok during code freeze.
Change-Id: I5d9e6602396735ee5798792527a0a7110ce02275
=> Document code freeze restrictions for adding conformance tests

contributors/guide/README.md
Fixed the link in setting up dev... this has been an open issue for quite some time.
=> various documentation fixes

committee-steering/governance/wg-governance.md
Ref: https://groups.google.com/a/kubernetes.io/forum/#!topic/steering/sDIgMImNpgY
=> wg-governance: limit stakeholders to SIGs

communication/slack-config/README.md
=> Fix Tempelis readme link

communication/slack-config/channels.yaml
Rename #deis-users and #deis-dev to #hephy-users and #hephy-dev.
Fixes #3582.
=> rename #deis-* to #hephy-*

communication/slack-config/channels.yaml
=> Add #helm-chart-testing channel to Slack

communication/slack-config/sig-docs/docs-channels.yaml
Fixes #3603
This PR adds two new Slack channels for Indonesian and Portuguese docs.
/assign @Katharine 
/ref https://github.com/kubernetes/community/pull/3604#issuecomment-483833387
=> Add Slack channels for Indonesian and Portuguese

sig-cloud-provider/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/715
/assign @andrewsykim @cheftako
=> Add apiserver-network-proxy to the cloud-provider-extraction-migration subproject

sig-architecture/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/731
=> kuberentes/contrib has been retired, rm from sig-arch

sig-contributor-experience/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/663
/cc @Katharine @jeefy
=> Add slack-infra subproject to sig-contribex

sig-api-machinery/README.md, sigs.yaml
Adding agenda doc for kubebuilder meeting.
=> Adding agenda doc for kubebuilder meeting

contributors/devel/sig-architecture/api_changes.md
=> Update E2E testing doc link

communication/slack-config/sig-docs/docs-channels.yaml
Ref:
- https://kubernetes.slack.com/archives/C1J0BPD2M/p1555534044122100
- https://twitter.com/Daminisatya/status/1118156363002040320
/cc @daminisatya @Rajakavitha1 
involved in Hindi localization
/assign @zacharysarah 
sig-docs lead
/cc @mrbobbytables @jeefy 
slack admins
/hold
for lgtm from Zach and slack admins
=> Add kubernetes-docs-hi channel for Hindi localization

events/events-team/README.md, events/events-team/best-practices.md
adding more about the roles, best practices, and more
will close # 3340
=> summit notes

contributors/devel/sig-architecture/godep.md, contributors/devel/sig-architecture/vendor.md
Follow-up from #3612 comments
/cc @cblecker
=> vendor doc follow-up

github-management/kubernetes-repositories.md, github-management/org-owners-guide.md
Follow up of https://github.com/kubernetes/community/pull/3294 and https://github.com/kubernetes/community/pull/3368
/cc @cblecker @spiffxp @mrbobbytables @justaugustus @rlenferink 
/assign @cblecker @spiffxp
=> github-management: add improvements to docs

sig-architecture/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/738
/assign @dims @jdumars
=> sig-arch: remove architecture-tracking repo

sig-docs/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/753
/assign @zacharysarah
=> sig-docs: remove website-metadata repo

events/OWNERS
=> Update OWNERs entry, I'm working on other things this year

sig-instrumentation/charter.md
See https://github.com/kubernetes/website/pull/12934
=> Fix link for resource metrics pipeline

contributors/design-proposals/architecture/namespaces.md
Encountered during troubleshooting https://github.com/kubernetes/kubernetes/issues/77086
/cc @derekwaynecarr
=> Fix typo in namespace finalize verb

contributors/guide/contributor-cheatsheet/README.md
=> Add a link to the product security team pages

communication/slack-config/channels.yaml
This channel will be used for the kube-score project
https://github.com/zegl/kube-score
=> Add #kube-score Slack channel

contributors/guide/non-code-contributions.md
Signed-off-by: Jorge Alarcon Ochoa <alarcj137@gmail.com>
=> Added info to non-code-contributing guide

communication/slack-config/channels.yaml
This channel is to go alongside the existing #minikube and should be managed the same way. The
The intent with #minikube-dev is to provide separation so that we can use the GitHub Slack bot and other notification mechanisms to track changes without spamming users.
Please let me know if you have any questions. Thanks!
=> New channel: #minikube-dev

contributors/design-proposals/storage/csi-migration.md
Clarifying the enhancements necessary for inline volume migration.
/cc @davidz627 @leakingtapan @msau42
=> Enhancements for inline volume migration

sig-ibmcloud/README.md, sigs.yaml
/cc @nikhita @cblecker @spzala
=> Added subproject cluster-api-provider-ibmcloud to ibmcloud.

communication/slack-config/channels.yaml
fixes #3665 
renames sig-big-data -> ug-big-data
=> Rename sig-big-data slack channel to ug-big-data.

communication/slack-config/channels.yaml, communication/slack-config/restrictions.yaml, communication/slack-config/sig-release/OWNERS, communication/slack-config/sig-release/config.yaml
Supercedes: #3655 
/assign @calebamiles @tpepper 
=> Add SIG Release Slack configs

contributors/guide/contributor-cheatsheet/README-ko.md
This commit fixed kubernetes/website#13989 kubernetes/website#13991.
/cc @kubernetes/sig-docs-ko-owners 
/cc @kubernetes/sig-docs-ko-reviews 
/cc @chenrui333
=> Localize contributor cheatsheet in Korean

contributors/devel/sig-node/cri-container-stats.md, contributors/devel/sig-node/cri-testing-policy.md, contributors/devel/sig-release/release.md, contributors/guide/coding-conventions.md, contributors/guide/pull-requests.md, contributors/guide/style-guide.md
Some files have old links like https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md.
This PR changes that to new links.
=> fix some links

contributors/devel/sig-architecture/conformance-tests.md
Fixes https://github.com/kubernetes/kubernetes/issues/75324 
This modifies the documentation with recommend ways to refactor the tests given feedback on https://github.com/kubernetes/kubernetes/issues/75324  
/assign @johnbelamaric @bgrant0607 @spiffxp
=> Update recommendations for tests that don't meet criteria

sig-release/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/801
/assign @cblecker @justaugustus @jeefy
=> Add release-notes to release-engineering subproject

github-management/subproject-site-requests.md
ref #3454
/cc @cblecker @zacharysarah
Holding till this is signed off on and an associated issue template is created in k/org.
/hold
=> Add subproject site request guidelines.

contributors/guide/contributor-cheatsheet/README-pt.md, hack/.spelling_failures
Addressing PR from  kubernetes/website#13989 and kubernetes/website#13997
=> Adding contributor-cheatsheet README-pt.md

sig-cluster-lifecycle/README.md, sigs.yaml
update links to slack and zoom of Cluster Addons
=> update links to cluster addons slack

contributors/guide/contributor-cheatsheet/README-id.md
This is an initial commit for contributor cheat sheet thus addressing https://github.com/kubernetes/website/issues/13996
=> Initialize contributing cheatsheet in Bahasa Indonesia.

sig-multicluster/README.md, sig-multicluster/charter.md, sigs.yaml
Rename the `federation-v2` project to `kubefed`; associated kubernetes/org request: https://github.com/kubernetes/org/issues/818
=> Rename federation-v2 to Kubefed

communication/slack-config/channels.yaml
Hello! I maintain the Terraform providers for Kubernetes and Helm at Hashicorp.
I would like to request a Slack channel for users of these providers to gather and exchange ideas but also to reach out to maintainers and PR authors.
I'm basing this request on several in-person conversations at Kubecon and user groups where this topic has come up and demand for such a channel was repeatedly mentioned.
Thank you!
=> Requesting Slack channel for Terraform providers for Kubernetes

sig-auth/README.md, sig-autoscaling/README.md, sigs.yaml
=> Fix node-identity-and-isolation subproject name

contributors/guide/README.md
Ref kubernetes/test-infra#9387
For #3642
cc @nikhita 
=> Adding note to not use keywords and mentions in commit messages

committee-steering/governance/ug-governance.md, governance.md, sig-wg-lifecycle.md
ref - https://github.com/kubernetes/steering/issues/92
=> Add User Group governance

contributors/devel/sig-architecture/api-conventions.md
=> Fix link in api-conventions.md

sig-docs/blog-subproject/README.md, sig-docs/blog-subproject/role-handbooks/blog-community-manager.md, sig-docs/blog-subproject/role-handbooks/copy-editor.md, sig-docs/blog-subproject/role-handbooks/editorial-lead.md, sig-docs/blog-subproject/role-handbooks/technical-editor.md
This PR includes proposed documentation, processes, and roles for the Kubernetes blog.
=> Kubernetes Blog Subproject: Proposed README and Role Handbooks 

events/events-team/README.md, events/events-team/registration/README.md
First pass at adding the reg lead handbook
/cc @parispittman @jonasrosland
=> Add events registration lead handbook

communication/slack-config/channels.yaml
=> slack: added jp-dev channel

communication/slack-config/channels.yaml
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>
context: https://groups.google.com/forum/#!topic/kubernetes-api-reviewers/FDZr4ksmCtk
cc @dims @liggitt
=> propose api-reviews slack channel

github-management/subproject-site-requests.md
Update instructions to be more explicit about creating a site config.
/cc @davidewatson @cblecker
=> Update Netlify site request instructions.

sig-windows/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/863
/assign @michmike
=> sig-windows: add windows-tools subproject

sig-cli/README.md, sigs.yaml
fixes https://github.com/kubernetes/org/issues/798
=> add cli-utils repo to sig-cli subprojects

communication/slack-config/channels.yaml
Creates #aks channel 
+1'd in `#slack-admins` by myself and @idvoretskyi
=> Create AKS channel

events/events-team/README.md, events/events-team/content-lead.md, events/events-team/events-lead.md, events/events-team/marketing/README.md
more handbook creation for event team roles
=> adding more event handbooks

contributors/guide/README.md, contributors/guide/bug-bounty.md, contributors/guide/coding-conventions.md, contributors/guide/collab.md, contributors/guide/community-expectations.md, contributors/guide/github-workflow.md, contributors/guide/help-wanted.md, contributors/guide/issue-triage.md, contributors/guide/non-code-contributions.md, contributors/guide/owners.md, contributors/guide/pull-requests.md, contributors/guide/release-notes.md, contributors/guide/scalability-good-practices.md, contributors/guide/style-guide.md
=> Add hugo metadata to the contributor guides. Fixes #3769

contributors/design-proposals/release/versioning.md
Fixes https://github.com/kubernetes/community/issues/3469
=> #3469: Removing arbitrarily mention of GKE versioning

events/2019/06-contributor-summit/README.md
=> Added session information, updated times, updated links for Shanghai CS.

events/2019/06-contributor-summit/README.md
This just fixes the end time, which was supposed to be 4pm.
=> Fix incorrect end time.

committee-steering/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/899
=> Add kubernetes/funding subproject to committee-steering

events/2019/06-contributor-summit/README.md
There's a schedule for the current contributor day now.
/area cn-summit
=> Added schedule, room numbers for contributor summit.

events/2019/11-contributor-summit/README.md
Mainly a copy/pasta with some updated verbage and info. :)
=> Stub out more basic NA Summit info

events/events-team/README.md
That's all there is to it really.
=> Fix broken links in events README

sig-service-catalog/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/894
/cc @carolynvs @jberkhahn 
/assign @jberkhahn
=> service-catalog: add minibroker subproject

contributors/guide/non-code-contributions.md
=> Fix typo non-code-contributions.md

contributors/guide/issue-triage.md
Would be useful to point them to discuss as well.
/assign @mrbobbytables @castrojo
=> Add discuss.k8s.io to support response blurb

github-management/README.md
\o/
/cc @nzoueidi 
ref: https://github.com/kubernetes/org/pull/930
/hold
hold for final ack.
=> Add nzoueidi as New Membership Coordinator.

contributors/guide/pull-requests.md
Reviewed and updated a few spelling, grammar and punctuation in guide/pull-requests.md.
=> Reviewd and updated spelling, grammar and punctuation.

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
/cc @kubernetes/release-managers @kubernetes/patch-release-team @kubernetes/build-admins 
/assign @tpepper @calebamiles
=> slack: Add Release Managers usergroup

communication/slack-config/usergroups.yaml
Okay, one more time...
/assign @Katharine @jdumars @jeefy 
ref: #3829 #3828 #3827
=> slack: Fix channel auto-joins for release-managers usergroup

sig-contributor-experience/role-handbooks/apac-coordinator.md
ref: https://github.com/kubernetes/community/issues/3693
cc @aravindputrevu @alisondy @saiyam1814
While we said in our initial meeting that we could start this with Google docs, I changed my mind later that we'd better check-in early and iterate often.
/cc @parispittman @nikhita
=> add sig-contribex apac coordinator role handbook

contributors/guide/README.md, contributors/guide/community-expectations.md
=> Guide needs to mention setting github status #3696

sig-cluster-lifecycle/README.md, sigs.yaml
Signed-off-by: Chuck Ha <chuckh@vmware.com>
/assign @nikhita
=> Adds cluster-api-provider-docker

sig-apps/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/880
/cc @xing-yang @liyinan926
/assign @janetkuo
=> sig-apps: add execution-hook subproject

sig-testing/README.md
There were some folks asking for slides in #sig-testing today so I
figured why not add them to our README. Went ahead and added the talks
from KubeCon Barcelona as well.
=> Add some sig testing presentations

communication/youtube/youtube-guidelines.md
adding more information for youtube admins re: automation, trimming videos, etc. 
this doc may have blow its scope though and may need to be separated out into other docs: for discussion.
=> youtube guideline updates

communication/mailing-list-guidelines.md
=> Add Google groups changes settings

sig-docs/blog-subproject/README.md
- Update @onlydole GitHub link in README
- Markdown run through linter (changes `*` to `-` and other best practices)
=> Update GitHub link for Onlydole

communication/slack-config/channels.yaml
KEDA is a Kubernetes-based Event Driven Autoscaling component. It provides event driven scale for any container running in Kubernetes. More info here - https://github.com/kedacore/keda/issues
=> Creating a Slack channel for KEDA

events/events-team/feedback.md
starting a list of retros and feedback for past and future contributor summits
=> adding contributor summit feedback

sig-docs/blog-subproject/README.md
- Add Kubernetes blog link
- Add Slack blog channel link 
- Add formatting for preferred PR label
- Add GitHub team links
=> Add relevant links to Kubernetes blog subproject readme

contributors/devel/sig-architecture/api_changes.md
=> Add rationale for preserving persisted data for alpha fields

contributors/design-proposals/apps/controller_history.md, contributors/design-proposals/apps/job.md
- Fix links in `controller_history.md`.
- Fix links in `job.md`.
=> Fix links in controller_history.md.

events/events-team/sig-contrib-events.md
Added a document that defines planning and activities needed to organize the SIG Meet and Greet and SIG F2F activities at Contributor Summits.
=> Added doc about leading the SIG Meet and Greet and SIG F2F

sig-scalability/README.md
=> Fix typo in sig-scalabilbity readme

sig-scalability/README.md
=> Change team members to regression contact points

sig-cluster-lifecycle/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/988
=> sig-cluster-lifecycle: add image-builder subproject

sig-architecture/api-review-process.md
I realized while reading #3875 that there is a missing goal: serving the users of APIs.
=> Add new api review process goal

contributors/guide/contributor-cheatsheet/README-id.md, contributors/guide/contributor-cheatsheet/README-ko.md, contributors/guide/contributor-cheatsheet/README-pt.md, contributors/guide/contributor-cheatsheet/README-zh.md, contributors/guide/contributor-cheatsheet/README.md
=> Fix approve command link in contributor cheatsheet

contributors/devel/sig-scalability/hollow-node_simplified_template.yaml, contributors/devel/sig-scalability/kubemark-setup-guide.md
Guide about how to setup a kubemark cluster.
Some people need the guide such as https://github.com/kubernetes/kubernetes/issues/78842, but there's no document.
=> A guide to set up a kubemark cluster

communication/slack-config/channels.yaml
Add slack channels for id-events and id-users
=> Add id-events and id-users.

contributors/devel/sig-node/e2e-node-tests.md
/assign @Random-Liu 
/sig node
=> Add documentation on running node e2e's with custom image configs

committee-code-of-conduct/charter.md
While we later said that any leak of personal information is inappropriate, this
sentence only specifically mentioned the right of privacy of the reporter. We believe
the reporter, anyone named in the report, anyone we talk to about the report, and
everyone involved should have their privacy respected. So this language is more
broad to make our intent more clear.
=> code of conduct: expand the list of people whose privacy will be respected

events/2019/11-contributor-summit/README.md
Add GH handles/links for the 2019 SD Team. :)
=> Add GH handles for SD team

communication/slack-config/channels.yaml
this was for an event in 2017, the channel is inactive other than spam
=> archive leadership-summit

communication/slack-config/channels.yaml
Kyverno is a policy engine designed for Kubernetes. Kyverno allows cluster administrators to manage environment-specific configurations independently of workload configurations and enforce configuration best practices for their clusters. More Info here - https://kyverno.io
=> Add project Kyverno

sig-node/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/957
/assign @derekwaynecarr @dchen1107
=> sig-node: add NFD Operator to NFD subproject

mentoring/meet-our-contributors.md
It's my attempt to learn how timezone converter works. 
And it might be useful.
=> Add timezone convert link for 'Meet Our Contributors'

communication/zoom-guidelines.md
=> updated broken zoom admins link

wg-iot-edge/whitepapers/edge-securuity-challenges/README.md
=> wg-iot-edge: Edge Security Challenges Whitepaper

sig-testing/charter.md
ref: https://github.com/kubernetes/sig-release/issues/631
=> Remove test-infra role from SIG Testing charter

sig-usability/OWNERS, sig-usability/README.md, sig-usability/charter.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1047
/assign @tashimi @vllry @Rajakavitha1 @hpandeycodeit
=>  Add sig-usability subproject 

sig-scalability/slos/api_call_latency.md
Fix: https://github.com/kubernetes/community/issues/3659
/assign @mm4tt @mborsz @shyamjvs
=> Link thresholds from API call latencies file

contributors/devel/sig-architecture/conformance-tests.md
=> Ensure that conformance.txt is regenerated

committee-steering/governance/wg-governance.md
=> Fix link in wg-governance

communication/slack-config/channels.yaml
This channel will be used for the sealed-secrets project
https://github.com/bitnami-labs/sealed-secrets
=> Add #sealed-secrets channel

OWNERS, contributors/devel/OWNERS
Removing myself from reviewers/approvers
=> remove grodrigues3 from OWNERS files

sig-storage/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1060
/cc @ddebroy @PatrickLang @msau42
/assign @saad-ali
=> sig-storage: add csi-proxy to kubernetes-csi subproject

events/2019/11-contributor-summit/README.md
Had the wrong handle. :( 
/priority important-soon
=> Update team with correct GH Handle

contributors/guide/contributor-cheatsheet/README-ja.md, contributors/guide/contributor-cheatsheet/README.md
Translate Contirbutor CheatSheet into Japanese.
Co-Authored-By: @cstoku
=> Translate/contributor cheatsheet into Japanese

contributors/devel/sig-node/container-runtime-interface.md
Its been a little bit of time since this documentation was updated, so
refresh the links and also hopefully improve clarity.
=> Update the sig-node/cri documentation

events/2019/11-contributor-summit/README.md
=> Added the last shadows to the team.  Team is now fully staffed.

events/2019/11-contributor-summit/README.md
Sorry ... I apparently paste-oed the line with Awards roles.
New PR to fix.
=> Ooops, forgot to add Awards leads.

events/events-team/README.md, events/events-team/projectmanagement/README.md
Added Project Manager Handbook in `events-team` folder.
=> Added Project Manager Handbook

events/2019/11-contributor-summit/README.md
added some important links to the event page
=> event page links

sig-usability/charter.md
Fixed minor typo in `sig-usability` charter
=> Fixed minor typo in charter

sig-cluster-lifecycle/README.md, sigs.yaml
Updates agenda doc link for the cluster-api-provider-aws office hours.
=> Update Agenda doc for cluster-api-provider-aws office hours

sig-api-machinery/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/1094
=> move apiserver-builder-alpha to kubernetes-sigs

sig-cluster-lifecycle/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1110
/cc @timothysc @yastij @neolit123 
=> SCL: add system-validators to kubeadm subproject

events/elections/2019/OWNERS, events/elections/2019/README.md, events/elections/README.md
This also updates the OWNERs to reflect the new election officers. 
/assign @parispittman @mrbobbytables @idvortetskyi @bgrant0607
=> Add initial guide for 2019 election

communication/slack-config/channels.yaml
Purpose for this channel is to allow users to ask questions and discuss Kubestack, a open source Gitops framework combining Terraform, Kustomize and TektonCD to provision and maintain EKS, AKS and GKE.
More information can be found on: https://www.kubestack.com/ and: https://github.com/kbst/terraform-kubestack
I am reachable as pst on Slack.
=> Channel request #kubestack

events/elections/2019/lachlanevenson.md
cc @idvoretskyi @castrojo @mrbobbytables @bgrant0607
=> Add candidate bio for Lachlan Evenson

events/elections/2019/christophblecker.md
```
$ wc -w events/elections/2019/christophblecker.md 
298 events/elections/2019/christophblecker.md
```
=> Add election bio for cblecker

events/elections/2019/pengfeini.md
cc @idvoretskyi @castrojo @mrbobbytables @bgrant0607
=> Add candidate bio for Pengfei Ni

communication/slack-config/channels.yaml
Signed-off-by: Kris Nova <kris@nivenly.com>
As we look at building Falco integrations with various components in the Kubernetes ecosystem, folks will naturally be looking for a #falco channel if they have questions or want to get involved. Unsure if we still require moderators in these channels, but I am happy to help any way I can.
=> Adding a slack channel for Falco

events/elections/2019/voters.md
=> Add eligible voters 2019-08-26 - 2019-08-29.

events/elections/2019/krisnova.md
Signed-off-by: Kris Nova <kris@nivenly.com>
I submitted the surverymonkey form to get added to `voters.md` and pinged @castrojo about it. Also will be kicking off an email in `-dev`. I think those are all the requirements here? Let me know if I am missing something.
=> Adding krisnova.md to steering elections 2019

events/elections/2019/README.md
Add first round of candidate bio links to the readme.
=> Update 2019 Steering Committee nominee bio links.

events/elections/2019/voters.md
=> Add eligible voters 2019-08-30 - 2019-09-03.

sig-cloud-provider/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1146
/assign @andrewsykim @cheftako 
/hold
for lgtm by sig cloud provider leads
=> sig-cloud-provider: add alibaba-cloud-csi-driver repo

events/elections/2019/README.md, events/elections/2019/klausma.md
Signed-off-by: Klaus Ma <klaus1982.cn@gmail.com>
=> Add 'Klaus Ma' as 2019 SC candidate.

communication/slack-config/sig-storage/config.yaml
The purpose of this channel is to set up a shared communication place
for the working group on supporting CSI windows
The proposal for enhancements to support CSI plugins on Windows nodes is
here kubernetes/enhancements#1141
=> Add slack channel for csi-windows working group

sig-service-catalog/README.md, sigs.yaml
Fixes https://github.com/kubernetes/org/issues/893
/assign @jberkhahn
=> Add go-open-service-broker-client to service-catalog subproject

events/elections/2019/vallerylancey.md
=> Fix heading typo in vallerylancey steering nominee bio

events/elections/2019/README.md, events/elections/2019/nikhitaraghunath.md
Ref: https://groups.google.com/forum/#!topic/kubernetes-dev/Bs4B0co4IJc
```
wc -w nikhitaraghunath.md
299 nikhitaraghunath.md
```
/cc @idvoretskyi @castrojo @mrbobbytables @bgrant0607
=> Add Nikhita's bio for 2019 Steering Committee election

contributors/devel/sig-instrumentation/instrumentation.md
Follow up of https://github.com/kubernetes/kubernetes/pull/72470#issuecomment-529007782
cc @logicalhan @piosz @mikedanese @ehashman @LiliC @s-urbaniak
=> contributors/devel/sig-instrumentation: Add further details on naming best practices

events/elections/2019/voters.md
Next round of eligible voters.
=> Add eligible voters 2019-09-04 - 2019-09-09.

events/elections/2019/README.md, events/elections/2019/parispittman.md
=> parispittman steering committee bio

events/elections/2019/README.md, events/elections/2019/stephenaugustus.md
Election Officers for approval:
/assign @idvoretskyi @castrojo @mrbobbytables @bgrant0607 
=> Add Stephen Augustus (justaugustus) bio for Steering Committee ('19)

events/elections/2019/brendanburns.md
Election Officers for approval:
/assign @idvoretskyi @castrojo @mrbobbytables @bgrant0607
=> Add brendan burns nomination.

events/elections/2019/README.md
Add Brendan Burns to candidate list and clarify +1 requirement for next time.
=> Add Brendan Burns to candidate list

contributors/guide/github-workflow.md
=> Fixed typo

events/elections/README.md
After running through a mock election we need to update some addresses here and add some detail. Also the original text mentions that we should include steering as the poll supervisor but members of the current committee are running so I've just left that to the election address for now since we can only put one. 
/assign @bgrant0607 @mrbobbytables @idvoretskyi
=> Civs updates

contributors/guide/contributor-cheatsheet/README-id.md, contributors/guide/contributor-cheatsheet/README.md
This PR for #4091 and fix some typo on indonesian readme.md
=> Add point release schedule on the contributor cheatsheet & fix typo on indonesian Readme.md

events/events-team/registration/README.md
This updates the events team registration handbook with the latest questions asked during registration.
/area na-summit
=> Updates events-team registration handbook

communication/moderators.md
=> Add nzoueidi to Youtube and Zoom

wg-iot-edge/README.md
=> Added Publicationslist

events/events-team/content/sig-contrib-events.md
Added more details about how we used the Google form to gather info and track representatives for the SIG M&G.
=> Minor update to organizing doc for SIG events.

contributors/devel/sig-testing/writing-good-conformance-tests.md
This document is in response to issue https://github.com/kubernetes/community/issues/3546
Welcome any additions or suggestions.
=> New document "Writing Good Conformance Tests"

contributors/guide/contributor-cheatsheet/README-id.md
this pr is for fix localization documents
#4103
- fix broken link
- sync with current readme.md
/cc @irvifa @girikuncoro
=> fix localization documents

contributors/devel/sig-testing/writing-good-conformance-tests.md
Signed-off-by: John Belamaric <jbelamaric@google.com>
=> Some edits and additional notes for writing conformance tests

wg-iot-edge/whitepapers/edge-securuity-challenges/README.md
=> Fixing white-paper formatting issues

contributors/devel/sig-testing/writing-good-e2e-tests.md
The document needs some information around resource usage.
Here is what I think would be suited for it.
=> Add resource usage docs

sig-docs/README.md, sigs.yaml
This PR should create a Hindi team.
=> SIG docs Hindi team

sig-contributor-experience/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/1233
/cc @castrojo 
/hold
=> Add discuss-theme OWNERS reference to community-management subproject.

mentoring/outreachy.md
Ref: https://github.com/kubernetes/community/issues/4043
=> mentoring: update Outreachy info for Dec 2019 - Mar 2020 round

events/events-team/marketing/README.md, events/events-team/projectmanagement/README.md, events/events-team/registration/README.md
- Added `Shadow Role` section to each of the events-team Best Practices doc. 
- Added Activites to the Project Management Best Practices.
=> Added Shadow Role section for each events-team and Activities to Project Management events team

events/events-team/content/sig-contrib-events.md
Added a task for making sure that sig meet & greet reps are registered for the Contrib Summit.
=> Update SIG M&G Organizer instructions with registration

wg-iot-edge/README.md
=> Updated Security Challenges link in Publications section of wg-iot-edge readme  

committee-steering/README.md, sigs.yaml
For https://github.com/kubernetes/steering/issues/137
Ref: https://groups.google.com/a/kubernetes.io/forum/#!topic/steering/u1N1OfRodfM
/assign @dims @parispittman
=> Update steering meeting time to Monday 11am PT

contributors/design-proposals/storage/csi-migration.md
Describe the plan to have a separate set of feature flags that will allow us to completely disable in-tree plugin code.
/cc @davidz627 @msau42 @leakingtapan @gnufied
=> Enhancements to disable in-tree plugin code for migration

contributors/guide/contributor-cheatsheet/README-id.md
Fix few typo, and finding much suitable word for few text
=> fix few typo, and some markdown cleanup

communication/slack-config/sig-docs/docs-channels.yaml
@10ten-me 
@mabunemeh 
@nofalx
https://github.com/cncf/foundation/pull/48/files
=> Create a channel for Arabic translation

contributors/devel/sig-testing/testing.md
This PR is springing from a discussion with @timothysc during the Sig-Arch Conformance Office Hours meeting on 2019-10-08. 
This adds a new section to the test guide describing 4 steps to making a PR review process move smoothly.
=> Contributor Testing Guide: Add section on smooth PR review process

sig-cluster-lifecycle/README.md, sigs.yaml
=> Added IBM Cloud to sig cluster lifecycle.

communication/slack-config/sig-docs/docs-channels.yaml
Slack channel for Vietnamese localization.
Refer: cncf/foundation#52
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
=> Create a channel for Vietnamese translation

communication/slack-config/sig-docs/docs-channels.yaml
Reference to https://github.com/kubernetes/website/pull/16404
@Potapy4 
@msheldyakov 
@aisonaku 
@dianaabv 
@lex111
=> Create a Slack channel for Russian translation

communication/slack-config/sig-docs/docs-channels.yaml
Coordinating Bengali language localization of Kubernetes documentation, 
https://en.wikipedia.org/wiki/Bengali_language
=> updated docs-channels.yaml for bengali language.

sig-cloud-provider/CHARTER.md, sig-cloud-provider/README.md, sigs.yaml
ref: #1247
Pending repo migration:
/hold
/assign @andrewsykim @cblecker @mrbobbytables
=> provider-azure: Update references to cloud-provider-azure repo

communication/meeting-notes-archive/201902-201911_Community_Meeting_Notes.md
Signed-off-by: Taylor Martin <martinta@vmware.com>
=> Add 2019's community notes to the archive

communication/slack-config/channels.yaml
Kaniko (https://github.com/GoogleContainerTools/kaniko) is a tool to build images inside a container.
This channel will be used to discuss kaniko development!
=> Add channel for discussion for Kaniko

contributors/design-proposals/architecture/declarative-application-management.md
fixing ansible k8s module link
=> fixing ansible k8s module link

contributors/devel/development.md
see kubernetes/kubernetes#82809
see kubernetes/kubernetes#85019
=> update go version to 1.13.4 for Kubernetes 1.17+

communication/best-practices.md, contributors/guide/contributor-cheatsheet/README-de.md, contributors/guide/issue-triage.md
fix a few spelling errors of the word "Kubernetes", plus a broken link.
=> Fix typo in names

events/2019/11-contributor-summit/unconference-notes/unconference-notes-template.md, events/events-team/content/unconference.md
cc: @parispittman & @thecrudge
=> More notes to unconf content,notes dir & notes template

communication/moderators.md
ref: https://github.com/kubernetes/community/issues/4231
=> add idealhack to YouTube & Zoom moderators

sig-docs/planning/2019-Q2-03-28.md
Create `planning` directory and add 2019 Q2 planning meeting notes.
/assign @zacharysarah
=> Add 2019 Q2 planning document

communication/slack-config/channels.yaml
This PR is to add a new slack channel for the New Contributor Workshop staff.
cc: @parispittman @guineveresaenger @chris-short 
/area/community-management
/area/slack-management
/sig/contributor-experience
=> This pr is to add kubecon SD ncw-staff channel

contributors/design-proposals/scheduling/predicates-ordering.md
As displayed on GH:
```
Author: yastij Approvers:
```
Expected output:
```
Author: yastij
Approvers:
```
=> Scheduling: predicates ordering: add missing NL

events/2019/11-contributor-summit/unconference-notes/Deploying_and_Scaling_Across_Multiple_Clusters-Vallery_Lancey.md
Notes taken during the k8s contributor summit unconference, Monday November 18 at 11:30am.
=> MultiCluster 2019 unconference notes

communication/slack-config/channels.yaml
This channel request is for the Flink Operator project.
See: https://github.com/GoogleCloudPlatform/flink-on-k8s-operator
=> Adding request for #flink-operator slack channel.

communication/slack-config/channels.yaml
Ship has been superseded by the KOTS project -- see https://github.com/replicatedhq/ship#replicated-ship-has-been-superseded-by-kots
=> rename #ship to #kots in Slack config

events/2020/03-contributor-summit/README.md, events/2020/07-contributor-summit/README.md, events/2020/11-contributor-summit/README.md
=> Add placeholders for 2020 Contributor Summits

communication/slack-config/channels.yaml
This channel request is for a project that we are starting called Konveyor.  The goal of the Konveyor project is to provide migration assistance for Kubernetes. This includes the ability to discover, assess, and migrate existing applications between Kubernetes clusters and migrate applications and infrastructure running in traditional environments to Kubernetes.
See: https://github.com/konveyor and https://konveyor.github.io/
=> Adding request for #konveyor slack channel.

events/2019/11-contributor-summit/session-notes/LTS-notes.md, events/2019/11-contributor-summit/session-notes/end-user-panel.md
This PR combines #4247 notes from Josh Berkus, plus typo fixes that were causing CI complaints, and additional notes for WG LTS which I scribed.
=> Contrib Summit Nov. 2019 notes

communication/README.md
added a ton of things that were not there, removed some things that aren't relevant, out-of-date processes, etc. 
took this [sheet](https://docs.google.com/spreadsheets/d/1Pmlj5nN_QJ3rRlc-HKOLfRdYY5qCWPMjnNPAdZZ22tg/edit?usp=sharing) and made updates to this doc. 
did i miss anything?
=> communication guide revision

events/events-team/content/sig-contrib-events.md
Updated the SIG M&G responsibilities with a few new things based on what we learned in San Diego.
@detiber - what do you think? Is there anything you can think to add?
=> SIG M&G - learning from SD

sig-storage/README.md
=> Update instructions for SIG Storage meeting invite

contributors/devel/sig-scalability/kubemark-guide.md
=> update the guide to reflect of new cloud providers

contributors/guide/github-workflow.md
Use "go env GOPATH" instead of "$GOPATH"
Signed-off-by: Elena Morozova <morelena@google.com>
=> github guide: update command to set working_dir

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
cc @nzoueidi
ref:
- https://github.com/kubernetes/community/blob/master/communication/moderators.md#youtube-channel
- https://github.com/kubernetes/community/blob/master/communication/moderators.md#zoom
=> slack: add nzoueidi and idealhack to youtube/zoom admin groups

events/2020/03-contributor-summit/README.md
Filled out the organizers for the AMS EU 2020 contrib summit
=> AMS EU 2020 contrib summit organizers team

sig-architecture/production-readiness.md
This is based on what I've seen when doing the pilot phase with 3 KEPs:
- simplify some of those (given we will get the same answer in 90+% of cases)
- clarify those where people didn't fully understood the intention)
- merge some of them (or add TODOs) to think if they make sense
/assign @johnbelamaric 
@liggitt
=> Rework PRR questionaire

communication/moderators.md, communication/youtube/youtube-guidelines.md
=> YouTube Docs Update

contributors/devel/development.md
=> Improving documentation for build-time dependencies

sig-node/README.md, sigs.yaml
ref https://github.com/kubernetes/org/issues/1488
=> Retire rktlet subproject

.github/PULL_REQUEST_TEMPLATE.md, contributors/guide/contributor-cheatsheet/README.md
- This PR adds a GitHub special keyword to the PR Template as I noticed some issues are opened but their related PR is already merged.
- Correcting the way to sync your fork with the remote ( [Reference](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) )
=> Improving the PR Template and Contributor-Cheatsheet

communication/slack-config/channels.yaml
This channel request is for a project that we are starting called alibaba-cloud. The goal of the PR is to gather intended audiences and organize them to discuss bugs report, features evolutions and some Roadmap of alibaba cloud in Kubernetes support.
And we will start our sig meeting, ref here: https://github.com/kubernetes/community/pull/4337
Fixes #
=> add alibaba cloud channel

contributors/guide/pull-requests.md
Fixes #923 
- This PR documents and highlights various cases with `ok-to-test` label for PRs.
=> feat: Documentation about ok-to-test label

communication.md, communication/README.md
- Removing the unused docs present in the root directory for `communication.md`.
- Correcting the link for `Requesting a channel`
=> chore: Deleting unused file & link correction

communication/slack-config/sig-docs/docs-channels.yaml
Add a Slack channel to coordinate Polish translation activities.
https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=pl
=> Add Slack channel for Polish translation community

events/2019/11-contributor-summit/unconference-notes/kind-ben-the-elder.md
unconference notes from ben the elder kind presentation
=> unconference notes from ben the elder kind presentation

events/2019/11-contributor-summit/unconference-notes/cert-manager-james-munnelly.md
unconference notes from James Munnelly cert manager presentation
=> unconference notes from James Munnelly cert manager presentation

events/2019/11-contributor-summit/unconference-notes/pair-programming-in-kubernetes-hippy-hacker.md
unconf notes frm Hippy Hacker presentation Pair prgm in k8s
=> unconf notes frm Hippy Hacker presentation Pair prgm in k8s

events/2019/11-contributor-summit/unconference-notes/tech-debt-Mayank.md
unconf notes frm Mayank preso on tech debt
=> unconf notes frm Mayank preso on tech debt

events/events-team/content/unconference.md
Minor updates to unconference events team notes
=> Minor updates to unconference events team notes

events/2020/03-contributor-summit/OWNERS, events/2020/07-contributor-summit/OWNERS, events/2020/11-contributor-summit/OWNERS
/cc @jeefy @parispittman @tpepper @mrbobbytables @jberkus @guineveresaenger
=> Add owners files for 2020 contrib summits

sig-cloud-provider/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1449
/assign @cheftako @andrewsykim 
/hold
=> sig-cloud-provider: add blobfuse-csi-driver

contributors/guide/README.md
Fixes #4333 
- Including a section for `Contributions Best Practices` in Contributors Guide
=> enh: Including contributions best practices

events/2020/03-contributor-summit/README.md
Adding details of shadows for NCW201 AMS EU 2020 contributor summit
=> Add Shadows for NCW201

events/2020/03-contributor-summit/README.md
Adding lead & shadow for D&I KCSEU2020 cc: @jeefy
=> Adding lead & shadow for D&I KCSEU2020

communication/slack-config/channels.yaml
This PR requests to set up a slack channel for the Data Protection WG which was just formed.  See details here:
https://github.com/kubernetes/community/tree/master/wg-data-protection
CC @yuxiangqian
=> Add slack channel for wg-data-protection

communication/moderators.md
=> Adding markyjackson to moderators list for zoom & youtube

committee-steering/governance/sig-governance.md, events/community-meeting.md
fixes https://github.com/kubernetes/steering/issues/150
=> Move community meeting to a monthly cadence

communication/slack-config/sig-docs/docs-channels.yaml, sig-docs/README.md, sigs.yaml
Relates to: https://github.com/kubernetes/website/pull/18569
=> Add Ukrainian sig-docs

events/events-team/registration/README.md
This PR removes a duplicate question from the Contributor Summit Registration Handbook.
=> Update registration handbook

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
Adding Marky Jackson to slack configuration
=> Adding Marky Jackson to slack configuration

events/events-team/content/contributor-workshops.md
Add role documentation based on San Diego summit.
=> Add information about the contributor workshop lead role

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
Adding Taylor Dolezal to Slack groups
=> Add Onlydole user to YAML files for Slack administration

sig-contributor-experience/triage-team/triage.md
Grammar correction to triage.md
=> Grammar corrections to triage.md

mentoring/google-summer-of-code.md
=> GSoC 2019 information added

contributors/devel/sig-testing/flaky-tests.md
based on looking at deflaking PRs from the past few months,
what are some common anti-patterns or fixes?
=> Add some suggestions on how to handle flakes

contributors/design-proposals/storage/csi-migration.md
Design for fix of: https://github.com/kubernetes/kubernetes/issues/79043
Original design document with alternate options (shared with kubernetes-dev@googlegroups): https://docs.google.com/document/d/1gz_rqrjT3ZqEczXZd2cmJy2f-ziusMATNDmIXMB-97A/edit#heading=h.kh5w27t7zhu2
/assign @msau42 @jsafrane @ddebroy
=> Dynamically provisioned volume deletion fix for migration design

communication/README.md
We don't explicitly say what's allowed and disallowed on our properties, so codifying this so when someone violates it we can point them to a policy. 
Fixes #4380
=> Be more explicit about what's allowed on our properties

sig-scheduling/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1564
Not sure if this should be a separate subproject?
/cc @Huang-Wei @ahg-g @k82cn 
/assign @ahg-g @k82cn 
/hold
=> sig-scheduling: add scheduler-plugins repo

sig-testing/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1519
=> sig-testing: remove testing_frameworks repo

sig-auth/archive/meeting-notes-2019.md
/assign @enj @mikedanese 
/sig auth
=> Archive SIG-Auth 2019 meeting notes

sig-contributor-experience/surveys/contribex-survey-2019.md
a follow up PR will have:
updated links  
csv file
2018 survey moved to new folder
=> adding readme for survey data

events/2020/03-contributor-summit/README.md
ref: https://github.com/kubernetes/community/issues/4406
/cc @jeefy @mrbobbytables @geekygirldawn 
/area eu-summit
=> eu-summit-2020: add shadows for current content team

events/2020/03-contributor-summit/README.md
Adding @detiber and @jonasrosland as M&G staff for Amsterdam 🎉
=> Add M&G staff to AMS page

mentoring/group-mentoring.md, mentoring/meet-our-contributors.md
fixes 2660 
this needs to be broken down into a process doc and a readme but would rather get this in and put a help wanted issue up for that later on.
=> meet our contrib host and doc updates

mentoring/group-mentoring.md
this doesn't completely fix 2659 but addresses many of the process improvements
=> updated process info for group mentoring

generator/OWNERS
This PR updates the OWNERS file for the generator to the current list of active approvers.
/hold
/assign @cblecker @spiffxp
=> generator: update OWNERS

mentoring/group-mentee-guide.md, mentoring/group-mentoring.md, mentoring/meet-our-contributors.md, mentoring/processes/README.md, mentoring/processes/group-mentoring.md, mentoring/processes/hosting-moc.md, mentoring/programs/README.md
2660
took some boxes off of 2659, 2663
lots of mentoring doc updates and moving things into folders
=> more mentoring folder restructure

mentoring/OWNERS
adding marky to reviewers - thanks for your help!
=> adding marky to reviewers

communication/mailing-list-guidelines.md
=> removed personal emails on communication mailing list

communication/youtube/youtube-guidelines.md
The list of splain users was out of date. This updates it to reflect current state 👍
=> Update splain users (zoom -> youtube automation)

contributors/design-proposals/node/pod-resource-management.md
fix burstable/cpu.shares configured
Fixes #
=> fix burstable/cpu.shares configured

sig-instrumentation/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1597
/assign @brancz
=> Move custom-metrics-apiserver to k-sigs

sig-cluster-lifecycle/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1583
=> Rename addon-operators to cluster-addons

events/office-hours.md
Updating this to reflect reality, also added host instructions. 
/hold
=> Update Office Hours times and sessions for 2020

communication/marketing-team/CHARTER.md
Let the comments and commits begin! 🧡🧡🧡
Signed-off-by: Chris Short <chris@chrisshort.net>
Fixes #4437
=> Init K8s Upstream Marketing Team CHARTER.md

communication/marketing-team/README.md
adding more info to the marketing page like focus areas, resources for the team, etc.
=> adding more marketing info

sig-docs/README.md, sigs.yaml
Add Polish language content GitHub team to the list.
=> Add Polish language content GitHub team

sig-docs/blog-subproject/README.md
=> Remove shadow status for onlydole

communication/moderators.md
Fixes #
https://github.com/kubernetes/community/issues/4473
=> Moderators fix

contributors/guide/bug-bounty.md, contributors/guide/coding-conventions.md, contributors/guide/collab.md, contributors/guide/contributing.md, contributors/guide/expectations.md, contributors/guide/first-contribution.md, contributors/guide/getting-started.md, contributors/guide/github-workflow.md, contributors/guide/help-wanted.md, contributors/guide/issue-triage.md, contributors/guide/non-code-contributions.md, contributors/guide/owners.md, contributors/guide/pull-requests.md, contributors/guide/release-notes.md, contributors/guide/scalability-good-practices.md, contributors/guide/style-guide.md
=> Assigning weights to contributor documents for proper surfacing

sig-docs/README.md, sigs.yaml
updating the google docs link to be a non-archived one.
=> fixed google doc and generated page

contributors/design-proposals/architecture/namespaces.md
a docs update following the implementation in https://github.com/kubernetes/kubernetes/pull/73405
=> Add namespace status conditions

sig-scalability/README.md
=> Add information about oncall rotation to SIG Scalability readme.

sig-architecture/production-readiness.md
Adds clarifications for some PRR questions as discussed in the last meeting. Also fixes whitespace on a number of lines.
=> Update PRR questions based on feedback

communication/slack-config/channels.yaml
Signed-off-by: Karen Chu <karen.chu@microsoft.com>
**Description of Request:**
Need a place to discuss AKS Engine matters with the community.
**Which issue(s) this PR addresses:**
Issue #4482.
=> Add slack channels for aks-engine-users & aks-engine-devs

contributors/guide/README.md
-`Contributors' Guide` would be a better title then `Getting Started with Contributing`
=> Changing title metadata for ReadME to Contributors Guide

communication/slack-config/channels.yaml
addresses https://github.com/kubernetes/community/pull/4522#discussion_r379894215
fixes https://github.com/kubernetes/community/issues/4482
/cc @idvoretskyi @castrojo
=> slack: rename aks-engine-dev channel

sig-architecture/production-readiness.md
Minor clarification.
/assign @wojtek-t
=> Add clarification for PRR troublshooting question

communication/slack-config/channels.yaml
ref: https://github.com/kubernetes/community/issues/4534
/cc @thockin 
/assign @jeefy
=> slack: Add k8s-infra-alerts channel

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
=> add contributor-comms slack team for upstream marketing

sig-auth/README.md, sigs.yaml
Fixes https://github.com/kubernetes/org/issues/1245
=> [sig-auth] Add secrets-store-csi-driver subproject

sig-scalability/configs-and-limits/thresholds.md
/sig scalability
Ref. kubernetes/kubernetes#83375
=> [Access-tokens] Add thresholds

events/events-team/content/new-contributor-workshops/build-and-test.md, events/events-team/content/new-contributor-workshops/community-groups.md, events/events-team/content/new-contributor-workshops/how-we-communicate.md, events/events-team/content/new-contributor-workshops/labels-and-bots.md, events/events-team/content/new-contributor-workshops/live-pr-demo.md, events/events-team/content/new-contributor-workshops/new-contributor-workshop-lead.md, events/events-team/content/new-contributor-workshops/playground-exercise.md, events/events-team/content/new-contributor-workshops/workspace-setup.md
Minor improvements to the ncw playbook documentation. Fixed some dead links as well.
=> [docs]ncw playbook: minor improvements

mentoring/README.md
=> Adding a link to NCW youtube playlist

governance.md
1. Removed big data from sig list on gov doc
2. make generate
3. git add, git commit, &  git push with correct email + username
=> removed 'big data' from sig list on gov doc

mentoring/programs/shadow-roles.md
=> Updating mentoring shadow-roles.md

communication/youtube/youtube-guidelines.md
=> Updating youtube-guidelines.md with description notes

communication/youtube/youtube-guidelines.md
Updates splain users
/cc @markyjackson-taulia @onlydole @castrojo
=> Add sig network, wg data protection to splain user list

sig-api-machinery/README.md, sigs.yaml
=> Fix python client repository link in community/sigs.yaml

communication/slack-config/channels.yaml
Raksh is a community project for "Seamlessly use VM based TEEs with Kubernetes for data-in use protection", more information can be found in https://github.com/IBM/raksh#overview
And it is a developed under Apache License 2.0 license
Fixes #
=> Add channel for project Raksh

OWNERS_ALIASES, sig-docs/README.md, sigs.yaml
=> update sig-docs, tech leads

communication/moderators.md, mentoring/programs/outreachy.md
=> Adding me as coord & a note for having 3 coordinators

events/events-team/events-lead.md
ref: #4374
Fixed formatting and added guidelines regarding setting up meetings and access to contributors@kubernetes.io/community@kubernetes.io.
/hold
for review
/assign @jeefy @parispittman @geekygirldawn
=> Update event lead rolebook

events/events-team/marketing/README.md
ref: #4374 
Fixed formatting and added guidelines regarding access to both contributors@kubernetes.io and the CNCF/kubernetes twitter handles.
/hold
for review
/assign @parispittman @jonasrosland @castrojo
=> Update event marketing rolebook

OWNERS_ALIASES
This PR updates provider-openstack project co-leads
Fixes #
=> Update provider-openstack project co-leads

communication/slack-config/channels.yaml
Lokomotive is an open source Kubernetes distribution (Apache License)
that ships pure upstream Kubernetes. It focuses on being minimal, easy
to use, and secure by default.
Lokomotive is fully self-hosted and includes Lokomotive Components
adding essential functionality for production not shipped with upstream
Kubernetes.
https://github.com/kinvolk/lokomotive
Fixes #
=> New slack channel for Lokomotive

communication/slack-config/channels.yaml
Signed-off-by: Kris Nova <kris@nivenly.com>
Fixes #
=> feat(slack): add kubernetes-streaming slack channel

hack/.spelling_failures
Fixes Spelling Test Failures for PR #4638
=> Add 2019 survey to spelling exception list

sig-api-machinery/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1731
/assign @deads2k @lavalamp @fedebongio 
/hold
for sign off from leads ~+ for repo migration~
=> sig-api-machinery: add clientgofix repo

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
- Adding myself to the Upstream Marketing group because I enjoy contributing there 🚀
=> Add mbbroberg to usergroup

communication/moderators.md
=> Updating zoom administrators 

communication/marketing-team/OWNERS, communication/marketing-team/README.md, communication/marketing-team/social-guidelines.md, communication/marketing-team/team-resources.md
some of #4516, adding team member names, more robust information for the README, addition of OWNERs (i know it's invalid comments; will take it off post discussion)
=> marketing doc updates: roles, owners, guidelines, more

communication/moderation.md
=> Add instructions for adding a moderator

communication/mailing-list-guidelines.md
There were some changes to google groups, this updates our mailing list creation guidelines to fit those changes. 
Fixes #4200
=> Updating mailing list instructions to reflect groups changes.

sig-api-machinery/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1710
/assign @DirectXMan12 @pwittrock
=> sig-api-machinery: add kubebuilder-release-tools

sig-api-machinery/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/1700
/cc @brendandburns @ityuhui
/assign  @fedebongio @deads2k @lavalamp
/hold 
For sign-off from leads
=> sig-api-machinery: Add C Kubernetes Client Library repo

sig-cloud-provider/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/1716
/assign @cheftako @andrewsykim 
/hold
For sign off from leads
=> sig-cloud-provider: Add provider-baiducloud subproject

contributors/guide/README.md
=> Fix broken link to meet our contributors page

sig-storage/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1744, https://github.com/kubernetes/org/issues/1743
cc @kmova 
/assign @saad-ali @xing-yang @msau42 @jsafrane 
/hold
=> sig-storage: add repos to nfs-provisioner subproject

sig-auth/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1669
cc @JimBugwadia @hannibalhuang @ericavonb 
/assign @enj @mikedanese @tallclair @deads2k @liggitt 
/hold
for lgtm from sig-auth leads
=> sig-auth: add wg-policy-prototypes repo

sig-architecture/production-readiness.md
/assign @johnbelamaric @deads2k
=> Update PRR questionarire

events/2019/11-contributor-summit/RETRO.md
Converted the retro from gdoc to markdown and commiting it here. 
Fixes #4280
=> Add retrospective document

contributors/design-proposals/architecture/architecture.md
Link the 'what is kubernetes' url to the word 'Kubernetes'
=> Attach link to the correct text

contributors/devel/running-locally.md
Flag --replicas has been deprecated.
=> Delete deprecated flag in the guide

communication/slack-config/channels.yaml
The WG has been retired - https://github.com/kubernetes/community/pull/4689
Ref: https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md#steps
cc @derekwaynecarr @vishh
=> slack-config: archive wg-resource-mgmt channel

contributors/devel/sig-testing/e2e-tests.md
The federation codebase was removed from the kubernetes repo years ago, so there's no point in carrying documentation on how to test it.
=> Update e2e test doc to remove mention of federation testing

events/2019/06-contributor-summit/RETRO.md, events/events-team/feedback.md
=> Add Shanghai retro

communication/zoom-guidelines.md
Small bit of clarification on the waiting room function
/assign @castrojo
=> Update zoom guidelines with waiting room info

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml, sig-contributor-experience/role-handbooks/apac-coordinator.md
- introduce a slack user group for better collaboration
- onboard new members
/cc @kubernetes/sig-contributor-experience-apac-coordinators
=> sig-contribex APAC coordinator April update

sig-contributor-experience/README.md, sigs.yaml
=> Adding marketing team meeting notes

sig-testing/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/1783
=> sigs.yaml: add kubernetes-sigs/boskos

events/office-hours.md
Removed the reference to the City of Ottawa as I no longer work there. It was a great part of the intro and it will be missed.
=> Removed City of Ottawa from company list :(

contributors/devel/development.md
Add some improvements to building a local environment section.
Adds improvement to the developer guide to help users.
=> Update developer guide

sig-multicluster/namespace-sameness-position-statement.md
Add a position statement on Namespace Sameness in the multi-cluster world per the 2020/3/24 SIG-multicluster meeting. Let's embrace lazy consensus and give it a few weeks to gather feedback.
Discussion: https://groups.google.com/forum/#!msg/kubernetes-sig-multicluster/jfDAMxFWlOg/9Z9O0mVpAgAJ
@kubernetes/sig-multicluster-proposals
/cc @pmorie 
@thockin
=> Add Namespace Sameness position statement

sig-node/archive/meeting-notes-2019.md
/assign @dchen1107 @derekwaynecarr 
/sig node
=> Archive SIG-Node meeting notes 2019

sig-network/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/1823
=> migrate kubernetes-incubator/cluster-proportional* to kubernetes-sigs

mentoring/programs/the1-on-1hour.md
For #2657 Some cleanup and slight rewording
=> Cleanup and rewording on one on one mentoring

communication/slack-config/channels.yaml
cc @sspeiche @vaikas @n3wscott @pmorie @bbrowning 
(That's all the github handles I know.  I'll also reply to the mail thread)
Some more context: https://twitter.com/mattomata/status/1247691450961121280
=> Create a slack channel where we can discuss K8s Binding patterns.

OWNERS_ALIASES, sig-instrumentation/README.md, sigs.yaml
Context: https://groups.google.com/g/kubernetes-sig-instrumentation/c/j4WzdUE1S84
=> Add dashpole as sig-instrumentation tech lead

communication/marketing-team/multichannel-communications.md
This will add guidelines for multichannel communications for the marketing team.
Signed-off-by: Jonas Rosland <jrosland@vmware.com>
=> Add multichannel communications for the marketing team

communication/moderators.md
=> Loic is retiring from slack moderatorship, thanks for your service

communication/slack-config/channels.yaml
Can we please have a channel for homelab Kubernetes rigs?
The topic: Home hardware running Kubernetes community
I can update the topic and volunteer to triage any issues
that come up.
Signed-off-by: Kris Nova <kris@nivenly.com>
Fixes #
=> feat(slack): Adding homelab slack channel

sig-windows/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1853
/assign @michmike 
/hold
for lgtm from sig windows leads
=> sig-windows: add samples repo

OWNERS, contributors/devel/OWNERS, contributors/guide/OWNERS, sig-contributor-experience/devstats/OWNERS
ref: https://github.com/kubernetes/community/issues/4585
I have spoken to all owners referenced in these owners files and moved the folks to emeritus or removed as a reviewer with their permission 👍 
Thanks to all for their time helping with these subprojects <3
/cc @calebamiles @Phillels @kbarnard10 
/assign @castrojo @nikhita @cblecker
=> Update contribex subproject owners

communication/slack-config/channels.yaml
Need a place to discuss [secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) matters in the community
Fixes #4775
=> add slack channel for csi-secrets-store

committee-steering/governance/annual-reports.md, committee-steering/governance/sig-governance.md, committee-steering/governance/ug-governance.md, committee-steering/governance/wg-governance.md, governance.md
https://github.com/kubernetes/steering/issues/153
I'm aware that the formatting needs work. This is going up for discussion in Steering meeting today.
=> adding community group annual report/health check

contributors/guide/issue-triage.md
=> Added Triage Party to Table of Contents

contributors/devel/sig-release/getting-builds.md
Followup to https://github.com/kubernetes/test-infra/pull/17672
=> Remove reference to latest-green.txt

.github/ISSUE_TEMPLATE/marketing-request.md
- Creates a way to request support from Upstream Marketing Group
Signed-off-by: Matthew Broberg <1744971+mbbroberg@users.noreply.github.com>
=> Add issue template for communication

contributors/devel/sig-node/e2e-node-tests.md
Adds a couple of commands that are needed before remote tests can be run.
Fixes N/A
=> e2e node: add commands for gcloud config

sig-multicluster/namespace-sameness-position-statement.md
Follows the example of
https://github.com/kubernetes/community/blob/master/sig-api-machinery/api-extensions-position-statement.md
/assign @pmorie
=> Change ns-sameness position statement to RELEASED

sig-instrumentation/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1907
/assign @logicalhan @dashpole @ehashman @brancz 
/hold
for lgtm from sig-instrumentation leads
=> sig-instrumentation: add instrumentation-tools repo

contributors/guide/collab.md, contributors/guide/review-guidelines.md
Fixes #1514
Fixes #1645 
- This PR adds a doc specifying the **guidelines for the reviewer**
=> feat: Addition of Reviewer's Guideline

communication/slack-config/channels.yaml
Signed-off-by: shubham <shubham.bajpai@mayadata.io>
This channel is to go alongside the existing #openebs and should be managed the same way. 
The intent with #openebs-dev is to provide separation of development-related discussions and other notification mechanisms to track changes from user queries and feature requests.
Please let me know if you have any questions. Thanks!
=> add openebs-dev slack channel

contributors/devel/development.md
=> Development: Fix typo

contributors/devel/sig-architecture/conformance-tests.md, sig-architecture/README.md
=> Replace refs for conformance.txt to conformance.yaml

events/office-hours.md
This is a no-op. No content changes were made, just formatting.
=> Update formatting of office hours doc

committee-steering/governance/sig-governance.md
Ref #4781
File modified: [sig-governance.md]
Enhancements/editions:
[x] white spacing issues
[x] line 69-72 needs editorial changes
[x] general formatting and other style guide changes
@parispittman 
[sig-governance.md]: https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md
=> sig-gov de-dupping evolution continues #4781

communication/slack-config/channels.yaml
A public channel to discuss all things related to kubernetes github management
/assign @cblecker @fejta @idvoretskyi  @nikhita @spiffxp 
/hold
=> Add github-management slack channel

github-management/opening-a-request.md, sig-contributor-experience/README.md, sigs.yaml
=> Document #github-management slack channel

communication/marketing-team/README.md
Per conversation with Paris, adding myself to the storytellers section.
Fixes #
=> marketing: add Divya Mohan to the storytellers team

communication/marketing-team/README.md
officially off of editor bootstrap and handing the keys to the car to @mbbroberg 
also added:
-twitter
-issue template
=> marketing team additions

contributors/devel/sig-testing/testing.md
=> Adding link to San Diego CS testgrid presentation

contributors/devel/development.md
Ref: https://github.com/kubernetes/kubernetes/pull/88638, https://github.com/kubernetes/kubernetes/pull/92438
=> devel: update required Go versions

contributors/devel/sig-api-machinery/generating-clientset.md
Fixes https://github.com/kubernetes/community/issues/4882
=> Update broken file link in title 3

sig-testing/README.md, sigs.yaml
Dropped gopherage and gubernator since they are inactive
Added kubetest2
=> Update sig testing subprojects

communication/slack-config/channels.yaml
Signed-off-by: Karen Chu <karen.chu@microsoft.com>
Description of Request:
Need a place to discuss Krustlet matters with the community.
=> Add slack channels for krustlet

contributors/devel/sig-testing/bazel.md
Ref kubernetes/test-infra#17254
Planter was removed by kubernetes/test-infra#17254, this PR synchronizes this change.
=> Remove planter from bazel.md

sig-contributor-experience/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/1971
/assign @nikhita
=> sig-contribex: Add contributor-tweets repo to community-mgmt subproject

sig-storage/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1942
/assign @saad-ali @xing-yang @jsafrane @msau42 
for lgtm
/hold
for lgtm from sig storage leads
=> sig-storage: add COSI repos

sig-wg-lifecycle.md
=> #4904 add mailing list creation in the SIG/wg lifecycle document

sig-testing/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1977
cc @amwat 
/assign @BenTheElder @spiffxp @stevekuznetsov 
for lgtm
/hold
for lgtm from sig-testing leads
=> sig-testing: add kubetest2 repo

committee-steering/governance/annual-reports.md
ref: https://github.com/kubernetes/steering/issues/164
=> adding 2020 wg reporting process steps

communication/marketing-team/social-guidelines.md
Adding self as an org member with access to the account. Adding more information about the themes/topics the group focuses on.
/cc @parispittman 
/sig-contribex
=> Adding Kaslin and updating guidelines.

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
Signed-off-by: Carlisia <carlisia@vmware.com>
=> Remove Steve Kriss from the Velero slack

community-membership.md
principal -> principle
English can be frustrating -_-
=> Fix grammar error in community membership guidelines

sig-testing/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/2026
/assign @BenTheElder @spiffxp
=> sig-testing: Add secret-sync-rotation subproject

communication/slack-config/sig-release/usergroups.yaml
Ref https://github.com/kubernetes/sig-release/pull/1123
=> Add saschagrunert and alejandrox1 to slack release-team-leads

committee-code-of-conduct/election.md
* Update nominee eligibility to include anyone that meets the eligibility for candidacy guidelines
* Add nomination process
xref: https://github.com/kubernetes/steering/issues/169
/committee code-of-conduct
=> Update Code of Conduct Committee election and nomination process

contributors/devel/README.md, contributors/devel/sig-architecture/api_changes.md, contributors/devel/sig-scheduling/scheduler.md
The initial purpose of this is to make sure there are no orphaned files in the Developer Guide, so we can make a complete map of all the content there.
=> Index all SIG contributions to the Developer Guide

communication/marketing-team/README.md
=> Listing APAC liaison role for marketing team

communication/youtube/youtube-guidelines.md
=> Update youtube guidelines to include subprojects

sig-cluster-lifecycle/README.md, sigs.yaml
Signed-off-by: championshuttler <shivams2799@gmail.com>
=> Add the meeting notes for etcdadm Office Hours

sig-release/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/1875
/assign @saschagrunert 
for lgtm
/hold
for lgtm from a sig-release lead
=> sig-release: add kubernetes-sigs/mdtoc repo

mentoring/README.md, mentoring/programs/office-hours.md
Signed-off-by: championshuttler <shivams2799@gmail.com>
Fixes  #4409
cc @mrbobbytables
=> Add Office Hours/ Mentoring of different SIGs

communication/slack-config/sig-docs/docs-channels.yaml
Fixes #4979 
/assign @sftim @jimangel @kbarnard10 
Holding for 👍 from @sattarfeizollahibarough
/hold
/sig docs
/language fa
=> Add a channel for Persian docs

contributors/devel/sig-architecture/conformance-tests.md
See the review thread at https://github.com/kubernetes/kubernetes/pull/93487#discussion_r461859648 for context
/cc @Jefftree @heyste
=> Fix formatting nit in example conformance comment

communication/calendar-guidelines.md, contributors/chairs-and-techleads/README.md
Adding a calendar event template that can be used as a reference
CC: @parispittman @jonasrosland @mbbroberg
=> Calendar template

communication/marketing-team/README.md
This PR promotes @rajula96reddy to lead for internal comms within the marketing team.
=> Promote Rajula as lead for internal comms

contributors/devel/sig-architecture/conformance-tests.md
Signed-off-by: knight42 <anonymousknight96@gmail.com>
Describe how to run conformance tests with kind as per @aojea's instructions: https://github.com/kubernetes-sigs/kind/issues/1181#issuecomment-567001724
Fixes #
=> doc: describe how to run conformance tests with kind

committee-code-of-conduct/charter.md
Fix typo, unamimous -> unanimous
=> Fix grammar error in committee-code-of-conduct

contributors/devel/automation.md
=> Fixed formatting of automation.md

contributors/devel/sig-architecture/api-conventions.md
Fixes#
Modified the first two bullet points under Naming conventions
=> Updated api-conventions.md

sig-contributor-experience/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/2081
=> sig-contribex: add .github repos

sig-multicluster/README.md, sigs.yaml
Ref: kubernetes/org#1970
/assign @nikhita @pmorie 
Replaces #5012
=> sig-multicluster: add mcs-api repo

communication/slack-config/sig-docs/docs-channels.yaml
Fixes #5026 
/sig docs
cc @kubernetes/website-maintainers 
/assign @jimangel @kbarnard10
=> Add Slack channel for SIG Docs localizations

events/elections/2020/README.md
Adds the missing word "see".
Adds sentence about terminating mail threads once endorsements have been reached.
=> Added two changes to the Endorsement section per Nikhita and Paris.

events/elections/2020/voters.md
As written this gave me a 404! I think this was the page you meant?
=> Fix broken link to 2020 elections

events/elections/2020/voters.md
68 eligible voters added to list.
This does not fix all missing voters; there is an undiagnosed issue with a few contributors missing from the Devstats dump.  The remaining omissions will be corrected on Friday.
/assign jdumars idvoretskyi castrojo
=> Correct list of voters based on case mismatch in github handles.

events/elections/2020/README.md
Fixing typo. 
Link is declared here:
=> Fixed the link to exemption form

sig-release/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/2131
/assign @justaugustus
=> sig-release: add downloadkubernetes to sigs.yaml

.github/ISSUE_TEMPLATE/marketing-request.md
With a focus on ease of use and clarity around communication timeline. Also, we self-market ourselves, because we definitely should do that.
Signed-off-by: Matthew Broberg <matt@opensource.com>
Fixes #4931 
/sig contribor-experience
=> Revise Comms template

contributors/guide/README.md
=> Meetups subsection updated

communication/slack-config/channels.yaml
Requesting channel for the newly-forming SIG-Security
https://github.com/kubernetes/community/tree/master/sig-security
Fixes #
=> Requesting SIG-Security channel

communication/zoom-guidelines.md, contributors/chairs-and-techleads/README.md
=> Rename kubernetes-sig-leads mentions to leads@ since the group has moved

sig-security/README.md, sigs.yaml
Added an agenda/archive link to SIG-Security README via sigs.yaml.
=> Added an agenda/archive link to SIG-Security README via sigs.yaml.

events/elections/2020/README.md
Ref: https://groups.google.com/a/kubernetes.io/g/steering/c/X_tyu2F04XQ
/assign @idvoretskyi
=> elections: add date for steering/candidate Q+A session

sig-contributor-experience/README.md
=> We give talks about contribex, this lists some good ones in our README

events/elections/2020/voters.md
Adds three voters based on outstanding exception requests as of Sept. 2.
/assign jdumars idvoretskyi 
=> Added three voters to voters.md based on exception requests

README.md
=> chore: remove broken link image from readme

communication/slack-config/channels.yaml
Intended for discussion around the Node Feature Discovery project:
https://github.com/kubernetes-sigs/node-feature-discovery
=> Add slack channel for node-feature-discovery

events/elections/2020/biotemplate.md
Got accidentally removed in https://github.com/kubernetes/community/pull/5115
/assign @idvoretskyi
=> elections: re-add biotemplate.md

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
=> Add rajula to upstream marketing slack usergroup

events/elections/2020/README.md, events/elections/2020/stephenaugustus.md
=> Add 2020 Steering candidate bio for Stephen Augustus

events/elections/2020/README.md, events/elections/2020/davanumsrinivas.md
=> Add Dims bio for 2020 steering election

communication/slack-config/channels.yaml
CRAFT is a project developed at Salesforce to facilitate easy operator creation. CRAFT declares Kubernetes Operators in a robust and generic way for any resource, letting developers focus on CRUD (create, read, update and delete) operations of resource management in a Dockerfile. With CRAFT you can create operators without a dependent layer and in the language of your choice. Further info: https://github.com/salesforce/craft#custom-resource-abstraction-fabrication-tool
We would like to create a channel in the Kubernetes community which can be used to raise and solve issues and suggest improvements on the existing framework and documentation.
Fixes #
=> Update channels.yaml to include new slack channel.

events/elections/2020/bobkillen.md
/assign @jdumars @jberkus @idvoretskyi
=> Add Bob Killen  bio for 2020 Steering Committee election

events/elections/2020/README.md, events/elections/2020/lachlanevenson.md
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
/assign @jdumars @idvoretskyi @jberkus
=> Add Lachlan Evenson candidate bio for SC 2020 election

events/elections/2020/voters.md
This should be the final update to voters.md
/assign jdumars idvoretskyi
=> Added two more voters per exception requests.

events/elections/2020/README.md, events/elections/2020/fedebongio.md
=> Add Federico Bongiovanni BIO for Steering election

events/elections/2020/README.md, events/elections/2020/mayankkumar.md
=> add mayanks bio for 2020 steering election

events/elections/2020/README.md, events/elections/2020/templates/election-templates.md
Just some documentation changes.
/assign jdumars idvoretskyi 
=> Add link to ballot replacement form and ballot template

sig-api-machinery/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/2193
/cc @pwittrock 
/hold
=> sig-api-machinery: Add apiserver-runtime repo

README.md, contributors/guide/contributing.md
Signed-off-by: Neha Viswanathan <itsnehavis@gmail.com>
Fixes #https://github.com/kubernetes/website/issues/23964
=> fix broken links in README

mentoring/programs/README.md
=> Changing mentoring meeting time

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
Please add Stephanie Bauman to our Velero user group.
c/c @stephbman
Signed-off-by: Carlisia <carlisia@vmware.com>
=> Add Stephanie + Bridget to the Velero user group

communication/slack-config/channels.yaml
WG-Reliability has been approved in: https://github.com/kubernetes/community/pull/5127
/cc @deads2k @stevekuznetsov
=> Create WG-Reliability slack channel

communication/slack-config/sig-release/usergroups.yaml
=> releng: Add Marky to Release Manager Associates

contributors/guide/README.md
Made first-pass changes to bring the contributor guide in line with the Kubernetes documentation style guide.
Fixes #
=> Updated readme.md to align with style guide

events/elections/2020/README.md
This deadline was mentioned in email, but not put in the README.
/assign jdumars idvoretskyi 
=> Add in deadline for replacement ballot requests.

contributors/design-proposals/service-catalog/pod-preset.md
indicating removal of PodPresets
xref https://github.com/kubernetes/kubernetes/issues/93900
xref https://github.com/kubernetes/kubernetes/pull/94090
=> indicate removal of PodPresets

communication/slack-config/channels.yaml
[PureLB](https://gitlab.com/purelb/purelb) is a new open source load
balancer controller for Kubernetes.  May we please have a slack
channel for user discussion?
Thank you
=> Slack channel for discussion of the PureLB load balancer

contributors/guide/first-contribution.md
WIP: Updating 'Your First Contribution' page to align with Kubernetes Developer Style Guide.
=> Update first contribution page

sig-cluster-lifecycle/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/2247
/assign @neolit123 
cc @christopherhein
=> SCL: add cluster-api-provider-nested repo

contributors/chairs-and-techleads/README.md
=> Add a section on swag capabilities available to cochairs and TLs

contributors/devel/sig-instrumentation/logging.md
As part of the structured logging migration It's probably worth having a line here for `InfoS()`
=> Mention the new structured logging convention

communication/slack-config/sig-docs/docs-channels.yaml
Fixes https://github.com/kubernetes/community/issues/5210
=> fix: Rename kubernetes-docs-be to kubernetes-docs-bn

contributors/guide/README.md
Fixes https://github.com/kubernetes/community/issues/5220
=> Fixes broken hyperlinks in the contributor guide

sigs.yaml, wg-reliability/README.md, wg-reliability/charter.md
/cc @deads2k @stevekuznetsov 
@kubernetes/steering-committee
=> Create Reliability WG charter

communication/youtube/youtube-guidelines.md
=> Video tutorial for youtube administrator

CLA.md
=> fix missing link

communication/slack-config/channels.yaml
Signed-off-by: Edrick Wong edwong@microsoft.com
Project URL: https://github.com/deislabs/akri
Description of Request:
We would like to have a centralized place to for users and contributors to discuss about Akri.
Fixes #
=> Add Slack channel for Akri

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
=> Create operator-sdk-maintainers slack group

events/office-hours.md
I noticed that office hours page stated Western Office hours were at 9am PT. The correct start time should be 5pm PT.
=> Fixed start time of Western Office hours.

communication/slack-config/channels.yaml
ref: https://github.com/kubernetes/community/issues/5254
/cc @dims
=> Slack: Archive retired working group channels

sig-storage/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/2289
/hold 
=> sig-storage: add cosi-api repo

contributors/devel/development.md
Updated the number of contributors in the document
Fixes  Issue in the document
=> Updated the number of contributors in the document

wg-naming/recommendations/template.md
Adds a template for recording recommendations to the WG Naming sub-directory.
=> [WG Naming] Add recommendation template

sig-cluster-lifecycle/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/2296
/assign @benmoss
=> SCL: add cluster-api-provider-kubemark repo

sig-testing/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/2271
/assign @spiffxp @BenTheElder 
/hold
for lgtm from sig-testing leads
=> sig-testing: add e2e-framework repo

sig-cli/CONTRIBUTING.md
Added Codebase Tour Video
Adding more resources for new contributors
=> Added Codebase Tour Video

sig-wg-lifecycle.md
kubernetes-sig-leads@googlegroups.com -> leads@kubernetes.io
The leads mailing list is no a managed list under the kubernetes.io
gsuite.
/cc @parispittman @castrojo 
/hold
=> Update leads mailing list reference

communication/slack-config/channels.yaml
Adds #image-builder channel for discussions related to  https://github.com/kubernetes-sigs/image-builder. 
This came up in #sig-cluster-lifecycle slack channel: https://kubernetes.slack.com/archives/C13J86Z63/p1604505942054800?thread_ts=1604505726.054600&cid=C13J86Z63
/cc @neolit123 @moshloop
=> Add #image-builder channel

contributors/chairs-and-techleads/technical-lead.md
We now split up the huge sentence into a list of bullet points under the
headline of the expectations of technical leads.
Follow up of https://github.com/kubernetes/community/pull/5179#discussion_r507764919
=> Reformat Technical Lead expectations

mentoring/OWNERS
=> Adding Marky Jackson to mentoring approvers

contributors/devel/sig-architecture/api-conventions.md
=> api-conventions: Typo in initials

sigs.yaml, wg-data-protection/README.md
Updates the Data Protection WG page to include a doc that tracks our work as suggested by the steering committee.
=> Update Data Protection WG page

sig-architecture/README.md
Signed-off-by: Sushmita Amarnath <sushmita.amarnath@gmail.com>
Fixes #
=> Adding KEP process info

contributors/guide/pull-requests.md
For the more compulsive among us, let's have a space just before a sentence begins.
Fixes nothing much
=> tiny whitespace fix

contributors/guide/first-contribution.md
Fix small typo in first-contribution page
=> Fix small typo

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
c/c @dsu-igeek
Signed-off-by: Carlisia <carlisia@vmware.com>
=> Add Dave Smith-Uchida to the Velero group

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
c/c @stephbman
Signed-off-by: Carlisia <carlisia@vmware.com>
=> Remove Stephanie from the Velero slack

contributors/devel/README.md, contributors/devel/sig-storage/flexvolume.md
This PR adds CSI drivers doc to the sig-storage developer guide.
Fixes #5238
=> Add CSI driver doc to developer guide

communication/slack-config/users.yaml
Not sure how this happened but Slack User ID for Mrinal Das was not correct.
@mik-dass, can you please confirm that this is your correct Slack User ID on Kubernetes Slack?
Fixes #
=> slack-config: fix mik-dass user ID

communication/marketing-team/OWNERS, communication/slack-config/usergroups.yaml
This will remove myself from the comms team files.
=> Remove jonasrosland from the comms team

communication/marketing-team/OWNERS
Signed-off-by: championshuttler <shivams2799@gmail.com>
Fixes #5281
=> Update the OWNERS for upstream marketing sub group

communication/slack-config/channels.yaml
Headlamp is an easy-to-use and extensible Kubernetes web UI.
https://github.com/kinvolk/headlamp
Headlamp was created to be a Kubernetes web UI that has the traditional
functionality of other web UIs/dashboards available (i.e. to list and
view resources) as well as other features.
It is available under the Apache 2.0 license.
@joaquimrocha 
Fixes #
=> New slack channel for Headlamp

communication/slack-config/channels.yaml
Add a channel for API priority and fairness discussions.
=> add channel for APF

contributors/guide/contributing.md
Added a link to, 'How to Make Your Code Reviewer Fall in Love With You,' by Michael Lynch
=> Added link to best practices section

sig-contributor-experience/role-handbooks/apac-coordinator.md
This PR updates the meeting doc link in APAC coordinator page. The existing linked doc has been archived.
=> Updating Meeting Doc For APAC Coordinator

wg-k8s-infra/2020-annual-report.md
For https://github.com/kubernetes/steering/issues/164
/hold
/assign @bartsmykla @dims @spiffxp 
=> wg-k8s-infra: add 2020 annual report

sig-instrumentation/README.md, sigs.yaml
I no longer work at Red Hat :) 
@logicalhan @ehashman @dashpole
=> sig-instrumentation: Update my company association

communication/marketing-team/social-guidelines.md
I now have access to the account and I'm documenting it.
=> Add to social media list

contributors/guide/README.md
Change "open ource" to "open source".
=> Fix a typo in contributors/guide/README.md

sig-instrumentation/archive/meeting-notes-2020.md
Archive SIG Instrumentation meeting notes from 2020.
=> Add 2020 meeting notes archive

communication/slack-config/channels.yaml
N/A
Relates to https://github.com/kedacore/governance/issues/11
=> Request for keda-dev channel

communication/slack-config/sig-release/usergroups.yaml
Adds @jeremyrickard to sig-release slack groups as part of technical lead
onboarding.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
xref https://github.com/kubernetes/sig-release/issues/1421
/hold
/assign @justaugustus @saschagrunert
=> slack-config: Add Jeremy Rickard as a SIG Release Technical Lead

communication/best-practices.md, communication/calendar-guidelines.md, communication/discuss-guidelines.md, communication/mailing-list-guidelines.md, communication/moderation.md, communication/moderators.md, communication/requesting-survey.md, communication/slack-guidelines.md, communication/website-guidelines.md, communication/youtube/youtube-guidelines.md, communication/zoom-guidelines.md
This PR updates all our comms documents with Hugo metadata, applies the style guide and fixes several out of date things.
Beyond that, content is has not been changed.
After this is merged, these docs should be surfaceable on the contributor site
=> Update comms guidelines

committee-steering/governance/annual-reports.md
most of the changes actually happened in the linked doc with the questions but they are also reflected on this doc 
discussed at Dec 7th Steering meeting:
http://bit.ly/k8s-steering-wd
only missing item: examples of good responses / link to wg-k8s-infra
=> 2021 annual report process updates and formatting

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
@mattmoyer @ankeesler @cfryanr @margocrawf @microwavables
=> Add slack user group for Pinniped developers

CLA.md
=> [minor] fix Github

contributors/guide/issue-triage.md
Update triage guidelines for the new automation.
Related #4743
=> Update triage guidelines

contributors/devel/sig-instrumentation/migration-to-structured-logging.md
Signed-off-by: chymy <chang.min1@zte.com.cn>
Add formatting language ‘go’
Fixes #
=> add 'go' for code

contributors/devel/development.md
This PR fixes spell errors and improved wording in contributors/devel/development.md
Fixes #
=> Fixed spell errors contributors/devel/development.md

communication/moderators.md, communication/slack-config/usergroups.yaml
ref: #5180
+@alisondy as new contribex chair
=> Update YouTube admins

contributors/devel/development.md
Update contributors development.md because the yum installation command on Linux is incorrect
=> Update contributors development.md

sig-security/security-audit-2021/RFP.md
**Which issue(s) this PR fixes**: none
This is the initial publication of the RFP for sig-security's third-party security audit sub-project.
=> Initial publication of 2021 third-party security audit RFP.

sig-security/security-audit-2021/RFP.md
Fixed incorrect date in Anticipated Selection Schedule
Fixes # none
=> Update 2021 Security Audit date typo

contributors/devel/sig-release/flake-finders/README.md, contributors/devel/sig-release/flake-finders/episodes/000/README.md
n/a
Bootstraps new subdir for the Flake Finder Fridays livestream.
/assign @justaugustus @saschagrunert 
/cc @RobertKielty
=> Add Flake Finder Fridays assets

wg-iot-edge/whitepapers/edge-security-challenges/README.md
=> Spelling and grammar fixes in edge whitepaper

liaisons.md, sig-api-machinery/README.md, sigs.yaml
=> typo in liaison name

contributors/devel/sig-instrumentation/migration-to-structured-logging.md
Per Slack discussion: https://kubernetes.slack.com/archives/C5P3FE08M/p1612207645034900
/cc @serathius @neolit123
=> Add guidance for fatal exit codes

contributors/devel/sig-release/cherry-picks.md
Updates cherry pick guide to note that applicable patches must be made
to all active release branches at the same time so that the fix will be
included for each in the same round of patch releases.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
/assign @justaugustus @saschagrunert
=> Require applicable cherry picks to active branches

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
=> Add Pablo to Pinniped user group

values.md
This pull request aims to rewrite the community values in terms of improving the grammar, active voice statements and commas. 
Fixes #5408
=> Rewrite community values 

mentoring/programs/new-contributor-workshop/resources/README.md, mentoring/programs/new-contributor-workshop/resources/new-contributor-workshop-lead.md
Slack discussion - https://kubernetes.slack.com/archives/C1TU9EB9S/p1612938420171600
/hold
/assign @mrbobbytables @alisondy @idvoretskyi 
cc @palnabarun @divya-mohan0209
=> NCW: Add docs for requesting coupon codes

communication/youtube/youtube-guidelines.md
Fixes #5451
Updated youtube-guidelines.md file.
=> Updated youtube-guidelines.md

sig-testing/README.md, sigs.yaml
Fixes https://github.com/kubernetes/org/issues/2490
/assign @BenTheElder 
/hold
for lgtm from sig-testing leads
=> sig-testing: add k/sig-testing repo

contributors/devel/sig-instrumentation/migration-to-structured-logging.md
/cc @ehashman @thockin @DirectXMan12
=> Update instruction for naming arguments

sig-multicluster/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/2468
/assign @pmorie @JeremyOT 
/hold
for lgtm from sig-multicluster leads
=> sig-multicluster: add work-api repo

contributors/devel/sig-instrumentation/logging.md
Related to https://github.com/kubernetes/kubernetes/issues/94428 and https://github.com/kubernetes/kubernetes/pull/99033.
@smarterclayton @lavalamp
=> update logging guideline re. shared libraries

contributors/devel/sig-release/flake-finders/episodes/000/README.md
Fixes code block formatting in guide for flake finders episode 000.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
n/a
=> [flake finders] fix episode 000 readme formatting

wg-api-expression/2020-annual-report.md
=> wg-api-expression annual report

wg-multitenancy/2021-annual-report.md
Copy/paste of wg-multitenancy report
Co-authored-by: Tasha Drew <tasha.drew@gmail.com>
/cc @srampa @tashimi
cc @kubernetes/steering-committee 
/hold for sig and steering review
=> Add 2021 wg-multitenancy annual report

contributors/guide/first-contribution.md
Fixes a small typo (SIG'ss) in the Your First Contribution page.
=> Fix typo in first-contribution page

community-membership.md
Capitalizing some points and improving general flow.  
As suggested on #pr-reviews - just to mention this is my first submission to any project - so a complete newbie. I read everything I can, so keen to jump in and get some experience submitting PRs
Fixes #
=> Grammatically updated Community Membership doc

sig-release/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/2539
/hold
=> SIG Release: Add release-sdk, release-utils repos

sig-service-catalog/charter.md
Update helm repository for sig-service-catalog
=> Update helm repository for sig-service-catalog
