kubernetes/community

contributors/devel/sig-api-machinery/OWNERS
contributors/devel/sig-architecture/OWNERS
contributors/devel/sig-instrumentation/OWNERS
contributors/devel/sig-node/OWNERS
contributors/devel/sig-release/OWNERS
contributors/devel/sig-scalability/OWNERS
contributors/devel/sig-scheduling/OWNERS
contributors/devel/sig-storage/OWNERS
contributors/devel/sig-testing/OWNERS

~~The first commit renames the sig sub-dirs from `sig-api-machinery` -> `api-machinery` and so on, to make it consistent with the nomenclature in [design-proposals](https://github.com/kubernetes/community/tree/master/contributors/design-proposals).~~ This will break a bunch of links. This isn't a super important change, so if we really need this, it can go in another PR.
The ~~second~~ commit adds OWNERS files to the existing SIG sub-directories. The content of the OWNERS file is same as that in [design-proposals](https://github.com/kubernetes/community/tree/master/contributors/design-proposals).
/cc @parispittman @eduartua @cblecker

 devel: add OWNERS files for SIG sub-directories 

---

contributors/guide/github-workflow.md
sig-azure/charter.md
sig-multicluster/CONTRIBUTING.md
sig-storage/contributing.md

The following broken links are fixed in the community documentation
FILE: ./sig-azure/charter.md
[✖] contributors/devel/owners.md → Status: 400 Error: ENOENT: no such file or directory, access '/home/jorge/src/kubernetes/community/sig-azure/contributors/devel/owners.md'
FILE: ./sig-storage/contributing.md
[✖] https://git.k8s.io/kubernetes/examples/volumes/flexvolume → Status: 404
FILE: ./sig-multicluster/CONTRIBUTING.md
[✖] http://github.com/kubernetes/community/blob/master/contributors/design-proposals/sig-multicluster → Status: 404
[✖] http://github.com/kubernetes/community/blob/master/contributors/design-proposals/sig-multicluster/template.md → Status: 404
FILE: ./contributors/guide/github-workflow.md
[✖] https://github.com/$user/kubernetes → Status: 404
[✖] https://reviewable.k8s.io → …

Broken Links fix for 2696

---

governance.md

As per Brian Grant in another thread https://github.com/kubernetes/community/pull/3174#discussion_r252500194
> Yes, it is intended. They are subgroups of SIGs. Thanks.
Since subprojects (like cluster-api) are subsumed by actual SIGs like cluster-lifecyle, I think it should be 4 "main types of groups".

clarify the actual number of main types of groups

---

Makefile

The `Makefile` has `generate-dockerized` and `test-dockerized`. For
consistency, and also because its helpful for those who may not have
their Go environment properly setup, add `verify-dockerized` to the
Dockerfile. Its responsible for running `verify` in the docker
container.

Add `verify-dockerized` to Makefile

---

Makefile

Previously, we used the Go 1.9 image for our dockerized targets in the
Makefile. The k8s project mandates Go 1.11 for k8s 1.13+
(https://github.com/kubernetes/community/blob/master/contributors/devel/development.md),
so there's no reason not to use Go 1.11 here.
I've verified all existing dockerized targets still work with go 1.11.

Use go 1.11 for Dockerized Makefile targets

---

sig-governance.md

Add info on moving sig repo into archives when a SIG is retired.
Closes: #3189 
cc: @castrojo

add info on archiving community repos

---

communication/README.md
communication/discuss-guidelines.md
communication/slack-guidelines.md
communication/zoom-guidelines.md
contributors/guide/README.md
governance.md

Ref: https://github.com/kubernetes/community/pull/3160
We should point to the Kubernetes Code of Conduct instead of the CNCF Code of Conduct since that's the source of truth for Kubernetes.
/committee conduct

Update CoC links to the Kubernetes CoC instead of the CNCF CoC

---

contributors/devel/sig-testing/integration-tests.md
contributors/devel/sig-testing/testing.md

Previously, information on running unit and integration tests lived in
the testing.md doc, while information on running e2e tests lived in its
own doc. The testing.md doc is getting large, and particularly since its
a doc that many new members of the project look at, I think there's a
lot of benefit to keeping it concise.
To accomplish this, move information around running integration tests
into integration-tests.md, and then link to said document from
testing.md. This allows a new member of the project to get up and
running with unit tests, and then explore integration/e2e testing as
they have the need.

Make integration-tests its own doc

---

communication/moderators.md

Hi Community,
As this is my first PR I really wanted to express my excitement and enthusiasm being part of such a great community. I hope I did everything right for my first PR but bear with me while I am learning the process and how to interact with the community. 
What this PR is actually about:
When looking over the [moderators](https://github.com/kubernetes/community/blob/9dc2678523eae4cea7aee86a6938e43cc2d3033d/communication/moderators.md) page I found that the link to the `moderation guidelines` is broken. This PR is intended to fix this.
Once again, I am excited of being part in this community and hope for many more PRs (also on the technical side) to come.
Best,
Fabian

fixing broken link to moderation guidelines

---

contributors/devel/sig-testing/testing.md

Improve the testing documentation in the following ways:
1. Ensure all of the given commands actually work. Some of them
specified tests that no longer existed or packages that no longer had
tests.
2. Clarify the ability to run tests for a package and all its
subpackages with `/...`.
3. Clarify how the developer can also utilize `go test` if they desire.

Fix and update testing documentation

---

contributors/devel/sig-testing/bazel.md

The default python on my system is python3. This caused me to run into
https://github.com/bazelbuild/rules_docker/issues/454 when running
`bazel build //...`. Update the documentation to indicate that
`/usr/bin/env python` must resolve to python2 in order for all of the
Bazel commands included in the documentation to work.
We can remove this comment after Bazel better supports using python3 as
the default system python. It appears from
https://github.com/bazelbuild/rules_docker/issues/580 that the
`rules_docker` folks hope to merge the fix in mid to late Q1 2019.

Specify need for using py2 with Bazel

---

wg-security-audit/README.md
wg-security-audit/RFP_Decision.md

In the interest of transparency, the Security Audit Working Group would like to document the decision process we used for evaluating the vendor proposals for the security audit. 
cc the rest of the WG: @aasmall @joelsmith

Add vendor selection process writeup for security audit

---

contributors/design-proposals/auth/encryption.md

This replaces https://github.com/kubernetes/community/pull/454 and is an updated version so we could continue to move the design forward as andrew didn't have bandwidth to continue.
I've updated the doc with most of the feedback and split out a few design options of increasing complexity so we can decide where to go next.
Based on the work that's been done in:
https://docs.google.com/document/d/1lFhPLlvkCo3XFC2xFDPSn0jAGpqKcCCZaNsBAv8zFdE/.
Related:
kubernetes/features#92
kubernetes/kubernetes#32579
kubernetes/kubernetes#12742
@kubernetes/sig-auth-misc

Encryption of secrets at the database layer

---

sig-release/README.md
sigs.yaml

It's confusing having two links for the release-engineering subproject
without any description of each. The k/release repo houses all of the
existing tooling, such as anago, while the k/sig-release repo houses the
procedures and processes. Add these links explicitly to the description
so that newcomers have a clearer idea of where to get started.

Add explicit links to release-engineering in sig-release

---

contributors/devel/sig-architecture/godep.md

This PR points to the list of approved whitelisted licenses by the CNCF Governing Board, as per the [slide deck](https://docs.google.com/presentation/d/1tbH15qF7bXOp8veRKHlWSeH6w1NWkMN3qmIwB6LvvgU/edit#slide=id.p1) shared by @swinslow. (Ref: https://github.com/kubernetes/steering/issues/57#issuecomment-458968990)
https://github.com/kubernetes/sig-release/pull/504 adds the actual list to the sig-release repo.
/cc @swinslow @dims @justaugustus 
members involved in the sig-release licensing subproject
/cc @thockin @cblecker @sttts 
dep-approvers
/hold
want to make sure this is explicitly lgtm'ed by @swinslow 
/sig release
/area licensing

godep: point to list of whitelisted licenses

---

community-membership.md
github-management/new-membership-procedure.md

An approver/reviewer in @kubernetes, may sponsor someone for the @kubernetes org or any of the related organizations (@kubernetes-sigs, @kubernetes-csi etc); as long as it's a project they're involved with.
However, this does not work the other way around. A sponsor that is only an approver/reviewer in @kubernetes-sigs cannot sponsor someone for membership in the @kubernetes org. They are scoped just to the org they're associated with.
Hopefully this reduces some of the back and forth (example https://github.com/kubernetes/org/issues/470#issuecomment-462763752) for @mrbobbytables and @justaugustus. :smile:  
/cc @cblecker @mrbobbytables @spiffxp @justaugustus  

github-management: clarify sponsorship criteria

---

sig-api-machinery/charter.md

Allow the project to scale by delegating kubernetes-sigs repo creation approval to specific sub-project owners.

Add sig-apimachinery delegates for subproject repo creation approval

---

contributors/devel/sig-scheduling/scheduler_benchmarking.md

Add a developer document on running scheduler benchmarks

---

contributors/devel/development.md

Ref. #3064 
Link in development.md file has been updated. The original section was moved to the integration-tests.md file in folder /devel/sig-testing.
/kind cleanup
/area developer-guide
cc @parispittman 
/assign @cblecker @nikhita

Install etcd dependency link updated

---

sig-storage/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/486
I also went ahead and removed `csi-driver-cinder` as a repo in the subproject because that repo was deleted. Ref: https://github.com/kubernetes/org/issues/317.
/assign @kfox1111 @msau42 @saad-ali

Add csi-driver-image-populator to kubernetes-csi subproject

---

generator/wg_readme.tmpl
wg-component-standard/README.md

Follow up of https://github.com/kubernetes/community/pull/2606 and https://github.com/kubernetes/community/pull/2500
For https://github.com/kubernetes/community/issues/2324
/cc @cblecker @spiffxp 

generator: remove google groups note from all WG READMEs

---

contributors/devel/sig-architecture/conformance-tests.md

Use the "new" `--ginkgo-parallel ` instead of the deprecated env var:
```bash
2019/02/20 14:09:10 main.go:980: Please use kubetest --ginkgo-parallel (instead of deprecated GINKGO_PARALLEL=y)
```
Tested with the latest kubetest version.

Update conformance docs to use --ginkgo-parallel 

---

sig-docs/charter.md

This PR adds a charter for SIG Docs as specified by https://github.com/kubernetes/steering/issues/31.
Because this PR involves creation of a SIG charter, all SIG Docs co-chairs must actively review and approve this PR.
/sig docs
/assign @bgrant0607 
/cc @jaredbhatti @Bradamant3

Create SIG Docs charter

---

github-management/opening-a-request.md
github-management/org-owners-guide.md

Ref: https://github.com/kubernetes/community/issues/3280#issuecomment-466446811
Currently, the access levels of our project boards are inconsistent. This PR documents guidelines for project boards so that we can have it consistent going forward.
/cc @cblecker @spiffxp 
/cc @justaugustus @jdumars @idvoretskyi 
/sig pm

github-management: add project board guidance

---

.github/ISSUE_TEMPLATE/moderator_application.md

This adds a moderator template so that moderators can apply via the community repo.

Add a moderator template

---

.github/ISSUE_TEMPLATE/moderator_application.md

/assign @castrojo @cblecker 
We are getting many issues for moderator request -- let's automatically apply the SIG label for those.

Automatically add contribex label to moderation issue template

---

.github/ISSUE_TEMPLATE/moderator_application.md

This reverts commit acaa9b8bedfb5d3603a7dbd505eca00e2a836a9b, reversing changes made to 95c22eab926f81e2e9865e567497076ce8d3cb58 (reverts https://github.com/kubernetes/community/pull/3314)
GitHub doesn't allow multiple labels in issue templates and if a comma separated list is used, GitHub refuses to recognize it as a issue template in the first place. :neutral_face: 

Revert automatically adding contribex label to moderation issue template

---

communication/moderators.md

Add @Katharine (closes #3316), @mrbobbytables (closes #3310), and @jeefy (closes #3321) to the Slack moderators list.
Also increases the number of bullet points to 9 to match the number listed, assuming I can count correctly.

Add new Slack mods to the list

---

sig-api-machinery/README.md
sigs.yaml

Trival updates, fixing links in readme
The repo has been renamed to [apiserver-builder-alpha](https://github.com/kubernetes-incubator/apiserver-builder-alpha), updating the link in SIG-api-machinery doc.

Sync server-sdk apiserver-builder repo name

---

wg-k8s-infra/charter.md

According to: https://github.com/kubernetes/k8s.io/issues/166
Signed-off-by: Bart Smykla <bsmykla@vmware.com>

Fixed url of wg's google group in community/wg-k8s-infra/charter.md

---

events/2019/05-contributor-summit/README.md

Update the Contributor Summit EU docs with initial information such as time and date, roles and leads, and some basic venue information.
Signed-off-by: Jonas Rosland <jrosland@vmware.com>

Update the Contributor Summit EU docs with initial information

---

generator/README.md
generator/app.go
generator/list.tmpl
generator/ug_readme.tmpl
hack/verify-generated-docs.sh

Fixes https://github.com/kubernetes/community/issues/3297
User Groups were added in #3174. This PR adds support for documenting them in sigs.yaml. Ref: https://github.com/kubernetes/community/pull/2988#issuecomment-465792969.
/cc @cblecker @parispittman 
/cc @spiffxp 

Add support for User Groups in sigs.yaml

---

OWNERS_ALIASES
committee-product-security/OWNERS
committee-product-security/README.md
committee-steering/governance/sig-governance.md
contributors/guide/bug-bounty.md
sig-auth/archive/meeting-notes-2018.md
sig-auth/charter.md
sig-service-catalog/charter.md
wg-k8s-infra/charter.md
wg-lts/charter.md

Commit 1 documents the formation of the new Product Security Committee (see https://github.com/kubernetes/steering/issues/89)
Commit 2 updates all references to the old PST to the new PSC

Create Product Security Committee, update references from PST to PSC

---

README.md
governance.md

User Groups were added in #3174. The README has a tldr of community groups - so this PR documents User Groups in the README.
The TLDR is adapted from https://github.com/kubernetes/community/blob/master/governance.md#user-groups.
/cc @kubernetes/steering-committee

Add User Groups to README

---

SECURITY_CONTACTS
committee-steering/governance/sig-governance.md
github-management/README.md
sig-service-catalog/charter.md

Related kubernetes/security#2, https://github.com/kubernetes/kubernetes-template-project/pull/27
The link to the Embargo Policy 404s for all `SECURITY_CONTACTS` files in all repos, but I want to be sure to update in this repo since it has lots of process-related docs for roles which require acceptance of the embargo policy (github-management for example).
/cc @philips @joelsmith @liggitt

Fix link to Embargo Policy

---

sig-release/README.md
sigs.yaml

... to the sig-release/release-engineering subproject
ref https://github.com/kubernetes/org/issues/551

Add kubernetes-sigs/k8s-container-image-promoter repo

---

sig-azure/README.md
sigs.yaml

Adding the azuredisk and azurefile CSI drivers OWNERS now that the repos have been migrated in.
Closes: kubernetes/org#344
/assign @nikhita @dstrebel @khenidak @feiskyer @andyzhangx

sig-azure: Add CSI driver subproject OWNERS

---

contributors/design-proposals/api-machinery/csi-new-client-library-procedure.md

As far as I can tell this qualification is poorly understood, and actually not a great goal anyway, since the generated examples (e.g. https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/AppsV1Api.md#deleteCollectionNamespacedDaemonSet) aren't really that useful anyway.
There's separate requirements about docs for the `stable` status below, and this is confusing various people
(e.g. https://github.com/kubernetes-client/javascript/pull/182)
Thus, I think it makes sense to delete this requirement.
cc @lavalamp @mbohlool

Remove generated examples, its unclear what it means.

---

contributors/devel/README.md

I visited [contributors/devel/README.md](https://github.com/kubernetes/community/blob/d91a9912d5712fb82293da49f9a0a53a8b4134fb/contributors/devel/README.md) from [kubernetes/kubernetes]( https://github.com/kubernetes/kubernetes/blame/eaa78b88ac25a61bfb1aa81d118c5ffeda041b64/README.md#L58).
I find some broken links.
Fix links.
I got URLs from PRs below.
- Document Conventions
- PR: Deleting outdated stub file #3137
- https://github.com/kubernetes/community/pull/3137/files#diff-145ff4e94d6e25958957f2fb0568af8fL5
- API Client Libraries
- PR: Deleting stub files in /devel and updating links - Umbrella issue 3064 #3086
- https://github.com/kubernetes/community/pull/3086/files#diff-2b7114a5eb334757eb23135e4a9c5563L3

Fix link in README.md

---

communication/moderation.md

Someone added a spam emoji during the last attack, we should check these after incidents until we have automation in place.

Add emoji audit as part of slack moderation

---

contributors/design-proposals/architecture/scope.md

Added document explaining the scope of the Kubernetes project, including
historical rationales and decision criteria.
cc @thockin @smarterclayton @kubernetes/sig-architecture-pr-reviews

Scope of Kubernetes

---

communication/zoom-guidelines.md
generator/list.tmpl
sig-list.md

Follow up of the TODOs in https://github.com/kubernetes/community/pull/3287
TODO:
- There are no such dependencies. 

Fix links to sig creation/lifecycle doc

---

.github/ISSUE_TEMPLATE/moderator_application.md

Moderators for Kubernetes communication properties should enable 2FA for any property they are going to moderate.
/cc @jeefy @castrojo

Add 2fa requirement to moderator request template.

---

communication/README.md
contributors/guide/README.md

- as a follow-up to #3428, fix communication link in contributor guide as well
- drop unused links to non-existant communication page

Fix links to communication page.

---

.github/ISSUE_TEMPLATE/slack-request.md
communication/slack-guidelines.md

This restructures the slack guidelines and adds an issue template for Slack requests. 
The goal is to move channel and bot/token/webhook requests to github where they may be discussed in a more async manor and get more eyes on the subject.
/cc @castrojo @parispittman @jeefy @coderanger @Katharine @jdumars

Update Slack communication guidelines

---

sig-cluster-lifecycle/README.md
sigs.yaml

As requested in https://github.com/kubernetes/org/issues/308
/cc @cblecker 
/cc @nikhita

Add etcdadm subproject to sig-cluster-lifecycle

---

contributors/guide/style-guide.md

Per several conversations (example: https://github.com/kubernetes/community/pull/3336#discussion_r261752054), title-style headings are preferred over sentence-style. This updates the guidelines to reflect that preference.
...also trims some unneeded whitespace.

Update heading guidelines in style guide.

---

contributors/devel/sig-release/release.md

A bit late for this, but hey...
ref: https://github.com/kubernetes/sig-release/issues/456

priority/critical-urgent isn't needed during code freeze

---

contributors/guide/README.md

Somehow I missed this one in #3311
See https://github.com/kubernetes/security/pull/1 for background info

Update security release page URL now that security docs have been moved

---

communication/moderators.md

The "Communications manager" role is tied to google+ (which is being [shutdown for most users](https://support.google.com/plus/answer/9217723?hl=en)) and has limited functionality within youtube itself. All of its abilities that do come with the role, do not align with how we use youtube. With that, figure it should be removed.
/cc @castrojo @parispittman

Remove youtube "Communications managers" from moderator roles.

---

generator/app.go
generator/sig_readme.tmpl
sig-architecture/README.md
sig-testing/README.md
sigs.yaml

Demonstrate by adding slack channels for sig-testing subprojects
that already have their own slack channels
Add a GitHub team related to conformance to sig-arch's conformance
definition subproject
GitHub teams as implemented now are very kubernetes-org centric,
I'm not trying to change that here, would suggest a followup
change to allow for the use of github teams in other orgs
(like kubernetes-sigs)
/hold
I would rather let some other generator-related PR's get in first,
I suspect there are merge conflicts and I'd rather take the hit

Add contact (slack, mailing_list, teams) to subprojects

---

committee-product-security/README.md
committee-steering/README.md
generator/committee_readme.tmpl
sig-architecture/README.md
sigs.yaml

Not sure if we officially say that committees can have subprojects, but I noticed steering as a subproject for sig-arch after creating https://github.com/kubernetes/community/pull/3437: https://github.com/kubernetes/community/tree/master/sig-architecture#subprojects.
Technically, committees also own repos (and thus "code") so I guess it makes sense to list these as subprojects?
/hold
/committee product-security
/cc @kubernetes/steering-committee @kubernetes/product-security-committee @mattfarina @jdumars 
/assign @spiffxp 
(generator owner)

Add subprojects for committees

---

sig-auth/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/528
/cc @liggitt @tallclair @mikedanese @easeway @davidopp

Add multi-tenancy subproject to sig-auth

---

CLA.md

fixes #3502 
The CLA support contact information has changed, this updates the CLA doc with the relevant information.
/cc @idvoretskyi @parispittman

Update CLA support contact information.

---

sig-cloud-provider/CHARTER.md

As discussed in today's SIG Cloud Provider meeting, here's an update to the SIG Cloud Provider charter. 
Motivations:
* To be in line with the charter template set by the steering committee
* Added specific call outs for subprojects in our SIG (pending SIG folding discussions)
* Guide for prioritizing work as we start planning/grooming for v1.15
Timeboxing this to March 20th 2019

Updates to SIG Cloud Provider Charter

---

sig-node/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/642
/assign @dims @derekwaynecarr

Add cri-api as a subproject to sig-node

---

governance.md

Just point the SIG Governance link to the right document (looks like it got moved).

Fix SIG Governance link

---

contributors/devel/sig-architecture/api-conventions.md

As I was reading through api-conventions.md, I noticed a couple of
broken links. This commit updates those links to resolve to their
previously linked content.

Update links in api conventions document

---

committee-steering/governance/sig-governance.md

The link to the `communication` document was there but missing the URL. Just added the desired URL.
Fixes #3530

Fix a link to "communication" document

---

contributors/guide/github-workflow.md

Added `export` to the examples for setting `working_dir` and `user` for clarity.

added export to user and working dir examples

---

contributors/devel/sig-release/cherry-picks.md

We're adding a GitHub team for the patch managers and have a group mail
alias to make it easier contacting the folks who shepherd cherry picks
across the arc of time.

devel guide: update patch release team contact for cherry picks

---

sig-docs/README.md
sigs.yaml

This pull requests adds the sig-docs-es team to the community repo. This team is working on the spanish localization and was added in https://github.com/kubernetes/org/pull/685.
```
❯ make WHAT=sig-docs generate | grep -v Skipping
go run ./generator/app.go
Generating sig-docs/README.md
Generating sig-list.md
Generating OWNERS_ALIASES
Finished generation!
```

Add sig-docs-es team

---

sig-api-machinery/README.md
sigs.yaml

Now that repo https://github.com/kubernetes-sigs/legacyflag is created per https://github.com/kubernetes/org/issues/683 and KEP https://github.com/kubernetes/enhancements/pull/764, add OWNERS link to the component-base subproject in sigs.yaml.
/cc @nikhita @luxas @sttts

Add legacyflag OWNERS to component-base subproject

---

generator/list.tmpl
sig-list.md

There is space for another column and it'd be nice to be consistent with other groups.
Note: we don't display label for WGs, but the columns look pretty dense already so I haven't added for it. 
xref https://github.com/kubernetes/test-infra/pull/12131
/cc @cblecker @spiffxp

Display label for user groups in the SIG list

---

github-management/kubernetes-repositories.md

Ref: https://groups.google.com/d/topic/kubernetes-sig-architecture/TjHLgJcDF-I/discussion
Ref: #3427 
/cc @dims @justaugustus @nikhita 
licensing subproject members
/assign @nikhita
/hold
This is a replacement for #3427, modifying the language and adding some details about copyright transfers and copyright notices.
Agree with comment at https://github.com/kubernetes/community/pull/3427#issuecomment-475847195 that sig-release might be a better place to aggregate more information about copyright notices, etc. over the longer term. I'm thinking that the added details here will be useful for now as we build out the more detailed guidance.

Add details about copyright notices and donated repos

---

contributors/devel/development.md

Signed-off-by: Jorge Alarcon Ochoa <alarcj137@gmail.com>

Updated developer documentation - upgrading Go

---

contributors/devel/sig-architecture/conformance-tests.md

This is high-level guidance of how to identify conformance cases that should apply to both Linux and Windows, which ones are Linux only, and common issues to watch out for that would affect cross-OS compatibility,
This would resolve https://github.com/kubernetes/kubernetes/issues/75741
/sig windows
/assign bclau
@bclau can you review first since you've done most of the PRs to tag the Linux only tests?

Start Windows considerations list for conformance tests

---

contributors/devel/sig-architecture/conformance-tests.md

* Adds the criteria to have an e2e test running for one release before
promotion.
* Adds a section on the review board describing the types of PRs that
require approval through that process.
* Updates the link to the review board.

Add detail on the conformance review process

---

.github/ISSUE_TEMPLATE/slack-request.md
communication/slack-config/OWNERS

Adds area/slack-management label to parts of the repo that deal with it, so requests can be tagged as such.

Add slack-management label

---

contributors/guide/owners.md

Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
fix #3591

fix repoowners misspelling

---

communication/moderators.md
communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml
communication/youtube-guidelines.md
communication/zoom-guidelines.md

Fixes #3577 -- instead of a combined channel, this creates two slack user groups (`@youtube-admins` and `@zoom-admins`) and updates documentation to use said user groups.
Along the way I found some inconsistencies in the `moderators.md` file that I updated.

Create YouTube and Zoom admin slack user groups

---

communication/slack-config/users.yaml

Per conversation yesterday -- slack user mappings should be alphabetically sorted for long term maintainability.
/cc @jeefy @Katharine

Update slack users.yaml to be alphabetically sorted.

---

committee-steering/governance/sig-governance.md
committee-steering/governance/wg-governance.md
governance.md
sig-wg-lifecycle.md

If sig leaders are not community members, this prevents us from putting them in OWNERS files, assigning issues/PRs to them, and other common community administration tasks. Requiring folks to go through this process also ensures that leaders are established members of the community and have had their work reviewed/sponsored by others.
/hold

Add community membership requirement

---

communication/slack-config/channels.yaml
communication/slack-config/restrictions.yaml
communication/slack-config/sig-docs/OWNERS
communication/slack-config/sig-docs/docs-channels.yaml

Delegate the ability to manipulate the locale-specific #kubernetes-docs-* channels to sig-docs-leads.

Slack: delegate #kubernetes-docs-* to sig-docs-leads

---

github-management/kubernetes-repositories.md

To document cases where we might want to **delete** empty repos. Empty repos = repos which have only the initial commits adding template files and no other activity.
Example - https://github.com/kubernetes-csi/csi-lib-common
Ref: https://github.com/kubernetes/org/issues/718
Note to the reviewer: we have previously deleted repos which satisfied this criteria but this PR documents the case explicitly. 
/assign @cblecker @spiffxp 
github-management owners

Add note about deleting empty repos

---

sig-creation-procedure.md
sig-governance.md

One of them explicitly says to be removed before 1.15, the other
hasn't substantively changed since Aug 30.
ref: https://github.com/kubernetes/community/issues/2857

Remove tombstones related to sig lifecycle

---

.github/ISSUE_TEMPLATE/slack-request.md
communication/slack-guidelines.md

Users can now issue a PR directly against the slack config to add channels and user groups with the slack admins there as approvers. Encouraging users to PR means Slack Admins don't have to watch the community repo for incoming requests as they'll be assigned through conventional means.
Updated with a note on the contextual menu for admins used for inactivating users and removing content.
/cc @Katharine @jeefy @parispittman @castrojo @nikhita

Update slack guidelines for tempelis and new moderation functionality

---

communication/slack-config/channels.yaml

For discussion of the slack-infra work (which currently mostly happens in a private channel, which is not ideal).

Add #slack-infra channel

---

sig-vmware/README.md
sigs.yaml

Docs regenerated
During the 2019/04/04 [meeting for SIG-VMware](https://docs.google.com/document/d/1RV0nVtlPoAtM0DQwNYxYCC9lHfiHpTNatyv4bek6XtA/edit#heading=h.7ux7o2icdb49) it was agreed to adopt CSI vSphere as a subproject of the SIG. This update to sigs.yaml adds that subproject to the list.
A PR to `kubernetes/org` for creation of the repo `kubernetes-sigs/vsphere-csi-driver` is pending, and will be xref'd here once opened.
/assign @frapposelli @cantbewong 
^ SIG-VMware chairs

Add csi-vsphere subproject to SIG VMware

---

contributors/devel/development.md
contributors/devel/sig-architecture/godep.md
contributors/devel/sig-architecture/vendor.md
contributors/devel/sig-testing/testing.md
contributors/guide/coding-conventions.md

Initial content for the new vendor management scripts.

Update vendor docs for go modules

---

sig-autoscaling/README.md

This commit add guidelines on what we expect from presentation and demos
at SIG Autoscaling meetings.  This should help set expectations for
future demos, and avoid any misunderstandings about what kinds of
content are acceptable.

[SIG Autoscaling] add guidelines on presentations

---

committee-code-of-conduct/README.md

August 7th, 2018 was the date that we had all of the confirmations from
the members of the inaugural members of the CoCC and the welcome email
was sent.

add term info to CoCC

---

github-management/kubernetes-repositories.md

This PR documents _suggestions_  for creating new repos (for members of the GitHub admin team).
Ref: https://github.com/kubernetes/org/issues/418#issuecomment-465345564
cc @kubernetes/owners 
/assign @cblecker @spiffxp

github-management: add suggestions for creating new repos

---

sig-storage/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/718
`kubernetes-csi-migration-library` was archived, but surprisingly it was never added to sigs.yaml (?!)
/cc @saad-ali 

Remove the deleted csi-lib-common repo

---

github-management/opening-a-request.md
github-management/org-owners-guide.md

Fixes https://github.com/kubernetes/community/issues/3102
and address the docs part of https://github.com/kubernetes/org/issues/563
/cc @spiffxp @justaugustus @mrbobbytables @idealhack @rlenferink 

github-management: document team structure and process

---

contributors/guide/contributor-cheatsheet/README.md

See https://github.com/kubernetes/community/issues/3502

LF HelpDesk email is not effective anymore

---

events/2019/05-contributor-summit/README.md
events/2019/05-contributor-summit/sig-f2f-guidelines.md

Added a new SIG F2F guidelines page to move this out of gdocs and into something more permanently discoverable. I also linked the README to this new page in the repo.
/cc @jonasrosland

Added SIG F2F Guidelines page

---

contributors/guide/contributor-cheatsheet/README.md

- Expands on links used as references and removes several dead/outdated ones.
- Add section on signing the CLA and troubleshooting.
ref #3629 
/cc @idvoretskyi @nikhita @eduartua

Update Contributor GitHub Cheatsheet

---

sig-docs/README.md
sig-docs/charter.md
sigs.yaml

This PR updates the list of SIG Docs subprojects and team contacts.
This is a newer version of the changes introduced in #3632. 
See:
- https://github.com/kubernetes/community/pull/3632#issuecomment-485999077
- https://github.com/kubernetes/org/issues/753
- https://github.com/kubernetes/org/issues/754
/cc @kbarnard10 @jaredbhatti @Bradamant3

Add K8s blog teams and update charter

---

communication/cncf-servicedesk/OWNERS
communication/cncf-servicedesk/README.md

CNCF service desk. Fixes kubernetes/steering/#102

Add an OWNERs file for people responsible for representing k8s in the

---

communication/slack-guidelines.md

Add a note regarding channel name length to guidelines.
ref: https://github.com/kubernetes/community/pull/3655#issuecomment-487778836
/cc @Katharine

Add Slack channel name length restriction.

---

sig-cloud-provider/CHARTER.md

As discussed during the SIG-Cloud Provider meeting on 4/17/2019.
/cc @jagosan @hogepodge @andrewsykim

Update sig-cloud-provider charter to support orphaned subprojects

---

sig-list.md
sigs.yaml
ug-big-data/README.md

Updating google group and slack to reflect the transition.
Note, the slack channel rename request is still outstanding:
https://github.com/kubernetes/community/issues/3665

Sync google group name and slack for Big Data User Group transition

---

communication/moderators.md

@raelga 
- discuss.k8s.io / Spanish Regional Category
[@rael](https://discuss.kubernetes.io/u/rael/summary)
- @mrbobbytables
- @jeefy 
- Experience moderating discuss and other forum engines such as phpbb or vbulletin.
- Contributor in the sig-docs team, leading the Spanish localization effort.
As discussed in https://discuss.kubernetes.io/t/spanish-regional-discussion-category/6142, we're trying to bootstrap the Spanish category on the Discuss forum.
So far, there is no movement, so it's hard to find a second moderator, but we will be looking into it once the community starts to get some activity.
/cc @mrbobbytables

Add Discuss Spanish Regional Category moderators

---

sig-node/README.md
sigs.yaml

cri-o has migrated to its own GitHub org: https://github.com/cri-o/cri-o
Ref: https://github.com/kubernetes/org/issues/675
/assign @derekwaynecarr @cblecker

sig-node: remove the cri-o subproject

---

contributors/guide/owners.md

Adds _"emeritus"_ to owners. This should be safely ignored by prow, and something we can build future tooling around. The intent is to provide a means for contributors who have potentially shifted roles or may be less active for a period of time to remove themselves from automated assignment, but still have an entry there if another opinion is needed. 
The suggested change is just to mimic the owner spec under the `emeritus` keyword. This would make it easy for people to swap over, but less useful for future tooling. An alternative might be to mimic + do something like this:
```yaml
emeritus:
approvers:
- name: bob
date: 2019-04-22
```
Which would make it easier to build a report or dashboard on.
ref: https://github.com/kubernetes/kubernetes/issues/76269#issuecomment-483069884
ref: …

Add emeritus to owners guidelines

---

communication/slack-config/channels.yaml

I am one of the maintainers of [node-problem-detector](https://github.com/kubernetes/node-problem-detector) project. In order to make the discussion more smoothly with end users,  we suggest we add a `node-problem-detector` slack channel.
/cc @Random-Liu @wangzhen127

add node-problem-detector channel

---

communication/slack-config/channels.yaml

- monolith is inactive today. It was created for discussing migrating monolith apps to Kubernetes. Ref: https://groups.google.com/forum/#!forum/monolithic-apps-to-k8s.
- ops-status was meant for "operations issues that might be relevant to the K8s community".
For upstream Kubernetes ops-specific discussion, we have #testing-ops.
For general ops discussion, we have #sre.
/hold

Archive monolith and ops-status slack channels

---

sig-architecture/README.md
sig-instrumentation/README.md
sigs.yaml

klog was initially under sig-arch, it makes a lot of sense to move this under sig-instrumentation as that sig owns the "logging" for kubernetes.
Change-Id: I0de87dd36a09175a51c24bef4466692825207bbd

Move klog to sig-instrumentation

---

sig-list.md
sigs.yaml
ug-big-data/README.md

This PR is to revert changes I made in #3666; the original placeholder names I used turned out to be the ones preferred by committee.
The sigs.yaml file altered in some way that prevented me from directly reverting the original PR.

revert changes to UG Big Data resource names

---

communication/slack-config/channels.yaml

I am one of the maintainers of [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) project. In order to make the discussion more smoothly with end users, we suggest we add a `kube-state-metrics` slack channel.
/cc @brancz @mxinden

add kube-state-metrics slack channel

---

sig-apps/README.md
sig-cli/README.md
sig-cluster-lifecycle/README.md
sig-contributor-experience/README.md
sig-instrumentation/README.md
sig-network/README.md
sig-node/README.md
sigs.yaml

A script of mine noticed there are a number of slack channels in https://github.com/kubernetes/community/blob/master/communication/slack-config/channels.yaml that happen to match the names of subprojects in sigs.yaml

Add subproject slack channels

---

communication/slack-config/channels.yaml

We are creating a subproject of SIG-Docs for the Kubernetes blog and would like to add a Slack channel for blog-specific discussions.

Requesting Slack channel for Kubernetes blog

---

contributors/design-proposals/storage/csi-migration.md

Update CSI migration design to include resize migration design.
/cc @ddebroy @davidz627 @gnufied

Update CSI migration design for volume resizing

---

contributors/devel/sig-architecture/api-conventions.md

This PR removes two use of `bool` fields in examples. This is a frequently commented-upon thing about the API conventions doc, since the doc contains guidance _not to use bools_ in the API.

Remove inconsistent use of bool as example

---

CLA.md

Fixes #3737 
- Replace “Kubernetes CLA” with “CNCF CLA”
- Write “Cloud Native Computing Foundation **(CNCF)**” to make the abbreviation clear to new readers

Clarify that CLA is CNCF CLA

---

contributors/devel/sig-architecture/api-conventions.md

When going through the api-conventions markdown doc online, I noticed a
couple small grammar and Markdown formatting issues. This patch fixes
those up.

Grammar and Markdown fixes for api-conventions

---

contributors/guide/owners.md

Also remove the no-issue quirk, since we no longer actively
use that (though it still exists as a configurable option)

Link to community membership doc from go.k8s.io/owners

---

github-management/subproject-site-requests.md

- Moves adding a `netlify.toml` at the root of the repo to the beginning
of the process, so that the site can be viewed directly once Netlify is
configured.
- Add a note about "Basic Build Settings" getting autopopulated with values
in `netlify.toml`.
- Remove step about explicitly enabling HTTPS. Netlify enables HTTPS
automatically after DNS records are updated.
- Some markdown improvements.
/assign @mrbobbytables @cblecker

Update instructions for subproject site requests

---

events/OWNERS

adding folks who have been with us for 3+ contributor summits. need to discuss with others, too.

adding more event owners

---

sig-cluster-lifecycle/README.md
sigs.yaml

The old link pointed to the 2017-2018 archived meeting notes document. This updates it to the current 2019 version.

Update Cluster API office hours link for 2019

---

contributors/devel/sig-cli/kubectl-conventions.md

The link to `logs.go` in the last paragraph of `Command implementation conventions` section is pointing to a non-existent document.

Fix wrong link to pkg/kubectl/cmd/logs/logs.go

---

hack/generate-devstats-repo-sql.py

This isn't perfect, but it's probably better living here
than in a random gist I have laying around.
/area devstats
/cc @nikhita
ref: https://github.com/kubernetes/community/issues/3305

Add script used to generate devstats repo groups

---

github-management/kubernetes-repositories.md
github-management/org-owners-guide.md

This PR contains the following changes:
- The first commit moves the repo creation/removal _process_ to org-owners-guide.md because that's only actionable for org admins.
- The second commit updates the repo creation process to use GitHub repo templates. Ref: https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/. 
I'll set https://github.com/kubernetes/kubernetes-template-project as a template repo once this PR gets lgtm.
/cc @cblecker @spiffxp @mrbobbytables

Update repo creation process to use GitHub repo templates

---

github-management/kubernetes-repositories.md

Current state of docs:
- https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md#subproject-creation
mentions that repos _may_ be created under k-sigs by a lazy consensus of subproject owners.
- Some charters like https://github.com/kubernetes/community/blob/master/sig-api-machinery/charter.md#deviations-from-sig-governance
have explicit processes setup for who can approve repo creation requests.
- https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-new-repositories
says that repo creation requests must be approved by lazy consensus of SIG membership.
Current state of how we do things:
- We create repos if the SIG leads have approved the repo creation
request.
- We don't require a lazy …

Update who must approve repo creation requests

---

sig-aws/README.md
sigs.yaml

There was no link from the sig-aws README to the meeting recordings on YouTube, so I added the link to sigs.yaml and generated the readme file to make the videos easier for people to find.

added link to meeting recordings for sig-aws

---

github-management/OWNERS
github-management/README.md

[kubernetes-sig-contribex@
thread](https://groups.google.com/forum/#!topic/kubernetes-sig-contribex/p8Je8FrpQ04)
for the nomination
calebamiles has graciously agreed to step down to make room for
mrbobbytables on the github admin team
/hold
need majority of steering committee to lgtm this change
can you confirm you're interested in this, and accept the security
embargo policy?
This may prompt the question of Bob's role as a New Membership
Coordinator, I would like for Bob to handle that separately once this
nomination has been addressed.
There will be a corresponding kubernetes/org to implement these changes
shortly

Add mrbobbytables to github admins team

---

communication/slack-config/channels.yaml

Hi! I work at [Garden.io](https://garden.io/), we're responsible for the eponymous development tool, [Garden](https://github.com/garden-io/garden). 
We'd like to be more easily accessible to the Kubernetes community, and since Garden is completely OSS, we'd like to have our development channel on Kubernetes Slack as well.

Add #garden and #garden-dev Slack Channels

---

events/2019/05-contributor-summit/README.md
events/2019/05-contributor-summit/communications.md

This PR adds all pre- and post-event email communications sent out to attendees of Contributor Summit Barcelona.

Add all email comms for BCN

---

communication/slack-config/channels.yaml

This is to add a cluster-api-vsphere channel, in preparation to the upcoming folding of SIG-VMware.
/cc: @akutz @andrewsykim

Add cluster-api-vsphere slack channel

---

events/events-team/content-lead.md

This PR adds a description for the New Contributor Content Lead role.
/sig-contributor-experience

New Contributor Content Lead Role fleshed out

---

contributors/devel/sig-scheduling/scheduler_benchmarking.md

- when running benchmark tests, we used to use `-run=xxx` to exclude unit tests; however a more conventional way is to use `-run=^$`, `-run=^$$` here is to escape the $ symbol, otherwise it won't work.
- add info to display benchmark output only
/assign @bsalamat 
/sig scheduling

conventional test args to bypass UTs

---

communication/slack-config/restrictions.yaml
communication/slack-config/sig-release/config.yaml

Supercedes: #3828 
Ref: #3827 
/sig release
/assign @Katharine @jdumars

slack: Rename release-managers channel to release-management

---

sig-cluster-lifecycle/README.md
sigs.yaml

ref https://github.com/kubernetes/org/issues/937
/cc @chuckha

sig-cluster-lifecycle: add cluster-api-bootstrap-provider-kubeadm subproject

---

communication/slack-config/channels.yaml

cluster-api-provider-docker can be found here: https://github.com/kubernetes-sigs/cluster-api-provider-docker.
This is part of the Cluster-API sub project which is a sub project of SIG Cluster Lifecycle.
Happy to answer any more questions, I am @ cha on the k8s slack!
Signed-off-by: Chuck Ha <chuckh@vmware.com>

Request new channel for CAPD

---

communication/slack-config/channels.yaml

Reverts kubernetes/community#3770. Apparently the name `aks` is irrevocably(?) taken by a user, so we fail every time we try to create the channel.
We may want to recreate this with a different name.

Revert "Create AKS channel"

---

events/events-team/best-practices.md
events/events-team/marketing/README.md

This adds more info around the marketing lead responsibilities, and a bit of cleanup to the best practices docs for running a Contributor Summit.
/area na-summit

Add more Contributor Summit marketing lead info and cleanup of best practices

---

github-management/org-owners-guide.md

Using the current instructions, we can only create repos using the
template repo if the template repo is in the same org as the new repo.
If template repo is _not_ in the same org, we can still use it by visiting
the template repo page and clicking on "Use this template".
/assign @mrbobbytables @cblecker

github: update instructions for creating repos from template repo

---

sig-apps/README.md
sigs.yaml

Instead of linking to a specific video in the playlist, it should link to the playlist.

Fix the link to SIG Apps meeting playlist

---

contributors/devel/README.md

The API conventions link from https://github.com/kubernetes/community/blob/master/contributors/devel/README.md was broken (page was moved to the sig-architecture directory)

Fix broken development README link to api-conventions doc

---

communication/best-practices.md

I would like to have your feedback and inputs for the Mailing list and Github notifications best practice. 
I am thinking that the two parts need to be in the same page for more simplicity.
Once, there is agreement about this file, I will add the links to the top level README and then also to the communication section of the contributor guide.
Fixes #1724

Best practice for mailing list and github notification

---

mentoring/OWNERS

This is essentially a no-op as `sig-contributor-experience-leads` already have approval access, but adding it explicitly for subproject ownership.

mentoring: add nikhita as approver

---

contributors/devel/sig-architecture/conformance-tests.md

doc: add an extra space between document and for

---

events/events-team/content-lead.md

Added a link from the Content Handbook, which mentioned the SIG Meet and Greet, to the new page describing how it is organized.

Added link to SIG contributor event doc

---

contributors/guide/README.md

New contributor can assign issue by themself now. 
The feature is provided by GitHub, more details please refer to [Change log](https://github.blog/changelog/2019-06-25-assign-issues-to-issue-commenters/).

Update contributor guide about assign feature

---

sig-contributor-experience/triage-team/triage.md

These guidelines and responsibilities are focused on  issues and PRs
that are identified for sig contributor experience. Keeping it as short
as possible for easier usage. It's also  utilizing and poiting to other
existing materials on triage.
Add the triage team members and specific role descriptions in a separate
document.
Related #3364

Create issue and PR management guildlines for the sig contribex

---

committee-code-of-conduct/README.md
committee-code-of-conduct/charter.md
sigs.yaml

This is a proposed charter for the Code of Conduct Committee for review by the Steering Committee.

Add Code of Conduct Committee Charter

---

sig-apps/CONTRIBUTING.md

- Removed Helm as it has been its own project for some time
- Removed the App Def WG as it is now complete and archived
- Added the Application CRD/controller
- Added a call for docs contributions
/cc @prydonius @janetkuo @kow3ns

Updating the SIG Apps contributing docs

---

communication/slack-config/channels.yaml

Create #sig-usability Slack channel, as a followup to the SIG being approved.
https://github.com/kubernetes/community/pull/3801

Add sig-usability Slack channel

---

governance.md

The /committee-steering/governance/sig-governance-template-short.md is not available anymore.

Removes a dead link to the sig-short-template

---

sig-architecture/api-review-process.md

This change updates the API review process to be more explicit about scope.  
Current text was too broad and outside the scope of sig-arch.  
I'm not sold on the naming listed so any recommendations are solicited. 
/assign @liggitt 
/cc @ncdc @justinsb @BenTheElder @jbeda 
Fixes #3864

Update API review document to be more explicit

---

generator/ug_readme.tmpl
generator/wg_readme.tmpl
wg-multitenancy/README.md

See https://github.com/kubernetes/community/pull/3923 where an emeritus lead was added to a WG, but the README was not updated.
/cc @cblecker @spiffxp 

generator: add emeritus leads to WG and UG template

---

contributors/guide/contributor-cheatsheet/README.md
github-management/opening-a-request.md

The mailing list has been already setup.
/cc @kubernetes/owners 
/assign @cblecker @spiffxp

Document private mailing list for GitHub Admin team

---

events/community-meeting.md

As per the last contribex meeting, this is to encourage SIGs that it's ok to give a short/brief status. 

Update SIG Update recommendations for the community meeting

---

OWNERS_ALIASES
contributors/design-proposals/aws/OWNERS
contributors/design-proposals/gcp/OWNERS
sig-aws/OWNERS
sig-aws/README.md
sig-azure/OWNERS
sig-azure/README.md
sig-gcp/OWNERS
sig-gcp/README.md
sig-ibmcloud/OWNERS
sig-ibmcloud/README.md
sig-openstack/OWNERS
sig-openstack/README.md
sig-vmware/OWNERS
sig-vmware/README.md

Adds custom content OWNERS for former cloud provider SIG Chairs/TLs
There may have been a more elegant way to do this, but here's what I did:
```shell
for provider in "aws" "azure" "gcp" "ibmcloud" "openstack" "vmware"; do 
for i in $(grep --exclude-dir=.git -lR sig-${provider}-leads .); do
sed -i "s/sig-${provider}-leads/provider-${provider}/g" "$i";
done
done
```
/assign @andrewsykim @nikhita 
Ref: #3895, https://github.com/kubernetes/org/pull/1050, https://github.com/kubernetes/org/issues/1051

sig-cloud-provider: s/sig-<provider>-leads/provider-<provider> in OWNERS

---

sig-cluster-lifecycle/README.md
sigs.yaml

The project kubeadm-dind-cluster has been retired. For more information see issue https://github.com/kubernetes/org/issues/1016.
/cc @timothysc @ivan4th

Remove kubeadm-dind-cluster sig-cluster-lifecycle subproject.

---

committee-code-of-conduct/README.md

The bootstrapping document stated that the top 3 voted would get 2-year
terms and the bottom 2 would get 1-year terms.
See the bootstrap document: https://github.com/kubernetes/community/blob/3db34d4f6aa092cbbf55c13eaf099cc34d6b1f15/committee-code-of-conduct/bootstrapping-process.md
However when announced 2 people were stated for 2 year terms and 3 were
stated for 1 year terms. This fixes the announced result to comply with
the rules as written.

CoCC: Fix the length of Carolyn's term

---

contributors/devel/sig-architecture/api-conventions.md

Document that the version portion of an apiVersion should be a DNS_LABEL.
This is required for CRDs, as encoded here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L176-L178
It seems like an eminently reasonable convention to have for built-in and aggregated APIs too.

Document version string pattern

---

OWNERS

@nikhita has a substantial number of PR reviews for this repo: https://github.com/kubernetes/community/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3Anikhita+
I also trimmed out root reviewers, see commits for details

Add nikhita as root approver

---

communication/slack-config/channels.yaml

kube-oidc-proxy is a reverse proxy to authenticate to managed Kubernetes API servers via OIDC. The project can be found here https://github.com/jetstack/kube-oidc-proxy
I'm also @JoshVanL on k8s.slack, happy to answer any questions :)
Signed-off-by: JoshVanL <vleeuwenjoshua@gmail.com>

Add kube-oidc-proxy slack channel

---

communication/slack-config/channels.yaml

`okteto` is a tool to develop directly in your dev Kubernetes cluster. No commit, build or push required. The channel will be used to share experiences between okteto users.
https://github.com/okteto/okteto
I'm @pablo on k8s.slack, happy to answer any questions :)

Add okteto channel

---

sig-release/README.md
sigs.yaml

As discussed in the Aug 5 Release Engineering meeting: https://docs.google.com/document/d/16GqCjnEh86w8yADcrUylNoE1y1sqjIMYNC_gdk5WPSQ/edit#heading=h.v4ysdzxj9fan
/assign @sttts @dims 
other publishing-bot owners
/assign @justaugustus @tpepper @calebamiles 
sig release leads
/hold
for lgtm by sig-release leads

sig-release: move publishing-bot to release-eng subproject

---

communication/slack-config/channels.yaml

Octant is a tool for developers to understand how applications run on a Kubernetes cluster. It aims to be part of the developer's toolkit for gaining insight and approaching complexity found in Kubernetes. Octant offers a combination of introspective tooling, cluster navigation, and object management along with a plugin system to further extend its capabilities.
We would like to have a channel dedicated to the project in the K8s Slack, to share experiences and grow the community.
The project can be found here: https://github.com/vmware/octant

Add Slack channel for Octant

---

contributors/guide/pull-requests.md

Looks like this link was broken when KEPs moved to their own repo.

Fix broken link from PR guide to KEP process guide

---

contributors/devel/sig-node/cri-container-stats.md

Update the cri-container-stats documentation with more recent status
info. Particularly, clarify that the option to consume CRI stats has
been implemented, and link to the code that determines the consumption
option.

Update cri-container-stats documentation

---

contributors/devel/sig-testing/bazel.md

This PR adds instructions to configure Bazel with Python 2. I removed the explicit reference to https://github.com/bazelbuild/rules_docker/issues/454 because now that it has been fixed, `make_deb.py` is broken (https://github.com/bazelbuild/bazel/issues/8443) and Python 3 still doesn't work.
I also turned all links in the paragraph into references, which makes the source a little more readable.

Add instructions to configure Bazel for Python 2

---

communication/slack-config/channels.yaml

ref: https://github.com/kubernetes/kubeadm/issues/1622
We've started a kubeadm meeting in a Chinese friendly time. A new slack channel is preferred for communication.

add new slack channel for kubeadm china

---

sig-contributor-experience/devstats/OWNERS

Specifically
- remove redundant reviewers
- move @spiffxp to emeritus_approvers
I haven't really been involved with the day to day of devstats for some
time now. I am periodically interested in ensuring it has accurate and
useful data, but feel that I have taken it about as far as I care to
via https://github.com/kubernetes/community/issues/3305

Update devstats OWNERS

---

OWNERS

Specifically
- add @grodigues3 as an emeritus_approver
- add @mrbobbytables as an approver
out of 145 most recently updated merged PRs in 'kubernetes/community'
involving 'mrbobbytables'... 73 touched files matching regex '.*' and no
files matching '^communication|^github-management' of those, mrbobbytables
authored 19, and commented '/lgtm' on 32
though not formally listed as a reviewer for 3 months, mrbobbytables has
been playing the part for PRs that are outside of the subprojects they own,
which is good enough for me

Update root OWNERS

---

sig-contributor-experience/README.md
sig-testing/README.md
sigs.yaml

repo-infra is mostly used for kazel, which relates to bazel, which
is under sig-testing's purview
/cc @fejta
subproject owner, sig-testing chair
/cc @cblecker @nikhita @parispittman @Phillels
sig-contribex chairs and TLs

move repo-infra subproject to sig-testing

---

contributors/devel/sig-architecture/conformance-tests.md

We have some conformance tests that do this today via the apiserver's node proxy endpoint, please see https://github.com/kubernetes/kubernetes/issues/81052
I'm not entirely sold that we want to disallow access via node proxy, but that's the strawman I'm putting forward for discussion.
/cc @bgrant0607 @smarterclayton @liggitt @timothysc @jbelamaric
/hold
for discussion
/area conformance

Kubelet API access should not be allowed for conformance tests

---

contributors/devel/sig-architecture/conformance-tests.md

New tests don't need to be run for a full release-cycle before getting
promoted to Conformance. Two weeks should be sufficient, and more practical.

Conformance Tests: Reduce soak time for new tests

---

events/elections/2019/README.md
events/elections/README.md

The links still worked, but took you to the top of the page instead of the header they were intending to reference.

Fix several election anchor links.

---

communication/slack-config/channels.yaml

For preparation for setting up Outreachy for Kubernetes.
We plan to toggle the channel name as and when we change programs.
Rationale behind using the same channel for both programs:
since both programs involve similar process/discussions/conversations,
the channel history is usually useful and has related context.
/hold
for lgtm by @parispittman

slack-config: rename #gsoc-apps to #outreachy-apps

---

contributors/devel/sig-architecture/conformance-tests.md

Add conformance requirement for test names in `framework.ConformanceIt` statements to be a literal string.
[`walk.go`](https://github.com/kubernetes/kubernetes/blob/39724859b524e345881eb8ef458f0d5a2f25bd9a/test/conformance/walk.go#L222) fails when a statement contains a non-literal string.

Add literal string requirement

---

contributors/devel/sig-testing/testing.md

When I ran the command,
```sh
make test KUBE_TIMEOUT="-timeout 300s"
```
I got the following error message:
```
can't load package: package k8s.io/kubernetes: no Go files in /home/noguchi/kubernetes/_output/local/go/src/k8s.io/kubernetes
make: *** [test] Error 1
Makefile:185: recipe for target 'test' failed
```
This patch fixes the command above.
ref.
https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test.sh#L72
```sh
KUBE_TIMEOUT=${KUBE_TIMEOUT:--timeout=120s}
```

Fix the command with KUBE_TIMEOUT

---

sig-usability/README.md
sigs.yaml

SIG Usability README has a link to an empty meeting notes google doc. Updated the link with our first meeting notes document.

Updated link to meeting notes

---

communication/slack-config/sig-release/config.yaml

This channel is for CI signal specific conversations.Hoping to help make information easier to find and to provide and to help contributors jump in.
/cc @alenkacz @Verolop @jimangel @soggiest @justaugustus @jberkus
/area release-team
/sig release

Add #release-ci-signal Slack channel

---

communication/slack-config/sig-release/config.yaml

To follow up from the discussion in [Slack:](
https://kubernetes.slack.com/archives/C1TU9EB9S/p1567608031060200)
I am proposing a new channel for release notes team discussion.

Add channel for release notes team discussion, transparency and continuity

---

communication/slack-config/channels.yaml

There is an `aus-nz-users` channel already, this would be nice for contributors in those regions as well.
We discussed this at last APAC coordinator meeting, this PR is to raise it to border audiences.
/cc @alisondy @DylanGraham

slack: add aus-nz-dev channel

---

communication/slack-config/channels.yaml
communication/slack-config/restrictions.yaml
communication/slack-config/sig-storage/OWNERS
communication/slack-config/sig-storage/config.yaml

This delegates the `sig-storage` channel and those prefixed with `csi` to the sig-storage-leads.
Channels `wg-csi` and `wg-csi-migration` are renamed to `csi` and `csi-migration` to better conform with slack channel name schema.
/cc @saad-ali @childsb
/hold

Delegate storage related slack channels to sig-storage.

---

sig-architecture/api-review-process.md

/cc @smarterclayton
xref https://github.com/kubernetes/community/pull/3261#pullrequestreview-214705893

Add field/validation/behavior change to API review requirements

---

contributors/devel/development.md

Also adds an explicit note that Go 1.13 is not supported yet since there have been few questions on slack/GitHub issues created (example https://github.com/kubernetes/client-go/issues/670) when Kubernetes failed to work with Go 1.13.

devel: update supported Go versions

---

sig-storage/README.md

fixing broken link,
due to the capitalization of the contributing.md file form "contributing.md" to CONTRIBUTING.md" the link doesn't work anymore

Fix broken link in SIG Storage README

---

communication/slack-config/channels.yaml

[FIAAS](https://fiaas.github.io) is a system that adds PaaS like functionality on top of Kubernetes. It is developed and used by several companies in [Schibsted Media Group](https://www.schibsted.com) and [Adevinta](https://www.adevinta.com). We have recently finalized the process of open sourcing the project, and are looking for ways to engage with what we hope will become a growing community outside the Schibsted and Adevinta companies.
As part of that process, we would like a project channel on the Kubernetes Slack, so that our users can reach out to us and discuss our project.

Add channel for fiaas project

---

communication/slack-config/channels.yaml

KubeOne is an open-source project for creating and managing Kubernetes highly-available clusters. It is supposed to work with on any cloud provider, on on-premises (with VMware vSphere and OpenStack), as well as on bare-metal.
The project and more information about it can be found here: https://github.com/kubermatic/kubeone
We would like to have a channel for the project, so we can grow the community, improve the user experience, and communicate with contributors.
I'm not sure do we need a channel moderator, but I'd be happy to take care of that if needed. This channel is supposed to become the main one and replace the one we have on our Kubermatic Slack. If there are any concerns regarding that, please let me know. As far as I know, we don't have any Slack channel on Kubernetes Slack …

Add a Slack channel for KubeOne

---

communication/slack-config/channels.yaml

Purpose of this channel is to set a place where leads and shadows for the new sig-conttribex issue triage team can connect and talk but also for folks who want to be involved.

Add slack channel for sig-contribex issue triage team

---

communication/slack-config/channels.yaml

[NAIS](nais.io) is a platform that adds PaaS like functionality on top of Kubernetes. It is developed and used by the Norwegian Labour and Welfare Administration(NAV). This platform has been open source from day one, and are used heavenly inside NAV, and has influenced several other platforms in the public sector in Norway. We think this can be used more broadly.
As part of that process, we would like a project channel on the Kubernetes Slack, so that our users can reach out to us and discuss our project.

adding nais as slack channel

---

sig-network/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/1154
/assign @caseydavenport @dcbw @thockin 
/hold
for explicit lgtm from sig leads

sig-network: migrate ip-masq-agent to kubernetes-sigs

---

mentoring/mentor-guide.md
mentoring/mentoring-events.md

I changed the focus from "speed mentoring" to "pod mentoring". It seems like the speed portion is more of a feature rather than the main idea, which is getting a group of mentors together to answer questions.
* Added Pod Mentoring information for potential mentors
* Added Pod Mentoring information for potential mentees
Fixes https://github.com/kubernetes/community/issues/3744

Add Pod Mentoring Information

---

contributors/devel/sig-release/cherry-picks.md

There has been a fair amount of ambiguity, even deliberately, around
what is a valid candidate for backporting to a stable release branch of
Kubernetes.  For some the criteria is simply "critical bug fixes", but
this is also something that lacks definition.  This documentation update
attempts to better describe what is expected of and what can be expected
by somebody proposing a cherry-pick on one of our stable release branches.

devel guide: add words on cherry pick review process

---

contributors/devel/sig-testing/e2e-tests.md

If a test impacts other workloads in a meaningful way it ought
to be considered disruptive. Clarified the wording so that it
isn't so focused on only restarting components.

Clarify the meaning of the [Disruptive] E2E test tag

---

communication/slack-config/channels.yaml

Add a dedicated Slack channel for use by members of the [Kubernetes Edinburgh Meetup Group](https://www.meetup.com/Kubernetes-Edinburgh/), to be able to discuss and coordinate things such as topics for future events.

Add channel for Kubernetes Edinburgh Meetup Group

---

sig-docs/README.md
sigs.yaml

The reference-docs repo has now been migrated to kubernetes-sigs.
Ref: https://github.com/kubernetes/org/issues/1158
/cc @jimangel 
/hold

Update reference-docs repo location.

---

contributors/guide/release-notes.md

This PR adds a link to @marpaia's talk at KubeCon to the release notes documentation.
I just recently had the need to add a release note to my PR for the first time and was a bit lost because I couldn't quickly find more information about why and how. I found this talk incredibly helpful and a good addition to the written documentation.
Ref [release/#883](https://github.com/kubernetes/release/pull/883)

Add KubeCon lightning talk to release-notes docs

---

communication/slack-config/channels.yaml

The open source chaos engineering project "Litmus" is a tool set for orchestrating chaos on Kubernetes. The project is at https://github.com/litmuschaos . As the users of this project will be in the Kubernetes community, we are requesting a separate channel to collaborate the communication.
Signed-off-by: Uma Mukkara <uma@mayadata.io>

Request for a new slack channel to collaborate chaos engineering on K8S

---

communication/slack-config/channels.yaml

We recently signed up ~15 new contributors for mentorship in our working
group, and @parispittman suggested we provision a special Slack channel
for our mentorship program.

Add Sslack channel for wg-component-standard mentorship program

---

sig-cloud-provider/README.md
sig-cluster-lifecycle/README.md
sigs.yaml

Now that the cloud provider SIG consolidation is complete and we've [buffed the OWNERS files](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/285) for capz, I'd like to official move capz in as a subproject of SIG Cluster Lifecycle (where it belongs).
ref: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/284
/assign @timothysc @andrewsykim 
cc: @vincepri @CecileRobertMichon @soggiest @awesomenix @juan-lee @serbrech

cluster-lifecycle: Move capz from SIG Cloud Provider to SIG CL

---

generator/app.go
generator/sig_readme.tmpl
generator/ug_readme.tmpl
generator/wg_readme.tmpl
sig-auth/README.md
sig-cli/README.md
sig-cloud-provider/README.md
sig-cluster-lifecycle/README.md
sig-contributor-experience/README.md
sig-docs/README.md
sig-pm/README.md
sig-release/README.md
sig-scheduling/README.md
sig-service-catalog/README.md
sigs.yaml
wg-multitenancy/README.md

If we end up specifying the company for emeritus leads, we could end up with stale information. Moreover, we don't gain any specific value from company info of emeritus leads either.
They shouldn't be required to update sigs.yaml in case they switch companies, especially if they've decided to step away from the project.
/hold
for discussion

generator: don't specify company for emeritus_leads

---

communication/slack-config/sig-release/config.yaml

To date, the Comms team have created DM groups with the lead and shadows for each release.
This channel would allow for process, questions, and knowledge to be passed on from each release and also allow any conversations within the team to be consumable by any casual observers with an interest in future participation.
---
Because I'm an idiot, this lay open for 2 weeks against my own fork 😂
There are a few comments worth consuming though.
https://github.com/rawkode/community/pull/1

feat(slack-channel): add channel for release-comms

---

contributors/devel/sig-testing/writing-good-e2e-tests.md

There was discussion about using `framework.Logf` for logging, this isn't yet in the documentation.

Add logging documentation

---

contributors/guide/owners.md

As there is an ongoing efforts to remove and pare down repo collaborators (ref: https://github.com/kubernetes/community/issues/3178), this PR updates the owners guide to remove repo collaborator references and replaces them with pointers to org members.
/cc @nikhita @cblecker @idvoretskyi 
/hold

Remove collaborator references from owners guide.

---

contributors/devel/README.md
contributors/devel/sig-api-machinery/controllers.md

Caught a few old references of `glog` and update them to `klog`.
There are still 2 remaining but wasn't sure if they should be updated since they are older design proposal. Happy to include them here if so.
- [contributors/design-proposals/storage/volumes.md](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/volumes.md)
- [contributors/design-proposals/storage/attacher-detacher-refactor-for-local-storage.md](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/attacher-detacher-refactor-for-local-storage.md)

Update old glog references to klog

---

sig-api-machinery/README.md
sigs.yaml

The file https://raw.githubusercontent.com/kubernetes/kubernetes/master/pkg/quota/OWNERS does not exist. 
Assuming the one in the V1 directory is the correct file, so updated sigs.yaml with a valid owners file: https://raw.githubusercontent.com/kubernetes/kubernetes/master/pkg/quota/v1/OWNERS

FIxed invalid owners file in sigs.yaml

---

contributors/devel/sig-release/release.md

This PR sends definitions and links to the kuberentes release phases.
Part of https://github.com/kubernetes/sig-release/issues/319.
Links may not work until https://github.com/kubernetes/sig-release/pull/827 is merged.
/sig release
/area release-team
/assign @tpepper

Adds definitions for release stages

---

contributors/guide/README.md
contributors/guide/bug-bounty.md
contributors/guide/github-workflow.md
contributors/guide/non-code-contributions.md
contributors/guide/pull-requests.md
contributors/guide/release-notes.md
contributors/guide/style-guide.md

Hugo uses the black friday markdown render engine which (sadly) doesn't render Markdown like GitHub. It's a bit less forgiving of spacing has some issues with mixing ordered and unordered lists. 
This PR fixes several of the bigger rendering issues.
Will mark where I made the biggest change.
/cc @guineveresaenger @castrojo

Update contributor guide formatting to be Hugo compatible.

---

contributors/guide/contributor-cheatsheet/README.md
contributors/guide/pull-requests.md

Especially because we link to https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#why-is-my-pull-request-not-getting-reviewed as `recommended escalation practices` in the bot comment for new contributors' PRs (https://github.com/kubernetes/org/pull/1313#issuecomment-542466991).
/cc @castrojo @guineveresaenger @mrbobbytables

contributor-guide: add note about #pr-reviews channel

---

sig-architecture/production-readiness.md

prr: start of pilot policy doc

---

sig-scalability/slos/api_call_latency.md
sig-scalability/slos/api_extensions_latency.md
sig-scalability/slos/slos.md

Initializers were removed from Kubernetes.
/assign @mm4tt 
@yue9944882

Remove references to initializers in SLOs

---

communication/slack-config/channels.yaml

Add a dedicated Slack channel for use by members of the [Kubernetes Cairo Meetup Group](https://www.meetup.com/Cairo-Kubernetes-Meetup/), to be able to discuss and coordinate things such as topics for future events, speakers, feedback, etc.

Add meetup-egypt channel

---

contributors/devel/sig-release/cherry-picks.md

We see a relatively high volume of cherry picks that aren't clearly
meeting the criteria for cherry-picking, but that criteria has only
recently started to be in written, shared form and it is not super
discoverable.  To make it more clear let's make that its own section
(linkable), move it earlier in the document, and add a table of contents
to the cherry-picks.md for navigation.

cherry-picks: bump up guidance on criteria, add table of contents

---

communication/slack-config/channels.yaml

The private steering slack channel is also called `steering-committee`, we should probably rename that to `steering-private` first.
/hold
/cc @kubernetes/steering-committee

Add public steering-committee slack channel

---

communication/mailing-list-guidelines.md

While doing some mailing list moderation, I noticed this typo in the
mailing list doc.

trivial: typo fix

---

committee-steering/README.md
sigs.yaml

Ref https://github.com/kubernetes/org/issues/1354
The repo has been retired: https://github.com/kubernetes-retired/spartakus

steering: remove spartakus from sigs.yaml

---

communication/slack-config/channels.yaml

This channel would be used to discuss issues with and roadmap for the distroless containers developed here:
https://github.com/GoogleContainerTools/distroless

Adding channel for discussion of the distroless containers

---

communication/slack-config/channels.yaml

This channel will be used to coordinate development of the production [readiness review process](https://github.com/kubernetes/enhancements/blob/37c1f0266a6371ca0ccc53965cfb376a53821000/keps/sig-architecture/20190731-production-readiness-review-process.md).

Add channel for production readiness review team

---

sig-network/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/1292
/cc @bowei 
/assign @thockin @dcbw @caseydavenport
/hold
for sign off from sig network leads

sig-network: Add service-apis repo to services subproject.

---

sig-instrumentation/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/1382
/cc @serathius 
/assign @brancz @piosz
/hold

sig-instrumentation: move metrics-server from k-incubator to k-sigs

---

sig-cluster-lifecycle/README.md
sigs.yaml

I noticed that there are now meeting notes for the Image Builder office hours, and so I thought it would be helpful to provide the link on the SIG-Cluster-Lifecycle README.

Add Meeting notes and Agenda for Image Builder office hours

---

sig-network/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/1286
/assign @thockin @dcbw @caseydavenport 
/hold
for lgtm by sig network leads

sig-network: move external-dns from k-incubator k-sigs

---

communication/slack-config/channels.yaml

The purpose of this Slack channel is to support activity associated with the new [VMware User Group](https://github.com/kubernetes/community/tree/master/ug-vmware-users) add with this [PR](https://github.com/kubernetes/community/pull/4083)
This channel will have some discussions closely aligned with the VMware cloud provider, but discourse will be about Kubernetes user focused topics and not proprietary information related to the provider.

add new Slack channel for VMware User Group

---

sig-cluster-lifecycle/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/1305
/cc @aaronlevy 
/assign @timothysc @justinsb
/hold

sig-cluster-lifecycle: move bootkube from k-incubator to k-sigs

---

contributors/guide/owners.md

- expected argument for /approve command is `no-issue`
- resolves #4227

chore: fixing typo in command example

---

sig-network/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/1328
/assign @thockin @dcbw @caseydavenport
/hold
for lgtm by sig network leads

sig-network: add ingress-controller-conformance repo

---

contributors/design-proposals/node/pod-lifecycle-event-generator.md

Section `Leverage Upstream Container Events` has broken link, so updated with latest docker's `Monitor events` api doc.

Broken link of Docker's event stream

---

communication/slack-config/channels.yaml

Signed-off-by: Chuck Ha <chuckh@vmware.com>
/cc @jeefy 
for context, the community/channel has had weeks of notification and we've merged into the cluster-api slack channel.
(copying folks who reviewed and approved from https://github.com/kubernetes/community/pull/3836)

Archive channel: cluster-api-docker

---

communication/slack-config/channels.yaml

This channel will field non-critical alerts for the prow.k8s.io
deployment to facilitate bug discovery and remediation while not
alerting the on-call.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

Add a #prow-alerts channel to Slack

---

communication/slack-config/channels.yaml

Crash Recovery and Diagnostics for Kubernetes (Crash Diagnostics for short) is designed to help human operators who are investigating and troubleshooting unhealthy or unresponsive Kubernetes clusters. It is a project designed to automate the diagnosis of problem clusters that may be in an unstable state including completely inoperable.
We would like to have a channel dedicated to the project in the K8s Slack, to share experiences and grow the community.
The project can be found here: https://github.com/vmware-tanzu/crash-diagnostics

Add crash-diagnostics channel

---

contributors/devel/sig-architecture/staging.md

Since https://github.com/kubernetes/publishing-bot/pull/148/, the list of staging repositories published has been externalized to https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/publishing/rules.yaml.
Not sure if https://github.com/kubernetes/publishing-bot/blob/master/hack/fetch-all-latest-and-push.sh#L35 should also be referenced.
FTR, the updated list of currently published repos was generated with:
```
```
For branches, the output of the following command needs manual processing:
```
```

Update the location of the list of staging repositories published

---

communication/slack-config/channels.yaml

This PR is part of the issue kubernetes/test-infra#14740
and required to the correct work of kubernetes/test-infra#15167.'
The slack reporter will push information about the test failures to the newly added channel #test-failures

Add test-failures channel to slack configuration

---

contributors/devel/sig-architecture/api-conventions.md

Rationale: The line hasn't been updated since 2017, even though changes were still being made to the doc. We can already see the last-updated date from the git history, and if we just update it now folks will probably continue forgetting to do so in the future.

Remove last-updated date line from api-conventions.md

---

communication/slack-config/channels.yaml

solr-operator (https://github.com/bloomberg/solr-operator) is an open-source kubernetes operator to run solrclouds infrastructure on kubernetes. It is built using kubebuilder v2.
There is a lot of interest from the community ever since the project was open sourced. Due to lack of a common communication platform, contributors are having a hard time to run technical conversations related to the design and future of the operator. It will immensely help the project, if we can have slack channel in the kubernetes workspace.
Signed-off-by: swarupdonepudi <swarup.donepudi@gmail.com>

Added new slack channel for solr-operator

---

communication/slack-config/channels.yaml

Antrea (https://github.com/vmware-tanzu/antrea) is an open-source CNI
plugin based on Open vSwitch. It was built specifically to be a
networking solution for Kubernetes clusters and supports Network
Policies.
We are adding a single channel at the moment (antrea) but may want to
have a dev channel in the future.
We would like to be part of the Kubernetes Slack so that our users have one
less workspace to "manage".
Signed-off-by: Antonin Bas <abas@vmware.com>

Add Slack channel for Project Antrea

---

events/2020/03-contributor-summit/README.md
events/2020/07-contributor-summit/README.md
events/2020/11-contributor-summit/README.md

Adding details for 2020 events in Amsterdam, China, and Boston to the placeholder pages. Some of the details are still TBD, but I thought it would be good to add the dates and get all of them into a common template based on what we had for San Diego.
/assign @jeefy @parispittman

Adding details for 2020 events in Amsterdam, China, and Boston

---

contributors/guide/release-notes.md

Hey :wave:, I'd like to push forward #484 and think a good first step would be to put the information into the contributors guide. After this we should discuss how we apply the guide to be more visible to all users.
Refers to: #484

Add release notes guideline to contributors guide

---

communication/slack-config/restrictions.yaml
communication/slack-config/sig-release/usergroups.yaml
communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

Syncing up the Slack user group with the current set of Release Managers.
**On hold until https://github.com/kubernetes/sig-release/pull/868 merges**
/hold
/assign @tpepper @calebamiles 
@kubernetes/sig-release-admins @kubernetes/release-engineering @kubernetes/release-managers 
/milestone v1.18
/kind feature cleanup

releng: Update release-managers Slack user group

---

contributors/guide/issue-triage.md

Fixing some spelling mistakes in the issue-triage guide.

Fix some typos in issue-triage guide

---

events/events-team/README.md

Fixed broken links to content handbooks that happened when we separated them into multiple handbooks for all of the roles. Also simplified it a bit and clarified that it links to page containing all of the roles.
/assign @parispittman @jberkus

Content Subteam Handbook - fixed links & clarified that it links to other handbooks

---

contributors/devel/sig-release/release.md

First pass at addressing https://github.com/kubernetes/sig-release/issues/320. 
Feedback and nits appreciated. :)

Add more milestone info to the release doc

---

contributors/guide/style-guide.md
sig-contributor-experience/markdown-link-style-guide.md

sig-contributor-experience/markdown-link-style-guide.md has since moved
to a more robust style guide at contributors/guide/style-guide.md.
Adding a tombstone for the deprecated guide.
/assign @nikhita @parispittman @cblecker 
ref: https://github.com/kubernetes/sig-release/issues/696

contribex: Tombstone old Markdown style guide

---

contributors/devel/sig-testing/flaky-tests.md

The content here is overall pretty old and not super useful to those looking to troubleshoot e2e flakes.  Before I go down the rabbit hole of rewriting, I have added links to examples of dashboards I have found helpful for identifying and troubleshooting flakes.
If there were egregiously old references (ie: jenkins) I dropped them
ref: https://github.com/kubernetes/kubernetes/issues/68091#issuecomment-563413793
cc @kubernetes/ci-signal 
cc @kubernetes/sig-testing-pr-reviews 
/cc @liggitt @justaugustus @smarterclayton @alejandrox1 
since you commented on the ref'ed issue

Try adding some more useful links for hunting flakes

---

communication/README.md

Follow up to nits, links etc in https://github.com/kubernetes/community/pull/4201.
The content itself remains the same.

Update communications guidelines

---

contributors/devel/sig-architecture/staging.md

xref https://github.com/kubernetes/kubernetes/issues/84608, https://github.com/kubernetes/enhancements/pull/1350, https://github.com/kubernetes/publishing-bot/pull/210
/hold
until 1.17 is actually released and we have enabled this functionality
/cc @liggitt @sttts @dims 
/assign @liggitt

sig-arch/staging: add note about semver tags

---

CLA.md

Fixes #4303 
On https://github.com/cncf/gitdm/ the developer_affiliation text file was broken down into smaller text files, so it's no longer possible to link a single file. This PR hopefully fixes that.

Changing link to cncf/gitdm developer_affiliation files

---

events/events-team/content/new-contributor-workshops/README.md
events/events-team/content/new-contributor-workshops/build-and-test.md
events/events-team/content/new-contributor-workshops/contributor-paths.md
events/events-team/content/new-contributor-workshops/first-issue-help.md
events/events-team/content/new-contributor-workshops/labels-and-bots.md
events/events-team/content/new-contributor-workshops/new-contributor-workshop-lead.md
events/events-team/content/new-contributor-workshops/playground-exercise.md

Fixed the typos that several of us found during reviews of PR #4278 since we decided to merge it and fix the typos later to get the content live.
/assign @castrojo 
/assign @guineveresaenger

Fixed some typos in NCW event handbooks

---

contributors/guide/release-notes.md

This adds a dedicated section about the review of release notes.
**Background information:** I have a highly experimental idea of classifying past release notes regarding the three cases described in the change (actually four cases when we assume that the note is correct). I would like to use this data to train a machine learning model which means that the number of classes needs to be as low as possible whereas the accuracy needs to be high. For example, If I classify something as _"Has no impact on the user"_ then someone else should classify it as the same. After the model exists with a fair amount of data, we could use it to classify new release notes and provide some sort of automatism around. To me this seems more useful than providing a dedicated checklist. WDYT?
Refers to #484
/cc …

Add release notes review section

---

communication/slack-config/channels.yaml
communication/slack-config/sig-cloud-provider/config.yaml

and moved to the sig-cloud-provider folder
addresses https://github.com/kubernetes/community/pull/4339#discussion_r360207711
/cc @zhangxiaoyu-zidif @cheftako @idvoretskyi

slack: rename provider-alibaba-cloud channel

---

contributors/devel/sig-testing/flaky-tests.md

When clicking the link for go.k8s.io/triage, the NotFound page was
shown because the link is invalid. This fixes it.

[Trivial] Fix link for go.k8s.io/triage

---

communication/slack-config/channels.yaml

I want to append a channel for study and q&a by novice users of Kubernetes in Japan(for Japanese speakers).
ref: https://kubernetes.slack.com/archives/C0QKVN230/p1577342193032500

Add slack #jp-users-novice channel

---

contributors/devel/sig-release/cherry-picks.md

> We need to document the specific criteria (issue introduced post-release in a patch & CI availability) and choose the document location (somewhere in k/sig-release)
This PR outlines the process and criteria for _special_ exceptions when back porting a fix to an "out-of-support" release.
resolves: https://github.com/kubernetes/sig-release/issues/450

adding in doc to cover exceptions

---

communication/slack-config/channels.yaml

[KubeMove](http://www.github.com/kubemove/kubemove) is a opensource project providing framework for applications running on Kubernetes to migrate across clusters in different cloud providers, on-prem along with data. This is under active development and licensed under Apache 2.0. This project, being providing framework, is having contributions from more than one company and expected to be interested by multiple applications.
To help multiple companies coordinate on this opensource project, we would like to have a slack channel for open discussions and to reach out to interested parties.
Signed-off-by: Vitta <vitta@mayadata.io>

adding kubemove slack channel

---

contributors/devel/sig-testing/flaky-tests.md

Updated the link to the test failure report to include the colon after protocol. Updated the link to velodrome to HTTP, as it does not run on HTTPS

[Trivial] Fix broken links

---

communication/slack-config/channels.yaml

Requesting a channel for discussion and support of the [kURL Open Source Kubernetes Installer](https://kurl.sh/) project.  kURL creates unique URLs to download customizable Kubernetes cluster install scripts, with a variety of selectable add-on components.  Public github repo for the project is [here](https://github.com/replicatedhq/kurl/).

add kurl channel

---

communication/slack-config/channels.yaml

Requesting a channel for discussion and support of the Troubleshoot Open Source project. Troubleshoot is a tool for running PreFlight checks on a cluster (to determine if the cluster meets necessary preconditions for installing an application or service) and for collecting support bundles for remote diagnosis of cluster issues.
Troubleshoot docs: https://troubleshoot.sh/
Troubleshoot public repo: https://github.com/replicatedhq/troubleshoot

add app-troubleshoot channel

---

communication/slack-config/channels.yaml

Requesting a channel for discussion and support of the SchemaHero Open Source project. SchemaHero is a Kubernetes Operator that manages database schema migrations as code.
SchemaHero docs: https://schemahero.io/docs/
SchemaHero public repo: https://github.com/schemahero/schemahero

add schemahero channel

---

contributors/devel/sig-architecture/conformance-tests.md

Based on conformance meeting today
- we want to allow a test to exercise the event API to verify it can
be exercised; this isn't depending on a specific component to
generate a specific event
- ref https://github.com/kubernetes/kubernetes/issues/86288
- ref https://github.com/kubernetes/kubernetes/pull/86858
- we don't want to allow tests which are attempting to exercise the
componentstatus API as there is a KEP out to deprecate it, and all
involved don't want to add more code around componentstatus
- ref https://github.com/kubernetes/kubernetes/pull/86860
- ref https://github.com/kubernetes/kubernetes/issues/86087
/area conformance
/cc @johnbelamaric @hh

Add two clarifications to conformance requirements

---

sig-scheduling/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/1529
/assign @ahg-g @k82cn 
/cc @ingvagabund
/hold
for confirm from leads

sig-scheduling: move cluster-capacity from k-incubator to k-sigs

---

communication/README.md

Fixes #4410
The current markdown files are out of date for the 2020 Kubernetes community call schedule.
Signed-off-by: Chris Hein <me@chrishein.com>

updating community call documented date to reflect 2020 changes

---

contributors/devel/sig-testing/e2e-tests.md

As far as I can tell, `kubetest` no longer has a `-ctl` flag.
Remove it from the examples of commands that can be run using `kubetest`.
Fixes #

Delete instructions describing the `kubetest -ctl` command

---

communication/slack-config/channels.yaml

This channel hasn't been used since May '18 and was originally requested by myself - this does not need to continue existing 😄 if anything changes in future, we can un-archive it.

slack-config: archive #navigator channel

---

communication/slack-config/channels.yaml

Inspektor Gadget (https://github.com/kinvolk/inspektor-gadget) contains
a collection of gadgets for developers of Kubernetes applications. Its
main gadget, traceloop, uses BPF to record system calls performed by
each pod like a flight recorder. It can be used to see the last system
calls performed by a pod after it crashed.
It is available under the Apache license.
It is built on top of BCC (https://github.com/iovisor/bcc) and traceloop
(https://github.com/kinvolk/traceloop).

New slack channel for Inspektor Gadget

---

OWNERS_ALIASES
generator/aliases.tmpl
generator/app.go

- Add LeadershipGroup#Owners() which returns a sorted and de-duped
list of owners ([]Person) for this LeadershipGroup by combining
Chairs and TechnicalLeads
- The function is used in generator/aliases.tmpl
- Update OWNERS_ALIASES with the new results
NONE
/assign @nikhita 
/kind feature

generator/app: add means for sorted and de-duped OWNERS_ALIASES

---

events/events-team/feedback.md

This will add links to the Barcelona 2019 retro and survey feedback documents.
Adds to #4230.
Signed-off-by: Jonas Rosland <jrosland@vmware.com>

Add Barcelona 2019 retro and survey feedback

---

contributors/guide/style-guide.md

- Adds a note on how to refer to Kubernetes Groups (SIG, WG, UG).
- Adds a note on usage of the `slug` attribute if used.

Update style guide with a few minor additions

---

wg-component-standard/README.md

Fixes #4117
/wg component-standard
/sig cluster-lifecycle
This patch uses custom content.
The trade-off is that the information is at the bottom. Not everyone reads until the end.
Alternative to #4137

Document component-standard issues /w custom content

---

github-management/README.md
github-management/new-membership-procedure.md

We get multiple  membership requests per day and New Membership Coordinators (NMCs) do the bulk of the work for adding members to the GitHub config. Currently, they need to wait for approval from a member of the GitHub admin team on such PRs.
To make the process smoother and faster, this PR updates docs to grant approval privileges to NMCs for PRs updating members in the GitHub config.
Discussed this with the GitHub admin team already.
/hold
for written sign off from github admin team

Update docs for granting approval privileges to NMCs

---

github-management/README.md

Yang is an active sig-contribex member, is familiar with peribolos and how the k/org repo is structured, and would be an amazing new membership coordinator. :)
Having another new membership coordinator should help lessen the burden from @nzoueidi and @justaugustus and let us have faster response times. Yang is also in Japan, so this should help us cover more timezones.
Discussed this offline within the GitHub Admin team and with Yang.
/cc @kubernetes/owners @nzoueidi @justaugustus @idealhack 
/assign @idealhack 
/hold
for lgtm from github admin team and @idealhack

Add idealhack as New Membership Coordinator

---

events/community-meeting.md

Changed Do NOT copy the meetings over to a your personal calendar to Do NOT copy the meetings over to your personal calendar
Fixes #

Fixed typo

---

communication/marketing-team/contributor-blogging.md

This PR adds a blog guideline for the marketing team.

add marketing blog guidelines

---

contributors/design-proposals/node/kubelet-eviction.md

As discussed in https://github.com/kubernetes/kubernetes/pull/84414#issuecomment-546782451, the section about daemonset is out of date, so remove it.

remove the daemonset specific exception

---

communication/slack-config/channels.yaml

https://sigs.k8s.io/krew is a vibrant SIG CLI project with user and developer
communities.
Proposing `#krew` channel to Kubernetes Slack for colalboration.

slack-config: add #krew

---

contributors/design-proposals/README.md

A few folks have stumbled across the design proposal docs and inquired about it. Figured it'd be a good idea to leave a note about it's deprecation and link to the KEP docs.
/cc @justaugustus 
/hold

Add note about design proposal process deprecation

---

mentoring/meet-our-contributors.md

In 4d540852a the time of the meet-our-contributors meeting was updated
to 3:30pm UTC, but the link to the timezone converter still pointed to
2:30pm. This change fixes the link to point to the updated meeting time.

Update TZ converter for meet-our-contributors mtg

---

sig-list.md
sigs.yaml
ug-vmware-users/README.md

Added a link to the VMware User Group Meeting Notes doc
Signed-off-by: Kendrick Coleman <kendrickc@vmware.com>
/assign @cantbewong @mylesagray

Add Meeting Notes Link to VMware UG

---

communication/slack-config/channels.yaml

Request the slack channel for the `cluster-api-digitalocean` similar that aws and azure have, to discuss subjects related to the CAPDO
/cc @xmudrii @detiber

slack channel: create cluster-api-digitalocean channel

---

communication/slack-config/channels.yaml

Signed-Off-By: David Anderson <dave@natulte.net>
Rationale (copied from #slack-admins): we already have #metallb for user traffic, but we'd like a place for myself (current maintainer) and new maintainers to talk project logistics and stuff that would get drowned out in the support cries for help on #metallb. Right now as a workaround, we have a private channel on Rancher's slack, but that's becoming an issue as non-Rancher people want to get involved. It seems natural to move things into the open on the k8s slack.

slack-config: add #metallb-dev.

---

communication/slack-config/channels.yaml

It would be great to have a channel for OpenEBS: https://openebs.io/ in slack.
OpenEBS is developed under Apache License 2.0 license at the project level. Some components of the projects are derived from the other Open Source projects and are distributed under their respective licenses.
OpenEBS is a sandbox CNCF project and provides storage-integration for Kubernetes.
Signed-off-by: David Karlsen <david@davidkarlsen.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/community/4528)

add openebs slack channel

---

communication/slack-config/channels.yaml

The DC meetup wants to use the kubernetes slack to communicate and post relevant information.

Add channel for dc kubernetes meetup

---

contributors/devel/development.md

`./pkg/api/helper` doesn't exist in the kubernetes repo. Replace it with [./pkg/apis/core/helper](https://github.com/kubernetes/kubernetes/tree/master/pkg/apis/core/helper).

Fix invalid command: replace absent package

---

sig-storage/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/1648
/hold
/assign @xing-yang @msau42 @jsafrane @saad-ali

sig-storage: add external-health-monitor repo

---

sig-contributor-experience/community-maintenance.md

fixes: #3305
fixes: #4477 
- Removed unnecessary checks from slack maintenance tasks
- Follow up on changes discussed in #4477
- Updated links to PR/Issue templates
- Removed outdated gsuite audit task
- With the automation of group management in k8s.io, a manual check is no longer necessary.
- Add devstats task regarding updating repo groups
- While this does not add automation to mapping repo -> repo group I think it's still safe to close #3305. With the new dashboard it is significantly easier to get an idea of what needs to be updated at a glance and the majority of changes here forward should be pretty minimal.
/cc @nikhita @castrojo @jberkus

Update community maintenance doc

---

communication/slack-config/channels.yaml

This requests a new channel for kcli, which is a tool designed to handle vms, containers and other objects on libvirt, ovirt, vsphere and cloud platforms.
The tool also allows to easily create kubernetes clusters either using kubeadm or openshift/okd, with the idea to extend it to other kubernetes deployment tooling, hence the request to host it here.

Add kcli channel

---

contributors/guide/contributing.md

Link was broken when the page got split up.

contributing: Fix link to "Sign the CLA"

---

contributors/devel/sig-testing/e2e-tests.md

According to the test-infra issue, some people seem to face the issue
when downloading kubetest command. So this adds NOTE to know how to
avoid the issue at this time.
Ref: https://github.com/kubernetes/test-infra/issues/14712

Add NOTE to know how to download kubetest command

---

contributors/devel/sig-testing/bazel.md

The correct spelling of openSUSE can be checked on https://en.opensuse.org/Portal:Distribution

Fix misspelling of openSUSE

---

sig-release/README.md
sigs.yaml

The existing group was not valid.  This may have been updated at some point.  This ensures the documentation is pointed to the correct group.

Update release managers group in documentation

---

communication/slack-config/channels.yaml

we would like a new slack channel called "sig-windows-leads"
We sometimes have lead specific work (like talking about presentations, deadlines, PRs, reviews, operations, etc) that makes sense to keep outside of the sig-windows channel. today, the only way we achieve this is by having many 2 and 3 and 4 people private chats. this is an unmanageable and we would like a dedicated channel.

Update channels.yaml to include a sig-windows-leads channel

---

contributors/devel/development.md
contributors/devel/sig-architecture/conformance-tests.md
contributors/devel/sig-node/node-performance-testing.md
contributors/devel/sig-testing/e2e-tests.md

**Which issue(s) this PR fixes**
Fixes #4486 
I changed contributor docs that referenced hack/e2e.go, to refer to kubetest instead
Thanks to @mrbobbytables for providing signposting.

fixes contrib doc bug #4486 - kubetest replaces hack/e2e.go

---

contributors/chairs-and-techleads/README.md
contributors/chairs-and-techleads/meeting-host.md

/hold
for comments. i think this is the best place to put this. documentation geared towards a certain type of contributor. i don't think the folder will be that extensive so not sure it warrants its own in the root. 
this would also house the archive for the chair/tl need to know email

adding chair and tl folder

---

committee-steering/governance/sig-governance.md

Fixes [issue in steering repo](https://github.com/kubernetes/steering/issues/152)
one bullet said meet once every three weeks (at min) another one said bi weekly. changing the second instance to once every three weeks (at min). also added the youtube link instead of a general youtube playlist as referenced.

sig-gov mtg consistency change

---

sig-network/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/1688
/assign @caseydavenport @dcbw @thockin 
/hold
for lgtm from sig-network leads

sig-network: add iptables-wrappers subproject

---

contributors/devel/sig-node/e2e-node-tests.md

Related to https://github.com/kubernetes/kubernetes/issues/83481

document the configuration for topology manager

---

sig-cloud-provider/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/1691
/assign @cheftako @andrewsykim 
/hold
for lgtm from sig-cloud-provider leads

sig-cloud-provider: add provider-huaweicloud subproject

---

communication/slack-guidelines.md

The archive directory is now owned by contributors@kubernetes.io and the export updated to be a recent archive.

Update Slack Archive link

---

communication/slack-config/channels.yaml

From the submariner[1][2] community we are looking for a neutral discussion place. We participate on the sig-multicluster and sig-networking SIG discussions to align API design with upstream.
We have lots of internal design threads which would pollute #sig-multicluster or #sig-networking channels.
Submariner is a project for connecting the IP address spaces of separate k8s clusters via IPSEC (and eventually WireGuard) plus routing. Today it mainly works with kube-proxy / iptables based implementations, but we plan to make proposals to the CNI interface for routing enhancements.
[1] https://submariner-io.github.io
[2] https://submariner.io

Add submariner to slack channels.yaml file

---

sig-scheduling/README.md
sigs.yaml

This PR updates `scheduler-plugins` as a standalone sig-scheduling subproject, instead of hosting under `scheduler`.
/sig scheduling

Correct scheduler-plugins as a standalone subproject

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

This removes them from the slack notifications when someone pings `@youtube-admins` on slack.

Retire jbeda and sarahnovotny from youtube admin slack notifications

---

communication/slack-config/channels.yaml

Some of my colleagues and I are forming a group for enablement of Kubernetes on ARM platform.
This is just getting started, and currently includes a [Github Organization](https://github.com/kubernetes-arm), some [Projects](https://github.com/orgs/kubernetes-arm/projects) we want to work on to better enable Kubernetes on ARM and [Blog](https://kubernetes-arm.com/) where we're going to post about the relevant projects and issues we work on, as well as experiments and guides.
The basic idea is just to invite engineers with similar interest and focus on improving ARM compatibility across upstream repos and it would be helpful if we could please have a Slack channel to organize ourselves in.
Thank you!

[slack channel] add kubernetes-arm channel

---

communication/slack-config/channels.yaml

The Las Vegas meetup community would like to use slack for communication.

Add meetup-lasvegas channel

---

OWNERS_ALIASES
sig-docs/README.md
sigs.yaml

Update `sigs.yaml` with my information around becoming a new tech lead for SIG Docs.

Add Taylor Dolezal to SIG Docs Tech Leads

---

communication/slack-config/channels.yaml

From k8spin.cloud we want to include a new channel in the kubernete slack group.
The channel will be used to share experiences between k8spin users.
K8Spin is a Kubernetes namespace as a service platform online.
In addition to the SaaS service, we are building some OSS tools related to kubernetes multi-tenant stuff: 
https://github.com/k8spin
Thanks!

Add k8spin channel

---

contributors/guide/contributor-cheatsheet/README.md
contributors/guide/github-workflow.md
contributors/guide/pull-requests.md

Related to `kubernetes/release` [#1204](https://github.com/kubernetes/release/issues/1204). 
This PR improves documentation and instruction around squashing commits – when you should do it (before a merge), who should do it (the PR author), and what to squash (anything that isn't a meaningful unit of work.)
SIG Docs wants this improvement because we often get contributors who aren't as familiar with Git as some of the other repositories/SIG's. It's difficult to tell a (very) new contributor that they're responsible for squashing their own commits if we don't provide a bit of guidance as to how to do that. Third party resources are good and perhaps preferred, but we often get requests for help with "the end to end process of making my first contribution" regardless of whether we link to …

Improve squashing documentation

---

communication/slack-config/channels.yaml

This PR adds a slack channel for https://github.com/dexidp/dex, an OAuth2 identity provider used significantly throughout the Kubernetes community. A conversation on both the [Dex Repo](https://github.com/dexidp/dex/issues/1682#issuecomment-609991257) and the #slack-admins channel motivated this change.

Adding dex slack channel

---

communication/slack-config/channels.yaml

In #4690 we created a channel for Dex (#dex) but it turns out there is a uniqueness constraint that prevents duplicates: 
From @jeefy: 
> Slack in its infinite wisdom requires a unique name within the workspace -- meaning if someone is named "dex" we cannot create a channel named "dex". We ran into this before but it's infrequent so we forgot.
This PR moves from #dex to #dexidp

Creating channel for Dex (#dexidp)

---

mentoring/programs/google-summer-of-code.md

CNCF has renamed the SOC repo to https://github.com/cncf/mentoring (to include all the CNCF mentorship programs), reflecting this change here.

CNCF mentoring repo URL updated

---

sig-autoscaling/README.md
sig-network/README.md
sigs.yaml

The OWNERS at the root of these repos are sig-network people, and
the recent activity I've seen around these repos is coming from
sig-network people. My understanding is sig-autoscaling doesn't
want these projects anymore.
This is the first step, the next step is to suggest that these be
moved to kubernetes-sigs or kubernetes-retired depending on your
willingness to support or own them.
/hold
/assign @MrHohn @thockin
looking for an /lgtm from sig-network
/assign @gjtempleton @mwielgus
looking for an /lgtm from sig-autoscaling

Move cluster-proportional subprojects to sig-network

---

sig-storage/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/1800, https://github.com/kubernetes/org/issues/1801 
/assign @saad-ali @xing-yang @msau42 @jsafrane 
/hold
for sign off from sig-storage leads

sig-storage: add gluster provisioner repos

---

communication/mailing-list-guidelines.md

The previous setting does not reflect the current state of most of our lists. We use the new member moderation as the general protection mechanism instead.
/cc @justaugustus

Update mailing list permissions guidelines

---

communication/slack-config/channels.yaml

SIG-Windows is working towards supporting the ContainerD container runtime on Windows nodes (instead of Docker) and would like a dedicated slack channel to better organize and collaborate.
ContainerD support for Windows went Alpha in 1.18 and we are currently focused on the following
- Identifying stability issues
- Identifying/closing feature parity gaps with Docker EE on Windows
- Identifying  potential feature parity gaps in Windows containers with respect to Linux containers which can be addressed with ContainerD
Having a dedicated slack channel would help us keep track of issues/test pass results/PRs/etc without adding noise to the sig-windows channel which is primarily used by cluster operators today.
KEP for ContainerD support on Windows: …

Add windows-containerd slack channel

---

sig-cluster-lifecycle/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/1812
The repo is archived.
/assign @neolit123 
for lgtm

sig-cluster-lifecycle: remove kubernetes-anywhere

---

sig-network/README.md
sigs.yaml

Ref:
https://github.com/kubernetes/community/blob/d8817f1a8d466fabb215410302a2bc705c27f356/communication/slack-config/sig-network/config.yaml#L1-L2
/assign @thockin 
for lgtm

sig-network: document service-apis slack channel

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

Adding user kaslin to the slack config for the Upstream Marketing usergroup. Added kaslin to users.yaml and usergroups.yaml.
Related to issue [k8s blog] series: SIG profiles/storytelling #3654 - Kaslin is joining and taking on one of the tasks in this issue. (As a starter task.)

Add user kaslin to Upstream Marketing

---

communication/slack-config/channels.yaml

Create a new channel where folks can discuss all aspects of
adding NUMA Topology Awareness to the scheduling phase
for pods.
Signed-off-by: vpickard <vpickard@redhat.com>
Fixes #

Create a slack channel to discuss Topology Aware Scheduling

---

sig-contributor-experience/meeting-notes-archive/2018-meeting-notes.md
sig-contributor-experience/meeting-notes-archive/2019-meeting-notes.md
sig-contributor-experience/meeting-notes-archive/README.md

The meeting notes google doc is around 200 pages and getting pretty slow. This archives off the 2018 and 2019 notes.
Fixes #4737 
/assign @cblecker @nikhita @castrojo

sig-contribex: archive 2018 and 2019 meeting notes

---

contributors/devel/sig-api-machinery/strategic-merge-patch.md

mutual exclusive -> mutually exclusive
**Which issue(s) this PR fixes**: #4764

docs: fix typo

---

communication/marketing-team/README.md
communication/marketing-team/role-handbooks/editor.md
communication/marketing-team/role-handbooks/internal-marketing.md
communication/marketing-team/role-handbooks/social-media.md
communication/marketing-team/role-handbooks/storytellers.md
communication/marketing-team/role-handbooks/wip-roles.md

adding handbook templates for the upstream marketing team. 
Ideally, quick reviews/edits and then to merge and iterate. (and passing tests of course :p ) The leads and shadows for each functional area will complete the rest in later PRs.

adding handbook templates for marketing team 

---

github-management/subproject-site-requests.md

Netlify has switched their hosted site domain from .com to .app.
Example:
`kubernetes-foo.netlify.com` -> `kubernetes-foo.netlify.app`
This brings the guidelines in line with the new tld

Update netlify request guidelines to reference new netlify tld

---

sig-storage/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/1867
/cc @andyzhangx 
/assign @xing-yang @saad-ali @msau42 @jsafrane
/hold

sig-storage: add csi-driver-smb repo

---

contributors/devel/development.md

I used to maintain a [longer guide](https://github.com/PatrickLang/kubernetes-windows-dev#hacking-on-kubernetes-for-windows) explaining how to build Kubernetes binaries for Windows, using a Windows dev box. This is much easier now, so I would like to just clarify the missing steps in the official docs, instead of keeping my own guide.
Testing details are still at https://github.com/kubernetes-sigs/windows-testing

Clarify how to build using or targetting Windows

---

communication/slack-config/channels.yaml

Request for creating a new slack channel `seccomp-operator`.
This is a off-tree project to develop an operator to help users managing clusters that use custom seccomp profiles.
Topic: Seccomp operator - for easier management of seccomp profiles in Kubernetes.
N/A

Add new slack channel: seccomp-operator

---

communication/marketing-team/social-guidelines.md

per last [steering meeting](http://bit.ly/k8s-steering-wd) on April 6th, folks wanted clarity around KEPs being promoted on social channels. 
//also added: source of truth for the TODO
steering review timebox: sunday, april 26th @ 6am UTC. no comments = no issues.

adding steering kep guidelines for twitter

---

committee-steering/governance/sig-governance.md

Answers #4577 - issue has the where the new information came from (other gov doc sources), reformatting and taking out duplicate information preventing us from having to update in multiple places, and adding very minor content. It will be best to read the original doc first entirely and then the new doc so you can see how things have moved around.
Open-ended questions and discussions pulled from the comments:
- the term member is bloated and needs to be changed. most folks associate member with sig member/contributor and not a role regardless of whether the term member is defined here. 
https://github.com/kubernetes/steering/issues/160

adding more descriptive chair role and reformat

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

Please add a slack group for the [Velero](https://velero.io) maintainers.

Add a slack group for Velero maintainers

---

sig-architecture/production-readiness.md

Follow up to https://github.com/kubernetes/enhancements/pull/1620, this removes the questionnaire from here and notes that PRR is required in 1.19.

Update PRR process status

---

sig-contributor-experience/README.md
sigs.yaml

There was a permissions issue with the previous doc. This links to a copy with the correct permissions.

sig-contribex: update marketing meeting notes link

---

communication/slack-config/channels.yaml

This PR adds slack #jp-mentoring channel.
This channel is used for discussion and Q&A about mentoring in Japanese.
And also used for Q&A at Japan local upstream training.
NONE

Add slack #jp-mentoring channel

---

contributors/guide/contributor-cheatsheet/README-it.md
contributors/guide/contributor-cheatsheet/README.md
hack/.spelling_failures

Given that the number of Italian contributors is growing, especially on the website, I'm adding a localized version of the contributor cheatsheet to make it easier for new people to get started
Fixes https://github.com/kubernetes/website/issues/13998
/cc @sftim

Localize contributor cheatsheet to it

---

communication/slack-config/channels.yaml
incubator.md
sig-cluster-lifecycle/README.md
sigs.yaml

the repository is being archived. please see:
https://github.com/kubernetes/org/issues/1888
/kind cleanup
/priority backlog
/sig cluster-lifecycle
sig-cluster-lifecycle: remove kube-deploy from the list of projects
Remove:
- The sub-project from sigs.yaml
- The reference in incubator.md (also remove kubernetes-anywhere)
Mark the slack channel #kube-deploy as archived.
Leave the mentions and links in these outdated design documents:
- /contributors/design-proposals/cluster-lifecycle/local-cluster-ux.md
- /contributors/design-proposals/multi-platform.md
- /sig-cluster-lifecycle/migrated-from-wiki/roadmap-cluster-deployment.md

sig-cluster-lifecycle: remove references to kube-deploy

---

sig-api-machinery/README.md
sigs.yaml

For kubernetes/org#1895 (PR to add staging dir at kubernetes/kubernetes#91354)
/assign @deads2k @fedebongio @lavalamp 
cc @cheftako @andrewsykim 
/hold
for lgtm from sig-api-machinery leads

sig-api-machinery: add controller-manager repo

---

sig-storage/README.md
sigs.yaml

For https://github.com/kubernetes/org/issues/1887
/assign @saad-ali @xing-yang @msau42 @jsafrane 
/hold

sig-storage: add mount-utils repo

---

communication/slack-config/channels.yaml

From SIGHUP.io we want to include a new channel in the Kubernetes slack group.
The channel will be used to share experiences between Fury Distribution users.
Fury is a CNCF certified Kubernetes distribution crafted by SIGHUP -> https://landscape.cncf.io/selected=fury-distribution
In addition to the Distribution, the team is building OSS tools around Kubernetes.
https://github.com/sighupio
Thanks!

Add Fury slack channel

---

communication/slack-config/channels.yaml

Reverts https://github.com/kubernetes/community/pull/4794
The fury slack channel name clashes with a user of the same name. Channels and usernames share the same namespace and cannot co-exist. =/
ref: https://github.com/kubernetes/community/pull/3852

Revert "Add fury slack channel"

---

communication/slack-config/sig-release/config.yaml

This PR adds the missing slack channels of the sig-release's subprojects:
- release-bug-triage
- release-docs
- release-emeritus
/cc @kubernetes/release-managers @justaugustus 
Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

add missing channels of sig-release subprojects

---

communication/marketing-team/CHARTER.md
communication/marketing-team/README.md
communication/marketing-team/blog-guidelines.md
communication/marketing-team/role-handbooks/editor.md
communication/marketing-team/role-handbooks/internal-marketing.md
communication/marketing-team/role-handbooks/social-media.md
communication/marketing-team/role-handbooks/storytellers.md
communication/marketing-team/role-handbooks/wip-roles.md
communication/marketing-team/social-guidelines.md
communication/marketing-team/team-resources.md

This PR cleans up some of the Markdown formatting and links for the Contributor Marketing Team docs, and also adds @rajula96reddy as shadow for the internal comms role.

Clean up formatting and links for marketing team docs

---

communication/slack-config/channels.yaml

We have channels for these projects in our internal slack and allowed users to join after they asked for slack access. I got asked by several users if we could move the discussions to the k8s slack which makes a lot of sense, I think. 
About the projects:
- devspace: development tool for kubernetes, on GitHub: https://github.com/devspace-cloud/devspace
- kiosk: multi-tenancy extension for kubernetes, on GitHub: https://github.com/kiosk-sh/kiosk
The purpose of these channels will be to prioritize features together, answer questions about the projects, help users resolve issues quicker, and to provide a way to share experiences with these tools.
Thanks for reviewing this PR! Let me know if you need me to make any changes.

slack: add channels for projects devspace and kiosk

---

communication/calendar-guidelines.md

I noticed this morning when looking through our calendar guidelines. It currently says to share with community@kubernetes.io, however I think the new practice is to share with contributors@kubernetes.io. 
It might be best to update the guidelines to shift to asking contributors@kubernetes.io to create the shared calendar and share it out with the leads to ensure that it is owned by a community managed account.
@parispittman @castrojo what are your thoughts?
/assign @parispittman @castrojo

Update email address for calendar sharing permissions

---

communication/slack-config/channels.yaml

#4794 2nd attempt ;)
---
From SIGHUP.io we want to include a new channel in the Kubernetes slack group.
The channel will be used to share experiences between Fury Distribution users.
Fury is a CNCF certified Kubernetes distribution crafted by SIGHUP -> https://landscape.cncf.io/selected=fury-distribution
In addition to the Distribution, the team is building OSS tools around Kubernetes.
https://github.com/sighupio
Thanks!

Add fury-distribution slack channel

---

contributors/guide/pull-requests.md

Fixes #2050 
- This PR concerns with adding a section for `Git Commit Message`.

feat: Adding guidance on commit message style

---

contributors/devel/sig-instrumentation/migration-to-structured-logging.md

Ref https://github.com/kubernetes/enhancements/issues/1602
/cc @44past4 @brancz @DirectXMan12 @thockin
Wrote instructions for structured logging migration.

Add instructions for structured logging migration

---

sig-storage/volume-plugin-faq.md

Conflicting statement since the CSI implementation is now GA.
Please correct me if I'm wrong 😅

Removed outdated CSI limitation

---

sig-cluster-lifecycle/charter.md

- [1] Remove ownership of the upgrade / downgrade testing of k8s.
Now owned by SIG Cloud Provider / GCP as it only supports
GCP clusters. See:
https://github.com/kubernetes/kubernetes/tree/master/test/e2e/cloud/gcp
- [2] Remove the "lock-step" coordination with SIG-Release. Historically
the release waited for kubeadm to update its default k8s versions
constants after a "stable-1.x" label was created. No longer needed,
as kubeadm defaults to "stable-1":
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta2/defaults.go#L36
- [3] Add sig-scheduling mention under "Out of scope".
- [4] Add sig-apps mention under "Out of scope".
- [5] Add note about release "informing/blocking" test jobs.
NONE
/sig cluster-lifecycle
/priority …

sig-cluster-lifecycle: amend the SIG charter

---

communication/slack-config/sig-release/usergroups.yaml
communication/slack-config/users.yaml

- Update `release-managers` usergroup
- Reference existing members as Release Managers (ref: https://github.com/kubernetes/sig-release/pull/1106)
- Include [Release Manager Associates](https://git.k8s.io/sig-release/release-managers.md#associates)
- Add `release-team-leads` usergroup
Includes:
- Current (1.19) Release Team Lead and Lead Shadows
- SIG Chairs
/assign @tpepper @onlydole @mrbobbytables @jeremyrickard 
cc: @kubernetes/release-engineering @kubernetes/release-team-leads 
/sig release
/area release-eng

slack/sig-release: Update usergroups

---

contributors/guide/release-notes.md

This aims to address [#729](https://github.com/kubernetes/sig-release/issues/729) and provide details to users for the finalized version of [#81278](#https://github.com/kubernetes/kubernetes/pull/81278) as well as some other changes that have already taken place.
Still very much incomplete and a WIP.
/cc @saschagrunert  
@paulbouwer  
@cartyc  
@kcmartin 
@guineveresaenger

Updating Release Notes Document

---

contributors/devel/sig-release/cherry-picks.md
contributors/devel/sig-release/getting-builds.md
contributors/devel/sig-release/release.md

(Review is best done by individual commit here, since there are several format fixes.)
@joelsmith mentioned in [#release-management](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1591899387412000) that there were some broken links in the SIG Release docs.
This PR cleans that up.
/assign @tpepper 
cc: @kubernetes/sig-release 
/kind cleanup documentation
/sig release
/area release-eng release-team

devel/sig-release: Fixup links, Markdown warnings, minor content tweaks

---

events/community-meeting.md

For the most part this is a no-op and just applies the style guide suggestions to the doc. The one content change is this part in the beginning:
We have PUBLIC and RECORDED monthly meeting the third Thursday of the month at 10am PT a). There will be no community meeting in the month of December, or in a week that conflicts with KubeCon + CloudNativeCon.
to
We have PUBLIC and RECORDED monthly meeting the third Thursday of the month at 10am PT; with the exception of December, or in the event it clashes with KubeCon + CloudNativeCon.

Update formatting to community meeting doc

---

mentoring/programs/meet-our-contributors.md

For the most part this is a no-op and just adds the metadata  header and a few other small formatting fixes.
The only content change is the removal of this sentence:
```
Grab a copy of the calendar to yours from [kubernetes.io/community]
```
The link it references does not container a calendar event. ¯\\_(ツ)_/¯
Fixes #4790

Update formatting of meet our contributors doc

---

events/2020/03-contributor-summit/README.md
events/2020/07-contributor-summit/README.md
events/2020/11-contributor-summit/README.md

Finally closing this loop for EU2020.
While doing this, noticed @idealhack and @mrbobbytables weren't set as leads for their respective events and tossed that in as well. 
/assign @mrbobbytables @idealhack

Update 2020 Events w/ covid cancellations and event leads

---

contributors/devel/sig-testing/testing.md

Existing docs are wrong about using `go test ./...` from the Kubernetes repository root because:
1. it will try to run integration and e2e tests, not just unit tests
2. it will not discover packages in staging modules and those tests would not be run
...So it is not really equivalent to running `make test` which uses specific shell script code (see [hack/make-rules/test.sh](https://github.com/kubernetes/kubernetes/blob/b48f5af2602bf097c11c6a252bc7f82a7c096206/hack/make-rules/test.sh#L34-L60)) to be able to run only unit tests and to discover unit tests contained within staging modules.
Also, the mixing of `make test` and `go test` examples in the docs is a little confusing, so I made an attempt at simplifying the docs by consolidating the `go test` examples into a single "go test" …

Update Testing Guide to clarify how to use go test as an alternative to make test

---

OWNERS_ALIASES
sig-release/README.md
sigs.yaml

Discussed on the SIG Release [mailing list](https://groups.google.com/d/topic/kubernetes-sig-release/2VZndEcjPTo/discussion) and in today's SIG Release [meeting](https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit#heading=h.6hgnu9qtrd4o).
/assign @tpepper @calebamiles @alejandrox1 @saschagrunert 
cc: @kubernetes/sig-release 
/hold for lazy consensus (timeout: Thursday, June 18 at 4pm US Eastern)

sig-release: Add Jorge Alarcon Ochoa and Sascha Grunert as TLs

---

contributors/guide/README.md
contributors/guide/coding-conventions.md
contributors/guide/contributing.md
contributors/guide/contributor-cheatsheet/README.md
contributors/guide/expectations.md
contributors/guide/first-contribution.md
contributors/guide/getting-started.md
contributors/guide/github-workflow.md
contributors/guide/help-wanted.md
contributors/guide/issue-triage.md
contributors/guide/non-code-contributions.md
contributors/guide/owners.md
contributors/guide/pull-requests.md
contributors/guide/release-notes.md
contributors/guide/review-guidelines.md
contributors/guide/scalability-good-practices.md
contributors/guide/style-guide.md

The descriptions will be used on list pages within the contributor site to give a brief overview of the pages 👍 
/hold for review
ref: https://github.com/kubernetes/community/issues/4444

Add frontmatter descriptions to the contributor guide docs

---

contributors/devel/sig-release/cherry-picks.md
contributors/devel/sig-release/release.md

As of the KEP
https://git.k8s.io/enhancements/keps/sig-release/1498-kubernetes-yearly-support-period
becoming implementable for 1.19, we should note this change in the
developer guide description of the release process and lifecycle.

release docs: update 9 months to 1 year patch support

---

communication/slack-config/channels.yaml

We want to add a slack channel in the kubernetes slack group for ChartCenter.
ChartCenter is a free central repository for Helm charts:
https://chartcenter.io
https://github.com/jfrog/chartcenter

Add a slack channel for chartcenter

---

sig-contributor-experience/devstats/OWNERS

@LappleApple has been doing SO MUCH AMAZING WORK :rainbow: with devstats and k8s recently. This PR adds her as an approver for the devstats directory (we should have done this way earlier!).
Lauri, let's also try to document and get in some of the work you've done in this directory to improve visibility for all the hard work you've been putting in and to ensure that it doesn't get lost. :)
/hold 
for @LappleApple to confirm

devstats: add LappleApple as approver

---

sig-cluster-lifecycle/README.md
sigs.yaml

[Packet](https://www.packet.com/) would like to move the cluster-api-provider repository to kubernetes-sig.
Here you can find the request https://github.com/kubernetes/org/issues/1934

Add packet cluster-api-provider

---

communication/slack-config/channels.yaml

Most communication regarding to the CNCF sandbox project KubeVirt is
happening inside #virtualization. We are spending a lot of time also on
development and keeping our e2e tests stable. This creates a lot of
traffic which we don't think is good to have in #virtualization. We
therefore want to have a dedicated channel to discuss and reports issues
around code and CI.

Add kubevirt-dev slack channel

---

community-membership.md

We've had many issues opened in k/org where existing `kubernetes` org
members request membership to `kubernetes-sigs`. Under our current
policy, all members of `kubernetes` are implicitly eligible for
membership to `kubernetes-sigs` and don't require sponsorship.
In such cases, we usually ask them to create a PR directly or we create
one ourselves and let the requester lgtm it. To ease the often
unnecessary two step process, this commit updates community membership
guidelines to suggest creating PRs directly if they are existing
`kubernetes` members.
/assign @mrbobbytables @cblecker @spiffxp 
/hold 
for review

Update docs to suggest creating PRs in k/org for kubernetes members

---

communication/slack-config/restrictions.yaml

This allows localization channels to create an additional maintainers channel.
Ref #4918 
/cc @sftim @zacharysarah @jimangel @inductor

Update sig-docs channel restriction to allow maintainers channels

---

communication/slack-config/sig-docs/OWNERS

This auto adds the `sig/docs` label for changes in the [sig-docs/](https://github.com/kubernetes/community/tree/master/communication/slack-config/sig-docs) subdirectory.
/assign @sftim

Auto add a label for sig-docs changes

---

communication/slack-config/sig-docs/docs-channels.yaml

This PR adds slack #kubernetes-docs-ja-maintainers channel.
This channel is used for discussion and communication about localization of Japanese language, but specifically for its maintaining.
NONE

add sig docs ja maintainers

---

communication/slack-config/channels.yaml

The r/kubernetes subreddit has grown to over 45k subscribers and is loosely maintained by a small set of moderators that largely overlap with the Kubernetes Slack org.
This channel is being created to get our mod team organized about policies and enforcement, and to work towards sufficient quality and Code of Conduct enforcement to eventually become an "official" subreddit (should the community will it).
Signed-off-by: Greg Taylor <greg@gctaylor.com>

Add reddit-mods Slack channel

---

committee-steering/governance/sig-governance.md
committee-steering/governance/wg-governance.md
events/community-meeting.md

drawing out what the policy would look like if we were to reduce the community group requirement from quarterly to once a year. 
why?
- less than half of the groups we have meet this requirement now (and haven't for the last year); let's make it something that everyone can meet without being a burden
- addition of the annual report
- it's not possible to have all groups go even twice a year based on 12 meetings with 4 slots and 37 community groups. 
- the language in there now for how to meet the requirement with sending an update to k-dev or using the KubeCon update isn't straightforward and also paints a picture that we should change it
- most give updates at least one KubeCon a year

reducing update meeting policy

---

community-membership.md

This adds a section regarding the removal of inactive members from the Kubernetes Orgs.  It has previously been discussed in the contribex weekly meetings as well as the [mailing list](https://groups.google.com/d/msg/kubernetes-sig-contribex/ni3eCii3Mis/acUA7CE4CQAJ), and independently in the chairs and TLs meetings. A general announcement + following through with the org clean up will follow.
ref: https://github.com/kubernetes/community/issues/3179
/cc @cblecker @nikhita @spiffxp @idvoretskyi @fejta 
/hold
for comments from other members / steering as this impacts all community members.

Add section on inactive members to community membership guidelines

---

sig-cluster-lifecycle/postmortems/OWNERS

The single owner in this file has been [inactive](https://github.com/kubernetes/community/blob/master/community-membership.md#inactive-members) for some time (over 18 months with no devstats recorded activity) and is slated for removal (ref: https://github.com/kubernetes/org/issues/2013).
I don't think a new owner for this specific directory needs to be established, but if so I can leave it in place and amend it instead.

sig-cluster-lifecycle: remove outdated postmortems owners file

---

committee-steering/governance/sig-governance.md

As discussed in the last [public steering committee meeting on July 6th](https://docs.google.com/document/d/1qazwMIHGeF3iUh5xMJIJ6PDr-S3bNkT8tNLRkSiOkOU/edit), this PR adds an Unconscious Bias Training requirement for all leads to be completed 30 days within the date of their appointment.
An email will be sent with more details soon.
/hold
for reviews

Add Unconscious Bias Training requirement for all leads

---

communication/slack-config/channels.yaml

Adding a channel for users of GoDaddy's [Kubernetes External Secrets](https://github.com/godaddy/kubernetes-external-secrets) as discussed in the linked issue.
Fixes godaddy/kubernetes-external-secrets#388.

Add channel for external-secrets

---

communication/slack-config/channels.yaml

This PR archives the #sig-docs-security channel on Kubernetes Slack.
/sig docs

Archive sig-docs-security

---

communication/slack-config/channels.yaml
communication/slack-config/restrictions.yaml
communication/slack-config/sig-docs/docs-channels.yaml

After the following question on Slack I noticed the `sig-docs*` channels were still in the channels.yml even though sig-docs has its own subdirectory already.
https://kubernetes.slack.com/archives/CA1MMM1HU/p1594016729218100
/cc @sftim @zacharysarah @mrbobbytables

Move sig-docs channels to sig-docs/ subdirectory

---

contributors/devel/running-locally.md

Update required versions, fix a bunch of broken links, and generally normalize the way shell commands are referred to. In addition, stop assuming that anybody has `.` in their `$PATH` in recommended shell commands.
Note that I recorded many of these issues in a friction log (https://docs.google.com/document/d/18741pdPn74ykHODEcX11fS21rU3GpJM30yBbcP1akUk/edit?usp=sharing).

Clean up broken links and fix commands in "Getting started locally"

---

sig-node/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/1873
/assign @derekwaynecarr @dchen1107 
cc @saschagrunert 
/hold
for lgtm by sig node leads

sig-node: add seccomp-operator repo

---

communication/slack-config/restrictions.yaml
communication/slack-config/sig-storage/config.yaml

This PR adds a slack channel for the kubernetes-cosi subproject under sig-storage. We are having weekly design meetings and working on prototyping. We'd like to have a slack channel for communication.
https://github.com/kubernetes/community/tree/master/sig-storage#kubernetes-cosi
CC @saad-ali @msau42 @jsafrane @jeffvance

Setting up a slack channel for sig-storage subproject kubernetes-cosi

---

sig-testing/README.md
sigs.yaml

Naming is hard. This makes the resulting staging gcr.io repo project
hit the 30 character limit
ref: https://github.com/kubernetes-sigs/secret-sync-rotation/issues/3

Rename secret-sync-rotation to k8s-gsm-tools

---

sig-contributor-experience/README.md
sig-testing/README.md
sigs.yaml

The `repo-infra` repo exists as a subproject both in SIG Contribex and
SIG Testing. Given that the repo is more appropriate under SIG Testing,
removing it from SIG Contribex's list of subprojects.
contribex -> https://github.com/kubernetes/community/tree/master/sig-contributor-experience#repo-infra
testing -> https://github.com/kubernetes/community/tree/master/sig-testing#repo-infra
/hold
for ack from sig-testing leads and other sig-contribex leads
/assign @cblecker @mrbobbytables @castrojo 
contribex leads
/assign @spiffxp @BenTheElder @stevekuznetsov 
testing leads

Remove repo-infra subproject from sig-contribex, keep in sig-testing

---

sig-storage/README.md
sigs.yaml

For https://github.com/kubernetes/org/issues/2039
cc @brahmaroutu 
/hold
for lgtm from sig storage leads

sig-storage: add repos to kubernetes-cosi subproject

---

communication/marketing-team/storytelling-resources/example-interview-qs-sig-windows.md
communication/marketing-team/storytelling-resources/example-topics.md

Adding a folder with resources for storytellers within /kubernetes/community/communication/marketing-team/. Adding two md files - one with suggested topics when interviewing a SIG for a SIG profile blog post. One with an example set of questions used in the SIG-Windows profile blog post.
Fixes #4798

Adding a folder with example resources for storytelling.

---

communication/slack-config/usergroups.yaml

see:
- go.k8s.io/oncall
- https://github.com/kubernetes/sig-release/issues/1150

add group / alias entry for current google build admin oncall

---

communication/slack-config/channels.yaml

Signed-off-by: Raj Babu Das <raj.das@mayadata.io>
This channel is to go alongside the existing #litmus and should be managed the same way.
The intent with #litmus-dev is to provide separation of development-related discussions and other notification mechanisms to track changes from user queries and feature requests.

Adding litmus-dev channel to kubernetes slack

---

.github/ISSUE_TEMPLATE/marketing-request.md
communication/README.md
communication/calendar-guidelines.md
contributors/guide/contributor-cheatsheet/README-de.md
contributors/guide/contributor-cheatsheet/README-fr.md
contributors/guide/contributor-cheatsheet/README-hi.md
contributors/guide/contributor-cheatsheet/README-id.md
contributors/guide/contributor-cheatsheet/README-it.md
contributors/guide/contributor-cheatsheet/README-ja.md
contributors/guide/contributor-cheatsheet/README-ko.md
contributors/guide/contributor-cheatsheet/README-pt.md
contributors/guide/contributor-cheatsheet/README-uk.md
contributors/guide/contributor-cheatsheet/README-zh.md
contributors/guide/contributor-cheatsheet/README.md
events/community-meeting.md
mentoring/programs/README.md

This updates the process and all links referencing the community calendar.
The community calendar no longer needs to be manually added as a guest for meetings. It has been replaced by a named account (calendar@kubernetes.io) that has joined each community group mailing list and will auto-aggregate the events.
fixes #3467 
fixes #4903 
Resolves some items for annual maintenance - ref: #3717

Update calendar guidelines & links

---

contributors/guide/README.md

As the readme is now the entrypoint for the contributor guide on the contributor site, it needed some metadata to go along with it \o/
/assign @castrojo 
EDIT: Forgot to reference the issue where they were consolidated: https://github.com/kubernetes/community/pull/4876

Add description to contributor guide readme

---

wg-naming/governance.md

This PR adds a governance document to WG Naming, described in #4968.
/wg naming
/assign @celestehorgan @jdumars @justaugustus

Add governance.md to WG Naming

---

communication/moderators.md
communication/slack-config/OWNERS

This adds myself as [slack-config/](https://github.com/kubernetes/community/tree/master/communication/slack-config) OWNER. I have been (pro tempore) moderator since #3374 and would like to help out with this as well.
This can also help with response times since Ihor is the only EMEA approver right now.
/cc @mrbobbytables @idvoretskyi

Add rlenferink as slack-config owner

---

github-management/README.md

The GitHub Admin already confirmed with the old NMCs about stepping down due to lack of bandwidth and confirmed with the new NMCs that they'd like to take on this role.
@justaugustus @idealhack @nzoueidi this is a lot of chopping wood and carry water, thank you SO MUCH for all your work!
Congrats to @ameukam @palnabarun @savitharaghunathan! :tada: I'll reach out to y'all later about next steps. :)
/assign @cblecker @mrbobbytables 
/hold
@ameukam @palnabarun @savitharaghunathan For the record,  can you please confirm here that you'd like to take this role?

Update New Membership Coordinators

---

communication/slack-config/channels.yaml

Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
This PR adds new Kubernetes Slack channels `olm-dev` and `operator-sdk-dev`.
[Operator Lifecycle Manager](https://github.com/operator-framework/operator-lifecycle-manager) and [Operator SDK](https://github.com/operator-framework/operator-sdk) were recently accepted into CNCF as Incubating projects under Operator Framework.
We would like to encourage the community to participate more in the development activities of these projects, so we are moving our communication to open slack channels.
Many of our user questions are raised in the existing `kubernetes-operators` channel, so we do not currently see a need for any new user channels.

Add olm-dev and operator-sdk-dev channels to slack config

---

contributors/guide/README.md

I left the leading and trailing `---` to signify the top section is a metadata header in #4935 🤦  This fixes it.

Fix metadata header in contributor guide readme

---

committee-steering/README.md
sig-contributor-experience/README.md
sigs.yaml

Ref: https://groups.google.com/a/kubernetes.io/g/steering/c/Ph7j8r0L0rA
/assign @mrbobbytables @castrojo @cblecker 
/hold
to ensure lgtm from another contribex lead

Move kubernetes-template-project from steering to contribex

---

sig-storage/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/1563
external-storage has now been retired - https://github.com/kubernetes-retired/external-storage
for lgtm
/hold
for lgtm from sig-storage lead

sig-storage: remove kubernetes-incubator repos

---

committee-code-of-conduct/README.md
committee-code-of-conduct/charter.md

This PR:
- Adds a section to the Code of Conduct Committee's `README.md` file for emeritus members. We thank @jdumars, @Bradamant3, and @carolynvs for their service to the community! It also adds @parispittman to this list, so that the information in `sigs.yaml` and listed on `README.md` match. Thanks to you too, Paris!
- Adds members with a term ending August 7, 2022 to the team: @celestehorgan, @karenhchu and @tpepper 
- Links the `elections.md` document from `charter.md`, and removes the TODO in the charter, because cleanup.

[CoCC] Add section on emeritus members, link to elections.md

---

communication/marketing-team/README.md

Updating the README of the marketing team. Switching @kaslin to social media lead, indicating @chris-short and @parispittman as advisors. Fixing various grammar.

Adding @kaslin as social lead + grammar

---

contributors/guide/README.md
contributors/guide/contributor-cheatsheet/README.md

Adds aliases to the contributor guide and cheatsheet for use on the contributor website.
https://k8s.dev/guide -> contributor guide
https://k8s.dev/cheatsheet -> contributor cheatsheet

contributor guide: Add site aliases

---

contributors/guide/contributing.md
contributors/guide/pull-requests.md
contributors/guide/review-guidelines.md

reorganize pull request page.
The review-guidelines.md had duplicate content from pull-requests.md.  I've removed it so that the review guidelines only have things useful to reviewers and pull-requests.md now has all the tips for getting a good review in one place.
The nitty gritty details of how prow/tide merges PRs is useful, but not so much when you're doing a PR, so I moved it to the bottom of the document so that the PR tips and best practices are listed before them. 
And lastly I reformatted pull-requests.md to remove the confusing numerals (they'll look better in the ToC on the contributor site this way and also reformatted it with semantic line feeds, so sorry for the noise there. 
fixes: #4444

Deduplify content: Remove reviewee content from the review-guidelines

---

go.mod
hack/verify-generated-docs.sh

`make verify` was failing locally as follows
```
+ cleanup
+ rm -rf /var/folders/8g/47qms67d0_1361dcyx3cpt3h00jp2t/T/tmp.yiOM5On7
rm: /var/folders/8g/47qms67d0_1361dcyx3cpt3h00jp2t/T/tmp.yiOM5On7/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190409140830-cdc409dda467/decode_test.go: Permission denied
rm: /var/folders/8g/47qms67d0_1361dcyx3cpt3h00jp2t/T/tmp.yiOM5On7/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190409140830-cdc409dda467/emitterc.go: Permission denied
rm: /var/folders/8g/47qms67d0_1361dcyx3cpt3h00jp2t/T/tmp.yiOM5On7: Directory not empty
FAILED   verify-generated-docs.sh	4s
```
I was originally going to solve this by setting `GOFLAGS="-modcacherw"` to allow `cleanup`'s `rm -rf` to work.  That flag isn't available until go1.14, so I decided let's go ahead and upgrade to go1.15.
But on further …

Update to go1.15, fix local make verify

---

.github/ISSUE_TEMPLATE/support.md
contributors/guide/issue-triage.md

The upstream project isn't officially tied to Stack Overflow and we direct
folks to Discuss now.
related - https://github.com/kubernetes/kubernetes/pull/94131

Remove stackoverflow from support template response

---

contributors/guide/contributing.md

collab.md was removed in https://github.com/kubernetes/community/pull/4866 This updates it to the link we've been using in its place.

Fix broken link in contrib guide contributing doc

---

contributors/guide/owners.md

This is a no-op and a bit of a stop-gap fix. The contrib site importer can't process markdown links that span multiple lines at the moment.

Fix PR workflow link in contrib guide owners doc

---

communication/mailing-list-guidelines.md

No issue!
When creating WG naming I ran into a bit of frustration when creating mailing lists and adding calendar(s) and meetings to them. This is one part of a multi-part update, which makes mailing list creation guidelines more exact, particularly around setting permissions.
It removes the section on creating a mailing list moderation queue, as that is now handled by one explicit permission in the new UI. 
cc: @mrbobbytables, I'd appreciate your review on this. I copied the settings we used for WG Naming, but now would be a good time to canonical-ize what settings we want people to use in the new UI.
Cheers!
Celeste

Update mailing-list-guidelines for clarity, new UI

---

contributors/devel/README.md
contributors/devel/development.md

This covers E2E setup instructions for compiling Kubernetes locally on
Linux, Windows, and macOS workstations. There is also a substantial
rewrite of the instructions for running tests, along with relevant
links for more information.
fixes: #1644

Developer Guide End-to-end setup instructions for Linux, Windows, and macOS

---

communication/slack-config/channels.yaml
communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

This PR is to add a dedicated Slack Channel (`meetup-atlanta`) for the Kubernetes Atlanta Meetup group. This will help facilitate general communication with Meetup members, speakers, etc. and foster a more robust community. This also adds a Slack Usergroup (`k8satl-hosts`) to make it easy for users to address the Meetup hosts to recommend speakers, topics, and other related items.
**Relevant Links**
- Meetup Group: https://www.meetup.com/Kubernetes-Atlanta-Meetup/
- Meetup Youtube Channel: https://meetups.k8satl.io/videos/
- Meetup Notes: http://github.com/k8satl/meetups/

Add Slack Channel for k8satl meetup

---

communication/slack-config/channels.yaml

Request the slack channel for the `cluster-api-packet` similar that aws, azure, DigitalOcean have, to discuss subjects related to the CAPP
/cc @detiber

slack: add cluster-api-packet channel

---

contributors/design-proposals/architecture/resource-management.md

"KRM" is the term we have been using in practice. It was buried and/or implicit in this document. Making it more prominent and explicit to make it easier to find.

Make "Kubernetes Resource Model (KRM)" more prominent

---

communication/slack-config/channels.yaml

This channel is intended to be used for routing of alerts that
affect tests running for the cluster-api-provider-aws subproject.
These alerts are currently routed to test-infra-oncall, and this will
allow for the alerts to be routed to the community members that are
more likely able to take action on the alerts.

Add a slack channel for cluster-api-aws-alerts

---

communication/slack-config/channels.yaml

The service binding project aims to be a community-driven project to define and implement a Service Binding API for binding kubernetes workloads with services.
It would be moved to a neutral org shortly.
https://github.com/redhat-developer/service-binding-operator

Add channel for public service binding conversations

---

sig-wg-lifecycle.md

Updating sig-wg-lifecycle.md to include the new label request process
Fixes #

Updating sig-wg-lifecycle.md to include the new label request process

---

contributors/devel/sig-testing/e2e-tests-kubetest2.md

This change creates a new file with e2e testing documentation for the
new kubetest2 test runner. Once kubetest is retired, this can drop
right into the existing e2e developer guide docs.
Fixes #

Developer Guide: Refresh e2e testing documents for kubetest2

---

contributors/devel/development.md

This clears up some stale information, links to some new resources, and includes a pretty important missing step: the Google Cloud CLI. This is a follow-up to notes on https://github.com/kubernetes/community/pull/5003

Developer Guide: Followup to correct stale information, missing step

---

committee-steering/governance/sig-governance.md

The KEP link was broken - it led to a 404 Not Found on GitHub.  I'm proposing to replace it with the KEP template link taken from the kubernetes/enhancements/ document found at https://github.com/kubernetes/enhancements/tree/master/keps.  The new link is https://github.com/kubernetes/enhancements/tree/master/keps/NNNN-kep-template/README.md.
Fixes #

Fixing broken link for KEP

---

sig-release/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2172
/assign @justaugustus 
/hold
for lgtm from sig-release leads

sig-release: add zeitgeist

---

communication/slack-config/channels.yaml

This allows developers and maintainers of https://github.com/prometheus-operator to communicate in an open channel, and the current prometheus-operator channel is left for user questions and support.
If I understood the docs this is all I need to do to create a new channel. Let me know if I missed something, thanks! :)

communication/slack-config/channels.yaml: Add prometheus-operator-dev

---

events/elections/2020/README.md

Adding missing folks whose bio is committed and alphabetizing list.

2020 steering election: fix up candidate index

---

events/elections/2020/voters.md

Voter was intended to be added on 9/3, but was omitted due to a paste-o
/assign jdumars idvoretskyi 

Fix voters list to included previously approved voter.

---

contributors/devel/sig-testing/writing-good-e2e-tests.md

This change updates the link to reboot.go as it has moved to the
`test/e2e/cloud/gcp` directory of the kubernetes repository.

update link to reboot test in writing good e2e tests doc

---

communication/slack-config/sig-docs/docs-channels.yaml

None
During the Sig Docs meeting today (20200915), the team decided to archive this channel in favor of #release-docs channel. 
#release-docs channel will be used by the release docs team to communicate with each other and Sig Release on ongoing efforts related to the current release.
#sig-docs channel will be used to communicate with Sig Docs team as intended which includes asking for reviews/help related to the release.
This decision was made to reduce duplicate channels that exist currently and to add clear purpose to the channels used by the release docs team.
cc @kubernetes/sig-docs-leads

Archive sig-docs-release channel in favor of release-docs channel

---

communication/slack-config/restrictions.yaml
communication/slack-config/sig-release/usergroups.yaml
communication/slack-config/users.yaml

- Add Lauri to teams
- Update Release Manager membership (ref: https://github.com/kubernetes/sig-release/issues/1226, https://github.com/kubernetes/sig-release/issues/1227)
- Rotate Release Team Leads (ref: https://kubernetes.slack.com/archives/C2C40FMNF/p1600212320332200?thread_ts=1600212056.329700&cid=C2C40FMNF)
- Add sig-release-leads group
/assign @tpepper @alejandrox1 @saschagrunert @LappleApple @mrbobbytables 
cc: @kubernetes/release-team-leads @kubernetes/release-engineering

slack-config/sig-release: Update teams

---

sig-wg-lifecycle.md

A hyphen in " Migrate/Remove/Deprecate any SIG/WG labels in labels.yaml; find instructions in [labels.md]" broke Markdown rendering. This corrects that.

Correct a markdown bug introduced in previous commit

---

committee-code-of-conduct/governance/onboarding-offboarding.md

Document the (known) onboarding and offboarding procedures for Code of Conduct Committee members
Fixes https://github.com/kubernetes/community/issues/3954
cc: @tpepper @karenhchu @AevaOnline @tashimi – please check this for completion!

Add onboarding and offboarding procedures for cocc members

---

sig-architecture/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2231
/hold
for sig-arch leads to lgtm
/assign @dims

sig-arch: add component-helpers repo

---

contributors/devel/sig-node/e2e-node-tests.md

Added documentation around the `--focus` and `--skip` arguments and documentation when using the `tests` image configuration field. Also included a short summary of `Testgrid`.
Resolves #4795.

Updated e2e node test docs

---

communication/slack-config/channels.yaml

Hi there -
We (@cfryanr and @mattmoyer) would like to create a Kubernetes Slack channel for our project, Pinniped.
* Pinniped is an new project that will be open sourced in the coming weeks.
* Pinniped provides identity services to Kubernetes.
* We realize that we don't have any links to our project to share right now, but our hope is that we can go ahead and start the process of creating a Kubernetes Slack channel so that we can have a Slack channel as close to release as possible.
* Pinniped development is sponsored by VMware, Inc.
None.

Request pinniped Slack channel

---

communication/slack-config/channels.yaml
sig-node/README.md
sigs.yaml

Renaming the operator to it's new proposed name.
Refers to https://github.com/kubernetes/org/issues/2177

Rename seccomp-operator to security-profiles-operator

---

communication/slack-guidelines.md

Sometimes there's some confusion as to when/how/if a project should ask for a slack channel on the K8s slack. We never really wrote that down so I took some of the excellent recommendations from @jdumars from this issue and wrote them down: https://github.com/kubernetes/community/pull/5107
I'm adding a hold since I'm sure I've missed some of the other things we look for in channel creation to give other people a chance to weigh in. 
/hold
/cc @jdumars 

Document slack channel creation for other projects

---

.github/ISSUE_TEMPLATE/support.md
contributors/guide/issue-triage.md

The label triage/support has been reclassified as kind/support. The
kind/* family of labels makes more logical sense, as they describe the
"kind" of thing an issue or PR is.
For more information, see the announcement email:
https://groups.google.com/g/kubernetes-dev/c/YcaJpsjjLKw/m/i15cLLx5CAAJ

Update triage/support label references to kind/support

---

communication/mailing-list-guidelines.md

Fixes #5169 
- Adds wording about subprojects
- Tries to standardize the "mailing list" vs "Mailing list" vs "Mailing List" and "google group" vs "Google Group" capitalization
- Adds a table of contents for easy navigation (and fixes some of the heading order issues, e.g. "Archive a mailing list" was nested under "Sharing the meeting notes")
Let me know if this should be in separate PRs instead - I realised afterwards that I ended up touching most of this file aha.

Update mailing list guidelines for subprojects

---

committee-steering/README.md
sigs.yaml

Update sigs.yaml to show that steering meets once a month publicly, and once a month privately

Update SC meeting times

---

contributors/devel/sig-testing/flaky-tests.md
contributors/guide/contributing.md
contributors/guide/contributor-cheatsheet/README-de.md
contributors/guide/contributor-cheatsheet/README-fr.md
contributors/guide/contributor-cheatsheet/README-hi.md
contributors/guide/contributor-cheatsheet/README-id.md
contributors/guide/contributor-cheatsheet/README-it.md
contributors/guide/contributor-cheatsheet/README-ja.md
contributors/guide/contributor-cheatsheet/README-ko.md
contributors/guide/contributor-cheatsheet/README-pt.md
contributors/guide/contributor-cheatsheet/README-uk.md
contributors/guide/contributor-cheatsheet/README-zh.md
contributors/guide/contributor-cheatsheet/README.md
sig-testing/charter.md

Velodrome no longer exists [[1]](https://github.com/kubernetes/test-infra/pull/18404) [[2]](https://github.com/kubernetes/test-infra/issues/16836)
I was looking at the [flaky tests](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md) page that @k8s-ci-robot links to and saw that we are still linking to it for assistance in triaging flaky tests.

Remove references to velodrome

---

communication/slack-config/channels.yaml

`cluster-api-provider-nested` was approved in https://github.com/kubernetes/org/issues/2247
Signed-off-by: Chris Hein <me@chrishein.com>
/cc @parispittman @Fei-Guo

Add cluster-api-nested Slack channel

---

communication/slack-config/sig-network/config.yaml

Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>
Adds the sig-network-policy-api slack channel for the sig-network network policy evolution subproject.

Add sig-network-policy-api slack channel

---

committee-steering/README.md
sigs.yaml

For https://github.com/kubernetes/steering/issues/185
Ref: https://github.com/kubernetes/steering/pull/187
This should make it more APAC/EU friendly too.
/hold
until https://github.com/kubernetes/steering/pull/187 merges

Update steering committee meeting time to 9:30am PT

---

communication/slack-config/channels.yaml

N/A
First of all! Hi!
We're a project called `odo` located here:
https://github.com/openshift/odo
**Information about us:**
We're an open source project that focuses on specifically on Kubernetes.
We also add support for other Kubernetes-based platforms, but our main
focus in k8s.
In a nutshell, odo is a tool that abstracts specific Kubernetes concepts
for an easier deployment of applications.
Our site is located here: https://odo.dev/ if you'd like to try it out!
**Purpose of the channel:**
For the past.. about a year. We've been using our own public slack channel
located here: http://openshiftdo.slack.com/
We have 100+ members and we're constantly chatting. Our motivation to
join kubernetes.slack.com is because well.. most of us are already on
the …

Add a #odo channel on the Kubernetes Slack

---

communication/slack-config/channels.yaml

New slack channel for discussions for the tooling working group in sig-security.

Adding sig-security-tooling slack channel

---

communication/slack-config/channels.yaml

Request the slack channel for the `cluster-api-gcp` similar that aws, azure, DigitalOcean have, to discuss subjects related to the CAPG and trying to back that project back on track 👍 
/assign @mrbobbytables @castrojo @nikhita 
@rsmitty FYI as we discussed in slack
Fixes n/a

slack: add cluster-api-gcp channel

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

N/A
**Channel:**
`#odo`
**Request:**
We'd like to be able to have the ability for users to ping `odo-devs` in
the channel in order to contact maintainers.
I have gone through each user's GitHub / Slack ID and added it to
`users.yaml` and created a new users group.
Many thanks!
Signed-off-by: Charlie Drage <charlie@charliedrage.com>

Add odo-devs user group

---

contributors/devel/sig-testing/flaky-tests.md

This updates flaky-tests.md with all of the great information from @liggitt's presentation to SIG Testing found here: https://www.youtube.com/watch?v=Ewp8LNY_qTg
Fixes #

Add Deflaking tests information to Developer Guide

---

contributors/chairs-and-techleads/technical-lead.md

This commit adds a role description for technical leads in the
Kubernetes community.
None
/cc @mbbroberg @justaugustus @alejandrox1 @LappleApple @parispittman

Add technical lead role description

---

wg-naming/language-evaluation-framework.md

Add the first version of the language evaluation framework.

WG Naming: Add language evaluation framework

---

committee-steering/governance/sig-governance.md
contributors/chairs-and-techleads/technical-lead.md

This links both documents together to enhance their visibility.
None
Follow-up of https://github.com/kubernetes/community/pull/5179

Link technical lead role description in sig-governance

---

sig-contributor-experience/charter.md

The weekly meetings are moved to monthly. Let's keep reference generic in case
the meeting time change in future.

Update community meeting reference

---

communication/slack-config/channels.yaml

The channel was dedicated to the development of the ELK helm chart. The
original maintainers have discussion back to the main charts channel.
For more info see this: https://kubernetes.slack.com/archives/C4M06S5HS/p1578279465008900

slack: archive elk-charts channel

---

communication/slack-config/channels.yaml

New slack channel for discussions for the security docs sub-project in sig-security 🎉 
cc: @IanColdwater @tabbysable

Adding sig-security-docs slack channel

---

contributors/devel/sig-release/getting-builds.md
contributors/devel/sig-release/kubernetes-versions.md

Part of https://github.com/kubernetes/sig-release/issues/850.
/assign @saschagrunert @cpanato @hasheddan @xmudrii 
cc: @kubernetes/release-engineering

sig-release: Add doc on version markers (migrated from k/test-infra)

---

wg-naming/OWNERS

I noticed in https://github.com/kubernetes/community/pull/5211 that @kubernetes/wg-naming-leads don't have approval powers over our directory, so let's fix that!
/assign @jdumars

[WG Naming] Add OWNERS

---

sig-contributor-experience/README.md
sigs.yaml

Moving to a new google document, the old one had google-only permissions, this new one is owned by contributors@kubernetes.io so we're all set
/cc @mrbobbytables @cblecker

Update location of SIG Contribex meeting notes

---

communication/slack-config/channels.yaml

This PR contains a new Slack channel request for Crossplane (https://crossplane.io/), a [CNCF Sandbox project](https://www.cncf.io/sandbox-projects/) that allows you to manage any infrastructure your applications need directly from Kubernetes.
The channel will be used for general discussion about the project, answering questions from Kubernetes community users that are interested in Crossplane, and supporting/troubleshooting issues from adopters.
The proposed channel name is #crossplane.

slack: add #crossplane slack channel for crossplane.io

---

github-management/kubernetes-repositories.md

I'm not sure if we need additional approvals for adding a new rule here (steering sign off?)...this PR is retroactively adding a rule which we follow today anyway.
To be clear, template files like `OWNERS`, etc can be added post-migration but it's usually easier to migrate repos when everything has been setup. It also signals that the repo donor is opting into the Kubernetes Code of Conduct.
/hold
for approval from GitHub admins
/assign @cblecker @mrbobbytables @spiffxp 
/cc @kubernetes/owners

github-management: add rule for template files for donated repos

---

wg-naming/workflow.md

Rough draft of the workflow to propose naming recommendations to @kubernetes/wg-naming.
(Note that this will eventually link out to content from https://github.com/kubernetes/community/pull/5206 and https://github.com/kubernetes/community/pull/5207, so certain links may be broken until they merge.)
/wg naming

wg-naming: Add workflow for proposing recommendations

---

wg-naming/recommendations/master-control-plane.md

This attempts to use the in-progress recommendation template from https://github.com/kubernetes/community/pull/5206
I don't think this satisfies all of the requirements of the proposed ADR form set forth in the proposed workflow from https://github.com/kubernetes/community/pull/5211
I started with a set of guidelines I put together for consistency in reviewing and making changes to use of the term master in testing code: https://github.com/kubernetes/kubernetes/issues/94901#issuecomment-705794619
I don't like where this is at but I am spinning my wheels. I would like some help or suggestions on how to make this clearer, and to satisfy the goals of WG Naming.
/wg naming
/sig testing
/priority important-soon

Try recommending alternatives to master

---

sig-node/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2302
/assign @derekwaynecarr @dchen1107 
fyi @swatisehgal
/hold
for lgtm from sig-node leads

sig-node: add noderesourcetopology-api repo

---

contributors/chairs-and-techleads/leadership-changes.md

Fixes https://github.com/kubernetes/steering/issues/179
This PR adds a light-weight process for proposing changes to SIG/WG/UG leadership. This will help in creating a consistent process for feedback from the community around leadership changes.
/hold
for review + steering approval

Document process for proposing changes to SIG/WG/UG leadership

---

contributors/devel/sig-architecture/api-conventions.md

Also clarify the use of proper names and acronyms within constants with
examples from existing use cases.
This was triggered by API review of kubernetes/kubernetes#92967 and discussion
in Slack where we realized our rules were insufficiently vague. This
normalizes constant naming for the full API surface area and clarifies rules.

api-conventions: Clarify that constant rules apply to flags and config

---

sig-instrumentation/archive/meeting-notes-2016.md
sig-instrumentation/archive/meeting-notes-2017.md
sig-instrumentation/archive/meeting-notes-2018.md
sig-instrumentation/archive/meeting-notes-2019.md

Doing a little housekeeping. Similar to #3074, converted the [SIG Instrumentation Meeting Notes] from 2016-2019 to markdown and am committing here for a git record using the docs -> markdown gdocs addon.
/cc @logicalhan @brancz @dashpole 
[SIG Instrumentation Meeting Notes]: https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#

Add sig-instrumentation meeting note archive

---

communication/slack-config/channels.yaml

The channel used to be used for coordination on client-go documentation improvement. It has not been used in quite a while and can be archived. (See [relevant Slack discussion](https://kubernetes.slack.com/archives/C86T1T737/p1605167908017000).)
/cc @sttts

Archive client-go-docs channel

---

communication/README.md
communication/website-guidelines.md

Added a brief policy on use/duration of the website banner for community statements as discussed in steering. I wasn't quite sure where this belonged, but under "communication", peer to mailing list / slack / discuss / social media guidelines seemed reasonable. All suggestions on location and phrasing welcome.
Also linked to existing sig-docs website content/style guides, and the blog subproject / contribution page.
/cc @cblecker @derekwaynecarr @dims @mrbobbytables @nikhita @parispittman
steering:
sig-docs chairs:
sig-docs tech leads:

Add website guidelines

---

communication/slack-config/restrictions.yaml
communication/slack-config/sig-release/usergroups.yaml
communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

SIG Release updates as described in https://github.com/kubernetes/sig-release/pull/1331.
Also adds two new usergroups:
- `security-release-team`: @kubernetes/release-managers + @kubernetes/product-security-committee 
- `product-security-committee`: https://github.com/kubernetes/security/#product-security-committee-psc
as requested by @tallclair. 
PSC Associates were purposely left off these groups, but can be added at a later time.
/assign @hasheddan @saschagrunert
cc: @kubernetes/sig-release-leads

slack-config: Update SIG usergroups + add PSC groups

---

communication/slack-config/OWNERS
communication/slack-config/users.yaml

A while back at the last Slack admins meet, we discussed moving some non-primary admins to be 'primary' admins. I don't think this was ever put into effect though, so thought I'd open up a PR to add myself as an approver so I can help within this repo too 😄
There's also a Google Sheet that lists all the admins that'll need updating too, which I'll go take a look for after this has been reviewed/accepted 🙂

Add munnerz as a primary admin/approver

---

communication/slack-config/channels.yaml

This requests a new channel for kubeinit, which is an Ansible collection
designed to deploy multiple Kubernetes distributions on top of multiple
infrastructure platforms.
The tool also allows to easily create kubernetes clusters either using
kubeadm, openshift/okd, rancher or canonical kubernetes with the idea to
extend it to other kubernetes distributions and deployment tools,
hence the request to host it here.
Also this Ansible collection helps potential new users to understand
the different components required to deploy production ready clusters.
The project's repository is hosted at https://github.com/kubeinit/kubeinit
Fixes #

Add kubeinit channel

---

communication/slack-config/channels.yaml

Adds a dedicated channel for Hetzner (https://www.hetzner.com/cloud).
This is a popular cloud provider with attractive prices.
Currently no managed Kubernetes service, it's in the work.
But they do provide:
https://github.com/hetznercloud/hcloud-cloud-controller-manager
https://github.com/hetznercloud/csi-driver
to support K8S on their cloud.
I came across Hetzner multiple times in other channels, so I think it could use a dedicated channel.

Add Hetzner to channels

---

sig-api-machinery/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2350
/assign @lavalamp @deads2k @fedebongio 
sig-api-machinery leads
/hold
for lgtm by apimachinery leads

sig-api-machinery: add kubectl-check-ownerreferences repo

---

hack/verify-steering-election.sh

The steering committee election [policy](https://github.com/kubernetes/community/tree/master/events/elections/2020#candidacy-process) states that all bios must be
limited to 300 words. This commit adds a verify script to check this.
Some bios from 2017-2020 exceed this limit so the script explicitly
avoids looking at the past elections.
---
This is a follow-up from the 2020 election [retro](https://docs.google.com/document/d/1xLs1PLoPDXHZAgImNHTiepn_f7-k5HjsCZqaozgFLzI/edit?usp=sharing).
as contribex TL for lgtm
/hold 
for cblecker to ack
cc @kubernetes/steering-committee @jberkus @jdumars @idvoretskyi

Add verify script to limit SC election bios to 300 words

---

events/2020/11-contributor-summit/README.md

Mostly just for future reference, all messaging has been using the contrib site links already.

📝 Update contributor summit/celebration doc with links to the actual event page

---

communication/marketing-team/README.md

I was struggling to find the right meeting, I eventually found it at the big [kubernetes calendar](https://calendar.google.com/calendar/u/0/embed?src=calendar@kubernetes.io) after Matt Broberg gave me the time for it.  This update should make it easier to find. 
I believe the meetings link should have been to the `#contributor-comms anchor`, so I updated that too, let me know if I'm wrong.
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>

Updating meeting details

---

sig-storage/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2371
kubernetes-csi/csi-driver-fibre-channel was surprisingly not in sigs.yaml in the first place...
/assign @msau42 @xing-yang 
/hold
until repos are actually archived

sig-storage: remove k-csi/csi-driver-flex repo

---

communication/slack-config/channels.yaml

open-cluster-management is a project focused on enabling end-to-end visibility and control across Kubernetes clusters.
https://github.com/open-cluster-management/community
The open-cluster-management architecture uses a hub - agent model. The hub centralizes control of all the managed clusters. An agent, which we call the klusterlet, resides on each managed cluster to manage registration to the hub and run instructions from the hub.
It is available under the Apache 2.0 license.
The channel name `open-cluster-mgmt` is chosen due to the character limit.

New slack channel for open-cluster-management

---

.github/ISSUE_TEMPLATE/survey-request.md
communication/requesting-survey.md

This PR is to address #3281 by giving instructions on requesting a community survey from ContribEx.
Please review.  One unresolved question: how do we want to flag survey requests?  In this draft, I specify the addition of an `area/survey` label, but we could potentially do it some other way.
I would also like to get this page on the Contributor Site, but that will require enabling the whole directory for that site.
attn: @mrbobbytables @parispittman @kaslin @mbbroberg

Add draft of instructions on requesting a survey.

---

contributors/devel/sig-instrumentation/instrumentation.md

This is a follow-up to https://github.com/kubernetes/enhancements/pull/1916, which added kube_* prefixed metrics to the scheduler.  The kube_* prefix was first used in Kube-state-metrics, and the linked KEP expanded the use of the prefix beyond a single component.
My primary motivation is to capture the discussions that have been had over the past few months, and make sure that we keep metrics in-line with our naming guidelines.
Some of the related discussion threads: 
https://github.com/kubernetes/kubernetes/pull/94866#discussion_r520884815
https://github.com/kubernetes/kubernetes/pull/95839#issuecomment-724197407
https://github.com/kubernetes/enhancements/pull/1916#discussion_r498559514
I realized there can be naming collisions if there are controllers …

Add exception for metric component prefixes for object metrics

---

sig-cluster-lifecycle/README.md
sigs.yaml

https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/OZPzQ5Niofc/m/oWHWDp7iBQAJ
```
The above PR also removed "sig-cluster-lifecycle-pr-reviews" as it was
matching the main "sig-cluster-lifecycle" team and updated the list of
active contributors in it.
```
@kubernetes/sig-cluster-lifecycle-pr-reviews - PR Reviews 
this is removed.

cleanup pr-review team for cluster-lifecycle

---

sig-architecture/production-readiness.md

Update the PRR policy to make approval required in 1.21 and later.

Make PRR approval required

---

generator/list.tmpl
sig-list.md

Removes the term `Master` from the sig-list template. I think just spelling it out is good enough, but also open to other suggestions.
Looping in wg-naming
/cc @celestehorgan @zacharysarah @justaugustus @jdumars 
/assign @nikhita @cblecker 
/hold

Replace master list with community group name in sig-list template

---

contributors/devel/sig-architecture/platforms.md

This outline should help contributors to get an idea about what needs to be done to add additional supported platforms to Kubernetes.
Supersedes https://github.com/kubernetes/community/pull/5014
- Went from `architectures` to `platforms`, which should not cover operating systems as well.
- Removed the `TODO` list since I think this is now covered
- Addressed previous review comments but tried to be not too specific for this short abstract.
I tried to not change too much of the document to still preserve the outlined style.
PTAL @dims @justaugustus @tpepper @LappleApple

Add guide for shipping alternative platforms

---

contributors/devel/sig-architecture/api-conventions.md

Updates the examples for `List` types to be de-pluralized since I think they are meant to be directly referencing the actual API objects of [PodList](https://github.com/kubernetes/api/blob/4a626d306b987a4096cf0784ec01af1be2f6d67f/core/v1/types.go#L3688), [ServiceList](https://github.com/kubernetes/api/blob/4a626d306b987a4096cf0784ec01af1be2f6d67f/core/v1/types.go#L4344), and [NodeList](https://github.com/kubernetes/api/blob/4a626d306b987a4096cf0784ec01af1be2f6d67f/core/v1/types.go#L4933).  
Also add a link to the existing field selector documentation as done for label filtering to satisfy the TODO.

Correct list api examples and add link to field selector documentation

---

sig-cluster-lifecycle/README.md
sigs.yaml

Update CAPI, CAPA notes doc URLs due to VMware G Suite data migration.
Fixes #

Update CAPI, CAPA notes doc URLs

---

contributors/devel/sig-architecture/api-conventions.md

This adds an entry for `DELETE` on a list of resources that matches the `GET` on a list of resources.
Also changes ampersand(`&`) to a question mark(`?`) on what since it is the start of a url query.

Add an entry for `DELETE` on a collection of resources.

---

sig-node/README.md
sigs.yaml

Currently recording url points to an old 2017 meeting recording and list, This PR updates it to point to list only.

Update sig-node meeting recording url to point to recording list 

---

communication/slack-config/sig-release/usergroups.yaml
communication/slack-config/users.yaml

Add 1.21 RT Leads to `release-team-leads` Slack usergroup.
Thank you @jeremyrickard for your service as the 1.20 Release Team Lead. ❤️ 
ref: https://github.com/kubernetes/sig-release/issues/1404
/assign
/sig release
/assign @justaugustus @saschagrunert @jeremyrickard @hasheddan @alejandrox1
/cc @kikisdeliveryservice @savitharaghunathan @bai

slack-config: add 1.21 RT Leads to the release-team-lead usergroup

---

sig-testing/README.md
sigs.yaml

kubetest2 was moved out of test-infra in https://github.com/kubernetes/test-infra/pull/18567
/cc @spiffxp @BenTheElder

Remove lingering references for test-infra kubetest2

---

contributors/devel/sig-architecture/api-conventions.md

Fixed the API Group convention for readability.
Fixes API Group description for readability.

Minor corrections to the api conventions.

---

wg-naming/recommendations/002-blacklist-whitelist-allowlist-denylist.md

This PR adds a recommendation to remove blacklist/whitelist from codebases and replace with allowlist/denylist.
Unblocks the following issues by adding a formal recommendation (i.e, work can be done):
https://github.com/kubernetes/test-infra/issues/19264
https://github.com/kubernetes/kubernetes/issues/90277
/assign @justaugustus @zacharysarah @jdumars

[WG Naming] Make recommendation for allowlist/denylist

---

contributors/devel/sig-architecture/vendor.md
sig-release/README.md
sigs.yaml

Ref: https://github.com/kubernetes/sig-release/pull/1412#discussion_r556191521
/cc @dims @justaugustus @saschagrunert @hasheddan @alejandrox1

Remove licensing subproject, move doc to vendor.md

---

sig-architecture/production-readiness.md

This updates the production readiness process based upon the discussion in the latest leads meeting.
/assign @wojtek-t @deads2k @mrbobbytables 
/cc @ehashman @kubernetes/enhancements 
/hold for lazy consensus until 4pm Pacific time, January 20th.

Update PRR description based on community feedback

---

sig-scalability/README.md

Signed-off-by: Madhav Jivrajani <madhav.jiv@gmail.com>
FIxed broken link in `sig-scalability/README` by changing `.blogs/k8s-services-scalability-issues.md` --> `./blogs/k8s-services-scalability-issues.md`
Fixes #5422

Fix broken link in sig scalability README

---

sig-storage/archive/README.md
sig-storage/archive/meeting-notes-2016.md
sig-storage/archive/meeting-notes-2017.md
sig-storage/archive/meeting-notes-2018.md
sig-storage/archive/meeting-notes-2019.md

Following practices used by other SIGs, this archives the old meeting
notes from the Google Doc into the repo for historical reference.
After this is merged, the logs can be cleaned up from the working
document to keep its size small, and a link will be added to the bottom
of the doc to point to this archive for anyone that needs to look for
past discussions.

Archive SIG Storage meeting notes

---

sig-release/charter.md

This patch updates the SIG Release charter to reflect the current
organizational structure.
Closes https://github.com/kubernetes/sig-release/issues/378
/cc @spiffxp @kubernetes/sig-release-leads

Update SIG Release charter to reflect latest changes

---

sig-node/README.md
sigs.yaml

The node-api content has since been moved to k8s.io/api. This updates
the links to the node-api OWNERS to point the current location.
See https://github.com/kubernetes/kubernetes/pull/87503 for more background.

Update sig-node node-api references

---

events/elections/2021/OWNERS
events/elections/2021/README.md
events/elections/2021/biotemplate.md
events/elections/2021/templates/election-templates.md
events/elections/README.md

This is a follow-up from the 2020 election [retro](https://docs.google.com/document/d/1xLs1PLoPDXHZAgImNHTiepn_f7-k5HjsCZqaozgFLzI/edit?usp=sharing). This PR only updates the election policy. It does NOT update the Election Committee guide. I have created an issue for updating the guide - https://github.com/kubernetes/steering/issues/190.
The first commit initializes the docs based on the 2020 docs. The second commit has updates based on the retro. Mainly:
- Move nomination and endorsement process to GitHub issues
- Clarify criteria for voter exemption forms
- Clarify word limit restriction for candidate bios
- Clarify that the EC updates the candidate index list in the README
- Update schedule to include:
- Selection of EC by the SC
- Move deadline for voter exemptions few days before …

Initialize 2021 Steering Committee Election docs

---

contributors/devel/sig-instrumentation/migration-to-structured-logging.md

Signed-off-by: chymy <chang.min1@zte.com.cn>
Fix klog.Infof change to klog.Infof err, should be klog.InfoS
Fixes #

Fix klog.Infof change to klog.InfoS err

---

mentoring/programs/the1-on-1hour.md

corrected path for mentor-guide.md

---

sig-instrumentation/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2182
/assign @ehashman @logicalhan @brancz @dashpole 
cc @s-urbaniak @lilic @DirectXMan12 
/hold
for lgtm from sig-instrumentation leads

sig-instrumentation: add prometheus-adapter repo

---

communication/slack-config/channels.yaml

Two updates: 
- The `#sig-contribex-triage` channel has not been used in some time, and that initiative has largely been spun down.
- The `#sig-contribex-meetings` channel is being added for our bi-weekly slack meetings with the intent of keeping the convos prominent and focused. If it doesn't pan out, the channel can be archived at a later date.
/assign @nikhita @cblecker @alisondy

Slack: Update SIG ContribEx channels

---

OWNERS

I'd like to request approver status for this repo based on:
- experience as steering emeritus
- prior review history (of the last 100 merged prs involving me, I authored 16 and commented on 53)
- experience with sigs.yaml tooling

Add spiffxp as approver

---

contributors/devel/sig-scalability/hollow-node_simplified_template.yaml
contributors/devel/sig-scalability/kubemark-setup-guide.md

kubemark setup guidance is outdated. I update guidance to make it work. 
1. `/bin/sh` was removed in distroless image. We need to update to use binary directly
2. `content-type` setting is incorrect. We need to give `--kube-api-content-type` to pair with the env value. However, this is not commonly changed. We can remove it from the general guidance.
Fixes #https://github.com/kubernetes/community/issues/5475

Update kubemark setup guidance

---

contributors/devel/sig-node/triage.md

Adds some guidelines for SIG Node PR Triage on the project board: https://github.com/orgs/kubernetes/projects/49
so more contributors can get involved!
/hold
for discussion
/cc @SergeyKanzhelev

Add guidelines for node PR triage

---

contributors/devel/sig-scheduling/scheduler_framework_plugins.md

Related to #5237
Moved from https://github.com/kubernetes/kubernetes/blob/35bc0fbad5cd87f1e67fe1f654e616891afbe997/pkg/scheduler/framework/plugins/README.md
cc @Huang-Wei @mrbobbytables

devel/sig-scheduling: add scheduler framework plugins doc

---

contributors/devel/sig-testing/bazel.md

I struggled to follow the doc as is, because my distro's `bazel` just so "happens" not to be exactly the one Kubernetes seems to require - but `bazelisk` seems like a great solution - we should recommend it here IMHO.

recommend using bazelisk

---

sig-cluster-lifecycle/CONTRIBUTING.md

the yearly SIG status update requires us to have a CONTRIBUTING.md under k/community.
given SIG CL is a bit different than other SIGs (like SIG CLI) our file is more about delegating to subprojects.

sig-cluster-lifecycle: add CONTRIBUTING.md

---

contributors/devel/sig-testing/verify-tests.md

/sig testing
/sig security
Adds a placeholder for documenting the various `verify-*` tests.  In particular, KEP-1933's introduction of static analysis via `go-flow-levee` can result in test failures whose remediation is not obvious.  This documentation aims to clarify confusion that could arise from such test failures.

Add documentation for hack/verify* tests.

---

contributors/devel/sig-architecture/api_changes.md

Adds a note regarding testing with feature gate on and feature gate off. Specifically highlights that contributors shouldn't assume that the status of the gate is off (or on).
Fixes #
N/A

minor update to api_changes to highlight gate on/off scenario

---

contributors/devel/sig-release/cherry-picks.md

Recently, I performed a cherry pick for the first time. When I ran ./hack/cherry_pick_pull.sh
after setting up all the env variables, I was asked for my github password. When I gave my actual
github password it threw a 404 not found which confused me. I then came across this
https://github.com/github/hub/issues/2655#issuecomment-735836048 . I created a github token post which
I was able to cherry pick successfully.
The hub project team is looking to fix it but until then I feel that we should document it.
Do let me know if I did something wrong here in the cherry pick process.

Add docs about github tokens for cherrypicking

---

contributors/devel/sig-architecture/api-conventions.md

This is response to a question on slack.  Having cross-namespace references in an API is a risky thing to do and this clarifies why.

add guidance about avoiding cross namespace references from namespaced resource

---

mentoring/programs/new-contributor-workshop/resources/README.md

Just adding a link here, not the original text, to ensure that we have a single source of truth for the slides.
/assign @alisondy

ncw: add link to slides from previous workshops

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

Requested by @dims :)
cc @kubernetes/steering-committee 
/assign @mrbobbytables @parispittman 
intersection of slack admins and SC
/hold
for review by slack admins

slack-config: add usergroup for steering-committee

---

communication/slack-config/usergroups.yaml

:woman_facepalming: 
channel names and usergroups share the same namespace, so they
can't have the same name.
follow up to https://github.com/kubernetes/community/pull/5552

slack-config: rename steering-committee usergroup to steering

---

communication/slack-config/usergroups.yaml

Follow up to https://github.com/kubernetes/community/pull/5553 and https://github.com/kubernetes/community/pull/5552
There is a deactivated slack user called `steering`. It looks like
deactivated users still share the same namespace as channels, users
and user groups.
Ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-community-tempelis-apply/1364844966282530816

slack-config: rename steering usergroup to steering-members

---

OWNERS_ALIASES
sig-release/README.md
sigs.yaml

(Discussed [privately](https://kubernetes.slack.com/archives/G01M2GAGDB2/p1611943383000100) between @alejandrox1, @saschagrunert, and I on 1/29.)
Jorge will be tackling some exciting new career opportunities in 2021, which unfortunately for us, will draw him away from SIG Release for the foreseeable future.
@alejandrox1 -- Thank you for all that you've contributed to the SIG Release family over the years!
We hope to see you again soon and wish you tremendous success always. 💕 
/assign @saschagrunert
cc: @kubernetes/sig-release-leads

sig-release: Jorge Alarcon Ochoa is now an Emeritus Tech Lead

---

communication/README.md

Link to LWKD is under Twitter, which isn't right, it's primarily a newsletter.  Moved it to "other" which seems more appropriate.  Apologies for auto-trimming trailing spaces in the process, you can ignore that.

Move link to LWKD under "other" section in communications.

---

contributors/guide/issue-triage.md

Clarify when to create a PR to address an issue when the issue is already assigned to someone else.

New PR for an already assigned issues

---

contributors/devel/sig-architecture/conformance-tests.md

**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it:**
Update the documentation for promotion of conformance test to match the removal of Bazel by #99561 
**Which issue(s) this PR fixes:**
**Special notes for your reviewer:**
Document update only 
**Does this PR introduce a user-facing change?:**
```
NONE
```
**Release note:**
```release-note
NONE
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**
```
NONE
```
/sig testing
/area conformance

Update conformance promotion instruction to support Remove Bazel PR

---

sig-security/README.md
sig-security/sig-security-docs/OWNERS
sig-security/sig-security-external-audit/OWNERS
sigs.yaml

For in case they want to store some files, and to get subproject owners listed in an OWNERS file

Add directories for sig-security subprojects

---

sig-release/README.md
sigs.yaml

The hyperkube subproject linked OWNERS files 404 since hyperkube went
away a year ago.
Fixes #

cleanup: remove stale sig-release subproject hyperkube links

---

contributors/design-proposals/api-machinery/csi-new-client-library-procedure.md

Fixes https://github.com/kubernetes/kubernetes/issues/68164
Status of existing client libraries applying this change:
/cc @mikedanese @zshihang @deads2k @lavalamp

Add token file reload to client library requirements

---

sig-contributor-experience/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/2544
The repo has been migrated from k-sigs to k.
/assign @alisondy @nikhita @cblecker

SIG-ContribEx: Migrate contributor site repo

---

sig-docs/blog-subproject/README.md

I think this is a correct fixup for PR #5534 but I'm not sure, so I'm going to
/hold
my own PR to highlight that.
PR #5534 removed one mention of a Google form, but there is another. _As I understand it_ that form is not used at all any more so we should remove the remaining reference.
/cc kbarnard10

Avoid use of blog form for embargoed content

---

contributors/devel/development.md

Update the needed version of Go for Kubernetes 1.18+.
It still mentioned that 1.18+ needs Go version 1.15, even though I could the error that I should use Go version 1.16 when building Kubernetes version 1.20.4 (most recent)

Update development.md to match new Go version

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

Signed-off-by: Hubert Stefanski <hstefans@redhat.com>
NA
- This PR adds a user group for grafana-operator maintainers/support
Fixes # NA

add grafana operator maintainer groups

---

contributors/devel/sig-architecture/api_changes.md

The current documentation described how to add a new field, but did not describe the requirements and process for safely adding a new enum value to an existing field.
Came up in review of https://github.com/kubernetes/kubernetes/pull/98918/files#r588922374
cc @thockin

Describe process for allowing a new enum value in an existing field

---

sig-instrumentation/README.md
sigs.yaml

Adding SIG instrumentation sub-projects and adding deprecation notice to heapster.
/assign @ehashman @brancz @dashpole

add SIG instrumentation sub-projects

---

github-management/default-branch-migration.md

Ref: https://github.com/kubernetes/org/issues/2222
This document is meant to be used by repos without too much traffic,
if they wish to migrate the default branch from master to main.
/hold
for review
/assign @spiffxp @mrbobbytables @cblecker

github-management: add docs for master to main migration

---

sig-storage/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2568
/assign @msau42 
/hold

sig-storage: remove k-csi/drivers repo

---

communication/slack-config/channels.yaml

Hello,
A project that I maintain for HA Kubernetes clusters and LoadBalancer type services in Kubernetes, has started to get a little bit of traction. Currently I'm getting questions in channels such as `#cluster-api` or `#cluster-api-vsphere` and I think it might make things easier to have somewhere dedicated for conversations, support, feature requests and general inquiries about this topic. 
Kube-Vip page: [https://kube-vip.io](https://kube-vip.io)
Kube-Vip GitHub: [https://github.com/plunder-app/kube-vip](https://github.com/plunder-app/kube-vip)
Fixes # N/A

Adds a kube-vip channel

---

committee-steering/governance/annual-reports.md

drew out the end of annual reports process with some clarified steps and added the issue piece since we set those.

annual reports: clarifying end process

---

communication/README.md

The link changed resulted in a Google search result that translated **local time into Pacific Time**. But the opposite was intended. This change fixes that. It also, removes some subtle ambiguity of reference to Standard Time vs Daylight-Saving Time - even though Google insightfully overlooks the error.

Update meetup time link for clearer result

---

contributors/guide/README.md

Hi folks, this PR removes the ending whitespace in the mentoring link. This change can let me fix the 404 in the `kubernetes.dev` site.
Furthermore, I have aligned the TOC with the content!
https://github.com/kubernetes/contributor-site/issues/175

Removing ending white space in mentorship and re-align TOC to content

---

sig-security/security-audit-2021/RFP.md

This PR updates the Kubernetes version in the 2021 Third-Party Security Audit RFP to version 1.21 which will be the most recent version at the time the RFP closes.
/assign @tabbysable

Update Kubernetes version to be the most recent at the close of the RFP

---

sig-instrumentation/annual-report-2021.md

Fixes #5504.
/hold
for discussion
/cc @kubernetes/sig-instrumentation-members

Add SIG Instrumentation annual report, 2021

---

sig-multicluster/README.md
sigs.yaml

Removes cluster-registry and federation-v1 from the SIG MC list as both have been retired.

Remove retired subprojects from SIG MC

---

communication/slack-config/channels.yaml

Adding a Slack channel in accordance with the [guidelines](https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel).
[`ko`](https://github.com/google/ko) is a tool for [building Go container images](https://github.com/google/ko#build-an-image), and easily [deploying them to Kubernetes](https://github.com/google/ko#kubernetes-integration). The channel will be used to discuss `ko` with end users and contributors, answer questions, gather bugs and feature requests, etc.
There's currently a `#ko` room in the [Knative Slack workspace](https://slack.knative.dev) for historical reasons, but since `ko` isn't limited to Knative, and is regularly used to deploy to Kubernetes, I think it makes sense to move folks from that room to the Kubernetes …

Add #ko-project to channels.yaml

---

communication/slack-config/sig-release/usergroups.yaml

Slack has a 140-character max for usergroup descriptions, and they can't contain newlines.
Tempelis doesn't understand either of these rules, so it is confused: it is repeatedly trying to add in the newlines that Slack is stripping out, and it cannot correctly create security-release-team because the description is too long. The correct tempelis behaviour would be for this file to fail validation, but that is not the current state.
This PR fixes both of these things to match what Slack permits.

Fix descriptions in sig-release usergroups.

---

communication/moderators.md

specifically
- add dims as administrator
- drop castrojo as moderator (e-mail was bouncing)
changes made to kubernetes-dev to align with these docs:
- add dims as owner
- drop castrojo vmware address as manager (e-mail was bouncing)
- drop jonasrosland vmware address as manager (e-mail was bouncing)
- drop kragniz as manager (was removed here in
https://github.com/kubernetes/community/pull/5397)
/assign @paris @dims
/cc @mrbobbytables @nikhita

communication: reconcile kubernetes-dev staff

---

communication/slack-config/README.md
sig-contributor-experience/README.md
sigs.yaml

Updates docs and links that pointed to the old default branch name
Part of https://github.com/kubernetes-sigs/slack-infra/issues/50

Rename kubernetes-sigs/slack-infra default branch

---

communication/slack-config/channels.yaml

Add a Slack channel for the DevOps Stack
The DevOps Stack is an Open Source project that aims to ease the deployment of
Kubernetes and its ecosystem in a GitOps fashion, using Terraform & ArgoCD.
https://devops-stack.io/
Fixes #

Add devops-stack channel

---

communication/moderators.md

Added my self to the primary, but I'm not sure if this is the right place or I should add it to the `Moderators Pro Tempore`
slack 🧵 https://kubernetes.slack.com/archives/C1TU9EB9S/p1617299576121200?thread_ts=1617297417.117000&cid=C1TU9EB9S
Also, I saw there is a `Regional Category Moderators` I can help for the Portuguese part if we want to have something in this area
Related to https://github.com/kubernetes/community/issues/5685
/assign @Paris @dims @spiffxp 
/cc @mrbobbytables @nikhita

communication: add cpanato to k-dev moderator group

---

sig-security/sig-security-external-audit/OWNERS

Update SIG Security External Audit Subgroup chair to Rey Lejano
/assign @tabbysable @IanColdwater 
/cc @aasmall

Update sig security external audit subgroup chair to Rey Lejano

---

sig-storage/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2592, https://github.com/kubernetes/org/issues/2591
cc @bswartz 
/hold

sig-storage: add volume-populators subproject

---

sig-multicluster/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2609
/assign @JeremyOT 
cc @lauralorenz
/hold
for lgtm from sig-multicluster leads

sig-multicluster: add about-api subproject

---

contributors/devel/sig-architecture/api-conventions.md

Point to the place where we document the semantics for lists in the API Conventions since the current documentation is pretty light.
I also couldn't find reasonable documentation for `patchMergeKey` or `patchMergeStrategy` but that could probably be linked here too.

Include documentation for listTypes in api conventions

---

communication/slack-config/channels.yaml

Kubewarden is an open source project policy engine for Kubernetes. It
allows users to write validation and mutating policies in a language
agnostic way by leveraging the power of WebAssembly.
The goal of this channel is for users, developers and in general,
community stakeholders to discuss about the project, its goals and
provide mutual help.
Kubewarden project page: https://kubewarden.io
Policy hub: https://hub.kubewarden.io
Documentation: https://docs.kubewarden.io
Helm charts: https://charts.kubewarden.io

Add #kubewarden slack channel

---

github-management/default-branch-migration.md

specifically
- remove reference to prow retriggering presubmits on PR rename (thanks
for the fix GitHub! :heart:)
- add links to issues for bootstrap and pod-utils not supporting default
branch as a concept
- add snippets showing how to auto-detect remote branch
- misc rewording or rephrasing
At least some of this is based on my experience migrating
kubernetes-sigs/slack-infra (ref:
https://github.com/kubernetes-sigs/slack-infra/issues/50)
ref: https://github.com/kubernetes/community/issues/5636 as the general
feedback issue for these docs, thought I didn't specifically address any of
the items there as part of this
fixes: https://github.com/kubernetes/community/issues/5619

docs: update default-branch-migration.md

---

sig-release/annual-report-2021.md

Requested in #5508.
Supersedes https://github.com/kubernetes/community/pull/5561
Steering liaison:
/assign @dims
PTAL @kubernetes/sig-release-leads

sig-release: Add 2021 annual report

---

sig-cluster-lifecycle/annual-report-2021.md

add annual report for sig-cluster-lifecycle for 2021
https://github.com/kubernetes/community/blob/master/committee-steering/governance/annual-reports.md

sig-cluster-lifecycle: add annual report for 2021

---

sig-scheduling/2020-annual-report.md

Adding initial template for SIG-Scheduling 2020 Annual Report.
This is due by March 8th and will be shown to the SIG and Slack.
Fixes #5510.

SIG-Scheduling 2020 Annual Report

---

mentoring/programs/group-mentoring.md

Fixing links to Mentee/Mentor guide on group-mentoring.md
/assign @ehashman @parispittman

Fixing links on group-mentoring.md

---

contributors/devel/sig-release/cherry-picks.md

This PR adds some guidance around using the `hub`-aware `GITHUB_TOKEN` environment variable to make using the cherry-pick script a bit easier.
Also makes some of the language more exactly correct so folks who are unfamiliar with github personal access tokens can bootstrap from these concepts more easily.
Fixes #

docs: clarify github tokens and cherry-pick script

---

sig-auth/archive/meeting-notes-2020.md

Auto generated from the SIG-auth agenda doc by the [Docs to Markdown addon](https://workspace.google.com/u/0/marketplace/app/docs_to_markdown/700168918607?hl=en&pann=docs_addon_widget). I'll delete the 2020 agenda sections once this merges.
/assign @ritazh @mikedanese @enj 
/sig auth

Archive 2020 SIG-Auth meeting notes

---

github-management/org-owners-guide.md

The new membership coordinators also have low bandwidth and are actively
participating in leadership roles in other parts of the project.
We are also in a pandemic!
This commit updates the SLO to match the current state - we mostly take
upto a week to address org invites. We can switch it back to 72 hours
once folks have more time.
/assign @mrbobbytables @cblecker @spiffxp @idvoretskyi 
members of the github admin team
/cc @ameukam @savitharaghunathan @palnabarun 
new membership coordinators
/hold
for review

github-management: update org invite SLO to one week

---

sig-security/security-audit-2021/RFP.md

Per discussions on SIG Security and SIG Security External Audit subproject meetings this PR updates the RFP with the following:
- Change scope of the audit to 
>the most recent release at the close of this RFP
- Extend the RFP until four proposals have been received
- Set the RFP closing date to 1 week after the fourth proposal has been received. 
- Set TBD as dates for the RFP Closure and Vendor Selection
- Change the audit timeline to be flexible
cc @aasmall @tabbysable

Update RFP closure dates and audit timeline

---

sig-node/annual-report-2021.md

Ref: https://github.com/kubernetes/community/issues/5507
add annual report for sig-node for 2021
https://github.com/kubernetes/community/blob/master/committee-steering/governance/annual-reports.md

SIG Node Annual 2021 Report

---

communication/slack-config/sig-release/usergroups.yaml
communication/slack-config/users.yaml

Adding 1.22 RT Leads to release-team-leads Slack usergroup.
ref: https://github.com/kubernetes/sig-release/issues/1522
/assign
/sig release
/assign @justaugustus @saschagrunert @jeremyrickard @hasheddan
/cc @annajung @divya-mohan0209 @erismaster @kikisdeliveryservice

slack-config: add 1.22 RT Leads to the release-team-lead usergroup

---

communication/slack-config/restrictions.yaml
communication/slack-config/sig-release/usergroups.yaml
communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

Follow-up to https://github.com/kubernetes/community/pull/5744#discussion_r621729357 (cc: @jeefy) and https://github.com/kubernetes/community/pull/5682 (cc: @Katharine).
/area release-eng
/committee security
/assign @hasheddan @jeefy @mrbobbytables 
cc: @kubernetes/release-managers @kubernetes/product-security-committee @kubernetes/sig-release-leads 
- Update guidance on release-team-leads membership
- Alpha-sort Anna's username
- Offboard @alejandrox1 from sig-release-leads
- Add @wilsonehusin to release-managers
- Alpha-sort Tabby in product-security-committee
- Add @tabbysable to Security Release Team usergroup
- s/security-release-team/security-rel-team
When initially attempting to create this usergroup, its description
was too long for Slack to accept. The original group name …

slack/sig-release: Update usergroup memberships

---

communication/meeting-notes-archive/201911-202010_Community_Meeting_Notes.md

Moving the older meeting notes out of the Google doc to the archive for the year. Generated with the Gdoc extension Docs to Markdown.

Add 2019 Q4 and 2020 community meeting notes to the archive

---

sig-security/annual-report-2021.md

Adding annual report template for SIG Security

add SIG Security annual report

---

communication/slack-config/channels.yaml

- create new channel to use for nginx ingress development
- rename existing ingress-nginx to be ingress-nginx-users for
support/general chat and also match other channels name.
We would like to have a channel to discuss the future and current development of nginx-ingress but not in the existing channel that is being used for support/questions.
also, rename the existing channel to match other channels that the main idea is for users of the tool/service ask questions/socialize/support. 
Fixes #
cc @rikatz @strongjz @ElvinEfendi

slack: create new channel for nginx-ingress development and rename the existing

---

communication/slack-config/channels.yaml
communication/slack-config/usergroups.yaml

Rename the existing velero channel to velero-users to better reflect its user-to-user nature, and add velero-dev.
As requested by the Velero team.

Velero Slack channel updates

---

communication/slack-config/channels.yaml

Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
This split keeps the existing `#headlamp` channel as the -users, and adds a new -dev channel.
The Headlamp project is opening up all its development iterations, which also includes moving conversations from an internal slack channel to the public community.

communication/slack-config: split #headlamp into dev and users

---

sig-auth/annual-report-2021.md

Fixes #5497
/assign @enj @mikedanese @liggitt @deads2k @tallclair

SIG Auth 2021 Annual Report

---

communication/slack-config/channels.yaml

CoC Committee is increasing transparency into what we do and
working to improve community's ability to interact with us in
order to support various projects and teams.
So, we'd like to add a public channel to help with that.
Details will be discussed in our keynote tomorrow.
Signed-off-by: Aeva Black <806320+AevaOnline@users.noreply.github.com>

Add a public Code of Conduct Slack channel

---

committee-code-of-conduct/incident-process.md

Add CoCC incident response and triage processes.

Add incident response and triage processes

---

committee-code-of-conduct/governance/onboarding-offboarding.md

We've added a public channel and also admin privileges within for CoCC
members.  These privileges need rotated during transitions.

update CoCC Slack management onboarding/offboarding

---

contributors/devel/sig-architecture/api-conventions.md

> When referencing another field name, indicate the name in back-quotes. Example: "must be greater than `request`". 
In this sentence, we're meant to see "request" surrounded by back-quotes.
In markdown, backticks (back-quotes) are used to create a code section, and thus aren't shown. By escaping them, they are shown to the user.

API conventions: escape back-quotes when visible

---

sig-cloud-provider/2020-annual-report.md
sig-cloud-provider/cloud-provider-extraction-migration/OWNERS

Adding initial template for SIG Cloud Provider 2020 Annual Report.
Part of issues/5500.
This is due by March 1st and will be shown to the SIG and Slack.
Fixes #5500

Initial template for SIG Cloud Provider 2020 Annual Report

---

communication/slack-config/channels.yaml

Adding a Slack channel in accordance with the [guidelines](https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel).
[`kcp`](https://github.com/kcp-dev/kcp) is an experimental prototype to separate K8s the API server (kubectl, YAML, RBAC, etcd) from K8s the container orchestrator (pods, nodes, deployments), shared by @smarterclayton at today's KubeCon EU keynote. We hope to use this channel to talk with potential users and contributors, answer questions, gather ideas and feedback from the community, etc.
Note: #kcp is also available, but we'd prefer to highlight that it's a prototype, to set expectations early and often. If we graduate beyond a prototype we could rename the channel at that time.

Add #kcp-prototype Slack channel

---

sig-cloud-provider/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2639
/assign @cheftako 
cc @nckturner 
/hold
for lgtm from sig-cloud-provider leads

sig-cloud-provider: add provider-aws-test-infra repo

---

liaisons.md
sigs.yaml
wg-structured-logging/README.md

Add dims as liaison for the new WG structured logging

---

sig-contributor-experience/README.md

Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
I don't think an issue has been opened for this. Please correct me if I'm wrong.
I was going through the README and noticed that the talk was up on YouTube but the link still pointed to the slides so I've updated that. Please let me know incase any changes are required. Thanks!

add link for KubeCon EU 2020 sig-contribex talk

---

sig-node/archive/README.md
sig-node/archive/meeting-notes-2020.md

Archive 2020 meeting logs from the active working document.
Also adds a simple README landing page for the archive to help in navigation.

Archive 2020 SIG Node meeting notes

---

contributors/guide/contributor-cheatsheet/README.md
contributors/guide/pull-requests.md

Add documentaion for tide/squash-on-merge to pull-request.md and contributor-cheatsheet
- adding documentation increases awareness that this label exists and can help PRs get merged quicker
- Manual squash causes removal of lgtm label and re-run of CI tests.
Suggestion provided and discussed on the [sig-contribex slack](https://kubernetes.slack.com/archives/C1TU9EB9S/p1620824009426800?thread_ts=1620824009.426800&cid=C1TU9EB9S).

Add documentaion for tide/squash-on-merge

---

sig-storage/README.md
sigs.yaml

Fixes https://github.com/kubernetes/org/issues/2701
cc @wlan0 
/hold

sig-storage: add cosi-driver-sample repo

---

communication/slack-config/channels.yaml

Hi! I'd like to request a slack channel for [Kilo](https://github.com/squat/kilo), a networking provider for Kubernetes built on WireGuard. This would be helpful to provide a designated place for the community members and maintainers to talk, discuss issues, and brainstorm.
As this is my first such request, please let me know if I need to do anything else.
Thanks!

request slack channel for Kilo

---

communication/moderators.md
communication/slack-config/usergroups.yaml
mentoring/OWNERS
mentoring/programs/outreachy.md

Marky has asked to step down for a bit. This PR moves him to emeritus where possible. ❤️ 
Thank you @markyjackson-taulia for all your work and hope to see you back when you can :) 
/cc @markyjackson-taulia

SIG ContribEx: Move markyjackson-taulia to emeritus
