kubernetes/community

- sig-testing/README.md
whoops, missed this in all the commotion with #3
> sig-testing meets on tuesdays

- sig-apps/minutes/2016-05-18.md
- sig-apps/minutes/2016-05-25.md
@michelleN any additions or changes?
> Adding minutes for past 2 meetings

- sig-apps/agenda.md
- sig-apps/minutes/2016-06-08.md
> add minutes for 06-08-16

- sig-apps/agenda.md
- sig-apps/minutes/2016-06-15.md
- sig-apps/minutes/2016-06-22.md
+ update agenda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/community/13)
> add minutes for 6/15, 6/22

- sig-apps/agenda.md
- sig-apps/minutes/2016-06-29.md
> add minutes for 6/29/16

- sig-apps/README.md
- sig-apps/agenda.md
* add another agenda link to README
cc/ @mattfarina
> update agenda for 7/6/16

- sig-apps/agenda.md
- sig-apps/minutes/2016-07-06.md
> add minutes for 7/6/16 sig-apps

- README.md
As discussed with @sarahnovotny
> Update "How to start a SIG" to include proposing it first

- sig-apps/agenda.md
- sig-apps/minutes/2016-07-13.md
> sig-apps: add 7/13 mins

- sig-apps/agenda.md
- sig-apps/minutes/2016-07-20.md
> sig-apps: add minutes from july 20, 2016

- sig-apps/agenda.md
- sig-apps/minutes/2016-08-03.md
> sig-apps: add minutes for 8/3/16

- sig-apps/README.md
- sig-apps/agenda.md
- sig-apps/minutes/README.md
> Updated for minutes and agenda in Google Docs

- README.md
Add ML info and google group link for users.
> Add kubernetes-users mailing list information

- incubator.md
Significant discussion on this process has happened here:
- https://groups.google.com/forum/#!topic/kubernetes-dev/o6E1u-orDK8
- https://groups.google.com/forum/#!topic/kubernetes-dev/brGt4bZ7UqQ
- https://docs.google.com/document/d/1ugAd9Zj-jW3YHdrNVdktmvDMEWtChPqyGHfkwWdQ3zo/edit#heading=h.83zj92jqj8w8
> incubator: initial commit

- sig-scheduling/README.md
> Added contact info for sig-scheduling.

- sig-service-catalog/README.md
Adds the new service-catalog SIG.
cc @sarahnovotny
> Add SIG service-catalog

- sig-rktnetes/README.md
We're moving to Zoom from hangouts.
> Update SIG-Rktnetes meeting URL

- incubator.md
Minor edits and typo fixes to the incubator process doc.
cc @sarahnovotny @bgrant0607 @philips
> Minor edits to incubator process doc

- incubator.md
Change the incubator process doc to allow sponsors to come from the top-level OWNERS file or `pkg/OWNERS`
> Change incubator process re: project sponsors

- sig-apps/README.md
- sig-apps/agenda.md
> sig-apps: update meeting schedule

- sig-windows/README.md
Added new directory for sig-windows, with a README file that includes meeting information.
> Add community space for sig-windows

- community/README.md
> Changed link to find meeting time in local timezone

- sig-openstack/README.md
Meeting time information had PDT/EDT values flipped.
> [SIG-OpenStack] Update meeting information

- README.md
> Fixed minor typos in README

- sig-storage/contributing.md
> Typos in sig-storage/contributing.md

- sig-aws/README.md
Publishing our notes for the new meetings starting next week.
Cheers
> Adding updated SIG-AWS notes

- sig-aws/README.md
Reactive to a comment in slack about the sig appearing not open to everyone.
> Verbage on joining - We want this to feel open/friendly

- sig-aws/README.md
Added Mackenzie Burnett to the list of SIG AWS leads
> Updated SIG-AWS leads list

- CLA.md
Same as https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ (which will redirect to here).
As per https://github.com/kubernetes/kubernetes/pull/37028#discussion_r88988966
cc @bgrant0607 @sarahnovotny
> Adding CLA-FAQ

- contributors/devel/api-conventions.md
Move from kubernetes/kubernetes#37652.
Design doc for how to make patch work for merging list of scalars based on #35647 (comment)
Related issue: #35163, #32398
Last attempt fix in #35647 has been reverted, since we want to use the approach proposed in this PR.
cc: @kubernetes/kubectl
> Design doc for patch merging list of scalars

- sig-federation/README.md
> Add the updated meeting time and additional links to the sig-federation README.

- contributors/devel/running-locally.md
Just a couple small tweaks to make it more accurate.
> devel/local-up: doc cfssl requirement

- contributors/devel/container-runtime-interface.md
Add required `--feature-gates=StreamingProxyRedirects=true`
> Add apiserver flag to CRI guide

- contributors/design-proposals/control-plane-resilience.md
- contributors/design-proposals/enhance-pluggable-policy.md
- contributors/design-proposals/federated-replicasets.md
- contributors/design-proposals/federated-services.md
- contributors/design-proposals/federation-phase-1.md
- contributors/design-proposals/ha_master.md
- contributors/design-proposals/indexed-job.md
- contributors/design-proposals/selector-generation.md
fix som typos and remove some extra spaces
Signed-off-by: Qinglan Peng <qinglanpeng@zju.edu.cn>
> fix some typos

- contributors/design-proposals/container-init.md
> Fix typos in init container design.

- README.md
- community/README.md
...because I couldn't find it anywhere :)
> Add zoom link for main community meeting

- contributors/design-proposals/multi-platform.md
- contributors/devel/bazel.md
- contributors/devel/development.md
- contributors/devel/e2e-tests.md
- contributors/devel/running-locally.md
I also converted a few links from relative to absolute.
> build-tools/ has been renamed build/

- contributors/design-proposals/disk-accounting.md
- contributors/design-proposals/downward_api_resources_limits_requests.md
- contributors/design-proposals/enhance-pluggable-policy.md
- contributors/design-proposals/expansion.md
- contributors/design-proposals/external-lb-source-ip-preservation.md
- contributors/design-proposals/federated-replicasets.md
- contributors/design-proposals/federated-services.md
- contributors/design-proposals/federation-phase-1.md
- contributors/design-proposals/garbage-collection.md
- contributors/design-proposals/gpu-support.md
- contributors/design-proposals/high-availability.md
- contributors/design-proposals/resource-quota-scoping.md
- contributors/design-proposals/runtimeconfig.md
- contributors/design-proposals/secret-configmap-downwarapi-file-mode.md
- contributors/design-proposals/service-external-name.md
- contributors/design-proposals/stateful-apps.md
- contributors/design-proposals/templates.md
- contributors/design-proposals/versioning.md
- contributors/design-proposals/volume-ownership-management.md
- contributors/design-proposals/volume-provisioning.md
Fix some markdown format errors and add code block high light
Signed-off-by: Qinglan Peng <qinglanpeng@zju.edu.cn>
> fix some markdown formats

- contributors/design-proposals/security-context-constraints.md
move from  https://github.com/kubernetes/kubernetes/pull/36967
> update scc doc about the intent of psp

- contributors/design-proposals/volume-hostpath-qualifiers.md
Signed-off-by: tim-zju <21651152@zju.edu.cn>
> symbol is wrong

- sig-network/README.md
> Update the SIG Network README

- community/developer-summit-2016/KubDevSummitVoting.md
> Title layout is not appropriate

- contributors/design-proposals/volume-hostpath-qualifiers.md
> Spelling error in vocabulary

- contributors/design-proposals/apiserver-watch.md
> Modify spelling mistake

- community/developer-summit-2016/application_service_definition_notes.md
Signed-off-by: Jie Luo <luo612@zju.edu.cn>
depencences -> dependences
> fix a typo

- contributors/design-proposals/stateful-apps.md
> Multiple spelling errors

- contributors/devel/e2e-tests.md
Signed-off-by: Xinbo Weng <xihuanbo_0521@zju.edu.cn>
> redundant backquote

- contributors/design-proposals/service_accounts.md
> The article is not correct

- contributors/design-proposals/admission_control_limit_range.md
- contributors/design-proposals/api-group.md
- contributors/design-proposals/apiserver-watch.md
- contributors/design-proposals/client-package-structure.md
- contributors/design-proposals/cluster-deployment.md
Signed-off-by: liwenqi <vikilwq@zju.edu.cn>
> correct some words

- contributors/devel/faster_reviews.md
Signed-off-by: Xinbo Weng <xihuanbo_0521@zju.edu.cn>
> Incorrect serial number

- contributors/design-proposals/release-test-signal.md
This comes after its implementation but want to include some detail on the design in a doc here.
Lets keep the discussion for this limited to existing functionality.  Please ask for clarification on anything and open new issues as needed.
cc @kubernetes/test-infra-maintainers
> Addition of a design doc for `find_green_build` functionality.

- sig-api-machinery/README.md
Fix the title of the file and link to github group.
> Fix API Machinery README

- contributors/devel/pull-requests.md
Add "WIP-" process notes to pull request.
Refer to the discussion at https://groups.google.com/forum/#!topic/kubernetes-dev/7Y4BaYon2Wc
> Add "WIP-" process notes to pull request.

- contributors/devel/scheduler.md
> fix invalid url

- contributors/devel/release/README.md
A minor update with more details and more clear naming.
> Features lead role defining

- governance.md
With regards to the PM meeting [conversation](https://docs.google.com/document/d/1ZElyRqNsGebvMpikEBhSuf2Q6WrEYHB2PgWIlGgwt78/edit?ts=58740b3d#heading=h.1txgejyk87dr), SIG representative functions for the PM group are described.
> PM representative responsibilities added

- contributors/design-proposals/kubectl-create-from-env-file.md
> Initial --from-env-file proposal

- contributors/design-proposals/networking.md
**What this PR does / why we need it:**
Updated information about AWS starting to support ipv6
**Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged): fixes #**
N/A
**Special notes for your reviewer:**
Docs update
**Release note:**
> Updated ipv6 support docs

- contributors/design-proposals/security-context-constraints.md
Fixes broken links along with the links that are lead to redirect.
> security-context-constraints.md: update links

- contributors/devel/local-cluster/local.md
reference to https://github.com/kubernetes/kubernetes/pull/34619
> update doc about enable rbac on local cluster

- community/developer-summit-2016/cluster_lifecycle_notes.md
Original notes were at https://docs.google.com/document/d/11kK39Zz3zxIY9-GFa8buqqWYOrctFQ7hvOw5NBFwJL0/edit#
> Notes from the Cluster Lifecycle Deployment & Upgrade Roadmap session at Kubernetes Dev Summit 2016

- contributors/design-proposals/daemonset-update.md
A proposal for DS update @lukaszo @bgrant0607 @erictune @smarterclayton @mml @fabioy @kubernetes/api-reviewers
> Proposal for DaemonSet updates

- contributors/design-proposals/daemonset-update.md
Follow up https://github.com/kubernetes/community/pull/262#issuecomment-274139506:
1. Move `PodTemplate` and "pod-template-hash" label to "future plans"
2. Add two more fields to DaemonSet status: numberAvailable and numberUnavailable
3. Updated implementation plan of DaemonSet controller
@lukaszo @bgrant0607 @erictune @smarterclayton @kargakis @pigmej @mml @fabioy @kubernetes/api-reviewers
> DS update proposal: Move PodTemplate to future, add 2 status fields

- contributors/design-proposals/all-in-one-volume.md
Copied from kubernetes/kubernetes#35313 (with slight modifications)
> Proposal: secrets,configmap,downwardAPI all in one volume

- contributors/devel/bazel.md
> Update Bazel documentation to current state-of-the-world

- contributors/design-proposals/cri-dockershim-checkpoint.md
ref: https://github.com/kubernetes/kubernetes/issues/34672
> [Proposal] Dockershim Sandbox Checkpoint 

- sig-big-data/README.md
Resurrecting the SIG.
kubernetes-dev post: https://groups.google.com/forum/#!topic/kubernetes-dev/1FACSVsWEp8
> Update README for sig-big-data

- sig-windows/README.md
i am the sig-windows lead making changes to our readme
> updated meeting invite and details

- sig-federation/README.md
I noticed the link was bad when I went to try to find the document. /cc @quinton-hoole @nikhiljindal
> Fix SIG-Federation notes link

- sig-creation-procedure.md
MD fixes to have the shareable links at the headers.
> Minor markdown fixes

- contributors/design-proposals/pod-safety.md
Changes to the system to better improve how pod safety is handled and
set a foundation for reliable cluster changes in stateful sets and
others.
From kubernetes/kubernetes#34160
> Proposal: Pod Safety Guarantees

- contributors/design-proposals/cronjob.md
@erictune I figured out it's worth to update the design doc to reflect current naming. It'll be easier to find, rather than using the old name. ptal
> Rename ScheduledJob to CronJobs

- sig-creation-procedure.md
Small typo fix in sig-creation-procedure doc.
> typo in sig-creation-procedure doc

- sig-on-prem/README.md
Updated SIG OnPrem meeting time in SIG specific readme
> Updated SIG OnPrem meeting time

- sig-pm/README.md
Indents added to make the README more human-readable; extra minor fixes.
> A few extra fixes to SIG-PM README

- contributors/design-proposals/annotations-downward-api.md
Moved from kubernetes/kubernetes#36058
Ref kubernetes/kubernetes#31218
> proposal: Expose single annotations via downward API

- contributors/design-proposals/default-storage-class.md
@kubernetes/sig-storage-proposals
> Proposal for deployment of default StorageClass

- contributors/design-proposals/controller-ref.md
@foxish @janetkuo @kow3ns Please take a look. I've tried to clarify existing specifications and pin down some more details of the implementation.
cc @erictune @lavalamp @gmarek @kubernetes/sig-apps-proposals
> Update ControllerRef proposal

- contributors/devel/testing.md
Pending merge of https://github.com/kubernetes/kubernetes/pull/41581
cc: @thockin
> Add package scoping to integration testing example

- sig-cli/README.md
- sig-cli/contributing.md
Attempt to clarify request/proposal/impl cycle and @mention usage.
Cut ~700 words (~30%), fixed some links, pluralize mention tags.
> Copy edit contributing.

- contributors/design-proposals/all-in-one-volume.md
The implementation has been merged, so no further changes should be required
after this.
> Update all-in-one proposal to reflect reality

- contributors/design-proposals/daemonset-update.md
Add an additional field `.templateGeneration` to DaemonSet, to keep track of DaemonSet template changes. We need it because we need to compare DaemonSet template with DaemonSet pods to know if the pods need to be updated, and:
1. Pod template hash isn't 100% reliable - it may change on PodTemplate API changes (e.g. adding new fields), and users will encounter unexpected DeamonSet rolling update after upgrading Kubernetes to a different version. 
2. It's not easy to infer pod template from a pod's spec, since many default values are applied to the pod, and the admission controller may update the pod as well. 
@erictune @lavalamp @kargakis @lukaszo @smarterclayton @kubernetes/sig-apps-api-reviews @kow3ns @foxish @enisoc @pwittrock 
--- 
Copied from my comment in …
> Add template generation to DaemonSet upgrade proposal

- contributors/design-proposals/cloudprovider-storage-metrics.md
cc @childsb @kubernetes/sig-storage-feature-requests
> Proposal for cloudprovider storage metrics

- contributors/devel/e2e-tests.md
Ref kubernetes/test-infra#1475
> Add --extract=E documentation

- sig-cli/contributing.md
I needed these when ramping up.
@pwittrock
> Add ptr to CLA signing instructions and a slack signup link.

- sig-cli/contributing.md
Per @pwittrock comment in #386.
> Add linux foundation helpdesk email address.

- contributors/devel/api-conventions.md
Clarifies a few points folks have asked.
> Describe API groups and spec/status for simple kinds

- contributors/devel/writing-good-e2e-tests.md
> Fix links in doc

- sig-openstack/README.md
- Updated sig-openstack README structure.
- Added notification mailing lists.
> Update sig-openstack README structure

- contributors/devel/api-conventions.md
fix invalid url in api-conventions.md
> fix invalid url in api-conventions.md

- sig-scalability/README.md
The intention here is to lead by example about what information the readme file for each sig should more or less contain and perhaps be organized.
> updating SIG-Scalability Readme.md

- contributors/design-proposals/pod-resource-management.md
> Fix example text for cgroup name

- sig-service-catalog/README.md
Pretty much what it sounds like
> Add link to youtube playlist for sig-service-catalog meetings

- contributors/design-proposals/envvar-configmap.md
fix little issue in envvar-configmap doc. help review thanks.
@fraenkel @pmorie
> lower case name/value in envvar-configmap example json

- sig-windows/README.md
> Add link to GC Next 2017 demo instructions.

- contributors/devel/e2e-tests.md
@pwittrock @ixdy Please review if everything is accurate.
> explain skew and upgrade test naming

- contributors/design-proposals/containerized-mounter.md
This PR describe the containerized mounter approach for
Container-Optimized OS.
> Containerized Mounter with Chroot

- contributors/design-proposals/apparmor.md
> modify link

- contributors/devel/security-release-process.md
> add gpg key

- contributors/devel/flexvolume.md
Update flex volume documentation for 1.6
> Update flex volume documentation for 1.6

- contributors/design-proposals/admission_control_limit_range.md
Fix typo in admission_control_limit_range.md.
> Fix typo in admission_control_limit_range.md

- sig-storage/contributing.md
> Fix the error url show in  sig-storage/contributing.md

- contributors/devel/client-libraries.md
Following conversation in https://groups.google.com/forum/#!topic/kubernetes-users/_HnGSuPmDoc
> Added a community Go client

- sig-big-data/resources.md
Adding some links to the work the community has been doing to help aggregate and find these
> Add links to design docs and resources

- contributors/design-proposals/csi-client-structure-proposal.md
- contributors/design-proposals/csi-new-client-library-procedure.md
Adding approved proposal for new client libraries
@kubernetes/sig-api-machinery-misc
> Add new client library procedure proposal

- contributors/design-proposals/apiserver-watch.md
The files path seems have been changed. Fix that error link by by updating the file path, but not sure whether the line number is correct?
> Update the file link path

- contributors/devel/on-call-build-cop.md
Update buildcop instructions with how to force a build.
> Update buildcop instructions with how to force a build.

- contributors/devel/controllers.md
... so that multi-paragraph list is properly indented.
> Re-format controllers doc

- contributors/devel/controllers.md
Fixes https://github.com/kubernetes/community/issues/135
@deads2k @lavalamp @kubernetes/sig-apps-misc ptal
Signed-off-by: Michail Kargakis <mkargaki@redhat.com>
> Add ObservedGeneration and owner ref suggestions in controller doc

- contributors/design-proposals/architecture.md
This link did not render properly.
> Fix broken link in architecture.md

- sig-aws/README.md
Since https://github.com/kubernetes/community/pull/433 was conflicted :)
> Updates for SIG

- contributors/devel/api-conventions.md
> Clarify optional fields

- sig-node/README.md
@kubernetes/sig-node-pr-reviews
> Fill in details of sig-node community

- sig-node/README.md
> Fix typo in sig-node README

- contributors/devel/README.md
> update links for README.md

- contributors/devel/generating-clientset.md
The generating-clientset page has three broken links. Fix them.
> Fix broken links in the generating-clientset

- contributors/devel/flexvolume.md
Rebased #525 and linking to main project, now.
> Fix example flex driver links in flexvolume document

- contributors/devel/local-cluster/docker.md
* replace `--config` with `--kubeconfig`
> update docs to correct config

- sig-cluster-lifecycle/postmortems/kubeadm-1.6.md
This document was converted to markdown after review of the original Google doc:
https://docs.google.com/document/d/1o-wJ39O8eqBxOCHgu0MGmgH4EdojzI3WlrsV3TVwhe0/edit?usp=sharing
> Adding kubeadm 1.6 postmortem.

- contributors/design-proposals/flakiness-sla.md
@calebamiles @pwittrock @kubernetes/sig-testing-proposals
> Add a document on the flakiness SLA for Kubernetes.

- contributors/devel/e2e-tests.md
PromDash has been deprecated, using Grafana instead
> Fix broken link:e2e-tests.md

- contributors/design-proposals/cloudprovider-storage-metrics.md
We are going to use same name for all metrics. But each api request
being made will be added as a dimension.
This has the benefit that - aggregating metrics is way easier without
without resorting to wildcards and stuff.
xref - https://github.com/kubernetes/features/issues/182
cc @kubernetes/sig-storage-pr-reviews @saad-ali @piosz @brancz @fabxc
> Amend cloudprovider metric proposal for new metric names

- sig-aws/2017_goals.md
> Adding first stab at goals for 2017

- contributors/devel/testing.md
1) Remove the blank space between "test-" and "integration".
2) Make the description more clear for "Run a specific integration test".
> Minor update for testing.md.

- contributors/devel/controllers.md
Fix minor link for factory methods in `controllers.md`.
> Fix link for factory methods of informers

- community/2017-events/12-dev-summit/information.md
Will start collecting information here. Also fixed folders :)
> Create info file for Dev Summit

- contributors/devel/api-conventions.md
> API: avoid bool fields

- sig-aws/kubernetes-on-aws.md
Signed-off-by: Arun Gupta <arun.gupta@gmail.com>
> first draft

- contributors/design-proposals/deployment.md
@kubernetes/sig-apps-proposals 
Signed-off-by: Michail Kargakis <mkargaki@redhat.com>
> Rename uniquifier field to collisionCount

- contributors/design-proposals/statefulset-update.md
@kubernetes/sig-apps-api-reviews 
@kubernetes/sig-apps-feature-requests 
@smarterclayton 
@kargakis 
@erictune 
@janetkuo 
@enisoc 
@foxish
> initial StatefulSet updates proposal

- community/2017-events/05-leadership-summit/session-notes/readme.md
Need to create folder and don't have git on machine. Made tiny readme inside new folder to make the new folder :)
> Create readme (& folder implicitly)

- sig-aws/kubernetes-on-aws.md
Added another way to get k8s on aws.
> adding stackpoint.io

- generator/README.md
- generator/app.go
- generator/footer.tmpl
- generator/sig_index.tmpl
- generator/sig_list.tmpl
Fixes https://github.com/kubernetes/community/issues/634.
cc/ @saad-ali @jbeda
> Add custom content blocks to generator

- wg-resource-management/README.md
@smarterclayton @bgrant0607 @dchen1107 @davidopp @vishh  -- please take a look.
> Document resource management working group

- sig-ui/README.md
fixes https://github.com/kubernetes/kubernetes/issues/46832#issuecomment-305899132
/assign @bryk 
/cc @cblecker
> Fix sig-ui README format

- contributors/devel/README.md
Added a missing reference.
Resolves https://github.com/kubernetes/kubernetes/issues/35253
> Update `contributors/devel/README.md` to reference `testing.md`

- sig-testing/README.md
> New Zoom URI for sig-testing

- sigs.yaml
Corrected leads, meeting time, uri
> Update sig-testing info in sigs.yaml

- generator/README.md
- sig-auth/README.md
- sig-autoscaling/README.md
- sig-big-data/README.md
For some reason there was a malformed space in the headers 🤔 
This PR will fix the broken rendering
> Add spaces to custom content headers

- contributors/design-proposals/mount-options.md
> Fix mount options proposal to be accurate

- sigs.yaml
> Updated leadership for sig-on-premise

- contributors/devel/development.md
> make'ing the build requires a null directory CDPATH.

- generator/app.go
> Create README file for new SIGs

- contributors/devel/container-runtime-interface.md
@feiskyer (who moved this file)
> Fix link to CRI API

- community-membership.md
- Membership includes GH org membership
- Requirements and expectations increased due to increased privs
- More explanation of sponsorship
> Change Kubernetes membership to include GitHub org membership

- contributors/devel/strategic-merge-patch.md
> Add retainKeys and setElementOrder to SMP doc

- contributors/design-proposals/local-storage-overview.md
Update local storage overview to alpha API.  Also add some info on secondary partition.
> Update local storage overview

- contributors/design-proposals/pod-preset.md
> Add additional documentation for opt-out annotation

- 2017-events/05-leadership-summit/session-notes/0300-0345_CODEORGANIZATION.md
> add docs from code organization session

- contributors/design-proposals/metrics-server.md
This was reviewed and approved in https://docs.google.com/document/d/1w6-ZfnA18aKYLJ8DCLBFKlv_1umm74x0I2X4V188kvU/edit#
> Metrics server design proposal

- contributors/devel/pull-requests.md
Depends on https://github.com/kubernetes/kubernetes/pull/47673
> pull-requests.md: delete broken link to pre-commit instructions

- sigs.yaml
updated my github account (the lead of sig-windows) to the accurate one and also slightly updated our mission statement
> change sig-windows contact details

- generator/wg_index.tmpl
> Fix generator by adding the missing workgroup template

- contributors/devel/on-call-build-cop.md
Based on https://docs.google.com/document/d/11nf_tg3_0OTHfKpJdaaPBJrCMIHHWyr5cBZ1EXDnI0o/edit?ts=59477035#
> Update buildcop instructions

- contributors/devel/testing.md
depends on:
https://github.com/kubernetes/kubernetes/pull/46923
> drop option KUBE_GOFLAGS

- contributors/design-proposals/network-policy.md
Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>
> design-proposals/network-policy.md: fix nit

- sig-scalability/goals.md
- sig-scalability/provider-configs.md
Document as reviewed/commented in Sig Scalability. @kubernetes/sig-scalability-pr-reviews
> Adding provider config document

- contributors/devel/flexvolume.md
Added a clarification about the matching between FlexVolume driver directory and the volume spec.
> Adding comment about vendor/driver matching in FlexVolume documentation.

- contributors/design-proposals/architecture.md
Update outdated links from  kubernetes.io
> Update outdated links from kubernetes.io

- contributors/design-proposals/federated-ingress.md
> update ingress url

- contributors/devel/development.md
Added extra information to testing section.
/cc @janetkuo
> Add information for testing

- contributors/design-proposals/multiple-schedulers.md
> Fix a 404 error

- sig-instrumentation/README.md
- sigs.yaml
@kubernetes/sig-instrumentation-misc
> Add mission statement for sig-instrumentation

- contributors/devel/security-release-process.md
> Add public key for liggitt

- contributors/devel/security-release-process.md
Public key has been updated with the new identities.
> s/Tim St\. Clair/Tim Allclair/g

- contributors/devel/release/scalability-validation.md
This outlines details of a new/improved scalability validation process for the release.
cc @kubernetes/sig-release-misc  @kubernetes/sig-scalability-misc @dchen1107 @thockin @wojtek-t @gmarek
> Document scalability validation process for release

- contributors/design-proposals/auditing.md
Sync the proposal with the implementation.
> Update advanced audit proposal with policy decisions

- contributors/devel/on-call-federation-build-cop.md
This is a first draft. It still needs:
1. Responsibilities section.
2. More entries in the playbook.
I will be adding those sections in follow up PRs.
/assign @csbell @nikhiljindal @perotinus
> First draft of federation buildcop guide/playbook.

- contributors/design-proposals/hugepages.md
Adding support for applications requiring hugetlbfs.
> Adding huge page volume plugin.

- community/K8sYoutubeCollaboration.md
Added Jorge Castro from Heptio as new PoC for YouTube changes
> Update contact info for new PoC

- sig-scalability/thresholds.md
@kubernetes/sig-scalability-pr-reviews @kubernetes/sig-scalability-api-reviews 
@smarterclayton @jeremyeder @timothysc @countspongebob @gmarek @shyamjvs
> Initial version of scalability thresholds

- contributors/devel/local-cluster/docker.md
outdate link that hint 404 error!
> outdate link

- contributors/design-proposals/dynamic-kubelet-configuration.md
We've decided against Verifiable ConfigMaps for now. RBAC should be
sufficient to protect against accidental mutation (e.g. only give
mutation permissions to a controller and interact with config
through that controller).
See this doc for more details:
https://docs.google.com/a/google.com/document/d/1yYmyYJu2mVqgOBPCSd2c_IPnGWItirbcN_5qbJaWZN0/edit?usp=sharing
Join kubernetes-dev@googlegroups.com for access to the doc.
See also the related kubernetes-dev thread:
https://groups.google.com/forum/#!topic/kubernetes-dev/gMBc3NkZ6Gs
> Remove hash verification mechanism from proposal

- contributors/devel/issues.md
Change numerical priorities of issue to verbose ones and fix a missing space as
discussed under,
https://github.com/kubernetes/community/pull/787
> Change numerical priorities to verbose

- sig-architecture/README.md
- sig-architecture/charter.md
- sigs.yaml
Write up charter as discussed so far.
cc @kubernetes/sig-architecture-proposals @kubernetes/sig-architecture-pr-reviews
> Initial draft of SIG architecture charter

- contributors/devel/pull-requests.md
Fixes: https://github.com/kubernetes/community/issues/831
> Remove incorrect contents in pull-requests.md

- contributors/design-proposals/aggregated-api-servers.md
update outdated links such as resource quota，limit range and namespace etc.
> update outdated links

- contributors/design-proposals/taint-node-by-condition.md
This is the design doc of https://github.com/kubernetes/kubernetes/issues/42001; the google doc is: https://docs.google.com/document/d/15Mg2GgxumUh9wQjc3LgalDeTUsVsBpfjQaBK4QB66-k/edit?usp=sharing
/cc @gmarek , @jamiehannaford, @luxas
> Desig doc of 'Taint node by condition'.

- Makefile
- hack/verify.sh
This adds a verify make target to let (future) CI check for changes.
cc: @jamiehannaford
> Add verify make rule

- contributors/devel/kubectl-conventions.md
This PR fixes a spelling mistake and a grammatical error within a single sentence.
> Fix minor typo

- contributors/design-proposals/cpu-manager.md
- Added a note about the CPUPressure node condition.
- Added a note about when pod evictions are necessary.
> Updated interface sketches to match implementation

- contributors/devel/owners.md
Move from design doc to state-of-the-world doc
The OWNERS feature has been implemented for a while now. Let's
document how it actually works
I originally started this with the intent of fleshing out measurable
critera for adding/removing OWNERS, but as I dug into it, I realized I
need more time to explore useful metrics.  Let's find out if this is
enough of a rewrite to call incremental progress
ref: https://github.com/kubernetes/test-infra/issues/1966
> Rewrite OWNERS docs

- contributors/devel/local-cluster/local.md
> Update golang version

- sig-storage/README.md
> Update storage link to docs

- contributors/devel/local-cluster/local.md
I can't access http://issue.k8s.io/6667. 
https://github.com/kubernetes/kubernetes/issues/6667 is OK
> Update issue link.

- contributors/devel/controllers.md
> format the code in controller.md

- sig-cluster-lifecycle/README.md
- sig-on-premise/README.md
the space code cann't been parsed by markdown。
od -c README.md command output
> fix space code

- contributors/design-proposals/api-group.md
Fix invalid url-link in  `contributors/design-proposals/api-group.md`.
> Fix invalid url-link in  contributors/design-proposals/api-group.md

- sig-big-data/resources.md
Update to include Airflow as a project under sig-big-data
> Update to include Airflow as a project under sig-big-data

- contributors/design-proposals/extending-api.md
remove unnecessary  "**`**"  in contributors/design-proposals/extending-api.md
> Fix: remove unnecessary ` in contributors/design-proposals/extending-api.md

- contributors/design-proposals/cpu-manager.md
xref https://github.com/ConnorDoyle/kubernetes/pull/19
cc @sjenning
> Updated cpu manager Policy and State interfaces.

- contributors/design-proposals/cpu-manager.md
re #950 -- forgot to update the block diagram image.
cc @sjenning
> Update interfaces in cpu manager block diagram.

- contributors/design-proposals/cpu-manager.md
> fix typos in cpu-manager proposal

- contributors/design-proposals/high-availability.md
> fix bad url in high-availability.md

- generator/sig_readme.tmpl
- sig-openstack/README.md
This does the same thing as #941 but updates the template so that the change won't revert
> Fix whitespace issue with template

- contributors/devel/flexvolume.md
Based on code (hmmm...), clarify that wait for attach should wait up to 10 minutes.
> Update wait for attach - clarify it's up to 10m

- contributors/design-proposals/apiserver-build-in-admission-plugins.md
this PR adds an example that highlights relevant parts of source code from sample apiserver that deals with admission registration.
close #47868
> provides an example on how to register custom admission plugin.

- contributors/devel/go-code.md
This PR fixes a few minor typos and grammatical errors in the docs.
> Fix minor typos and grammar

- CLA.md
> [minor] Grammar

- contributors/design-proposals/grow-volume-size.md
> Fix typo: kubelet

- contributors/devel/api_changes.md
Fix some wording.
Remove the demand for validation to fail.  It also says to clearthose
fields, which more closely models non-existent fields.
Change the tombstone (proposed - nobody is using this yet, obviously).
This format matches what gengo uses for other tags.
> Update the docs around alpha fields & deprecating

- contributors/devel/generating-clientset.md
> https://github.com/kubernetes/kubernetes/tree/master/pkg/client/clientset_generated/clientset/typed/core/v1/pod_expansion.go
> to
> https://github.com/kubernetes/kubernetes/blob/master/pkg/client/clientset_generated/internalclientset/typed/core/internalversion/pod_expansion.go
> fix broken link 

- incubator.md
OWNERS File - 2 places - pointing to the links
line 'kubernetes incubator' pointing to link
Reworded template project line pointing to link.
> incubator.md - making some links pointing to the right places.

- contributors/devel/how-to-doc.md
> fix bad url in how-to-doc.md

- contributors/design-proposals/flexvolume-deployment.md
Made it explicit that driver uninstalls are allowed, and cautioned against uninstalling while a volume depends on the driver.
/sig storage
/assign @chakri-nelluri @saad-ali
> Flexvolume Dynamic Plugin Discovery: Added comments about possible driver installation actions

- contributors/design-proposals/daemon.md
> Fix the format of yaml

- contributors/design-proposals/sig-storage/OWNERS
/cc @kubernetes/sig-storage-pr-reviews
> Add OWNERS for sig-storage design proposals

- committee-steering/calebamiles_bio.md
**cc: @castrojo, @sarahnovotny**
> Adds bio and steering committee platform for caleb miles

- committee-steering/calebamiles_bio.md
> Fixes typo in Caleb Miles' bio for the steering committee

- committee-steering/calebamiles_bio.md
> trims bio for caleb miles to the proper length

- contributors/design-proposals/cpu-manager.md
- Describe new `--cpu-manager-reconcile-period` flag.
- Describe node allocatable requirements for static policy.
- Remove references to CPU pressure and node condition.
- Update interface sketches.
- Update block diagram image.
- Expand static policy description.
> Update cpu-manager doc to match implementation.

- contributors/devel/bazel.md
Covers set of packages for commonly used distributions for  kubernetes/kubernetes#51623
> Document set of host dependencies for bazel-build

- contributors/devel/pull-requests.md
Add commentary on WIP title prefixes
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
Add the /hold and /hold cancel commands to PR doc
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
---
xref: https://github.com/kubernetes/test-infra/pull/4206 https://github.com/kubernetes/test-infra/pull/4145
/cc @xiangpengzhao
> Update pull request document with new features

- voters-guide-2017.md
> Create Voters Guide 2017

- contributors/design-proposals/cpu-manager.md
> Fix note about reservations in cpu-manager.md.

- contributors/design-proposals/device-plugin.md
@RenaudWasTaken @jiayingz PTAL.
> Minor fix quick link

- community/elections/2017/README.md
- community/elections/2017/rhirschfeld_bio.md
Here is my bio for Steering Committee elections.
As per request of @parispittman
> Rob Hirschfeld BIO for election

- community/elections/2017/README.md
- community/elections/2017/timothysc_bio.md
Adds bio to steering election 
/cc @castrojo
> timothysc bio

- community/elections/2017/README.md
Avoid setting up a promise that may be difficult to meet technically.
> Election: Avoid commitment to _immediately_ publish

- community/elections/2017/README.md
- community/elections/2017/sebastiengoasguen_bio.md
Adds sebastien goasguen's bio to the ballot table :)
> add sebgoa

- README.md
Signed-off-by: sakeven <jc5930@sina.cn>
The link of architecture is broken. Just fix it.
> fix architecture link

- contributors/design-proposals/resource-management/device-plugin.md
@RenaudWasTaken @jiayingz PTAL :)
> Minor fix typo

- contributors/design-proposals/federation/federated-api-servers.md
update aggregated-api-servers.md link which has been moved to api-machinery
> update aggregated-api-servers.md link

- contributors/devel/flexvolume.md
> fix bad link

- contributors/devel/pull-requests.md
1.  Remove the title link
2.  Modify the links which don't work
> Clean up the bad link

- contributors/design-proposals/resource-management/device-plugin.md
@vishh @RenaudWasTaken PTAL :-)
> Minor fix format

- contributors/design-proposals/resource-management/hugepages.md
@derekwaynecarr @sjenning PTAL :-)
> Highlight keywords and fix typo

- sig-apps/README.md
@prydonius @michelleN Trying to make these meetings just a little more findable.
> Adding SIG Apps subgroup meeting details for helm and charts

- generator/app.go
Just nit picking a spelling mistake
> Fixed spelling error

- contributors/design-proposals/scheduling/podaffinity.md
Signed-off-by: Ce Gao <ce.gao@outlook.com>
> podaffinity.md: Fix a broken link

- contributors/devel/how-to-doc.md
> fix link in how-to-doc.md

- contributors/devel/development.md
- contributors/devel/godep.md
This corresponds to https://github.com/kubernetes/kubernetes/pull/51766 - do not merge until we get confirmation on that PR.
> Rewrite docs on godep

- contributors/devel/release/issues.md
The bot changes are still in review:  https://github.com/kubernetes/test-infra/pull/4433
> Update active milestone issues process to reflect bot changes

- sig-scalability/README.md
Updating Scalability page to reflect shift to biweekly schedule.
> Updating Scalability page to reflect shift to biweekly schedule.

- contributors/design-proposals/apps/cronjob.md
As requested by @soltysh, in relation to https://github.com/kubernetes/kubernetes/issues/47538.
> Add section on manually triggering CronJobs

- contributors/devel/security-release-process.md
cc @philips @cjcullen @tallclair @liggitt 
First draft based off items in http://oss-security.openwall.org/wiki/mailing-lists/distros
> Security Process: Add Distributors List Process

- sig-federation/ONCALL.md
All this info was in our oncall calendar invite.
This will make it easily accessible to everyone.
cc @quinton-hoole @csbell
> Adding ONCALL.md with details about our oncall rotation

- contributors/devel/api_changes.md
This PR makes some improvements to the `api_changes.md` doc:
- update path to files and links
- remove Google Analytics footer
- tiny formatting improvement
CC @simo5
> contributors/devel/api_changes.md: assorted improvements

- contributors/devel/kubectl-conventions.md
@fabianofranz @smarterclayton @pwittrock @kubernetes/sig-cli-maintainers
> add draft exit code to kubectl-conventions

- community/office-hours.md
Adding a file for the time and specifics for the k8s office hours.
> Add k8s office hours

- contributors/design-proposals/api-machinery/api-chunking.md
> fix spelling error

- contributors/design-proposals/api-machinery/apiserver-build-in-admission-plugins.md
> word spell mistake

- contributors/design-proposals/api-machinery/apiserver-count-fix.md
> change tecnical to technical

- contributors/design-proposals/api-machinery/dynamic-admission-control-configuration.md
update lot of misspelled word to initializer
> update lot of misspelled word to initializer

- contributors/design-proposals/api-machinery/bulk_watch.md
update bulk_watch.md many misspelled words
> update bulk_watch.md many misspelled words

- contributors/design-proposals/api-machinery/aggregated-api-servers.md
update form "replicatable" to "replicable"
> update aggregated-api-servers.md spelling mistake

- contributors/design-proposals/architecture/architecture.md
> Fix Ingress controller broken link

- sig-scalability/provider-configs.md
This is a little cryptic to someone with no AWS experience.
> Expand AZ acronym.

- community/elections/2017/aaroncrickenberger_bio.md
> revise spelling mistake

- contributors/devel/flaky-tests.md
> Fixing typo

- contributors/devel/automation.md
They seem to be saying the same thing.
> Merge two paragraphs.

- community/office-hours.md
This text comes for a previously authored document that was peer reviewed by sig-contribex.
> Add more event detail

- contributors/devel/scalability-good-practices.md
See #1197 for discussion.
/hold
@castrojo please /hold cancel once you actually rename
> Change channel name for the rename.

- sig-cli/outreachy.md
Ref: #1227
cc @sarahsharp @sarahnovotny @castrojo @cblecker
> Update Outreachy program deadline and link

- contributors/devel/pull-requests.md
Update to latest process. Test in https://github.com/kubernetes/kubernetes/pull/53785
ref:
https://github.com/kubernetes/test-infra/pull/4718
https://github.com/kubernetes/kubernetes/pull/54114
/cc @cjwagner @Bradamant3
> Update release note process

- community/2017-events/12-dev-summit/ContribSummitInformation.md
- community/2017-events/12-dev-summit/information.md
Added preliminary information
@castrojo
> Update Information file

- contributors/devel/development.md
Update Go version required by Kubernetes
> Update Go version required by Kubernetes

- contributors/design-proposals/api-machinery/dynamic-admission-control-configuration.md
https://github.com/kubernetes/community/pull/1191 was accidentally merged
> Revert initializer namespace selector change

- contributors/design-proposals/storage/volume-metrics.md
@verult PTAL, thanks! https://github.com/kubernetes/kubernetes/pull/50036#issuecomment-338079916
> Update volume operations metric names as implemented

- contributors/design-proposals/api-machinery/thirdpartyresources.md
- contributors/design-proposals/apps/controller_history.md
- contributors/design-proposals/apps/cronjob.md
- contributors/design-proposals/apps/stateful-apps.md
- contributors/design-proposals/architecture/1-kubernetes-enhancement-proposal-process.md
> update misspelled words and code block

- contributors/design-proposals/auth/image-provenance.md
- contributors/design-proposals/auth/no-new-privs.md
- contributors/design-proposals/autoscaling/hpa-status-conditions.md
> fixed misspelling

- contributors/design-proposals/cli/apply_refactor.md
- contributors/design-proposals/cli/multi-fields-merge-key.md
> some mistake spelling

- contributors/design-proposals/config-conventions.md
This is an oldish doc that is just now being converted into a proposal.
https://docs.google.com/document/d/1arP4T9Qkp2SovlJZ_y790sBeiWXDO6SG10pZ_UUU-Lc/edit#heading=h.xgjl2srtytjt
> document component config conventions

- contributors/devel/bazel.md
It has been a while since this was last updated.
> Update bazel documentation

- contributors/design-proposals/node/troubleshoot-running-pods.md
This leaves reporting command & args of Ephemeral Containers for a future proposal.
> Simplify Container Status for Ephemeral Containers proposal

- contributors/design-proposals/cloud-provider/cloud-provider-refactoring.md
- contributors/design-proposals/node/kubelet-cri-logging.md
> update cloud-provider-refactoring.md and kubelet-cri-logging.md

- sig-api-machinery/design-docs/admission-control-webhooks.md
I will send another PR making adjustments.
> First draft from the 2017-10-11 SIG meeting.

- OWNERS_ALIASES
> Fix spacing in OWNERS_ALIASES file

- contributors/design-proposals/instrumentation/monitoring_architecture.md
> Fix broken link in monitoring_architecture.md

- contributors/design-proposals/api-machinery/admission-control-webhooks.md
Adding the synopsis of a naming thread to the webhook's design document.
> Adding naming discussion details to the design document.

- contributors/design-proposals/api-machinery/admission-control-webhooks.md
Changes to the doc since it was agreed on, builds on #1280.
> Webhook proposal up to date

- contributors/design-proposals/storage/raw-block-pv.md
> Version 2 for Raw Block Devices

- contributors/devel/component-config-conventions.md
* strip some of the design proposal cruft
* make recommendation on config group naming
@bgrant0607 @mtaufen @ncdc
> config: move config proposal to developer docs

- contributors/design-proposals/architecture/namespaces.md
Could someone make sure I linked to the correct docs
> Links now work

- contributors/design-proposals/api-machinery/aggregated-api-servers.md
Fix the path of api-conventions doc.
> Fix the path of api-conventions doc.

- contributors/design-proposals/api-machinery/admission-control-webhooks.md
Fill in areas that were lacking.
> Webhook upgrade

- contributors/design-proposals/api-machinery/admission-control-webhooks.md
> small change

- contributors/design-proposals/architecture/principles.md
> Ms4720 issue 1317

- contributors/design-proposals/multicluster/control-plane-resilience.md
Fix some errors in control-plane-resilience.md
> Fix some errors in control-plane-resilience.md

- contributors/design-proposals/instrumentation/custom-metrics-api.md
I don't think `dimenisionality` is right spell, should be `dimensionality`.
> fixed dimenisionality to dimensionality

- contributors/design-proposals/autoscaling/initial-resources.md
> fix invalid link for initial-resources.md

- contributors/design-proposals/storage/local-storage-pv.md
Moving the doc https://docs.google.com/document/d/1hRRzZpWtbHyJC1lotE8rqp2h1NEXuFv-rAW-vLuQa94/edit?usp=sharing into this block pv document.
cc @msau42
> Add  provisioner changes to support block dev

- contributors/devel/godep.md
This was missed in the last rewrite.
> Add staging godeps to godep instructions

- contributors/devel/api_changes.md
- contributors/devel/generating-clientset.md
Documentation counterpart PR for https://github.com/kubernetes/kubernetes/pull/54950.
> contributors/devel: document '// +groupGoName' code-generation tag

- contributors/design-proposals/architecture/architecture.md
- contributors/design-proposals/auth/apparmor.md
> fix links to CRI. issue #1391

- contributors/devel/release/scalability-validation.md
> Some minor wording fixes.

- contributors/design-proposals/auth/secrets.md
Maybe these links have been invalid, I try to fix them.
> Fixed invalid link

- communication.md
Pointing people to Kubernetes Office Hours from general Communicating doc.
> added office hours to communication

- community/2017-events/12-dev-summit/ContribSummitInformation.md
> Update Contributor Summit Info

- contributors/design-proposals/architecture/0000-kep-template.md
This is based on input from @timothysc.  Still need to reconcile this with the instructions.
> KEP template update

- contributors/design-proposals/multicluster/cluster-registry/api-design.md
> The federation has been moved to an independent repo.

- contributors/devel/release/README.md
fixed three spelling mistakes in contributors/devel/release/README.md
> fix spelling mistakes

- contributors/devel/release/scalability-validation.md
Following from https://github.com/kubernetes/test-infra/pull/5532
/cc @porridge
> Update scalability-validation doc to reflect current job schedule

- contributors/design-proposals/architecture/architecture.md
The GCE ingress controller was moved to github.com/kubernetes/ingress-gce.
> fix broken links

- contributors/devel/on-call-federation-build-cop.md
Killed Jenkins section, updated a few links and rerun section.
/assign @madhusudancs
> Update some test-infra related doc for federation oncall page

- contributors/guide/README.md
Minor fix typos, @guineveresaenger @cblecker @idvoretskyi @stp-ip PTAL, Thanks!
> Minor fix typos

- contributors/design-proposals/node/resource-qos.md
fix invalid links on resource-qos.md
Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>
> resource-qos: fix invalid links

- sig-apps/README.md
/cc @prydonius @michelleN 
While prepping for the SIG Apps update at Kubecon I noticed the goals were a bit dated and could use a little grammar love.
> Updating the SIG Apps goals to reflect current state

- contributors/design-proposals/architecture/architecture.md
> Fixes relative link to Architectural Roadmap

- contributors/devel/on-call-federation-build-cop.md
/assign @madhusudancs @krzyzacy 
/cc @kubernetes/sig-multicluster-pr-reviews
> Update on-call-federation-build-cop.md with current state

- contributors/devel/welcome-to-kubernetes-new-developer-guide.md
Fixes https://github.com/kubernetes/website/issues/5952
> add some words about keeping Slack and GitHub handles in sync

- contributors/devel/kubectl-conventions.md
> fix misspelling

- contributors/design-proposals/scheduling/nodeaffinity.md
- contributors/design-proposals/scheduling/podaffinity.md
- contributors/design-proposals/storage/raw-block-pv.md
- contributors/devel/architectural-roadmap.md
Minor fix markdown format while reading design proposal.
> Minor fix markdown format

- contributors/design-proposals/autoscaling/hpa-v2.md
hpa-v2.md:  fix invalid links
Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>
> hpa: fix invalid links

- sig-governance.md
Updating after communicating with @sarahnovotny
> Updating calendar directions so they work

- sig-apps/README.md
> Updating the SIG Apps sub-meeting details

- mentoring/README.md
Signed-off-by: parispittman <parispittman@google.com>
> adding mentoring folder to collect initiative docs

- community/2017-events/12-contributor-summit/ContribSummitInformation.md
> update contrib summit info

- code-of-conduct.md
closes https://github.com/kubernetes/community/issues/1414
We do not have this file in this repo.
> adding code-of-conduct.md

- community/2017-events/12-contributor-summit/container-identity.md
- community/2017-events/12-contributor-summit/enabling-kubernetes-ecosystem.md
- community/2017-events/12-contributor-summit/feature-roadmap-2018.jpg
- community/2017-events/12-contributor-summit/feature-roadmap-2018.md
- community/2017-events/12-contributor-summit/feature-workflow.md
- community/2017-events/12-contributor-summit/onboarding-new-developers-through-better-docs.md
- community/2017-events/12-contributor-summit/should-k8s-use-feature-branches.md
- community/2017-events/12-contributor-summit/steering-committee-update.md
- community/2017-events/12-contributor-summit/whats-up-with-sig-cluster-lifecycle.md
This will be an ongoing PRfest! Fixes to formatting and general copyediting would be most appreciated.
> Initial commit of summit notes

- community/2017-events/12-contributor-summit/cloud-native-design-refactoring-across-k8s.md
- community/2017-events/12-contributor-summit/current-state-of-client-libraries.md
- community/2017-events/12-contributor-summit/scaling-up-and-scaling-down-and-addon-management.md
This is an initial commit of the contributor summit notes.
> Add contributor summit notes

- community/OWNERS
- monitoring/OWNERS
Adds an OWNERS file to the mentoring directory, and updates the OWNERS for the community directory (mostly for event information and such)
> Add some more OWNERS files

- community/2017-events/12-contributor-summit/breaking-up-the-monolith.md
> Fix formatting of this article

- community/office-hours.md
I'd like to put this on the page in addition to the email announcements since we announced this page heavily during kubecon.
> Update for the holiday schedule

- OWNERS
Reasoning: I helped create / populate this repo originally, and I'm a member of the steering committee.
I'm also fine being told no, but trying to help reduce bottlenecks that hit root.
> Add spiffxp to root OWNERS

- contributors/guide/README.md
The File an Issue section is work in progress. Adding more detail with a broader
coverage on what to file, why and where to file a issue to complete this section.
> Complete File an Issue section

- sig-cli/CONTRIBUTING.md
> fix dead link

- contributors/devel/welcome-to-kubernetes-new-developer-guide.md
As per #sig-contribex, let's not break URLs (yet).
> Add a redirect

- contributors/devel/README.md
> developer README points to new contrib guide

- mentoring/group-mentoring.md
Was looking for membership information and came across a broken link.
> fixing broken link

- contributors/design-proposals/storage/volume-topology-scheduling.md
> Fix broken link

- contributors/devel/staging.md
> Add contributors/devel/staging.md

- contributors/design-proposals/storage/local-storage-overview.md
The Error: `unknown object type schema.GroupVersionKind{Group:"", Version:"v1", Kind:"pod"}`
> unknown object type schema.GroupVersionKind

- events/office-hours.md
This effectively resets the page for 2018, Happy New Year!
> Update information for 2018

- contributors/guide/README.md
> fixes broken link to github workflow

- contributors/guide/github-workflow.md
Fix broken links in github-workflow.md
> Fix broken links in github-workflow.md

- project-managers/README.md
ref: kubernetes/kubernetes#57689
> Drop reference to kubernetes/kubernetes/wiki

- sig-docs/README.md
- sigs.yaml
Update sig-docs with link to sig-docs-pr-reviews.
> add sig-docs-pr-reviews link

- communication/slack-guidelines.md
Apologies for the pedantry, just read through the doc after the link from the community meeting, and wanted to fix up a couple minor grammar/spelling issues.
> minor grammar and spelling fixes

- wg-cloud-provider/draft-20171128-controller-manager.md
Adding the rough draft of the cloud-provider KEP document.
> Adding the rough draft of the cloud-provider KEP document.

- contributors/guide/README.md
- mentoring/README.md
Fixes some broken links (and their surrounding content, as necessary).
@chenopis PTAL, thanks!
> [quick fix] Revise broken links

- communication.md
> Fix slack signup link

- mentoring/README.md
- mentoring/google-summer-of-code.md
- sig-cli/outreachy.md
Add Google Summer of Code page.
xref https://github.com/cncf/soc/issues/22.
/assign parispittman idvoretskyi
> Add Google Summer of Code page

- contributors/devel/testing.md
Update the instructions for installing etcd. The location of the etcd.manifest has changed, as cluster/saltbase was deprecated.
> Update the instructions for installing etcd

- contributors/guide/README.md
* Remove the working comments from the top so users can just get to the content
* Remove inline todos and replace with link to labelled issues
> Make the index more user-facing by removing draft notes

- keps/sig-apps/OWNERS
- keps/sig-apps/README.md
Adds a KEPs directory for sig-apps
> add sig-apps keps directory

- contributors/design-proposals/instrumentation/custom-metrics-api.md
> Fix dead link to HPA v2

- mentoring/group-mentee-guide.md
modified info to the dev areas section
> Update dev areas

- contributors/devel/api-conventions.md
> fix a bad punctuation

- sig-apps/README.md
- sigs.yaml
Old link was to meeting minutes that are out of date
/cc @michelleN
> Update helm dev meeting minutes

- contributors/devel/event-style-guide.md
I got reminded by @bgrant0607 that I forgot to put this into markdown. I'm fixing this omission now.
cc @timothysc @smarterclayton @bgrant0607 @kubernetes/sig-instrumentation-misc
> Add Event style guide for Events v2

- contributors/guide/coding-conventions.md
Fixes broken links in coding-conventions.md
> fixing more links

- communication.md
> Fixing link to communication doc

- contributors/guide/contributor-cheatsheet.md
Even the existing one is working, the updated is more correct.
> Updated k8s devstats link

- contributors/design-proposals/multi-platform.md
> fix typo in multi-platform.md

- contributors/design-proposals/scheduling/pod-preemption.md
> Fix a typo in pod-preemption.md

- contributors/design-proposals/api-machinery/bulk_watch.md
> fix a typo in bulk watch

- contributors/design-proposals/storage/local-storage-pv.md
Small typo fix in the local storage persistent volumes proposal.
> doc: Small typo fix in the local storage persistent volumes proposal

- contributors/design-proposals/storage/volume-topology-scheduling.md
Describing the PV NodeAffinity here instead of in the local storage design document, since this is more generic and can apply to any volume type.
> Formalize volume topology specification

- community-membership.md
- sig-cli/CONTRIBUTING.md
> Remove references to outside collaborators

- events/2018/05-contributor-summit/README.md
This is mostly a placeholder for now but will let us announce and socialize the event early.
> Initial commit for Contrib Summit 2018 EU

- events/office-hours.md
This change points people to Meet Our Contributors if they're interested
in development topics.
> Add contributor/developer topics as offtopic

- committee-steering/OWNERS
- communication/OWNERS
- contributors/design-proposals/OWNERS
- contributors/guide/OWNERS
- generator/OWNERS
- hack/OWNERS
This will better help label PRs that touch these :)
> Add some labels to directory OWNERS files

- contributors/devel/e2e-tests.md
Signed-off-by: taoyu27 <yutao@chinacloud.com.cn>
> fix broken link in e2e-tests.md

- contributors/devel/profiling.md
This documents steps that I found useful when working on performance improvements with [#57215](https://github.com/kubernetes/kubernetes/pull/57215).
> Add tips for profiling tests

- contributors/guide/README.md
With an example, people can better see how labels work
> Contains example for adding a SIG label

- contributors/design-proposals/cloud-provider/cloud-provider-refactoring.md
>  fix a typo

- sig-contributor-experience/markdown-link-style-guide.md
I said I'd do this.. two weeks ago? But finally got a chance to write some of these style guidelines down. We can move these around, or change them later.. but at least this is written down somewhere :)
"if it can't be automated, it better be documented"
/assign @guineveresaenger @parispittman
> Add markdown style guide

- contributors/design-proposals/api-machinery/apiserver-count-fix.md
- contributors/design-proposals/api-machinery/bulk_watch.md
- contributors/design-proposals/api-machinery/server-get.md
> fix some duplication problems in api-machinery

- contributors/design-proposals/apps/cronjob.md
> fix a duplication problem

- contributors/design-proposals/multicluster/federated-ingress.md
> fix a duplication problem in federated-ingress.md

- contributors/design-proposals/cluster-lifecycle/self-hosted-kubernetes.md
> Fix duplication problem in self-hosted-kubernetes.md

- contributors/design-proposals/multi-platform.md
fix invalid links for golang.sh
Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>
> fix invalid links for golang.sh

- contributors/design-proposals/resource-management/gpu-support.md
> fix a duplication problem in gpu-support.md

- contributors/devel/pull-requests.md
[Before](https://git.k8s.io/test-infra/commands.md)
[After](https://go.k8s.io/bot-commands)
> Update link for the commands doc

- contributors/design-proposals/node/troubleshoot-running-pods.md
> fix a duplication problem in troubleshoot-running-pods.md

- contributors/design-proposals/resource-management/resource-quota-scoping.md
- contributors/design-proposals/scheduling/rescheduling.md
> fix a duplication problem in resource-quota-scoping.md

- sig-scheduling/README.md
- sigs.yaml
> fix wrong link

- org-owners-guide.md
@kubernetes/sig-contributor-experience-pr-reviews
ref: https://groups.google.com/a/kubernetes.io/d/msg/steering/qnZuXlqK44Y/ugGn8lXdAwAJ
> Add team guidance section to org-owners-guide

- README.md
> Updates community Readme

- contributors/devel/godep.md
Add section to godeps doc talking about the procedure to review/approve dependency changes.
/assign @thockin
> Add section on reviewing/approving godeps

- sig-multicluster/README.md
- sigs.yaml
Fix some errant whitespace in sig-multicluster
> Fix whitespace for sig-multicluster

- contributors/design-proposals/scheduling/pod-priority-resourcequota.md
This is a design doc for priority in resource quota.
Ref: https://github.com/kubernetes/kubernetes/issues/48648
/assign @bsalamat to make sure everything is on the right track.
cc @kubernetes/sig-scheduling-pr-reviews
> [Proposal] Design doc for priority in resource quota

- contributors/design-proposals/api-machinery/aggregated-api-servers.md
> Fix typo in aggregated-api-servers.md doc

- contributors/guide/github-workflow.md
> Complete Install etcd in GitHub Workflow

- events/2018/05-contributor-summit/README.md
Fixes #1820 
cc @jberkus @parispittman @idvoretskyi
> Add draft schedule

- contributors/devel/README.md
> Rename this to a table of contents

- CLA.md
> chore(*): fix typos

- communication/README.md
> Updating office hours url

- OWNERS_ALIASES
- generator/app.go
- generator/app_test.go
- hack/verify.sh
Not super pretty, but it works.
> Add ability to have custom content in OWNERS_ALIASES

- contributors/design-proposals/storage/volume-topology-scheduling.md
Update volume topology design doc with:
* Defining terms used to describe topology
* Dynamic provisioning new APIs
* In-tree and external provisioning interface changes
* Scheduler implementation details
* Examples for local, zonal, and multi-zonal volumes
@kubernetes/sig-storage-pr-reviews
> Topology aware dynamic provisioning design

- contributors/design-proposals/storage/volume-topology-scheduling.md
Reverts kubernetes/community#1855
> Revert "Topology aware dynamic provisioning design"

- sig-product-management/SIG PM representatives.md
I am a sig network member and currently is responsible for kube-proxy IPVS work. I am a full-time open source software engineer and have a team from huawei.
I have contributed 150+ commits to Kubernetes core repo and mainly focus on network area.
I would like to contribute other than just writing codes. For example, I am keeping attending SIG-Network meeting so I can identify all features in the current release from the SIG-Network and track all features.
cc @dcbw @cmluciano @caseydavenport @thockin @quinton-hoole @deepak-vij
> Add m1093782566 as secondary PM on behalf sig network

- contributors/devel/cri-testing-policy.md
@kubernetes/sig-node-proposals 
@dchen1107 @derekwaynecarr
> Add CRI testing policy

- sig-storage/volume-plugin-faq.md
Not sure if this is the best header to add, but the last two questions shouldn't be in the FlexVolume section.
/sig storage
/assign @saad-ali
> Adding header to last few questions of volume plugin faq

- sig-apps/README.md
- sigs.yaml
/ref #1869 to address remaining deficiencies.
> Update kubernetes code base ownership of sig app

- contributors/devel/container-runtime-interface.md
> update the link of cri api proto

- contributors/design-proposals/apps/controller_history.md
> fix: some typo

- contributors/guide/README.md
> fix a typo in the Contributor Guide readme

- community-membership.md
I had no idea about these and only found out about them when @nikhita told me on chat. I figured it'd be useful for other new members to have these specifically pointed out to them.
Feel free to suggest different wording, or add anything we missed.
> Added privileges to Responsibilities and privileges section

- communication/K8sYoutubeCollaboration.md
This was breaking people's ability to add videos to the collaboration
playlists.
Updating contact information for youtube support.
> Add instructions for people using gsuite accounts

- README.md
- governance.md
First stab on getting some mention of subprojects into our docs. Will follow up with more details.
> Add subprojects

- contributors/design-proposals/node/kubelet-eviction.md
This is a proposal containing different possible solutions for https://github.com/kubernetes/kubernetes/issues/51745.
My intention is to converge on a single solution, and incorporate that into the documentation.
This proposal assumes https://github.com/kubernetes/kubernetes/pull/56112 is accepted.  Work would be targeted for 1.10.
Please share thoughts/concerns, or propose additional solutions I have not thought of.
cc @vishh @derekwaynecarr @sjenning @kubernetes/sig-node-proposals
> Propose solution to make memory cgroup events effective.

- keps/sig-network/README
> Create new KEP directory for SIG Network with just a README for now.

- org-owners-guide.md
Updated https://github.com/kubernetes/community/pull/1754
cc @spiffxp
> Updated list of Kubernetes organizations

- README.md
Update link to communication page and fix typo.
> Minor edits to community README

- contributors/devel/gubernator.md
- contributors/guide/pull-requests.md
Change `k8s-merge-robot` to `k8s-ci-robot`
> Change k8s-merge-robot to k8s-ci-robot

- events/2018/05-contributor-summit/README.md
> Add registration information for the contributor summit

- sig-apps/README.md
- sigs.yaml
cc @kubernetes/helm-maintainers
> [sig-apps] updates Helm meeting notes/agenda link

- OWNERS_ALIASES
- committee-steering/OWNERS
> adding alias for SC

- keps/sig-contributor-experience/0005-community-site.md
- keps/sig-contributor-experience/0005-contributor-site.md
This is a concrete proposal on how we can implement a community site.  I'm looking forward to a healthy discussion around this proposal.
> Add more details and a concrete proposal for KEP-5

- contributors/design-proposals/instrumentation/monitoring_architecture.md
> Add hyperlink to the referenced issue

- OWNERS
- OWNERS_ALIASES
- generator/OWNERS
- alpha sort steering-committee alias
- Update top-level OWNERS with steering-committee alias
- Update sig docs generator OWNERS
> Update a few OWNERS files

- contributors/design-proposals/api-machinery/synchronous-garbage-collection.md
- contributors/design-proposals/resource-management/gpu-support.md
Correct some spelling mistakes
> fix some typo

- contributors/devel/flexvolume.md
Signed-off-by: yanxuean <yan.xuean@zte.com.cn>
> correct the link to nginx.yaml for flexvolume

- sig-contributor-experience/community-maintenance.md
Adding a few community meeting items before we start our first audit!
> Add section on the community meeting

- keps/sig-contributor-experience/0005-contributor-site.md
This is a final call for comments and tweaks to KEP 5 before we move forward with implementation. Please let me know of any last concerns or tweaks that need to be made.
(Obviously, we can change things if this isn't working, but this marks that we are confident enough in this plan to start implementing it.  Experience with that can lead to further modifications here or abandoning this KEP altogether.)
> Move KEP-5 to implementable

- community-membership.md
> fix grammar mistake

- contributors/design-proposals/scheduling/pod-priority-resourcequota.md
> fix AdmissionConfiguration yaml format

- sig-governance.md
> Add sig lead list reference, update slack admin information

- contributors/devel/testing.md
> Add note on KUBE_TIMEOUT to resolve timeout panic

- mentoring/mentor-guide.md
appreciate comments - this is a work in progress; there are some minor grammar errors that I see and white space issues that I will change after comments. 
/hold
> add docs for mentorguidelines.md

- sig-storage/contributing.md
Current link points to issues + PRs, update it to point to open issues for the label `sig/storage`.
> Update issue link for sig/storage

- sig-contributor-experience/projects.md
Correction to GH handle for @chris-short (I know, it's confusing for me too)
Signed-off-by: Chris Short <chris@chrisshort.net>
> projects.md: Typo

- wg-machine-learning/README.md
ran `make WHAT=wg-machine-learning`
> Fix typo in wg-machine-learning readme.

- contributors/devel/flexvolume.md
> Fix broken links in flexvolume guide

- contributors/design-proposals/api-machinery/aggregated-api-servers.md
> update aggregated-api-servers.md: fix a typo

- contributors/design-proposals/storage/pv-to-rbd-mapping.md
> Typo fix: metada->metadata

- contributors/new-contributor-playground/README.md
Testing for contributor workshop
/area/new-contributor-track
> fixing area label

- contributors/new-contributor-playground/new-contributors.md
This is a paragraph describing your intent and the background for this pull request
> This is a practice commit

- contributors/new-contributor-playground/hello-from-copenhagen.md
Welcoming all new contributors from the New Contributor Summit in Copenhagen
> Adding a note from KubeCon + CloudNativeCon in Copenhagen

- contributors/design-proposals/scheduling/rescheduling.md
> Typo fix: we wil->we will

- contributors/new-contributor-playground/new-contributor-nodes.md
- contributors/new-contributor-playground/new-contributor-notes.md
I took some notes during the New contributor summit notes.
Here they are
> Add New contributor summit notes

- sig-governance.md
> Solve typo error

- keps/0002-controller-manager.md
Fix two typos:
Line 53: make is easy->make it easy
Line 223: initilization-> initialization
> Typo fix: make is easy->make it easy/initilization->initialization

- contributors/design-proposals/node/cri-windows.md
Line 88: configration->configuration
> [cri-windows.md] Typo fix: configration->configuration

- contributors/new-contributor-playground/new-contributors.md
> Add first practice commit

- contributors/devel/scheduler.md
The source may be moved to a separated repo from kubernetes.
> Link to new target

- sig-scalability/slis/apimachinery_slis.md
> Typo error: repeat 'from'

- sig-multicluster/README.md
- sigs.yaml
> Typo fix: run make regenerate the files, focussed=>focused

- contributors/design-proposals/node/node-usernamespace-remapping.md
/cc @mrunalp @adelton @derekwaynecarr @sjenning
> Add proposal for node-level User Namespaces remapping support

- events/community-meeting.md
> Correct UTC time for meeting

- events/community-meeting.md
> More time zone fixes.

- keps/sig-cli/0008-kustomize.md
> Fix links to kustomize examples

- contributors/design-proposals/scheduling/taint-node-by-condition.md
Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>
doc of https://github.com/kubernetes/kubernetes/issues/54313
> Doc about PID pressure taint.

- contributors/design-proposals/apps/daemonset-update.md
> Typo fix: DeamonSet->DaemonSet

- contributors/design-proposals/node/kubelet-cri-logging.md
> Update the documentation of CRI log format

- sig-scheduling/README.md
- sigs.yaml
> Add poseidon to sig-scheduling subproject

- sig-api-machinery/README.md
- sigs.yaml
> Update api-machinery OWNER links

- contributors/design-proposals/storage/grow-volume-size.md
- events/2016/developer-summit-2016/application_service_definition_notes.md
> Typo fix: Kuberntes->Kubernetes 

- contributors/design-proposals/apps/statefulset-update.md
> Typo fix: A users-> A user

- sig-scalability/slos/pod_startup_latency.md
- sig-scalability/slos/slos.md
/assign @shyamjvs @countspongebob
> Document pod startup SLO

- sig-scalability/README.md
> Cleanup sig-scalability readme

- mentoring/meet-our-contributors.md
> fixed times for meet-our-contributors.md

- sig-azure/charter.md
Draft of the SIG Azure Charter. We're opening this up for comments!
Announcement on sig-azure mailing list to follow.
/cc @shubheksha @khenidak @colemickens @jdumars
> Add SIG Azure Charter

- kubernetes-repositories.md
@bgrant0607 @smarterclayton @sarahnovotny @jbeda @spiffxp
> Add repo removal criteria and process.

- sig-scalability/configs-and-limits/thresholds.md
Based on findings in https://github.com/kubernetes/kubernetes/issues/64774
/cc @wojtek-t
> Add #services/ns limit to scalability thresholds doc

- contributors/design-proposals/multicluster/multicluster-reserved-namespaces.md
/assign @csbell @quinton-hoole 
/sig multicluster
/cc @pmorie @madhusudancs
Addresses https://github.com/kubernetes/cluster-registry/issues/221
> Document sig-multicluster decision about reserved namespaces

- contributors/design-proposals/multicluster/multicluster-reserved-namespaces.md
\sig multicluster
\assign @csbell 
Addresses comments in #2220.
> Follow up to #2220, addressing @csbell's comments.

- sig-api-machinery/README.md
- sigs.yaml
As discussed in SIG apimachinery.
> sigs.yaml add kubebuilder and controller-runtime sig apimachinery

- keps/sig-cli/0008-kustomize.md
/assign @pwittrock 
/assign @monopole
> Kustomize KEP typos fixes

- keps/0006-apply.md
> Update ServerSide apply Kep to fix links

- contributors/devel/help-wanted.md
- contributors/guide/README.md
* Document the `good first issue` label
* Clarify the `help wanted` label, it is a superset of `good first issue`
* Explain new commands `/good-first-issue` and `/remove-good-first-issue`
This is related to #1959 and https://github.com/kubernetes/test-infra/pull/8273.
> Document "good first issue" label

- keps/sig-cluster-lifecycle/0004-bootstrap-checkpointing.md
> Convert it to a string

- sig-scalability/configs-and-limits/thresholds.md
> Fix some scalability thresholds

- sig-scalability/slos/api_call_latency.md
> Typo fix: Descibe->Describe

- generator/app.go
- generator/sig_readme.tmpl
- generator/wg_readme.tmpl
- sig-architecture/README.md
- sig-azure/README.md
- sig-cloud-provider/README.md
- sig-contributor-experience/README.md
- sigs.yaml
- wg-app-def/README.md
fixes #2243.
Adds first class field to sig readme for link to charter
> Add link to charter from sig readme

- README.md
> Remove the link around Analytics

- OWNERS
OWNERS file updated with @parispittman and @jdumars 
cc @kubernetes/sig-contributor-experience-pr-reviews
> OWNERS file update

- sig-autoscaling/README.md
- sigs.yaml
> Remove an unexpected colon

- sig-pm/README.md
- sig-release/README.md
- sigs.yaml
> Update Agenda links for SIG PM + SIG Release

- contributors/devel/api-conventions.md
> Update API conventions

- sig-scalability/blogs/k8s-services-scalability-issues.md
This is a markdown version of my google doc. Sharing more widely to make it common knowledge.
cc @kubernetes/sig-scalability-misc @kubernetes/sig-network-misc 
/cc @wojtek-t @countspongebob (sig-scale leads)
> Catalog of known scalability issues with kubernetes services

- keps/sig-aws/OWNERS
- keps/sig-aws/README.md
Responding to an inquiry in slack so we can add one of our KEPs to the repository.
> Adding OWNERS and README.md for keps/sig-aws

- contributors/guide/github-workflow.md
Fixes #1809 
/cc cblecker dims 
/assign castrojo
Not sure if this is the best place to add it but I guess it comes under the github workflow?
> contributor guide: document the revert process

- sigs.yaml
- wg-iot-edge/README.md
> wg-iot-edge - add meeting archive url

- contributors/guide/README.md
> Fix grammatical error in testing section of the contributing guide.

- contributors/devel/controllers.md
There is a missing `:` in sample code.
> fix a typo in contributors/devel/controllers.md

- contributors/devel/e2e-tests.md
/sig testing
/assign @BenTheElder @nikhita 
fixes https://github.com/kubernetes/community/issues/2151
> replace e2e-runner with kubetest

- events/office-hours.md
> two minor changes to formatting

- sig-pm/OWNERS
- wg-app-def/OWNERS
- wg-apply/OWNERS
- wg-cluster-api/OWNERS
- wg-container-identity/OWNERS
- wg-iot-edge/OWNERS
- wg-kubeadm-adoption/OWNERS
- wg-multitenancy/OWNERS
- wg-policy/OWNERS
- wg-resource-management/OWNERS
Fixes a bunch of OWNERS files stuff for the wgs and sig-pm
> Fix WG OWNERS files

- sig-cluster-lifecycle/README.md
- sigs.yaml
Change-Id: Idf9b661fcf7a8f5aa353ca72134ef786b5c58b45
> Add cluster-api* git repositories under sig-cluster-lifecycle

- contributors/guide/README.md
Closes https://github.com/kubernetes/community/issues/1833
> Contributors guide: Clarify repository specific guidelines

- keps/sig-api-machinery/OWNERS
copied from https://github.com/kubernetes/community/blob/master/sig-api-machinery/OWNERS
> Add sig-api-machinery KEP OWNERS file

- committee-code-of-conduct/bootstrapping-process.md
> add code of conduct committee bootstrapping doc

- keps/sig-azure/OWNERS
/sig pm
/sig azure
/cc @jdumars @calebamiles @idvoretskyi
> Add keps/sig-azure/OWNERS

- contributors/devel/writing-good-e2e-tests.md
> Fix broken links and typos in writing-good-e2e-tests.md

- keps/sig-api-machinery/0015-dry-run.md
This is to address https://github.com/kubernetes/community/pull/2301#discussion_r202886027, https://github.com/kubernetes/community/pull/2301#discussion_r202886261, and https://github.com/kubernetes/community/pull/2301#discussion_r202886329
> Add more detailed plan for admission controller and webhook support to dry-run kep

- keps/sig-api-machinery/0015-dry-run.md
> Improve dry-run KEP

- keps/sig-cloud-provider/providers/cloud-provider-baiducloud.md
Hi Kim, this pr is for applying for cloud provider baiducloud in Kubernetes community, please make a review and let me know if you have any questions, thanks! @andrewsykim
> Apply for cloud provider baiducloud.

- keps/sig-cloud-provider/providers/0017-cloud-provider-digitalocean.md
KEP proposing DigitalOcean as a Kubernetes cloud provider.
> KEP for Cloud Provider DigitalOcean

- OWNERS_ALIASES
- sig-azure/README.md
- sigs.yaml
(I regenerated the alias file per the PR instructions)
cc: @justaugustus @khenidak @shubheksha
> sig-azure: remove Cole Mickens as Technical Lead

- sig-architecture/README.md
Added links to the various process tracking boards owned and maintained by the SIG.
> Added architecture tracking info to the README

- community-notes/q1-2_2018_community_meeting_minutes.md
I pulled out the notes for q1 and q2 2018. There's a Google doc version of this here: https://docs.google.com/document/d/1SCBGGRqm_8goKnMZG6TTpEPxGraeIRFY44eEoAWe2Xk/edit
> Archived community notes for q1 q2 2018

- sig-testing/README.md
- sigs.yaml
ref: https://github.com/kubernetes/community/issues/2464
> Follow testing-common's frameworks repo move to kubernetes-sigs

- contributors/devel/cri-testing-policy.md
Change the layout in the test grid.
> Update CRI testing policy

- keps/sig-node/0014-runtime-class.md
Address a few of @dchen1107 's comments that were left open when https://github.com/kubernetes/community/pull/2290 merged: added examples & alpha criteria.
Also marked as implementable in its current state, as this is the feature set we want to pursue for the initial alpha in 1.12.
/sig node
/milestone v1.12
> [RuntimeClass] Add examples & alpha criteria, mark as implementable

- sig-docs/README.md
- sigs.yaml
This repo has been moved to kubernetes-retired
> Remove kubernetes-bootcamp subproject from sig-docs

- keps/sig-contributor-experience/0007-20180403-community-forum.md
> Change forum KEP to implemented

- contributors/design-proposals/storage/volume-topology-scheduling.md
Fixes https://github.com/kubernetes/kubernetes/issues/60002.
This PR addresses volume topology scheduling related predicates only.
Related issues and prs:
- https://github.com/kubernetes/kubernetes/pull/55039
- https://github.com/kubernetes/kubernetes/issues/58797
- https://github.com/kubernetes/kubernetes/pull/59335
- https://github.com/kubernetes/kubernetes/pull/66106
- https://github.com/kubernetes/kubernetes/pull/65616
> Update volume scheduling design with event handling details.

- OWNERS_ALIASES
- committee-code-of-conduct/OWNERS
- committee-code-of-conduct/README.md
> add Code of Conduct Committee Members

- sig-architecture/README.md
- sigs.yaml
Reference: https://github.com/kubernetes/community/issues/2476
> added architecture tracking to sigs.yaml

- events/community-meeting.md
> Add some ideas for what a SIG Update should contain

- github-management/README.md
- github-management/opening-a-request.md
- github-management/org-owners-guide.md
Add information on suggested SLOs and how to open a request with the GitHub Administration Team.
/cc @spiffxp @idvoretskyi @calebamiles @grodrigues3 @fejta
> Add information on SLOs and how to open a request

- committee-code-of-conduct/bootstrapping-process.md
came across this during the community meeting.
/cc @michelleN 
/committee conduct
/assgin @cblecker
> Code of Conduct Commitee : fix typos

- sig-storage/README.md
- sigs.yaml
> Add kubernetes-csi/* repos to sigs.yaml

- sig-service-catalog/charter.md
@carolynvs @duglin @kibbles-n-bytes @pmorie
> explicit and clear about what majority means

- sig-node/README.md
> Update reference to SIG Network in SIG Node Readme

- events/elections/2018/README.md
- events/elections/README.md
Starting the process outlined in #2517
> Start 2018 election process 

- keps/sig-cli/OWNERS
The contents where copied from https://github.com/kubernetes/community/blob/master/sig-cli/OWNERS
> Add sig-cli KEP OWNERS file

- sig-aws/README.md
- sigs.yaml
added aws-iam-authenticator
added aws-encryption-provider
ran make generate to update sig-aws/README
> Updated sigs.yaml with new aws subproject details

- contributors/design-proposals/instrumentation/metrics-server.md
> Fix a typo in metrics-server.md

- generator/README.md
Updated minor issues in the .md file.
- Introduced working groups in the intro (the abbreviation was not introduced previously).
- Removed extra words (that).
- Added a missing comma.
> Copy-edit pass

- sig-auth/README.md
This content was moved into the charter document
/assign @tallclair @mikedanese
> Remove sig-auth custom content

- sig-scalability/README.md
- sigs.yaml
> *: fix "kubemark" OWNERS links

- sig-cluster-lifecycle/README.md
- sigs.yaml
Less is more, prune the lists! 
/assign @roberthbailey @kris-nova
> Prune sig-cluster-lifecycle github teams

- events/elections/2018/README.md
added links, fixed formatting, and corrected the email address for election officials
> fixing voters guide

- events/elections/2018/voters.md
> voters.md clean up

- events/elections/README.md
This should be the last set of changes.
> Reflect changes in duties and add more detail to the election process

- sig-scalability/slos/slos.md
> Add a link to watch latency sli

- contributors/guide/README.md
Removed superfluous "for" in the "Find something to work on" section
> Corrected contributor guide readme

- events/elections/README.md
> Change election email

- sig-storage/README.md
- sigs.yaml
/assign @saad-ali
I'm taking a best guess here
ref: https://github.com/kubernetes/org/issues/30
> Add kubernetes/csi-api to sigs.yaml

- mentoring/group-mentee-guide.md
Changed 'Contibuting' to 'Contributing'
> Fixes typo in group-mentee-guide.md

- contributors/guide/pull-requests.md
Added the text from @castrojo to the 'Best Practices for Faster Reviews' section and linked it at the top of the document.
Issue: #1628
> Adds the 'trivial edit contribution policy' to contributors/guide/pull-requests.md

- sig-scalability/slos/api_call_latency.md
- sig-scalability/slos/api_extensions_latency.md
- sig-scalability/slos/pod_startup_latency.md
- sig-scalability/slos/slos.md
- sig-scalability/slos/system_throughput.md
- sig-scalability/slos/watch_latency.md
Motivated by this comment: https://github.com/kubernetes/community/pull/2586/files#r212707580
> Make SLOs page more clear

- sig-scalability/slos/slos.md
> Clarify some things in main slo page

- contributors/design-proposals/api-machinery/customresource-conversion-webhook.md
Signed-off-by: bruceauyeung <ouyang.qinhua@zte.com.cn>
> delete a duplicate word --associated

- events/elections/2018/aaroncrickenberger.md
```
$ wc aaroncrickenberger.md
50     300    2275 aaroncrickenberger.md
```
> Add my bio for 2018 election

- communication/README.md
- contributors/guide/issue-triage.md
- sig-governance.md
Fixes https://github.com/kubernetes/community/issues/2605
cc @dholbach @castrojo @parispittman
> README.md updated - slackarchive removed

- sig-cluster-lifecycle/charter.md
The following is the charter submission for SIG Cluster Lifecycle
/assign @bgrant0607 @jbeda 
/cc @neolit123 @luxas @roberthbailey @kris-nova
> SIG Cluster Lifecycle Charter

- sig-api-machinery/README.md
- sigs.yaml
Signed-off-by: bruceauyeung <ouyang.qinhua@zte.com.cn>
> remove URLS which can not accessed and were removed

- sig-multicluster/README.md
cc: @pmorie @irfanurrehman @quinton-hoole
> sig-multicluster: Update readme to reflect current state of fedv2

- contributors/guide/non-code-contributions.md
Per today's meeting.
/assign @jonasrosland @qedrakmar
> Add suggestions for Event-related contributions to the noncode guide

- events/elections/2018/README.md
- events/elections/2018/timpepper.md
I'm adding my bio here.  Also noted Aaron's was added, but not linked in
the README.md, so added him there in addition to me.
> tpepper standing for steering election

- mentoring/mentor-guide.md
- mentoring/the1-on-1hour.md
> Fix some markdown links in the mentoring directory

- sig-scalability/block_merges.md
> Follow up comments on sig scalability charter

- contributors/design-proposals/autoscaling/vertical-pod-autoscaler.md
Link pointing to label selector was broken
fixes #2634.
> Fxing broken link

- sig-node/README.md
- sigs.yaml
- cri-container move ref: https://github.com/containerd/containerd/issues/1942
- cri-tools move ref: https://github.com/kubernetes/org/issues/60
- cri-o move ref: https://github.com/kubernetes/org/issues/64
> Update cri subprojects

- sig-cli/README.md
- sigs.yaml
This was asked in https://github.com/kubernetes/org/issues/58
> Update sig-cli subprojects

- contributors/design-proposals/architecture/architecture.md
> Fix broken url for rkt.

- community-membership.md
* Who approves membership requests
* How long membership requests take to process
Fixes: https://github.com/kubernetes/org/issues/76
/cc @cblecker @parispittman
> Add clarification to requesting Kubernetes org membership

- contributors/devel/flexvolume.md
* Updating documentation to reflect the newly updated Flexvolume example directory. Depends on https://github.com/kubernetes/kubernetes/pull/59149.
* Removing mentions of --enable-controller-attach-detach because setting it to false is not recommended.
* Adding documentation about pod information passed as mounter options.
/sig storage
/assign @chakri-nelluri @saad-ali
> Flex deploy examples, and miscellaneous documentation updates.

- sig-vmware/charter.md
> add SIG VMware charter.md

- events/elections/2018/README.md
- events/elections/2018/nikhitaraghunath.md
Ref: https://groups.google.com/d/topic/kubernetes-dev/sRpIsf6VH8w/discussion
```
wc -w nikhitaraghunath.md
290 nikhitaraghunath.md
```
/assign castrojo idvoretskyi parispittman
> Add Nikhita's bio for 2018 Steering Committee Election

- contributors/design-proposals/api-machinery/customresource-conversion-webhook.md
Add missing bullet point in Advice to Users.
> Fix typo in CRD Conversion Webhook proposal

- events/elections/2018/README.md
- events/elections/2018/davanumsrinivas.md
```
$ wc -w davanumsrinivas.md
298 davanumsrinivas.md
```
> Add dims bio for 2018 election

- keps/sig-network/0015-20180614-SCTP-support.md
The KEP document for SCTP support is updated.
"Status" changed to "implemented"
"Editor" set to "@janosi"
> SCTP KEP document update

- events/2018/12-contributor-summit/README.md
First pass at some content. Copied a bunch from May's folder and updated it with December's info. :)
> Create and start populating SEA Contrib Summit directory

- governance.md
A minor cleanup.
/kind cleanup
> governance: remove note that SC is still being formed

- events/elections/2018/README.md
- events/elections/2018/krisnova.md
Adding my bio for the 2018 steering committee election
Also adding my name to the list in the README.md
---
Hey @castrojo can you take a look at tell me if this all looks kosher? Unsure about if the picture is allowed or not, etc.
Happy to change anything as needed!
> Adding krisnova.md for election

- events/elections/2018/README.md
- events/elections/2018/timothysc.md
/assign @parispittman @castrojo @idvoretskyi
> timothysc bio for 2018 steering election

- communication/README.md
- contributors/guide/contributor-cheatsheet.md
- contributors/guide/issue-triage.md
- sig-governance.md
> Replace kubernetes-users mentions with new location

- events/elections/2018/voters.md
adding eligible voters from for the steering committee election round 1 of the exception form voting by election officials. second round to follow in the next 24 hours.
> adding more eligible voters

- keps/sig-cloud-provider/providers/0020-cloud-provider-alibaba-cloud.md
This is a supplementary info for adding Alibaba Cloud Provider into kubernetes repository. 
See Also.
https://github.com/kubernetes/community/pull/2394
https://github.com/kubernetes/community/commit/aba21ccbc9d095607eb561b8ef42cb497ad6c668
https://github.com/kubernetes/community/commit/6ad7317d59906b0ade1df51a5bec11e26bf6cf94
Signed-off-by: yaoyao.xyy <yaoyao.xyy@alibaba-inc.com>
> Proposal for Alibaba Cloud Provider repository

- keps/sig-node/0009-node-heartbeat.md
Signed-off-by: Rui Cao <ruicao@alauda.io>
> Fix typo: improvment -> improvement

- sig-storage/README.md
- sigs.yaml
ref: https://github.com/kubernetes/org/issues/92
> Add new repos to kubernetes-csi subproject

- sig-auth/README.md
- sigs.yaml
sig-auth's existing mission statement indicates how we achieve our objectives and this quote really sums up what our objective is to end users.
@kubernetes/sig-auth-api-reviews
> update sig-auth mission statement for vernacular readers

- contributors/design-proposals/node/resource-qos.md
> Fix typo in resource-qos.md

- communication/zoom-guidelines.md
This PR adds zoom screen sharing guidelines and recommendations. Fix #2599. Replacing #2710
> Added Zoom screen sharing guidelines and recommendations

- contributors/design-proposals/README.md
> Update a proposal process link

- events/2018/12-contributor-summit/README.md
new registration link and other misc info
> update summit info

- events/2018/12-contributor-summit/README.md
This will change, but it's solid enough to commit for now.
> Add a draft contrib summit schedule

- keps/OWNERS
/sig pm architecture
/hold
(holding until https://github.com/kubernetes/test-infra/pull/9437 merges)
rel:
- https://github.com/kubernetes/community/pull/2655
- https://kubernetes.slack.com/archives/C09QZ4DQB/p1537137652000100
> Update labels for keps/ dir

- github-management/new-membership-procedure.md
> Add new membership procedure doc

- sig-scheduling/README.md
- sigs.yaml
ref: https://github.com/kubernetes/org/issues/112
> Move kubernetes-incubator/kube-arbitrator to k-sigs/kube-batch

- OWNERS_ALIASES
ref: https://github.com/kubernetes/steering/pull/79
> Update steering-committee alias per 2018 election results

- contributors/design-proposals/resource-management/admission_control_resource_quota.md
- contributors/design-proposals/scheduling/taint-toleration-dedicated.md
- contributors/design-proposals/storage/container-storage-interface.md
- contributors/design-proposals/storage/volume-snapshotting.md
- contributors/design-proposals/storage/volume-topology-scheduling.md
Remove duplication in below files:
1. contributors/design-proposals/scheduling/taint-toleration-dedicated.md
2. contributors/design-proposals/storage/container-storage-interface.md
3. contributors/design-proposals/storage/volume-snapshotting.md
4. contributors/design-proposals/storage/volume-topology-scheduling.md
> Remove duplication

- sig-cloud-provider/README.md
- sigs.yaml
ref: https://github.com/kubernetes/org/issues/147
> Add cloud-provider repo to sig-cloud-provider subprojects

- sig-scalability/processes/formal-scalability-processes.md
Fix for https://github.com/kubernetes/community/issues/2696
FILE: ./sig-scalability/processes/formal-scalability-processes.md
[✖] https://github.com/kubernetes/community/blob/master/sig-scalability/blogs/scalability-regressions-case-studies.md → Status: 404
> Fix regression case studies link

- github-management/kubernetes-repositories.md
- github-management/org-owners-guide.md
- github-management/setting-up-cla-check.md
doing these changes in a separate PR before doing content changes
in followup PR's
> word wrap github management subproject at 80-char width

- sig-storage/README.md
- sigs.yaml
ref: https://github.com/kubernetes/org/issues/153
> Update kubernetes-csi subproject

- sig-scalability/configs-and-limits/provider-configs.md
> Remove excess 'on'

- mentoring/OWNERS
> mentoring: Add label in OWNERS

- contributors/design-proposals/api-machinery/customresource-conversion-webhook.md
> coresponding-->corresponding

- contributors/devel/release.md
Also links to test-infra's label reference, which is more complete, but not up to date either.
> Completes possible list of kind/ labels on PRs/Issues

- communication/moderation.md
> Add more mailing list moderation tips

- sig-big-data/resources.md
For SIG Big Data, updating the document outlining current SIG activities. Information is separated into status and activities for each project.
> SIG Big Data: improved and updated overview of resources regarding SIG activities.

- contributors/design-proposals/api-machinery/auditing.md
- contributors/design-proposals/node/secret-configmap-downwardapi-file-mode.md
- sig-scalability/slos/slos.md
> Fixing grammatical errors

- contributors/guide/pull-requests.md
Clarify the use of lgtm and approve labels and call out special cases which may result in surprising behavior by the code review system.
Fixes #2771
> Clarify the use of lgtm and approve labels

- contributors/devel/release.md
@justaugustus @kacole2 
Needs more changes but probably not all `features` should be replaced, PTAL
> Features -> Enhancements

- committee-steering/governance/README.md
- committee-steering/governance/sig-governance.md
- communication/meeting-notes-archive/q1-2_2018_community_meeting_minutes.md
- contributors/guide/non-code-contributions.md
- events/2017/12-contributor-summit/feature-roadmap-2018.md
- events/2018/05-contributor-summit/README.md
- events/2018/05-contributor-summit/new-contributor-notes.md
- keps/sig-contributor-experience/0007-20180403-community-forum.md
- sig-azure/charter.md
- sig-storage/contributing.md
> Conformance of the names of the conferences

- events/2018/12-contributor-summit/README.md
added wait list and badge pick up instructions
> sea contrib summit updates

- contributors/devel/on-call-federation-build-cop.md
Fix for #2696
FILE: ./contributors/devel/on-call-federation-build-cop.md
[✖] https://git.k8s.io/test-infra/testgrid/config/config.yaml → Status: 404
> Fix test grid config link

- sig-windows/charter.md
@PatrickLang @michmike @spiffxp
> Add a charter for sig windows.

- wg-security-audit/README.md
We don't, in fact, want to keep the RFP open for a year and a month.
cc: @cji 
/assign joelsmith
> Fix typo in RFP date

- sig-governance.md
Add discuss for WGs as an option.
> Synchronize this content with the moderation guidelines

- mentoring/OWNERS
Ref: https://groups.google.com/d/topic/kubernetes-sig-contribex/79lhaqgq-dw/discussion
@parispittman Following up on an AI from our call.
> mentoring: add nikhita as reviewer

- sig-architecture/README.md
- sigs.yaml
> Re org sig arch sub projects

- contributors/devel/e2e-tests.md
> Adding note about new directories with e2e tests

- community-membership.md
Fixes https://github.com/kubernetes/community/issues/2883
/cc @cblecker @spiffxp @justaugustus @mrbobbytables
> Clarify membership requirements for members of related Kubernetes orgs

- communication/resources/README.md
> Add community resources

- contributors/devel/bazel.md
@liztio asked about this last month, which made me realize this was a bit out of date.
cc @fejta @BenTheElder @jayconrod
> Update bazel documentation with current known issues and limitations

- contributors/design-proposals/node/accelerator-monitoring.md
Fix typos: acclerator -> accelerator
> Fix typos: acclerator -> accelerator

- contributors/design-proposals/node/cri-windows.md
- contributors/design-proposals/storage/volume-provisioning.md
- keps/sig-network/0030-nodelocal-dns-cache.md
- sig-autoscaling/README.md
- sigs.yaml
Fixup some typos in below files:
1. contributors/design-proposals/node/cri-windows.md
2. contributors/design-proposals/storage/volume-provisioning.md
3. keps/sig-network/0030-nodelocal-dns-cache.md
4. sig-autoscaling/README.md
5. sigs.yaml
> Fixup some typos

- contributors/guide/README.md
Changes in contributors guide:  purpose of triaging
> Update Contributors guide README.md

- github-management/README.md
Recognize and call out @mrbobbytables and @justaugustus for their efforts with the github management subproject.
> Add info on NMC

- events/community-meeting.md
- events/office-hours.md
Timezones are hard and daylight savings is silly.
Updating repos to reflect current UTC-time.
> Change UTC time for standard.

- sig-contributor-experience/community-maintenance.md
Fixed a very small typo (community was not spelled correctly).
> fixed typo in community-maintenance.md
