committee-steering/governance/sig-governance.md, contributors/chairs-and-techleads/leadership-changes.md
Ref: https://lists.cncf.io/g/cncf-toc/topic/78231677#5503, https://github.com/cncf/toc/pull/570
LF has launched a new course for inclusive training in an open source
context - https://training.linuxfoundation.org/announcements/linux-foundation-and-ncwit-release-free-training-course-on-diversity-in-open-source/
All CNCF maintainers are also required to take this course.
/hold
steering review
=> Update LF course for inclusive training

communication/slack-config/channels.yaml
Adding a Slack channel in accordance with the guidelines. 
[UnDistro](https://undistro.io) is a Kubernetes distribution.  The channel will be used to discuss UnDistro with end users and contributors, answer questions, gather bugs and feature requests, etc.
=> Add #undistro to channels.yaml

communication/slack-config/sig-security/config.yaml
From SIG-Security's last weekly [meeting](https://docs.google.com/document/d/1GgmmNYN88IZ2v2NBiO3gdU8Riomm0upge_XNVxEYXp0/edit#heading=h.7u1tzh1qn1z4) an action item was to create a new channel in order to facilitate a focussed discussion on security assessment of cluster-api (a sub project of kubernetes). This is a first attempt of a security assessment of a sub-project performed in collaboration with sig-security of the parent graduated project. 
Since we are breaking new ground here, I am happy to revisit if this channel should be prefixed as `wg` or `sig`.  We intend to periodically revisit the results from our assessments, so I do not see this as a time-bound effort but more of a continuous improvement cycle.
=> New channel for security assessment of cluster api

sig-auth/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/2713
/hold
needs lgtm from a sig-auth lead
/assign @enj 
cc @tallclair
=> sig-auth: add pod-security-admission repo

committee-code-of-conduct/incident-process.md
As CoCC collects information on an incident report it is important
that folks understand not just that this is done confidentially,
but also a little more about how it is done, eg: in which forums
and by which people.
Fixes #
=> CoCC: describe more the info clarifying process

sig-apps/annual-report-2021.md
Fixes:  #5495
Replaces: #5616
I flubbed when fixing commit messages before merging this PR and can no longer push to @kow3ns branch >_>
This PR is the same as the previous one with the exception of correcting the  commit msgs and updates the average time to merge on line 59.
/assign @soltysh  @kow3ns @mattfarina @janetkuo
=> SIG Apps: Add 2021 Annual Report

contributors/devel/sig-architecture/api-conventions.md
**Disclaimer**
I sent this PR to help clarify best practices for object references in the future, as I saw a few conflicting patterns myself. I welcome feedback on this PR does if the change doesn't accurately reflect the intended best practices, and am happy to make changes.
**Description**
There are a few types of patterns for multi-kind object references
that are currently included in the Kubernetes core resources
(EnvVarSource, ObjectReference).
Adding a section to clarify the preferred pattern for future
resources.
N/A
=> clarifying schema for multi-kind object references

sig-network/README.md, sigs.yaml
Fixes https://github.com/kubernetes/org/issues/2678
/assign @caseydavenport 
/hold
for lgtm from sig-network leads
=> sig-network: add network-policy-api

contributors/guide/contributor-cheatsheet/README-ja.md
This PR adds translation for tide/squash-on-merge to contributor-cheatsheet/README-ja.md
NONE
=> Add translation for tide/squash-on-merge to contributor-cheatsheet

OWNERS_ALIASES, sig-release/README.md, sigs.yaml
From https://groups.google.com/a/kubernetes.io/g/release-managers/c/zzk3naZhS4A:
> @kubernetes/release-engineering,
> 
> After some discussion with the leads, we'd like to propose both @cpanato and @puerco as Technical Leads for SIG Release, and more specifically, the Release Engineering subproject.
> 
> They are both dedicated Release Managers and never fail to lend a helping hand to contributors or jump into unfamiliar territory to support the subproject.
> 
> We're opening this for discussion with Release Managers, before formally proposing this on the mailing list.
/assign @saschagrunert @hasheddan @LappleApple @jeremyrickard 
cc: @kubernetes/sig-release
=> sig-release: Add Carlos Tadeu Panato Jr. & Adolfo García Veytia as TLs

sig-storage/README.md, sigs.yaml
The repo is being archived.
Fixes https://github.com/kubernetes/org/issues/2687
/hold
for lgtm from a sig-storage lead
=> sig-storage: remove cosi-driver-minio repo

communication/slack-config/channels.yaml
The #sig-node-rkt Slack channel appears to be unused. The last major activity was in 2018 and there have been no posts since early 2020.
/hold
for one week for lazy consensus (will also post in the channel)
Please cancel hold on June 17, 2021.
/sig node
=> Archive unused #sig-node-rkt channel

contributors/devel/sig-architecture/api-conventions.md
Clarifying practices around object references that help
prevent against privilege escalation.
Fixes #5797
=> Adding object references security considerations

communication/slack-config/sig-release/usergroups.yaml
This PR is part of the tech lead onboarding for @cpanato  and @puerco. It adds their handles  to the following slack groups:
* release-team-leads
* sig-release-leads slack groups
Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>
Part of: https://github.com/kubernetes/sig-release/issues/1590
=> Add carlos+adolfo to release-team-leads and sig-release-leads slack groups

sig-architecture/api-review-process.md
This PR makes the following changes:
- Fixes broken **KEP** link in [api-review-process.md](https://github.com/kubernetes/community/blob/master/sig-architecture/api-review-process.md#what-apis-need-to-be-reviewed) under Mechanics.0 second point (A KEP and tracking issue in kubernetes/enhancements has been created for changes within the kubernetes-* org introducing)
Fixes #5833
=> Fix broken link to KEP in pre-review checklist

sig-architecture/charter.md
Fixes #4839
As discussed in SIG Arch call on 2/25, clarify skew policy support changes are domain of this SIG along with upgrade/downgrade policy.
=> Update sig-arch charter for upgrade/downgrade and skew

contributors/devel/sig-architecture/vendor.md
Proposing this as follow up to slack conversation:
https://kubernetes.slack.com/archives/CHGFYJVAN/p1623348521105500
Fixes #
=> Add guidance on SHA vs tags in dependencies

contributors/devel/sig-testing/verify-tests.md
Fixes #5532
As part of this PR, documentation for test `verify-api-groups` have been added.
/sig testing
=> add documentation for verify-api-groups

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
Add jiangd and yinw to the Velero group.
Remove nrb, calisia, ashish-amarnath.
Signed-off-by: Daniel Jiang <jiangd@vmware.com>
=> Update members of the Velero Group

sig-release/README.md, sigs.yaml
Closes https://github.com/kubernetes/release/issues/2017.
/assign @mrbobbytables @cblecker @dims 
cc: @kubernetes/sig-release-leads @kubernetes/release-engineering
=> sig-release: Remove the deprecated hyperkube subproject from listing

governance.md
Remove broken analytics links, same as https://github.com/kubernetes/kubernetes/issues/93949
Fixes #
/kind cleanup
=> Remove broken analytics links

contributors/devel/sig-architecture/api-conventions.md
API conventions had two semi-duplicated sections for
object references, with slightly different guidance.
Consolidating guidance to point to the most recent
guidance.
=> consolidate object ref guidance in api conventions

communication/moderators.md, communication/slack-config/OWNERS
Hereby I am removing myself as Slack moderator. I don't have the time anymore to volunteer for this task at this point. By removing myself someone else can potentially take over.
None
/cc @jberkus
=> Removing myself as Slack moderator

communication/moderators.md
Ref: https://github.com/kubernetes/community/issues/5685
Nabarun has been around in the Kubernetes community for a long time and
has been in high-trust roles like the Kubernetes release lead and
the New Membership Coordinator (with approval access to k8s GitHub org
config) so he is a good fit for the moderator role for the k-dev
mailing list (which is a high trust role as well).
Additionally, Nabarun is in APAC so this helps us distribute the
moderation load better.
---
/hold
for lgtms from the following folks
/assign @palnabarun 
have already discussed with him, would like an ack on this PR
have already discussed with Bob, would like to see a lgtm here as contribex chair
/cc @spiffxp @parispittman @dims 
k-dev "owners"
/assign @dims 
would like to see a lgtm from …
=> communication: add Nabarun Pal as primary moderator for k-dev

communication/slack-config/channels.yaml
This pull request adds a dedicated Slack channel for [Krator](https://github.com/krator-rs/krator), a newly accepted CNCF Sandbox project. See [Krator onboarding](https://github.com/cncf/toc/issues/691). 
Historically, Krator has used the Slack channel for Krustlet on the Kubernetes slack, however both projects have now been accepted as separate sandbox projects, so it seems reasonable to use separate Slack channels. 
[Issue tracking Slack channel creation](https://github.com/krator-rs/krator/issues/34).
=> Add slack channel for Krator sandbox project.

communication/slack-config/usergroups.yaml
He is no longer a member of the core odo development team.
=> remove girishramnani from odo-devs slack group

contributors/devel/sig-release/kubernetes-versions.md
Update the kubernetes-versions guide to avoid referencing `gsutil` and
URI's that have GCS bucket names hardcoded in them where possible.
We don't have a CLI accessible way to list the contents of a given build
through dl.k8s.io, so it was necessary to keep it there.
Anything else that uses http or https to download kubernetes artifacts
should always use dl.k8s.io. It greatly reduces the amount of code that
will need to change whenever a different location is used (GCS bucket
rename, some other backing store, etc.)
There are a few other `kubernetes-release` references in this repo that
could be changed, but they're all historical or blockaded, so the
version markers doc was the only file that needed changes
This is part of https://github.com/kubernetes/k8s.io/issues/2318
=> contributors/devel/sig-release: use dl.k8s.io where possible

contributors/guide/issue-triage.md
The issue triage instructions referenced `lifecycle/needs-information`, but the correct label is `triage/needs-information`. I also added the Prow command corresponding to this label.
This tripped me up on https://github.com/kubernetes/ingress-nginx/issues/6191#issuecomment-883548832 when the incorrectly documented label was not accepted.
=> Fix typo in triage/needs-information label

sig-testing/README.md, sig-testing/charter.md, sigs.yaml
Rather than call out a deviation from governance in our chair, make it
clear that current SIG Testing Chairs are doing double-duty as Tech
Leads
=> sig-testing: make chair/tech_lead explicit

sig-security/security-audit-2021/RFP.md
This PR updates the vendor selection date in the 2021 external audit RFP to <strike>7/23/2021</strike> 8/10/2021 for sufficient time to review
/sig security
=> Update the vendor selection date in the 2021 External Audit RFP 

sig-security/security-audit-2021/RFP.md
Minor improvement: Fix the link for Project Goal and Scope under [Which attack vectors are of most concern to the Working Group.
](https://github.com/kubernetes/community/blob/master/sig-security/security-audit-2021/RFP.md#which-attack-vectors-are-of-most-concern-to-the-working-group) in RFP.md of security-audit-2021
=> Fix the link for Project Goals and Scope.

sig-cluster-lifecycle/README.md, sigs.yaml
This repository has been inactive for a long time, and it's due for
archival.
Signed-off-by: Vince Prignano <vincepri@vmware.com>
Fixes #
=> Remove all references to cluster-api-bootstrap-provider-kubeadm

contributors/devel/sig-node/OWNERS, sig-node/OWNERS
/kind cleanup
/sig node
I would like to propose getting approver access on the SIG Node repo as I have been active in maintaining and updating our community docs, meeting times, etc.
/assign @dchen1107 @derekwaynecarr
=> Add ehashman as a SIG Node community repo approver

sig-security/sig-security-external-audit/README.md
This PR creates an initial README.md for the SIG Security External Audit subproject.
The REAMD.md adds an overview and guide for the SIG Security External Audit subproject.
/sig security
=> Create guide/overview for the SIG Security External Audit subproject

sig-network/README.md, sigs.yaml
There was a refactor last year which left a broken link in the sig-network README. This PR corrects the broken link.
Refactor: https://github.com/kubernetes/kubernetes/pull/90976
Reported in: https://github.com/kubernetes/kubernetes/issues/104159
Fixes https://github.com/kubernetes/kubernetes/issues/104159
Signed-off-by: Bridget Kromhout <bridget@kromhout.org>
=> Fixing broken link in sig-network README

contributors/guide/owners.md
As the guide says: 
> Good examples of OWNERS usage:
>   the approvers are not in the reviewers section
Fixes #
=> Fix owners guide: approver in the reviewers section

sig-security/security-audit-2021/RFP.md
This PR updates the vendor selection date of the external security audit RFP for 2021.
Vendors were notified of the delay.
/sig security
/assign @tabbysable @IanColdwater 
/cc @aasmall
=> Update External Security Audit RFP vendor selection date

communication/slack-config/sig-release/usergroups.yaml, communication/slack-config/users.yaml
Adds the 1.23 RT Leads to release-team-leads Slack usergroup.
Fixes #
Ref: https://github.com/kubernetes/sig-release/issues/1652
/assign
/sig release
/assign @justaugustus @saschagrunert @jeremyrickard @cpanato @puerco @hasheddan
/cc @JamesLaverack @jrsapi @mkorbi @MonzElmasry
=> slack-config/sig-release: Add 1.23 RT leads to release-team-leads

sig-scheduling/README.md, sigs.yaml
Related:
- repo creation request: https://github.com/kubernetes/org/issues/2878
=> sig-scheduling: add kube-scheduler-simulator subproject

contributors/design-proposals/release/versioning.md
The document has been moved over to the sig-release repository, which is
now reflected with that change.
=> Update SIG Release versioning docs

communication/slack-config/sig-release/config.yaml
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
During release 1.22 retro, it was decided that the enhancements team should have a dedicated public channel to allow collaboration with the community.
In addition to already existing release-x slack channels, this request creates a missing channel for the enhancements team.
cc @kubernetes/sig-release-leads @reylejano @JamesLaverack @salaxander
=> Add release-enhancements channel

sig-scalability/configs-and-limits/thresholds.md
The text should say `cube` and not `kube` as mentioned in the kubecon talk
Fixes #
=> Should be `cube` and not `kube`

communication/slack-config/channels.yaml
The channel is no longer needed and we want users to use sig-network channel instead to discuss specific issues.
ref: https://kubernetes.slack.com/archives/CGF3A900N/p1614883236000400
=> archive slack channel k8s-dual-stack

contributors/design-proposals/README.md
Noticed this link was 404ing; now links to KEP-0000 which is currently located in sig-architecture's directory in the enhancement's repo
=> Update outdated link

contributors/devel/sig-node/e2e-node-tests.md
It wasn't obvious to me until reading the source code for the remote runner, and then looking up the GCP library docs that `gcloud login` wasn't sufficient to get things up and running.
This adds a quick note to the existing instructions for future folks who may want to run E2E's remotely.
=> sig-node-e2e: gcloud application-defaults are required

contributors/devel/sig-node/updating-pause-images.md
This doc serves as a rough tracker of where we bump kubernetes Pause images, and how we try to coordinate them when new pause releases happen.
This is a first attempt to formalize roughly what happens in staggered PRs historically, and tries to keep things well tested while moving fairly quickly to unblock developers who may rely on new features for their testing (e.g Windows Server 2022 support in the latest release).
We may want to add a tracking issue template to this document after @kerthcet drafts the first issue.
Slack Discussion: https://kubernetes.slack.com/archives/C0BP8PW9G/p1631032292078800
/cc @dims
/cc @SergeyKanzhelev
/cc @BenTheElder 
/cc @kerthcet
=> sig-node: add doc with basic info for pause image updates

contributors/devel/sig-architecture/api-conventions.md
This is a follow up to the earlier [sig-arch/apimachinery thread](https://groups.google.com/g/kubernetes-sig-architecture/c/WhHTjTDzcQg) and [sig-arch meeting](https://docs.google.com/document/d/1BlmHq5uPyBUDlppYqAAzslVbAO8hilgjqZUTaNXUhKM/edit#bookmark=id.i4u0xzqr7517) today. I hope I've represented the conclusion of that meeting reasonably accurately here. 
/cc @deads2k @lavalamp @liggitt @smarterclayton @thockin @toumorokoshi @youngnick
=> Clarifying API Conventions regarding Kind and Resource in object refs

sig-instrumentation/charter.md
The repository has been moved to kubernetes-sigs namespace. It seems ownership is now official as well: https://github.com/kubernetes/community/blob/master/sig-instrumentation/README.md#prometheus-adapter
=> sig-instrumentation: Update URL to prometheus-adapter repository

communication/slack-config/channels.yaml
Request the slack channel for `cluster-api-kubevirt`, similar to aws, azure, gcp, etc., to facilitate discussions around CAPK.
=> slack: add channel cluster-api-kubevirt

sig-cluster-lifecycle/README.md, sigs.yaml
This repository has been inactive for a long time, and it's due for archival.
Rif https://github.com/kubernetes-sigs/cluster-api/issues/5087
/cc @vincepri @neolit123
=> Remove all references to cluster-api-provider-docker

contributors/devel/sig-release/cherry-picks.md
Follow up on https://github.com/kubernetes/community/pull/6027 on Jordan's comment https://github.com/kubernetes/community/pull/6027#discussion_r711614882 about backports for alpha features, making it extensive to beta features too.
=> cherry-pick policy for alpha features

contributors/guide/contributor-cheatsheet/README.md
Fixes #6024.
This PR will add a link for Hindi language Cheetsheet on Readme.md
=> Fix: Missing link for Hindi language Cheatsheet on Readme.md

communication/slack-config/channels.yaml
Adding a slack Channel
Fixes #
* Slack Channel Name: cert-manager-aws-privateca-issuer
* Purpose of the Channel: To communicate with the users of the cert-manager/aws-privateca-issuer plugin for Kubernetes and keep the users informed about on potential issues and Plugin updates.
* GitHub Link: https://github.com/cert-manager/aws-privateca-issuer
=> Added slack channel for cert-manager/aws-privateca-issuer

communication/slack-config/channels.yaml
It is a magnet for recruiter spam so no one uses it for discussion anymore.
Sigh, can't have nice things. If we did want to keep it, just need to remove `jobs` from the title I bet.
=> Archive the #kubernetes-batch-jobs channel

events/elections/2021/README.md, events/elections/2021/election.yaml, events/elections/2021/election_desc.md
Also add link to voters.yaml and a few other documents.
This update moves the entire election back one week given the late starting date.  This means that the new SC won't be seated until November 7th.  However, it doesn't seem reasonable to compress the timeline any more than that -- particularly since we'll be finishing the nomination period during Kubecon as it is.
As such, I need an LGTM from a member of the SC as well as the EC; placing hold until we have both of those.
/hold
attn: @coderanger @alisondy @mrbobbytables @spiffxp 
=> Update election schedule due to the 1 week technical delay.

communication/zoom-guidelines.md
There was a broken link in line 220 of the zoom-guidelines.md doc which is supposed to link to `Meet our Contributors` page. Refer to [this issue](https://github.com/kubernetes/community/issues/6079)
=> Changed the broken link to Meet our Contributors in Zoom guidelines

OWNERS_ALIASES
Replace inactive owners with active provider-aws contributors. 
Fixes #5671
=> Fix owner aliases for provider-aws

communication/slack-config/channels.yaml
A while ago, the #headlamp channel was split into -users and -dev
because some members were concerned that an eventual dev conversation
increase would bother non-dev users.
However, our community is still small, and the Slack channels are
very low traffic, so this split only makes the communication more
difficult.
Therefore, as Headlamp's project manager, I would like to request
that the -users channel be renamed back to the prefixless case, and
the -dev channel to be archived.
=> communication/slack-config: archive headlamp-dev and rename -users

communication/slack-config/channels.yaml
#community-sites was created in 2016.  It has not carried any legit discussion in at least a year.
/area slack-management
=> Archive abandoned channel #community-sites per discussion

communication/slack-config/channels.yaml
Request the slack channel for `cluster-api-kubemark`, similar to kubevirt, aws, azure, gcp, etc., to facilitate discussions around CAPK.
=> slack: add channel cluster-api-kubemark

contributors/devel/README.md
None
It seems kubetest is deprecated so it would be nice if we have a link to kubetest2 in the README.md too. Thank you for your review!
=> Add a kubetest2 link to contributors/README.md

OWNERS_ALIASES, sig-testing/README.md, sigs.yaml
For the last 5.5 years, SIG Testing Chairs have also acted as Tech Leads. A
few months ago, we changed our charter to make the Tech Lead role explicit,
but left things as they were by explicitly listing our Chairs as filling
both roles
Today we would like to change that, and recognize the work that two of our
awesome contributors have been doing to further the vision of this SIG
To that end, we are proposing:
- Cole Wagner (@cjwagner) to replace Aaron Crickenberger (@spiffxp) as Tech Lead
- Alvaro Aleman (@alvaroaleman) to replace Steve Kuznetsov (@stevekuznetsov) as Tech Lead
- Aaron and Steve to remain as Chairs
We recognize this means we will remain a SIG with some of the longest-serving
Chairs in the Kubernetes community. Anyone interested in helping us work
through how to improve …
=> sig-testing: propose new TLs

events/elections/README.md
Also, divide README into a "current" and an "outdated" section.  
/assign @alisondy @coderanger 
=> Add instructions for qualifying candidates to the README

values.md
The description for the Kubernetes Community Values in values.md was inaccurate (the existing description was relevant to mentoring initiatives).
Changed it to better reflect the content.
Fixes #6188
=> Fix: Inaccurate Description for Kubernetes Community Values

events/elections/2021/README.md
Dates for candidate notification and the public steering meeting were off by one.
/assign @coderanger
=> Fix dates for candidate/public notification.

communication/slack-config/channels.yaml
Requesting channel "krafternetes"
Purpose: This channel is for discussion and coordination among Kubernetes contributors and users who also do things in the visual, culinary, and performing arts and want to discuss them in our slack and use our artistic abilities to support the project.  Among other things, I plan to use the channel to coordinate work on (a) a visual arts event for the Contributor Celebration, (b) contributor event tshirts and swag design, and (c) other arts needs that the project has.
The name is somewhat whimsical, if you find it too much so we can go with something more direct, like "kube-artists".
I will be on the channel to moderate.  @kaslin is likely to be available to co-moderate.
=> Request channel krafternetes.

OWNERS_ALIASES, contributors/guide/OWNERS, github-management/OWNERS
Taking an opportunity to prune myself from some aliases/review paths
to reduce my workload.
=> OWNERS(justaugustus): Prune extraneous reviewer roles

communication/slack-config/sig-architecture/usergroups.yaml
I'm moving to emeritus and Kirsten was missing from the usergroup!
ref: https://github.com/kubernetes/enhancements/pull/3046, https://github.com/kubernetes/enhancements/blob/c342fea7acb59059b400e7206671bea751699799/OWNERS_ALIASES#L166-L170, https://kubernetes.slack.com/archives/C1L57L91V/p1636653299011400
/assign @mrbobbytables @kikisdeliveryservice 
cc: @kubernetes/enhancements
=> slack-config(enhancements): Update subproject owners

contributors/guide/github-workflow.md
ᕕ(ᐛ)ᕗ New contributor here!
I have been using this very helpful github-workflow guide while I make my first contributions- thank you!
With this PR I am changing all references to 'master' and replacing them with 'main'.  I am so pleased that the default branch is now called 'main'!
The diagram on the page is now out-of-date and if you accept these changes it will be inconsistent with the text.  But we have to start somewhere!
\(^-^)/  Have a great day!
=> Change 'master' to 'main' in github-workflow markdown

communication/slack-config/channels.yaml
The channel serves as a medium for discussions related to [`controller-runtime`](https://github.com/kubernetes-sigs/controller-runtime/). Till now, the discussions for controller-runtime took place in the `#kubebuilder` slack channel. As controller-runtime grows as a project and adoption increases, having a dedicated channel will help.
=> Add channel for controller-runtime

liaisons.md, sig-autoscaling/README.md, sig-cli/README.md, sig-cloud-provider/README.md, sig-docs/README.md, sig-k8s-infra/README.md, sig-multicluster/README.md, sig-network/README.md, sig-node/README.md, sig-service-catalog/README.md, sig-ui/README.md, sigs.yaml, ug-big-data/README.md, ug-vmware-users/README.md, wg-data-protection/README.md, wg-iot-edge/README.md
Part of @tpepper and my onboarding in https://github.com/kubernetes/steering/issues/219.
We're also taking the opportunity to rebalance some of the load for a few of the continuing @kubernetes/steering-committee members.
ref: https://docs.google.com/spreadsheets/d/14jfFbZYZi1QVy_l6RZXD2kIt8aTqa9wxh-br2Od1FpI/edit?usp=sharing
/assign @tpepper @parispittman @mrbobbytables @liggitt @cblecker @dims 
/hold
=> steering: Update governance group liaisons

contributors/devel/sig-scheduling/scheduler_algorithm.md
The `scheduler.md` file was deleted in this [PR](https://github.com/kubernetes/community/pull/6198), but the `scheduler_algorithm` file still references the deleted file.
According to the linked PR, all the information in the `scheduler.md` are already in [scheduling_code_hierarchy_overview.md](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scheduling/scheduling_code_hierarchy_overview.md), so the link is replaced with a link to this file instead.
=> Fixes broken URL in scheduler_algorithm for a deleted documentation

contributors/devel/sig-architecture/conformance-tests.md, contributors/devel/sig-testing/e2e-tests.md
/kind cleanup
/sig windows
/milestone v1.24
We've removed support for Windows Docker in Kubernetes v1.24, so we no longer need this tag.
Updates a few of the Windows tests considerations, since a few of them are supported by Windows Containerd.
Fixes #6123
=> Removes [Exclude:WindowsDocker] test tag

committee-code-of-conduct/governance/onboarding-offboarding.md
From https://github.com/kubernetes/org/pull/3090#issuecomment-965802315:
> (FYI, this should be added to https://github.com/kubernetes/community/blob/master/committee-code-of-conduct/governance/onboarding-offboarding.md)
- cocc/onboarding: Add steps for kubernetes/org GitHub teams and OWNERS
- cocc/onboarding: Fix markdown lint warnings
ref: https://kubernetes.slack.com/archives/CPNFRNLTS/p1636583166079300?thread_ts=1636482065.073000&cid=CPNFRNLTS
/assign @celestehorgan @tpepper 
cc: @kubernetes/code-of-conduct-committee
=> cocc/onboarding: Add steps for kubernetes/org GitHub teams and OWNERS

contributors/devel/sig-testing/verify-tests.md
Fixes https://github.com/kubernetes/community/issues/5532
As part of this PR, I've added documentation for below two scripts:
- hack/verify-structured-logging.sh
- hack/verify-gofmt.sh
=> Add documentation for remaining hack/verify* tests

contributors/devel/sig-instrumentation/logging.md
During recent WG Structured Logging meeting we went into discussion what features/changes should be make in specific problem. This lead us to agree that we need some high level guide about what changes make sense in which format. 
This is draft PR that I started writing to document goals of each logging format.
/cc @ehashman @pohly
=> Documment logging formats

committee-code-of-conduct/README.md, committee-security-response/README.md, liaisons.md, sigs.yaml
Proposing Steering Committee liaisons for the following groups:
- @kubernetes/code-of-conduct-committee (@tpepper)
- @kubernetes/security-response-committee (@justaugustus)
Choosing Tim and Stephen here, because:
- they're newly-appointed @kubernetes/steering-committee members with a lighter liaison load
- they have served on (or [have] operate[d] in) the respective
committee's private spaces and are familiar with their processes
Fixes https://github.com/kubernetes/steering/issues/170
/assign @parispittman @dims 
/hold for any discussion
=> steering: Add Committee liaisons

sig-contributor-experience/README.md, sigs.yaml
N/A
Added the owners file for newly made repository [Contributor Katacoda](https://github.com/kubernetes-sigs/contributor-katacoda) under the SIG-Contributor Experience Mentoring subproject as mentioned [here](https://github.com/kubernetes/org/issues/3095#issuecomment-985179525)
=> Added the Contributor Katacoda owners file under SIG-Contribex mentoring subproject

github-management/README.md
Part of https://github.com/kubernetes/sig-release/issues/1772.
/assign @cblecker @mrbobbytables 
cc: @kubernetes/owners @kubernetes/publishing-bot-maintainers @kubernetes/release-engineering 
/hold for https://github.com/kubernetes/org/pull/3131
Slack convo: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1638832884428700
=> github-mgmt: Add `kubernetes-nightly` as a community-owned org

sig-instrumentation/archive/meeting-notes-2021.md
Adds a meeting note archive for 2021 for SIG Instrumentation.
We've just finished our last meeting for the year today.
=> Add SIG Instrumentation 2021 meeting notes archive

committee-steering/governance/annual-reports.md
cc @kubernetes/steering-committee 
Cleans up the process bits and reorients them around completing a generated template report.
Drops the link to the obsolete questions template and the bootstrap 2020 documentation
=> Annual report process cleanup

communication/slack-config/sig-release/usergroups.yaml
Promote palnabarun and Verolop to Release Managers
Part of https://github.com/kubernetes/sig-release/issues/1713 and https://github.com/kubernetes/sig-release/issues/1789
Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>
=> slack: update release-managers group config

sig-scheduling/README.md, sigs.yaml
=> Fix link to OWNERS path for kube-scheduler-simulator

events/awards/playbook.md
Added rules clarification on who is eligible to be nominated for a community award.
Apparently, this clarification is needed.
/area awards
=> Added rules clarification on who is eligible to be nominated

sig-docs/blog-subproject/README.md
@sftim (that's me) is now a blog editor
Adopt change from https://github.com/kubernetes/website/pull/30798
=> Add sftim as blog editor (SIG Docs)

contributors/devel/sig-architecture/api_changes.md
Fixes a broken link and updates a link in `api_changes.md` to reflect the current state of the scripts being run
/kind cleanup documentation
=> devel: fix/update links in api_changes.md

communication/slack-config/sig-release/usergroups.yaml
Part of https://github.com/kubernetes/sig-release/issues/1713 and https://github.com/kubernetes/sig-release/issues/1789
=> slack: add palnabarun and Verolop to security-rel-team usergroup

sig-release/charter.md
A broken link to KEP template in the charter.md documentation is fixed here.
=> sig-release/charter: Update link to KEP directory

communication/slack-config/sig-release/config.yaml, communication/slack-config/sig-release/usergroups.yaml
Presently there are a number of Release Team "area" channels such as #release-docs, #release-enahncements, etc. These are used for parts of the release team to discuss release team internal matters that are not confidential.
However there is no similar state for the release team leads (the Release Lead, Release Lead Shadows, EA, and role leads). So this ends up *either* cluttering up #sig-release itself or just happening in DM. In a desire to make the internal discussions of the release team more open, I'd like a public channel that is a space for the release lead, area leads, and others to discuss "day-to-day" topics such as:
- Scheduling meetings
- Organising and drafting emails
- asking for general advice from each other
=> slack-config/sig-release: Add #release-team-leads channel

communication/slack-config/channels.yaml
Signed-off-by: eyuen <eyuen@redhat.com>
N/A
Hi! This request is to create a slack channel for discussing things related to the devfiles. 
**Information about us:**
Devfile is an open-source project that provides an open standard defining containerized development environments that enable developer tools to simplify and accelerate workflows. It helps to make the development environment easily reproducible as well.
Our project has a strong tie to Kubernetes. Some of the existing Kubernetes-specific tools are using the devfile support, e.g. odo (https://odo.dev/), Eclipse Che (https://eclipse.org/che/), Dev Workspace (https://github.com/devfile/devworkspace-operator), and OpenShift Developer Console. 
If you want to know more about the devfile project, here …
=> Add devfile channel

contributors/devel/sig-architecture/api-conventions.md
As per KEP https://github.com/kubernetes/enhancements/issues/2527 -
remove the "from observation" guidance and add some discussion of when
to use status fields vs. additional types for allocated resources.
=> Loosen the meaning of status in API conventions

contributors/devel/sig-node/triage.md
In lieu of https://github.com/kubernetes/community/issues/5641, removing `kind/design` from the triage process doc.
/sig node
NA
/hold
until `kind/design` is removed from `k/k` by a gh admin.
=> Remove kind/design from triage doc

communication/slack-config/channels.yaml, sig-cli/README.md, sigs.yaml
Adds a Slack channel for the KRM Functions subproject of SIG-CLI, which was created here: https://github.com/kubernetes/community/pull/6249
Also fixes that subproject's agenda link.
=> Krm functions channel

sig-cloud-provider/cloud-provider-extraction-migration/OWNERS
`emeritus` is not the right key. it should be `emeritus_approvers`
Please see the PR where this was introduced:
https://github.com/kubernetes/community/commit/1a9db591729f34fec2ec4491aa420c0f1812d73b
Fixes #
=> Fix cloud-provider-extraction-migration/OWNERS file with correct structure

sig-release/README.md, sigs.yaml
Update Adolfo García Veytia (@puerco) company affiliation from @uServers to @chainguard-dev 
Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>
=> Update Adolfo García Veytia company affiliation

community-membership.md
Membership across orgs is now equivalent. When joining a Kubernetes GitHub Org, you are now joining the Kubernetes project and have implicit membership in the other active orgs.
ref: https://github.com/kubernetes/org/issues/966
ref: [Steering Public Meeting August 2nd, 2021](https://docs.google.com/document/d/1qazwMIHGeF3iUh5xMJIJ6PDr-S3bNkT8tNLRkSiOkOU/edit?pli=1#heading=h.kpax73jkdye0)
/cc @kubernetes/owners @kubernetes/steering-committee 
/hold
=> Update github org membership requirements

communication/slack-config/channels.yaml
Add channel for kpack, an open source project created to build application source code into OCI compliant images leveraging Cloud Native Buildpacks (buildpacks.io). We plan to use this channel to discuss all things kpack with the OSS community.
https://github.com/pivotal/kpack
=> Add slack channel for kpack

OWNERS_ALIASES, sig-instrumentation/README.md, sigs.yaml
Lazy consensus period is one week (~Jan. 13~ Jan. 19, 2022). Email: https://groups.google.com/a/kubernetes.io/g/dev/c/EgLQ5ynIbaw
/hold
Frederic [stepped down](https://groups.google.com/g/kubernetes-sig-instrumentation/c/kWsG-3XHzoM/m/fEmkYlu9BwAJ) as SIG Instrumentation TL in December 2021.
[At today's meeting,](https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#heading=h.t61dmzcxx1g) the SIG Instrumentation leads have proposed Damien Grisonnet (@dgrisonnet) as our new Technical Lead. Congratulations, Damien! :tada: :cake: 
/assign @logicalhan @dashpole 
/cc @brancz 
=> Propose Damien Grisonnet as new SIG Instrumentation TL

communication/slack-config/channels.yaml
Add a surveys channel for folks who want to do market surveys against our user base.
Once this channel is deployed and ready, we will change Slack policy so that such surveys will no longer be allowed in kubernetes-users, and instead have to go in the surveys channel.  Users will be notified of the new channel so that they can join it if they're interested in taking surveys.
cc: @coderanger @markyjackson-taulia
=> Add surveys channel.

communication/slack-config/channels.yaml
Netmaker is a virtual networking project with a strong focus on Kubernetes. Adoption has been growing pretty quickly in the K8S space and we would like to have a place in the Kubernetes Slack to talk with users. Here are some related resources for reference:
https://github.com/gravitl/netmaker
https://github.com/gravitl/netmaker-helm
https://nm-k8s.readthedocs.io/
=> Add the netmaker channel

sig-storage/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/2966
sig storage lead
/hold
for lgtm from a sig storage lead
cc @MeinhardZhou
=> sig-storage: add csi-driver-nvmf repo

sig-api-machinery/README.md, sig-architecture/README.md, sig-release/README.md, sigs.yaml
Part of SIG Release Annual Report 2021: https://github.com/kubernetes/community/issues/6377
/assign @saschagrunert @dims 
/cc @kubernetes/sig-release-leads 
---
Fixes based on https://github.com/dims/maintainers/tree/be0c97550f21065e2383500c23479945b750b369
Before:
```console
❯ time maintainers audit sig-release --kubernetes-directory ~/prj/k8s/kubernetes
WARN: GOPATH not setRunning script : 01-25-2022 13:14:47
>>>> Processing sig [sig-release/Release]
OPTIONAL: missing 'private_mailing_list' in contact
>>>> Processing subproject Release Engineering under sig-release
WARNING: missing 'mailing_list' in contact
OPTIONAL: missing 'private_mailing_list' in contact
OPTIONAL: missing 'teams' in contact
>>>> Processing owners files for sig-release/Release …
```
=> sig-release: Audit sigs.yaml

contributors/guide/coding-conventions.md, contributors/guide/github-workflow.md, contributors/guide/help-wanted.md
Edit parts of the Contributor Guide to match the Kubernetes
Documentation style guide. This PR updates the following:
- the GitHub Workflow document
- the Help Wanted guide
- the Coding Conventions document
Co-authored-by: Joel Barker <joel@lionswaycontent.com>
=> Update parts of the contributor guide to match the style guide

communication/slack-config/channels.yaml
This PR adds a slack channel for Cluster API operator subproject https://github.com/kubernetes-sigs/cluster-api-operator
=> Add CAPI operator slack channel

sig-cluster-lifecycle/README.md, sigs.yaml
Add CAPI Operator to `sigs.yaml`. @fabriziopandini @vincepri @JoelSpeed I set CAPI slack channel and office hours as related to the operator repo, hope this is fine.
Fixes #
=> Add CAPI Operator to sigs.yaml

sig-cluster-lifecycle/README.md, sigs.yaml
Changes the CAPI meeting notes link from the 2021 meeting notes to 2022
/assign @vincepri 
looks like we missed (at least) one link
=> cluster-api: update meeting notes

sig-scheduling/README.md, sigs.yaml
Fixes https://github.com/kubernetes/org/issues/3263
/assign @ahg-g 
/hold
need lgtm from at least one sig-scheduling lead
=> sig-scheduling: add kueue repo

sig-docs/CONTRIBUTING.md
This PR adds a CONTRIBUTING.md to k/community/sig-docs per [sig-governance.md](https://git.k8s.io/community/committee-steering/governance/sig-governance.md)
> Ensure contributing instructions (CONTRIBUTING.md) are defined in the SIGs folder located in the Kubernetes/community repo if the groups contributor steps and experience are different or more in-depth than the documentation listed in the general [contributor guide](https://github.com/kubernetes/community/blob/master/contributors/guide/README.md) and [devel](https://github.com/kubernetes/community/blob/master/contributors/devel/README.md) folder.
/cc @divya-mohan0209 @jimangel @natalisucks
=> Add SIG Docs CONTRIBUTING.md

sig-instrumentation/README.md, sig-instrumentation/charter.md, sigs.yaml
This is a small change to our charter/summary to reflect our current projects and responsibilities.
This scope update adds tracing and removes references to the deprecated project Heapster, replacing it with klog.
I also made sure the projects in charter.md and README.md matched.
since this is a charter update that covers scope (although we have defacto been covering this scope since [tracing was added](https://github.com/kubernetes/enhancements/issues/647))
As discussed amongst SIG Instrumentation leads when preparing our annual report.
/cc @logicalhan @dashpole @dgrisonnet
=> SIG Charter Update: Instrumentation (tracing, non-retired projects)

github-management/org-owners-guide.md
This adds specific guidance to the org owners guide on how to licence mixed context repos under Kubernetes organizations.
=> Add licensing guidance to the org owners guidance

contributors/guide/first-contribution.md
The link to "Contributor Role Board" in the https://www.kubernetes.dev/docs/guide/first-contribution/ page is broken.  The PR updates it to the good first issue link.
Fixes #6493
=> Repair broken link for first contributions

sig-node/README.md, sigs.yaml
While drafting the sig annual report I noticed that we were missing documentation for the ci-testing subproject that originated in [May 2020](https://kubernetes.io/blog/2022/02/16/sig-node-ci-subproject-celebrates/).
This adds them to sigs.yaml and regenerates the node readme. I think this should be a representative example of the code that is nominally owned by the subproject.
/cc @ehashman @SergeyKanzhelev 
(as the subproject leads)
/cc @derekwaynecarr
(as a sig-node lead)
=> sig-node: add ci-testing subproject

communication/slack-config/channels.yaml
This proposes to add a new cluster-api-cloudstack Slack channel for use of community building, participation and discussion around CAPI provider for Apache CloudStack (http://cloudstack.apache.org/), an opensource IaaS cloud computing platform. This is under the cluster-api sub-project of k8s cluster-lifecycle SIG. We're in process of proposing and donating this provider to the SIG.
=> channels: add cluster-api-cloudstack slack channel

contributors/devel/sig-architecture/api_changes.md
This is needed since we have implemented beta APIs as off by default, but still require testing them.  We have  way to enable this for integration tests and for e2e tests and this PR describes how to do both.  
xref https://github.com/kubernetes/enhancements/issues/3136
=> add details for testing beta APIs now that they are off by default

contributors/devel/sig-architecture/api-conventions.md
Heartbeats previously caused significant standing load, they are not recommended for API types.
=> Remove recommendation for condition heartbeat

sig-apps/annual-report-2021.md
Fixes #6363
/assign @janetkuo @kow3ns @mrbobbytables
=> SIG Apps 2021 annual report

contributors/devel/sig-testing/flaky-tests.md
This changed from .md to .yaml in
https://github.com/kubernetes/kubernetes/pull/104468.
=> flaky-tests.md: update template in link

communication/slack-config/channels.yaml
This PR adds new Kubernetes Slack channel: rukpak-dev
[RukPak](https://github.com/operator-framework/rukpak) is a new project under the CNCF Operator Framework project and already has contributors from the community.
We want to encourage the community to participate more in the development of rukpak, so we would like to move our communication to open slack channels.
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
=> Add rukpak-dev channel

communication/slack-config/channels.yaml
This PR adds a slack channel for Cluster API Oracle Cloud Infrastructure (OCI) provider https://github.com/oracle/cluster-api-provider-oci
No open issues related to this PR
=> Add CAPI Oracle Cloud Infrastructure (OCI) slack channel

communication/slack-config/usergroups.yaml
Removing Matt Broberg from the contributor comms slack group, as he has stepped away from the group for now.
=> Removing Matt Broberg from ContribComms

github-management/OWNERS, github-management/README.md
Ref: [sig contribex thread](https://groups.google.com/g/kubernetes-sig-contribex/c/O26DCoCdMYQ/m/GwkkzX-2AQAJ) for the nomination.
Lazy consensus achieved.
/hold
need majority of steering committee to lgtm this change
/assign @cblecker @mrbobbytables 
currently active gh admins (Ihor is temporarily unavailable)
Can you also +1 here?
/assign @palnabarun @ameukam 
Can you confirm that you are interested in joining the GitHub Admin Team and accept the security embargo policy?
=> Add Nabarun and Arnaud to GitHub Admin Team

sig-storage/annual-report-2021.md
* Remove extraneous space resulting in bad formatting in KEP work in 2021 section
* Remove broken link in Continuing sub-section of Working groups section
=> Fix typo in sig-storage/annual-report-2021.md

contributors/guide/issue-triage.md
This edit on the Issue Triage document brings it up to date with the style guideline while clarifying some language and doing some minor edits.
-------
Fixes #
=> Overhaul the Issue Triage guide to match style guide

communication/slack-guidelines.md, communication/zoom-guidelines.md
Update the Zoom and Slack communication guides to match style guidelines. This also includes a few updates, grammar fixes, and modifications from the community.
Co-authored-by: Aaron Epperson <aaron@aaronepperson.com>
-------
Fixes #
=> Update communication guide to match style guidelines

contributors/guide/release-notes.md
This updates the release notes guide to meet style guidelines, as well as including additional advice on release notes from community feedback.
-------
Fixes #
=> Update release-notes.md with community feedback

contributors/guide/issue-triage.md
The table syntax was breaking the build for the contributor site.
Need to troubleshoot this later as it should work, but need to this to get builds working again.
/cc @pymander @jberkus
=> Remove hugo table syntax from issue triage guide

contributors/devel/sig-instrumentation/migration-to-structured-logging.md
In Kubernetes 1.24, the necessary infrastructure got added. Now developers can
take advantage of it.
=> logging: include information about contextual logging

sig-security/annual-report-2021.md
Fixes #6380
First draft of SIG Security 2021 annual report. WILLFIX
=> SIG Security 2021 annual report

sig-release/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/3259
/assign @saschagrunert 
cc @leonardpahlke 
/hold
need lgtm from at least one sig release lead
=> sig-release: add release-team-shadow-stats repo

contributors/devel/running-locally.md
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
As referenced in #4497, Vagrant is no longer supported, so this removes the reference to Vagrant in the `running-locally.md` doc and replaces it with Kind (as suggested in the referenced PR).
=> Removes vagrant reference in running-locally doc

communication/slack-config/channels.yaml
Zarf is open-source air gap software delivery tool that focuses on enabling declarative deployments for various K8s distros in air-gapped and limited-connectivity environments.  I am requesting a channel for user support (zarf) and a dev channel (zarf-dev) for open-source collaboration.
Git repo: https://github.com/defenseunicorns/zarf/
Related Zarf Issue: https://github.com/defenseunicorns/zarf/issues/424
=> Add Zarf slack channels: #zarf and #zarf-dev

contributors/devel/sig-instrumentation/instrumentation.md
Add guidelines so that deprecated metrics (when applicable) will have helpful pointers to their non-deprecated counterparts.
=> add deprecation policy guidelines to instrumenting kubernetes guide

sig-scalability/charter.md
Fixes #6646
The test has been removed in https://github.com/kubernetes/kubernetes/pull/83322. The link here is taken from that PR.
Also, the OWNERS file link (kubernetes/kubernetes/test/e2e/scalability) is broken: https://github.com/kubernetes/community/tree/master/sig-scalability#subprojects
I'd like to update this too, is https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/OWNERS a new one?
=> Fix the link to scalability tests

Makefile, go.mod
`GO111MODULE` isn't required to set anymore and this might fix this issue: https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/config/jobs/kubernetes/community/community-presubmit.yaml#L14-L15
=> Update Go version to 1.18

contributors/devel/development.md
This change updates to the new go version for Kubernetes 1.24 as it has been updated to 1.18.
=> Adding new release version 1.24 and associated go version 1.18

sig-testing/charter.md
fejta-bot has been replaced with k8s-triage-robot and it's owned by sig-k8s-infra, so removed the mention to it.
=> Remove mention to fejta-bot from sig-testing charter

communication/slack-config/channels.yaml
Hi admins, 
I am working on a Streaming Runtime on top of Kubernetes. I would like to create a space (slack channel) where people can ask questions and involve themselves in this project. 
Git Repo: https://github.com/vmware-tanzu/streaming-runtimes
Docs: https://vmware-tanzu.github.io/streaming-runtimes/
Fixes #
=> Add Streaming Runtime channel

communication/slack-config/channels.yaml
Terranetes enables application developers to self-serve cloud resources with minimal user input using Helm packages. You can either choose from our list of packages available on [artifacthub.io](https://artifacthub.io/packages/search?ts_query_web=appvia) or adopt our pattern and use [tf2helm](https://github.com/appvia/tf2helm) to build out your own packages. The solution leverages [Terraform](https://www.terraform.io/) and [Helm](https://helm.sh/) to create a Kubernetes Custom Resource Definition (CRD) Object watched and understood by a [terraform controller](https://github.com/appvia/terraform-controller) which then triggers a workflow that applies a referenced Terraform module.
Kubernetes / Community Projects:
-  [terraform controller](https://github.com/appvia/terraform-controller)
- …
=> Add terranetes channel

communication/slack-config/channels.yaml
Hi, I'd like to propose a Slack channel for [Kamaji](https://github.com/clastix/kamaji).
Kamaji is a tool aimed to build and operate a Managed Kubernetes Service with a fraction of the operational burden. With Kamaji, you can deploy and operate hundreds of Kubernetes clusters as a hyper-scale cloud provider.
- [Kamaji](https://github.com/clastix/kamaji)
Currently is the solution for hard multi-tenancy provided by [Clastix](https://clastix.io).
We are working to create a community around it as the project is in the development stage. It has been released just 6 days ago.
At the same time we would like to share solutions and get feedbacks from the cloud native community, so I think that the Kubernetes workspace would be the right one.
=> slack config: add Kamaji channel

communication/slack-config/channels.yaml
Hi, I'd like to propose a Slack channel for [Capsule](https://capsule.clastix.io/docs/).
Capsule implements a multi-tenant and policy-based environment in your Kubernetes cluster. It is designed as a micro-services-based ecosystem with the minimalist approach, leveraging only on upstream Kubernetes.
Currently is the soft multi-tenancy solution that [Clastix](https://clastix.io/) provides.
- [Capsule](https://github.com/clastix/capsule/)
- [Capsule Community](https://github.com/clastix/capsule-community)
We would like to make growing the community on the Kubernetes workspace, in order to make it easier the access to the cloud native community and be present also for other cloud native projects, on the same workspace.
For example we contributed to other cloud native proejcts like Kubespray …
=> slack config: add Capsule channel

communication/slack-config/channels.yaml
Adding a new channel for communication around sig node's project Evented PLEG. 
See [Evented PLEG doc](https://docs.google.com/document/d/1GfWDoKAYiaXApxayXmPl9bcK5ewyiimFDJ966r28TUE/edit#).
=> Add evented-pleg Slack channel

communication/slack-config/sig-release/usergroups.yaml
Lauri has stepped back from SIG Release some time ago. This cleanup should reflect the current state of the SIG. :sob: 
cc @kubernetes/sig-release-leads 
Refers to https://github.com/kubernetes/org/pull/3450, https://github.com/kubernetes/k8s.io/pull/3789
=> Remove `LappleApple` from SIG Release user group

OWNERS, communication/OWNERS, communication/marketing-team/OWNERS, contributors/guide/OWNERS, events/OWNERS, mentoring/OWNERS, sig-contributor-experience/devstats/OWNERS
/hold for review
/assign @mrbobbytables @cblecker @nikhita
=> Update owners for ContribEx

mentoring/programs/group-mentee-guide.md
Signed-off-by: AugustasV <reg1nt1z@gmail.com>
Fixes broken url in group-mentee-guide.md file
=> group-mentee-guide broken link fix

sig-docs/README.md, sigs.yaml
The [original one](https://docs.google.com/document/d/1ddHwLK3kUMX1wVFIwlksjTk0MsqitBnWPe1LRa1Rx5A/edit) has been marked as archived. It's linked to [the new one](https://docs.google.com/document/d/1emuO4nmaQq3K8JZ9-MQeIygtrCPO9kWv7U7RzTaW4F8/edit) now.
(Not sure should it be https://bit.ly/sig-docs-agenda or the long URL.)
=> Change SIG-Docs agenda link to the new one

sig-api-machinery/charter.md
AFAIK there is no longer a need to create subprojects at a rate that would burden the TLs, and since several of the people listed have switched focus, I think we should remove this section all together.
/assign @fedebongio @deads2k 
cc @cheftako @pwittrock @sttts in case one of you disagrees. (I'm happy to put this clause back in the future if it becomes necessary again)
=> Remove subproject creation exception

sig-docs/blog-subproject/README.md
Adding @nate-double-u (myself) to the list of blog editors.
Change as per https://github.com/kubernetes/website/pull/34285
=> Add Nate W. as a blog editor

communication/slack-config/restrictions.yaml, communication/slack-config/sig-testing/config.yaml
Adds a "TestGrid" channel for users and developers of our test visualization system, https://testgrid.k8s.io/
TestGrid is being continuously developed, and having an open, central place to discuss features, make announcements, and collaborate would be ideal. The general "sig-testing" channel doesn't quite fit for all of these users.
=> Add TestGrid channel under sig-testing

communication/slack-config/channels.yaml
Canonical Distribution of Kubernetes (cdk) has evolved to include both MicroK8s and Charmed Kubernetes. I'd like to rename this channel so it's more obvious that we're supporting all Canonical k8s offerings here.
=> rename cdk -> canonical-kubernetes

sig-node/CONTRIBUTING.md, sig-node/sig-node-contributor-ladder.md
Fixes #6612
As noted in the document, the SIG had a desire to establish transparent criteria for how it evaluates requests for reviewer and approver rights.  This document has been reviewed by existing SIG Node and CI sub-project leads with input suggested over past many months.
To highlight a key desire for the SIG, top-level approval rights in the `kubelet` sub-project have a strong preference to acquiring prior approval rights in an intermediate sub-folder or sub-system or adjacent area like e2e testing or CRI (client or server) side.    Since `kubelet` has intersection with both storage and networking code paths given our current project approach, making this explicit in our guidance felt appropriate given our project maturity.
Our goals are to …
=> SIG Node contributor ladder review guidance

icons/README.md
As per the discussion in #6527, the linked Google Slides deck does not exist. This pull request removes the link and reference to it in the documentation.
Fixes #6527
=> Remove link to deleted Google Slide deck

communication/slack-config/channels.yaml
Addresses issue #6729
This is a request for a public slack channel for African contributorsof Kubernetes for easy communication and mentoring of new African devs to the Kubernetes community.
Cc @somtochiama
=> Add africa-dev channel for dedicated k8s mentorship

communication/slack-config/channels.yaml
Add new channel for Contribex Elections Subproject.
We considered other mechanisms for keeping in touch with subproject contributors, but they weren't working.  As such, we need this channel in order to coordinate among Subproject contributors.
This is purposefully separate from the #election-officers channel, since that one is closed & private and only allows the current EOs to join so that they can discuss detailed election matters.  The new channel, to develop the subproject, will be open for everyone working on long-term election goals.
=> Add channel for Elections Subproject.

events/awards/README.md, events/awards/award-recipients/2020-award-recipients.md, events/awards/award-recipients/2021-award-recipients.md
As we have more Contributor Awards, instead of adding award recipients to the README.md, I suggest moving the award recipients from the README.md and into separate files by year.
This PR suggests the following changes:
- move the 2020 Contributor Award recipients from README.md to its own file in a new awards dir
- add the 2021 Contributor Award recipients
- Update README.md with links to the playbook and awards recipient files
=> Move Contributor Awards recipients from README.md to separate files and add 2021 award recipients

generator/app.go
the verify job redirects stdout to /dev/null:
https://github.com/kubernetes/community/blob/d8990155422b34cd1354be6074110e4c0bd74c16/hack/verify-generated-docs.sh#L33-L34
that means a validation error encountered (e.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/community/6598/pull-community-verify/1529966618602377216) was printed to stdout, so it was invisible
=> Write generate errors to stderr

sig-architecture/generics.md
as discussed in the last SIG Architecture meeting
cc @dims @johnbelamaric
=> Add generics policy for kubernetes

sig-scheduling/README.md, sigs.yaml
Fixes https://github.com/kubernetes/org/issues/3479
/assign @Huang-Wei 
/hold
for lgtm from a sig-scheduling lead
=> sig-scheduling: add kwok repo

sig-windows/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/3585
/assign @jayunit100 
cc @iXinqi @knabben 
/hold
for lgtm from a sig-windows lead
=> sig-windows: add windows-operational-readiness repo

sig-node/README.md, sigs.yaml
Update sigs.yaml and sig-node docs to rename special-resource-operator to kernel-module-management to match repo rename
Fixes [#3587](https://github.com/kubernetes/org/issues/3587)
=> Update sigs.yaml to rename special-resource-operator

sig-network/annual-report-2021.md
Add the SIG network annual report for 2021.
Fixes https://github.com/kubernetes/community/issues/6375
=> Add sig-network 2021 report

elections/steering/2022/README.md
Attention @kubernetes/steering-committee:
This answers a question that the current Election Officers have due to the CoCC being selected shortly before the election begins.  Under this clarification, people who are or were on the CoCC or SRC at any time during the "contribution year" are automatically eligible to vote.  Otherwise, we'd have ended up with a situation where folks who served in the CoCC from July 2021-July2022 would not be eligible.
@coderanger @kaslin @dims
=> Clarify CoCC & SRC addition to include the full year.

contributors/devel/sig-architecture/api-conventions.md
In reviewing an issue/PR I realized this lesson had not been documented
anywhere.  This is not the ideal mechanism, IMO, but better than
nothing.
This comes out of Service ClusterIP and NodePorts, plus #103546
@robscott @aojea @khenidak @liggitt @msau42
=> API conventions: add more on defaulting

events/awards/playbook.md
This PR fixes a small spelling error in the awards playbook
=> Fix spelling error in awards playbook

communication/slack-config/channels.yaml
This rename follows the repo rename in https://github.com/kubernetes/org/issues/3587.
=> Rename the SRO channel to KMM.

communication/slack-config/sig-release/config.yaml
Adds #release-obs-poc Slack channel for collaboration with SUSE folks around an OBS-based PoC of building k8s DEB/RPM packaging to avoid adding noise to the #sig-release channel
Fixes #6811
=> slack-config/sig-release: Add release-packages-poc channel

contributors/devel/sig-architecture/api-conventions.md
Conditions should follow the standard schema included in [k8s.io/apimachinery/pkg/apis/meta/v1/types.go](https://github.com/kubernetes/apimachinery/blob/release-1.23/pkg/apis/meta/v1/types.go#L1432-L1492).
This updates the condition guidance to reference the existing type and includes a 1.23 snapshot of the schema.
=> update condition guidance to use metav1.Conditions

contributors/devel/sig-architecture/api-conventions.md
=> api-conventions: fix leftover merge conflict mark

contributors/devel/README.md, contributors/devel/sig-api-machinery/controllers.md, contributors/devel/sig-api-machinery/generating-clientset.md, contributors/devel/sig-api-machinery/strategic-merge-patch.md, contributors/devel/sig-architecture/api-conventions.md, contributors/devel/sig-architecture/conformance-tests.md, contributors/devel/sig-node/cri-container-stats.md, contributors/devel/sig-release/release.md, contributors/devel/sig-storage/flexvolume.md, governance.md, sig-architecture/README.md, sig-architecture/naming/recommendations/001-master-control-plane.md, sig-cli/CONTRIBUTING.md, sig-multicluster/CONTRIBUTING.md, sig-multicluster/README.md
The old links for design proposals are totally unavailable now.
- #6591
The following files also contains old links, but leave untouched.
```
communication/meeting-notes-archive/201902-201911_Community_Meeting_Notes.md
events/2017/12-contributor-summit/kubernetes-client-libraries-open-space.md
events/2017/12-contributor-summit/current-state-of-client-libraries.md
events/2017/12-contributor-summit/feature-roadmap-2018.md
events/elections/2017/quintonhoole_bio.md
sig-auth/archive/meeting-notes-2017.md
sig-auth/archive/meeting-notes-2018.md
sig-node/archive/meeting-notes-2017.md
sig-node/archive/meeting-notes-2018.md
sig-node/archive/meeting-notes-2020.md
sig-instrumentation/archive/meeting-notes-2017.md
```
=> Fix links for k/design-proposals-archive

communication/slack-config/channels.yaml
"dra" stands for dynamic resource allocation, a KEP that got accepted for
Kubernetes 1.25:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/3063-dynamic-resource-allocation#readme
It is a complex feature that is owned by SIG Node, SIG Scheduling and various
others. Significant discussions are expected not just while we develop this
feature, but also while third-party developers and users start to make use of
the functionality. It is similar to CSI (owned by SIG Storage) in that regard
which also has its own #csi channel.
Discussing it in either of these SIG's channels would miss relevant people and
may cause additional noise for those who are not interested in details of this
new feature. We also considered other means of communication (CNCF #tag-runtime
Slack channel, …
=> slack-config: create "dra" channel

sig-node/README.md, sigs.yaml
This PR does a minor update in the link to the OWNERS of sub-project security-profile-operator that is referenced under SIG node README page.
=> Updated the security-profile-operator reference

sig-node/sig-node-contributor-ladder.md
Fixes the reference to [sub-projects](https://github.com/kubernetes/community/blob/master/sig-node/README.md#subprojects) in [sig-node-contributor-ladder.md](https://github.com/kubernetes/community/blob/master/sig-node/sig-node-contributor-ladder.md)
=> Corrected the README link

contributors/guide/issue-triage.md
- Fix link for invalid `[Define its priority.](##step-three-define-priority)` and `[Follow Up](#Step-Five:-Follow-Up)`
- Remove redundant spaces
- Change https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/ to https://kubernetes.io/docs/tasks/debug/ since it's reorganized
- Use `https://` instead of `http://` for Slack invitation
=> Fix link for issue-triage.md

communication/slack-guidelines.md, communication/youtube/youtube-guidelines.md, communication/zoom-guidelines.md, contributors/guide/release-notes.md
While the trailing brackets [] are markdown compatible they break the links with the contributor-site link generator when the content is ingested. The contributor-site script that does the ingestion needs to be updated, but removing them is a short term solution to fix the site.
=> Fix markdown links to be compatible with contributor-site

events/awards/README.md, events/awards/award-recipients/2019-award-recipients.md
This PR adds the 2019 contributor award recipients to k/community/events/awards
Source of 2019 contributor award recipients is https://www.kubernetes.dev/community/awards/2019/
=> Add 2019 contributor award recipients to k/community

communication/slack-config/channels.yaml, communication/slack-config/restrictions.yaml, communication/slack-config/sig-node/OWNERS, communication/slack-config/sig-node/config.yaml, communication/slack-config/sig-node/usergroups.yaml, communication/slack-config/users.yaml
This is for pinging the right set of people when posting on a channel like #sig-node or #sig-scheduling that they might not actively follow.
=> slack sig-node: add users and dra-dev group

contributors/devel/running-locally.md
go get does not work anymore, please see https://github.com/kubernetes/kubernetes/issues/111351 for the error.
So we switch to go install as documented in cfssl repository:
https://github.com/cloudflare/cfssl/#installation
/kind cleanup
Use the newer "go install" variant as we are above go 1.18
Fixes #
=> Update instructions to install cfssl

committee-code-of-conduct/governance/onboarding-offboarding.md
The code of conduct committee docs are currently missing a couple slack channels that new members will need to join. This PR adds that!
=> docs: update slack channel membership for onboarding CoCC members

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
Signed-off-by: Kim Tsao <ktsao@redhat.com>
Fixes #
N/A
We would like to add a new user group `devfile-devs` so our core team can be directly notified on our `#devfile` channel
=> Add new devfile-devs user group

communication/README.md
Incorrect form of noun, pronoun, and unwanted article usage
Changed "all of communication" to "all of the communication" -> article usage fixed
Changed "community groups" to "community group's" -> noun form fixed 
Replaced "listed in the" to "listed on the" -> preposition fixed
Changed "groups and" to "groups and," -> added (,) to separate the elements
Changed "each community groups" to "each community group" -> mentioned "each" as individual group so removing (s) would be appropriate
Changed "weekly" to "a weekly" -> missing a determiner before it, adding "a" could be essential.
Changed "held every" to "is held every" -> missing verb fixed.
=> Improvements to Docs in (Communication)

contributors/devel/sig-node/cri-container-stats.md
It seems that the summary API [the CRI doc](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/cri-container-stats.md) is referencing was refactored in v1.20, so this PR fixes the broken link by referring to the summary API in v1.19.
=> cri-container-stats: fix broken link to legacy summary API

communication/slack-config/channels.yaml
This PR adds a slack channel for Oracle Cloud Infrastructure (OCI) provider - https://github.com/oracle/oci-cloud-controller-manager. It includes cloud-controller-manager, CSI driver, volume provisioner open source implementation of Oracle Cloud Infrastructure Cloud Provider. 
No open issues related to this PR
=> Add official Oracle Cloud Infrastructure OCI provider channel

sig-contributor-experience/README.md, sigs.yaml
=> changed the marketing-team subdirectory name to contributor-comms

liaisons.md
Just searched and replaced the assignments for now. We can rebalance later as discussed in the chat.
Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>
Part of https://github.com/kubernetes/steering/issues/256
cc: @kubernetes/steering-committee
=> steering: Update liaison assignments following 2023 election

contributors/devel/development.md
Haven't found an issue created yet but ran into an issue on master where `make test` command was failing and it wasn't evident from errors whats the issue. After poking around I figured minimum bash version required is >4.3 and couldn't find this info anywhere in the docs.
=> Add requirement for minimum bash version for running unit tests

communication/contributor-comms/role-handbooks/blog-coordinator.md
Signed-off-by: Frederico Muñoz <fsmunoz@gmail.com>
Add Blog Coordinator role handbook
=> Add blog coordinator handbook

communication/slack-config/channels.yaml
This PR adds a new Slack channel called #external-secrets-dev to be used by the maintainers and contributors of the external-secrets CNCF project (external-secrets.io). It will be used to coordinate development communication amongst maintainers and contributors leaving `#external-secrets` to be user and broader community focused.
=> add external-secrets-dev channel

communication/slack-config/channels.yaml
The `#ko-project` channel would like to rename to `#ko-build`.
This matches the project's new GitHub org (https://github.com/ko-build) and website (https://ko.build) and main command (`ko build`).
=> slack-config: rename ko-project to ko-build

communication/slack-config/channels.yaml
channels: Add kube-operating-systems-dev
This is intended to be a cross-distro/cross-os channel for
cooperation and questions between developers/maintainers of
Kubernetes-native and Kubernetes-adjacent operating systems.
On topic are things like system provisioning, Kube-native APIs
for operating system configuration and management, sharing
image-based update ideas and code, etc.
For example: Talos Linux, Fedora/RHEL CoreOS, Flatcar, etc.
This thread got some interest:
https://twitter.com/cgwalters/status/1583122147756556288
and I'm hoping we can move some conversation here.
=> channels: Add kube-operating-systems-dev

communication/slack-config/channels.yaml
This PR adds a slack channel for The Nutanix CAPI Provider (CAPX) - https://github.com/nutanix-cloud-native/cluster-api-provider-nutanix
NONE
=> Add official Nutanix CAPI Provider Slack Channel

sig-release/README.md, sigs.yaml
Signed-off-by: leonardpahlke <leonard.pahlke@googlemail.com>
None
ref: PR to rename the ci signal team https://github.com/kubernetes/org/pull/3738
/cc @palnabarun @reylejano @Nivedita-coder 
cc @kubernetes/sig-release-leads
=> Update subteams in the release team

sig-auth/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/3688
@enj should this be a new subproject? or is there another that would be better?
=> sig-auth: Add sig-auth-tools repo

hack/generate-devstats-repo-sql.py
spelling fix on 'defintions' in the first block of comments in generate-devstats-repo-sql.yaml
Fixes #
=> typo in generate-devstats-repo-sql.yaml 

communication/slack-config/channels.yaml, communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
Add #podman-desktop to the Kubernetes slack
N/A
**Overview:**
Hey all!
We're a dev team that focuses on creating a GUI interface
for "Podman" which is an open source project.
Podman Desktop implements Kubernetes heavily as you can create a
container, change it to a pod, and then deploy to Kubernetes. All with
open source tools.
Under-the-hood it is podman (open source) as well as the kubernetes
Node.JS library.
We have first class support for Kubernetes and wish to
be part of the Kubernetes slack for all community communication.
Our future intentions of the project is the implementation of Docker
Compose to Kubernetes tools such as Kompose
(https://github.com/kubernetes/kompose), which I'm a core maintainer of.
We have a ROADMAP to add more Kubernetes …
=> Add #podman-desktop to the Kubernetes slack

communication/moderators.md
removing myself from moderation and putting correct info in the slack OWNERS area
many of the other areas need updating too as I'm seeing people who haven't been active in years. current mods can deal with that though :)
=> removing me and adding current names in slack 

contributors/devel/sig-node/OWNERS, sig-node/OWNERS
I am no longer active in SIG Node. Thanks!
/kind cleanup
/sig node
Fixes #
=> Remove ehashman from sig-node roles

sig-architecture/generics.md
Kubernetes v1.24 is built on Go 1.18, and will not revert to Go 1.17 at this point.  Ergo, it should be allowed to use Go generics as soon as 1.24 is the oldest supported release.
cc @dims
cc @BenTheElder 
cc @liggitt 
=> Adjust guidance on generics to include v1.24

communication/contributor-comms/CHARTER.md, communication/contributor-comms/role-handbooks/Social-Media.md, communication/contributor-comms/role-handbooks/council.md, communication/contributor-comms/role-handbooks/storytellers.md, communication/contributor-comms/storytelling-resources/blog-guidelines.md, communication/contributor-comms/storytelling-resources/social-guidelines.md
Related to issue https://github.com/kubernetes/community/issues/6641
Follow-up to PR https://github.com/kubernetes/community/pull/6911
This PR changes files in k/community/contributor-comms in the following manner:
- to fix links for the dir name change from k/community/marketing-team to k/community/contributor-comms
- to reflect the name change of Upstream Marketing to Contributor Comms
/cc @kaslin @chris-short
=> Update files in k/community/contributor-comms to reflect name change

archive/wg-component-standard/component-config/README.md
Adds the VCCF doc to the community archive for wg-component-standard.
While this doc predates the WG, it is a primary historical record of
ComponentConfig's early development, which was primarily driven by
that WG.
=> Add Versioned Component Configuration Files doc

sig-node/README.md, sigs.yaml
Add resource-management subproject to sig-node
As part of this, add `dynamic-resource-management` staging repo as part of this subproject as well as absorb the (previously) standalone subproject for `noderesourcetopology-api` into this new subproject.
/cc @derekwaynecarr 
/cc @swatisehgal 
/cc @pohly
=> Add resource-management subproject to sig-node

contributors/devel/sig-release/kubernetes-versions.md
Part of the conversation in https://kubernetes.slack.com/archives/CJH2GBF7Y/p1669065861073859, https://github.com/kubernetes/sig-release/issues/850:
We're now publishing the `k8s-stable4` version marker so this PR documents it.
Relevant to https://github.com/kubernetes/sig-release/issues/2094
/assign @justaugustus @jeremyrickard @cici37
cc: https://github.com/orgs/kubernetes/teams/release-engineering
=> Document the k8s-stable4 version marker

communication/slack-config/sig-release/usergroups.yaml
Part of https://github.com/kubernetes/sig-release/issues/2099.
/assign @saschagrunert @cpanato @puerco
cc: @kubernetes/sig-release-leads @jeremyrickard @Verolop
=> sig-release: Update Slack usergroups for lead promotions

contributors/devel/running-locally.md
This PR will update the etcd reference in [running-locally.md](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md) to match the exact [header ](https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#etcd)
=> Updated the reference to etcd

contributors/devel/development.md
Today we had k8s upstream training[1] in Japan, and we found this table is not updated at this time.
The pull request[2] updated the go version to 1.19 in Kubernetes v1.25 development.
This updates the table to catch that.
[1]: https://www.okinawaopendays.com/session-dec14-training
[2]: https://github.com/kubernetes/kubernetes/pull/111679
=> Update required go version

contributors/guide/github-workflow.md
This is related to the blog post proposed at https://github.com/kubernetes/contributor-site/pull/313 and the Prow/Tilde squashing method. This change adds a reference to the method to the guide.
=> Add tide/merge-method-squash option for automated squashing

communication/slack-config/OWNERS
Moved multiple former slack admins to emeritus.
Added myself as OWNER; while this is redundant right now because of root-level ownership, it won't always be.
Please comment if there are additional slack admins I should be adding.
=> Update slack approvers to match current team

communication/slack-config/channels.yaml
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>
The purpose of the PR is to create a slack channel for the project https://github.com/vmware/cluster-api-provider-cloud-director
- The project implements cluster-api (https://github.com/kubernetes-sigs/cluster-api) for VMWare cloud director platform.
Fixes #
=> Add cluster api cloud director slack channel

sig-cloud-provider/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/3866
/assign @nckturner 
/hold
for lgtm from sig-cloud-provider lead
=> sig-cloud-provider: add aws-file-cache-csi-driver repo

communication/slack-guidelines.md, communication/youtube/youtube-guidelines.md, communication/zoom-guidelines.md, events/2016/developer-summit-2016/KubDevSummitVoting.md, events/2016/developer-summit-2016/Kubernetes_Dev_Summit.md
When using reference links (`[a link to something][something]`) the link goes itself is referred to later in the file. This normally should be a line that starts with the reference name in brackets, followed by the actual link (`[something]: <link>`).
Many of these reference links in the repo have unnecessary leading spaces. While this renders OK, at least with GitHub's markdown rendering, it currently causes problems for sites like kubernetes.dev that pull in these docs and attempt to update the links so they are usable from a different rendered location.
While the script that does that import should probably be updated to be a little more robust, this addresses the immediate need of fixing these broken kubernetes.dev links by removing the leading whitespaces so they are properly …
=> Correct reference link formatting

sig-cloud-provider/README.md, sigs.yaml
kubernetes-sigs/aws-alb-ingress-controller has long since renamed to aws-load-balancer-controller. This updates references accordingly.
/cc @kishorj 
None
=> aws-alb-ingress-controller was renamed to aws-load-balancer-controller

elections/steering/2023-GB/candidate-cblecker.md, elections/steering/2023-GB/candidate-justaugustus.md, elections/steering/2023-GB/election.yaml
Elekto errors out with an empty profile.
Repeated candidate name.
also bumped start date to today to test.
/assign @jberkus
=> Fix 2023 GB election bios

communication/contributor-comms/role-handbooks/Comms-Events.md
This PR tends to solve:
- a couple of broken links found [here](https://github.com/kubernetes/community/blob/master/communication/contributor-comms/role-handbooks/Comms-Events.md#minimum-skills-and-requirements)
- a minor typo in the above-referenced link
=> FIX: Broken Link on Comms Events Lead Role Handbook

contributors/devel/sig-architecture/conformance-tests.md
We have not previously documented demotion of a conformance test,
although we have several examples. A request for a backport of
demotion was questioned based on the lack of process and this update
clarifies that responsibility.
=> Describe the demotion process for a conformance test

communication/best-practices.md, contributors/chairs-and-techleads/leadership-changes.md, contributors/guide/contributor-cheatsheet/README.md
This pull request updates several docs to reflect that the historic google group https://groups.google.com/g/kubernetes-dev has been sunset and archived as of January 2022.
The new group is https://groups.google.com/a/kubernetes.io/g/dev.
This pull request only updates general docs and does not touch any references in meeting notes etc which should remain pointing to the old archived group.
=> Fix k8s dev mailing list links

committee-steering/governance/README.md, committee-steering/governance/annual-reports.md, committee-steering/governance/sig-governance.md, governance.md
The community meeting has not been an effective means of communicating important information or updates for a few years now, and is no longer occurring on a regular cadence (and may be removed altogether soon in the future).
As such it should be removed as a community group governance requirement.
/hold for comments
=> Remove community meeting requirements from governance docs

sig-scalability/slos/pod_startup_latency.md
Follow-up of https://github.com/kubernetes/enhancements/pull/3739#discussion_r1094255726
With the introduction of [PodSchedulingReadiness](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/), between pod gets created and scheduled, there might be a new phase `SchedulingGated`, to claim it's not scheduling ready. And this is controlled by external components.
So this PR is updating the statement of 'schedulable pod' to avoid ambiguity on the related SLO.
=> clarify the term 'schedulable pod' in SLO document

communication/contributor-comms/role-handbooks/storytellers.md
This PR **tends** to solve a couple of broken links found [here](https://github.com/kubernetes/community/tree/master/communication/contributor-comms/role-handbooks).
However, before merging the changes, we need to take a look at the last line of [this](https://github.com/kubernetes/community/blob/master/communication/contributor-comms/role-handbooks/storytellers.md#expectations) content. There's a broken link found here as well which is **not fixed**:
_There is no shadow roles for Storytellers. If Storytellers are interested in becoming a shadow they can read more about it in the [Marketing Council Handbook](https://github.com/kubernetes/community/blob/master/communication/contributor-comms/role-handbooks/council.md)._
As per the research, I found that no such file exists in the repo/has …
=> FIX: Broken Link on Comms Role-hadbooks

contributors/devel/sig-node/cherry-picks.md, contributors/devel/sig-node/container-runtime-interface.md, contributors/devel/sig-node/e2e-node-tests.md, contributors/devel/sig-node/triage.md
This PR updates the references in [sig-node](https://github.com/kubernetes/community/tree/master/contributors/devel/sig-node) under the contributors development area
=> Update the references under sig-node

contributors/devel/running-locally.md
I think the variable has been renamed at some point. `DNS_DOMAIN=${KUBE_DNS_NAME:-"cluster.local"}`
Fixes #
=> Fixing wrong KUBE_DNS_NAME at running locally

committee-code-of-conduct/README.md, committee-code-of-conduct/transparency-reports/2022-h1.md
Add the first transparency report for 2022 to the conduct directory. Also including a small update to the readme to reflect membership
Fixes #
=> Conduct: Add H1 2022 Transparency Report

contributors/devel/running-locally.md
Fixes #
- Replace image/container listing commands with containerd equivalent
- Document running locally using containerd configured with systemd cgroups
=> update running locally instructions

communication/slack-config/channels.yaml
Hi, I'd like to propose a Slack channel for [Nauticus](https://nauticus.edixos.com/).
**Nauticus** is a Kubernetes space management controller. With Nauticus, you can easily create, update, and delete spaces within your Kubernetes cluster. Each space is a unique namespace with its own set of resources and quotas, making it ideal for multi-tenancy environments.
We believe that a Nauticus channel in the Kubernetes Slack community would foster greater collaboration and help to build a strong, supportive community around the project.
We would like to make growing the community on the Kubernetes workspace, in order to make it easier the access to the cloud native community and be present also for other cloud native projects, on the same workspace.
Thank you !
=> slack config: add Nauticus channel

sig-ui/charter.md
Dashboard cluster addon had been removed already.
https://github.com/kubernetes/kubernetes/pull/107481
Fixes #
=> Remove cluster addon for dashboard

contributors/devel/sig-architecture/api_changes.md
Fixes the  error anchor link of chapter `Multiple API versions`
=> Fix error anchor link of multiple-api-versions

communication/slack-guidelines.md
We've always had the working rule that projects not owned by a SIG never get more than two channels (and only get one to start).  However, the explanation of that in the guidelines has been very unclear, leading to some argument.  This PR makes it explicitly clear.
/area slack
attn: @mrbobbytables @coderanger @markyjackson-taulia
=> Clarify rules around having only two channels per external project

contributors/devel/sig-architecture/api-conventions.md
`design-proposals` directory in `community` repo moved to a `design-proposals-archive` repo.  Update links in API conventions document.
=> Fix design-proposals links in API conventions

contributors/devel/sig-architecture/api-conventions.md
Fixes a typo in the API convention `Concurrency Control and consistency` part.
=> docs: fix api convention concurrency control and consistency part typo

contributors/guide/scalability-good-practices.md
Performed 2 actions:
- Run `npx prettier --w`
- Tweak long lines to have a consistent style with other .md files in this folder.
=> Tweak line wrappings for consistency

contributors/devel/sig-testing/writing-good-e2e-tests.md
This reflects the recent changes that came with Ginkgo v2. The goal is to get this reviewed and then send out an email to Kubernetes-Dev to make developers aware of these changes.
/sig testing
/cc @aojea @onsi
=> writing-good-e2e-tests.md: polling, contexts and failure messages

committee-steering/governance/sig-governance.md, contributors/chairs-and-techleads/technical-lead.md
Follow up on https://github.com/kubernetes/community/pull/7094 - clarification on KEPs approval responsibility
cc @steering-committee
=> Added a TLs responsibility to approve KEPs

committee-steering/governance/sig-governance.md, contributors/chairs-and-techleads/technical-lead.md
This reverts commit 0037f98e6a9dce802a4d7af6f0f79f92004cfab9, which was accidentally merged with #7095 
=> Revert "TLs are approving KEPs"

communication/contributor-comms/role-handbooks/storytellers.md
This PR seeks to resolve the issue of the broken link in the Storytellers.md file for the **Marketing Council Handbook**. The link had been leading to a 404 Error page, however, with this PR, it should now be functioning correctly.
=> Updated the Marketing Council Handbook Link in the Storytellers.md file

committee-steering/governance/sig-governance.md
This PR removes the Tech Lead role from automatically rolling up into the Chair role and explicitly defines the TL responsibilities. It incorporates some language from #7095 to further clarify responsibilities around KEP stewardship.
TL;DR of changes:
- Both Chair and TL suggested # of leads is now 2+
- Removed quarterly reporting requirement to k-dev from Chair role (this hasn't really ever been done)
- Both Chair and TL are responsible for maintaining KEP metadata / state (but may delegate responsibility)
- TL's are responsible for reviewing and approving KEPs (but may delegate for individual KEPs)
Note - there are a number of other things in the governance doc that are not inline with how we as a project function day to day (namely around subproject creation requiring a KEP). Those …
=> SIG Governance: Split Chair & TL roles

communication/slack-config/channels.yaml
This PR is a request for the [bpfd](https://bpfd.netlify.app/) project to receive a channel in the Kubernetes Slack Workspace. 
Bpfd allows users to easily deploy and manage [bpf programs within kubernetes clusters](https://bpfd.netlify.app/k8s-deployment/).  The project includes a [kubernetes operator](https://github.com/redhat-et/bpfd/tree/main/bpfd-operator) written using the operator SDK framework, and there are already [plans to integrate it with Blixt](https://github.com/Kong/blixt/issues/77) (a [soon to be](https://github.com/kubernetes/org/issues/3875) Kubernetes-sigs project).  
The project is [fully open source](https://github.com/redhat-et/bpfd#license). Due to increased interest from the kubernetes community we would like a  dedicated public channel for further upstream …
=> Add Slack Channel for BPFD

contributors/devel/running-locally.md
depth=1 will break git version info and break the build
Fixes #
https://github.com/kubernetes/kubernetes/issues/116716 may be related, see also https://github.com/kubernetes/test-infra/issues/26590
=> stop suggesting depth=1, suggest filter=blob:none instead

communication/slack-config/usergroups.yaml
=> slack: add usergroup for Kubernetes GitHub Admins

sig-api-machinery/README.md, sigs.yaml
Towards https://github.com/kubernetes/community/issues/7097
ref https://github.com/kubernetes/community/pull/7195#discussion_r1145165124
/assign @kubernetes/sig-api-machinery-leads
=> Fix link for controlplane subproject

sig-security/README.md, sigs.yaml
Adding Self Assessments as a subproject to SIG Security
Fixes #
=> Add Self Assessments as a subproject to SIG Security

committee-steering/governance/sig-governance.md
This PR does 3 things, broken down by commit:
- bd5c10e8b5b217d108a9bf027f5db6a8018a5ce9 - This is a no-op, just general formatting and readability improvements.
- 2f4aafcf6892d5fb34bff81abf8f051def3f38c3 - Removes the requirement to send yearly sig updates to the mailing list. No SIG is actively doing this today.
- 14461a6fb57d89b58fb66328eac016a6cb3c81ea - Completely reworks the subproject section on creation and requirements to bring in line with how they are actually being managed.
/hold for review
=> Clean up SIG Governance

sig-cloud-provider/README.md, sigs.yaml
Fixes https://github.com/kubernetes/org/issues/4106
/assign @nckturner 
/hold
for lgtm from a sig-cloud-provider lead
=> sig-cloud-provider: add aws-fsx-openzfs-csi-driver repo

communication/slack-config/sig-docs/docs-channels.yaml
Fixes #7183
This PR adds a new slack channel for SIG-Docs Bulgarian localization (`kubernetes-docs-bg`).
This request is based on https://github.com/kubernetes/community/issues/7183
=> Add new slack channel for SIG-Docs Bulgarian localization (kubernetes-docs-bg)

contributors/devel/sig-instrumentation/logging.md
This is mentioned in [1], but since structured logging is now the norm (and soon contextual logging), I think this is a more appropriate and more permanent place for the style guide.
[1] https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md
=> Add log message style guidelines

sig-docs/annual-report-2022.md
This PR adds the SIG Docs annual report for 2022
Fixes https://github.com/kubernetes/community/issues/7106
SIG Docs co-chairs: @divya-mohan0209 @natalisucks 
SC Liaison: @cpanato
/sig docs
/area annual-reports
=> SIG Docs annual report 2022

communication/slack-config/channels.yaml
This PR adds a slack channel for Cluster API k3s controlplane and bootstrap providers: https://github.com/cluster-api-provider-k3s/cluster-api-k3s.
As per discussion at https://github.com/cluster-api-provider-k3s/cluster-api-k3s/discussions/32.
=> Add cluster-api-k3s Slack Channel

sig-apps/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/4137
cc @ahg-g 
/assign @soltysh 
/hold
for lgtm from at least one sig-apps lead
=> sig-apps: add jobset repo

communication/slack-config/channels.yaml
This PR adds a slack channel for AWS Gateway API Controller for VPC Lattice: https://github.com/aws/aws-application-networking-k8s.
Fixes #
=> add vpc-lattice-k8-community to slack

sig-windows/annual-report-2022.md
=> SIG-windows-2022-annual-report

sig-scheduling/annual-report-2022.md
Fixes #7114
/cc @alculquicondor @Huang-Wei
=> sig-scheduling annual report

contributors/devel/README.md
There were several inaccessible outdated links in the 'contributors/devel/README.md', so I fixed them. Could you please check if there are any problems with this modified?
Fixes #
- Modified the below links 
- User Guide
- Cluster Admin Guide
- REST API documentation
- Authentication
- Authorization Plugin
=> Modified the links in contributors/devel/README.md

github-management/README.md
=> docs: fix tiny typo in github-management `README.md`

sig-node/README.md, sig-node/annual-report-2022.md, sigs.yaml
/sig node
relates to: #7111 
/cc @mrunalp 
Tasks still left:
=> SIG Node Annual Report 2022

mentoring/programs/google-summer-of-code.md
The Past Participation section from the Mentoring Docs had to link a list of project ideas published for GSoC at the [CNCF Mentoring repo](https://github.com/kubernetes/community/blob/master/mentoring/programs/google-summer-of-code.md#past-participation). To get an idea about the projects, one can look at the list provided. Unfortunately, **the redirected link was found to be broken**. This contribution aims to fix the link, providing access to the list of project ideas. It is hoped that this contribution will be counted, as it is an effort to improve the accessibility of the project ideas. 
Furthermore, this ain't a major contribution, I am doing best to familiarize myself with Kubernetes. I appreciate your time and I hope this is a valid pull request. Hopefully soon will be able to …
=> CNCF + Summer of Code Mentoring Repo Link Detached - Fixed

contributors/devel/sig-architecture/api-conventions.md
This change updates many Kubernetes document links in the API Conventions document, as many links had changed from when the document was initially published.
=> Fix kubernetes doc links in api conventions doc

communication/slack-config/channels.yaml
This PR adds a Slack channel for [ebpf](https://ebpf.io/) which is a burgeoning technology that enables running sandboxed programs in privileged contexts (such as an operating system kernel).
eBPF has been gaining prevalence in the Kubernetes SIGs community with projects such as [bpfd](https://github.com/kubernetes/community/pull/7172), [blixt](https://github.com/Kong/blixt/discussions/42) and with Kubernetes SIGs already having software that utilizes it such as [KPNG](https://github.com/kubernetes-sigs/kpng/tree/master/backends/ebpf).
The purpose of this channel will be general discussion and help for building and running eBPF programs on Kubernetes clusters as several of us in the SIG Network community are particularly trying to help grow this technology in the Kubernetes context and …
=> feat: add ebpf channel

sig-docs/blog-subproject/README.md
=> fix: Typo in sig-docs/blog-subproject README

mentoring/programs/lfx-mentorship.md
PR fixes broken link to CNCF mentorship Repository.
https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/README.md
=> lfx-mentorship repo detached

communication/slack-config/channels.yaml
This is a request for the [Atmosphere](https://github.com/vexxhost/atmosphere) project to get a channel in the Kubernetes Slack.
The project allows you to deploy a full Kubernetes control plane (using `kubeadm`), deploy an OpenStack cloud on top of it (using `openstack-helm`, which the community exists on the Kubernetes slack), leverage Rook to provide object storage and use the Cluster API for OpenStack to deploy Kubernetes clusters on top of that infrastructure.
The project is fully open sourced, there are several contributors from different organizations and with the increased volume of PRs, we wanted to have a space that new users can talk and ask about it, but also a space for existing developers to discuss the project.
=> Add channel for Atmosphere

elections/README.md, elections/steering/documentation/README.md
This PR starts the new, overhauled documentation for running a Steering election.  This is the start, which documents the election Roles.  I'm PRing it so that other members of the Subproject can collaborate on adding additional documentation over time -- and importantly, even if these docs are incomplete, they are better than what is already present.
Also, the current Officers need them.
@parispittman @mrbobbytables @jdumars @fsmunoz 
@dims @coderanger @kaslin @bridgetkromhout
=> Begin new Steering Committee election docs

sig-release/annual-report-2022.md
This PR adds the SIG Release 2022 Annual Report. 
Fixes #7112
=> SIG Release 2022 Annual Report

contributors/devel/sig-release/cherry-picks.md
I think it's worth adding this to the guidelines.
I made this as a result of [feedback](https://github.com/kubernetes/kubernetes/pull/117149#issuecomment-1507687032) to my own cherry-pick.
Fixes #
=> docs: Ask for cherry-picks to be made in order from newest to oldest releases

sig-scheduling/README.md, sigs.yaml
Fixes https://github.com/kubernetes/org/issues/4174
/assign @Huang-Wei @alculquicondor 
/hold
for lgtm from at least one sig-scheduling lead
=> sig-scheduling: add kube-scheduler-wasm-extension repo

sig-scheduling/CONTRIBUTING.md
Fixes https://github.com/kubernetes/community/issues/7228
=> Add CONTRIBUTING.md to sig scheduling

contributors/devel/sig-testing/e2e-tests-kubetest2.md
This commit updates the 'e2e-tests-kubetest2.md' documentation. Instead of instructing users to use a `gsuti`l command to find release names, they are now directed to visit the Kubernetes GitHub releases page. This change removes the reliance on GCS as the release buckets will eventually be fully replaced with the community owned `dl.k8s.io` endpoint.
ref https://github.com/kubernetes/k8s.io/issues/2396
=> Update e2e-tests-kubetest2.md with new source for Kubernetes releases

.github/ISSUE_TEMPLATE/leadership-change.yml
Adds an issue template for SIG/WG leadership changes based off this doc: https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md
/assign @jberkus @kaslin @palnabarun
=> Add issue template for leadership change

communication/slack-config/channels.yaml
This PR adds a slack channel for The Cluster API Add-on Provider for Helm (CAAPH) - https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm
NONE
=> Add official CAAPH Slack Channel

.github/ISSUE_TEMPLATE/leadership-change.yml
When using the new issue template for https://github.com/kubernetes/community/issues/7340 I noticed a couple of links to fix.
=> Fixing links in leadership change issue template

.github/ISSUE_TEMPLATE/leadership-change.yml
Adds a textarea for labels and other prow commands since there isn't a singular set of labels that can be added directly to the template.
=> Add label section to leadership change template

contributors/devel/sig-node/triage.md, sig-node/CONTRIBUTING.md, sig-node/README.md, sig-node/annual-report-2021.md
/sig node
Fixes #7223
- - [x] add code path for components and test-grid/job code pathes
- - [x] add e2e tests and e2e_node tests doc links
=> Sig node contributing.md update

communication/slack-config/channels.yaml
This is a request for the [eksctl](https://eksctl.io/) project to have a channel in the Kubernetes Slack.
eksctl is a simple CLI tool for creating and managing clusters on EKS - AWS's managed Kubernetes service. The project is open source, and we want to move our Slack channel to Kubernetes Slack.
=> add eksctl channel in k8s slack

github-management/OWNERS, github-management/README.md
Ref:
- [sig contribex thread](https://groups.google.com/g/kubernetes-sig-contribex/c/PtLSBDS2yms/m/oFpc3PqUAQAJ) for nomination
- @ameukam's [email](https://groups.google.com/a/kubernetes.io/g/steering/c/-ubWV0Daaxk/m/avoaWI7fAAAJ) to steering to step down 
Lazy consensus achieved.
need majority of steering committee to lgtm this change
/assign @cblecker @mrbobbytables @palnabarun @idvoretskyi 
Can you also +1 here?
/assign @MadhavJivrajani 
Can you confirm that you are interested in joining the GitHub Admin Team and accept the security embargo policy?
=> github-management: add madhav as github admin

sig-testing/README.md
SIG Testing's README has a link to a recording of "KubeCon NA 2022 - SIG Testing: Intro And Updates", which currently goes to https://www.youtube.com/watch?v=CdKBl6CncHg. That's the wrong link though- although the first slide in that video says SIG Testing, it's actually a talk about SIG Security. 
Fixes by using the correct link.
=> Fix KubeCon video link

sig-windows/README.md, sigs.yaml
The sig-windows meeting notes was causing rendering issues on some systems due to use of tables. To work around this, a new meeting note doc has been created with a link to the old notes which have now been archived.
=> sig-windows: Update meeting notes link

sig-docs/README.md, sigs.yaml
The `sig-docs-ru-owners` GitHub team was not mentioned in the "Contact" list. However, it exists and operates, thus adding it.
=> Adding sig-docs-ru-owners to sig-docs/README.md

sig-release/meeting-notes-archive/2017.md, sig-release/meeting-notes-archive/2018.md, sig-release/meeting-notes-archive/2019.md, sig-release/meeting-notes-archive/2020.md, sig-release/meeting-notes-archive/2021.md, sig-release/meeting-notes-archive/2022.md
Following the [instructions for SIG-Docs](https://github.com/kubernetes/community/tree/master/sig-docs/meeting-notes-archive), I archived all the previous year's meeting minutes into markdown.
I didn't spend a ton of time reviewing the content for any formatting issues, as this process is more for record keeping, searchability, and improving the speed of the running notes' doc vs. intended for regular use.
Fixes: https://github.com/kubernetes/sig-release/issues/2255
/cc @RohanSasne
=> adding meeting minutes to yearly archive

elections/steering/2023/OWNERS, elections/steering/2023/README.md, elections/steering/2023/election-template.yaml, elections/steering/2023/election_desc.md, elections/steering/2023/nomination-template.md, elections/steering/2023/voters.yaml
This adds the 2023 election officers and alternates per [Steering approval](https://github.com/kubernetes/steering/issues/268).
Also adds some template files for the EOs to set up the 2023 election.
Needs LGTM by one steering member.
Attn: @kaslin @bridgetkromhout @dims @cblecker @lachie83 
=> Adds the 2023 Election officers

communication/slack-config/channels.yaml
Hi, We'd like to create a channel for our community
The project is open source, website at https://kuadrant.io/, source at https://github.com/Kuadrant
We do have an existing community, albeit on our own slack, but we're interested in moving it to the kubernetes slack for easier discovery and awareness.
At this time there is no commercial service built on it, but there will likely be soon. The contributors are primarily from Red Hat at this time.
Asked, with a provisional yes, in slack-admins as well https://kubernetes.slack.com/archives/C4M06S5HS/p1689175964952669
I might follow up with a usergroup for maintainers at a later time.
Thanks
fyi @maleck13 @jasonmadigan @thomasmaas @alexsnaps @guicassolato
=> Add kuadrant channel

events/events-team/README.md, events/events-team/operations/README.md
Add Operations handbook and update base event team page with appropriate links
=> add Operations Handbook to event team

communication/slack-config/channels.yaml
This PR adds a channel in slack for the [cri-dockerd](https://github.com/Mirantis/cri-dockerd) project
=> Add cri-dockerd slack channel

elections/steering/2023/README.md, elections/steering/documentation/README.md, elections/steering/documentation/template/README.md
Originally these two statements made it sound like the period of time needed to be "a entire weekend" and also "a day" (which cannot both be true).
In discussion among the election officers, we think we should give a reasonable amount of notice to all candidates, but we also want to leave room for election tasks to take place one or both weekend days as necessary before the announcement of results.
This PR clears up the ambiguity by changing the two previously-contradictory statements to convey the same thing. I'm changing the documentation and template file, as well as the 2023 README to match this update.
=> Disambiguate timeline for candidate notifications

contributors/devel/sig-architecture/api-conventions.md
This puts them in a more incremental order and adds a stronger convention around prefering int32 vs int64.
cc @liggitt
=> Reorganize conventions for numeric fields

committee-code-of-conduct/election.md
Till date, CoCC elections have been happening through CIVS. We want to
move to use https://elections.k8s.io/ based on Elekto for all voting
requirements. This would also improve the transparency of the process.
/cc @kubernetes/code-of-conduct-committee 
=> cocc: update election procedure

communication/contributor-comms/README.md, communication/contributor-comms/role-handbooks/[Deprecated]Comms-Events.md, sig-contributor-experience/README.md, sigs.yaml
From Comms meet it was decided to settle down the comms event role as of mid 2023.
Also fixed few links that were pointing to our old doc
=> deprecated comms event role

elections/steering/2023/voters.yaml
When we merged a PR https://github.com/kubernetes/community/pull/7417 with an empty voter list, Elekto errored out. Testing whether the voter list must contain at least one element. /cc @jberkus
=> Testing whether the voter list must be non-empty

events/events-team/content/social-content.md
Complete draft of the Social handbook for the Contributor Summit.
Includes most of the handbook/guidelines.  Does not include a full timeline of Social planning; I'll leave that for someone else to add.
/area events
/kind docs
attn: @pnbrown @nitishfy @cici37 @salaxander
=> Contributor Social handbook

elections/steering/2023/voters.yaml
Reverts kubernetes/community#7427
This test was when we were troubleshooting the problem that was eventually fixed in https://github.com/kubernetes/k8s.io/pull/5665.
=> Revert "Testing whether the voter list must be non-empty"

elections/steering/2023/election.yaml
As published on https://github.com/kubernetes/community/tree/master/elections/steering/2023#schedule the plan is to use Anywhere on Earth dates. AoE is 12 hours behind UTC, so the yaml is set up incorrectly.
This PR fixes it so the Elekto site will correctly use the published and approved AoE times for these two times instead of accidentally closing each time a day early.
Saturday, September 23 | Deadline to submit voter exception requests
Tuesday, September 26 | Election Closes at the end of the day in AoE time
=> Use correct Anywhere on Earth dates

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
This PR updates the slack user groups for the new Cluster API release v1.6 team.
=> Update CAPI v1.6 Release Team usergroup members list

elections/steering/2023/README.md, elections/steering/documentation/template/README.md
After setting up the election in https://github.com/kubernetes/community/pull/7417 I noticed this line saying "Election Begins via email ballots" and got it confirmed by sig-contribex-elections that this refers to a past process no longer in use. I'm adjusting it in this year's election as well as the template.
=> remove outdated reference to email ballots

contributors/devel/sig-testing/writing-good-e2e-tests.md
This PR fixed up the broken link about the `TimeoutContext` in the `contributors/devel/sig-testing/writing-good-e2e-tests.md` file.
=> docs: fix broken link for TimeoutContext

elections/steering/documentation/README.md, elections/steering/documentation/template/voters.yaml
Thanks to guidance from @mrbobbytables, I was able to generate the complete list of eligible voters for https://github.com/kubernetes/community/pull/7442. I am updating the instructions to reflect how I did so.
=> Clarifying how to generate the eligible voter list

github-management/OWNERS, github-management/README.md
Ref: [sig contribex thread](https://groups.google.com/g/kubernetes-sig-contribex/c/36Y3tT06FyQ/m/WYKUHcAaDAAJ) for nomination
Lazy consensus achieved.
/hold
need majority of steering committee to lgtm this change
/assign @cblecker @mrbobbytables @palnabarun @MadhavJivrajani 
Can you also +1 here?
/assign @Priyankasaggu11929  
Can you confirm that you are interested in joining the GitHub Admin Team and accept the security embargo policy?
=> github-management: add Priyanka as github admin

elections/code-of-conduct/2023/election.yaml, elections/code-of-conduct/2023/election_desc.md
The end of the 2023 CCoC election ending date was adjusted from August 15 to August 17 in this commit: https://github.com/kubernetes/community/commit/f15901e9b4d16e4686b7cb657006b9a45460613b - but that commit doesn't change the configs correctly (due to non-intuitive datetimes). This PR fixes the error.
While the text states we're using Anywhere on Earth, the end_datetime still listed in https://github.com/kubernetes/community/blob/master/elections/code-of-conduct/2023/election.yaml#L4 does not reflect August 17 "anywhere on earth" (which needs to be listed as August 18 11:59am UTC). This is a common error I address in https://github.com/kubernetes/community/pull/7433. If we don't set the correct date and time for closing, the election will accidentally automatically close a day earlier …
=> Correct date discrepancies - 2023 CoCC election

contributors/devel/development.md
I was trying to figure out how to build Kubernetes with a specific Go version and found that this wasn't documented explicitly anywhere.
This commit documents it.
/sig architecture release testing 
/assign @liggitt 
/cc @palnabarun
=> devel: add docs around go version decision in K8s build targets

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
As detailed in #7360, we have 9 maintainers and we struggle with mentioning all of them each time we have a decision to make in the cert-manager-dev channel. 
I don't know if I have entered the correct Slack usernames. I have used the GitHub usernames from the approvers list:
```bash
curl https://raw.githubusercontent.com/cert-manager/cert-manager/master/OWNERS | yq .approvers
```
To find the Slack User IDs, I had to open Slack in my browser by going at https://kubernetes.slack.com and then I opened the Dev Tools (option+cmd+i) and then select the person's name with shift+cmd+c and look for "data-message-sender":
Closes https://github.com/kubernetes/community/issues/7360.
=> Add the usergroup "cert-manager-maintainers"

communication/contributor-comms/blogging-resources/blog-guidelines.md
Update blogging approval process based on recent experiences, namely that the initial content for both `website` and `contributor-site` should be identical (and not a placeholder, as implicitly suggested).
Fixes #7478
=> Update blogging process description

sig-scheduling/CONTRIBUTING.md
These are some common guidelines that we have been using over the years in SIG Scheduling.
Fixes #
=> Add style and technical guidelines for SIG Scheduling

committee-code-of-conduct/governance/onboarding-offboarding.md
The current governance onboarding/offboarding checklist contains the statement:
> Ping project Slack admins to add/remove Slack admin privileges for incoming/outgoing members in CoCC channel(s)"
Currently, Slack does not provide granular admin permissions. Per @mrbobbytables we have not been granting Slack admin access to CoCC members. 
This PR removes the section on slack admin. If we'd like to change to grant Slack admin access, perhaps we can document that in additional places and update the sentence for clarity. 
/committee code-of-conduct
/kind docs
=> Update governance onboarding checklist for COCC to remove Slack Admin section

committee-code-of-conduct/README.md, committee-security-response/README.md, generator/committee_readme.tmpl
The committee README template doesn't have a list of Emeritus Members to generate, deviating from what we have for SIGs. This PR adds that.
I have noticed a couple of PRs [1][2] in the past updating custom sections. This needs manual intervention and can be avoided if the section is generated like SIG READMEs.
The PR intentionally doesn't add employers for emeritus members going by reasons described in https://github.com/kubernetes/community/pull/4120.
- (generator): add emeritus members section to committee template
- (committee/code-of-conduct): update generated changes
- (committee/security-response): update generated changes
[1]: https://github.com/kubernetes/community/pull/7486
[2]: https://github.com/kubernetes/community/pull/7047 …
=> generator: add generated section in committee README for emeritus members

communication/contributor-comms/CHARTER.md, communication/contributor-comms/role-handbooks/Social-Media.md
Roles like Comms Event Lead and Storytellers are deprecated
=> Fix broken links in Contributor Comms charter and role handbooks

contributors/devel/sig-architecture/api-conventions.md
Fixes https://github.com/kubernetes/autoscaler/pull/5848#discussion_r1297485877
=> Update example for conditions to use SSA go tags

elections/steering/2023/voters.yaml
Voter alerted us that we used their Slack instead of GitHub username - correcting an already-approved exception.
=> Correcting GitHub username for election exception

elections/steering/documentation/template/election-template.yaml
The dates need to be listed in UTC for this file, but they should be chosen to allow for Anywhere on Earth times, which are 12 hours behind UTC and thus need to have the visible date listed as "desired date plus one day, set to 11:59am". 
I made the correction for the 2023 Steering election in https://github.com/kubernetes/community/pull/7432/ and in this PR, I am adding comments to make it easier for people to avoid this error in the future and successfully list the date/time correctly for AoE purposes.
Note that I didn't attempt to adjust the opening date to allow for AoE, just the closing dates. Open to feedback as to whether the opening should also be adjusted; I am slightly concerned that may be a miss in terms of "voting is open" promo.
=> date examples for steering election template

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
This commit adds MadhavJivrajani and Priyankasaggu11929 to the `github-admins` slack usergroup. As a part of this, their slack IDs are also mapped in users.yaml
Further, Arnaud and Ihor are rotated out.
Ref https://github.com/kubernetes/community/pull/7327 https://github.com/kubernetes/community/pull/7464
/assign @Priyankasaggu11929 @palnabarun
=> slack-config: add Madhav and Priyanka to GH Admin slack usergroup

communication/slack-config/channels.yaml
This PR does 3 things:
- Renames kubernetes-contributors to kubernetes-new-contributors
- Creates kubernetes-maintainers
- Archives some unused channels
**Context:**
The kubernetes-contributors channel has become a place where people drop in and ask for support or requests from those completely new to OSS/K8s ignore the provided onboarding resources (join message + links to k8s.dev etc) and spam the channel or dm individuals with requests for direct 1:1 mentorship (sometimes riding the line of escalating to a CoC issue).
The channel has over 12k people in it, but our intended core audience, our k8s org members, have largely left, ignored, or muted the channel defeating its intended purpose.
To prevent this happening again to the new channel, the change will be backed up with a join …
=> Update Kubernetes core contributor slack channels

committee-code-of-conduct/election.md
TL;DR of changes:
- Adds information on setting up the election
- Adds a section on announcing the results
/hold for consensus
=> Add voting and result announcement information to cocc election process doc

contributors/devel/sig-release/cherry-picks.md
We are getting requests for cherry-picking things that actually do not fix anything. So adding that as an example of something that we should NOT allow to be cherry-picked.
Fixes #
=> Add dependency update example for cherry-picks

communication/slack-config/channels.yaml
This is a request for the [Cluster API driver for Magnum](https://github.com/vexxhost/magnum-cluster-api) project to get a channel in the Kubernetes Slack.
The project allows you to deploy Kuberentes clusters using the Cluster API for OpenStack, it enables users of OpenStack to make use of the Cluster API to get a fully integrated cluster wtih the underlying cloud using the Cloud Provider for OpenStack (CCM), Cinder CSI, Manila CSI, etc.
The project is fully open sourced, there are several contributors from different organizations and with the increased volume of PRs, we wanted to have a  space that new users can talk and ask about it, but also a space for existing developers to discuss the project.
=> chore: add magnum-cluster-api channel

sig-architecture/production-readiness.md
Follow up from 1.28 retro item to improve documentation on finding PRR reviewer
Issue link: https://github.com/kubernetes/sig-release/issues/2321
Current [Production Readiness Review](https://github.com/kubernetes/community/blob/master/sig-architecture/production-readiness.md) documentation is focused on PRR reviewers. Need documentation for KEP owner to provide an overview on how to get a PRR review. See k8s slack [discussion](https://kubernetes.slack.com/archives/C02BY55KV7E/p1692805318973359?thread_ts=1687366474.953659&cid=C02BY55KV7E).
=> Update docs for submitting kep for PRR

communication/slack-config/sig-release/usergroups.yaml, communication/slack-config/users.yaml
Part of https://github.com/kubernetes/sig-release/issues/2329
PR adds incoming 1.29 Release team lead, lead shadows, and Emiratus Advisor information to `release-team-leads` Slack Group [(kubernetes/community)](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)
- add slack ID(s) to [users.yaml](https://git.k8s.io/community/communication/slack-config/users.yaml), if they are not yet in the file
- add username(s) to [usergroups.yaml](https://git.k8s.io/community/communication/slack-config/sig-release/usergroups.yaml)
cc: @kubernetes/release-team-leads, @salaxander
=> [1.29] update RT lead, lead shadows and emiratus advisor info in slack

sigs.yaml, wg-lts/README.md
Fixes https://github.com/kubernetes/community/issues/7515
@jeremyrickard
@liggitt 
Meeting recordings link is current a playlist that was created by myself. 
- for a general one, it may look like https://bit.ly/k8s-wg-lts-videos by Kubernetes official account.
=> update wg-lts agenda link

sig-cloud-provider/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/4438
/assign @kubernetes/sig-cloud-provider 
/sig cloud-provider
=> sig-cloud-provider: add cloud-pv-admission-labeler as cloud-provider-extraction-migration subproject

communication/slack-config/channels.yaml
This PR creates `#claudie` slack channel.
Claudie is a platform for managing multi/hybrid cloud Kubernetes clusters with each nodepool in a different cloud provider or on-prem. By creating this channel we would like to unify the communication of our community in one place.
Some useful resources:
- [Claudie GH repository](https://github.com/berops/claudie)
- [Claudie documentation ](https://docs.claudie.io)
=> add claudie to channels.yaml for slack

communication/slack-config/channels.yaml
This commit adds a slack channel for Krkn project - https://github.com/redhat-chaos/krkn, a chaos testing tool for Kubernetes focusing on resiliece and performance validation under failure conditions.
This channel will act a discussion place for the Kubernetes community interested in the Krkn tooling and methodology as well Chaos and Performance Engineering.
=> Add Krkn slack channel

communication/slack-config/channels.yaml
This PR adds a Slack channel for the [Sovereign Cloud Stack (SCS)](https://scs.community).
SCS is using and standardizing existing and proven Open Source components such as e.g. Kubernetes and does extend them where required.
As our community around container technologies keeps growing, we need a place for discussion which is close to the Kubernetes community.
=> Add SCS slack channel

communication/contributor-comms/role-handbooks/Social-Media.md
Worked with @Hii-Arpit to update the social media lead handbook. Significant updates were made across the doc to remove references to the contributor-tweets repo and to "Twitter." We are also adding in new requirements for Buffer management. And we updated the lead and shadow eligibility requirements, adding clarification on the shadow role.
=> Update Social-Media lead handbook

committee-steering/governance/sig-governance.md, community-membership.md, generator/app.go, generator/sig_readme.tmpl
Broadly this PR has the following changes:
- Add Subproject Lead section to SIG governance
- Pare down the responsibilities of the Subproject Owners
- Add field in sigs.yaml to define Subproject Leads and update generator to allow for that
- Point community-membership guideline to governance doc instead of having duplicated content
Steering Votes:
/hold for comments
=> governance: add Subproject Leads as a named role in the SIG governance

elections/steering/2023/voters.yaml
Adding approved voter exceptions for Steering 2023 election.
/cc @dims @kaslin
=> Adding voter exceptions for Steering 2023 election

sig-cloud-provider/annual-report-2022.md
Here is SIG Cloud Provider's (exceedingly overdue)* annual report for 2022.
*As the SIG chairs both were new in spring 2023, we didn't realize this was missing until mid-summer. We've scoped it to 2022 where possible (although there are some numbers we couldn't ret-con).
/cc @elmiko
=> SIG Cloud Provider annual report for 2022

elections/steering/2023/README.md
I noticed that the previous date for the scheduled retro was still listed in this file. Due to Election Officer availability, we needed to adjust the retro date. The correct date went out to the k-dev email list today.
/cc @dims @kaslin
=> Correcting date for 2023 Steering election retro

contributors/guide/contributor-cheatsheet/README.md
The job view of Gubernator is now considered deprecated so I removed its reference from the file. 
I also fixed some minor grammar mistakes and typos.
Info on the discontinuation:
https://groups.google.com/a/kubernetes.io/g/dev/c/SIpSxGqu_3Q
https://groups.google.com/g/kubernetes-sig-testing/c/waDH9Tis8n4
=> Remove Gubernator reference from README.md (deprecated) and fix grammar

communication/slack-config/channels.yaml
Hi, we would like to request the Slack channel open-component-model for the open source project [Open Component Model](https://github.com/open-component-model).
OCM concentrates on modeling and deploying cloud-native software on Kubernetes, but can as well be used for any other kind of software, e.g. large legacy products deployed on-prem to VMs. It supports the whole lifecycle of software artifacts along a secure supply chain.
Useful resources can be found at https://ocm.software/
=> Request new Slack channel for the Open Component Model (OCM)

CONTRIBUTING.md, contributors/guide/pull-requests.md
The current documentation suggests that the CLA must be signed before opening a pull request.
https://github.com/kubernetes/community/blob/586e54c54a4225612e8a2e956a0e36509604b548/contributors/guide/pull-requests.md?plain=1#L60-L65
I tried to do this (submit a pull request ahead of opening a pull request) and received a response that a pull request needs to be opened before signing the CLA.  So I thought I would test out the process by opening a pull request that clarifies that opening a pull request should happen before signing the CLA.
I've also updated a couple links to point to the rendered version of the guide on the documentation website (https://www.kubernetes.dev/docs/guide/).  If it is preferable to use the link shortener or to leave the links as they were, I can change that …
=> Link to documentation site and clarify PR/CLA order

sig-api-machinery/annual-report-2020.md, sig-api-machinery/annual-report-2021.md
This PR updates the incorrect links present in the [sig-api-machinery](https://github.com/kubernetes/community/tree/master/sig-api-machinery)
=> Updated incorrect links under sig api-machinery in k/community

communication/slack-config/channels.yaml
This PR creates #educates slack channel.
The Educates project is designed to provide a platform for hosting workshops. It was primarily created to support the work of a team of developer advocates who needed to train users in using Kubernetes and show case developer tools or applications running on Kubernetes.
Although the principal deployment platform for Educates is Kubernetes, and is being used to teach users about Kubernetes, it could also be used to host training for other purposes as well. It may for example be used to help train users in web based applications, use of databases, or programming languages.
By creating this channel we would like to unify the communication of our community in one place.
Some useful resources:
[Educates GH …
=> Add educates channel

sig-autoscaling/README.md, sigs.yaml
Fixes up some of the SIG-Autoscaling subproject owner links to be more specific. Also removed scale client as an explicit subproject, as the SIG doesn't seem to have been actively involved in ownership of this for a long time now (it doesn't even have a [standalone OWNERS](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/scale) file these days.)
=> SIG-Autoscaling - Subproject Owners Cleanup

sig-multicluster/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/4440
/assign @JeremyOT
cc @qiujian16 @jnpacker @ryanzhang-oss @RainbowMango @dixudx
/hold
for lgtm from sig-multicluster lead and repo creation.
=> sig-multicluster: add cluster-inventory-api subproject

communication/slack-config/channels.yaml
Since etcd is now a SIG, it's time to change the channel name.
References can be updated after this merges.
/sig etcd
/area slack
attn: @serathius @wenjiaswe @jmhbnz
=> Change "etcd" channel to sig-etcd

sig-architecture/README.md, sig-architecture/annual-report-2020.md, sig-architecture/annual-report-2021.md, sig-architecture/api-review-process.md
Updating links from old github project (https://github.com/orgs/kubernetes/projects/13) to new github project (https://github.com/orgs/kubernetes/projects/169)
/assign @dims
=> Update API review project links

communication/slack-config/channels.yaml
This is a request to add #openstack-magnum channel in the Kubernetes Slack.
Magnum is an OpenStack project which offers APIs and drivers for deploying and managing Kubernetes as first class resources in OpenStack.
We'd like to have space to discuss with Kubernetes Cloud Provider for OpenStack, CAPI, CAPO and other Kubernetes deployment related projects.
=> chore: add openstack-magnum channel

github-management/kubernetes-repositories.md
The information is dated, updating to what we do now. Also taking specific named people out of the loop as we now have a process in place at the foundation level.
=> Document latest process(es) for licenses

sig-auth/README.md, sigs.yaml
Updating sig-auth to rotate @mikedanese out of TL and @enj in.
Many thanks, Mike! Congrats, Mo!
https://groups.google.com/a/kubernetes.io/g/dev/c/YbcO8tEk82U
/hold for acks
/sig auth
/assign @deads2k @ritazh @mikedanese @enj
=> Update sig-auth TL

sig-cluster-lifecycle/README.md, sigs.yaml
As the [logical-cluster repository README](https://github.com/kubernetes-sigs/logical-cluster) indicates, this project was primary created for serving in CAPI usage. Later it can become used by other subprojects like kOps, or cloud providers.
However, having it as a subproject creates extra work for us that is not necessary - e.g. subproject yearly reports. After discussion in the SIG meeting of 31.10.2023, we have agreed to move it from a subproject to a "associated repository" of the CAPI subproject.
A similar case for this can be seen under kubeadm - e.g. see k/system-validators.
NONE
=> sig-cluster-lifecycle: move logical-cluster to a subproject repo

contributors/devel/sig-architecture/api-conventions.md
No issue created yet about the problem. The `StatusTooManyRequests` had two spelling mistakes that have been addressed with the current PR.
=> Fix typo and grammar in StatusTooManyRequests

communication/slack-config/channels.yaml
This PR is intended to update the AKS-related Slack channels to more accurately reflect reality and be more consistent with other cloud providers.
Currently, the two AKS-specific channels on Kubernetes Slack are legacy channels intended for discussion of a [now-archived tool for self-managed non-AKS Kubernetes clusters on Azure](https://github.com/Azure/aks-engine): #aks-engine-users, #aks-engine-dev.
This is a source of ongoing confusion. What ends up happening now is that people looking for Azure Kubernetes Service discussion bring their questions to those legacy channels and often don't get the help they're looking for, since the AKS Engine tool in question is EOL.
I am hoping that by renaming #aks-engine-users to ~#aks~ #azure-aks (edit: see note) (and retiring #aks-engine-dev), we …
=> Clarify AKS-related channels on K8s Slack

github-management/README.md
This PR adds @helayoty @jasonbraganza and @ydFu as new New Membership Coordinators (NMC). :tada: 
They've been handling the New org membership requests for a while now, and @jasonbraganza also documented the entire process, which is a valuable addition to our overall NMC onboarding process!
/assign @kubernetes/owners
=> add helayoty, jasonbraganza, ydFu as New Membership Coordinators

contributors/guide/github-workflow.md
`--force-with-lease` is less dangerous:
from the docs:
> --force-with-lease alone, without specifying the details, will protect all remote refs that are going to be updated 
> by requiring their current value to be the same.
=> use `--force-with-lease`

sig-docs/localization-subproject/README.md
This PR is to add docs around the localization subproject. More context can be found in this issue: https://github.com/kubernetes/website/issues/37200
To Do:
* Reach out to localization teams for review
* Make sure all leaders are aware they are listed on this document and are still acting in this role
* This content updates/improves on the subproject information on https://github.com/kubernetes/community/tree/master/sig-docs, so we should consider some cleanup work to make sure we aren't duplicating things
**Which issue(s) this PR fixes**: 
Fixes # https://github.com/kubernetes/website/issues/37200
=> Add localization subproject docs

OWNERS_ALIASES, sig-windows/README.md, sigs.yaml
Adding Amim Knabben as SIG-Windows TL and moving Jay Vyas to Emeritus lead 
Fixes #7614
=> Changing Jay Vays to Amim Knabben as SIG-Windows tech lead

sig-architecture/production-readiness.md
In the Nov 29th PRR Office Hours meeting, it was discussed that shadows should include links to review comments when opening a PR to aid in reviewing against the criteria for becoming an approver. 
This PR updates the wording a little to clarify that. 
/kind cleanup
=> Update guidance for becoming an approver

sig-release/README.md, sigs.yaml
Part of https://github.com/kubernetes/org/issues/4170
/assign @kubernetes/sig-release-leads
=> sig-release: add release-actions repo under release-engineering subproject

contributors/devel/sig-architecture/conformance-tests.md
It's not true that running conformance test is non-privileged and does not require cluster admin permissions.
Fixes https://github.com/kubernetes/kubernetes/issues/122220
=> Fix outdated conformance test requirement

events/events-team/content/meet-and-greet.md
Updating the Contributor Summit events handbook with renaming of the SIG Meet & Greet to Meet the Kubernetes Contributor Community (MKCC) and added notes and updates from this past run at KubeCon/CloudNativeCon NA 2023.
/assign @nimbinatus
=> Update events handbook for MKCC after NA 2023 event

hack/.spelling_failures, hack/verify-spelling.sh
This PR updates the spelling failures check to exempt any localized version of the contributor cheatsheet from spelling check failures.
=> Update spelling failures check for contributor cheatsheet

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
This PR updates the slack user groups for the new Cluster API release v1.7 team.
=> Update capi v1.7 release team members

communication/slack-config/channels.yaml
[Myks](https://github.com/mykso/myks) is an automation tool and configuration framework. It helps to manage configuration for many Kubernetes clusters by generating a source of truth from the provided configuration. It heavily relies on some of the Carvel tools (ytt, vendir) and helm, and provides integration with ArgoCD.
At the moment, it is used in production in a couple of companies, but it is still in active development. We have a channel in one of the companies' Slack workspace, but it is not public. We want to work towards onboarding more users and contributors. We think that Kubernetes Slack is the most appropriate place for that.
I am one of the maintainers of the project, and I am happy to answer any questions.
=> Add #myks Slack channel

communication/best-practices.md, contributors/chairs-and-techleads/process-workflow-guide.md, contributors/guide/contributor-cheatsheet/README-de.md, contributors/guide/contributor-cheatsheet/README-fr.md, contributors/guide/contributor-cheatsheet/README-hi.md, contributors/guide/contributor-cheatsheet/README-id.md, contributors/guide/contributor-cheatsheet/README-it.md, contributors/guide/contributor-cheatsheet/README-ja.md, contributors/guide/contributor-cheatsheet/README-ko.md, contributors/guide/contributor-cheatsheet/README-pt.md, contributors/guide/contributor-cheatsheet/README-uk.md, contributors/guide/contributor-cheatsheet/README-zh.md, contributors/guide/issue-triage.md
Gubernator is deprecated since June, 2023
Info on the discontinuation:
https://groups.google.com/a/kubernetes.io/g/dev/c/SIpSxGqu_3Q
Fixes #7635
=> Remove references to Gubernator in Contributors and Comms docs

contributors/devel/sig-testing/flaky-tests.md
Fixes https://github.com/kubernetes/kubernetes/issues/95528
```
([TODO](https://github.com/kubernetes/kubernetes/issues/95528): Move these instructions to the issue template.)
```
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/flaking-test.yaml is updated by https://github.com/kubernetes/kubernetes/pull/104468.
In https://github.com/kubernetes/kubernetes/issues/new?assignees=&labels=kind%2Fflake&projects=&template=flaking-test.yaml, we can see the link of flaking test now.
Or do we need to add more instructions there? All that we may miss is about how to check multi job failure and multi test failure with similar reason, but this is already in the first link.
=> remove todo of adding instructions to flaking test issue template

sig-release/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/4550
cc: @kubernetes/sig-release-leads
=> sig-release: add obscli repo under release-engineering subproject

sig-docs/blog-subproject/README.md
**Which issue(s) this PR fixes**: _none_
Per https://github.com/kubernetes/website/pull/44607, add Gaurav Padam to the blog team.
=> Add Gaurav Padam as editor for blog

sig-docs/offboarding.md
This is a follow-up PR raised against [tracking issue](https://github.com/kubernetes/website/issues/44292).
In addition to manually removing the exiting co-chair from Google Analytics, one of the new chairs needs to be added in their place to facilitate refreshing and synching of the dashboard.
Failure to do so will result in breaking the dashboard since access doesn't automatically get assigned.
=> Clarify Google Analytics offboarding and addition

hack/verify-generated-docs.sh
Fixes the following non-blocking error message in the verify job:
```
ls: cannot access '/home/prow/go/src/github.com/kubernetes/community/ug-*/README.md': No such file or directory
```
=> Remove reference to user groups in verify script

communication/slack-config/channels.yaml
Adding the #hydrophone slack channel for https://github.com/kubernetes-sigs/hydrophone which is part of sig-testing.
=> Added hydrophone slack channel

sig-node/archive/README.md, sig-node/archive/meeting-notes-2021.md, sig-node/archive/meeting-notes-2022.md, sig-node/archive/meeting-notes-2023.md
Archiving meeting agenda for historical availability, and to clean up the agenda doc for performance. I'll delete the old entries from https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit once this merges.
Generated using the [Docs to Markdown extension](https://workspace.google.com/marketplace/app/docs_to_markdown/700168918607)
/assign @SergeyKanzhelev @mrunalp
=> Archive past years of SIG-node agenda

communication/slack-config/channels.yaml
For discussions about bringing RISC-V support
to Kubernetes.
No SIG at this point.
=> Add riscv to Slack channels

sig-cluster-lifecycle/README.md, sigs.yaml
This doc updates the link to the CAPI office hours agenda doc to use the new alias (the old one no longer works).
Fixes #
=> Cluster API: update office hours agenda document link

contributors/devel/development.md
This fixes a minor URL mix up on the `development.md` doc.
=> fix: minor url fix

communication/contributor-comms/OWNERS, communication/contributor-comms/README.md
As discussed in the Contributor Comms Meeting on February 2nd 2024 add mfahlandt as Tech Lead for Sig-Contribex-Comms.
Thank you @SD-13 for your Service to the community.
@SD-13 is being moved to Emeritus.
=> Add mfahlandt as Comms Tech Lead, move SD-13 to Emeritus

communication/slack-config/channels.yaml
This adds a Slack channel for the contributors of https://github.com/kubernetes-sigs/blixt, and also a channel for the SIG Network KNI KEP which resolves #7703.
=> Add some slack channels for SIG Network

sig-architecture/README.md, sigs.yaml
Towards https://github.com/kubernetes/org/issues/4705
/assign @kubernetes/sig-architecture-leads 
for LGTM
/hold
=> sig-architecture: add apisnoop subproject

communication/slack-config/channels.yaml
During KCD Brazil / Sao Paulo, we have realized the need to gather more contributors from Brazil together on Kubernetes and subprojects.
While we have a channel for docs-pt contributions, the idea is that as the "in-dev" and "jp-dev" we have a more generic channels where Brazilians can join, understand process contributions, some maintainers to announce need for help or some workshops, etc.
=> Create the Brazilian dev channels

community-membership.md
As per https://datatracker.ietf.org/doc/html/rfc2119 , we can replace `may` by `should`  on the new contributors requirements to avoid misenterpretations.  The spirit of the requirements is to get people that contributes to the project across all areas, if only attend meetings is enough, per example, can be easily gamed.
=> Update community-membership.md s/may/should/

sig-scalability/slos/dns_programming_latency.md
Update the SLI to reflect the DNS latency expectactions for headless services, that have a high impact on on AI/ML workloads that make a have use of headless services  and DNS https://github.com/kubeflow/mpi-operator/issues/611#issuecomment-1875645627
=> update DNS programming latency SLI

OWNERS_ALIASES, sig-api-machinery/README.md, sigs.yaml
Stefan has spent eight years working in kubernetes, the majority of those in the apimachinery area developing key infrastructure like CRDs and the less glamorous code like code generators.  His knowledge of the apiserver internals, type system, schemes, generators, clients, controller libraries, binary helper libraries, and all aspects of the apimachinery stack are very deep.
/assign @jpbetz @fedebongio @sttts
=> Add Stefan as tech lead for sig-api-machinery

sig-etcd/README.md, sigs.yaml
Fixed active projects' OWNER link only, mainly by changing file name from MAINTAINERS to OWNERS and updating branch name from master to main
Notice that for a repo that doesn't have a MAINTAINER or OWNER file, the link is left as-is, the `dbtester` repo.
References:
- https://github.com/etcd-io/bbolt/pull/578
=> Fix broken OWNER links in sig-etcd README

community-membership.md
With this:
- we ensure that they show up in devstats
- with at least the affiliation when they apply for org membership (instead of the gitdm tool guessing!)
- with at least one working email id if we ever needed to contact them
Bonus, we don't have to store that info ourselves! We should also prompt folks who have no entry there to add one with a deadline of some sort once now and once before the next pruning?
=> Add a new requirement to org membership - updated gitdm!

contributors/devel/sig-instrumentation/metric-instrumentation.md, contributors/devel/sig-instrumentation/trace-instrumentation.md
Part of https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/647-apiserver-tracing
This meets the following KEP requirements:
* Publish guidelines for kubernetes components on when and how to add tracing to a component.
* Define and document stability guarantees for trace instrumentation.
@kubernetes/sig-instrumentation-leads
=> Add tracing instrumentation documentation

contributors/devel/development.md
Table needed an update, table included Go versions used up to early 1.25 release.
Fixes #
=> Update required Go versions for different versions of Kubernetes.

sig-cluster-lifecycle/README.md, sigs.yaml
Signed-off-by: Stefan Büringer buringerst@vmware.com
This PR updates the links to the CAPV meeting notes (we recently moved them to the community gdrive)
=> Update CAPV meeting notes links

communication/slack-config/channels.yaml
These slack channels were related to various [AppsCode](https://appscode.com) projects. We stopped using these channels 2-3 years ago and moved over to our own discord channels. Now, we would like to archive them to avoid confusion among the users. Your help in this matter is much appreciated.
Fixes #
=> slack-config: Archive appscode slack channels

contributors/devel/sig-testing/e2e-tests.md
This PR adds a link to `e2e_node test` in `e2e test` docs.
Currently, there is no proper information about `e2e test` and `e2e_node test`. Each use cases, difference, etc... so, developers dont't know how to do e2e test fo each k8s component.
This PR also adds such information.
Fixes #
=> Add link to e2e_node test docs

communication/slack-config/channels.yaml
This PR adds the `terraform-kops` slack channel.
It will be a place for maintainers of the [github.com/terraform-kops/terraform-provider-kops](https://github.com/terraform-kops/terraform-provider-kops) project to discuss the project, which is related to Kubernetes sub-project [github.com/kubernetes/kops](https://github.com/kubernetes/kops)
cc @eddycharly
=> Add terraform-kops slack channel.

sig-network/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/4856
=> sig-network: add kube-network-policies under network-policy subproject

contributors/devel/sig-architecture/feature-gates.md
Follow up from SIG Architecture meeting on Apr 18th 2024
/assign @deads2k @johnbelamaric @thockin @liggitt @jpbetz
=> Guidance for skipping Alpha for feature gated changes

sig-storage/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/4875
=> sig-storage: remove container-object-storage-interface-csi-adapter for archival

sig-storage/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/4874
=> sig-storage: add external-snapshot-metadata as new sub-project

sig-release/annual-report-2023.md
This PR updates the 2023 annual report for SIG Release
Fixes #7778
=> update SIG release annual report

contributors/devel/sig-architecture/api_changes.md, contributors/devel/sig-architecture/feature-gates.md
Add more to feature-gates.md about patterns for feature implementors.  This correlates to the text in api_changes.md but with less specific code snippets.
xref https://github.com/kubernetes/kubernetes/pull/123385#discussion_r1508318944
/cc @liggitt
=> Document feature gates more

sig-scheduling/README.md, sigs.yaml
Based on discussions with @alculquicondor, this PR adds @alculquicondor and @tenzen-y to Kueue leads.
=> Kueue: Add Aldo and Yuki to leads roles

sig-etcd/annual-report-2023.md
=> Complete sig-etcd annual report for 2023

contributors/devel/README.md
PR fixes broken links in contributors/develop/README.md
Instrumentation files were renamed in commit `76c29a326d74a60bb219c4c323993ace49bf9816`. This broke the links in README.md.
=> fixed broken links in contributors readme

events/events-team/registration/README.md
This PR updates the Registration Team handbook:
- removes the 2 paths of the registration form (new and active contributor), we no longer do a new contributor path
- updates the approval process, updates the commands to generate the org members list to include etcd, gives an alternate command to generate the list
- add new sections for exceptions, dietary requirements, and celebration guests
- removed content about two tracks: Active Contributor and New
Contributor Track. We no longer have two tracks
=> Update the event's registration team's README.md

events/events-team/marketing/README.md
This PR updates the Communications Team handbook:
- Add the renamed role name to avoid confusion for future leads/shadows
- Adds explanatory sections for the website, Slack
- Updates social media names and links (with the main k8s X account currently transitioning to ContribEx)
- Adds link to prior GDrive for comms templates
=> Update comms handbook for contributor summit

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
I created the group `@cert-manager-maintainers` a while back in #7368. Today, @ThatsMrTalbot was added as a maintainer after a vote (https://github.com/cert-manager/community/pull/23) and I'd like to add Adam to the Slack handle `@cert-manager-maintainers`.
=> Add ThatsMrTalbot to the cert-manager-maintainers group on Slack

contributors/guide/contributor-cheatsheet/README.md, contributors/guide/pull-requests.md
This commit adds more information about the label
`tide/merge-method-squash` and shows what the commit
message ends up looking like if the label is used on
multiple commits, especially if the PR contains fixup
commits like "address reviews".
Adding this documentation to better illustrate the
effects of using this label as opposed to squashing
by hand and preserve good commit message practices.
Some slack context [here](https://kubernetes.slack.com/archives/C5P3FE08M/p1635345481012900)
=> guide: Add more docs around tide/merge-method-squash

sig-cli/README.md, sigs.yaml
This PR updates the link to the sig-cli agenda to a new one owned by the org instead of an individual.
ref: https://github.com/kubernetes/community/issues/7903
/kind cleanup
/sig cli
=> Update sig-cli agenda

communication/calendar-guidelines.md
Tested on Sidecar WG meeting from https://calendar.google.com/calendar/embed?src=c68df4a61d14122e8e81eb42309f6cca63eb1b7b443384eebc803e6832dbe0b6%40group.calendar.google.com&ctz=America%2FLos_Angeles
It wasn't in community calendar before the invite and appeared there after
=> Add a note on how to appear in community calendar

sig-storage/annual-report-2023.md
Fixes #7782 
cc @saad-ali @msau42 @jsafrane
=> New update to SIG Storage 2023 report

OWNERS_ALIASES, sig-cloud-provider/README.md, sigs.yaml
Updating sigs.yaml and associated generated files for https://github.com/kubernetes/community/issues/7865.
/sig cloud-provider
=> SIG Cloud Provider update

sig-scalability/README.md, sigs.yaml
This PR fixes the broken links to `GitHub-Teams` in the `sig-scalability` README file:
1. Remove non-existing links
2. Add two new links
Fixes https://github.com/kubernetes/community/issues/7869
=> Fix broken links in sig-scalability README

events/events-team/registration/README.md
This PR updates the contributor summit registration team handbook with a sentence on adding the lead and shadows to the summit-team@kubernetes.io email group
/cc @savitharaghunathan
=> Update registration team handbook about the summit-team email group

OWNERS_ALIASES, communication/slack-config/sig-release/OWNERS, contributors/devel/sig-release/OWNERS, sig-release/OWNERS
Part of https://github.com/kubernetes/sig-release/issues/2516.
Grants:
- Reviewer:
- /sig-release
- Approver:
- /communication/slack-config/sig-release
- /contributors/devel/sig-release
Context: There are some existing PRs e.g., https://github.com/kubernetes/community/pull/7919, https://github.com/kubernetes/community/pull/7600 that could be reviewed/approved by subproject leads, now that the role exists.
cc: @kubernetes/sig-release-leads @gracenng @katcosgrove @xmudrii
=> sig-release: Add subproject leads as reviewers/approvers for subdirs

sig-release/meeting-notes-archive/2023.md
Fixes https://github.com/kubernetes/sig-release/issues/2521
/assign @xmudrii
=> sig-release: Add 2023 meeting notes archive

contributors/guide/contributor-cheatsheet/README-de.md, contributors/guide/contributor-cheatsheet/README-es.md, contributors/guide/contributor-cheatsheet/README-fr.md, contributors/guide/contributor-cheatsheet/README-hi.md, contributors/guide/contributor-cheatsheet/README-id.md, contributors/guide/contributor-cheatsheet/README-it.md, contributors/guide/contributor-cheatsheet/README-ja.md, contributors/guide/contributor-cheatsheet/README-ko.md, contributors/guide/contributor-cheatsheet/README-pt.md, contributors/guide/contributor-cheatsheet/README-uk.md, contributors/guide/contributor-cheatsheet/README-zh.md, contributors/guide/contributor-cheatsheet/README.md
- fix broken links in Contributor Cheatsheet (and localized)
- before: http://git.k8s.io/test-infra/prow/cmd/tide/pr-authors.md
- after: https://sigs.k8s.io/prow/site/content/en/docs/components/core/tide/pr-authors.md
=> docs: fix 404 errors in Contributor Cheatsheet

communication/meeting-notes-archive/201902-201911_Community_Meeting_Notes.md, communication/meeting-notes-archive/201911-202010_Community_Meeting_Notes.md, communication/slack-guidelines.md, contributors/chairs-and-techleads/technical-lead.md, contributors/devel/sig-architecture/staging.md, contributors/devel/sig-release/cherry-picks.md, contributors/guide/first-contribution.md, elections/steering/2020/bobkillen.md, elections/steering/2022/candidate-mrbobbytables.md, events/events-team/registration/README.md, sig-auth/CONTRIBUTING.md, sig-cli/CONTRIBUTING.md, sig-cloud-provider/CONTRIBUTING.md, sig-cluster-lifecycle/CONTRIBUTING.md, sig-multicluster/annual-report-2020.md, sig-release/meeting-notes-archive/2019.md, sig-scalability/CONTRIBUTING.md, sig-ui/CONTRIBUTING.md
This PR is a follow-up to #7884
- Changed the links to 
- "sigs.k8s.io" to use `https://sigs.k8s.io/...` instead of `http://sigs.k8s.io/...`
- "git.k8s.io" to use `https://git.k8s.io/...` instead of `http://git.k8s.io/...`
ref. https://github.com/kubernetes/community/pull/7884#discussion_r1631501117
> all `sigs.k8s.io` links should be using `https://sigs.k8s.io/...` (`https://` instead of `http://`)
=> docs: use "https" instead of "http"

elections/OWNERS, elections/README.md
Updates the Election Subproject Members for 2024.
This is a prerequisite to choosing the Election Officers for 2024.
Please approve,
@Priyankasaggu11929 @MadhavJivrajani @kaslin @palnabarun
=> Annual change of membership for Election Subproject

events/events-team/comms/README.md
KCSNA 2024 comms lead. Changing title of role from marketing to comms. Updating list of past resources for reference.
=> Changing marketing to comms and updating resources

contributors/devel/sig-testing/e2e-tests.md
This explains how to use --filter-label (possible since Kubernetes 1.29) and clarifies the usage of feature gate labels.
The intent is that adding tests with only a `FeatureGate` label is sufficient. Before we allow such tests, we have to
- can be done with regexp negative lookahead workaround or
- a Ginkgo enhancement (https://kubernetes.slack.com/archives/C09QZ4DQB/p1714668500446099, available in master) (**actual solution**)
That is because the "traditional" `SKIP=\[Features:.+\]` will no longer match tests which have `[FeatureGate:Foo] [Alpha]`, as explained in https://github.com/kubernetes/kubernetes/pull/124350.
=> e2e-tests.md: update description of labels

go.mod, go.sum
- Update go version and specify go patch version to clarify forwards compatibility
[Go 1.21 Release Notes](https://tip.golang.org/doc/go1.21)
> To improve forwards compatibility, Go 1.21 now reads the go line in a go.work or go.mod file as a strict minimum requirement: go 1.21.0 means that the workspace or module cannot be used with Go 1.20 or with Go 1.21rc1. This allows projects that depend on fixes made in later versions of Go to ensure that they are not used with earlier versions. It also gives better error reporting for projects that make use of new Go features: when the problem is that a newer Go version is needed, that problem is reported clearly, instead of attempting to build the code and printing errors about unresolved imports or syntax errors.
=> chore: Update go version

OWNERS_ALIASES, sig-docs/README.md, sigs.yaml
Add Kat Cosgrove as SIG Docs Tech Lead to sigs.yaml and k/community/sig-docs/README.md
Ran `make generate` which updated OWNERS_ALIASES 
/assign @MadhavJivrajani 
/cc @natalisucks @divya-mohan0209
=> Add Kat Cosgrove as SIG Docs Tech Lead

communication/slack-config/channels.yaml
This adds a Slack channel for the IONOS Cloud cluster-api provider: https://github.com/ionos-cloud/cluster-api-provider-ionoscloud.
=> Add cluster-api-ionoscloud Slack channel

sig-security/README.md, sigs.yaml
Ref https://github.com/kubernetes/org/issues/4873
/hold
=> Add cve-feed-osv project

communication/slack-config/usergroups.yaml
This is a trivial change to test https://github.com/kubernetes/test-infra/pull/32928
=> add a period to the end of youtube-admins and zoom-admins descriptions

elections/steering/2024/OWNERS, elections/steering/2024/README.md, elections/steering/README.md
This PR contains the Election Subproject's choices for Election Officer for 2024.  They are:
Election Officers:
- Bridget Kromhout
- Christoph Blecker
- Priyanka Saggu
Alternates:
- Rey Lejano
- Joseph Sandoval
Other aspects of the 2024 Election README are not updated (deliberately) and I'll still need to update things in Org.  But first Steering needs to approve the Officers.
**This PR must be approved by a majority of Steering Committee members**
Attn:
@kubernetes/steering-committee 
@salaxander @parispittman @fsmunoz
=> Select Election Officers for 2024 Elections

communication/slack-config/sig-network/config.yaml, sig-network/README.md, sigs.yaml
This is a companion issue to https://github.com/kubernetes/org/issues/5054 which archives the [KPNG](https://github.com/kubernetes-sigs/kpng) sub-project.
=> chore: archive kpng sub-project for SIG Network

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
Irbe stepped down and joined the cert-manager Emeriti Maintainers.
Ref: https://github.com/cert-manager/community/pull/31
=> Irbe moved to emeritus cert-manager maintainer

OWNERS, communication/OWNERS, elections/steering/OWNERS
Jaice's current workload does not permit him to contribute currently, and it's not clear when it will.  As such, moving him to emeritus_approvers in all OWNERs files so that he won't be assigned review.
=> Move Jaice to emeritus_approvers

communication/slack-config/restrictions.yaml, communication/slack-config/sig-testing/usergroups.yaml
/kind cleanup
/sig testing
Second part of https://github.com/kubernetes/test-infra/pull/33083
/hold
=> remove deprecated sig testing groups

communication/slack-config/channels.yaml
Not that the WG Etcd Operator is official, it needs a slack channel.
/sig etcd
/sig cluster-lifecycle
/area slack
=> Add #wg-etcd-operator

communication/slack-config/users.yaml
I noticed in https://github.com/kubernetes/community/pull/7985#issuecomment-2248438016 that we are failing to update some user groups.
By inspecting the logs at https://prow.k8s.io/?job=post-community-tempelis-apply we can see which groups
From there we check the list of members in the group and verify the UIDs for each.
cc @AdheipSingh @camilamacedo86
=> fix tempelis config

communication/slack-config/usergroups.yaml
Hopefully this stops tempelis from attempting to mutate this group every time any changes merge.
previously: https://github.com/kubernetes/community/pull/7990#issuecomment-2248731582
=> remove newline from PSC description

communication/slack-config/channels.yaml
[kubecfg](https://github.com/kubecfg/kubecfg) is a tool for managing Kubernetes resources as code. `kubecfg` allows you to express the patterns across your infrastructure and reuse these powerful "templates" across many services, and then manage those templates as files in version control.
Helps https://github.com/kubecfg/kubecfg/issues/429
---
* chore: add channel for kubecfg (f2c3c727)
https://github.com/kubecfg/kubecfg
=> chore: add channel for kubecfg

elections/steering/documentation/README.md
Add some missing instructions about setting up the slack channel and email address per comments by @bridgetkromhout and @cblecker.
=> Update slack/email process per retro item.

communication/contributor-comms/blogging-resources/blogging-shadow-guide.md
Initial version of the Contribex Comms blogging shadowing guide.
Fixes #7875
=> Add contribex-comms blog shadow guide

elections/steering/2024/README.md, elections/steering/2024/election.yaml, elections/steering/2024/election_desc.md, elections/steering/2024/nomination-template.md, elections/steering/2024/voters.yaml, elections/steering/README.md, elections/steering/documentation/README.md, elections/steering/documentation/template/README.md, elections/steering/documentation/template/nomination-template.md
This PR sets up the 2024 Steering Election, with Election Officers of @Priyankasaggu11929, @cblecker, and @bridgetkromhout. 
We're seeking approval from Steering for this timeline as well as approval for the voter eligibility criteria (which have not changed from last year).
Notes:
- I also corrected issues with the templates and fixed broken links in the docs.
- We are avoiding requiring action during holidays such as Labor Day (US), Rosh Hashanah, and Yom Kippur.
- I am creating the voters.yaml with an empty list to be populated when the election opens, as was recommended last year.
Holding for the majority of Steering to approve.
/hold
=> 2024 Steering Election setup

elections/steering/2024/voters.yaml
Follow up on https://github.com/kubernetes/community/pull/8001
Minor correction in voters.yaml for proper alpha-sorting
/assign @bridgetkromhout @cblecker 
/hold
(to remove after reviews are completed)
=> [steering elections 2024] alpha-sort correction in voters.yaml

sig-node/charter.md
https://github.com/kubernetes/community/blob/32d76b26594c5010a2a3ab49576dc62c04d9b4a6/sig-node/charter.md?plain=1#L72
```
[perf dashboard]: http://node-perf-dash.k8s.io/#/builds
```
http://node-perf-dash.k8s.io/#/builds this is not available.
Other node related performance dashboard can be found in https://perf-dash.k8s.io/#/?jobname=containerd-node-throughput&metriccategoryname=E2E&metricname=PodStartup&Metric=run_to_watch.
=> sig-node: remove unavailable node-perf-dash.k8s.io

communication/slack-config/channels.yaml
This adds #hmc to the Kubernetes Slack Channels
**Purpose:**
We at Mirantis are developing a new Hybrid Multi Cloud platform called (HMC) which is leveraging CAPI under the hood. It is developed fully in the open under https://github.com/Mirantis/hmc (currently private, will be public in 2-3 days) in the Apache 2 License. We have already 5+ of our customers that committed to develop and design HMC with us.
For this we are looking for a Slack Channel to communicate with our customers, to prevent that we need to use company slack channels, plus allow the whole k8s community to be part of the discussions (as the project management will also happen in Github fully public)
Happy to provide additional information if needed.
=> add hmc to slack channel

elections/steering/2024/voters.yaml
PR adds voters from approved exception request, as of Aug 21, 2024.
/assign @bridgetkromhout @cblecker
/hold
for review/approval from Election Officers.
=> [steering 2024] add voters from approved exception request - aug 21

contributors/guide/owners.md
Warning message about filters on OWNERS files not working for the approve plugin links to <https://github.com/kubernetes/test-infra/issues/7690>, which appears to be resolved.
=> docs: remove outdated warning

elections/steering/2024/voters.yaml
PR adds voters from approved exception request, as of Aug 26, 2024.
/assign @bridgetkromhout @cblecker
/hold
for review/approval from Election Officers.
=> [steering 2024] add voters from approved exception request - aug 26

contributors/guide/README.md
This PR aims to update the sample link in the [#sign-the-cla](https://www.kubernetes.dev/docs/guide/#sign-the-cla) section.
The current example does not follow the repository’s template, making it a little inconvenient for review. Therefore, I want to update it to adhere to the template.
=> Modify the sample link in #sign-the-cla section

elections/steering/2024/voters.yaml
PR adds following voters from approved exception requests, as of Aug 30, 2024.
- @ehashman
---
/assign @bridgetkromhout @cblecker
/hold
for review/approval from Election Officers.
=> [steering 2024] add voters from approved exception request - aug 30

communication/slack-config/sig-release/usergroups.yaml, communication/slack-config/users.yaml
Adds the release team to Slack groups for v1.32 cycle.
xref: 
- https://github.com/kubernetes/community/pull/7919
- https://github.com/kubernetes/community/pull/7682
cc: @kubernetes/sig-release-leads @Priyankasaggu11929 @katcosgrove @gracenng
=> 1.32 release team slack groups

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
Adds erikgb to the cert-manager-maintainers usergroup. He is a new cert-manager maintainer (see https://github.com/cert-manager/community/pull/32).
=> Add new cert-manager maintainer erikgb to the slack usergroup

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
New CAPI v1.9 RT members announced here: https://kubernetes.slack.com/archives/C8TSNPY4T/p1723216277709389
This PR removes old and adds new v1.9 RT members from/to the list in alphabetical order
=> Update CAPI v1.9 release team members

communication/slack-config/channels.yaml
This creates a channel for the [SimKube](https://github.com/acrlabs/simkube) project, which is a Kubernetes simulation environment.  SimKube recently announced its [1.0 release](https://blog.appliedcomputing.io/p/announcing-simkube-v10) and I'd like to provide a place for users to come ask questions/report bugs/discuss issues.  
SimKube is an open-source, MIT-licensed project by [Applied Computing Research Labs](https://appliedcomputing.io).
=> Add SimKube to Slack Channels

communication/slack-config/channels.yaml
Adds a #kubearchive channel to the Kubernetes slack 
**Project URL:** [https://github.com/kubearchive/kubearchive](https://github.com/kubearchive/kubearchive)
**Purpose:**
KubeArchive is an open source project, licensed under Apache-2.0, that allows kubernetes users to specify resource(s) on their cluster that they would like to be archive (written to a Postgres database and the object deleted from the cluster) when objects of these resource(s) reach a user specified state and provide an API and CLI for querying and retreiving the archived objects. Think Tekton Results (the inspiration for KubeArchive), but more flexible so that it can operate on everything from Tekton PipelineRuns, to plain old Jobs, to any CR you create yourself. KubeArchive uses Knative Eventing under the hood to find …
=> add kubearchive slack channel

wg-serving/README.md
Just added these in custom content in the markdown file directly for now for easy access.
=> wg-serving: add links to sponsored subprojects

sig-network/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/5121
=> sig-network: add gwctl under gateway-api subproject

sig-cluster-lifecycle/README.md, sigs.yaml
Updates the CAPO office hours agenda link to the redirect we added in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2125
=> cluster-api-provider-openstack: Update agenda URL

elections/steering/2024/ballots.csv, elections/steering/2024/results.md, elections/steering/2024/voters.yaml
This PR adds the formal results of the 2024 Kubernetes Steering Committee election.
=> Add election results of 2024 Steering Committee election

contributors/guide/github-workflow.md
Updates the contributor guide to reflect the shift to Go Modules as the default build system from Go 1.13 onwards. Contributors are no longer required to clone the repository within their GOPATH, simplifying the setup process.
Fixes #
=> Simplify contributor setup by removing GOPATH dependency

communication/slack-config/channels.yaml
Adds kubectl-nvim channel intended for [kubectl.nvim](https://github.com/Ramilito/kubectl.nvim)
=> REQUEST: New Slack kubectl.nvim to the channel.yaml

contributors/devel/sig-node/e2e-node-tests.md
/kind feature
/kind doc
doc: Support specifying a custom network parameter when running e2e-node-tests with the remote option.
*Automatically closes linked issue when PR is merged.
Usage: `Fixes https://github.com/kubernetes/community/issues/8089  .
=> doc(test-e2e): support custom network and subnet on remote e2e mode

contributors/devel/sig-node/e2e-node-tests.md
/kind bug
the command specified on "List the available test images using gcloud." is outdated since the LIST_IMAGES option was [removed ](https://github.com/kubernetes/kubernetes/pull/109606/files  ) from hack/make-rules/test-e2e-node.sh file.  
*Automatically closes linked issue when PR is merged.
Usage: `Fixes https://github.com/kubernetes/community/issues/8083  .
=> doc(e2e-node-tests): fix gcloud list images cmd

communication/slack-config/channels.yaml
Archiving three disused channels.
`#ncw-staff` was for the old New Contributor Workshop and hasn't been used since 2020
`wg-naming` was for the Naming Working Group which was dissolved in 2021
`talk-proposals` never really fulfilled its purpose, and has been inactive since 2019 (tag @castrojo)
/area slack-management
=> Archive three disused channels.

communication/slack-config/channels.yaml
Currently there are 2 channels for the Zarf project. We've decided to archive #zarf-dev in favor of the #zarf channel
=> archive zarf-dev slack channel

sig-network/README.md, sigs.yaml
1. Add more structure to what it means to being a sub-project lead.
2. Add sub project leads and owner repos to existing areas
=> SIG-Network: Add Subproject Leads responsibilities

events/events-team/operations/mainroom-room-proctor.md, events/events-team/operations/presentation-session-room-proctor.md, events/events-team/operations/sig-meeting-room-proctor.md, events/events-team/operations/unconference-room-proctor.md
This PR adds KCS room proctor instructions for moderators for unconference sessions, the main room, general presentation, and SIG meetings.
Separate files are used instead of adding to volunteers.md since these instructions are intended to be printed and provided to room proctors.
The unconference room proctor instructions came from @mfahlandt 's Google Doc: https://docs.google.com/document/d/1V2Eoqulktul_i-UqJTd3svbODxulm5n7RV7m_rJg9P0/edit?usp=sharing
=> Add room proctor instructions

sig-cluster-lifecycle/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/5097
/assign @kubernetes/sig-cluster-lifecycle-leads 
=> sig-cluster-lifecycle: add karpenter-provider-cluster-api repo

contributors/guide/pull-requests.md
Occasionally contributors run linters, fix issues found by them (sometimes automatically!) and then create PRs. This creates work for maintainers and is often not useful, so let's write this down. Perhaps future contributors will find it, if not, we can point to it in PRs when closing them.
Related-to: https://github.com/kubernetes/kubernetes/pull/128350#issuecomment-2439631164
/assign @liggitt 
/cc @thockin
=> PRs: document policy around fixing linter checks

communication/slack-config/channels.yaml
This adds #k0s-users and #k0s-dev to the Kubernetes Slack Channels
**Purpose:**
The k0s community is growing and we are working on multiple things that would make it much easier to have two slack channels about k0s
1. k0s has been maintained by Mirantis employees so far, recently we added additional Maintainers from other companies to k0s (https://github.com/k0sproject/k0s/blob/main/MAINTAINERS.md) and would need a place to talk about PRs, issues, etc. - hence we would like to add #k0s-dev
2. k0s has a growing community of users and right now there is no slack channel for k0s users to talk about it we would like to do this in the CNCF slack - hence we would like to add #k0s-users
3. k0s is working on becoming a Sandbox project: https://github.com/cncf/sandbox/issues/125
**About k0s:**
- …
=> Add k0s-users and k0s-dev to slack channels

communication/slack-config/channels.yaml
create slack channels for the e2e-framework project
one for the development and the other for users support and general requests/topics
/assign @jberkus @mrbobbytables @harshanarayana @vladimirvivien
=> create e2e-framework slack channels

communication/slack-config/channels.yaml
Add a new slack channel 'kro' to facilitate discussions around Kube Resource Orchestrator implementation and usage.
Link: https://kro.run/
=> Add project `kro` to slack channels

generator/app.go, sigs.yaml
This is for https://github.com/kubernetes/steering/issues/281, and may also be useful for populating the leads mailinglist.
It is not intended to surface the leads's emails for other purposes and therefore the generator is not extended to display it in the SIG/WG markdown files.
=> add email to lead metadata

sigs.yaml
Add emails for wg-batch leads. I used https://github.com/kubernetes/k8s.io/blob/main/groups/wg-batch/groups.yaml as the source of truth here.
Refer to https://groups.google.com/a/kubernetes.io/g/leads/c/3A2d1_onI3o
cc @soltysh @swatisehgal @mwielgus
=> add emails for wg-batch leads on sigs list

sig-release/README.md, sigs.yaml
This PR updates the lead data for the SIG release leads.
Hold while collecting everyone's info
/hold
Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>
=> Update SIG Release leads emails and affiliations - 2024

sigs.yaml
Adding now that https://github.com/kubernetes/community/pull/8138 is done
Using the same addresses that we already have listed here:
https://github.com/kubernetes/k8s.io/blob/main/groups/committee-security-response/groups.yaml#L27-L34
=> Add SRC email addresses

elections/code-of-conduct/2023/OWNERS, elections/code-of-conduct/2025/README.md, elections/code-of-conduct/2025/election.yaml, elections/code-of-conduct/2025/election_desc.md, elections/code-of-conduct/2025/results.md, elections/code-of-conduct/2025/voters.yaml, elections/code-of-conduct/OWNERS
*In an effort to deconflict between Steering and Code of Conduct Committee
election timing and provide new Steering Committee members sufficient time to
onboard (3+ months), the Steering Committee has made the decision to move the
Code of Conduct Committee elections to follow the 2024 Steering elections,
instead of preceding them.*
I am proposing the following timeline for the 2025 Code of Conduct Committee elections:
| Date | Event |
| --- | --- |
| Monday, December 2 | Nominations Open |
| Friday, January 31 | Nominations Close |
| Monday, February 3 | Steering to confirm candidacy |
| Monday, February 10 | Election Begins |
| Monday, February 17 | Election Closes |
| Tuesday, February 18 | Announcement of results |
| Thursday, February 20 | CoCC to hold onboarding sessions for new …
=> Code of Conduct Committee Elections — 2025

wg-serving/README.md
Work groups CANNOT sponsor subprojects, only suggest and participate in them. work groups are discussion groups for interests that potentially cross sigs.
Also, subprojects are tracked in sigs.yaml in a standardized format with specific metadata required.
Fixes #
FYI @ArangoGutierrez @Jeffwan @SergeyKanzhelev @terrytangyuan
=> remove inaccurate representation of subprojects

github-management/README.md
Cleaning up the list of New Membership Coordinators.
=> New Membership Coordinator: cleanup

sig-architecture/README.md, sigs.yaml
The repo was created based on https://github.com/kubernetes/org/issues/4886 with SIG Architecture as owner, so it should be documented under that SIG.
Fixes https://kubernetes.slack.com/archives/G6LUC4J7M/p1732278914037949?thread_ts=1732231045.231229&cid=G6LUC4J7M
/assign @johnbelamaric
=> sig-architecture: document wg-device-management repo

sigs.yaml
Follow-up https://github.com/kubernetes/community/pull/8154 for other leads after obtaining their preferred emails.
=> Add emails to WG Serving leads in sigs.yaml

sigs.yaml
this change adds email addresses for the chairs and tech leads.
=> update sig-cloud-provider emails in sigs.yaml

sigs.yaml
xref https://groups.google.com/a/kubernetes.io/g/leads/c/3A2d1_onI3o
cc @serathius, @wenjiaswe, @ahrtr
=> Add sig-etcd lead emails to sigs.yaml

sig-storage/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/5238
=> sig-storage: add container-object-storage-interface repo

contributors/guide/owners.md
~~Should avoid to the next maintainer looking at OWNERS files docs to needlessy avoid `filters` for use with `approvers`~~
- gubernator reference cleanup
- followup to 0fc7f1615b8799e6b25d15b26b8dfb15f8430e35 : clean up leftover links.
/sig contribex
=> owners.md: cleanup outdated links / stale gubernator reference

contributors/chairs-and-techleads/process-workflow-guide.md
* SIG CLI tp instance moved to https://cli.triage.k8s.io/s/kubectl
* SIG Release doesn't use tp anymore (https://github.com/kubernetes/k8s.io/commit/eb5b0bb4326edf78540f8a0f5ac7ff5217b9fdc0, https://github.com/kubernetes/sig-release/issues/2660)
=> Update triage party usage information

sig-storage/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/5238
=> sig-storage: remove cosi-provisioner-sidecar, cosi-controller, cosi-spec repos from kubernetes-cosi subproject

sigs.yaml
Following the merge of #8138, adding the emails for SIG Docs chairs and tech leads
cc: @natalisucks @reylejano @katcosgrove @salaxander @tengqm 
=> Adding emails for SIG Docs chairs and tech leads

sigs.yaml
Email for @klueska is from
https://github.com/kubernetes/k8s.io/blob/ab454c582cd8aa08187da5d9ec95926a4b48fa66/groups/wg-device-management/groups.yaml#L17C9-L17C26
Related-to: https://github.com/kubernetes/steering/issues/281
/assign @BenTheElder @klueska
=> add emails for pohly and wg-device-management

sig-storage/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/5238
cc: @kubernetes/owners 
=> sig-storage: remove container-object-storage-interface-api subproject repo

.github/ISSUE_TEMPLATE/slack-request.yml
I wasn't aware that GH issue template YML didn't support line continuation.  Fix here.
=> Fix GH Yml format on slack template.

OWNERS_ALIASES, sig-k8s-infra/README.md, sigs.yaml
Add myself (@xmudrii) as a SIG K8s Infra Tech Lead.
xref https://github.com/kubernetes/community/issues/8204
/assign @BenTheElder @dims @ameukam @upodroid
=> Add xmudrii as K8s Infra Tech Lead

sig-apps/README.md, sig-network/README.md, sigs.yaml
New name will be gateway-api-inference-extension.
None in this repo, but addresses https://github.com/kubernetes-sigs/llm-instance-gateway/issues/41.
For more context on the name change, refer to the original [proposal](https://docs.google.com/document/d/1gLYe9zPNeMuxKWolcu5MRm_Sq2xoZBXn100e-fZ6fX4/edit?tab=t.0) which has previously been discussed in SIG-Network, Instance Gateway, and Gateway API community meetings, as well as WG-Serving Slack and mailing list. 
Looking for LGTM from representatives from each of the following groups:
SIG Apps Leads:
/cc @janetkuo @kow3ns @soltysh 
SIG Net Leads:
/cc @aojea @danwinship @MikeZappa87 @shaneutt @thockin 
WG Serving Leads:
/cc @ArangoGutierrez @Jeffwan @SergeyKanzhelev @terrytangyuan
/hold for consensus
=> Moving Instance Gateway to SIG-Network and renaming it

contributors/devel/sig-architecture/staging.md
This PR updates the staging branch list and clarify publishing rules in the contributor directory.
Fixes #
=> doc: Update staging branch list and clarify publishing rules

communication/README.md
Fixes # NA
When following the older link it was showing a deprecation notice
> As of January 2, 2022, this group will be sunset in favor of dev@[kubernetes.io](http://kubernetes.io/). Please join that one if it's not already in your list. https://groups.google.com/a/kubernetes.io/group/dev
This PR fixes the link and points it to  https://groups.google.com/a/kubernetes.io/group/dev as said above ^^
=> Fix google groups link

sig-cli/CONTRIBUTING.md
Update the path to the implementation of kubectl to `kubernetes/staging/src/k8s.io/kubectl/pkg` in `sig-cli/CONTRIBUTING.md`
**Which issue(s) this PR fixes**: #8224 
Fixes #8224
=> Update sig-cli CONTRIBUTING.md file

contributors/devel/sig-node/e2e-node-tests.md
Fixes #
KEP-3041.
Use Feature instead of NodeFeature.
See https://github.com/kubernetes/test-infra/issues/33823
=> drop mention of NodeFeature

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
This PR syncs up the Slack `cluster-api-release-team` with its current v1.10-release members.
Refs kubernetes-sigs/cluster-api#11648
=> CAPI: Update v1.10 release team members

sigs.yaml
See also https://github.com/kubernetes/steering/issues/281 and https://github.com/kubernetes/community/pull/8138
=> Add emails for sig security leads

sigs.yaml
Add sig-instrumentation emails from https://github.com/kubernetes/k8s.io/blob/b12ba16414584f6196da71053c40059a906dd264/groups/sig-instrumentation/groups.yaml#L27.
=> Add sig-instrumentation leads' emails

communication/slack-config/channels.yaml, sig-autoscaling/README.md, sigs.yaml
vertical-pod-autoscaler is a big enough subproject in sig-autoscaling
that it needs a dedicated channel.
I also noticed that the karpenter channel wasn't listed, so I added
that.
cc @gjtempleton (The sig-autoscaling chair)
=> Create new vertical-pod-autoscaler channel

sigs.yaml
xref https://groups.google.com/a/kubernetes.io/g/leads/c/3A2d1_onI3o
cc @kubernetes/sig-contributor-experience-leads 
/hold
hold for confirmation for added emails by all SIG ContribEx leads
=> sig-contribex: add leads emails to sigs.yaml

communication/slack-config/channels.yaml
Adds a new Slack channel named "cluster-api-release" for the Cluster API SIG to use for coordinating Cluster API releases and release team responsibilities.
=> slack-config: Add cluster-api-release channel

committee-steering/governance/annual-reports.md
I was asked about the [annual reports process](https://github.com/kubernetes/community/blob/master/committee-steering/governance/annual-reports.md), which currently is a bit outdated. 
This PR updates that document, to point to the template files used by [the generator](https://github.com/kubernetes/community/tree/master/generator#how-to-use), rather than copying verbatim the questions from those templates. 
cc: @kubernetes/steering-committee
=> Update annual reports documentation to point to actual templates used for generating reports

sig-node/CONTRIBUTING.md
/sig node
This is in response to https://docs.google.com/document/d/1AavM205LRi-RNB2xQRduzDo_ChTZ8clacKYtgsbfSAQ/edit
Related to #6611
=> contributing KEPs in SIG Node: best practices

contributors/devel/README.md, contributors/devel/sig-node/cri-validation.md, sig-node/charter.md
/sig node
See also: https://github.com/kubernetes-sigs/cri-tools/pull/1761
This page belongs to cri-tools repo. And it is alredy referenced from https://www.kubernetes.dev/docs/code/cri-api-version-skew-policy/#feature-testing
All CRI docs pages can and should be moved to the contributing website.
=> remove critest page from community repository

committee-steering/governance/project-naming.md, github-management/kubernetes-repositories.md
Fixes https://lists.cncf.io/g/cncf-toc/message/8738
/hold
=> naming guidelines

OWNERS_ALIASES, sig-testing/OWNERS, sig-testing/README.md, sigs.yaml
- Move Cole and Alvaro to emeritus (thanks again!)
- Add new subproject leads (as detailed in the announce email to kubernetes-sig-testing in September)
- Add subproject leads to SIG Testing reviewers.
(Saw that SIG Release has a similar setup and given the number of folks we have as subproject leads, it seemed reasonable to follow suit. If someone has a better recommendation, lemme know!)
I added everyone from the announce email, but I'm missing some emails for some of y'all; if you can provide them I'm happy to add them. (Specifically for @rjsadow , @petr-muller , @upodroid , @jbpratt , @xmcqueen )
=> Update SIG Testing leads and subproject leads.

OWNERS_ALIASES, contributors/devel/OWNERS
It looks logical to match this folder to https://github.com/kubernetes/contributor-site/blob/master/content/en/docs/code/OWNERS.
Many articles here may be better suited for contributor site as well.
Discovered this OWNER file when was looking at old CRI documentation like this: https://github.com/kubernetes/community/pull/8305
=> make sig-architecture-approvers to be approvers of devel

sig-etcd/README.md, sigs.yaml, wg-etcd-operator/README.md, wg-etcd-operator/annual-report-2024.md
Most of the annual report for Etcd Operator working group.  A few things missing:
1. Where can I put a link to our repository in sigs.yaml?  I don't see a field for repos.
2. Since our WG was created in 2024, do we need to have status meetings with our sponsoring SIGs?
3. I couldn't find the Operator Workflow doc, @ahrtr link to that?
attn: @soltysh @justinsb @jmhbnz
=> WG-Etcd Operator annual report

wg-batch/annual-report-2024.md
=> annual report for wg-batch 2024

sig-cluster-lifecycle/annual-report-2024.md
Fixes https://github.com/kubernetes/community/issues/8260
- https://github.com/kubernetes/community/issues/8260
=> 2024 Annual Report: SIG Cluster Lifecycle

communication/slack-config/channels.yaml
I would like to add a Slack channel for my project Spegel, which is a stateless cluster local OCI registry mirror built for Kubernetes.
https://github.com/spegel-org/spegel
I read through the Slack guidelines and did not see any explicit requirements for adding project channels so hopefully this is ok.
=> Add Spegel Slack channel

sig-release/annual-report-2024.md
=> SIG Release Annual Report 2024

sig-instrumentation/annual-report-2024.md
Fixes #https://github.com/kubernetes/community/issues/8264
=> Annual Report for SIG Instrumentation 2024

events/events-team/comms/README.md
Updating requirements, tasks, and descriptions for all roles on the KCS Comms team.
=> Update KCS Comms Team Handbook

communication/slack-config/usergroups.yaml
Postsubmit  [post-community-tempelis-apply](https://testgrid.k8s.io/sig-contribex-slack-infra#post-community-tempelis-apply) job is failing after changes in https://github.com/kubernetes/community/pull/8361
IIUC, it is because the new added user `Hii-Arpit` to the `youtube-admins` group didn't have a corresponding entry in `communication/slack-config/users.yaml`.
We do have an entry for `hii-arpit` :
https://github.com/kubernetes/community/blob/d1d75b0720a20a44a4c7dec2e608935760d14d33/communication/slack-config/users.yaml#L101
So, PR is updating the `youtube-admins` groups to instead add `hii-arpit`, in an attempt to fix the failing tempelis job.
cc: @chris-short @kaslin
=> update youtube-admins slack user group

sig-network/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/5433
=> sig-network: add network-policy-finalizer under network-policy subproject

sig-scalability/README.md, sigs.yaml
xref https://github.com/kubernetes/org/issues/5334
/assign @wojtek-t 
for LGTM
/hold
=> sig-scalability: add inference-perf subproject

sig-api-machinery/annual-report-2024.md
=> Update SIG API Machinery annual-report-2024.md

sig-contributor-experience/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/5437
/assign @kubernetes/sig-contributor-experience-leads
=> sig-contribex: retire contributor-katacoda repo

sig-autoscaling/CONTRIBUTING.md, sig-autoscaling/README.md, sig-autoscaling/annual-report-2024.md
=> SIG Autoscaling - 2024 Report

wg-serving/annual-report-2024.md
Fixes https://github.com/kubernetes/community/issues/8283
=> 2024 Annual Report: WG Serving

sig-storage/annual-report-2024.md
This PR updates the SIG-Storage 2024 annual report.
cc @saad-ali @msau42 @jsafrane 
Fixes #8273
=> SIG-Storage 2024 annual report

sig-testing/README.md, sigs.yaml
Ref: https://github.com/kubernetes/org/issues/5414
/assign @kubernetes/sig-testing-leads 
=> sig-testing: add subproject - randfill

wg-lts/annual-report-2024.md
Fixes https://github.com/kubernetes/community/issues/8281
/hold 
/wg lts
/cc @jeremyrickard @micahhausler
=> 2024 wg-lts report

github-management/kubernetes-repositories.md
Follow up on https://github.com/kubernetes/org/issues/5414#issuecomment-2701378732
Including additional guidelines for creating forks of external repos under Kubernetes GitHub organisations (in addition to the existing guidelines for donating repos.)
/assign @kubernetes/owners
=> github-management: update guidelines for forking external repositories

sig-instrumentation/README.md, sigs.yaml
Updates list of sub-projects under sig-instrumentation
Apologies for the back and forth on this, we actually decided against stating zpages as a subproject [later on](https://github.com/kubernetes/community/pull/8327#discussion_r1974068328) 
Issue #https://github.com/kubernetes/community/issues/8264
=> Remove zpages as subproject from sig-instrumentation

sig-scheduling/README.md, sigs.yaml
Fixes #
We removed some teams, but forgot updating the list here.
=> fix: remove removed teams from the "Contact" lists

contributors/devel/running-locally.md
This PR fixed the Hyperlink of dns docs under the [The pods fail to connect to the services by host names](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md#the-pods-fail-to-connect-to-the-services-by-host-names) in [running-locally.md](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md)
Fixes #8360
=> Fixed the Hyperlink of DNS.

contributors/devel/running-locally.md
As Per https://github.com/kubernetes/community/pull/8375#issuecomment-2710328409, added Debugging DNS Resolution under the [The pods fail to connect to the services by host names](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md#the-pods-fail-to-connect-to-the-services-by-host-names) in [running-locally.md](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md)
=> Added Debugging DNS Resolution.

sig-instrumentation/annual-report-2024.md
Noting that all sig-instrumentation recordings are now uploaded to youtube.
=> Update sig-inst 2024 report to say all recordings are uploaded

sig-multicluster/README.md, sigs.yaml
For https://github.com/kubernetes/org/issues/5457
/assign @kubernetes/sig-multicluster-leads
=> sig-multicluster: add subproject for kubernetes-sigs/multicluster-runtime

sig-node/annual-report-2024.md
=> sig-node: update 2024 annual report

sig-node/CONTRIBUTING.md, sig-node/README.md, sig-node/sig-node-ci-testing-group-charter.md
This is an update for the charter (from  https://docs.google.com/document/d/1yS-XoUl6GjZdjrwxInEZVHhxxLXlTIX2CeWOARmD8tY/) with some mentions in how to contribute.
/sig node
/cc @haircommander
=> charter for CI testing subgroup of SIG Node

sig-contributor-experience/annual-report-2024.md
Bootstrapping the 2024 annual report for SIG ContribEx
Fixes #8261
=> sig-contribex: update 2024 annual report

sig-scheduling/annual-report-2024.md
/cc @kubernetes/sig-scheduling-misc @macsko @dom4ha @AxeZhan 
Added the 2024 annual report for SIG-Scheduling.
Fixes #8271
=> add: SIG-Scheduling annual report

communication/slack-config/channels.yaml
Per discussion in [Kep-5000](https://github.com/kubernetes/enhancements/pull/5102#discussion_r1983184427), we would like to create a slack channel for communication around API machinery dev tooling that we are introducing
=> Add slack channel for API Machinery dev tools

sig-etcd/annual-report-2024.md
Ref #8263 
/sig etcd
/cc @ahrtr @serathius @jmhbnz
=> 2024 SIG etcd annual report

sig-auth/README.md, sigs.yaml
=> sig-auth: add subproject leads for secrets-store (csi driver and sync-controller)

generator/OWNERS
Follow up from https://github.com/kubernetes/community/pull/8377#issuecomment-2716010345
Changes:
- add @kubernetes/sig-contributor-experience-leads as approvers for generator tool
- add @nikhita @spiffxp as emeritus approvers
/assign @kubernetes/sig-contributor-experience-leads
=> Update generator owners

sig-security/README.md, sigs.yaml
Per longstanding discussion in SIG Security meetings and slack, retire SIG Security Self-Assessments subproject.
See also https://groups.google.com/g/kubernetes-sig-security/c/-f_yguXvop8/m/uwlsLfeQAgAJ
=> Sunset SIG Security Self-Assessments subproject

OWNERS
1. Add me to Approvers so that I can continue to help with the backlog
2. Move Ihor and Paris to Emeritus, since neither is actively reviewing/approving right now.
attn: @kaslin @mfahlandt @MadhavJivrajani @Priyankasaggu11929
=> Update OWNERS for k/community

contributors/devel/sig-architecture/staging.md
As discussed in https://github.com/kubernetes/test-infra/pull/34209 we want those best practices applied for all staging repositories
=> List the best practices on configuring staging repo

events/awards/README.md
before we synced things like https://github.com/kubernetes/community/pull/6759#issuecomment-1195778361.
We may merely maintain the award recipient in the contributor site.
=> add link to contributor awards site

mentoring/README.md
Moving `1:1 Hour` session to discontinued activities
/assign @kubernetes/sig-contributor-experience-leads
=> move 1:1 hour to discontinued activities under mentoring subproject

sig-testing/charter.md
=> drop defunct tools references from sig testing charter

contributors/devel/development.md
This removes adding the gnu bin utils to the path on macOS.
This is handled by `homebrew` in most cases.
Fixes #8391
=> Remove add gnu bins to path

sigs.yaml
pulled from https://github.com/kubernetes/k8s.io/blob/main/groups/committee-code-of-conduct/groups.yaml
this will make it easier to validate that all leads have this field set, in the future we can drive the email lists from this source of truth ...
Blocks https://github.com/kubernetes/community/pull/8421
=> add missing emails for code of conduct committee

contributors/devel/sig-testing/e2e-tests.md
Fixes # N/A
DBG=1 enables these settings and also disables stripping the binaries. The current instructions do not produce a debuggable binary.
NOTE: this change does produce a binary that can be debugged, the next bit about using it with "ginkgo.sh" is also wrong but I'm not done iterating on that part. I filed this to avoid forgetting fixing the part which I know the correct fix for already.
/cc @pohly @aojea
=> correct guidance for building e2e.test with debug symbols

generator/app.go
Fixes #
xref: https://github.com/kubernetes/steering/issues/281
NOTE: This will fail because some emails are missing currently.
I have PRs in flight for the emails.
=> fix validation for company affiliation and email must be set for leads

sig-node/CONTRIBUTING.md
Fixes a broken link to the SIG Node CI charter doc from the SIG Node CONTRIBUTING.md file.
=> Fixed link to SIG Node CI charter doc

sig-cli/CONTRIBUTING.md
Old broken URL: https://github.com/kubernetes/kubectl/projects/3
New URL https://github.com/kubernetes/kubectl/issues?q=is%3Aissue%20state%3Aopen%20label%3Apriority%2Fbacklog
Fixes #8431
=> Fix [issues] link in `sig-cli/CONTRIBUTING.md`

communication/slack-config/users.yaml
Follow up: https://github.com/kubernetes/community/pull/8411
---
To fix failing tempelis job - https://storage.googleapis.com/kubernetes-ci-logs/logs/post-community-tempelis-apply/1920490705503916032/build-log.txt
```
2025/05/08 14:47:30 Error 1: Product Security Committee: unknown user names: natherz97.
```
=> [tempelis] add slack member id for gh user natherz97

communication/slack-config/channels.yaml, communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
In accordance with the [Slack guidelines](https://www.kubernetes.dev/docs/comms/slack/#requesting-a-channel), we, the maintainers of kubetail, @amorey and myself, are respectfully requesting the creation of a channel for the kubetail project.
Kubetail is a real-time logging dashboard designed for Kubernetes. As an open-source project under the Apache License Version 2.0, our community is expanding. To mark our milestone of achieving +1000🌟 on github, we aim to grow and centralize our community on the Kubernetes Slack platform. This will facilitate easier access for new contributors, as a significant portion of the Kubernetes community is already active on this Slack.
- Website: [kubetail.com](https://www.kubetail.com/)
- GitHub: [kubetail-org/kubetail](https://github.com/kubetail-org/kubet …
=> new: add kubetail and its usergroup

communication/slack-config/channels.yaml
This change adds a slack channel for the inference-perf project (https://github.com/kubernetes-sigs/inference-perf) since we have quite a few topics to discuss on a regular basis.
cc @terrytangyuan @wangchen615 @SachinVarghese
=> Create #inference-perf slack channel

contributors/guide/pull-requests.md
This primarily came out of the discussion around allowing the use of LLMs (https://github.com/kubernetes/steering/issues/291), but isn't limited to it because other tools (search/replace, linters) can have the same effect.
The goal is to clarify expected behavior and to give reviewers something that they can link to when they decide that a PR shouldn't get merged.
Fixes https://github.com/kubernetes/steering/issues/291
/cc @kubernetes/steering-committee @danwinship
=> pull-requests.md: add guidance for large and/or automatic edits

communication/slack-config/sig-release/usergroups.yaml, communication/slack-config/users.yaml
Update `release-team-leads` slack group and user.yaml to reflect the v1.34 release team.
=> Add permissions for v1.34 release team leads and subteam leads

contributors/devel/sig-architecture/feature-gates.md
This syncs the featuregate docs with the beta criteria doc from sig-arch in enhancements: https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/5241-beta-featuregate-promotion-requirements
/assign @johnbelamaric
=> explain that GA features must be disableable if it is the first release they are default-on

contributors/devel/sig-node/kubelet-cri-networking.md
**Which issue(s) this PR fixes**: 
This PR updates a broken link (http://kubernetes.io/docs/admin/networking/) that returns 404 Not Found.
I considered linking to one of these docs:
* [Design Proposal: Networking](https://github.com/kubernetes/design-proposals-archive/blob/main/network/networking.md)
* [Concepts: Services/Networking](https://kubernetes.io/docs/concepts/services-networking/) 
...but it seems [Cluster Admin Concepts: Networking](https://kubernetes.io/docs/concepts/cluster-administration/networking/) is most fitting as a simple doc that doesn't overemphasize Services, etc.
=> update doc link; add period

sig-scheduling/CONTRIBUTING.md
SIG-scheduling's contribution docs should point to the correct charter. It is not pointing at the correct one currently.
/sig scheduling
=> Fix SIG scheduling's contribution charter link

contributors/guide/release-notes.md
**What this PR does / why we need it**:
This PR updates the "Release Notes Handbook" link in `contributors/guide/release-notes.md` to point to the correct location of the handbook on GitHub.  
The previous link was broken and resulted in a 404 error.
Fixes #8509
**Special notes for your reviewer**:
- No other content was changed.
- The new link is: https://github.com/kubernetes/sig-release/blob/master/release-engineering/release-notes.md
=> fix: update Release Notes Handbook link to correct URL

contributors/guide/pull-requests.md
Currently it doesn't render correctly as a link, and the text is just `The effort required to review such sweeping changes might not be worth it, see [“large or automatic edits”)[#large-or-automatic-edits] below`
Fixes #
=> Fix link to large-or-automatic-edits

sig-api-machinery/README.md, sigs.yaml
ref: https://github.com/kubernetes/org/issues/5592
/assign @kubernetes/sig-api-machinery-leads 
=> sig-api-machinery: add crdify subproject

mentoring/README.md
N/A
Request to update the mentoring docs since Google season of docs program is no longer active.
Also fixing a heading that I believe should be a H2 rather than a H4?
=> Minor update to move GSoD to discontinued section

contributors/guide/issue-triage.md
- Update Release Team project board link to current working URL
- Replace broken SIG project board links (Contributor Experience, Network, Windows) with currently active project boards (Apps, Auth, Scheduling).
Fixes #
=> Fix: broken GitHub project board links in triage

OWNERS
/assign @kubernetes/steering-committee
=> root OWNERS: match charter.md case-insensitive, require steering instead of only labeling

sigs.yaml
The email in sigs.yaml doesn't have a google account so can't use google groups. Using my work email instead so I can access the Google Group for leads.
=> Fixing my email in Node Lifecycle WG Chairs

communication/slack-config/usergroups.yaml, communication/slack-config/users.yaml
This PR syncs up the Slack cluster-api-release-team with its current v1.11-release members.
Also moved a couple aliases in the users.yaml file to proper alphabetical position.
Refs kubernetes-sigs/cluster-api#12150
=> CAPI: Update v1.11 release team members

elections/steering/2025/election.yaml, elections/steering/2025/election_desc.md, elections/steering/2025/voters.yaml
Adds the election.yaml and election_desc.md required to setup the election in Elekto. Also adds the template for voters.yaml although this still needs to be populated with the list of eligible voters.
/hold
=> 2025 Steering Elections: Added election.yaml and election_desc.md

elections/steering/2025/README.md
Looks like we accidentally repeated the number of open seats from last year's election README instead of adjusting it to match the correct number for this year. Based on https://elections.k8s.io/app/elections/steering---2025 there are 4 open seats (which makes sense, as it was 3 open seats in 2024 and 4 open seats in 2023.)
=> Fixing typo about number of seats in election

sig-multicluster/terminology.md
Add a `terminology.md` page in the community repo for SIG-Multicluster that gives a bare-bones list of terminology and their alternate names, and provides a link out to the website for more information.
No issue, but based off of conversation in https://github.com/kubernetes/community/pull/8210#issuecomment-3012304521.
=> Add basic terminology page for SIG-MC.

elections/OWNERS, elections/steering/2025/OWNERS, elections/steering/OWNERS
- Ensures that `area/elections` is added to elections/ dir stuff
- Uses `no_parent_owners` to prevent contribex stuff from applying to steering stuff
=> Fixup labels for elections directories

hack/verify-steering-election.sh
This was broken because it was pointing to the wrong directory. I've got a better go-based version in #8596, but this at least fixes the bash version immediately
=> Fix bash-based word count validation for steering elections

contributors/devel/sig-architecture/api-conventions.md, contributors/devel/sig-architecture/api_changes.md
Fixes #8559 
Issue text copied below for context:
As of v1.33, Kubernetes supports declarative validation for API developers.  
- https://kubernetes.io/docs/reference/using-api/declarative-validation/
The kubernetes/community documentation at:
- contributors/devel/sig-architecture/api_changes.md
- contributors/devel/sig-architecture/api-conventions.md
should be updated to reference declarative validation where appropriate, explain that it is the preferred way to declare validation of types and fields for supported validations, and explain how to use it generally.
=> docs: update api_changes.md and api_conventions.md with declarative validation information

sig-api-machinery/README.md, sigs.yaml
This PR fixes the archive_url for the recently added Declarative APIs and Linters subproject meeting setting it to the appropriate file (currently it points to the Kubebuilder meeting archive_url)
=> docs: fix archive_url for Declarative APIs and Linters subproject meeting

sig-node/sig-node-kep-wrangler-program.md
This PR adds a page to the sig-node docs describing the KEP wrangler role and all the different responsibilities of the wranglers. A part of the content is based on [this brainstorming doc](https://docs.google.com/document/d/1CypSsxdowXk0PmoYLF7h5Q91MjiUPibsLFmwUVR4fKs/edit?tab=t.0) which used to be the only documentation relating to the wrangler program until now. I've added details about some new processes on status reporting, which is something we want to try for v1.35, and is up for review.
CC: @SergeyKanzhelev @haircommander
=> Added doc on SIG Node KEP wrangler program

sig-architecture/production-readiness.md
No issue created for this. `kepctl` was replaced by GitHub project boards.
=> prod-readiness: remove mentions of kepctl

sig-api-machinery/README.md, sigs.yaml
Updates the recordings url to be correct for the SIG API Machinery Suproject Meeting - Declarative APIs and Linters
=> docs: update declarative apis and linters meeting recordings url

OWNERS_ALIASES, sig-autoscaling/README.md, sigs.yaml
Updates SIG Autoscaling TL from myself to @adrianmoisey per [this announcement](https://groups.google.com/g/kubernetes-sig-autoscaling/c/VH_Dj1nWCUw/m/ulj2jMCuAQAJ).
Updated info in `sigs.yaml` and ran `make generate`.
See https://github.com/kubernetes/community/issues/8629.
=> Update SIG-Autoscaling TL to adrianmoisey

elections/steering/2025/voters.yaml
This PR adds following voters from approved exception requests, as of September 28, 2025.
- @avni-mahajan
- @chewong
- @chris-short
- @Debanitrkl
- @fykaa
- @intUnderflow
- @lachie83
- @nimbinatus
- @sandeepkanabar
---
/assign @cblecker @npolshakova 
/hold
for review and approval from Election Officers. Thanks!
=> [Steering 2025] Add voters from approved exception requests - Sep 28

communication/slack-config/channels.yaml
This adds a new slack channel to be used for a working group focused on machine pools in cluster api.
=> chore: add new slack channel for CAPI working group
