contributors/devel/sig-testing/e2e-tests.md

xref https://github.com/kubernetes/kubernetes/issues/99909

sig-testing/e2e-tests.md: add notes about MinimumKubeletVersion

---

communication/slack-config/channels.yaml

Create a channel for discussion around [OpenKruise](https://openkruise.io/en-us/) (a set of extended k8s workload controllers and a CNCF sandbox project) and connect its maintainers with k8s community.

Add channel for openkruise project

---

mentoring/README.md
mentoring/programs/google-season-of-docs.md
mentoring/programs/google-summer-of-code.md
mentoring/programs/lfx-mentorship.md

Mentoring information updated

---

sig-instrumentation/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2566
/assign @brancz 
/hold
for lgtm from sig-instrumentation leads

sig-instrumentation: add k-sigs/instrumentation repo

---

sig-security/security-audit-2021/RFP.md

Extend 2021 External Security Audit RFP's question period and closing dates
/assign @tabbysable

Extend 2021 External Security Audit RFP's question period and closing dates

---

communication/moderators.md

Updates the moderator list for the Discuss platform.
/cc @mrbobbytables
/cc @cartyc

docs: updates the discuss moderators list

---

sig-auth/README.md
sigs.yaml

Fixes https://github.com/kubernetes/org/issues/2516
/assign @mikedanese 
/hold
for lgtm from sig-auth leads

sig-auth: add HNC subproject

---

contributors/devel/README.md
sig-storage/CONTRIBUTING.md

This PR updates the contributing doc for sig-storage.
Fixes #

Update CONTRIBUTING doc

---

sig-cli/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2461
cc @starpit @myan9
/assign @eddiezane 
/hold
for lgtm from sig-cli leads

sig-cli: add kui repo

---

communication/slack-config/channels.yaml

This PR adds a slack channel for the open-source project [metal-stack](https://metal-stack.io) which can be used to produce Kubernetes clusters with the help of [gardener](https://gardener.cloud/) or in the near future with the cluster-api on bare-metal.

Add slack channel for metal-stack

---

mentoring/README.md
values.md

Hello folks,
this PR adds the Hugo headers to three different pages we want to import in a new section in the Contributor Site!
https://github.com/kubernetes/contributor-site/issues/201
@mrbobbytables please let me know if you are planning to add other contents in this first iteration.

Adding Hugo headers for contributor site

---

sig-network/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2410
cc @mcluseau 
/assign @thockin 
for lgtm
/hold
for lgtm from sig-network leads

sig-network: add kpng repo

---

communication/slack-config/sig-release/usergroups.yaml

As part of my offboarding https://github.com/kubernetes/sig-release/issues/1442
Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>

Remove myself from release-manager slack group

---

sig-scalability/annual-report-2021.md

Ref https://github.com/kubernetes/community/issues/5509

2021 SIG Scalability annual report

---

sig-contributor-experience/annual-report-2020.md

ref: #5502 
/assign @mrbobbytables @alisondy @cblecker @nikhita

SIG ContribEx: Add 2021 Annual Report

---

sig-storage/annual-report-2021.md

Fixes #5513
CC @saad-ali @msau42 @jsafrane

Add annual report for SIG-Storage

---

contributors/guide/first-contribution.md

Typo critiqe to critique in first-contribution.md

Fix typo in first-contribution.md

---

wg-data-protection/annual-report-2021.md

This PR adds the annual report for Data Protection WG.
Fixes #
CC @yuxiangqian

Add annual report for Data Protection WG 2021

---

sig-instrumentation/README.md
sigs.yaml

Fixes https://github.com/kubernetes/org/issues/2611
/assign @logicalhan 
/hold
for lgtm sig-instrumentation leads

sig-instrumentation: add instrumentation-addons repo

---

sig-security/README.md
sigs.yaml

Add slack contact for sig-security-docs

---

contributors/devel/sig-release/cherry-picks.md

Follow up from https://github.com/kubernetes/community/pull/5703

A note on CP reviews

---

sig-multicluster/annual-report-2021.md

Add annual report for SIG-MC

---

communication/slack-config/usergroups.yaml

See also https://github.com/kubernetes/security/pull/124 and https://github.com/kubernetes/community/pull/5686

Add Tabitha to PSC usergroup

---

mentoring/programs/group-mentoring.md

Co-authored-by: Elana Hashman <ehashman@redhat.com>

bringing group mentoring program current

---

mentoring/processes/group-mentoring.md

Co-Authored-By: Elana Hashman <ehashman@redhat.com>

bringing group mentoring process current

---

contributors/devel/sig-instrumentation/migration-to-structured-logging.md

The current document does not clearly explain how to migration some situations,  I added.
Fixes #

Clear instructions for structured log migration

---

sig-architecture/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2636
/assign @dims 
for lgtm
/hold
for lgtm from sig-arch leads

sig-arch: add depstat repo

---

sig-storage/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/2631
/hold
for lgtm from sig-storage lead

sig-storage: add cosi-driver-minio repo

---

contributors/devel/sig-api-machinery/strategic-merge-patch.md

Warn that SMP is somewhat obsolete

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

Signed-off-by: Matthew Broberg <matt@opensource.com>
Fixes #5704

Slack: adding new memebers of contrib-comms

---

sig-auth/README.md
sigs.yaml

xref: https://github.com/kubernetes/kubernetes/pull/100885

Update sig-auth subproject OWNERS links

---

sig-api-machinery/annual-report-2020.md

Fixes https://github.com/kubernetes/community/issues/5494
This provides the standard annual report.  Overall, we think api-machinery is in a healthy spot.
/cc @fedebongio 
/assign @dims

apimachinery annual report for 2020

---

contributors/devel/sig-instrumentation/instrumentation.md

We don't allow the use of prometheus directly anymore, let's update the docs to reflect that.

Update instrumentation.md with current information

---

mentoring/programs/shadow-roles.md

/cc @parispittman 
/assign @johnbelamaric

Add PRR to shadow programs

---

contributors/devel/sig-testing/e2e-tests.md

Adds docs to debug an e2e test with delve
Ref: https://github.com/kubernetes/kubernetes/pull/100205

Add docs about debugging an e2e test with delve

---

sig-scalability/configs-and-limits/provider-configs.md

🐳 Link to clusterloader2, and new docs repo of etcd.

---

sig-cli/annual-report-2021.md

Fixes #5499 
/cc @seans3 @pwittrock @eddiezane

SIG CLI Annual 2021 Report

---

sig-usability/annual-report-2021.md

Signed-off-by: Tasha Drew <tasha.drew@gmail.com>
Fixes #

SIG Usability 2021 annual report

---

communication/slack-config/channels.yaml

- Creates autoscaling-api slack channel
- This is for the autoscaling working group for coordinating the graduation of v2beta2 autoscaling APIs to GA for the 1.22 release.
Fixes #5750

Slack Channel Addition

---

communication/zoom-guidelines.md

Fixes two broken links in Zoom guidelines
* Fixes link to youtube guidelines
* Fixes link to kubernetes code of conduct
N/A

Fix links from Zoom guidelines

---

contributors/devel/sig-node/cherry-picks.md

/sig node
/cc @SergeyKanzhelev @hasheddan

Add SIG Node cherry-pick guide

---

sig-node/CONTRIBUTING.md

Adding contributing.md guide for sig-node group.

add contributing guide for sig-node

---

sig-ui/annual-report-2021.md

SIG-UI's Annual Report WIP
Addresses #5516
Steering Liason
/assign @nikhita 
/cc @maciaszczykm @floreks

SIG-UI 2021 Annual Report

---

sig-architecture/annual-report-2021.md

Fixes #5496
/assign @dims @derekwaynecarr 
/cc @liggitt

SIG Architecture 2021 Annual Report

---

contributors/devel/sig-storage/flexvolume.md

Fix a typo in the doc

---

communication/moderators.md

rawkode-youtube-mod

---

events/community-meeting.md

Update the Zoom link on the Community Meeting page with the link from the published agenda.

update the zoom link on the community meeting page

---

contributors/devel/sig-instrumentation/OWNERS

Add serathius to devel reviewers and approvers

---

contributors/devel/sig-instrumentation/migration-to-structured-logging.md

Signed-off-by: JunYang <yang.jun22@zte.com.cn>
Fixes #https://github.com/kubernetes/kubernetes/issues/102353

Support setting depth to structured logging

---

communication/slack-config/sig-release/usergroups.yaml
communication/slack-config/users.yaml

ref: https://github.com/kubernetes/sig-release/pull/1564, https://github.com/kubernetes/sig-release/issues/1567
cc: @kubernetes/release-engineering @kubernetes/sig-release-leads 
/assign @saschagrunert @hasheddan @puerco @cpanato

slack-config: Update SIG Release user groups

---

contributors/devel/sig-architecture/api_changes.md

Explain use of feature labels for alpha and beta releases

---

sig-security/security-audit-2021/RFP.md

This PR updates the 2021 RFP with additional questions and replies from the subproject group

Update 2021 RFP with additional questions

---

sig-autoscaling/annual-report-2021.md

SIG Autoscaling Annual Report 2021

---

sig-autoscaling/annual-report-2020.md

N/A - Follow-up to #5614 and #5817 as per https://github.com/kubernetes/steering/pull/209#pullrequestreview-675629273

Rename SIG Autoscaling report to match calendar year

---

sig-network/annual-report-2021.md

Fixes https://github.com/kubernetes/community/issues/5506
This PR is currently a template with no questions yet answered, intended to
be a forum for open discussion before codifying the results.

Add SIG network 2021 annual report

---

sig-cluster-lifecycle/README.md
sigs.yaml

Changed the link from the [2020 notes](https://docs.google.com/document/d/1LW5SDnJGYNRB_TH9ZXjAn2jFin6fERqpC9a0Em0gwPE/edit) to the [2021 notes](https://docs.google.com/document/d/1LdooNTbb9PZMFWy3_F-XAsl7Og5F2lvG3tCgQvoB5e4/edit).

Updated cluster-api meeting notes link for 2021

---

sig-architecture/README.md
sigs.yaml

- fix link to KEP process
- fix anchor links

Fix KEP process link

---

contributors/devel/sig-architecture/feature-gates.md

Taking this over from @dims via #5545 
Partially updated based on outstanding comments, will iterate shortly in the next day or so. 😄 Wanted to update to get the new PR up so that conversation can move here.
Fixes #5542

sig-arch: Working with feature gates doc

---

sig-network/annual-report-2020.md

2021 -> 2020 to conform with the other reports.

sig network: rename annual report to conform with standard

---

contributors/devel/sig-instrumentation/migration-to-structured-logging.md

Signed-off-by: JunYang <yang.jun22@zte.com.cn>
Fixes [#102557](https://github.com/kubernetes/kubernetes/issues/102557)

Document structured logging contribution process

---

contributors/guide/owners.md
generator/app.go

fix some typos in the docs and the comments

---

sig-security/security-audit-2021/RFP.md

The fourth proposal for the third-party security audit was received on 2021/06/22.
This PR sets the RFP closing date and vendor selection.

Update RFP with closing date

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

- removes no longer active members (@adisky)
- adds recently joined members (@feloy) and  QE (@anandrkskd @rnapoles-rh)

update odo-devs slack group

---

committee-code-of-conduct/governance/onboarding-offboarding.md
communication/moderation.md
sig-contributor-experience/README.md
sig-node/archive/meeting-notes-2020.md
sig-wg-lifecycle.md
sigs.yaml
wg-k8s-infra/annual-report-2020.md

Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
Needed for kubernetes/k8s.io#1597

replacing master with main for k/k8s.io links

---

sig-scalability/configs-and-limits/provider-configs.md

Ref. kubernetes/perf-tests#1110
/assign @wojtek-t

Add information for containerd being CRI of choice for SIG Scalability

---

contributors/guide/pull-requests.md

Typos and other punctuation fixes

---

github-management/kubernetes-repositories.md

Added sections detailing maintenance mode, its roadmap, and how-tos

Adding section about Maintenance mode

---

sig-node/CONTRIBUTING.md

Update the link in sig-node/CONTRIBUTING.md

---

events/community-meeting.md

Updating the community meeting documentation to match the new format.

Update community meeting doc with new information

---

contributors/devel/sig-architecture/api_changes.md

Also add guidance on how to structure commits when doing API promotions.

Update steps on how to make a new API version

---

mentoring/processes/group-mentoring.md
mentoring/programs/leads-curriculum.md

/assign @parispittman 
/area mentorship-planning

Add curriculum outline for leads program

---

sig-contributor-experience/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/2589
/cc @jberkus @coderanger

sig-contribex: Add lwkd repo

---

contributors/devel/sig-instrumentation/instrumentation.md

Re: https://github.com/kubernetes/kubernetes/issues/104008

amend instrumentation cardinality guidelines to explicitly advise against using namespaces

---

communication/slack-config/channels.yaml
sig-cluster-lifecycle/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/2824
/cc @neolit123

SCL: Remove booktube subproject

---

sig-windows/README.md
sigs.yaml

Fixes https://github.com/kubernetes/org/issues/2721
/assign @jayunit100 
cc @sladyn98 
/hold
for lgtm from a sig-windows lead

sig-windows: add sig-windows-dev-tools repo

---

sig-cloud-provider/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/2804
/cc @spzala

sig-cloud-provider: Add ibm-vpc-block-csi-driver repo

---

contributors/devel/sig-node/OWNERS
sig-node/OWNERS

/kind cleanup
/sig node
I would like to propose myself as an approver for the SIG Node as I have been active in reviewing and maintaining docs and meetings
/assign @dchen1107 @derekwaynecarr

Propose SergeyKanzhelev as node approver

---

sigs.yaml
wg-structured-logging/README.md
wg-structured-logging/charter.md

/cc @dims @shubheksha @thockin 
@kubernetes/steering-committee

Add charter for WG Structured Logging

---

contributors/guide/github-workflow.md

To be consistent with the example code (`squash`) below.
https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md#L204

Update `git squash` doc

---

community-membership.md

Improve links to create community membership

---

sig-docs/meeting-notes-archive/2020_Weekly_Meeting_Minutes.md

Updating the meeting minutes archive for 2020 as we juggle around our meeting g-doc.
/cc @sftim @parispittman

adding SIG Docs 2020 meeting minutes

---

sig-security/README.md
sig-security/sig-security-tooling/OWNERS
sigs.yaml

Record keeping updates for sig-security-tooling:
- Added OWNERS file
- Updated sigs.yaml
- Generated README.md from sigs.yaml
/sig security
/assign @IanColdwater @tabbysable

Record-keeping updates related to sig-security-tooling 

---

sig-security/security-audit-2021/RFP.md

This PR updates the vendor selection date for the RFP for the third party security audit 
/cc @aasmall 
/assign @tabbysable @IanColdwater

Update RFP vendor selection date

---

sig-auth/CONTRIBUTING.md

Fixes #5760 
As part of this PR, we are adding a new CONTRIBUTING.md under sig-auth

Add CONTRIBUTING.md under SIG Auth

---

sig-contributor-experience/charter.md

Updated mailing list of sig-leads in community/sig-contributor-experience/charter.md 
Fixes #5976

Update mailing list of sig-leads

---

sig-security/sig-security-external-audit/external-audit-roadmap.md

Past external security audits have not been comprehensive of the entire Kubernetes project.
This PR creates a roadmap that lists previously audited focus areas and focus areas requested to be included in future audits.

Initial External Security Audit Roadmap

---

sig-contributor-experience/charter.md

Broken links on SIG-Contribex Charter

---

wg-data-protection/OWNERS

This PR adds OWNERS file for wg-data-protection.
Fixes https://github.com/kubernetes/org/issues/2914

Add OWNERS file to wg-data-protection

---

communication/marketing-team/role-handbooks/storytellers.md

Updated workflow

---

communication/slack-config/sig-release/usergroups.yaml

/kind cleanup
update the link to the current release cycle
Fixes #
None
/assign
/sig release
/assign @justaugustus @saschagrunert @jeremyrickard @cpanato @puerco
/cc @JamesLaverack @jrsapi @mkorbi @MonzElmasry

slack-config/sig-release: update link for current release cycle 1.23

---

contributors/devel/sig-architecture/api-conventions.md

Add a note re the behavior of automatically allocating/releasing resource and the related validation.

Auto resource release based on api changes

---

contributors/devel/sig-architecture/api_changes.md

Based on Service ClusterIPs pluralization.
cc @liggitt 
cc @khenidak 
cc @aojea 
xref https://github.com/kubernetes/enhancements/pull/2661

Update API pluralization docs

---

sig-security/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/2923
/assign @tabbysable @IanColdwater

sig-security: Add sig-security repo subproject

---

github-management/default-branch-migration.md

Sneak in a link to the umbrella issue to allow tracking there when people copy the checklist into an issue in their repository.
@nikhita

docs: update default-branch-migration.md

---

communication/marketing-team/storytelling-resources/example-topics.md

Adding another helpful question.
Fixes #5816

Add note about help-wanted issues

---

contributors/devel/sig-release/cherry-picks.md

N/A - just updating a link to its new home.

Update doc link to active release branches

---

contributors/devel/sig-release/cherry-picks.md

We were doing this already, but wanted to make sure we write it down so it's easier for reviewers to point to something written down.
(nudged by discussion in https://github.com/kubernetes/kubernetes/pull/105011)
Fixes #

Update cherry picks doc with a description for alpha features

---

sig-release/README.md
sigs.yaml

Part of https://github.com/kubernetes-sigs/promo-tools/issues/424.

sig-release: Update Release Engineering OWNERS references

---

communication/slack-config/channels.yaml

We are retiring wg component standard, hence archiving the related slack channels
Related to #6039 

Archive the #wg-component-standard channel

---

communication/slack-config/channels.yaml

Add capi-ibmcloud channel

---

sig-node/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/2847

sig node: remove frakti project

---

communication/moderators.md

Fixes #6033 
cc: @parispittman

Updated moderators.md

---

committee-security-response/README.md
sig-security/charter.md
sig-security/sig-security-external-audit/README.md
sigs.yaml

/sig security 
/hold for https://github.com/kubernetes/org/issues/2967

Replace k/security with k/committee-security-response in k/community/sig-security

---

sig-cluster-lifecycle/README.md
sigs.yaml

Add SCL CAPI kubevirt subproject
ref: https://github.com/kubernetes/org/issues/2925

sig cluster-lifecycle: Add capi kubevirt subproject

---

communication/moderators.md

added myself to moderators per the guidelines and group instruction.
Signed-off-by: Debabrata Panigrahi d.panigrahi.nitrkl@gmail.com
Related to #6032
cc @parispittman

Update moderators.md for K-dev

---

OWNERS_ALIASES
sig-windows/README.md
sigs.yaml

Signed-off-by: Mark Rossetti <marosset@microsoft.com>
Part of https://github.com/kubernetes/community/issues/6045

Swap Claudiu Belu with Deep Debroy as Windows TL

---

communication/slack-config/sig-network/config.yaml

Add slack channel for KPNG https://github.com/kubernetes-sigs/kpng in the open !

Add a KPNG announcements channel

---

sig-scalability/configs-and-limits/faq.md

/assign @mm4tt @marseel @mborsz @shyamjvs

Inception of SIG Scalability FAQ

---

contributors/guide/release-notes.md

The ["adding release notes page"](https://www.kubernetes.dev/docs/guide/release-notes/#applying-a-release-note) had unwanted text. This PR removes it. 
> Applying a Release Note
> 
> _slug: “adding-release-notes”_
> 
> On the kubernetes/kubernetes repository, release notes are required for any pull request with user-visible changes.

remove unwanted text

---

sig-scalability/configs-and-limits/faq.md
sig-scalability/configs-and-limits/provider-configs.md

/assign @marseel @mm4tt @mborsz @shyamjvs

Extend SIG scalability FAQ

---

events/elections/2021/templates/election-templates.md
events/elections/README.md

Add note to README that it contains outdated information.
attn: @alisondy @coderanger

Add template for candidate qualification announcement.

---

contributors/guide/non-code-contributions.md

Fix: Broken link on non-code-contributions

---

events/elections/2021/candidate-LachlanEvenson.md

Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
Fixes #6089

Add Steering Committee 2021 candidate: Lachlan Evenson

---

events/elections/2021/candidate-LachlanEvenson.md
events/elections/2021/nomination-template.md

Remove @ in candidate profiles, apparently causing a parse error.

---

events/elections/2021/candidate-LachlanEvenson.md

Removing more characters to fix the parse error

---

events/elections/2021/README.md

Fix Elekto link.

---

sig-contributor-experience/README.md

Add recent KubeCon deep dive video links to SIG contributor experience README.md

---

events/elections/2021/RESULTS.md

Publish results to the app.
Blog post and announcements will follow later.
/assign @coderanger @alisondy

Publish 2021 election results

---

sig-cluster-lifecycle/README.md
sigs.yaml

Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5506

Cluster API issue5506 - Links to owners files should be updated to use the main branch

---

sig-apps/README.md

Signed-off-by: Baiju Muthukadan <baiju.m.mail@gmail.com>

Update link to Helm proposal to be part of CNCF

---

contributors/devel/sig-architecture/feature-gates.md

Adds documentation on how we generally expect feature gates to work.
/assign @johnbelamaric @deads2k

Document expectations of feature gate use per PRR

---

sig-release/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/3106
/assign @justaugustus @saschagrunert @puerco @cpanato @jeremyrickard

sig-release: Add bom subproject

---

communication/slack-config/users.yaml

Signed-off-by: Daniel Jiang <jiangd@vmware.com>

Fix the slack ID for jiangd and yinw

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

cc @mattmoyer @ankeesler @pabloschuhmacher @anjaltelang @shamus

Update pinniped user group membership

---

sig-architecture/README.md
sigs.yaml

ref: #6055
ref: #6258 
/hold
For other PR to merge and owners in https://github.com/kubernetes/design-proposals-archive to be configured

sig-arch: Update design proposals location

---

communication/slack-config/sig-docs/docs-channels.yaml

Temporary channel to help coordinate the effort to update docs for the upcoming dockershim removal.
/cc @celestehorgan @SergeyKanzhelev 
/assign @jimangel @sftim @divya-mohan0209

Add dockershim slack channel

---

communication/moderators.md

Adding markyjackson-taulia to mods list

---

events/elections/2021/ballots.csv
events/elections/2021/ranking.md
events/elections/2021/results.md

Upload ballots and complete rankings for 2021 SC election.

---

committee-steering/governance/README.md

pedantic fix of typos, that were not even displayed when the markdown was rendered on GitHub
Fixes # n/a

committee-steering/governance/README.md: Typo fixes

---

contributors/guide/owners.md

Cleanup of inactive contributors from OWNERS files

---

sig-contributor-experience/meeting-notes-archive/2020-meeting-notes.md

/assign @mrbobbytables @alisondy

Archive the 2020 meeting notes.

---

contributors/guide/pull-requests.md

Reword the GitHub keywords usage in PR and commit messages to make sure the intent for use in PR and commit message are both clearly conveyed
https://kubernetes.slack.com/archives/CDHA7K9L5/p1635172467025600?thread_ts=1635170408.022400&cid=CDHA7K9L5

Reword github keywords usage in PR and commit messages

---

communication/OWNERS

Fixes #6279 
cc @parispittman @coderanger

Adding markyjackson-taulia to reviewers

---

contributors/devel/sig-node/updating-pause-images.md

Signed-off-by: kerthcet <kerthcet@gmail.com>
Fixes #https://github.com/kubernetes/kubernetes/issues/104890

add new repo related to pausing image reference

---

contributors/devel/sig-testing/flaky-tests.md

Fixes #6314
update stress installation command for go version 1.17

update stress installation command for go version 1.17 and later

---

contributors/devel/running-locally.md

Update local-up-cluster.sh doc to use CRI
Related to https://github.com/kubernetes/kubernetes/pull/106909

Update local-up-cluster.sh doc to use CRI 

---

communication/slack-config/OWNERS

Whoops we missed this forever ago.

Add DylanGraham as a Slack moderator and thus approver.

---

communication/slack-config/channels.yaml

See relevant discussion: https://kubernetes.slack.com/archives/C4M06S5HS/p1641263233066400?thread_ts=1641229254.066200&cid=C4M06S5HS

Add slack channel for Karpenter

---

committee-steering/governance/annual-reports.md

Fixes https://github.com/kubernetes/steering/issues/223

Add draft / publication dates for annual report

---

contributors/devel/sig-architecture/api-conventions.md

Add default tag to api conventions

Add default tag to api conventions

---

sig-k8s-infra/README.md
sigs.yaml

Fixes  https://github.com/kubernetes/org/issues/3143
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

sig-k8s-infra: ownership of oci-proxy

---

communication/slack-config/channels.yaml

Contributor count for https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2876-crd-validation-expression-language is growing and a dedicated slack channel would really help us keep everyone informed and involved.

Add sig-api-machinery-cel-dev channel

---

contributors/guide/owners.md

incorporate review comments from @smarterclayton in https://github.com/kubernetes/community/pull/6240/files#r783993513
Fixes #

Update language to make emeritus process clearer

---

communication/slack-config/channels.yaml

This is a bit too off-topic to discuss in the main node channel. We'd consider doing a synchronous zoom meeting, but we have a lot of global contributors which makes it difficult to schedule a workable time.
/sig node

Add slack channel for coordinating swap implementation

---

communication/marketing-team/CHARTER.md

fixed the marketing council links in charter.md

---

generator/liaisons.tmpl
liaisons.md

https://github.com/kubernetes/steering/issues/228

adding liaison expectations

---

generator/annual-report/github_issue.tmpl
generator/annual-report/sig_report.tmpl
generator/annual-report/wg_report.tmpl
generator/app.go

/assign @mrbobbytables @nikhita

Add generation function for annual report

---

contributors/chairs-and-techleads/README.md

adding more information to our leads documentation 
- meeting doc structure
- recognition 
- cleaned up communication section; added context where needed
- cleaned up formatting 
fixes #3708

adding recognition and cleaning up doc

---

generator/README.md
generator/annual-report/github_issue.tmpl
generator/annual-report/sig_report.tmpl

This adds some minor changes as well as README docs for the annual report generator
/cc @justaugustus

Annual Report generator followup

---

contributors/devel/sig-architecture/api-conventions.md

See https://github.com/kubernetes/community/issues/6041#issuecomment-1021176213
Fixes #6041 
/assign @liggitt

Note when PUT can create items

---

communication/slack-config/channels.yaml

Signed-off-by: Anish Ramasekar <anish.ramasekar@gmail.com>
We have group of folks working on kms enhancements in the upcoming releases as part of sig-auth. Creating this slack channel to collaborate. 
/sig auth
/cc @enj @ritazh

add sig-auth-kms-dev slack channel

---

communication/marketing-team/README.md

Related to #6399 
**Description**
Added a shadow under Marketing Council Promotional Lead

Add Debanitrkl as shadow for Marketing Council

---

sig-contributor-experience/meeting-notes-archive/2021-meeting-notes.md

Archive SIG Contributor Experience meeting notes from 2021

Archive 2021 Contribex Meeting Notes

---

contributors/guide/contributing.md

Fix broken links to learn about sigs in the contributor guide

---

mentoring/programs/group-mentee-guide.md

Typo fix: extra space character inserted

---

sig-cluster-lifecycle/README.md
sigs.yaml

- Adds slack channel for cluster-api-provider-packet subproject for sig-cluster-lifecycle

Update contact information for cluster-api-provider-packet

---

CLA.md

**Which issue(s) this PR fixes**: #6401
Updated the CLA documentation for the new EasyCLA process.

Updated: CLA.md

---

sig-testing/README.md
sigs.yaml

Fixes https://github.com/kubernetes/org/issues/3228
/assign @BenTheElder 
/hold
for lgtm from sig-testing lead

sig-testing: add prow repo

---

communication/moderators.md

add csantanapr as moderator for youtube

---

sig-contributor-experience/README.md
sigs.yaml

Fixed sig-contribex youtube link

---

sig-windows/CONTRIBUTING.md

Signed-off-by: Mark Rossetti <marosset@microsoft.com>
Fixes #6429

sig-windows contributing.md updates

---

communication/slack-config/channels.yaml

This PR adds a new Slack channel called `#kyverno-dev` to be used by the maintainers and contributors of the Kyverno CNCF project (kyverno.io). It will be used to coordinate development communication amongst maintainers and contributors leaving `#kyverno` to be user and broader community focused.

add kyverno-dev channel

---

communication/slack-config/channels.yaml

Based on https://github.com/kubernetes/community/tree/master/wg-batch
Ref #6263

Add slack channel for WG Batch

---

communication/slack-config/channels.yaml

per request of openshift/okd working group creating just a single channel for openshift-users
Fixes #

archiving openshift-dev; merging to openshift-user

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

Clean up & add new members to contributor-comms slack usergroup

---

sig-scalability/README.md

Update README for sig-scalability

Update README for sig-scalability

---

sig-contributor-experience/README.md
sigs.yaml

Fixes https://github.com/kubernetes/org/issues/3208
/hold
for another contribex lead to lgtm

sig-contribex: add maintainers repo

---

sig-scalability/CONTRIBUTING.md

Add CONTRIBUTING guide for sig-scalability.
Fixes #

Add CONTRIBUTING for sig-scalability

---

wg-data-protection/data-protection-workflows-white-paper.md

This PR addresses some review comments from PR https://github.com/kubernetes/community/pull/6306.

Update white paper

---

sig-windows/annual-report-2021.md

Signed-off-by: Mark Rossetti <marosset@microsoft.com>
Part of https://github.com/kubernetes/community/issues/6386
CONTRIBUTING.md was updated with https://github.com/kubernetes/community/pull/6433
/assign @jayunit100 @liggitt

sig-windows 2021 annual report operational tasks + fixing linting errors

---

sig-node/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/3140

sig-node: Add special-resource-operator subproject

---

contributors/devel/sig-architecture/conformance-tests.md

fixed a tiny typo error

---

sig-scalability/annual-report-2021.md

Fixes #6378
Initial draft for sig-scalability annual report.

Sig Scalability 2021 annual report

---

contributors/devel/development.md

Changed some mistakes in docs. Made bullet points instead of copy box.
Fixes #

Updated development.md

---

contributors/devel/sig-instrumentation/instrumentation.md
contributors/devel/sig-instrumentation/metric-stability.md

Addresses the first task in https://github.com/kubernetes/kubernetes/issues/108497
/cc @CatherineF-dev @logicalhan

Add metrics stability documentation from KEP-1209

---

sig-contributor-experience/README.md
sigs.yaml

Update events subproject slack channel in sigs.yaml

---

wg-data-protection/data-protection-workflows-white-paper.md

Data Protection White Paper: Formatting fix under 'Desirable Characteristics of Volume Backups'

---

sig-contributor-experience/annual-report-2021.md

2021 Annual Report for SIG Contributor Experience.
See #6370 for more details.

SIG Contribex 2021 Annual Report

---

sig-storage/annual-report-2021.md

SIG Storage annual report 2021

---

sig-testing/annual-report-2021.md

Fixes #6383 
/cc @BenTheElder @aojea 

Add sig-test 2021 annual report

---

wg-structured-logging/annual-report-2021.md

cc @pohly @dims 
Fixes #https://github.com/kubernetes/community/issues/6393

Update WG Structured logging 2021 annual report

---

sig-cluster-lifecycle/annual-report-2021.md

xref https://github.com/kubernetes/community/issues/6369

2021 Annual Report: SIG Cluster Lifecycle

---

sig-cli/annual-report-2021.md

Fixes https://github.com/kubernetes/community/issues/6367

Add 2021 SIG-CLI Annual Report

---

communication/slack-config/channels.yaml

Fixes #
Ref: https://kubernetes.slack.com/archives/C010097GJLE/p1648807287255479

Archive raksh channel

---

communication/youtube/youtube-guidelines.md

This updates the YouTube guidelines with feedback from the community and formatting changes to make it match the Markdown style guidelines.
Co-authored-by: Aaron Epperson <aaron@aaronepperson.com>
-------
Fixes #

Update the YouTube guidelines

---

wg-data-protection/annual-report-2021.md

DP WG annual report 2021

---

sig-scheduling/README.md
sigs.yaml

Related to:
- https://github.com/kubernetes/org/issues/3262
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

Retire poseidon from sig-scheduling

---

sig-release/README.md
sigs.yaml

I am now working at Microsoft so this PR updates my company in `sigs.yaml` and regens the sig-release/README.md
/sig release
Signed-off-by: Jeremy Rickard <jeremyrrickard@gmail.com>

Update jeremyrickard company affiliation

---

mentoring/programs/mentoring-lead.md

Added the mentoring lead handbook for 3rd party mentorship programs

---

sig-docs/annual-report-2021.md

Amended the formatting for bullet points in the Operational section
Fixes #

Formatting the annual report for SIG Docs

---

sig-multicluster/README.md
sigs.yaml

SIG Multicluster: Remove kubemci subproject

---

communication/slack-config/channels.yaml

Flatcar Container Linux is a fully open source, minimal-footprint, secure by default and always up-to-date Linux distribution for running containers at scale.
https://www.flatcar.org/
Flatcar has many users in the cloud native community, using Flatcar as their OS of choice to run Kubernetes. Our maintainers actively participate in multiple cloud native projects (e.g. image-builder, CAPI, and several CAPI providers).
Flatcar CC: @ahrkrak @jepio @vbatts @pothos @tormath1 @miao0miao
Kubernetes / cloud native CC: @dims @codenrhoden

slack config: add Flatcar channel

---

contributors/guide/README.md

Adding kubernetes.io hyperlink to Getting Started

---

mentoring/programs/mentoring-lead.md

Updated few suggested changes in the already merged pr #6570 
/assign @nikhita @parispittman

Added follow-up changes to Internship Mentoring Lead Handbook

---

communication/moderators.md
communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

Updating the youtube moderator list/slack handle to reflect current moderators

Update YouTube moderator list

---

communication/slack-guidelines.md

[Issues 6606] Add updated slack-guidelines for moderators

---

sig-cloud-provider/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/3379

SIG Cloud Provider: Add azurelustre-csi-driver repo

---

sig-instrumentation/README.md
sigs.yaml

Part of https://github.com/kubernetes/org/issues/3356

sig-instrumentation: add logtools OWNERS

---

communication/slack-config/usergroups.yaml

Moderator's file was updated to add Nigel as Zoom admin, but Slack group was not updated.
Fixes #

Add Nigel to Zoom Admin List

---

sig-ui/annual-report-2021.md

Annual report 2021 for SIG UI.
Fixes #6384

SIG UI Annual Report 2021

---

sig-testing/README.md
sigs.yaml

Related:
- https://github.com/kubernetes/org/issues/3432
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>\

sig-testing: remove k8s-gsm-tools

---

communication/slack-config/channels.yaml

apko is a free and open source software tool for building container images
using apk, the package manager most typically used in Alpine Linux.
Signed-off-by: Ariadne Conill <ariadne@chainguard.dev>

slack-config: add apko channel

---

communication/slack-config/channels.yaml

feat: Introduce channel for docs on KEDA

---

github-management/setting-up-cla-check.md

Fix plugins.yaml reference link

---

contributors/guide/contributing.md

- Fix invalid link to the "Opening a Pull Request" section

Fix link in contributing.md

---

communication/slack-config/channels.yaml

Hi,
We'd like to add a channel to the Slack for the open source vcluster project. vcluster is a tool for creating and managing virtual Kubernetes clusters.
The GitHub page for the project is: [https://github.com/loft-sh/vcluster](https://github.com/loft-sh/vcluster)
Thank you.

add Slack channel for the vcluster project

---

communication/marketing-team/role-handbooks/storytellers.md

Fixes #6731 the correct link for the council markdown document

Add correct link for council.md

---

sig-scalability/configs-and-limits/faq.md

Add SIG Scalability FAQ about object sizes

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

Update pinniped user group

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

This commit updates the members for "velero-maintainers" to reflect the
change in maintainers of project velero
Signed-off-by: Daniel Jiang <jiangd@vmware.com>

Update velero-maintainers group

---

communication/slack-config/channels.yaml

Adding an `Eraser` channel to K8s slack. This is an open source project that exists solely to be run on Kubernetes clusters to help with cluster administration. Adding the channel to create a community space for development and contribution discussion.
https://github.com/Azure/eraser
(The project will soon be moved out of the Azure org. We do not want to create the impression that this is a Microsoft owned project. There are contributors outside of Microsoft, and it is very much a community owned project)

Add Eraser channel to Slack

---

communication/moderation.md

[Moderation] CoC escalation procedures for  mods

---

sig-storage/volume-plugin-faq.md

also removed two dead links
Fixes #

update status on plugin CSI migration

---

elections/steering/2022/README.md

Draft schedule for review by EOs.

📝 Proposed 2022 election schedule.

---

communication/slack-config/channels.yaml

Rename Slack channel #kcp-prototype to #kcp-dev
Fixes #

Rename #kcp-prototype to #kcp-dev

---

code-of-conduct.md

Update the link that references to [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

Update the branch name from master to main

---

contributors/devel/sig-architecture/api_changes.md

Signed-off-by: tianyang ni tianzong48@gmail.com
/kind cleanup documentation

devel: fix/update script path in api_changes.md

---

elections/steering/2022/README.md

🎨 Update the elegibility snapshot date to match this year's election timeline

---

elections/steering/2022/README.md
elections/steering/2022/election.yaml
elections/steering/2022/election_desc.md
elections/steering/2022/nomination-template.md
elections/steering/2022/templates/election-templates.md

Add the election.yaml used by elekto and the nomination template as well for 2022 Steering Election

Prep info for election process including elekto

---

contributors/devel/sig-architecture/object-lifecycle.md

Emphasis on "DELETING" as a distinct state.  I keep finding controllers
which do not handle it at all.

Add a short developer doc on object lifecycle

---

elections/steering/2022/election_desc.md

Also drop the ':' at the end of the line
/assign @jberkus

highlight schedule by moving it to another line

---

elections/steering/2022/election_desc.md

Fix 2022 steering election exception URL

---

elections/steering/2022/voters.yaml

🎨 Add CoCC 2022 members.

---

elections/steering/2022/templates/election-templates.md

Fix voters.yaml url

---

elections/steering/2022/README.md

Fix email address of the k-dev mailing list

---

elections/steering/2022/README.md

Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>
cc: @dims @kaslin @coderanger

update dev@ mailing list address

---

events/awards/playbook.md

This PR updates the awards playbook with additional suggestions on how the community can be involved with awards and how SIGs can model awards to their own needs/goals.

Update awards playbook

---

events/awards/award-recipients/2020-award-recipients.md

Fix misspelled name

---

elections/steering/2022/election_desc.md

📝 Also fix number of seats in Elekto.

---

community-membership.md

Pull Request changed to 2 words
Capitalized Hub in GitHub

Fixed 2 Typos

---

elections/steering/2022/templates/election-templates.md

Add the rest of the email templates for 2022 steering election

---

communication/slack-config/channels.yaml

This PR adds multi-network channel where community will discuss on introducing multi network concept and a Network construct into Kubernetes.
Fixes #6751

Add multi-network channel.

---

elections/steering/2022/README.md

/assign @coderanger @kaslin 
Fixes #

Pencil in the date for Steering Q&A

---

elections/steering/2022/voters.yaml

🎨 Add voters from exception requests.

---

communication/slack-config/channels.yaml

Proposal for new channel dedicated to discussion of AWS Controllers for Kubernetes 
https://aws-controllers-k8s.github.io/community/

Update channels.yaml to add ACK

---

communication/slack-config/channels.yaml

Signed-off-by: Austin Macdonald <austin@redhat.com>

Add Operator Framework community channel for outreach and planning 

---

sig-testing/README.md
sigs.yaml

Update the branch name from master to main in the url of OWNERS of sub-projects e2e-framework and kind in sig testing.

Update sig-testing README.md

---

elections/steering/2022/candidate-deads2k.md

fixes https://github.com/kubernetes/community/issues/6824

Steering Commitee Candidate: David Eads

---

elections/steering/2022/candidate-lavalamp.md

Steering Committee Candidate: Daniel Smith

---

elections/steering/2022/candidate-cpanato.md

Fixes: https://github.com/kubernetes/community/issues/6800

Steering Commitee Candidate: Carlos Panato

---

elections/steering/2022/candidate-palnabarun.md

Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>
Fixes #6831

Add palnabarun candidate bio for 2022 steering elections

---

elections/steering/2022/nomination-qedrakmar.md

Add steering election bio for Noah Abrahams

---

elections/steering/2022/candidate-bentheelder.md

Add steering candidate bio for bentheelder

---

elections/steering/2022/candidate-cici37.md

Add steering candidate bio for cici37

---

elections/steering/2022/candidate-mrbobbytables.md

Add mrbobbytables 2022 steering election bio

---

elections/steering/2022/candidate-bentheelder.md
elections/steering/2022/candidate-mrbobbytables.md
elections/steering/2022/voters.yaml

🎨 Election update stuff

---

communication/slack-config/sig-release/usergroups.yaml
communication/slack-config/users.yaml

Signed-off-by: leonardpahlke <leonard.pahlke@googlemail.com>
Update release team leads, see onboarding issue: https://github.com/kubernetes/sig-release/issues/2006
None
/cc @palnabarun @saschagrunert

Update RT leads group in slack

---

elections/steering/2022/voters.yaml

🎨 Update voter exceptions.

---

contributors/guide/pull-requests.md

Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #6868

updated contributors/guide/pull-requests.md

---

contributors/guide/contributor-cheatsheet/README.md

Fix broken link for testing locally on contributor-cheatsheet page

---

contributors/devel/sig-node/node-performance-testing.md

/cc @SergeyKanzhelev 
/sig node
Updates node performance testing doc with the current status. Add information about k8s performance dashboard.
Fixes the doc for the error encountered while running the tests.
Fixes #

Update node perf testing doc

---

sig-storage/volume-plugin-faq.md

Update info about Flexvolume

---

sig-auth/README.md
sigs.yaml

Related:
- https://github.com/kubernetes/org/issues/3630
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

sig-auth: add kms staging repo

---

sig-windows/CONTRIBUTING.md

Signed-off-by: Mark Rossetti <marosset@microsoft.com>
Fixes #

Updating links for SIG-Windows project boards

---

communication/marketing-team/storytelling-resources/blog-guidelines.md

Reflect how the first PR should be made on the contributor-site.
Fixes #

Update instructions for blog PRs

---

contributors/devel/sig-architecture/conformance-tests.md

Fix typos in the conformance-tests doc

---

communication/marketing-team/storytelling-resources/social-guidelines.md

Fix broken Charter link

---

contributors/chairs-and-techleads/README.md

Found typos, incorrect article usage
Changed "Place" to "A place" -> missing a determiner before it fixed
Changed "Recogition" to "Recognition" -> typo fixed
Changed "commuity" to "community " -> typo fixed
Changed "list and slack" to "list and the slack" added a article

Fixed accidence in (chair and techleads readme)

---

communication/slack-config/channels.yaml

An on cluster general purpose constraint/SAT solver for Kubernetes dependencies. This project is a part of the Operator Lifecycle Manager subproject of the Operator Framework

Add deppy-dev slack channel

---

elections/steering/2022/ballots.csv
elections/steering/2022/results.md

That's a wrap folks! Congrats to the new steering members.

Results for 2022 Steering Elections

---

communication/slack-config/channels.yaml

**Which issue(s) this PR fixes**: N/A
Proposal for new channel dedicated to discussion of AWS VPC CNI - https://github.com/aws/amazon-vpc-cni-k8s

Update channels.yaml to add AWS VPC CNI

---

communication/slack-config/channels.yaml

A channel to discuss Azure Service Operator
See: https://azure.github.io/azure-service-operator/ and https://github.com/Azure/azure-service-operator

Update channels.yaml to add azure-service-operator

---

mentoring/processes/group-mentoring.md

adding clarity and steps for group mentoring coordinators 
/area mentorship-planning

adding more instructions for group mentoring coordinators 

---

communication/slack-config/channels.yaml

Slack channel for https://github.com/kube-bind/kube-bind

slack-config: add kube-bind channel

---

communication/slack-config/usergroups.yaml

Name change PR'd into community.
Fixes # N/A

upstream-marketing is now contributor-comms

---

communication/slack-config/channels.yaml

As requested by Tanzu team.
Fixes #

🔥 Archive tanzu community channel

---

sig-release/README.md
sigs.yaml

Ref:
- https://github.com/kubernetes/org/issues/3656
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

sig-release: add tejolote repo

---

sig-network/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/3731

sig-network: Add ingress2gateway repo

---

communication/OWNERS
communication/contributor-comms/OWNERS
communication/slack-config/OWNERS
communication/youtube/OWNERS
contributors/guide/OWNERS
elections/steering/OWNERS
events/OWNERS
mentoring/OWNERS

practicing what I preach :) it's been fun.
several things need to happen before we merge this:
- change me as owner on slack to the contribex account: changed to main contribex googlegroup
- removal from slack admins private channel - done
- another PR to the mailing list config removing me from groups there - PR https://github.com/kubernetes/k8s.io/pull/4423/files 
/hold

adding myself as emeritus in OWNERs files

---

contributors/devel/development.md
governance.md

Update to maintain GitHub style guide

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

This PR adds a slack user group for the Cluster API release team.
Fixes #

User group for Cluster API release team

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

This PR adds new member to the `cluster-api-release-team` slack alias.
Fixes #

add joekr to cluster-api-release-team slack alias

---

communication/contributor-comms/README.md

Updating roles and removing "marketing council" concept.

Update Roles in README.md

---

contributors/guide/contributing.md

In some bullet points there were words where first character wasn't in uppercase and in some they were. Fixed the inconsistency.

Fixed inconsistent first character capitalization.

---

sig-cluster-lifecycle/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/3836

sig-cluster-lifecycle: Add minikube-gui repo

---

communication/slack-config/channels.yaml

Request to add a Slack channel, which will focus on Velero Data Mover design, developing and future supporting topics.
Signed-off-by: Xun Jiang <jxun@vmware.com>
Fixes #

Request for adding a Slack channel to focus on Velero Data Mover.

---

sig-node/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/3837

sig-node: Add dra-example-driver repo

---

sig-instrumentation/README.md
sigs.yaml

sig-instrumentation: add usage-metrics-collector

---

sig-storage/README.md
sigs.yaml

ref https://github.com/kubernetes/org/issues/3378

Remove retired repos for sig-storage

---

communication/slack-config/channels.yaml

Signed-off-by: Monis Khan <mok@microsoft.com>

Add triage channel for SIG Auth

---

communication/slack-config/channels.yaml

Add new Slack channel for Koordinator, which is a QoS based scheduling system for hybrid orchestration workloads on Kubernetes.
- Website: https://koordinator.sh/
- Github: https://github.com/koordinator-sh/koordinator
This channel would be a place for the community discussion, release announcements and so on. Thanks!
Fixes #6954

Add new Slack channel for Koordinator

---

communication/slack-config/sig-release/usergroups.yaml
communication/slack-config/users.yaml

Update SIG release slack groups for 1.27 release
None

update sig-release config for 1.27 release

---

CLA.md

Fixes to `email` from `e-mail` which is a continuous occurrence

Update with similar style

---

sig-windows/README.md
sigs.yaml

Fixes https://github.com/kubernetes/org/issues/3888
/assign @marosset 
/hold
for a lgtm from a sig-windows lead

sig-windows: add windows-service-proxy repo

---

sig-scalability/configs-and-limits/faq.md

Adds a section to FAQ to provide general guidance on how to avoid creating excessive LISTing load when writing K8s apps.

Add FAQ section on how to avoid excessive LIST load when writing apps

---

communication/slack-config/channels.yaml

Fixes #
Looking to foster collaboration for https://karpenter.sh/v0.20.0/contributing/working-group/

chore: add karpenter-dev channel for karpenter contributors

---

sig-cluster-lifecycle/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/3762

sig-cluster-lifecycle: Add cluster-api-addon-provider-helm repo

---

sig-network/role-sig-chair.md

/assign caseydavenport
/assign dcbw
/cc @aojea

Add sig-net description of sig-chair role

---

contributors/guide/README.md

Fix typos in contributors/guide/README.md

---

communication/contributor-comms/OWNERS

Updating OWNERS based on roles

---

committee-code-of-conduct/README.md
sigs.yaml

Not sure why I was forgotten given I was a founding member.

Add Eric Paris to Emeritus

---

sig-contributor-experience/meeting-notes-archive/2022-meeting-notes.md

Archive the old notes.
attn: @mrbobbytables

Archive 2022 ContribEx meeting notes

---

communication/slack-config/channels.yaml

add slack channel for k8s-image-swapper

---

elections/steering/2023-GB/candidate-cblecker.md
elections/steering/2023-GB/candidate-justaugustus.md

in order to figure out the issue.

Tinkering with formatting on 2023-GB election

---

elections/steering/2023-GB/election.yaml

Fix election end date

---

elections/steering/2023-GB/ballots.csv
elections/steering/2023-GB/results.md

Election Results
/assign @jberkus

Add 2023 GB Election results

---

OWNERS
generator/annual-report/github_issue.tmpl

Automatically adds labels for annual reports and charter changes

Add automatic labelling for annual reports and charter changes

---

sig-multicluster/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/3841

sig-multicluster: add sig-multicluster-site repo

---

sig-storage/CONTRIBUTING.md

Additional presentations for 2022 and the PV controller slides

---

communication/slack-config/sig-security/config.yaml

Adding this slack channel for coordinating and performing the vSphere CSI Driver self asessment!
Fixes #

Add Slack Channel - vSphere CSI Driver assessment

---

communication/contributor-comms/OWNERS
communication/contributor-comms/README.md

Add: Atharva-Shinde to contributor-comms OWNERS

---

communication/slack-config/channels.yaml

Signed-off-by: Atulpriya Sharma <sharma.atulpriya@gmail.com>
Adding Paralus to Kubernetes slack as it was inducted as a CNCF sandbox project.
Reference: https://github.com/cncf/toc/issues/973

Adding Paralus to K8s Slack

---

sig-cluster-lifecycle/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/3995
/assign @vincepri 
/hold
for lgtm from at least one sig-cluster-lifecycle lead

sig-cluster-lifecycle: add logical-cluster repo

---

contributors/devel/sig-node/e2e-node-tests.md

**Which issue(s) this PR fixes**: N/A

Update node e2e docs

---

contributors/devel/development.md

**Which issue(s) this PR fixes**: 
Fixes #6888

Update docs: recommend setting DBG instead of GOGCFLAGS to make in debug mode

---

communication/contributor-comms/role-handbooks/Social-Media.md

FIX: Typos in Comms social media role-handbook

---

generator/README.md
generator/annual-report/github_issue.tmpl

A couple more fixes for the GH issue template

Update issue template for annual reports

---

communication/zoom-guidelines.md

Fixed reference link for community meeting

---

OWNERS_ALIASES
sig-cluster-lifecycle/README.md
sigs.yaml

Promote CecileRobertMichon as SIG Cluster Lifecycle Lead

---

communication/slack-config/channels.yaml

Add kwok slack channel

---

communication/slack-config/channels.yaml

Requesting konveyor-dev channel to direct all active development Konveyor project collaborations and comms. Thanks in advance.

Requesting konveyor-dev channel

---

sig-k8s-infra/README.md
sigs.yaml

Ref:
- https://github.com/kubernetes/org/issues/4054

sig-k8s-infra: Add community-images repo

---

sigs.yaml
wg-batch/README.md

Update Working group Batch Youtube playlist link.
Signed-off-by: Swati Sehgal <swsehgal@redhat.com>

wg-batch: Update the youtube playlist link

---

sig-testing/README.md
sigs.yaml

Ref:
- https://github.com/kubernetes/org/issues/4052

sig-testing: Add cloud-provider-kind repo

---

communication/slack-config/sig-docs/docs-channels.yaml

This is a PR to request a new slack channel for Tamil

Add a channel for Tamil(ta) docs

---

communication/slack-config/sig-release/usergroups.yaml

Related issue: https://github.com/kubernetes/sig-release/issues/2152
/hold until https://github.com/kubernetes/sig-release/pull/2156 merges.
/assign @jeremyrickard
/cc https://github.com/orgs/kubernetes/teams/release-managers
/milestone v1.27
/priority important-soon

releng: Update release-managers Slack user group

---

contributors/devel/sig-node/e2e-node-tests.md

add info on debugging e2e node tests

---

communication/slack-config/channels.yaml

For discussion around new authentication features such as https://kep.k8s.io/3331

Add sig-auth-authenticators-dev slack channel

---

sig-instrumentation/annual-report-2022.md

annual report for SIG Instrumentation for 2022

---

contributors/devel/sig-node/container-runtime-interface.md

Fixes #7206
Updated the link to point to correct location

Fixed Broken link to api.proto

---

contributors/guide/contributor-cheatsheet/README.md

Fixes #7191 
added new contributor course to the helpful resources section of this cheatsheet!

added contributor course link to helpful resources

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

This PR updates the slack user group for the Cluster API release team.
Fixes #

Update the user group for Cluster API release team

---

contributors/devel/sig-architecture/api_changes.md

These pointers may help developers who are new to the code.

api changes: document how to support `kubectl get`

---

contributors/devel/sig-architecture/api_changes.md

Try to avoid in the future the confusion that motivated https://github.com/kubernetes/kubernetes/pull/116566.
/cc @msau42 
/cc @liggitt

Clarify fuzzer operation

---

sig-storage/annual-report-2022.md

Fixes #7116
cc @saad-ali @msau42 @jsafrane

Add 2022 sig-storage annual report

---

wg-batch/annual-report-2022.md

Fixes #7122
/cc @Huang-Wei @ahg-g @endocrimes @swatisehgal 

WG Batch Annual report 2022

---

sig-ui/annual-report-2022.md

Annual report 2022 for SIG UI.
Fixes #7118

SIG UI Annual Report 2022

---

sig-api-machinery/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4146

Add cel-admission-webhook subproject

---

sig-multicluster/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4122

Remove kubefed subproject

---

events/events-team/registration/README.md

Add missing org member query to reg playbook

Add org member cmd for reg playbook

---

sig-cli/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/pull/4182
/area github-repo

Add kubectl-validate subproject

---

contributors/guide/coding-conventions.md

Update Shell Style Guide link and text

---

sig-scalability/annual-report-2022.md

@shyamjvs @marseel @kubernetes/sig-scalability 
/cc @mrbobbytables @

SIG Scalability annual report 2022

---

contributors/guide/pull-requests.md

Fixes #7008 
A suggestion based on my experience of seeing such PRs linger unreviewed...

Add a section to the pull-request docs about giant multi-SIG PRs

---

sig-autoscaling/annual-report-2022.md

SIG Autoscaling - 2022 Annual Report

---

sig-cluster-lifecycle/annual-report-2022.md

SIG cluster lifecycle annual report 2022
Fixes #7104
/cc @palnabarun 
/cc @vincepri 
/cc @neolit123 
/cc @justinsb 
/cc @CecileRobertMichon

SIG cluster lifecycle annual report 2022

---

sig-api-machinery/annual-report-2022.md

Fixes https://github.com/kubernetes/community/issues/7097
/assign @fedebongio 

Add API Machinery Annual Report

---

communication/slack-config/channels.yaml

This is to discuss issues about the new plugin that we've created.
cc @alexzielenski @eddycharly

Add kubectl-validate channel

---

sig-testing/annual-report-2022.md

Initial draft for the 2022 sig-testing report, to be fleshed out by leads + members next week.
Fixes #7117

sig-testing annual-report-2022.md

---

contributors/devel/sig-architecture/api-conventions.md

xref https://github.com/kubernetes/kubernetes/pull/117742#issuecomment-1548147525
cc @kubernetes/api-reviewers 
/cc @thockin @smarterclayton

Document short-names and categories

---

sig-cli/annual-report-2022.md

Add SIG CLI Annual Report 2022

---

communication/slack-config/users.yaml

added users from kubestellar-devs

---

communication/slack-config/channels.yaml

changes to the ownership of kcp have required the KubeStellar (fka kcp-edge) community to establish our own slack channel, mailing list, cicd, and other items that were once shared between kcp and KubeStellar (fka kcp-edge).
Fixes #

request to add kubestellar-dev channel

---

sig-scheduling/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4200

sig-scheduling: Remove kube-batch subproject

---

icons/tools/rasterize.sh

Fixes https://github.com/kubernetes/community/issues/7320

cleanup containers after use (post execution of icon rasterize.sh script), fix spacing

---

mentoring/programs/google-season-of-docs.md

This PR solves the problem of broken links
Fixes #

docs: update google-season-of-docs resolving broken links

---

committee-steering/governance/sig-governance.md
communication/calendar-guidelines.md
communication/contributor-comms/storytelling-resources/event-checklist.md
communication/contributor-comms/storytelling-resources/multichannel-communications.md
events/events-team/marketing/README.md
mentoring/programs/shadow-roles.md

Change remaining marketing-team names

---

sig-testing/README.md

fix published sig-testing intro talk link

---

sig-cluster-lifecycle/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4204

sig-cluster-lifecycle: add cluster-api-ipam-provider-in-cluster subproject

---

wg-data-protection/annual-report-2022.md

Data Protection WG 2022 Annual Report

---

committee-code-of-conduct/election.md

Fixes #7355
corrected the misspelled word

docs :Update election.md

---

sig-contributor-experience/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/4218
/assign @nikhita 

contribex: Add sigs-github-actions subproject

---

communication/slack-config/sig-release/usergroups.yaml
communication/slack-config/users.yaml

Part of https://github.com/kubernetes/sig-release/issues/2223
/assign @gracenng @leonardpahlke

Update release-team-leads slack group for 1.28 RT

---

generator/app.go

Currently, everytime the verify job is run, API calls are made to github to fetch kubernetes release information since verify calls generate first.
The issue with this is that everytime this runs in the CI, eventhough we only generate annual reports when ANNUAL_REPORT env is set, the API calls are made and if they are rate limited (since we don't use a token here), the job will fail without a legitimate reason.
An instance of this: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/community/7369/pull-community-verify/1671504152347283456
Part of: https://github.com/kubernetes/community/pull/7369
/hold 
/assign @Priyankasaggu11929

generator: Refactor to make github API calls only when needed

---

contributors/devel/sig-architecture/api_changes.md

updated link for In-place updates

---

sig-contributor-experience/surveys/multi_year_comparisons/README.md
sig-contributor-experience/surveys/multi_year_comparisons/multi_year_2019.ipynb

Fix typo in  multi_year_comparisons

---

communication/slack-config/channels.yaml

For discussion around new authentication features such as https://kep.k8s.io/3221

Add sig-auth-authorizers-dev slack channel

---

sig-auth/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4297

sig-auth: remove multi-tenancy subproject

---

communication/slack-config/channels.yaml

[Primaza](https://github.com/primaza/primaza) is a multi-cluster service consumption framework built around multi-tenancy.  For more information, please checkout [our documentation](https://www.primaza.io/).
Fixes #

Add public channel for discussing primaza

---

communication/slack-config/channels.yaml

Add #gophercloud Slack channel

---

sig-node/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4224

Update noderesourcetopology-api repo location

---

wg-policy/annual-report-2022.md

wg-policy annual community report

---

sig-multicluster/CONTRIBUTING.md
sig-multicluster/annual-report-2022.md

[Draft]
Updates the 2022 annual report for sig-mc

sig-multicluster 2022 annual report

---

communication/slack-config/channels.yaml

Related to:
- https://github.com/kubernetes/community/issues/7259

restore wg-lts slack channel

---

contributors/guide/README.md

added the missing letter
**Which issue(s) this PR fixes**: #7377

updated readme

---

contributors/devel/sig-scalability/kubemark-setup-guide.md

build kubemark static binary with `make all WHAT=cmd/kubemark`
Fixes #

improve kubemark binary building

---

communication/slack-config/sig-node/config.yaml

[sig-node] mothball old scrub slack channel and create a fresh one for CI subgroup

---

sig-cloud-provider/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4259

sig-cloud-provider: Add equinix-metal subproject

---

communication/contributor-comms/README.md

Adding myself as a Social Media Shadow (Contributor-Comms)

Adding myself as a Social Media Shadow

---

elections/steering/2023/candidate-pacoxu.md

add pacoxu bio as candidate for 2023 steering

---

elections/steering/2023/voters.yaml

Adding voter for 2023 Steering election.

Adding exception

---

communication/slack-config/channels.yaml

For discussion around KEPs such as https://kep.k8s.io/3257

Add sig-auth-certificates-dev slack channel

---

contributors/devel/running-locally.md

Update the incorrect links in contributors/devel/running-locally.md

---

elections/steering/2021/candidate-vincepri.md
elections/steering/2023/candidate-vincepri.md

Add candidate bio for Vince Prignano

---

elections/steering/2023/candidate-qedrakmar.md

Add steering 2023 candidate bio for Noah Abrahams

---

elections/steering/2023/candidate-soltysh.md

Add candidate bio for Maciej Szulik (soltysh)

---

communication/contributor-comms/OWNERS

Update contributor comms OWNERS

---

elections/steering/2023/candidate-pohly.md

Steering 2023 Candidate Bio for Patrick Ohly

---

elections/steering/2023/candidate-xmudrii.md

Add candidate bio for Marko Mudrinić (xmudrii)

---

elections/steering/2023/candidate-justaugustus.md

Fixes #7498
Election Officers:
/assign @kaslin @dims @bridgetkromhout

elections/steering/2023: Add Stephen Augustus (justaugustus) bio

---

elections/steering/2023/candidate-ameukam.md

Add bio for candidate Arnaud Meukam (ameukam)

---

elections/steering/2023/voters.yaml

Voting exceptions for steering election (and re-alphabetizing an earlier one).

Voting exceptions

---

elections/steering/2023/candidate-natalisucks.md

**Which issue(s) this PR fixes:**
Fixes #7503
Election Officers:
/assign @bridgetkromhout  @kaslin @dims

Add bio for 2023 Steering Election candidate Natali Vlatko (natalisucks)

---

elections/steering/2023/voters.yaml

Adding approved exceptions. (I also removed the redundant/unused comment section because the GitHub history for this file is a much more accurate way to look at changes for the file over time.)

Adding approved exceptions

---

OWNERS_ALIASES

Update to reflect changes in https://github.com/kubernetes/cloud-provider-openstack/pull/2318

Update cloud-provider-openstack maintainers

---

elections/code-of-conduct/2023/ballots.csv
elections/code-of-conduct/2023/results.md

Add 2023 CoCC election results

---

communication/contributor-comms/automation/announcement-guidelines.md

Fixes # N/A
Corrected image links with appropriate path and formatted in markdown.

Fixing automation page image links

---

communication/contributor-comms/role-handbooks/blog-coordinator.md

Added a clearer description of the activities expected from shadows.

Improve shadow requirements for Blogging Lead

---

elections/steering/2023/voters.yaml

Adding approved voter exception for the 2023 Steering election.
/cc @kaslin @dims

Adding approved voter exception

---

elections/steering/2023/voters.yaml

Creating a pull request accepting @nitishfy's exception request to vote in the 2023 Kubernetes Steering election. Thank you for your contributions to the community and interest in participating in the election, @nitishfy!

Add exception to voters.yaml

---

communication/contributor-comms/role-handbooks/Subproject-Lead.md

Updating requirements both of the subproject lead, and of a strong shadow candidate.

Update Subproject-Lead.md Shadow Requirements

---

communication/slack-config/channels.yaml

This channel is archived in favor of https://cloud-native.slack.com/archives/C05GETJ2NP7

Archive kpack channel

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

Fixes #
We need to update our group to reflect our current members

Update devfile-devs group

---

events/awards/award-recipients/2019-award-recipients.md

My first name is Wei. Blame for my GH handle for causing confusion...
cc @reylejano

typo: exchange Wei Huang's first/last name

---

communication/slack-config/channels.yaml

Discussed at the SIG Contribex meeting on 27 September 2023.
/assign @nimbinatus 

patch(channel): archive outdated sig-contribex-meetings channel

---

sig-contributor-experience/README.md
sigs.yaml

/assign @kaslin 
ref: https://github.com/kubernetes/org/issues/4481

sig-contribex: remove contributor-tweets repo

---

hack/.spelling_failures

Fixes https://github.com/kubernetes/community/pull/7444

spellcheck: exclude all voters.yaml

---

elections/steering/2023/ballots.csv
elections/steering/2023/results.md

Adding results for 2023 Steering election.
/cc @dims @kaslin

Adding results for 2023 Steering election

---

sig-cluster-lifecycle/README.md
sigs.yaml

Add contact info for Cluster API Add-on Provider for Helm

---

committee-code-of-conduct/README.md

Update the custom content for the CoCC Committee Readme as part of #7482

Update custom content for CoCC Readme

---

sig-network/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/3875
/assign @shaneutt

sig-network: add blixt subproject

---

OWNERS_ALIASES
sig-network/README.md
sigs.yaml

Part of resolving #7572.
/cc @thockin @MikeZappa87 @danwinship

Add Dan Winship as SIG Network Technical Lead

---

contributors/devel/sig-architecture/feature-gates.md

@liggitt 
xref https://github.com/kubernetes/kubernetes/pull/120954

Update feature-gates doc re. 'Deprecated'

---

OWNERS_ALIASES
sig-k8s-infra/README.md
sigs.yaml

See: https://groups.google.com/d/msgid/kubernetes-sig-k8s-infra/CAO_RewZxTk_c-hja-cYQGC8gjh3zekReJQzruqmsC0ktBL6a%3Dg%40mail.gmail.com

rotate K8s Infra Leadership

---

committee-steering/README.md
sigs.yaml

The meeting time has moved to the first Wednesday of every month at 8am PT

Update monthly steering meeting time

---

communication/slack-config/channels.yaml

We have archived the lokomotive repository already, more info here:
https://github.com/kinvolk/lokomotive/issues/1582#issuecomment-1170123280
I've talked with the Lokomotive team at Microsoft and we decided to archive the slack channel too, as we don't plan to continue developing the project.
cc @iaguis @vbatts 
---
Fixes #

slack-config: Archive lokomotive channel

---

community-membership.md

Fixes two small stale/dead links on subproject governance.

Update stale subproject governance links

---

sig-scalability/README.md

Add perfdash links and fix testgrid links for Sig-scalability

---

contributors/guide/first-contribution.md

Builds are failing because the community site doesn't support the note tag. Fixes 79b1bb59a.

first contribution: avoid node block

---

communication/slack-config/sig-node/usergroups.yaml
communication/slack-config/users.yaml

Add Atanas and myself to the DRA user group.
**Which issue(s) this PR fixes**: None-just user addition.

Add 2 users to the dra-dev group

---

communication/README.md
communication/contributor-comms/blogging-resources/blog-guidelines.md
sig-docs/blog-subproject/README.md

Revise https://github.com/kubernetes/community/blob/master/sig-docs/blog-subproject/README.md and some associated pages.
Notification to: @mrbobbytables @onlydole @nate-double-u

Update details around blog contribution

---

sig-architecture/production-readiness.md

An attempt to flesh out the expectations from PRR shadows to make a good application to become an approver.  This will  help the shadows select PRs that expand their experience.
/assign @johnbelamaric @wojtek-t 
/cc @enj @logicalhan @jpbetz @cici37 @jeremyrickard @tallclair @BenTheElder @spiffxp @andrewsykim

add details for becoming a PRR approver

---

sig-autoscaling/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/4562
/assign @kubernetes/sig-autoscaling-leads 
/sig autoscaling

sig-autoscaling: add karpenter subproject

---

communication/slack-config/channels.yaml

We've [renamed our project](https://bpfman.io/blog/2023/11/23/bpfd-becomes-bpfman/)

slack-config: Rename bpfd to bpfman

---

sig-architecture/production-readiness.md

Follow up from https://github.com/kubernetes/community/pull/7305/files#r1204289399
/assign @johnbelamaric @deads2k

Clarify PRR approvers criteria

---

OWNERS_ALIASES
sig-network/README.md
sigs.yaml

Ref: https://github.com/kubernetes/community/issues/7650

add aojea as sig-network TL

---

contributors/devel/sig-testing/flaky-tests.md

- KCSEU23 - The Art of Deflaking Kubernetes Tests
https://sched.co/1LXGm for the schedule 
https://www.youtube.com/watch?v=wyMyQdvg1Qw for the video recording

use the video link of kcseu deflaking

---

OWNERS_ALIASES
sig-docs/README.md
sig-docs/netlify-access.md
sigs.yaml

update tech leads for sig-docs

---

events/events-team/registration/README.md

This PR fixes small typos in the [Registration Handbook](https://github.com/kubernetes/community/blob/master/events/events-team/registration/README.md).
cc @reylejano @savitharaghunathan @Namanl2001

Fix typos in the registration handbook

---

sig-testing/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/4654
/assign @kubernetes/sig-testing-leads 
for acks
/assign @Priyankasaggu11929 
for approval
/hold

sig-testing: add hydrophone repo

---

sig-network/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/4640

sig network: add subproject node-ipam-controller

---

sig-network/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4673

sig-network: Add knftables subproject

---

communication/slack-config/channels.yaml

Adding the #okd-dev slack channel for OKD  (upstream of OpenShift OCP)

added okd-dev

---

communication/slack-config/channels.yaml

New channel is needed for collaboration
Fixes #

Add Capi Proxmox Channel

---

OWNERS_ALIASES
sig-docs/README.md
sigs.yaml

I am stepping down from my SIG Docs Technical Lead role to make room for new contributors and maintainers. Thank you ALL for a wonderful experience, and I promise not to go TOO far :smile:

Move onlydole to emeritus for SIG Docs Tech Lead

---

CONTRIBUTING.md

Please forgive my nitpicking, but this apostrophe was making me crazy.

Remove incorrect apostrophe

---

communication/slack-config/sig-node/config.yaml

/sig node
We keep improving Sidecar feature and need a Slack channel for discussions.

Sidecar WG slack channel

---

committee-steering/README.md
sigs.yaml

follow up on migrating the funding repo requests to the steering repo

steering: remove funding repo

---

sig-etcd/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4754

sig-etcd: Add auger subproject

---

sig-cli/README.md
sigs.yaml

This PR fixes the company info for @koba1t.
/sig cli
/assign @koba1t
/approve

SIG CLI: Update company for Yugo

---

Makefile
generator/README.md
hack/verify.sh

Containerized generation wasn't working under podman. This updates it to work under both :)

Fix containerized generation

---

communication/slack-config/sig-security/config.yaml

Adding a channel for the etcd self assessment
Fixes #

Update config.yaml to include a new channel for the etcd security self assessment

---

sig-apps/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/4737
/assign @kubernetes/sig-apps-leads

sig-apps: add lws subproject

---

github-management/subproject-site-requests.md

Updates netlify subproject site request details with correct DNS CNAME destination

Update netlify DNS request details

---

github-management/org-owners-guide.md

Updates the docs after running this recently

Update repo creation instructions

---

sig-testing/charter.md

Add the definition of the testing strategy and guidelines to the charter and clarify that the testing is a responsability of each SIG
Fixes #

Update sig testing charter.md

---

contributors/guide/help-wanted.md

Fixes the link to the suggestions section within `help-wanted.md` .
Fixes #

docs: Fix suggestions link in help-wanted.md

---

communication/slack-config/channels.yaml

For discussions around:
https://github.com/kubernetes/enhancements/issues/2339 https://github.com/kubernetes/enhancements/issues/4192
/assign jpbetz

Add sig-api-machinery-storageversion-dev channel

---

contributors/guide/coding-conventions.md

This PR updates the links in coding-conventions.md
Fixes #

coding-conventions: update links

---

contributors/guide/first-contribution.md

This PR add SIG Node link in first-contribution.md

first-contribution: add sig-node link

---

OWNERS_ALIASES
sig-cluster-lifecycle/README.md
sigs.yaml

I recently stepped into a new role and am no longer able to fulfill my duties as SIG Tech Lead. After discussing this with @vincepri @fabriziopandini @neolit123 @justinsb, I've decided to step down from the Tech Lead role for the time being. I still plan to be involved in the community and hope to be able to contribute to other SIGs as well in the future.
Fixes #

Remove myself as SIG Cluster Lifecycle TL

---

events/awards/playbook.md

As part of the contributor awards at an event, the contributor site needs to be updated. This is currently missing from the playbook

docs: update the checklist on the event awards playbook

---

events/awards/playbook.md
events/events-team/events-lead.md

Following the EU contributor summit, there are some updates that will need to be made to the various handbooks. This is the first of those

docs: update events lead handbook

---

sig-scheduling/CONTRIBUTING.md

I revise from reflect.Equal to reflect.DeepEqual
Fixes #

revise from reflect.Equal to reflect.DeepEqual

---

sig-cloud-provider/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4774
/assign @elmiko @bridgetkromhout

sig-cloud-provider: remove baiducloud project

---

wg-data-protection/annual-report-2023.md

Update DP WG annual report 2023

---

.github/ISSUE_TEMPLATE/leadership-change.yml

Thinking of where to put WG Serving meeting recordings

Added YouTube list creation in the list of action items

---

sig-auth/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4902

sig-auth: Add secrets-store-sync-controller subproject

---

communication/slack-config/channels.yaml

See https://github.com/kubernetes/community/pull/7823
/sig apps
I hope to get the slack channel going to simplify collaboration ahead of the official wg approval.

wg-serving slack channel

---

communication/moderators.md
communication/slack-config/usergroups.yaml

Just cleaning up the list of moderators. I added a section for emergency or backup admins that have access, but don't really participate on a regular basis.
/hold
/assign @kaslin @palnabarun

Update youtube admin list

---

sig-node/annual-report-2023.md

/sig node
/assign @mrunalp 
Relates to #7777

SIG Node annual report 2023

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

This PR updates the slack user groups for the new Cluster API release v1.7 team.

Update capi v1.8 release team members

---

sig-docs/annual-report-2023.md

2023 Annual Report: SIG Docs
Chairs: @natalisucks @divya-mohan0209 @reylejano
Liaison: @justaugustus
Fixes #7771
/assign @justaugustus 
/sig docs

SIG Docs Annual Report 2023

---

sig-cli/annual-report-2023.md

Add SIG CLI Annual Report 2023

---

sig-cli/annual-report-2023.md

/cc @soltysh @eddiezane 
it seems to be a problem of the generator.

Fix link sig-cli annual-report-2023.md

---

wg-batch/charter.md

Fix typos at wg-batch charter

---

sig-autoscaling/annual-report-2023.md

SIG Autoscaling 2023 Report

---

sig-node/annual-report-2023.md

fix link in sig-node 2023 annual report

---

sig-multicluster/CONTRIBUTING.md

Update CONTRIBUTING.md for SIG-MC as part of 2023 annual report operations

Update CONTRIBUTING.md for SIG-MC

---

sig-multicluster/README.md
sigs.yaml

Fix typo in sig MC teams as part of 2023 annual report operations

Fix typo in sig MC teams

---

wg-serving/README.md

wg-serving: add mention to workstreams

---

wg-structured-logging/annual-report-2023.md

2023 Annual Report: WG Structured Logging

---

wg-serving/README.md

/cc @SergeyKanzhelev @ArangoGutierrez

wg-serving: add link to orchestration workstream and minor edits

---

sigs.yaml
wg-serving/README.md

/cc @SergeyKanzhelev @ArangoGutierrez

wg-serving: add link to K8s WG Serving playlist

---

communication/slack-config/channels.yaml

This PR is to create a new Slack channel for the [Lula](https://lula.dev) project. Lula is a compliance controller designed for Kubernetes. It will be helpful for the maintainers to have somewhere public to collaborate :)

add slack channel for lula project

---

sig-scalability/annual-report-2023.md

FYI - @kubernetes/sig-scalability-leads @wojtek-t @marseel 
/cc @mrbobbytables

2023 annual report for SIG scalability

---

sig-instrumentation/annual-report-2023.md

Fixes: #7773
Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>

Prep SIG Instrumentation Annual Report

---

sig-windows/annual-report-2023.md

SIG Windows Annual report 2023

---

sig-cluster-lifecycle/annual-report-2023.md

Fixes https://github.com/kubernetes/community/issues/7769

sig-cluster-lifecycle: add annual report for 2023

---

wg-serving/OWNERS

/wg serving 
so we can edit our readme file easier

OWNERS for WG Serving

---

sig-etcd/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4908

sig-etcd: add etcd-manager subproject

---

wg-serving/README.md

added instructions on how to deal with the meetings

---

wg-serving/README.md

cc @Jeffwan @SergeyKanzhelev @ArangoGutierrez

wg-serving: add multi-host/multi-node workstream link

---

sig-architecture/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/4706
/area github-repo

sig-arch: Add verify-conformance repo

---

wg-batch/annual-report-2023.md

Fixes https://github.com/kubernetes/community/issues/7787
/cc @swatisehgal @alculquicondor @mwielgus 
/hold 
for approvals

WG Batch Annual report 2023

---

sig-apps/annual-report-2023.md

Fixes https://github.com/kubernetes/community/issues/7763
/cc @janetkuo @kow3ns 
/hold
for approvals

SIG Apps Annual report 2023

---

events/events-team/README.md

The event team readme was super out of date. Updating it throughout.

Updating the event-team README.

---

sig-contributor-experience/annual-report-2023.md

Adding SIG Contributor Experience annual report for 2023
Fixes https://github.com/kubernetes/community/issues/7770
cc: @kubernetes/sig-contributor-experience-leads

sig-contribex: annual report 2023

---

icons/README.md

Fixes #7905 
Added location for Kubernetes Icon it self in https://github.com/kubernetes/community/tree/master/icons README.md.

Add location for Kubernetes Icon it self

---

sig-network/annual-report-2023.md

SIG Network 2023 annual report
/assign @thockin @shaneutt @MikeZappa87 @danwinship @aojea 
Fixes #7776

update sig-network 2023 report

---

sig-docs/README.md
sigs.yaml

- Fix broken link in sig-docs/README.md

Fix broken link in sig-docs/README.md

---

sig-testing/annual-report-2023.md

2023 sig-testing annual report
Fixes #7783
initial draft
/sig testing
/area annual-reports

sig-testing: annual report 2023

---

sig-scheduling/annual-report-2023.md

sig-scheduling 2023 update

---

communication/moderators.md
communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

N/A
@chadmcrowell has a long history of working with YouTube; adding Chad will help spread the load on the already busy people that are YouTube Admins

Adding new YouTube Admin Chad M. Crowell

---

sig-architecture/README.md
sig-network/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/5072
ref: https://github.com/kubernetes/org/issues/4997
ref: https://github.com/kubernetes/org/issues/4996

Add repos for wg-serving, multi-network subprojects

---

contributors/guide/contributor-cheatsheet/README-ja.md

Fixes #
https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-ja.md

Corrected URL destination

---

elections/steering/2024/candidate-saschagrunert.md

Fixes https://github.com/kubernetes/community/issues/8015

Add candidate profile for saschagrunert

---

elections/steering/2024/candidate-aojea.md

add aojea candidate proposal

---

elections/steering/2024/candidate-bentheelder.md

2024 steering election: add bentheelder candidate bio

---

sig-node/sig-node-contributor-ladder.md

emeritus approver

---

communication/slack-config/channels.yaml

For conversations concerning the projects of https://github.com/reconcilerio
I have read https://www.kubernetes.dev/docs/comms/slack/#requesting-a-channel. 😄

Add channel #reconcilerio

---

generator/.gitattributes
generator/annual-report/sig_report.tmpl

- Wrapping code into comments
- ensures that files like .sh, .md, and .tmpl always use LF, regardless of the operating system. 
Fixes #

Fix KEP listing for annual report 

---

elections/steering/2024/candidate-xmudrii.md

Add candidate bio for xmudrii for Steering 2024 elections

---

elections/steering/2024/candidate-katcosgrove.md

Add candidate bio for Kat Cosgrove

---

elections/steering/2024/candidate-natalisucks.md

Candidate @natalisucks is traveling with very limited internet for the entire nominations period, so she reached out and asked the election officers to submit this PR on her behalf. The content is unmodified from what she provided.
Fixes https://github.com/kubernetes/community/issues/8025
/assign @Priyankasaggu11929

Adding bio for natalisucks: K8s Steering election 2024

---

elections/steering/2024/candidate-palnabarun.md

Fixes #8041
/cc @bridgetkromhout @Priyankasaggu11929 

Steering Elections 2024: Add candidate bio for palnabarun

---

sigs.yaml
wg-etcd-operator/README.md

First meeting recording has now been uploaded and playlist created for future meetings.
cc @ahrtr,@jmhbnz,@hakman,@jberkus,@justinsb

Add meeting recordings url for wg-etcd-operator

---

sig-apps/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/5106

sig-apps: Add llm-instance-gateway repo

---

elections/steering/2024/voters.yaml

PR adds following voters from approved exception requests, as of Sept 10, 2024.
@ArvindParekh 
/assign @bridgetkromhout @cblecker
/hold
for review/approval from Election Officers.

[steering 2024] add voters from approved exception request - sept 10

---

contributors/devel/sig-node/e2e-node-tests.md

xref https://github.com/kubernetes/k8s.io/issues/1527

Update references for deprecated kubernetes-node-e2e-images

---

communication/slack-config/usergroups.yaml
communication/slack-config/users.yaml

Fixes N/A
This PR adds sandeepkanabar to the slack-config for using the slack-post-message (aka Announcebot) in K8s Slack

Adding sandeepkanabar to Slack Announcebot

---

hack/verify-generated-docs.sh

/kind cleanup
Context: https://kubernetes.slack.com/archives/C1TU9EB9S/p1714768291414659

verify that files were not removed without changing sig.yaml

---

sigs.yaml
wg-device-management/README.md

Update meeting recordings link for wg-device-management

---

events/events-team/operations/volunteers.md

Additional volunteer instructions; needed for volunteer push.

Add more to volunteers instructions

---

communication/kubernetesio-x-guidelines.md

A Guideline for the usage of the Kubernetes X account.
Fixes #8059

kubernetesio x guidelines

---

communication/contributor-comms/OWNERS

Moving AvineshTripathi to emeritus
Fixes #

Moving AvineshTripathi to emeritus

---

communication/slack-config/usergroups.yaml

Updating contributor-comms team members

---

contributors/devel/sig-release/cherry-picks.md

Fixes https://github.com/kubernetes/community/issues/7634
/hold for review
/sig release
/cc @dims @jeremyrickard

Clarify cherry-pick candidates

---

contributors/devel/sig-architecture/feature-gates.md

Partially addresses https://github.com/kubernetes/community/issues/8082 for kubernetes/community

Update feature gate documentation for compatibility version

---

contributors/devel/sig-architecture/feature-gates.md

Addresses remaining comments in https://github.com/kubernetes/community/pull/8087#pullrequestreview-2396605525.
/assign @jpbetz @thockin

Update feature gate documentation for compatibility version - fixups

---

sig-scalability/README.md

No longer involved in SIG Scalability
@wojtek-t

Remove myself from sig-scalability README.md

---

sig-network/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/5228
cc: @kubernetes/owners 

sig-network: add cni-dra-driver repo

---

sig-node/CONTRIBUTING.md

/sig node
as we are getting more chairs, need to share instructions

instructions on how to uploade videos for SIG Node

---

sigs.yaml

Add my email to sigs.yaml

---

sigs.yaml

add aojea email to sigs.yaml

---

sigs.yaml

xref https://groups.google.com/a/kubernetes.io/g/leads/c/3A2d1_onI3o
cc @BenTheElder

Add jbelamaric email

---

sigs.yaml

Add dims' email to sigs.yaml

---

sigs.yaml

Ref: https://groups.google.com/a/kubernetes.io/g/leads/c/3A2d1_onI3o

Add email to sigs.yaml

---

sigs.yaml

xref https://groups.google.com/a/kubernetes.io/g/leads/c/3A2d1_onI3o
cc @BenTheElder

Add mengjiao-liu' email to sigs.yaml

---

sigs.yaml

Add SIG CLI leads' emails to sigs.yaml
@soltysh @eddiezane

Add sig-cli lead emails to sigs.yaml

---

sig-scheduling/README.md
sigs.yaml

Ref https://github.com/kubernetes-sigs/kueue/pull/3296

Step down as TL for Kueue and add mimowo

---

sigs.yaml

Added SIG API-Machinery leads' emails to sigs.yaml
cc @deads2k @jpbetz @fedebongio

Add sig-api-machinery emails in sigs.yaml

---

sigs.yaml

Refer to https://groups.google.com/a/kubernetes.io/g/leads/c/3A2d1_onI3o
cc @hakman @jberkus @jmhbnz @justinsb

Add emails for wg-etcd-operator leads on sigs list

---

sigs.yaml

FYI @ahg-g @Huang-Wei @tenzen-y 

Add emails for SIG Scheduling owners

---

sigs.yaml

/cc @thockin @shaneutt @MikeZappa87 @aojea 
(though Antonio's email was already there; it's your google address if you care)

add emails for sig-network leadership

---

sig-network/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/5280

sig-network: Add ingate subproject

---

sig-apps/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/5279
/assign @kubernetes/sig-apps-leads 

sig-apps: add kjob subproject

---

communication/moderators.md

**Hindi Category in Kubernetes Discussion**
Fixes #
IT Update details on Hindi Category in Kubernetes Discussion

Hindi Category in Kubernetes Discussion

---

.github/ISSUE_TEMPLATE/slack-request.yml
communication/slack-guidelines.md

Also, added some questions for the Slack Request template that we usually end up asking anyways.
/area slack-management
attn: @mrbobbytables @coderanger @jeefy

Updated some slack rules to match actual practice.

---

sigs.yaml

update steering emails

---

sigs.yaml

xref
- https://github.com/kubernetes/steering/issues/281
/assign @kubernetes/steering-committee

sig-cl: add lead emails

---

committee-steering/OWNERS

steering dir: only steering can approve

---

sigs.yaml

This is for https://github.com/kubernetes/steering/issues/281.
cc @saad-ali @msau42 @jsafrane

Add sig-storage leads emails

---

communication/slack-config/channels.yaml

Add kubernetes-hybrid-cloud slack channel
Link: https://github.com/kubernetes-hybrid-cloud

Add hybrid-cloud-users slack channel

---

sig-network/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/5299
cc: @kubernetes/owners 

sig-network: add nat64 repo to pod-networking sub-project

---

sigs.yaml

As per https://github.com/kubernetes/steering/issues/281
Fixes #

Add SIG-Multicluster lead emails

---

wg-policy/annual-report-2023.md

update wg-policy 2023 annual report

---

sig-multicluster/annual-report-2023.md

SIG-MC 2023 annual report update

---

sig-k8s-infra/README.md
sig-k8s-infra/charter.md
sigs.yaml

Follow-up of:
- https://github.com/kubernetes/k8s.io/pull/7783
Related to:
- https://github.com/kubernetes/k8s.io/issues/3205
Fixes #

sig-k8s-infra: Update mailing list

---

sig-cli/annual-report-2024.md

Fixes https://github.com/kubernetes/community/issues/8258

Add sig-cli annual report for 2024

---

sig-instrumentation/README.md
sigs.yaml

Issue https://github.com/kubernetes/community/issues/8264

Add sig-inst meeting recordings link

---

sigs.yaml

Wrong email address probably as a result of resolving conflicts between these two PRs: https://github.com/kubernetes/community/commit/b0dfc73f804a43fc62430a85f85ba8e9a70bc03e
and https://github.com/kubernetes/community/commit/c9e5901c1fe1ec3e16077bb98246c97962378be6
cc @alculquicondor @tenzen-y

Fix the email address for mimowo

---

wg-structured-logging/annual-report-2024.md

Fixes https://github.com/kubernetes/community/issues/8284
/assign @mengjiao-liu

wg-structured-logging: annual report 2024

---

communication/slack-config/channels.yaml

As suggested by @shaneutt.
/cc @ahg-g @danehans @Jeffwan @kfswain

Adding a #gateway-api-inference-extension Slack channel

---

sig-multicluster/README.md
sig-multicluster/annual-report-2024.md

Add the 2024 SIG-Multicluster report

---

sig-apps/annual-report-2024.md

Fixes https://github.com/kubernetes/community/issues/8254
/cc @janetkuo @kow3ns
/assign @aojea 
/hold
for approvals

SIG Apps Annual Report 2024

---

sig-instrumentation/README.md
sigs.yaml

Updates list of sub-projects under sig-instrumentation
Issue #https://github.com/kubernetes/community/issues/8264

Add zpages as subproject under sig-instrumentation

---

elections/code-of-conduct/2025/ballots.csv
elections/code-of-conduct/2025/results.md

Community announcement: https://groups.google.com/a/kubernetes.io/g/dev/c/B_LzpmUStUI/m/E90hPh0dAgAJ
cc: @kubernetes/steering-committee @kubernetes/code-of-conduct-committee 
/hold

elections/cocc: Add 2025 election results

---

sig-contributor-experience/README.md
sigs.yaml

Ref: https://github.com/kubernetes/org/issues/5397
/assign @kubernetes/sig-contributor-experience-leads

sig-contribex: remove subproject sigs-github-actions

---

liaisons.md
sigs.yaml
wg-device-management/README.md

Swap wg-device-management liaisons to avoid conflict of interest

---

sig-ui/annual-report-2024.md

2024 Annual Report: SIG UI

---

sig-auth/annual-report-2024.md

fixes https://github.com/kubernetes/community/issues/8256
/assign enj ritazh liggitt

sig-auth: 2024 annual report

---

sig-node/archive/README.md

Updated sig-node archive readme listing all years referencing new entries merged in https://github.com/kubernetes/community/pull/8244
/sig node
Fixes #

Updated sig-node archive readme listing all years.

---

sig-cloud-provider/annual-report-2024.md

adding more content to the initial report.
Fixes #8259

update SIG Cloud Provider 2024 annual report

---

sig-instrumentation/README.md
sigs.yaml

Updating the recordings link (again) to a new, more comprehensive playlist.

Update sig-instrumentation's meeting-recordings link

---

sig-scalability/annual-report-2024.md

sig scalability annual report 2024

---

sig-security/annual-report-2024.md

Add completed SIG Security annual report 2024

---

sig-ui/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/5468

sig-ui: Add headlamp subproject

---

sig-docs/annual-report-2024.md

SIG Docs Annual Report 2024

---

sig-windows/annual-report-2024.md

SIG Windows Annual report 2024

---

sig-architecture/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/5498

Add maintainer-tools subproject

---

sig-release/README.md
sigs.yaml

This updates  my affiliation in the SIG lists.
Fixes # N/A

Update puerco's affiliation

---

sig-api-machinery/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/5519

api-machinery: add kube-api-linter subproject

---

sigs.yaml

Fixes #
based on https://github.com/kubernetes/k8s.io/blob/main/groups/wg-policy/groups.yaml
/hold
/assign @JimBugwadia @poonam-lamba @sudermanjr 
unblocks https://github.com/kubernetes/community/pull/8421

add wg-policy lead emails

---

sigs.yaml

based on https://github.com/kubernetes/k8s.io/blob/b3ca8e41c0ed8c11407a78abf555c99f5d3ecc92/groups/sig-ui/groups.yaml#L4
Fixes #
/hold
/cc @floreks @maciaszczykm @shu-mutou 
context:
https://groups.google.com/a/kubernetes.io/g/leads/c/3A2d1_onI3o

add sig ui lead emails

---

sigs.yaml

Fixes #
/hold
/assign @xmcqueen 
cc @michelle192837 @jbpratt 
context:
https://groups.google.com/a/kubernetes.io/g/leads/c/3A2d1_onI3o
based on https://github.com/kubernetes/k8s.io/blob/master/groups/sig-testing/groups.yaml#L21

add missing sig-testing lead email

---

sigs.yaml

Fixes #
/hold
/assign @marosset @claudiubelu @jsturtevant @knabben 
/cc @marosset 
context:
https://groups.google.com/a/kubernetes.io/g/leads/c/3A2d1_onI3o
based on: https://github.com/kubernetes/k8s.io/blob/main/groups/sig-windows/groups.yaml#L21

add missing sig windows emails

---

sigs.yaml

Fixes #
/assign @upodroid 
context:
https://groups.google.com/a/kubernetes.io/g/leads/c/3A2d1_onI3o
based on https://github.com/kubernetes/k8s.io/blob/main/groups/sig-k8s-infra/groups.yaml

add missing sig-k8s-infra email

---

sigs.yaml

based on https://github.com/kubernetes/k8s.io/blob/main/groups/wg-data-protection/groups.yaml
Fixes #
/assign @yuxiangqian
/cc @xing-yang 
unblocks #8421

add missing wg-data-protection email

---

sig-k8s-infra/annual-report-2024.md

SIG k8s Infra 2024 annual report

---

sig-auth/README.md
sigs.yaml

- Archive kubernetes-sigs/pspmigrator https://github.com/kubernetes/org/issues/5484
- Archive kubernetes-sigs/hierarchical-namespaces https://github.com/kubernetes/org/issues/5485

Archive kubernetes-sigs/pspmigrator and kubernetes-sigs/hierarchical-namespaces

---

sig-architecture/annual-report-2024.md

SIG Architecture 2024 annual report

---

OWNERS_ALIASES
sig-cloud-provider/README.md
sigs.yaml

Updated [sigs.yaml](https://git.k8s.io/community/sigs.yaml) and associated [generated files](https://git.k8s.io/community/generator) (ran make).
For https://github.com/kubernetes/community/issues/8457

Adding Joel Speed

---

contributors/guide/help-wanted.md

Based on discussion in today's SIG Contribex meeeting:
Fixes https://github.com/kubernetes/community/issues/8444
Also specifically clarifies the type of "further discussions" that should not be required (IE consensus is reached on the high level approach, discussion and help may be warranted for _implementation details, debugging, etc_)
I intend to send follow-ups to add go.k8s.io/good-first-issue and go.k8s.io/help-wanted searches, but they need fixing first.

relax help-wanted guidelines

---

communication/moderators.md

Remove Taylor Dolezal from the following lists:
* Slack
* Zoom

Remove Taylor Dolezal from moderators and administrators lists

---

contributors/devel/sig-architecture/api_changes.md

Describe ratcheting validation

---

communication/slack-migration-faq.md

This adds a FAQ to accompany the Slack service announcements to go out Monday morning.
Attn: @Priyankasaggu11929

Add FAQ for changes to Slack.

---

communication/slack-config/sig-node/config.yaml

Fixes https://github.com/kubernetes/community/issues/8497

slack-config: added channel sig-node-wranglers

---

communication/slack-migration-faq.md

Slack has extended our free Pro account, so updating blog post. Changes added to blog posts, updating FAQ as well.
Attn: @mfahlandt @Priyankasaggu11929 @palnabarun 
/area slack-management

Update the information on Slack.

---

communication/slack-config/channels.yaml

Due to the merge of https://github.com/kubernetes/community/pull/8515 we request for the AI Conformance WG the slack Channel as documented in https://github.com/kubernetes/community/tree/master/wg-ai-conformance 
#wg-ai-conformance

Add WG AI Conformance Slack Channel

---

sig-cluster-lifecycle/README.md
sigs.yaml

more information here:
- https://github.com/kubernetes/org/issues/5756
/cc @fabriziopandini
cc @vielmetti

sig-cl: remove capi provider packet subproject

---

sig-apps/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/5750
/assign @kubernetes/sig-apps-leads 

sig-apps: add agent-sandbox under application subproject

---

communication/slack-config/channels.yaml
sig-network/README.md
sig-network/charter.md
sigs.yaml

Ref https://github.com/kubernetes/org/issues/5807
Relates to https://github.com/kubernetes/org/pull/5821

chore: archive kubernetes-sigs/blixt

---

elections/steering/2025/candidate-katcosgrove.md

Fixes #8584
/assign @cblecker @npolshakova @sreeram-venkitesh

Adds candidate bio for Kat Cosgrove

---

elections/steering/2025/candidate-xmudrii.md

steering/2025: add candidate bio for xmudrii

---

wg-ai-conformance/README.md

@mfahlandt @ritazh @terrytangyuan

Add links to AI conformance definition repos

---

sig-cluster-lifecycle/README.md
sigs.yaml

ref: github.com/kubernetes/org/issues/5772, https://github.com/kubernetes/org/issues/5762
/assign @kubernetes/sig-cluster-lifecycle-leads 

sig-cluster-lifecycle: document minkube-os/preloads repos

---

sig-network/README.md
sigs.yaml

ref: https://github.com/kubernetes/org/issues/5848
/assign @kubernetes/sig-network-leads 

sig-network: document new wg-ai-gateway repo owners

---

elections/steering/2025/voters.yaml

This PR adds following voters from approved exception requests, as of October 5, 2025.
@arujjval 
@krol3 
@sharmarahul8222 
/assign @cblecker @npolshakova
/hold
for review and approval from Election Officers. Thanks!

[Steering 2025] Add voters from approved exception requests - Oct 5
